k8s-operatorhub/community-operators

operators/mongodb-atlas-kubernetes/1.4.1/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/1.4.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/1.4.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/1.4.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/1.4.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/1.4.1/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/1.4.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/1.4.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/1.4.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/1.4.1/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/1.4.1/tests/scorecard/config.yaml

Signed-off-by: Helder Santana <helder.santana@mongodb.com>
--

operator mongodb-atlas-kubernetes (1.4.1)

---

operators/elastic-cloud-eck/2.5.0/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.5.0/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.5.0/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.5.0/elastic-cloud-eck.v2.5.0.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.5.0/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.5.0/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.5.0/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.5.0/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.5.0/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml

Updates ECK Elasticsearch operator to the latest version 2.5.0
Signed-off-by: naemono <mmontg1@gmail.com>

operator elastic-cloud-eck (2.5.0)

---

operators/keda/2.8.1/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.8.1/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.8.1/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.8.1/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.8.1/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.8.1/manifests/keda.v2.8.1.clusterserviceversion.yaml
operators/keda/2.8.1/metadata/annotations.yaml

Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>
--

operator keda (2.8.1)

---

operators/intel-device-plugins-operator/0.25.0/bundle.Dockerfile
operators/intel-device-plugins-operator/0.25.0/manifests/deviceplugin.intel.com_dlbdeviceplugins.yaml
operators/intel-device-plugins-operator/0.25.0/manifests/deviceplugin.intel.com_dsadeviceplugins.yaml
operators/intel-device-plugins-operator/0.25.0/manifests/deviceplugin.intel.com_fpgadeviceplugins.yaml
operators/intel-device-plugins-operator/0.25.0/manifests/deviceplugin.intel.com_gpudeviceplugins.yaml
operators/intel-device-plugins-operator/0.25.0/manifests/deviceplugin.intel.com_iaadeviceplugins.yaml
operators/intel-device-plugins-operator/0.25.0/manifests/deviceplugin.intel.com_qatdeviceplugins.yaml
operators/intel-device-plugins-operator/0.25.0/manifests/deviceplugin.intel.com_sgxdeviceplugins.yaml
operators/intel-device-plugins-operator/0.25.0/manifests/fpga.intel.com_acceleratorfunctions.yaml
operators/intel-device-plugins-operator/0.25.0/manifests/fpga.intel.com_fpgaregions.yaml
operators/intel-device-plugins-operator/0.25.0/manifests/intel-device-plugins-operator.clusterserviceversion.yaml
operators/intel-device-plugins-operator/0.25.0/metadata/annotations.yaml
operators/intel-device-plugins-operator/0.25.0/tests/scorecard/config.yaml

Signed-off-by: Hyeongju Johannes Lee <hyeongju.lee@intel.com>
--

operator intel-device-plugins-operator (0.25.0)

---

operators/mondoo-operator/1.8.0/k8s.mondoo.com_mondooauditconfigs.yaml
operators/mondoo-operator/1.8.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
operators/mondoo-operator/1.8.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
operators/mondoo-operator/1.8.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mondoo-operator/1.8.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/mondoo-operator/1.8.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
operators/mondoo-operator/1.8.0/mondoo-operator-manager-config_v1_configmap.yaml
operators/mondoo-operator/1.8.0/mondoo-operator-webhook_v1_serviceaccount.yaml
operators/mondoo-operator/1.8.0/mondoo-operator.clusterserviceversion.yaml
operators/mondoo-operator/mondoo-operator.package.yaml

operator mondoo-operator (1.8.0)

---

operators/kiali/1.59.0/bundle.Dockerfile
operators/kiali/1.59.0/manifests/kiali.crd.yaml
operators/kiali/1.59.0/manifests/kiali.v1.59.0.clusterserviceversion.yaml
operators/kiali/1.59.0/metadata/annotations.yaml

operator kiali (1.59.0)

---

operators/knative-operator/1.8.1/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.8.1/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.8.1/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.8.1/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.8.1/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.8.1/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.8.1/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.8.1/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.8.1/manifests/knative-operator.v1.8.1.clusterserviceversion.yaml
operators/knative-operator/1.8.1/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.8.1/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.8.1/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.8.1/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.8.1/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.8.1/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.8.1/metadata/annotations.yaml
operators/knative-operator/1.8.1/tests/scorecard/config.yaml

operator knative-operator (1.8.1)

---

operators/pulp-operator/1.0.0-alpha.2/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.0.0-alpha.2/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.0.0-alpha.2/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-alpha.2/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-alpha.2/manifests/pulp-operator.1.0.0-alpha.2.clusterserviceversion.yaml
operators/pulp-operator/1.0.0-alpha.2/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.0.0-alpha.2/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.0.0-alpha.2/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.0.0-alpha.2/metadata/annotations.yaml
operators/pulp-operator/1.0.0-alpha.2/tests/scorecard/config.yaml

operator pulp-operator (1.0.0-alpha.2)

---

operators/gitlab-operator-kubernetes/0.13.3/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.13.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.13.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.13.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.13.3/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.13.3/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.13.3/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.13.3)

---

operators/instana-agent-operator/2.0.7/manifests/controller-manager-metrics-service_v1_service.yaml
operators/instana-agent-operator/2.0.7/manifests/instana-agent-operator.clusterserviceversion.yaml
operators/instana-agent-operator/2.0.7/manifests/instana.io_agents.yaml
operators/instana-agent-operator/2.0.7/manifests/manager-config_v1_configmap.yaml
operators/instana-agent-operator/2.0.7/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
operators/instana-agent-operator/2.0.7/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/instana-agent-operator/2.0.7/manifests/webhook-service_v1_service.yaml
operators/instana-agent-operator/2.0.7/metadata/annotations.yaml
operators/instana-agent-operator/2.0.7/metadata/dependencies.yaml
operators/instana-agent-operator/2.0.7/tests/scorecard/config.yaml

operator instana-agent-operator (2.0.7)

---

operators/cluster-aas-operator/0.0.1/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml
operators/cluster-aas-operator/0.0.1/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml
operators/cluster-aas-operator/0.0.1/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cluster-aas-operator/0.0.1/manifests/cluster-aas-operator-webhook-service_v1_service.yaml
operators/cluster-aas-operator/0.0.1/manifests/cluster-aas-operator.clusterserviceversion.yaml
operators/cluster-aas-operator/0.0.1/manifests/cluster_templates_user_role.yaml
operators/cluster-aas-operator/0.0.1/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml
operators/cluster-aas-operator/0.0.1/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml
operators/cluster-aas-operator/0.0.1/manifests/clustertemplate.openshift.io_clustertemplates.yaml
operators/cluster-aas-operator/0.0.1/metadata/annotations.yaml
operators/cluster-aas-operator/0.0.1/metadata/dependencies.yaml
operators/cluster-aas-operator/0.0.1/tests/scorecard/config.yaml
operators/cluster-aas-operator/ci.yaml

Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
--

operator [N] [CI] cluster-aas-operator (0.0.1)

---

operators/trivy-operator/0.6.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.6.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.6.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.6.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.6.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.6.0/trivy-operator.v0.6.0.clusterserviceversion.yaml
operators/trivy-operator/0.6.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.6.0)

---

operators/camel-k/1.10.3/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/1.10.3/manifests/camel-k.v1.10.3.clusterserviceversion.yaml
operators/camel-k/1.10.3/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/1.10.3/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/1.10.3/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/1.10.3/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/1.10.3/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/1.10.3/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/1.10.3/metadata/annotations.yaml
operators/camel-k/1.10.3/tests/scorecard/config.yaml

operator camel-k (1.10.3)

---

operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmagents.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmalertmanagers.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmalerts.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmauths.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmclusters.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmnodescrapes.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmpodscrapes.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmprobes.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmrules.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmservicescrapes.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmsingles.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmstaticscrapes.yaml
operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmusers.yaml
operators/victoriametrics-operator/0.29.1/victoriametrics-operator.0.29.1.clusterserviceversion.yaml
operators/victoriametrics-operator/victoriametrics-operator.package.yaml

operator victoriametrics-operator (0.29.1)

---

operators/mondoo-operator/1.8.1/k8s.mondoo.com_mondooauditconfigs.yaml
operators/mondoo-operator/1.8.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
operators/mondoo-operator/1.8.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
operators/mondoo-operator/1.8.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mondoo-operator/1.8.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/mondoo-operator/1.8.1/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
operators/mondoo-operator/1.8.1/mondoo-operator-manager-config_v1_configmap.yaml
operators/mondoo-operator/1.8.1/mondoo-operator-webhook_v1_serviceaccount.yaml
operators/mondoo-operator/1.8.1/mondoo-operator.clusterserviceversion.yaml
operators/mondoo-operator/mondoo-operator.package.yaml

operator mondoo-operator (1.8.1)

---

operators/cryostat-operator/2.2.0/Dockerfile
operators/cryostat-operator/2.2.0/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.2.0/manifests/cryostat-operator-manager-config_v1_configmap.yaml
operators/cryostat-operator/2.2.0/manifests/cryostat-operator-oauth-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.2.0/manifests/cryostat-operator.clusterserviceversion.yaml
operators/cryostat-operator/2.2.0/manifests/operator.cryostat.io_cryostats.yaml
operators/cryostat-operator/2.2.0/metadata/annotations.yaml
operators/cryostat-operator/2.2.0/tests/scorecard/config.yaml

operator cryostat-operator (2.2.0)

---

operators/istio-workspace-operator/0.5.3/manifests/istio-workspace-operator.clusterserviceversion.yaml
operators/istio-workspace-operator/0.5.3/manifests/workspace.maistra.io_sessions.yaml
operators/istio-workspace-operator/0.5.3/metadata/annotations.yaml
operators/istio-workspace-operator/0.5.3/tests/scorecard/config.yaml

operator istio-workspace-operator (0.5.3)

---

operators/cloud-native-postgresql/1.18.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
operators/cloud-native-postgresql/1.18.0/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
operators/cloud-native-postgresql/1.18.0/manifests/postgresql-operator-webhook-service_v1_service.yaml
operators/cloud-native-postgresql/1.18.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
operators/cloud-native-postgresql/1.18.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
operators/cloud-native-postgresql/1.18.0/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
operators/cloud-native-postgresql/1.18.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
operators/cloud-native-postgresql/1.18.0/metadata/annotations.yaml
operators/cloud-native-postgresql/1.18.0/tests/scorecard/config.yaml

operator cloud-native-postgresql (1.18.0)

---

operators/cloud-native-postgresql/ci.yaml

Signed-off-by: Jonathan Gonzalez V <jonathan.abdiel@gmail.com>
--

operator [CI] cloud-native-postgresql

---

operators/cloud-native-postgresql/1.17.2/manifests/cloud-native-postgresql.clusterserviceversion.yaml
operators/cloud-native-postgresql/1.17.2/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
operators/cloud-native-postgresql/1.17.2/manifests/postgresql-operator-webhook-service_v1_service.yaml
operators/cloud-native-postgresql/1.17.2/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
operators/cloud-native-postgresql/1.17.2/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
operators/cloud-native-postgresql/1.17.2/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
operators/cloud-native-postgresql/1.17.2/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
operators/cloud-native-postgresql/1.17.2/metadata/annotations.yaml
operators/cloud-native-postgresql/1.17.2/tests/scorecard/config.yaml

Signed-off-by: John Long <john.long@enterprisedb.com>
--

operator cloud-native-postgresql (1.17.2)

---

operators/cloud-native-postgresql/1.16.4/manifests/cloud-native-postgresql.clusterserviceversion.yaml
operators/cloud-native-postgresql/1.16.4/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
operators/cloud-native-postgresql/1.16.4/manifests/postgresql-operator-webhook-service_v1_service.yaml
operators/cloud-native-postgresql/1.16.4/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
operators/cloud-native-postgresql/1.16.4/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
operators/cloud-native-postgresql/1.16.4/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
operators/cloud-native-postgresql/1.16.4/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
operators/cloud-native-postgresql/1.16.4/metadata/annotations.yaml
operators/cloud-native-postgresql/1.16.4/tests/scorecard/config.yaml

operator cloud-native-postgresql (1.16.4)

---

operators/ack-kinesis-controller/ci.yaml

- onboarding new ACK controller

operator [CI] ack-kinesis-controller

---

operators/pulp-operator/1.0.0-alpha.3/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.0.0-alpha.3/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.0.0-alpha.3/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-alpha.3/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-alpha.3/manifests/pulp-operator.1.0.0-alpha.3.clusterserviceversion.yaml
operators/pulp-operator/1.0.0-alpha.3/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.0.0-alpha.3/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.0.0-alpha.3/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.0.0-alpha.3/metadata/annotations.yaml
operators/pulp-operator/1.0.0-alpha.3/tests/scorecard/config.yaml

operator pulp-operator (1.0.0-alpha.3)

---

operators/opentelemetry-operator/0.62.1/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
operators/opentelemetry-operator/0.62.1/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/opentelemetry-operator/0.62.1/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
operators/opentelemetry-operator/0.62.1/manifests/opentelemetry-operator.clusterserviceversion.yaml
operators/opentelemetry-operator/0.62.1/manifests/opentelemetry.io_instrumentations.yaml
operators/opentelemetry-operator/0.62.1/manifests/opentelemetry.io_opentelemetrycollectors.yaml
operators/opentelemetry-operator/0.62.1/metadata/annotations.yaml
operators/opentelemetry-operator/0.62.1/tests/scorecard/config.yaml

Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>
--

operator opentelemetry-operator (0.62.1)

---

operators/searchpe-operator/4.1.0/manifests/searchpe-operator.clusterserviceversion.yaml

Signed-off-by: carlosthe19916 <2582866+carlosthe19916@users.noreply.github.com>
--

operator [N] searchpe-operator (4.1.0)

---

operators/awx-operator/1.0.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/1.0.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/1.0.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/1.0.0/manifests/awx-operator.v1.0.0.clusterserviceversion.yaml
operators/awx-operator/1.0.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/1.0.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/1.0.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/1.0.0/metadata/annotations.yaml
operators/awx-operator/1.0.0/tests/scorecard/config.yaml

operator awx-operator (1.0.0)

---

operators/verticadb-operator/1.8.0/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/1.8.0/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/1.8.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/1.8.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/1.8.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/1.8.0/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/1.8.0/metadata/annotations.yaml
operators/verticadb-operator/1.8.0/tests/scorecard/config.yaml

operator verticadb-operator (1.8.0)

---

operators/elastic-phenix-operator/1.2.0/elastic-phenix-operator.v1.2.0.clusterserviceversion.yaml
operators/elastic-phenix-operator/1.2.0/elasticindices.elastic.carrefour.com.crd.yaml
operators/elastic-phenix-operator/1.2.0/elastictemplates.elastic.carrefour.com.crd.yaml
operators/elastic-phenix-operator/ci.yaml
operators/elastic-phenix-operator/elastic-phenix-operator.package.yaml

operator [CI] elastic-phenix-operator (1.2.0)

---

operators/security-profiles-operator/0.6.0/bundle.Dockerfile
operators/security-profiles-operator/0.6.0/manifests/metrics-token_v1_secret.yaml
operators/security-profiles-operator/0.6.0/manifests/security-profiles-operator-profile_v1_configmap.yaml
operators/security-profiles-operator/0.6.0/manifests/security-profiles-operator.clusterserviceversion.yaml
operators/security-profiles-operator/0.6.0/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
operators/security-profiles-operator/0.6.0/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
operators/security-profiles-operator/0.6.0/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
operators/security-profiles-operator/0.6.0/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
operators/security-profiles-operator/0.6.0/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
operators/security-profiles-operator/0.6.0/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
operators/security-profiles-operator/0.6.0/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
operators/security-profiles-operator/0.6.0/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
operators/security-profiles-operator/0.6.0/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.6.0/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.6.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.6.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.6.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.6.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.6.0/manifests/spo-webhook_v1_serviceaccount.yaml
operators/security-profiles-operator/0.6.0/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.6.0/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.6.0/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.6.0/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.6.0/manifests/spod_v1_serviceaccount.yaml
operators/security-profiles-operator/0.6.0/metadata/annotations.yaml
operators/security-profiles-operator/0.6.0/tests/scorecard/config.yaml

Part of https://github.com/kubernetes-sigs/security-profiles-operator/issues/1308
--

operator security-profiles-operator (0.6.0)

---

operators/trivy-operator/0.7.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.0/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.0/trivy-operator.v0.7.0.clusterserviceversion.yaml
operators/trivy-operator/0.7.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.7.0)

---

operators/aerospike-kubernetes-operator/2.3.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/aerospike-kubernetes-operator/2.3.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/aerospike-kubernetes-operator/2.3.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml
operators/aerospike-kubernetes-operator/2.3.0/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml
operators/aerospike-kubernetes-operator/2.3.0/manifests/aerospike-operator-manager-config_v1_configmap.yaml
operators/aerospike-kubernetes-operator/2.3.0/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/aerospike-kubernetes-operator/2.3.0/manifests/aerospike-operator-webhook-service_v1_service.yaml
operators/aerospike-kubernetes-operator/2.3.0/manifests/asdb.aerospike.com_aerospikeclusters.yaml
operators/aerospike-kubernetes-operator/2.3.0/metadata/annotations.yaml
operators/aerospike-kubernetes-operator/2.3.0/tests/scorecard/config.yaml

Signed-off-by: Sudhanshu Ranjan <sudhanshu@aerospike.com>
--

operator aerospike-kubernetes-operator (2.3.0)

---

operators/trivy-operator/0.7.1/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.1/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.1/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.1/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.1/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.1/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.7.1/trivy-operator.v0.7.1.clusterserviceversion.yaml
operators/trivy-operator/0.7.1/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.7.1)

---

operators/mondoo-operator/1.9.0/k8s.mondoo.com_mondooauditconfigs.yaml
operators/mondoo-operator/1.9.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
operators/mondoo-operator/1.9.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
operators/mondoo-operator/1.9.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mondoo-operator/1.9.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/mondoo-operator/1.9.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
operators/mondoo-operator/1.9.0/mondoo-operator-manager-config_v1_configmap.yaml
operators/mondoo-operator/1.9.0/mondoo-operator-webhook_v1_serviceaccount.yaml
operators/mondoo-operator/1.9.0/mondoo-operator.clusterserviceversion.yaml
operators/mondoo-operator/mondoo-operator.package.yaml

operator mondoo-operator (1.9.0)

---

operators/cluster-aas-operator/0.0.2/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml
operators/cluster-aas-operator/0.0.2/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml
operators/cluster-aas-operator/0.0.2/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cluster-aas-operator/0.0.2/manifests/cluster-aas-operator-webhook-service_v1_service.yaml
operators/cluster-aas-operator/0.0.2/manifests/cluster-aas-operator.clusterserviceversion.yaml
operators/cluster-aas-operator/0.0.2/manifests/cluster_templates_user_ct_role.yaml
operators/cluster-aas-operator/0.0.2/manifests/cluster_templates_user_role.yaml
operators/cluster-aas-operator/0.0.2/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml
operators/cluster-aas-operator/0.0.2/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml
operators/cluster-aas-operator/0.0.2/manifests/clustertemplate.openshift.io_clustertemplates.yaml
operators/cluster-aas-operator/0.0.2/metadata/annotations.yaml
operators/cluster-aas-operator/0.0.2/metadata/dependencies.yaml
operators/cluster-aas-operator/0.0.2/tests/scorecard/config.yaml

Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
--

operator cluster-aas-operator (0.0.2)

---

operators/flux/0.37.0/manifests/alert.crd.yaml
operators/flux/0.37.0/manifests/bucket.crd.yaml
operators/flux/0.37.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
operators/flux/0.37.0/manifests/crd-controller-flux-system.clusterrole.yaml
operators/flux/0.37.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
operators/flux/0.37.0/manifests/flux.v0.37.0.clusterserviceversion.yaml
operators/flux/0.37.0/manifests/gitrepository.crd.yaml
operators/flux/0.37.0/manifests/helmchart.crd.yaml
operators/flux/0.37.0/manifests/helmrelease.crd.yaml
operators/flux/0.37.0/manifests/helmrepository.crd.yaml
operators/flux/0.37.0/manifests/imagepolicy.crd.yaml
operators/flux/0.37.0/manifests/imagerepository.crd.yaml
operators/flux/0.37.0/manifests/imageupdateautomation.crd.yaml
operators/flux/0.37.0/manifests/kustomization.crd.yaml
operators/flux/0.37.0/manifests/notification-controller.service.yaml
operators/flux/0.37.0/manifests/ocirepository.crd.yaml
operators/flux/0.37.0/manifests/provider.crd.yaml
operators/flux/0.37.0/manifests/receiver.crd.yaml
operators/flux/0.37.0/manifests/source-controller.service.yaml
operators/flux/0.37.0/manifests/webhook-receiver.service.yaml
operators/flux/0.37.0/metadata/annotations.yaml

operator flux (0.37.0)

---

operators/microcks/1.6.1/microcks-operator.v1.6.1.clusterserviceversion.yaml
operators/microcks/1.6.1/microcksinstall.crd.yaml
operators/microcks/microcks.package.yaml

operator microcks (1.6.1)

---

operators/cluster-aas-operator/0.0.3/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml
operators/cluster-aas-operator/0.0.3/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml
operators/cluster-aas-operator/0.0.3/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cluster-aas-operator/0.0.3/manifests/cluster-aas-operator-webhook-service_v1_service.yaml
operators/cluster-aas-operator/0.0.3/manifests/cluster-aas-operator.clusterserviceversion.yaml
operators/cluster-aas-operator/0.0.3/manifests/cluster_templates_user_ct_role.yaml
operators/cluster-aas-operator/0.0.3/manifests/cluster_templates_user_role.yaml
operators/cluster-aas-operator/0.0.3/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml
operators/cluster-aas-operator/0.0.3/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml
operators/cluster-aas-operator/0.0.3/manifests/clustertemplate.openshift.io_clustertemplates.yaml
operators/cluster-aas-operator/0.0.3/metadata/annotations.yaml
operators/cluster-aas-operator/0.0.3/metadata/dependencies.yaml
operators/cluster-aas-operator/0.0.3/tests/scorecard/config.yaml

Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
--

operator cluster-aas-operator (0.0.3)

---

operators/rabbitmq-messaging-topology-operator/1.10.0/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_bindings.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_exchanges.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_federations.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_permissions.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_policies.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_queues.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_schemareplications.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_shovels.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_superstreams.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_topicpermissions.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_users.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_vhosts.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.webhook-service.yaml
operators/rabbitmq-messaging-topology-operator/1.10.0/metadata/annotations.yaml

operator rabbitmq-messaging-topology-operator (1.10.0)

---

operators/kubero-operator/0.0.73/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.0.73/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.0.73/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.0.73/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.0.73/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.0.73/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.0.73/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.0.73/metadata/annotations.yaml
operators/kubero-operator/0.0.73/tests/scorecard/config.yaml

operator kubero-operator (0.0.73)

---

operators/pulp-operator/1.0.0-alpha.4/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.0.0-alpha.4/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.0.0-alpha.4/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-alpha.4/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-alpha.4/manifests/pulp-operator.1.0.0-alpha.4.clusterserviceversion.yaml
operators/pulp-operator/1.0.0-alpha.4/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.0.0-alpha.4/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.0.0-alpha.4/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.0.0-alpha.4/metadata/annotations.yaml
operators/pulp-operator/1.0.0-alpha.4/tests/scorecard/config.yaml

operator pulp-operator (1.0.0-alpha.4)

---

operators/project-quay/3.8.0-rc.7/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.0-rc.7/quayecosystems.crd.yaml
operators/project-quay/3.8.0-rc.7/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add v3.8.0-rc.7 to community operators

operator project-quay (3.8.0-rc.7)

---

operators/mondoo-operator/1.9.1/k8s.mondoo.com_mondooauditconfigs.yaml
operators/mondoo-operator/1.9.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
operators/mondoo-operator/1.9.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
operators/mondoo-operator/1.9.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mondoo-operator/1.9.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/mondoo-operator/1.9.1/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
operators/mondoo-operator/1.9.1/mondoo-operator-manager-config_v1_configmap.yaml
operators/mondoo-operator/1.9.1/mondoo-operator-webhook_v1_serviceaccount.yaml
operators/mondoo-operator/1.9.1/mondoo-operator.clusterserviceversion.yaml
operators/mondoo-operator/mondoo-operator.package.yaml

operator mondoo-operator (1.9.1)

---

operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.7.0-rc1/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.7.0-rc1/metadata/annotations.yaml
operators/external-secrets-operator/0.7.0-rc1/tests/scorecard/config.yaml

bump external-secrets-operator 0.7.0-rc1

operator external-secrets-operator (0.7.0-rc1)

---

operators/function-mesh/0.8.0/bundle.Dockerfile
operators/function-mesh/0.8.0/manifests/compute.functionmesh.io_functionmeshes.yaml
operators/function-mesh/0.8.0/manifests/compute.functionmesh.io_functions.yaml
operators/function-mesh/0.8.0/manifests/compute.functionmesh.io_sinks.yaml
operators/function-mesh/0.8.0/manifests/compute.functionmesh.io_sources.yaml
operators/function-mesh/0.8.0/manifests/function-mesh-controller-manager-metrics-service_v1_service.yaml
operators/function-mesh/0.8.0/manifests/function-mesh-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/function-mesh/0.8.0/manifests/function-mesh-webhook-service_v1_service.yaml
operators/function-mesh/0.8.0/manifests/function-mesh.clusterserviceversion.yaml
operators/function-mesh/0.8.0/manifests/mesh-test-pulsar_v1_configmap.yaml
operators/function-mesh/0.8.0/manifests/test-auth_v1_secret.yaml
operators/function-mesh/0.8.0/manifests/test-pulsar_v1_configmap.yaml
operators/function-mesh/0.8.0/manifests/test-secret_v1_secret.yaml
operators/function-mesh/0.8.0/manifests/test-sink_v1_configmap.yaml
operators/function-mesh/0.8.0/manifests/test-source_v1_configmap.yaml
operators/function-mesh/0.8.0/manifests/test-tls_v1_secret.yaml
operators/function-mesh/0.8.0/metadata/annotations.yaml
operators/function-mesh/0.8.0/tests/scorecard/config.yaml

Signed-off-by: Rui Fu <rfu@apache.org>
--

operator function-mesh (0.8.0)

---

operators/function-mesh/0.7.0/manifests/function-mesh.clusterserviceversion.yaml

Signed-off-by: Rui Fu <rfu@apache.org>
--

operator [O] function-mesh (0.7.0)

---

operators/opentelemetry-operator/0.66.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
operators/opentelemetry-operator/0.66.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/opentelemetry-operator/0.66.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
operators/opentelemetry-operator/0.66.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
operators/opentelemetry-operator/0.66.0/manifests/opentelemetry.io_instrumentations.yaml
operators/opentelemetry-operator/0.66.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
operators/opentelemetry-operator/0.66.0/metadata/annotations.yaml
operators/opentelemetry-operator/0.66.0/tests/scorecard/config.yaml

Signed-off-by: Vineeth Pothulapati <vineethpothulapati@outlook.com>
--

operator opentelemetry-operator (0.66.0)

---

operators/kiali/1.60.0/bundle.Dockerfile
operators/kiali/1.60.0/manifests/kiali.crd.yaml
operators/kiali/1.60.0/manifests/kiali.v1.60.0.clusterserviceversion.yaml
operators/kiali/1.60.0/metadata/annotations.yaml

operator kiali (1.60.0)

---

operators/awx-operator/1.1.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/1.1.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/1.1.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/1.1.0/manifests/awx-operator.v1.1.0.clusterserviceversion.yaml
operators/awx-operator/1.1.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/1.1.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/1.1.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/1.1.0/metadata/annotations.yaml
operators/awx-operator/1.1.0/tests/scorecard/config.yaml

operator awx-operator (1.1.0)

---

operators/aqua/2022.4.7/bundle.Dockerfile
operators/aqua/2022.4.7/manifests/aqua-operator.v2022.4.7.clusterserviceversion.yaml
operators/aqua/2022.4.7/manifests/aquacsps.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.7/manifests/aquadatabases.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.7/manifests/aquaenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.7/manifests/aquagateways.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.7/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.7/manifests/aquascanners.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.7/manifests/aquaservers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.7/manifests/aquastarboards.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.7/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.7/manifests/configauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.7/metadata/annotations.yaml
operators/aqua/ci.yaml

Signed-off-by: Baruch Bilanski <baruch.bilanski@aquasec.com>
--

operator [CI] aqua (2022.4.7)

---

operators/grafana-operator/4.8.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml
operators/grafana-operator/4.8.0/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/4.8.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/4.8.0/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/4.8.0/integreatly.org_grafanadashboards.yaml
operators/grafana-operator/4.8.0/integreatly.org_grafanadatasources.yaml
operators/grafana-operator/4.8.0/integreatly.org_grafanafolders.yaml
operators/grafana-operator/4.8.0/integreatly.org_grafananotificationchannels.yaml
operators/grafana-operator/4.8.0/integreatly.org_grafanas.yaml
operators/grafana-operator/grafana-operator.package.yaml

operator grafana-operator (4.8.0)

---

operators/gitlab-operator-kubernetes/0.14.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.14.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.14.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.14.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.14.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.14.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.14.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.14.1)

---

operators/mondoo-operator/1.9.2/k8s.mondoo.com_mondooauditconfigs.yaml
operators/mondoo-operator/1.9.2/k8s.mondoo.com_mondoooperatorconfigs.yaml
operators/mondoo-operator/1.9.2/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
operators/mondoo-operator/1.9.2/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mondoo-operator/1.9.2/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/mondoo-operator/1.9.2/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
operators/mondoo-operator/1.9.2/mondoo-operator-manager-config_v1_configmap.yaml
operators/mondoo-operator/1.9.2/mondoo-operator-webhook_v1_serviceaccount.yaml
operators/mondoo-operator/1.9.2/mondoo-operator.clusterserviceversion.yaml
operators/mondoo-operator/mondoo-operator.package.yaml

operator mondoo-operator (1.9.2)

---

operators/galaxy-operator/1.0.0-alpha.4/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/galaxy-operator/1.0.0-alpha.4/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/galaxy-operator/1.0.0-alpha.4/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/galaxy-operator/1.0.0-alpha.4/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/galaxy-operator/1.0.0-alpha.4/manifests/pulp-operator.1.0.0-alpha.4.clusterserviceversion.yaml
operators/galaxy-operator/1.0.0-alpha.4/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/galaxy-operator/1.0.0-alpha.4/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/galaxy-operator/1.0.0-alpha.4/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/galaxy-operator/1.0.0-alpha.4/metadata/annotations.yaml
operators/galaxy-operator/1.0.0-alpha.4/tests/scorecard/config.yaml
operators/galaxy-operator/ci.yaml

operator [N] [CI] galaxy-operator (1.0.0-alpha.4)

---

operators/synapse-operator/0.3.0/Dockerfile
operators/synapse-operator/0.3.0/manifests/synapse-operator.clusterserviceversion.yaml
operators/synapse-operator/0.3.0/manifests/synapse.opdev.io_heisenbridges.yaml
operators/synapse-operator/0.3.0/manifests/synapse.opdev.io_mautrixsignals.yaml
operators/synapse-operator/0.3.0/manifests/synapse.opdev.io_synapses.yaml
operators/synapse-operator/0.3.0/metadata/annotations.yaml
operators/synapse-operator/0.3.0/tests/scorecard/config.yaml
operators/synapse-operator/ci.yaml

Signed-off-by: mgoerens <mgoerens@redhat.com>
N/A
--

operator [N] [CI] synapse-operator (0.3.0)

---

operators/kubero-operator/0.0.74/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.0.74/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.0.74/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.0.74/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.0.74/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.0.74/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.0.74/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.0.74/metadata/annotations.yaml
operators/kubero-operator/0.0.74/tests/scorecard/config.yaml

operator kubero-operator (0.0.74)

---

operators/trivy-operator/0.8.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.8.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.8.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.8.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.8.0/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.8.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.8.0/trivy-operator.v0.8.0.clusterserviceversion.yaml
operators/trivy-operator/0.8.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.8.0)

---

operators/mongodb-atlas-kubernetes/1.5.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/1.5.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/1.5.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/1.5.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/1.5.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/1.5.0/tests/scorecard/config.yaml

Signed-off-by: fabritsius <antonfabritsius@gmail.com>
--

operator mongodb-atlas-kubernetes (1.5.0)

---

operators/netobserv-operator/0.2.1/bundle.Dockerfile
operators/netobserv-operator/0.2.1/manifests/flows.netobserv.io_flowcollectors.yaml
operators/netobserv-operator/0.2.1/manifests/netobserv-manager-config_v1_configmap.yaml
operators/netobserv-operator/0.2.1/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/netobserv-operator/0.2.1/manifests/netobserv-metrics-service_v1_service.yaml
operators/netobserv-operator/0.2.1/manifests/netobserv-operator.clusterserviceversion.yaml
operators/netobserv-operator/0.2.1/metadata/annotations.yaml

operator netobserv-operator (0.2.1)

---

operators/portworx/1.10.1/core_v1_storagecluster_crd.yaml
operators/portworx/1.10.1/core_v1_storagenode_crd.yaml
operators/portworx/1.10.1/portworxoperator.clusterserviceversion.yaml
operators/portworx/portworx.package.yaml

Signed-off-by: CNBU Jenkins <cnbu-jenkins@purestorage.com>
--

operator portworx (1.10.1)

---

operators/ack-cloudtrail-controller/ci.yaml

operator [CI] ack-cloudtrail-controller

---

operators/awx-operator/1.1.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/1.1.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/1.1.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/1.1.1/manifests/awx-operator.v1.1.1.clusterserviceversion.yaml
operators/awx-operator/1.1.1/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/1.1.1/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/1.1.1/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/1.1.1/metadata/annotations.yaml
operators/awx-operator/1.1.1/tests/scorecard/config.yaml

Signed-off-by: Christian M. Adams <chadams@redhat.com>
--

operator awx-operator (1.1.1)

---

operators/project-quay/3.9.0-nightly.1/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.1/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add v3.9.0-nightly.1 to community operators

operator project-quay (3.9.0-nightly.1)

---

operators/gitlab-operator-kubernetes/0.14.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.14.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.14.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.14.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.14.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.14.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.14.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.14.2)

---

operators/trident-operator/22.10.0/trident-operator.v22.10.0.clusterserviceversion.yaml
operators/trident-operator/22.10.0/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
operators/trident-operator/trident-operator.package.yaml

operator trident-operator (22.10.0)

---

operators/pulsar-operator/0.11.5/manifests/pulsar.streamnative.io_pulsarbrokers.yaml

operator [O] pulsar-operator (0.11.5)

---

operators/external-secrets-operator/0.7.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.7.0/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.7.0/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.7.0/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.7.0/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.7.0/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.7.0/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.7.0/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.7.0/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.7.0/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.7.0/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.7.0/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.7.0/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.7.0/metadata/annotations.yaml
operators/external-secrets-operator/0.7.0/tests/scorecard/config.yaml

bump external-secrets-operator 0.7.0

operator external-secrets-operator (0.7.0)

---

operators/trivy-operator/0.9.0/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.9.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.9.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.9.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.9.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.9.0/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.9.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.9.0/trivy-operator.v0.9.0.clusterserviceversion.yaml
operators/trivy-operator/0.9.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.9.0)

---

operators/project-quay/3.9.0-nightly.2022.12.11/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.11/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.11 to community operators

operator project-quay (3.9.0-nightly.2022.12.11)

---

operators/camel-k/1.11.0/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/1.11.0/manifests/camel-k.v1.11.0.clusterserviceversion.yaml
operators/camel-k/1.11.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/1.11.0/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/1.11.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/1.11.0/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/1.11.0/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/1.11.0/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/1.11.0/metadata/annotations.yaml
operators/camel-k/1.11.0/tests/scorecard/config.yaml

operator camel-k (1.11.0)

---

operators/awx-operator/1.1.2/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/1.1.2/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/1.1.2/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/1.1.2/manifests/awx-operator.v1.1.2.clusterserviceversion.yaml
operators/awx-operator/1.1.2/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/1.1.2/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/1.1.2/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/1.1.2/metadata/annotations.yaml
operators/awx-operator/1.1.2/tests/scorecard/config.yaml

Signed-off-by: Christian M. Adams <chadams@redhat.com>
--

operator awx-operator (1.1.2)

---

operators/project-quay/3.9.0-nightly.2022.12.13/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.13/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.13 to community operators

operator project-quay (3.9.0-nightly.2022.12.13)

---

operators/mondoo-operator/1.9.3/k8s.mondoo.com_mondooauditconfigs.yaml
operators/mondoo-operator/1.9.3/k8s.mondoo.com_mondoooperatorconfigs.yaml
operators/mondoo-operator/1.9.3/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
operators/mondoo-operator/1.9.3/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mondoo-operator/1.9.3/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/mondoo-operator/1.9.3/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
operators/mondoo-operator/1.9.3/mondoo-operator-manager-config_v1_configmap.yaml
operators/mondoo-operator/1.9.3/mondoo-operator-webhook_v1_serviceaccount.yaml
operators/mondoo-operator/1.9.3/mondoo-operator.clusterserviceversion.yaml
operators/mondoo-operator/mondoo-operator.package.yaml

operator mondoo-operator (1.9.3)

---

operators/beegfs-csi-driver-operator/1.4.0/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml
operators/beegfs-csi-driver-operator/1.4.0/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml
operators/beegfs-csi-driver-operator/1.4.0/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/beegfs-csi-driver-operator/1.4.0/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml
operators/beegfs-csi-driver-operator/1.4.0/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml
operators/beegfs-csi-driver-operator/1.4.0/metadata/annotations.yaml
operators/beegfs-csi-driver-operator/1.4.0/tests/scorecard/config.yaml

Signed-off-by: Weber, Eric <Eric.Weber2@netapp.com>
--

operator beegfs-csi-driver-operator (1.4.0)

---

operators/project-quay/3.9.0-nightly.2022.12.14/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.14/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.14 to community operators

operator project-quay (3.9.0-nightly.2022.12.14)

---

operators/service-binding-operator/1.3.2/manifests/binding.operators.coreos.com_bindablekinds.yaml
operators/service-binding-operator/1.3.2/manifests/binding.operators.coreos.com_servicebindings.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-clusterworkloadresourcemappings-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-clusterworkloadresourcemappings-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-manager-config_v1_configmap.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-operator.clusterserviceversion.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.2/manifests/service-binding-webhook-service_v1_service.yaml
operators/service-binding-operator/1.3.2/manifests/servicebinding.io_clusterworkloadresourcemappings.yaml
operators/service-binding-operator/1.3.2/manifests/servicebinding.io_servicebindings.yaml
operators/service-binding-operator/1.3.2/metadata/annotations.yaml
operators/service-binding-operator/1.3.2/tests/scorecard/config.yaml

Signed-off-by: Baiju Muthukadan <baiju.m.mail@gmail.com>
--

operator service-binding-operator (1.3.2)

---

operators/project-quay/3.9.0-nightly.2022.12.15/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.15/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.15 to community operators

operator project-quay (3.9.0-nightly.2022.12.15)

---

operators/kubero-operator/0.0.75/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.0.75/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.0.75/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.0.75/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.0.75/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.0.75/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.0.75/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.0.75/metadata/annotations.yaml
operators/kubero-operator/0.0.75/tests/scorecard/config.yaml

operator kubero-operator (0.0.75)

---

operators/seldon-operator/1.15.0/manifests/machinelearning.seldon.io_seldondeployments.yaml
operators/seldon-operator/1.15.0/manifests/seldon-operator.clusterserviceversion.yaml
operators/seldon-operator/1.15.0/metadata/annotations.yaml
operators/seldon-operator/1.15.0/tests/scorecard/config.yaml

Signed-off-by: Rafal Skolasinski <r.j.skolasinski@gmail.com>
--

operator seldon-operator (1.15.0)

---

operators/authorino-operator/0.5.0/bundle.Dockerfile
operators/authorino-operator/0.5.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.5.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.5.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.5.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.5.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.5.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
operators/authorino-operator/0.5.0/manifests/authorino-operator-manager-config_v1_configmap.yaml
operators/authorino-operator/0.5.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.5.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.5.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.5.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.5.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.5.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.5.0/metadata/annotations.yaml
operators/authorino-operator/0.5.0/tests/scorecard/config.yaml

Signed-off-by: Guilherme Cassolato <guicassolato@gmail.com>
--

operator authorino-operator (0.5.0)

---

operators/project-quay/3.9.0-nightly.2022.12.17/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.17/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.17 to community operators

operator project-quay (3.9.0-nightly.2022.12.17)

---

operators/project-quay/3.9.0-nightly.2022.12.18/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.18/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.18 to community operators

operator project-quay (3.9.0-nightly.2022.12.18)

---

operators/project-quay/3.9.0-nightly.2022.12.19/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.19/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.19 to community operators

operator project-quay (3.9.0-nightly.2022.12.19)

---

operators/dynatrace-operator/0.10.1/Dockerfile
operators/dynatrace-operator/0.10.1/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml
operators/dynatrace-operator/0.10.1/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml
operators/dynatrace-operator/0.10.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/0.10.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/0.10.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml
operators/dynatrace-operator/0.10.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/dynatrace-operator/0.10.1/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml
operators/dynatrace-operator/0.10.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.10.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.10.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.10.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.10.1/metadata/annotations.yaml

operator dynatrace-operator (0.10.1)

---

operators/netobserv-operator/0.2.2/manifests/flows.netobserv.io_flowcollectors.yaml
operators/netobserv-operator/0.2.2/manifests/netobserv-manager-config_v1_configmap.yaml
operators/netobserv-operator/0.2.2/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/netobserv-operator/0.2.2/manifests/netobserv-metrics-service_v1_service.yaml
operators/netobserv-operator/0.2.2/manifests/netobserv-operator.clusterserviceversion.yaml
operators/netobserv-operator/0.2.2/metadata/annotations.yaml

operator netobserv-operator (0.2.2)

---

operators/nfs-provisioner-operator/0.0.6/Dockerfile
operators/nfs-provisioner-operator/0.0.6/manifests/cache.jhouse.com_nfsprovisioners.yaml
operators/nfs-provisioner-operator/0.0.6/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml
operators/nfs-provisioner-operator/0.0.6/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nfs-provisioner-operator/0.0.6/manifests/nfs-provisioner-operator.clusterserviceversion.yaml
operators/nfs-provisioner-operator/0.0.6/metadata/annotations.yaml
operators/nfs-provisioner-operator/0.0.6/tests/scorecard/config.yaml
operators/nfs-provisioner-operator/0.0.7/manifests/cache.jhouse.com_nfsprovisioners.yaml
operators/nfs-provisioner-operator/0.0.7/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml
operators/nfs-provisioner-operator/0.0.7/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nfs-provisioner-operator/0.0.7/manifests/nfs-provisioner-operator.clusterserviceversion.yaml
operators/nfs-provisioner-operator/0.0.7/metadata/annotations.yaml
operators/nfs-provisioner-operator/0.0.7/tests/scorecard/config.yaml

Signed-off-by: jooho <jlee@redhat.com>
--

operator [R] nfs-provisioner-operator (0.0.6 0.0.7)

---

operators/limitador-operator/0.4.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml
operators/limitador-operator/0.4.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
operators/limitador-operator/0.4.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/limitador-operator/0.4.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/0.4.0/manifests/limitador.kuadrant.io_limitadors.yaml
operators/limitador-operator/0.4.0/metadata/annotations.yaml
operators/limitador-operator/0.4.0/tests/scorecard/config.yaml
operators/limitador-operator/ci.yaml

operator [CI] limitador-operator (0.4.0)

---

operators/project-quay/3.9.0-nightly.2022.12.20/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.20/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.20 to community operators

operator project-quay (3.9.0-nightly.2022.12.20)

---

operators/mongodb-atlas-kubernetes/1.5.1/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/1.5.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/1.5.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/1.5.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/1.5.1/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/1.5.1/tests/scorecard/config.yaml

Signed-off-by: Timur_Akhmadiev <Timur_Akhmadiev@epam.com>
--

operator mongodb-atlas-kubernetes (1.5.1)

---

operators/project-quay/3.9.0-nightly.2022.12.21/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.21/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.21 to community operators

operator project-quay (3.9.0-nightly.2022.12.21)

---

operators/dell-csi-operator/1.10.0/csiisilons.storage.dell.com.crd.yaml
operators/dell-csi-operator/1.10.0/csipowermaxes.storage.dell.com.crd.yaml
operators/dell-csi-operator/1.10.0/csipowermaxrevproxies.storage.dell.com.crd.yaml
operators/dell-csi-operator/1.10.0/csipowerstores.storage.dell.com.crd.yaml
operators/dell-csi-operator/1.10.0/csiunities.storage.dell.com.crd.yaml
operators/dell-csi-operator/1.10.0/csivxflexoses.storage.dell.com.crd.yaml
operators/dell-csi-operator/1.10.0/dell-csi-operator.v1.10.0.clusterserviceversion.yaml
operators/dell-csi-operator/dell-csi-operator.package.yaml

operator dell-csi-operator (1.10.0)

---

operators/kuadrant-operator/0.2.0/bundle.Dockerfile
operators/kuadrant-operator/0.2.0/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
operators/kuadrant-operator/0.2.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.2.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.2.0/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.2.0/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.2.0/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.2.0/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.2.0/metadata/annotations.yaml
operators/kuadrant-operator/0.2.0/metadata/dependencies.yaml
operators/kuadrant-operator/0.2.0/tests/scorecard/config.yaml
operators/kuadrant-operator/ci.yaml

operator [N] [CI] kuadrant-operator (0.2.0)

---

operators/cloud-native-postgresql/1.17.3/manifests/cloud-native-postgresql.clusterserviceversion.yaml
operators/cloud-native-postgresql/1.17.3/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
operators/cloud-native-postgresql/1.17.3/manifests/postgresql-operator-webhook-service_v1_service.yaml
operators/cloud-native-postgresql/1.17.3/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
operators/cloud-native-postgresql/1.17.3/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
operators/cloud-native-postgresql/1.17.3/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
operators/cloud-native-postgresql/1.17.3/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
operators/cloud-native-postgresql/1.17.3/metadata/annotations.yaml
operators/cloud-native-postgresql/1.17.3/tests/scorecard/config.yaml

operator cloud-native-postgresql (1.17.3)

---

operators/cloud-native-postgresql/1.18.1/manifests/cloud-native-postgresql.clusterserviceversion.yaml
operators/cloud-native-postgresql/1.18.1/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
operators/cloud-native-postgresql/1.18.1/manifests/postgresql-operator-webhook-service_v1_service.yaml
operators/cloud-native-postgresql/1.18.1/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
operators/cloud-native-postgresql/1.18.1/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
operators/cloud-native-postgresql/1.18.1/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
operators/cloud-native-postgresql/1.18.1/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
operators/cloud-native-postgresql/1.18.1/metadata/annotations.yaml
operators/cloud-native-postgresql/1.18.1/tests/scorecard/config.yaml

operator cloud-native-postgresql (1.18.1)

---

operators/cloud-native-postgresql/1.16.5/manifests/cloud-native-postgresql.clusterserviceversion.yaml
operators/cloud-native-postgresql/1.16.5/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
operators/cloud-native-postgresql/1.16.5/manifests/postgresql-operator-webhook-service_v1_service.yaml
operators/cloud-native-postgresql/1.16.5/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
operators/cloud-native-postgresql/1.16.5/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
operators/cloud-native-postgresql/1.16.5/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
operators/cloud-native-postgresql/1.16.5/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
operators/cloud-native-postgresql/1.16.5/metadata/annotations.yaml
operators/cloud-native-postgresql/1.16.5/tests/scorecard/config.yaml

operator cloud-native-postgresql (1.16.5)

---

operators/gitlab-runner-operator/1.11.0/manifests/apps.gitlab.com_runners.yaml
operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml
operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml
operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml
operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-webhook-service_v1_service.yaml
operators/gitlab-runner-operator/1.11.0/metadata/annotations.yaml
operators/gitlab-runner-operator/1.11.0/tests/scorecard/config.yaml

Signed-off-by: Georgi N. Georgiev <ggeorgiev@gitlab.com>
--

operator gitlab-runner-operator (1.11.0)

---

operators/project-quay/3.9.0-nightly.2022.12.22/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.22/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.22 to community operators

operator project-quay (3.9.0-nightly.2022.12.22)

---

operators/function-mesh/0.9.0/bundle.Dockerfile
operators/function-mesh/0.9.0/manifests/compute.functionmesh.io_functionmeshes.yaml
operators/function-mesh/0.9.0/manifests/compute.functionmesh.io_functions.yaml
operators/function-mesh/0.9.0/manifests/compute.functionmesh.io_sinks.yaml
operators/function-mesh/0.9.0/manifests/compute.functionmesh.io_sources.yaml
operators/function-mesh/0.9.0/manifests/function-mesh-controller-manager-metrics-service_v1_service.yaml
operators/function-mesh/0.9.0/manifests/function-mesh-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/function-mesh/0.9.0/manifests/function-mesh-webhook-service_v1_service.yaml
operators/function-mesh/0.9.0/manifests/function-mesh.clusterserviceversion.yaml
operators/function-mesh/0.9.0/manifests/mesh-test-pulsar_v1_configmap.yaml
operators/function-mesh/0.9.0/manifests/test-auth_v1_secret.yaml
operators/function-mesh/0.9.0/manifests/test-pulsar_v1_configmap.yaml
operators/function-mesh/0.9.0/manifests/test-secret_v1_secret.yaml
operators/function-mesh/0.9.0/manifests/test-sink_v1_configmap.yaml
operators/function-mesh/0.9.0/manifests/test-source_v1_configmap.yaml
operators/function-mesh/0.9.0/manifests/test-tls_v1_secret.yaml
operators/function-mesh/0.9.0/metadata/annotations.yaml
operators/function-mesh/0.9.0/tests/scorecard/config.yaml

Signed-off-by: Rui Fu <rfu@apache.org>
--

operator function-mesh (0.9.0)

---

operators/cryostat-operator/2.2.1/Dockerfile
operators/cryostat-operator/2.2.1/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.2.1/manifests/cryostat-operator-manager-config_v1_configmap.yaml
operators/cryostat-operator/2.2.1/manifests/cryostat-operator-oauth-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.2.1/manifests/cryostat-operator.clusterserviceversion.yaml
operators/cryostat-operator/2.2.1/manifests/operator.cryostat.io_cryostats.yaml
operators/cryostat-operator/2.2.1/metadata/annotations.yaml
operators/cryostat-operator/2.2.1/tests/scorecard/config.yaml

operator cryostat-operator (2.2.1)

---

operators/project-quay/3.9.0-nightly.2022.12.23/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.23/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.23 to community operators

operator project-quay (3.9.0-nightly.2022.12.23)

---

operators/project-quay/3.9.0-nightly.2022.12.24/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.24/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.24 to community operators

operator project-quay (3.9.0-nightly.2022.12.24)

---

operators/project-quay/3.9.0-nightly.2022.12.25/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.25/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.25 to community operators

operator project-quay (3.9.0-nightly.2022.12.25)

---

operators/project-quay/3.9.0-nightly.2022.12.26/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.26/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.26 to community operators

operator project-quay (3.9.0-nightly.2022.12.26)

---

operators/project-quay/3.9.0-nightly.2022.12.27/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.27/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.27 to community operators

operator project-quay (3.9.0-nightly.2022.12.27)

---

operators/mondoo-operator/1.10.0/k8s.mondoo.com_mondooauditconfigs.yaml
operators/mondoo-operator/1.10.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
operators/mondoo-operator/1.10.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
operators/mondoo-operator/1.10.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mondoo-operator/1.10.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/mondoo-operator/1.10.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
operators/mondoo-operator/1.10.0/mondoo-operator-manager-config_v1_configmap.yaml
operators/mondoo-operator/1.10.0/mondoo-operator-webhook_v1_serviceaccount.yaml
operators/mondoo-operator/1.10.0/mondoo-operator.clusterserviceversion.yaml
operators/mondoo-operator/mondoo-operator.package.yaml

operator mondoo-operator (1.10.0)

---

operators/project-quay/3.9.0-nightly.2022.12.28/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.28/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.28 to community operators

operator project-quay (3.9.0-nightly.2022.12.28)

---

operators/edp-keycloak-operator/1.14.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.14.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.14.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.14.0/tests/scorecard/config.yaml

Signed-off-by: Sergiy Kulanov <sergiy_kulanov@epam.com>
--

operator edp-keycloak-operator (1.14.0)

---

operators/kubero-operator/0.0.82/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.0.82/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.0.82/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.0.82/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.0.82/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.0.82/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.0.82/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.0.82/metadata/annotations.yaml
operators/kubero-operator/0.0.82/tests/scorecard/config.yaml

operator kubero-operator (0.0.82)

---

operators/mongodb-enterprise/1.18.0/bundle.Dockerfile
operators/mongodb-enterprise/1.18.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.18.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.18.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.18.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.18.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.18.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.18.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.18.0/manifests/mongodb.com_mongodbmulti.yaml
operators/mongodb-enterprise/1.18.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.18.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.18.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.18.0/tests/scorecard/config.yaml

operator mongodb-enterprise (1.18.0)

---

operators/project-quay/3.9.0-nightly.2022.12.30/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.30/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.30 to community operators

operator project-quay (3.9.0-nightly.2022.12.30)

---

operators/project-quay/3.9.0-nightly.2022.12.31/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.2022.12.31/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.2022.12.31 to community operators

operator project-quay (3.9.0-nightly.2022.12.31)

---

operators/trivy-operator/0.10.0/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.0/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.0/trivy-operator.v0.10.0.clusterserviceversion.yaml
operators/trivy-operator/0.10.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.10.0)

---

operators/trivy-operator/0.10.1/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.1/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.1/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.1/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.1/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.1/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.1/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.10.1/trivy-operator.v0.10.1.clusterserviceversion.yaml
operators/trivy-operator/0.10.1/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.10.1)

---

operators/pulp-operator/1.0.0-alpha.5/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.0.0-alpha.5/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.0.0-alpha.5/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-alpha.5/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-alpha.5/manifests/pulp-operator.1.0.0-alpha.5.clusterserviceversion.yaml
operators/pulp-operator/1.0.0-alpha.5/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.0.0-alpha.5/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.0.0-alpha.5/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.0.0-alpha.5/metadata/annotations.yaml
operators/pulp-operator/1.0.0-alpha.5/tests/scorecard/config.yaml

operator pulp-operator (1.0.0-alpha.5)

---

operators/temporal-operator/0.9.1/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.9.1/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.9.1/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.9.1/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.9.1/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.9.1/metadata/annotations.yaml

operator temporal-operator (0.9.1)

---

operators/cluster-aas-operator/0.0.4/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml
operators/cluster-aas-operator/0.0.4/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml
operators/cluster-aas-operator/0.0.4/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cluster-aas-operator/0.0.4/manifests/cluster-aas-operator-webhook-service_v1_service.yaml
operators/cluster-aas-operator/0.0.4/manifests/cluster-aas-operator.clusterserviceversion.yaml
operators/cluster-aas-operator/0.0.4/manifests/cluster_templates_user_ct_role.yaml
operators/cluster-aas-operator/0.0.4/manifests/cluster_templates_user_role.yaml
operators/cluster-aas-operator/0.0.4/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml
operators/cluster-aas-operator/0.0.4/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml
operators/cluster-aas-operator/0.0.4/manifests/clustertemplate.openshift.io_clustertemplates.yaml
operators/cluster-aas-operator/0.0.4/metadata/annotations.yaml
operators/cluster-aas-operator/0.0.4/metadata/dependencies.yaml
operators/cluster-aas-operator/0.0.4/tests/scorecard/config.yaml

Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
--

operator cluster-aas-operator (0.0.4)

---

operators/splunk/2.1.1/bundle.Dockerfile
operators/splunk/2.1.1/manifests/enterprise.splunk.com_clustermanagers.yaml
operators/splunk/2.1.1/manifests/enterprise.splunk.com_clustermasters.yaml
operators/splunk/2.1.1/manifests/enterprise.splunk.com_indexerclusters.yaml
operators/splunk/2.1.1/manifests/enterprise.splunk.com_licensemanagers.yaml
operators/splunk/2.1.1/manifests/enterprise.splunk.com_licensemasters.yaml
operators/splunk/2.1.1/manifests/enterprise.splunk.com_monitoringconsoles.yaml
operators/splunk/2.1.1/manifests/enterprise.splunk.com_searchheadclusters.yaml
operators/splunk/2.1.1/manifests/enterprise.splunk.com_standalones.yaml
operators/splunk/2.1.1/manifests/splunk-operator-config_v1_configmap.yaml
operators/splunk/2.1.1/manifests/splunk-operator-controller-manager-metrics-service_v1_service.yaml
operators/splunk/2.1.1/manifests/splunk-operator-controller-manager-service_v1_service.yaml
operators/splunk/2.1.1/manifests/splunk-operator-manager-config_v1_configmap.yaml
operators/splunk/2.1.1/manifests/splunk-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/splunk/2.1.1/manifests/splunk-operator.clusterserviceversion.yaml
operators/splunk/2.1.1/metadata/annotations.yaml
operators/splunk/2.1.1/tests/scorecard/config.yaml

Signed-off-by: vivekr-splunk <94569031+vivekr-splunk@users.noreply.github.com>
--

operator splunk (2.1.1)

---

operators/external-secrets-operator/0.7.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.7.1/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.7.1/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.7.1/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.7.1/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.7.1/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.7.1/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.7.1/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.7.1/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.7.1/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.7.1/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.7.1/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.7.1/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.7.1/metadata/annotations.yaml
operators/external-secrets-operator/0.7.1/tests/scorecard/config.yaml

bump external-secrets-operator 0.7.1

operator external-secrets-operator (0.7.1)

---

operators/eginnovations-operator/0.0.4/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml
operators/eginnovations-operator/0.0.4/manifests/eginnovations-operator-manager-config_v1_configmap.yaml
operators/eginnovations-operator/0.0.4/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/eginnovations-operator/0.0.4/manifests/eginnovations-operator-webhook-service_v1_service.yaml
operators/eginnovations-operator/0.0.4/manifests/eginnovations-operator.clusterserviceversion.yaml
operators/eginnovations-operator/0.0.4/manifests/eginnovations.com_eguniversalagents.yaml
operators/eginnovations-operator/0.0.4/metadata/annotations.yaml
operators/eginnovations-operator/0.0.4/tests/scorecard/config.yaml

Signed-off-by: Gaurav Singh <gauravsingh.r@eginnovations.com>
--

operator eginnovations-operator (0.0.4)

---

operators/nfs-provisioner-operator/0.0.7/manifests/nfs-provisioner-operator.clusterserviceversion.yaml

Signed-off-by: jooho <jlee@redhat.com>
--

operator [O] nfs-provisioner-operator (0.0.7)

---

operators/ack-kafka-controller/ci.yaml

operator [CI] ack-kafka-controller

---

operators/ack-eventbridge-controller/ci.yaml

operator [CI] ack-eventbridge-controller

---

operators/percona-server-mongodb-operator/1.13.0/manifests/percona-server-mongodb-operator.v1.13.0.clusterserviceversion.yaml

Signed-off-by: Natalia Marukovich <natalia.marukovich@percona.com>
--

operator percona-server-mongodb-operator (1.13.0)

---

operators/rabbitmq-cluster-operator/2.1.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.1.0/manifests/crds.yaml
operators/rabbitmq-cluster-operator/2.1.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.1.0/metadata/annotations.yaml

operator rabbitmq-cluster-operator (2.1.0)

---

operators/opentelemetry-operator/0.67.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
operators/opentelemetry-operator/0.67.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/opentelemetry-operator/0.67.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
operators/opentelemetry-operator/0.67.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
operators/opentelemetry-operator/0.67.0/manifests/opentelemetry.io_instrumentations.yaml
operators/opentelemetry-operator/0.67.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
operators/opentelemetry-operator/0.67.0/metadata/annotations.yaml
operators/opentelemetry-operator/0.67.0/tests/scorecard/config.yaml

Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
--

operator opentelemetry-operator (0.67.0)

---

operators/temporal-operator/0.10.0/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.10.0/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.10.0/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.10.0/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.10.0/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.10.0/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.10.0/metadata/annotations.yaml

operator temporal-operator (0.10.0)

---

operators/awx-operator/1.1.3/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/1.1.3/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/1.1.3/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/1.1.3/manifests/awx-operator.v1.1.3.clusterserviceversion.yaml
operators/awx-operator/1.1.3/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/1.1.3/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/1.1.3/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/1.1.3/metadata/annotations.yaml
operators/awx-operator/1.1.3/tests/scorecard/config.yaml

Signed-off-by: Christian M. Adams <chadams@redhat.com>
--

operator awx-operator (1.1.3)

---

operators/self-node-remediation/0.5.0/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml
operators/self-node-remediation/0.5.0/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.5.0/manifests/self-node-remediation-manager-config_v1_configmap.yaml
operators/self-node-remediation/0.5.0/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.5.0/manifests/self-node-remediation-webhook-service_v1_service.yaml
operators/self-node-remediation/0.5.0/manifests/self-node-remediation.clusterserviceversion.yaml
operators/self-node-remediation/0.5.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
operators/self-node-remediation/0.5.0/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
operators/self-node-remediation/0.5.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
operators/self-node-remediation/0.5.0/metadata/annotations.yaml
operators/self-node-remediation/0.5.0/tests/scorecard/config.yaml

Signed-off-by: Michael Shitrit <mshitrit@redhat.com>
--

operator self-node-remediation (0.5.0)

---

operators/percona-server-mongodb-operator/1.13.1/manifests/percona-server-mongodb-operator.v1.13.1.clusterserviceversion.yaml
operators/percona-server-mongodb-operator/1.13.1/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.13.1/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.13.1/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.13.1/metadata/annotations.yaml

Signed-off-by: Natalia Marukovich <natalia.marukovich@percona.com>
--

operator percona-server-mongodb-operator (1.13.1)

---

operators/loki-operator/0.1.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
operators/loki-operator/0.1.0/manifests/loki-operator-manager-config_v1_configmap.yaml
operators/loki-operator/0.1.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/loki-operator/0.1.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
operators/loki-operator/0.1.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/loki-operator/0.1.0/manifests/loki-operator-webhook-service_v1_service.yaml
operators/loki-operator/0.1.0/manifests/loki-operator.clusterserviceversion.yaml
operators/loki-operator/0.1.0/manifests/loki.grafana.com_alertingrules.yaml
operators/loki-operator/0.1.0/manifests/loki.grafana.com_lokistacks.yaml
operators/loki-operator/0.1.0/manifests/loki.grafana.com_recordingrules.yaml
operators/loki-operator/0.1.0/manifests/loki.grafana.com_rulerconfigs.yaml
operators/loki-operator/0.1.0/metadata/annotations.yaml
operators/loki-operator/0.1.0/tests/scorecard/config.yaml
operators/loki-operator/ci.yaml

Signed-off-by: Periklis Tsirakidis <periklis@redhat.com>
--

operator [N] [CI] loki-operator (0.1.0)

---

operators/kubero-operator/0.0.84/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.0.84/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.0.84/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.0.84/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.0.84/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.0.84/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.0.84/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.0.84/metadata/annotations.yaml
operators/kubero-operator/0.0.84/tests/scorecard/config.yaml

operator kubero-operator (0.0.84)

---

operators/dynatrace-operator/0.10.2/Dockerfile
operators/dynatrace-operator/0.10.2/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.10.2/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.10.2/metadata/annotations.yaml

operator dynatrace-operator (0.10.2)

---

operators/verticadb-operator/1.9.0/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/1.9.0/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/1.9.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/1.9.0/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/1.9.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/1.9.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/1.9.0/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/1.9.0/metadata/annotations.yaml
operators/verticadb-operator/1.9.0/tests/scorecard/config.yaml

operator verticadb-operator (1.9.0)

---

operators/datadog-operator/0.8.4/manifests/datadog-operator.clusterserviceversion.yaml
operators/datadog-operator/0.8.4/manifests/datadoghq.com_datadogagents.yaml
operators/datadog-operator/0.8.4/manifests/datadoghq.com_datadogmetrics.yaml
operators/datadog-operator/0.8.4/manifests/datadoghq.com_datadogmonitors.yaml
operators/datadog-operator/0.8.4/metadata/annotations.yaml
operators/datadog-operator/0.8.4/tests/scorecard/config.yaml

operator datadog-operator (0.8.4)

---

operators/gitlab-operator-kubernetes/0.15.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.15.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.15.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.15.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.15.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.15.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.15.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.15.2)

---

operators/gitlab-operator-kubernetes/0.15.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.15.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.15.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.15.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.15.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.15.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.15.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.15.1)

---

operators/service-binding-operator/1.3.3/manifests/binding.operators.coreos.com_bindablekinds.yaml
operators/service-binding-operator/1.3.3/manifests/binding.operators.coreos.com_servicebindings.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-clusterworkloadresourcemappings-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-clusterworkloadresourcemappings-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-manager-config_v1_configmap.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-operator.clusterserviceversion.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.3/manifests/service-binding-webhook-service_v1_service.yaml
operators/service-binding-operator/1.3.3/manifests/servicebinding.io_clusterworkloadresourcemappings.yaml
operators/service-binding-operator/1.3.3/manifests/servicebinding.io_servicebindings.yaml
operators/service-binding-operator/1.3.3/metadata/annotations.yaml
operators/service-binding-operator/1.3.3/tests/scorecard/config.yaml

operator service-binding-operator (1.3.3)

---

operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml
operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml
operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-operator-manager-config_v1_configmap.yaml
operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-operator-webhook-service_v1_service.yaml
operators/aerospike-kubernetes-operator/2.4.0/manifests/asdb.aerospike.com_aerospikeclusters.yaml
operators/aerospike-kubernetes-operator/2.4.0/metadata/annotations.yaml
operators/aerospike-kubernetes-operator/2.4.0/tests/scorecard/config.yaml
operators/aerospike-kubernetes-operator/ci.yaml

Signed-off-by: Sudhanshu Ranjan <sudhanshu@aerospike.com>
--

operator [CI] aerospike-kubernetes-operator (2.4.0)

---

operators/ndmspc-operator/0.1.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.1.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.1.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.1.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.1.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.1.0/metadata/annotations.yaml
operators/ndmspc-operator/0.1.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.1.0)

---

operators/ndmspc-operator/0.1.1/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.1.1/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.1.1/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.1.1/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.1.1/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.1.1/metadata/annotations.yaml
operators/ndmspc-operator/0.1.1/tests/scorecard/config.yaml

operator ndmspc-operator (0.1.1)

---

operators/ndmspc-operator/0.1.2/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.1.2/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.1.2/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.1.2/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.1.2/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.1.2/metadata/annotations.yaml
operators/ndmspc-operator/0.1.2/tests/scorecard/config.yaml

operator ndmspc-operator (0.1.2)

---

operators/external-secrets-operator/0.7.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.7.2/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.7.2/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.7.2/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.7.2/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.7.2/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.7.2/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.7.2/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.7.2/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.7.2/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.7.2/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.7.2/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.7.2/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.7.2/metadata/annotations.yaml
operators/external-secrets-operator/0.7.2/tests/scorecard/config.yaml

bump external-secrets-operator 0.7.2

operator external-secrets-operator (0.7.2)

---

operators/ndmspc-operator/0.1.3/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.1.3/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.1.3/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.1.3/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.1.3/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.1.3/metadata/annotations.yaml
operators/ndmspc-operator/0.1.3/tests/scorecard/config.yaml

operator ndmspc-operator (0.1.3)

---

operators/kuadrant-operator/0.2.1/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
operators/kuadrant-operator/0.2.1/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.2.1/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.2.1/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.2.1/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.2.1/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.2.1/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.2.1/metadata/annotations.yaml
operators/kuadrant-operator/0.2.1/metadata/dependencies.yaml
operators/kuadrant-operator/0.2.1/tests/scorecard/config.yaml

2. [x} Features and capabilities of your Operator and how to use it
--

operator kuadrant-operator (0.2.1)

---

operators/function-mesh/0.10.0/bundle.Dockerfile
operators/function-mesh/0.10.0/manifests/compute.functionmesh.io_functionmeshes.yaml
operators/function-mesh/0.10.0/manifests/compute.functionmesh.io_functions.yaml
operators/function-mesh/0.10.0/manifests/compute.functionmesh.io_sinks.yaml
operators/function-mesh/0.10.0/manifests/compute.functionmesh.io_sources.yaml
operators/function-mesh/0.10.0/manifests/function-mesh-controller-manager-metrics-service_v1_service.yaml
operators/function-mesh/0.10.0/manifests/function-mesh-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/function-mesh/0.10.0/manifests/function-mesh-webhook-service_v1_service.yaml
operators/function-mesh/0.10.0/manifests/function-mesh.clusterserviceversion.yaml
operators/function-mesh/0.10.0/manifests/mesh-test-pulsar_v1_configmap.yaml
operators/function-mesh/0.10.0/manifests/test-auth_v1_secret.yaml
operators/function-mesh/0.10.0/manifests/test-pulsar_v1_configmap.yaml
operators/function-mesh/0.10.0/manifests/test-secret_v1_secret.yaml
operators/function-mesh/0.10.0/manifests/test-sink_v1_configmap.yaml
operators/function-mesh/0.10.0/manifests/test-source_v1_configmap.yaml
operators/function-mesh/0.10.0/manifests/test-tls_v1_secret.yaml
operators/function-mesh/0.10.0/metadata/annotations.yaml
operators/function-mesh/0.10.0/tests/scorecard/config.yaml

Signed-off-by: Rui Fu <rfu@apache.org>
--

operator function-mesh (0.10.0)

---

operators/kubernetes-imagepuller-operator/1.0.4/che.eclipse.org_kubernetesimagepullers_crd.yaml
operators/kubernetes-imagepuller-operator/1.0.4/controller-manager-metrics-service_v1_service.yaml
operators/kubernetes-imagepuller-operator/1.0.4/kubernetes-imagepuller-operator.v1.0.4.clusterserviceversion.yaml
operators/kubernetes-imagepuller-operator/1.0.4/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml

Signed-off-by: Anatolii Bazko <abazko@redhat.com>
--

operator kubernetes-imagepuller-operator (1.0.4)

---

operators/yaks/0.12.2/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.12.2/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.12.2/yaks.v0.12.2.clusterserviceversion.yaml
operators/yaks/yaks.package.yaml

operator yaks (0.12.2)

---

operators/aqua/2022.4.8/bundle.Dockerfile
operators/aqua/2022.4.8/manifests/aqua-operator.v2022.4.8.clusterserviceversion.yaml
operators/aqua/2022.4.8/manifests/aquacsps.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.8/manifests/aquadatabases.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.8/manifests/aquaenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.8/manifests/aquagateways.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.8/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.8/manifests/aquascanners.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.8/manifests/aquaservers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.8/manifests/aquastarboards.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.8/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.8/manifests/configauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.8/metadata/annotations.yaml

Signed-off-by: Baruch Bilanski <baruch.bilanski@aquasec.com>
--

operator aqua (2022.4.8)

---

operators/aqua/6.5.9/bundle.Dockerfile
operators/aqua/6.5.9/manifests/aqua-operator.v6.5.9.clusterserviceversion.yaml
operators/aqua/6.5.9/manifests/aquacsps.operator.aquasec.com.crd.yaml
operators/aqua/6.5.9/manifests/aquadatabases.operator.aquasec.com.crd.yaml
operators/aqua/6.5.9/manifests/aquaenforcers.operator.aquasec.com.crd.yaml
operators/aqua/6.5.9/manifests/aquagateways.operator.aquasec.com.crd.yaml
operators/aqua/6.5.9/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml
operators/aqua/6.5.9/manifests/aquascanners.operator.aquasec.com.crd.yaml
operators/aqua/6.5.9/manifests/aquaservers.operator.aquasec.com.crd.yaml
operators/aqua/6.5.9/manifests/aquastarboards.aquasecurity.github.io.crd.yaml
operators/aqua/6.5.9/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/6.5.9/manifests/configauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/6.5.9/metadata/annotations.yaml

Signed-off-by: Baruch Bilanski <baruch.bilanski@aquasec.com>
--

operator aqua (6.5.9)

---

operators/gitlab-operator-kubernetes/0.11.4/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.11.4/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.11.4/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.11.4/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.11.4/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.11.4/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.11.4/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.11.4)

---

operators/ndmspc-operator/0.2.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.2.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.2.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.2.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.2.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.2.0/metadata/annotations.yaml
operators/ndmspc-operator/0.2.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.2.0)

---

operators/ack-acm-controller/ci.yaml

operator [CI] ack-acm-controller

---

operators/ndmspc-operator/0.2.1/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.2.1/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.2.1/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.2.1/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.2.1/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.2.1/metadata/annotations.yaml
operators/ndmspc-operator/0.2.1/tests/scorecard/config.yaml

operator ndmspc-operator (0.2.1)

---

operators/kubero-operator/0.0.96/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.0.96/manifests/application.kubero.dev_kuberocouchdbs.yaml
operators/kubero-operator/0.0.96/manifests/application.kubero.dev_kuberoelasticsearches.yaml
operators/kubero-operator/0.0.96/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.0.96/manifests/application.kubero.dev_kuberokafkas.yaml
operators/kubero-operator/0.0.96/manifests/application.kubero.dev_kuberomongodbs.yaml
operators/kubero-operator/0.0.96/manifests/application.kubero.dev_kuberomysqls.yaml
operators/kubero-operator/0.0.96/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.0.96/manifests/application.kubero.dev_kuberopostgresqls.yaml
operators/kubero-operator/0.0.96/manifests/application.kubero.dev_kuberoredis.yaml
operators/kubero-operator/0.0.96/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.0.96/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.0.96/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.0.96/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.0.96/metadata/annotations.yaml
operators/kubero-operator/0.0.96/tests/scorecard/config.yaml

operator kubero-operator (0.0.96)

---

operators/kubero-operator/0.0.97/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.0.97/manifests/application.kubero.dev_kuberocouchdbs.yaml
operators/kubero-operator/0.0.97/manifests/application.kubero.dev_kuberoelasticsearches.yaml
operators/kubero-operator/0.0.97/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.0.97/manifests/application.kubero.dev_kuberokafkas.yaml
operators/kubero-operator/0.0.97/manifests/application.kubero.dev_kuberomongodbs.yaml
operators/kubero-operator/0.0.97/manifests/application.kubero.dev_kuberomysqls.yaml
operators/kubero-operator/0.0.97/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.0.97/manifests/application.kubero.dev_kuberopostgresqls.yaml
operators/kubero-operator/0.0.97/manifests/application.kubero.dev_kuberoredis.yaml
operators/kubero-operator/0.0.97/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.0.97/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.0.97/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.0.97/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.0.97/metadata/annotations.yaml
operators/kubero-operator/0.0.97/tests/scorecard/config.yaml

operator kubero-operator (0.0.97)

---

operators/mongodb-atlas-kubernetes/1.6.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/1.6.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/1.6.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/1.6.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/1.6.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/1.6.0/tests/scorecard/config.yaml

Signed-off-by: Igor Karpukhin <karpukhinigor@gmail.com>
--

operator mongodb-atlas-kubernetes (1.6.0)

---

operators/ndmspc-operator/0.2.2/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.2.2/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.2.2/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.2.2/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.2.2/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.2.2/metadata/annotations.yaml
operators/ndmspc-operator/0.2.2/tests/scorecard/config.yaml

operator ndmspc-operator (0.2.2)

---

operators/kubero-operator/0.0.99/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.0.99/manifests/application.kubero.dev_kuberocouchdbs.yaml
operators/kubero-operator/0.0.99/manifests/application.kubero.dev_kuberoelasticsearches.yaml
operators/kubero-operator/0.0.99/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.0.99/manifests/application.kubero.dev_kuberokafkas.yaml
operators/kubero-operator/0.0.99/manifests/application.kubero.dev_kuberomongodbs.yaml
operators/kubero-operator/0.0.99/manifests/application.kubero.dev_kuberomysqls.yaml
operators/kubero-operator/0.0.99/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.0.99/manifests/application.kubero.dev_kuberopostgresqls.yaml
operators/kubero-operator/0.0.99/manifests/application.kubero.dev_kuberoredis.yaml
operators/kubero-operator/0.0.99/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.0.99/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.0.99/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.0.99/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.0.99/metadata/annotations.yaml
operators/kubero-operator/0.0.99/tests/scorecard/config.yaml

operator kubero-operator (0.0.99)

---

operators/project-quay/3.8.1/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.1/quayecosystems.crd.yaml
operators/project-quay/3.8.1/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.8.1 to community operators

operator project-quay (3.8.1)

---

operators/mondoo-operator/1.11.0/k8s.mondoo.com_mondooauditconfigs.yaml
operators/mondoo-operator/1.11.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
operators/mondoo-operator/1.11.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
operators/mondoo-operator/1.11.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mondoo-operator/1.11.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/mondoo-operator/1.11.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
operators/mondoo-operator/1.11.0/mondoo-operator-manager-config_v1_configmap.yaml
operators/mondoo-operator/1.11.0/mondoo-operator-webhook_v1_serviceaccount.yaml
operators/mondoo-operator/1.11.0/mondoo-operator.clusterserviceversion.yaml
operators/mondoo-operator/mondoo-operator.package.yaml

operator mondoo-operator (1.11.0)

---

operators/portworx/1.10.2/core_v1_storagecluster_crd.yaml
operators/portworx/1.10.2/core_v1_storagenode_crd.yaml
operators/portworx/1.10.2/portworxoperator.clusterserviceversion.yaml
operators/portworx/ci.yaml
operators/portworx/portworx.package.yaml

operator [CI] portworx (1.10.2)

---

operators/awx-operator/1.1.4/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/1.1.4/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/1.1.4/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/1.1.4/manifests/awx-operator.v1.1.4.clusterserviceversion.yaml
operators/awx-operator/1.1.4/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/1.1.4/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/1.1.4/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/1.1.4/metadata/annotations.yaml
operators/awx-operator/1.1.4/tests/scorecard/config.yaml

Signed-off-by: Christian M. Adams <chadams@redhat.com>
--

operator awx-operator (1.1.4)

---

operators/netobserv-operator/1.0.1/manifests/flows.netobserv.io_flowcollectors.yaml
operators/netobserv-operator/1.0.1/manifests/netobserv-manager-config_v1_configmap.yaml
operators/netobserv-operator/1.0.1/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/netobserv-operator/1.0.1/manifests/netobserv-metrics-service_v1_service.yaml
operators/netobserv-operator/1.0.1/manifests/netobserv-operator.clusterserviceversion.yaml
operators/netobserv-operator/1.0.1/metadata/annotations.yaml

operator netobserv-operator (1.0.1)

---

operators/ndmspc-operator/0.2.3/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.2.3/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.2.3/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.2.3/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.2.3/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.2.3/metadata/annotations.yaml
operators/ndmspc-operator/0.2.3/tests/scorecard/config.yaml

operator ndmspc-operator (0.2.3)

---

operators/flux/0.38.3/manifests/alert.crd.yaml
operators/flux/0.38.3/manifests/bucket.crd.yaml
operators/flux/0.38.3/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
operators/flux/0.38.3/manifests/crd-controller-flux-system.clusterrole.yaml
operators/flux/0.38.3/manifests/crd-controller-flux-system.clusterrolebinding.yaml
operators/flux/0.38.3/manifests/flux.v0.38.3.clusterserviceversion.yaml
operators/flux/0.38.3/manifests/gitrepository.crd.yaml
operators/flux/0.38.3/manifests/helmchart.crd.yaml
operators/flux/0.38.3/manifests/helmrelease.crd.yaml
operators/flux/0.38.3/manifests/helmrepository.crd.yaml
operators/flux/0.38.3/manifests/imagepolicy.crd.yaml
operators/flux/0.38.3/manifests/imagerepository.crd.yaml
operators/flux/0.38.3/manifests/imageupdateautomation.crd.yaml
operators/flux/0.38.3/manifests/kustomization.crd.yaml
operators/flux/0.38.3/manifests/notification-controller.service.yaml
operators/flux/0.38.3/manifests/ocirepository.crd.yaml
operators/flux/0.38.3/manifests/provider.crd.yaml
operators/flux/0.38.3/manifests/receiver.crd.yaml
operators/flux/0.38.3/manifests/source-controller.service.yaml
operators/flux/0.38.3/manifests/webhook-receiver.service.yaml
operators/flux/0.38.3/metadata/annotations.yaml

operator flux (0.38.3)

---

operators/mongodb-atlas-kubernetes/1.6.1/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/1.6.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/1.6.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/1.6.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/1.6.1/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/1.6.1/tests/scorecard/config.yaml

Signed-off-by: fabritsius <antonfabritsius@gmail.com>
--

operator mongodb-atlas-kubernetes (1.6.1)

---

operators/portworx/1.10.3/core_v1_storagecluster_crd.yaml
operators/portworx/1.10.3/core_v1_storagenode_crd.yaml
operators/portworx/1.10.3/portworxoperator.clusterserviceversion.yaml
operators/portworx/portworx.package.yaml

operator portworx (1.10.3)

---

operators/mariadb-operator/0.6.4/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.6.4/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.6.4/metadata/annotations.yaml
operators/mariadb-operator/0.6.4/tests/scorecard/config.yaml
operators/mariadb-operator/ci.yaml

operator [N] [CI] mariadb-operator (0.6.4)

---

operators/camel-k/1.10.4/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/1.10.4/manifests/camel-k.v1.10.4.clusterserviceversion.yaml
operators/camel-k/1.10.4/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/1.10.4/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/1.10.4/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/1.10.4/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/1.10.4/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/1.10.4/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/1.10.4/metadata/annotations.yaml
operators/camel-k/1.10.4/tests/scorecard/config.yaml

operator [R] camel-k (1.10.4 1.11.0)

---

operators/camel-k/1.11.1/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/1.11.1/manifests/camel-k.v1.11.1.clusterserviceversion.yaml
operators/camel-k/1.11.1/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/1.11.1/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/1.11.1/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/1.11.1/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/1.11.1/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/1.11.1/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/1.11.1/metadata/annotations.yaml
operators/camel-k/1.11.1/tests/scorecard/config.yaml

operator camel-k (1.11.1)

---

operators/knative-operator/1.9.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.9.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.9.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.9.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.9.0/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.9.0/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.9.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.9.0/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.9.0/manifests/knative-operator.v1.9.0.clusterserviceversion.yaml
operators/knative-operator/1.9.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.9.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.9.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.9.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.9.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.9.0/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.9.0/metadata/annotations.yaml
operators/knative-operator/1.9.0/tests/scorecard/config.yaml

operator knative-operator (1.9.0)

---

operators/temporal-operator/0.11.0/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.11.0/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.11.0/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.11.0/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.11.0/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.11.0/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.11.0/metadata/annotations.yaml

operator temporal-operator (0.11.0)

---

operators/cass-operator-community/1.14.0/manifests/cass-operator-manager-config_v1_configmap.yaml
operators/cass-operator-community/1.14.0/manifests/cass-operator-webhook-service_v1_service.yaml
operators/cass-operator-community/1.14.0/manifests/cass-operator.clusterserviceversion.yaml
operators/cass-operator-community/1.14.0/manifests/cassandra.datastax.com_cassandradatacenters.yaml
operators/cass-operator-community/1.14.0/manifests/control.k8ssandra.io_cassandratasks.yaml
operators/cass-operator-community/1.14.0/metadata/annotations.yaml
operators/cass-operator-community/1.14.0/tests/scorecard/config.yaml

operator cass-operator-community (1.14.0)

---

operators/seldon-operator/ci.yaml

operator [CI] seldon-operator

---

operators/project-quay/3.9.0-nightly.20230202/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230202/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230202 to community operators

operator project-quay (3.9.0-nightly.20230202)

---

operators/opentelemetry-operator/0.68.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
operators/opentelemetry-operator/0.68.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/opentelemetry-operator/0.68.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
operators/opentelemetry-operator/0.68.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
operators/opentelemetry-operator/0.68.0/manifests/opentelemetry.io_instrumentations.yaml
operators/opentelemetry-operator/0.68.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
operators/opentelemetry-operator/0.68.0/metadata/annotations.yaml
operators/opentelemetry-operator/0.68.0/tests/scorecard/config.yaml

Signed-off-by: Israel Blancas <iblancasa@gmail.com>
Based on https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.68.0
https://github.com/open-telemetry/opentelemetry-operator/issues/1390

operator opentelemetry-operator (0.68.0)

---

operators/project-quay/3.9.0-nightly.20230203/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230203/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230203 to community operators

operator project-quay (3.9.0-nightly.20230203)

---

operators/tackle-operator/2.1.3/manifests/tackle-operator.clusterserviceversion.yaml
operators/tackle-operator/2.1.3/manifests/tackle.konveyor.io_addons.yaml
operators/tackle-operator/2.1.3/manifests/tackle.konveyor.io_tackles.yaml
operators/tackle-operator/2.1.3/metadata/annotations.yaml

operator tackle-operator (2.1.3)

---

operators/yaks/0.13.0/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.13.0/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.13.0/yaks.v0.13.0.clusterserviceversion.yaml
operators/yaks/yaks.package.yaml

operator yaks (0.13.0)

---

operators/project-quay/3.9.0-nightly.20230204/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230204/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230204 to community operators

operator project-quay (3.9.0-nightly.20230204)

---

operators/mariadb-operator/0.6.5/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.6.5/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.6.5/metadata/annotations.yaml
operators/mariadb-operator/0.6.5/tests/scorecard/config.yaml

Add operator mariadb-operator (0.6.5) to community operators

operator mariadb-operator (0.6.5)

---

operators/trivy-operator/0.11.0/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.0/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.0/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.0/trivy-operator.v0.11.0.clusterserviceversion.yaml
operators/trivy-operator/0.11.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.11.0)

---

operators/project-quay/3.9.0-nightly.20230206/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230206/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230206 to community operators

operator project-quay (3.9.0-nightly.20230206)

---

operators/mariadb-operator/0.6.6/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.6.6/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.6.6/metadata/annotations.yaml
operators/mariadb-operator/0.6.6/tests/scorecard/config.yaml

Add operator mariadb-operator (0.6.6) to community operators

operator mariadb-operator (0.6.6)

---

operators/flux/0.39.0/manifests/alert.crd.yaml
operators/flux/0.39.0/manifests/bucket.crd.yaml
operators/flux/0.39.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
operators/flux/0.39.0/manifests/crd-controller-flux-system.clusterrole.yaml
operators/flux/0.39.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
operators/flux/0.39.0/manifests/flux.v0.39.0.clusterserviceversion.yaml
operators/flux/0.39.0/manifests/gitrepository.crd.yaml
operators/flux/0.39.0/manifests/helmchart.crd.yaml
operators/flux/0.39.0/manifests/helmrelease.crd.yaml
operators/flux/0.39.0/manifests/helmrepository.crd.yaml
operators/flux/0.39.0/manifests/imagepolicy.crd.yaml
operators/flux/0.39.0/manifests/imagerepository.crd.yaml
operators/flux/0.39.0/manifests/imageupdateautomation.crd.yaml
operators/flux/0.39.0/manifests/kustomization.crd.yaml
operators/flux/0.39.0/manifests/notification-controller.service.yaml
operators/flux/0.39.0/manifests/ocirepository.crd.yaml
operators/flux/0.39.0/manifests/provider.crd.yaml
operators/flux/0.39.0/manifests/receiver.crd.yaml
operators/flux/0.39.0/manifests/source-controller.service.yaml
operators/flux/0.39.0/manifests/webhook-receiver.service.yaml
operators/flux/0.39.0/metadata/annotations.yaml

operator flux (0.39.0)

---

operators/project-quay/3.9.0-nightly.20230207/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230207/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230207 to community operators

operator project-quay (3.9.0-nightly.20230207)

---

operators/ovms-operator/1.1.0/Dockerfile
operators/ovms-operator/1.1.0/manifests/intel.com_model_servers.yaml
operators/ovms-operator/1.1.0/manifests/openvino-operator-controller-manager-metrics-service_v1_service.yaml
operators/ovms-operator/1.1.0/manifests/openvino-operator-manager-config_v1_configmap.yaml
operators/ovms-operator/1.1.0/manifests/openvino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ovms-operator/1.1.0/manifests/openvino-operator.clusterserviceversion.yaml
operators/ovms-operator/1.1.0/metadata/annotations.yaml
operators/ovms-operator/1.1.0/tests/scorecard/config.yaml

Signed-off-by: mzegla <milosz.zeglarski@intel.com>
--

operator ovms-operator (1.1.0)

---

operators/synapse-operator/0.4.0/Dockerfile
operators/synapse-operator/0.4.0/manifests/synapse-operator-controller-manager-metrics-service_v1_service.yaml
operators/synapse-operator/0.4.0/manifests/synapse-operator-manager-config_v1_configmap.yaml
operators/synapse-operator/0.4.0/manifests/synapse-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/synapse-operator/0.4.0/manifests/synapse-operator.clusterserviceversion.yaml
operators/synapse-operator/0.4.0/manifests/synapse.opdev.io_heisenbridges.yaml
operators/synapse-operator/0.4.0/manifests/synapse.opdev.io_mautrixsignals.yaml
operators/synapse-operator/0.4.0/manifests/synapse.opdev.io_synapses.yaml
operators/synapse-operator/0.4.0/metadata/annotations.yaml
operators/synapse-operator/0.4.0/tests/scorecard/config.yaml

operator synapse-operator (0.4.0)

---

operators/project-quay/3.9.0-nightly.20230208/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230208/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230208 to community operators

operator project-quay (3.9.0-nightly.20230208)

---

operators/rabbitmq-messaging-topology-operator/1.10.1/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_bindings.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_exchanges.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_federations.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_permissions.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_policies.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_queues.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_schemareplications.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_shovels.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_superstreams.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_topicpermissions.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_users.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_vhosts.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.webhook-service.yaml
operators/rabbitmq-messaging-topology-operator/1.10.1/metadata/annotations.yaml

operator rabbitmq-messaging-topology-operator (1.10.1)

---

operators/project-quay/3.9.0-nightly.20230209/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230209/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230209 to community operators

operator project-quay (3.9.0-nightly.20230209)

---

operators/yaks/0.14.1/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.14.1/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.14.1/yaks.v0.14.1.clusterserviceversion.yaml
operators/yaks/yaks.package.yaml

operator yaks (0.14.1)

---

operators/ndmspc-operator/ci.yaml

operator [CI] ndmspc-operator

---

operators/project-quay/3.9.0-nightly.20230210/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230210/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230210 to community operators

operator project-quay (3.9.0-nightly.20230210)

---

operators/ndmspc-operator/0.2.5/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.2.5/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.2.5/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.2.5/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.2.5/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.2.5/metadata/annotations.yaml
operators/ndmspc-operator/0.2.5/tests/scorecard/config.yaml

operator ndmspc-operator (0.2.5)

---

operators/kernel-module-management/1.0.0/manifests/kernel-module-management.clusterserviceversion.yaml
operators/kernel-module-management/1.0.0/manifests/kmm-operator-controller-manager-metrics-service_v1_service.yaml
operators/kernel-module-management/1.0.0/manifests/kmm-operator-device-plugin_v1_serviceaccount.yaml
operators/kernel-module-management/1.0.0/manifests/kmm-operator-manager-config_v1_configmap.yaml
operators/kernel-module-management/1.0.0/manifests/kmm-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kernel-module-management/1.0.0/manifests/kmm-operator-module-loader_v1_serviceaccount.yaml
operators/kernel-module-management/1.0.0/manifests/kmm.sigs.x-k8s.io_modules.yaml
operators/kernel-module-management/1.0.0/manifests/kmm.sigs.x-k8s.io_preflightvalidations.yaml
operators/kernel-module-management/1.0.0/metadata/annotations.yaml
operators/kernel-module-management/1.0.0/tests/scorecard/config.yaml
operators/kernel-module-management/ci.yaml

operator [N] [CI] kernel-module-management (1.0.0)

---

operators/ack-route53-controller/ci.yaml

operator [CI] ack-route53-controller

---

operators/grafana-operator/4.9.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml
operators/grafana-operator/4.9.0/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/4.9.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/4.9.0/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/4.9.0/integreatly.org_grafanadashboards.yaml
operators/grafana-operator/4.9.0/integreatly.org_grafanadatasources.yaml
operators/grafana-operator/4.9.0/integreatly.org_grafanafolders.yaml
operators/grafana-operator/4.9.0/integreatly.org_grafananotificationchannels.yaml
operators/grafana-operator/4.9.0/integreatly.org_grafanas.yaml
operators/grafana-operator/grafana-operator.package.yaml

operator grafana-operator (4.9.0)

---

operators/mariadb-operator/0.6.7/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.6.7/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.6.7/metadata/annotations.yaml
operators/mariadb-operator/0.6.7/tests/scorecard/config.yaml

Add operator mariadb-operator (0.6.7) to community operators

operator mariadb-operator (0.6.7)

---

operators/project-quay/3.9.0-nightly.20230211/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230211/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230211 to community operators

operator project-quay (3.9.0-nightly.20230211)

---

operators/project-quay/3.9.0-nightly.20230212/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230212/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230212 to community operators

operator project-quay (3.9.0-nightly.20230212)

---

operators/ack-ssm-controller/ci.yaml

operator [CI] ack-ssm-controller

---

operators/ibm-security-verify-directory-operator/23.2.0/manifests/ibm-security-verify-directory-operator.clusterserviceversion.yaml
operators/ibm-security-verify-directory-operator/23.2.0/manifests/ibm.com_ibmsecurityverifydirectories.yaml
operators/ibm-security-verify-directory-operator/23.2.0/manifests/verify-directory-operator-controller-manager-metrics-service_v1_service.yaml
operators/ibm-security-verify-directory-operator/23.2.0/manifests/verify-directory-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ibm-security-verify-directory-operator/23.2.0/manifests/verify-directory-operator-webhook-service_v1_service.yaml
operators/ibm-security-verify-directory-operator/23.2.0/metadata/annotations.yaml
operators/ibm-security-verify-directory-operator/23.2.0/tests/scorecard/config.yaml
operators/ibm-security-verify-directory-operator/ci.yaml

Signed-off-by: Scott Exton <scotte@au1.ibm.com>
--

operator [N] [CI] ibm-security-verify-directory-operator (23.2.0)

---

operators/gitlab-runner-operator/1.12.0/manifests/apps.gitlab.com_runners.yaml
operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml
operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml
operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml
operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-webhook-service_v1_service.yaml
operators/gitlab-runner-operator/1.12.0/metadata/annotations.yaml
operators/gitlab-runner-operator/1.12.0/tests/scorecard/config.yaml

Signed-off-by: Georgi N. Georgiev <ggeorgiev@gitlab.com>
--

operator gitlab-runner-operator (1.12.0)

---

operators/hive-operator/ci.yaml

Adding jstuever and lleshchi to hive-operator ci.yaml.

operator [CI] hive-operator

---

operators/project-quay/3.9.0-nightly.20230214/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230214/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230214 to community operators

operator project-quay (3.9.0-nightly.20230214)

---

operators/cloud-native-postgresql/1.17.4/manifests/cloud-native-postgresql.clusterserviceversion.yaml
operators/cloud-native-postgresql/1.17.4/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
operators/cloud-native-postgresql/1.17.4/manifests/postgresql-operator-webhook-service_v1_service.yaml
operators/cloud-native-postgresql/1.17.4/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
operators/cloud-native-postgresql/1.17.4/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
operators/cloud-native-postgresql/1.17.4/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
operators/cloud-native-postgresql/1.17.4/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
operators/cloud-native-postgresql/1.17.4/metadata/annotations.yaml
operators/cloud-native-postgresql/1.17.4/tests/scorecard/config.yaml

operator cloud-native-postgresql (1.17.4)

---

operators/cloud-native-postgresql/1.18.2/manifests/cloud-native-postgresql.clusterserviceversion.yaml
operators/cloud-native-postgresql/1.18.2/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
operators/cloud-native-postgresql/1.18.2/manifests/postgresql-operator-webhook-service_v1_service.yaml
operators/cloud-native-postgresql/1.18.2/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
operators/cloud-native-postgresql/1.18.2/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
operators/cloud-native-postgresql/1.18.2/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
operators/cloud-native-postgresql/1.18.2/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
operators/cloud-native-postgresql/1.18.2/metadata/annotations.yaml
operators/cloud-native-postgresql/1.18.2/tests/scorecard/config.yaml

operator cloud-native-postgresql (1.18.2)

---

operators/cloud-native-postgresql/1.19.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
operators/cloud-native-postgresql/1.19.0/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
operators/cloud-native-postgresql/1.19.0/manifests/postgresql-operator-webhook-service_v1_service.yaml
operators/cloud-native-postgresql/1.19.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
operators/cloud-native-postgresql/1.19.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
operators/cloud-native-postgresql/1.19.0/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
operators/cloud-native-postgresql/1.19.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
operators/cloud-native-postgresql/1.19.0/metadata/annotations.yaml
operators/cloud-native-postgresql/1.19.0/tests/scorecard/config.yaml

operator cloud-native-postgresql (1.19.0)

---

operators/project-quay/3.9.0-nightly.20230215/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230215/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230215 to community operators

operator project-quay (3.9.0-nightly.20230215)

---

operators/trivy-operator/0.11.1/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.1/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.1/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.1/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.1/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.1/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.1/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.1/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.11.1/trivy-operator.v0.11.1.clusterserviceversion.yaml
operators/trivy-operator/0.11.1/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.11.1)

---

operators/project-quay/3.9.0-nightly.20230216/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230216/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230216 to community operators

operator project-quay (3.9.0-nightly.20230216)

---

operators/awx-operator/ci.yaml

operator [CI] awx-operator

---

operators/awx-operator/1.2.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/1.2.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/1.2.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/1.2.0/manifests/awx-operator.v1.2.0.clusterserviceversion.yaml
operators/awx-operator/1.2.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/1.2.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/1.2.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/1.2.0/metadata/annotations.yaml
operators/awx-operator/1.2.0/tests/scorecard/config.yaml

operator awx-operator (1.2.0)

---

operators/project-quay/3.9.0-nightly.20230217/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230217/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230217 to community operators

operator project-quay (3.9.0-nightly.20230217)

---

operators/kube-green/0.5.0/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml
operators/kube-green/0.5.0/manifests/kube-green-manager-config_v1_configmap.yaml
operators/kube-green/0.5.0/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kube-green/0.5.0/manifests/kube-green-webhook-service_v1_service.yaml
operators/kube-green/0.5.0/manifests/kube-green.clusterserviceversion.yaml
operators/kube-green/0.5.0/manifests/kube-green.com_sleepinfos.yaml
operators/kube-green/0.5.0/metadata/annotations.yaml
operators/kube-green/0.5.0/tests/scorecard/config.yaml

operator kube-green (0.5.0)

---

operators/cluster-manager/0.10.0/cluster-manager.clusterserviceversion.yaml
operators/cluster-manager/0.10.0/operator.open-cluster-management.io_clustermanagers.yaml
operators/cluster-manager/cluster-manger.package.yaml

operator cluster-manager (0.10.0)

---

operators/klusterlet/0.10.0/klusterlet.clusterserviceversion.yaml
operators/klusterlet/0.10.0/operator.open-cluster-management.io_klusterlets.yaml
operators/klusterlet/klusterlet.package.yaml

operator klusterlet (0.10.0)

---

operators/project-quay/3.9.0-nightly.20230220/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230220/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230220 to community operators

operator project-quay (3.9.0-nightly.20230220)

---

operators/kiali/1.64.0/bundle.Dockerfile
operators/kiali/1.64.0/manifests/kiali.crd.yaml
operators/kiali/1.64.0/manifests/kiali.v1.64.0.clusterserviceversion.yaml
operators/kiali/1.64.0/metadata/annotations.yaml

operator kiali (1.64.0)

---

operators/flux/0.40.0/manifests/alert.crd.yaml
operators/flux/0.40.0/manifests/bucket.crd.yaml
operators/flux/0.40.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
operators/flux/0.40.0/manifests/crd-controller-flux-system.clusterrole.yaml
operators/flux/0.40.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
operators/flux/0.40.0/manifests/flux-edit-flux-system.clusterrole.yaml
operators/flux/0.40.0/manifests/flux-view-flux-system.clusterrole.yaml
operators/flux/0.40.0/manifests/flux.v0.40.0.clusterserviceversion.yaml
operators/flux/0.40.0/manifests/gitrepository.crd.yaml
operators/flux/0.40.0/manifests/helmchart.crd.yaml
operators/flux/0.40.0/manifests/helmrelease.crd.yaml
operators/flux/0.40.0/manifests/helmrepository.crd.yaml
operators/flux/0.40.0/manifests/imagepolicy.crd.yaml
operators/flux/0.40.0/manifests/imagerepository.crd.yaml
operators/flux/0.40.0/manifests/imageupdateautomation.crd.yaml
operators/flux/0.40.0/manifests/kustomization.crd.yaml
operators/flux/0.40.0/manifests/notification-controller.service.yaml
operators/flux/0.40.0/manifests/ocirepository.crd.yaml
operators/flux/0.40.0/manifests/provider.crd.yaml
operators/flux/0.40.0/manifests/receiver.crd.yaml
operators/flux/0.40.0/manifests/source-controller.service.yaml
operators/flux/0.40.0/manifests/webhook-receiver.service.yaml
operators/flux/0.40.0/metadata/annotations.yaml

operator flux (0.40.0)

---

operators/project-quay/3.9.0-nightly.20230221/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230221/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230221 to community operators

operator project-quay (3.9.0-nightly.20230221)

---

operators/function-mesh/0.11.0/bundle.Dockerfile
operators/function-mesh/0.11.0/manifests/compute.functionmesh.io_functionmeshes.yaml
operators/function-mesh/0.11.0/manifests/compute.functionmesh.io_functions.yaml
operators/function-mesh/0.11.0/manifests/compute.functionmesh.io_sinks.yaml
operators/function-mesh/0.11.0/manifests/compute.functionmesh.io_sources.yaml
operators/function-mesh/0.11.0/manifests/function-mesh-controller-manager-metrics-service_v1_service.yaml
operators/function-mesh/0.11.0/manifests/function-mesh-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/function-mesh/0.11.0/manifests/function-mesh-webhook-service_v1_service.yaml
operators/function-mesh/0.11.0/manifests/function-mesh.clusterserviceversion.yaml
operators/function-mesh/0.11.0/manifests/mesh-test-pulsar_v1_configmap.yaml
operators/function-mesh/0.11.0/manifests/test-auth_v1_secret.yaml
operators/function-mesh/0.11.0/manifests/test-pulsar_v1_configmap.yaml
operators/function-mesh/0.11.0/manifests/test-secret_v1_secret.yaml
operators/function-mesh/0.11.0/manifests/test-sink_v1_configmap.yaml
operators/function-mesh/0.11.0/manifests/test-source_v1_configmap.yaml
operators/function-mesh/0.11.0/manifests/test-tls_v1_secret.yaml
operators/function-mesh/0.11.0/metadata/annotations.yaml
operators/function-mesh/0.11.0/tests/scorecard/config.yaml

operator function-mesh (0.11.0)

---

operators/project-quay/3.8.2/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.2/quayecosystems.crd.yaml
operators/project-quay/3.8.2/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.8.2 to community operators

operator project-quay (3.8.2)

---

operators/mariadb-operator/0.7.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.7.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.7.0/metadata/annotations.yaml
operators/mariadb-operator/0.7.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.7.0) to community operators

operator mariadb-operator (0.7.0)

---

operators/mariadb-operator/0.7.0/manifests/mariadb-operator.clusterserviceversion.yaml

Add operator mariadb-operator (0.7.0) to community operators

operator [O] mariadb-operator (0.7.0)

---

operators/project-quay/3.7.11/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.7.11/quayecosystems.crd.yaml
operators/project-quay/3.7.11/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.7.11 to community operators

operator project-quay (3.7.11)

---

operators/ndmspc-operator/0.2.6/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.2.6/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.2.6/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.2.6/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.2.6/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.2.6/metadata/annotations.yaml
operators/ndmspc-operator/0.2.6/tests/scorecard/config.yaml

operator ndmspc-operator (0.2.6)

---

operators/portworx/1.10.4/core_v1_storagecluster_crd.yaml
operators/portworx/1.10.4/core_v1_storagenode_crd.yaml
operators/portworx/1.10.4/portworxoperator.clusterserviceversion.yaml
operators/portworx/portworx.package.yaml

operator portworx (1.10.4)

---

operators/project-quay/3.9.0-nightly.20230223/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230223/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230223 to community operators

operator project-quay (3.9.0-nightly.20230223)

---

operators/project-quay/3.9.0-nightly.20230224/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230224/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230224 to community operators

operator project-quay (3.9.0-nightly.20230224)

---

operators/project-quay/3.9.0-nightly.20230225/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230225/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230225 to community operators

operator project-quay (3.9.0-nightly.20230225)

---

operators/mariadb-operator/0.7.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.7.1/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.7.1/metadata/annotations.yaml
operators/mariadb-operator/0.7.1/tests/scorecard/config.yaml

Add operator mariadb-operator (0.7.1) to community operators

operator mariadb-operator (0.7.1)

---

operators/project-quay/3.9.0-nightly.20230226/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230226/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230226 to community operators

operator project-quay (3.9.0-nightly.20230226)

---

operators/mariadb-operator/0.8.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.8.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.8.0/metadata/annotations.yaml
operators/mariadb-operator/0.8.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.8.0) to community operators

operator mariadb-operator (0.8.0)

---

operators/druid-operator/1.0.0/druid-operator.v1.0.0.clusterserviceversion.yaml
operators/druid-operator/1.0.0/druid.apache.org_druids.yaml
operators/druid-operator/druid-operator.package.yaml

operator druid-operator (1.0.0)

---

operators/project-quay/3.9.0-nightly.20230227/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230227/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230227 to community operators

operator project-quay (3.9.0-nightly.20230227)

---

operators/camel-k/1.12.0/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/1.12.0/manifests/camel-k.v1.12.0.clusterserviceversion.yaml
operators/camel-k/1.12.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/1.12.0/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/1.12.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/1.12.0/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/1.12.0/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/1.12.0/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/1.12.0/metadata/annotations.yaml
operators/camel-k/1.12.0/tests/scorecard/config.yaml

operator camel-k (1.12.0)

---

operators/windup-operator/0.0.12/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.12/manifests/windup.crd.yaml
operators/windup-operator/0.0.12/metadata/annotations.yaml

operator windup-operator (0.0.12)

---

operators/yaks/0.14.2/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.14.2/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.14.2/yaks.v0.14.2.clusterserviceversion.yaml
operators/yaks/yaks.package.yaml

operator yaks (0.14.2)

---

operators/opentelemetry-operator/0.70.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
operators/opentelemetry-operator/0.70.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/opentelemetry-operator/0.70.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
operators/opentelemetry-operator/0.70.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
operators/opentelemetry-operator/0.70.0/manifests/opentelemetry.io_instrumentations.yaml
operators/opentelemetry-operator/0.70.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
operators/opentelemetry-operator/0.70.0/metadata/annotations.yaml
operators/opentelemetry-operator/0.70.0/tests/scorecard/config.yaml

operator opentelemetry-operator (0.70.0)

---

operators/keda/2.9.3/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.9.3/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.9.3/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.9.3/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.9.3/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.9.3/manifests/keda.v2.9.3.clusterserviceversion.yaml
operators/keda/2.9.3/metadata/annotations.yaml

operator keda (2.9.3)

---

operators/verticadb-operator/1.10.0/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/1.10.0/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/1.10.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/1.10.0/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/1.10.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/1.10.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/1.10.0/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/1.10.0/metadata/annotations.yaml
operators/verticadb-operator/1.10.0/tests/scorecard/config.yaml

operator verticadb-operator (1.10.0)

---

operators/project-quay/3.9.0-nightly.20230302/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230302/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230302 to community operators

operator project-quay (3.9.0-nightly.20230302)

---

operators/dynatrace-operator/0.10.3/Dockerfile
operators/dynatrace-operator/0.10.3/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/0.10.3/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/0.10.3/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml
operators/dynatrace-operator/0.10.3/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.10.3/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.10.3/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.10.3/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.10.3/metadata/annotations.yaml

operator dynatrace-operator (0.10.3)

---

operators/project-quay/3.9.0-nightly.20230303/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230303/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230303 to community operators

operator project-quay (3.9.0-nightly.20230303)

---

operators/ndmspc-operator/0.2.7/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.2.7/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.2.7/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.2.7/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.2.7/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.2.7/metadata/annotations.yaml
operators/ndmspc-operator/0.2.7/tests/scorecard/config.yaml

operator ndmspc-operator (0.2.7)

---

operators/mariadb-operator/0.9.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.9.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.9.0/metadata/annotations.yaml
operators/mariadb-operator/0.9.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.9.0) to community operators

operator mariadb-operator (0.9.0)

---

operators/project-quay/3.9.0-nightly.20230305/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230305/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230305 to community operators

operator project-quay (3.9.0-nightly.20230305)

---

operators/trivy-operator/0.12.0/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.0/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.0/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.0/trivy-operator.v0.12.0.clusterserviceversion.yaml
operators/trivy-operator/0.12.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.12.0)

---

operators/aqua/2022.4.9/bundle.Dockerfile
operators/aqua/2022.4.9/manifests/aqua-operator.v2022.4.9.clusterserviceversion.yaml
operators/aqua/2022.4.9/manifests/aquacsps.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.9/manifests/aquadatabases.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.9/manifests/aquaenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.9/manifests/aquagateways.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.9/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.9/manifests/aquascanners.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.9/manifests/aquaservers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.9/manifests/aquastarboards.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.9/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.9/manifests/configauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.9/metadata/annotations.yaml

operator aqua (2022.4.9)

---

operators/aqua/6.5.10/bundle.Dockerfile
operators/aqua/6.5.10/manifests/aqua-operator.v6.5.10.clusterserviceversion.yaml
operators/aqua/6.5.10/manifests/aquacsps.operator.aquasec.com.crd.yaml
operators/aqua/6.5.10/manifests/aquadatabases.operator.aquasec.com.crd.yaml
operators/aqua/6.5.10/manifests/aquaenforcers.operator.aquasec.com.crd.yaml
operators/aqua/6.5.10/manifests/aquagateways.operator.aquasec.com.crd.yaml
operators/aqua/6.5.10/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml
operators/aqua/6.5.10/manifests/aquascanners.operator.aquasec.com.crd.yaml
operators/aqua/6.5.10/manifests/aquaservers.operator.aquasec.com.crd.yaml
operators/aqua/6.5.10/manifests/aquastarboards.aquasecurity.github.io.crd.yaml
operators/aqua/6.5.10/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/6.5.10/manifests/configauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/6.5.10/metadata/annotations.yaml

operator aqua (6.5.10)

---

operators/awx-operator/1.3.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/1.3.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/1.3.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/1.3.0/manifests/awx-operator.v1.3.0.clusterserviceversion.yaml
operators/awx-operator/1.3.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/1.3.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/1.3.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/1.3.0/metadata/annotations.yaml
operators/awx-operator/1.3.0/tests/scorecard/config.yaml

operator awx-operator (1.3.0)

---

operators/project-quay/3.9.0-nightly.20230307/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230307/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230307 to community operators

operator project-quay (3.9.0-nightly.20230307)

---

operators/eginnovations-operator/0.0.5/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml
operators/eginnovations-operator/0.0.5/manifests/eginnovations-operator-manager-config_v1_configmap.yaml
operators/eginnovations-operator/0.0.5/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/eginnovations-operator/0.0.5/manifests/eginnovations-operator-webhook-service_v1_service.yaml
operators/eginnovations-operator/0.0.5/manifests/eginnovations-operator.clusterserviceversion.yaml
operators/eginnovations-operator/0.0.5/manifests/eginnovations.com_eguniversalagents.yaml
operators/eginnovations-operator/0.0.5/metadata/annotations.yaml
operators/eginnovations-operator/0.0.5/tests/scorecard/config.yaml

operator eginnovations-operator (0.0.5)

---

operators/stackgres-operator/1.4.3/manifests/stackgres-operator-controller-manager-metrics-service_v1_service.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres-operator.clusterserviceversion.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres.io_sgbackups.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres.io_sgclusters.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres.io_sgconfigs.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres.io_sgdbops.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres.io_sgdistributedlogs.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres.io_sginstanceprofiles.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres.io_sgobjectstorages.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres.io_sgpgconfigs.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres.io_sgpoolconfigs.yaml
operators/stackgres-operator/1.4.3/manifests/stackgres.io_sgscripts.yaml
operators/stackgres-operator/1.4.3/metadata/annotations.yaml
operators/stackgres-operator/1.4.3/tests/scorecard/config.yaml
operators/stackgres-operator/ci.yaml

operator [N] [CI] stackgres-operator (1.4.3)

---

operators/portworx/1.10.5/core_v1_storagecluster_crd.yaml
operators/portworx/1.10.5/core_v1_storagenode_crd.yaml
operators/portworx/1.10.5/portworxoperator.clusterserviceversion.yaml
operators/portworx/portworx.package.yaml

operator portworx (1.10.5)

---

operators/project-quay/3.9.0-nightly.20230308/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230308/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230308 to community operators

operator project-quay (3.9.0-nightly.20230308)

---

operators/project-quay/3.9.0-nightly.20230309/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230309/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230309 to community operators

operator project-quay (3.9.0-nightly.20230309)

---

operators/node-maintenance-operator/0.14.0/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml
operators/node-maintenance-operator/0.14.0/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/node-maintenance-operator/0.14.0/manifests/node-maintenance-operator-webhook-service_v1_service.yaml
operators/node-maintenance-operator/0.14.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
operators/node-maintenance-operator/0.14.0/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml
operators/node-maintenance-operator/0.14.0/metadata/annotations.yaml
operators/node-maintenance-operator/0.14.0/tests/scorecard/config.yaml

Let NMO v0.14.0 be available on OperatorHub.io
--

operator node-maintenance-operator (0.14.0)

---

operators/microcks/1.7.0/microcks-operator.v1.7.0.clusterserviceversion.yaml
operators/microcks/1.7.0/microcksinstall.crd.yaml
operators/microcks/microcks.package.yaml

operator microcks (1.7.0)

---

operators/stackgres/1.4.3/manifests/stackgres-controller-manager-metrics-service_v1_service.yaml
operators/stackgres/1.4.3/manifests/stackgres-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/stackgres/1.4.3/manifests/stackgres.clusterserviceversion.yaml
operators/stackgres/1.4.3/manifests/stackgres.io_sgbackups.yaml
operators/stackgres/1.4.3/manifests/stackgres.io_sgclusters.yaml
operators/stackgres/1.4.3/manifests/stackgres.io_sgconfigs.yaml
operators/stackgres/1.4.3/manifests/stackgres.io_sgdbops.yaml
operators/stackgres/1.4.3/manifests/stackgres.io_sgdistributedlogs.yaml
operators/stackgres/1.4.3/manifests/stackgres.io_sginstanceprofiles.yaml
operators/stackgres/1.4.3/manifests/stackgres.io_sgobjectstorages.yaml
operators/stackgres/1.4.3/manifests/stackgres.io_sgpgconfigs.yaml
operators/stackgres/1.4.3/manifests/stackgres.io_sgpoolconfigs.yaml
operators/stackgres/1.4.3/manifests/stackgres.io_sgscripts.yaml
operators/stackgres/1.4.3/metadata/annotations.yaml
operators/stackgres/1.4.3/tests/scorecard/config.yaml
operators/stackgres/ci.yaml

operator [N] [CI] stackgres (1.4.3)

---

operators/temporal-operator/0.12.0/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.12.0/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.12.0/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.12.0/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.12.0/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.12.0/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.12.0/metadata/annotations.yaml

operator temporal-operator (0.12.0)

---

operators/project-quay/3.9.0-nightly.20230310/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230310/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230310 to community operators

operator project-quay (3.9.0-nightly.20230310)

---

operators/opentelemetry-operator/0.71.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
operators/opentelemetry-operator/0.71.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/opentelemetry-operator/0.71.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
operators/opentelemetry-operator/0.71.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
operators/opentelemetry-operator/0.71.0/manifests/opentelemetry.io_instrumentations.yaml
operators/opentelemetry-operator/0.71.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
operators/opentelemetry-operator/0.71.0/metadata/annotations.yaml
operators/opentelemetry-operator/0.71.0/tests/scorecard/config.yaml

operator opentelemetry-operator (0.71.0)

---

operators/mariadb-operator/0.9.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.9.1/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.9.1/metadata/annotations.yaml
operators/mariadb-operator/0.9.1/tests/scorecard/config.yaml

Add operator mariadb-operator (0.9.1) to community operators

operator mariadb-operator (0.9.1)

---

operators/mariadb-operator/0.10.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.10.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.10.0/metadata/annotations.yaml
operators/mariadb-operator/0.10.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.10.0) to community operators

operator mariadb-operator (0.10.0)

---

operators/project-quay/3.9.0-nightly.20230311/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230311/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230311 to community operators

operator project-quay (3.9.0-nightly.20230311)

---

operators/ndmspc-operator/0.2.8/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.2.8/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.2.8/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.2.8/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.2.8/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.2.8/metadata/annotations.yaml
operators/ndmspc-operator/0.2.8/tests/scorecard/config.yaml

operator ndmspc-operator (0.2.8)

---

operators/project-quay/3.9.0-nightly.20230312/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230312/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230312 to community operators

operator project-quay (3.9.0-nightly.20230312)

---

operators/trivy-operator/0.12.1/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.1/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.1/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.1/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.1/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.1/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.1/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.1/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.12.1/trivy-operator.v0.12.1.clusterserviceversion.yaml
operators/trivy-operator/0.12.1/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.12.1)

---

operators/project-quay/3.9.0-nightly.20230314/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230314/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230314 to community operators

operator project-quay (3.9.0-nightly.20230314)

---

operators/apicast-community-operator/0.7.1/bundle.Dockerfile
operators/apicast-community-operator/0.7.1/manifests/apicast-operator-controller-manager-metrics-service_v1_service.yaml
operators/apicast-community-operator/0.7.1/manifests/apicast-operator.clusterserviceversion.yaml
operators/apicast-community-operator/0.7.1/manifests/apps.3scale.net_apicasts.yaml
operators/apicast-community-operator/0.7.1/metadata/annotations.yaml
operators/apicast-community-operator/0.7.1/tests/scorecard/config.yaml

operator apicast-community-operator (0.7.1)

---

operators/verticadb-operator/1.10.1/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/1.10.1/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/1.10.1/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/1.10.1/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/1.10.1/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/1.10.1/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/1.10.1/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/1.10.1/metadata/annotations.yaml
operators/verticadb-operator/1.10.1/tests/scorecard/config.yaml

operator verticadb-operator (1.10.1)

---

operators/grafana-operator/4.10.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml
operators/grafana-operator/4.10.0/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/4.10.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/4.10.0/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/4.10.0/integreatly.org_grafanadashboards.yaml
operators/grafana-operator/4.10.0/integreatly.org_grafanadatasources.yaml
operators/grafana-operator/4.10.0/integreatly.org_grafanafolders.yaml
operators/grafana-operator/4.10.0/integreatly.org_grafananotificationchannels.yaml
operators/grafana-operator/4.10.0/integreatly.org_grafanas.yaml
operators/grafana-operator/grafana-operator.package.yaml

operator grafana-operator (4.10.0)

---

operators/project-quay/3.9.0-nightly.20230315/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230315/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230315 to community operators

operator project-quay (3.9.0-nightly.20230315)

---

ci/pipeline-config-k8s.yaml

Changing secrets to a robot user

Change secrets to a robot user

---

operators/rabbitmq-cluster-operator/2.2.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.2.0/manifests/crds.yaml
operators/rabbitmq-cluster-operator/2.2.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.2.0/metadata/annotations.yaml

operator rabbitmq-cluster-operator (2.2.0)

---

operators/kiali/1.65.0/bundle.Dockerfile
operators/kiali/1.65.0/manifests/kiali.crd.yaml
operators/kiali/1.65.0/manifests/kiali.v1.65.0.clusterserviceversion.yaml
operators/kiali/1.65.0/metadata/annotations.yaml

operator kiali (1.65.0)

---

operators/project-quay/3.8.4/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.4/quayecosystems.crd.yaml
operators/project-quay/3.8.4/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.8.4 to community operators

operator project-quay (3.8.4)

---

operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmagents.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmalertmanagers.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmalerts.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmauths.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmclusters.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmnodescrapes.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmpodscrapes.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmprobes.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmrules.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmservicescrapes.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmsingles.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmstaticscrapes.yaml
operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmusers.yaml
operators/victoriametrics-operator/0.32.0/victoriametrics-operator.0.32.0.clusterserviceversion.yaml
operators/victoriametrics-operator/victoriametrics-operator.package.yaml

operator victoriametrics-operator (0.32.0)

---

operators/external-secrets-operator/0.8.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.8.0/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.8.0/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.8.0/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.8.0/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.8.0/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.8.0/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.8.0/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.8.0/metadata/annotations.yaml
operators/external-secrets-operator/0.8.0/tests/scorecard/config.yaml

bump external-secrets-operator 0.8.0

operator external-secrets-operator (0.8.0)

---

operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmagents.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmalertmanagers.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmalerts.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmauths.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmclusters.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmnodescrapes.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmpodscrapes.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmprobes.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmrules.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmservicescrapes.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmsingles.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmstaticscrapes.yaml
operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmusers.yaml
operators/victoriametrics-operator/0.32.1/victoriametrics-operator.0.32.1.clusterserviceversion.yaml
operators/victoriametrics-operator/victoriametrics-operator.package.yaml

operator victoriametrics-operator (0.32.1)

---

operators/external-secrets-operator/0.8.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.8.1/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.8.1/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.8.1/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.8.1/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.8.1/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.8.1/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.8.1/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.8.1/metadata/annotations.yaml
operators/external-secrets-operator/0.8.1/tests/scorecard/config.yaml

bump external-secrets-operator 0.8.1

operator external-secrets-operator (0.8.1)

---

operators/mariadb-operator/0.11.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.11.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.11.0/metadata/annotations.yaml
operators/mariadb-operator/0.11.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.11.0) to community operators

operator mariadb-operator (0.11.0)

---

operators/project-quay/3.9.0-nightly.20230319/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230319/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230319 to community operators

operator project-quay (3.9.0-nightly.20230319)

---

operators/project-quay/3.9.0-nightly.20230320/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230320/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230320 to community operators

operator project-quay (3.9.0-nightly.20230320)

---

operators/cc-operator/0.4.0/manifests/cc-operator-controller-manager-metrics-service_v1_service.yaml
operators/cc-operator/0.4.0/manifests/cc-operator-manager-config_v1_configmap.yaml
operators/cc-operator/0.4.0/manifests/cc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cc-operator/0.4.0/manifests/cc-operator.clusterserviceversion.yaml
operators/cc-operator/0.4.0/manifests/confidentialcontainers.org_ccruntimes.yaml
operators/cc-operator/0.4.0/metadata/annotations.yaml
operators/cc-operator/0.4.0/tests/scorecard/config.yaml

operator cc-operator (0.4.0)

---

operators/deployment-validation-operator/0.4.0/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.4.0/manifests/deploymentvalidationoperator.0.4.0.clusterserviceversion.yaml
operators/deployment-validation-operator/0.4.0/metadata/annotations.yaml
operators/deployment-validation-operator/0.4.0/tests/scorecard/config.yaml

operator deployment-validation-operator (0.4.0)

---

operators/metallb-operator/0.13.11/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
operators/metallb-operator/0.13.11/manifests/manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/metallb-operator/0.13.11/manifests/metallb-operator-webhook-server-cert_v1_secret.yaml
operators/metallb-operator/0.13.11/manifests/metallb-operator-webhook-service_v1_service.yaml
operators/metallb-operator/0.13.11/manifests/metallb-operator.clusterserviceversion.yaml
operators/metallb-operator/0.13.11/manifests/metallb.io_addresspools.yaml
operators/metallb-operator/0.13.11/manifests/metallb.io_bfdprofiles.yaml
operators/metallb-operator/0.13.11/manifests/metallb.io_bgpadvertisements.yaml
operators/metallb-operator/0.13.11/manifests/metallb.io_bgppeers.yaml
operators/metallb-operator/0.13.11/manifests/metallb.io_communities.yaml
operators/metallb-operator/0.13.11/manifests/metallb.io_ipaddresspools.yaml
operators/metallb-operator/0.13.11/manifests/metallb.io_l2advertisements.yaml
operators/metallb-operator/0.13.11/manifests/metallb.io_metallbs.yaml
operators/metallb-operator/0.13.11/manifests/speaker_v1_serviceaccount.yaml
operators/metallb-operator/0.13.11/manifests/webhook-server-cert_v1_secret.yaml
operators/metallb-operator/0.13.11/manifests/webhook-service_v1_service.yaml
operators/metallb-operator/0.13.11/metadata/annotations.yaml
operators/metallb-operator/0.13.11/tests/scorecard/config.yaml
operators/metallb-operator/ci.yaml

Adding the operator just released

operator [R] [CI] metallb-operator (0.13.11 0.13.3)

---

operators/project-quay/3.9.0-nightly.20230321/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230321/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230321 to community operators

operator project-quay (3.9.0-nightly.20230321)

---

operators/function-mesh/0.12.0/bundle.Dockerfile
operators/function-mesh/0.12.0/manifests/compute.functionmesh.io_connectorcatalogs.yaml
operators/function-mesh/0.12.0/manifests/compute.functionmesh.io_functionmeshes.yaml
operators/function-mesh/0.12.0/manifests/compute.functionmesh.io_functions.yaml
operators/function-mesh/0.12.0/manifests/compute.functionmesh.io_sinks.yaml
operators/function-mesh/0.12.0/manifests/compute.functionmesh.io_sources.yaml
operators/function-mesh/0.12.0/manifests/function-mesh-controller-manager-metrics-service_v1_service.yaml
operators/function-mesh/0.12.0/manifests/function-mesh-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/function-mesh/0.12.0/manifests/function-mesh-webhook-service_v1_service.yaml
operators/function-mesh/0.12.0/manifests/function-mesh.clusterserviceversion.yaml
operators/function-mesh/0.12.0/manifests/mesh-test-pulsar_v1_configmap.yaml
operators/function-mesh/0.12.0/manifests/test-auth_v1_secret.yaml
operators/function-mesh/0.12.0/manifests/test-pulsar_v1_configmap.yaml
operators/function-mesh/0.12.0/manifests/test-secret_v1_secret.yaml
operators/function-mesh/0.12.0/manifests/test-sink_v1_configmap.yaml
operators/function-mesh/0.12.0/manifests/test-source_v1_configmap.yaml
operators/function-mesh/0.12.0/manifests/test-tls_v1_secret.yaml
operators/function-mesh/0.12.0/metadata/annotations.yaml
operators/function-mesh/0.12.0/tests/scorecard/config.yaml

operator function-mesh (0.12.0)

---

operators/project-quay/3.9.0-nightly.20230324/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230324/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230324 to community operators

operator project-quay (3.9.0-nightly.20230324)

---

operators/mongodb-atlas-kubernetes/1.7.1/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/1.7.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/1.7.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/1.7.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/1.7.1/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/1.7.1/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (1.7.1)

---

operators/project-quay/3.9.0-nightly.20230325/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230325/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230325 to community operators

operator project-quay (3.9.0-nightly.20230325)

---

operators/security-profiles-operator/0.7.1/manifests/metrics-token_v1_secret.yaml
operators/security-profiles-operator/0.7.1/manifests/security-profiles-operator-profile_v1_configmap.yaml
operators/security-profiles-operator/0.7.1/manifests/security-profiles-operator.clusterserviceversion.yaml
operators/security-profiles-operator/0.7.1/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
operators/security-profiles-operator/0.7.1/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
operators/security-profiles-operator/0.7.1/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
operators/security-profiles-operator/0.7.1/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
operators/security-profiles-operator/0.7.1/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
operators/security-profiles-operator/0.7.1/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
operators/security-profiles-operator/0.7.1/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
operators/security-profiles-operator/0.7.1/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
operators/security-profiles-operator/0.7.1/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.7.1/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.7.1/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.7.1/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.7.1/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.7.1/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.7.1/manifests/spo-webhook_v1_serviceaccount.yaml
operators/security-profiles-operator/0.7.1/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.7.1/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.7.1/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.7.1/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.7.1/manifests/spod_v1_serviceaccount.yaml
operators/security-profiles-operator/0.7.1/metadata/annotations.yaml
operators/security-profiles-operator/0.7.1/tests/scorecard/config.yaml

Part of https://github.com/kubernetes-sigs/security-profiles-operator/issues/1574
--

operator security-profiles-operator (0.7.1)

---

operators/service-binding-operator/1.3.4/manifests/binding.operators.coreos.com_bindablekinds.yaml
operators/service-binding-operator/1.3.4/manifests/binding.operators.coreos.com_servicebindings.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-clusterworkloadresourcemappings-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-clusterworkloadresourcemappings-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-manager-config_v1_configmap.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-operator.clusterserviceversion.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.3.4/manifests/service-binding-webhook-service_v1_service.yaml
operators/service-binding-operator/1.3.4/manifests/servicebinding.io_clusterworkloadresourcemappings.yaml
operators/service-binding-operator/1.3.4/manifests/servicebinding.io_servicebindings.yaml
operators/service-binding-operator/1.3.4/metadata/annotations.yaml
operators/service-binding-operator/1.3.4/tests/scorecard/config.yaml

operator service-binding-operator (1.3.4)

---

operators/loki-operator/0.2.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
operators/loki-operator/0.2.0/manifests/loki-operator-manager-config_v1_configmap.yaml
operators/loki-operator/0.2.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/loki-operator/0.2.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
operators/loki-operator/0.2.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/loki-operator/0.2.0/manifests/loki-operator-webhook-service_v1_service.yaml
operators/loki-operator/0.2.0/manifests/loki-operator.clusterserviceversion.yaml
operators/loki-operator/0.2.0/manifests/loki.grafana.com_alertingrules.yaml
operators/loki-operator/0.2.0/manifests/loki.grafana.com_lokistacks.yaml
operators/loki-operator/0.2.0/manifests/loki.grafana.com_recordingrules.yaml
operators/loki-operator/0.2.0/manifests/loki.grafana.com_rulerconfigs.yaml
operators/loki-operator/0.2.0/metadata/annotations.yaml
operators/loki-operator/0.2.0/tests/scorecard/config.yaml

operator loki-operator (0.2.0)

---

operators/yaks/0.14.3/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.14.3/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.14.3/yaks.v0.14.3.clusterserviceversion.yaml
operators/yaks/yaks.package.yaml

operator yaks (0.14.3)

---

operators/project-quay/3.9.0-nightly.20230329/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230329/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230329 to community operators

operator project-quay (3.9.0-nightly.20230329)

---

operators/project-quay/3.8.5/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.5/quayecosystems.crd.yaml
operators/project-quay/3.8.5/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.8.5 to community operators

operator project-quay (3.8.5)

---

operators/opentelemetry-operator/0.74.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
operators/opentelemetry-operator/0.74.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/opentelemetry-operator/0.74.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
operators/opentelemetry-operator/0.74.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
operators/opentelemetry-operator/0.74.0/manifests/opentelemetry.io_instrumentations.yaml
operators/opentelemetry-operator/0.74.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
operators/opentelemetry-operator/0.74.0/metadata/annotations.yaml
operators/opentelemetry-operator/0.74.0/tests/scorecard/config.yaml

Supersedes https://github.com/k8s-operatorhub/community-operators/pull/2560#issuecomment-1490408938 
--

operator opentelemetry-operator (0.74.0)

---

operators/flux/0.41.2/manifests/alert.crd.yaml
operators/flux/0.41.2/manifests/bucket.crd.yaml
operators/flux/0.41.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
operators/flux/0.41.2/manifests/crd-controller-flux-system.clusterrole.yaml
operators/flux/0.41.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml
operators/flux/0.41.2/manifests/flux-edit-flux-system.clusterrole.yaml
operators/flux/0.41.2/manifests/flux-view-flux-system.clusterrole.yaml
operators/flux/0.41.2/manifests/flux.v0.41.2.clusterserviceversion.yaml
operators/flux/0.41.2/manifests/gitrepository.crd.yaml
operators/flux/0.41.2/manifests/helmchart.crd.yaml
operators/flux/0.41.2/manifests/helmrelease.crd.yaml
operators/flux/0.41.2/manifests/helmrepository.crd.yaml
operators/flux/0.41.2/manifests/imagepolicy.crd.yaml
operators/flux/0.41.2/manifests/imagerepository.crd.yaml
operators/flux/0.41.2/manifests/imageupdateautomation.crd.yaml
operators/flux/0.41.2/manifests/kustomization.crd.yaml
operators/flux/0.41.2/manifests/notification-controller.service.yaml
operators/flux/0.41.2/manifests/ocirepository.crd.yaml
operators/flux/0.41.2/manifests/provider.crd.yaml
operators/flux/0.41.2/manifests/receiver.crd.yaml
operators/flux/0.41.2/manifests/source-controller.service.yaml
operators/flux/0.41.2/manifests/webhook-receiver.service.yaml
operators/flux/0.41.2/metadata/annotations.yaml

operator flux (0.41.2)

---

operators/elastic-cloud-eck/2.7.0/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.7.0/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.7.0/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.7.0/elastic-cloud-eck.v2.7.0.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.7.0/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.7.0/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.7.0/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.7.0/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.7.0/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.7.0/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml

Update the ECK operator to the latest version `2.7.0`.

operator elastic-cloud-eck (2.7.0)

---

operators/project-quay/3.9.0-nightly.20230401/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230401/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230401 to community operators

operator project-quay (3.9.0-nightly.20230401)

---

operators/project-quay/3.9.0-nightly.20230402/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230402/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230402 to community operators

operator project-quay (3.9.0-nightly.20230402)

---

operators/edp-keycloak-operator/1.15.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.15.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.15.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.15.0/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.15.0)

---

operators/trivy-operator/0.13.0/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.0/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.0/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.0/trivy-operator.v0.13.0.clusterserviceversion.yaml
operators/trivy-operator/0.13.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.13.0)

---

operators/dell-csm-operator/1.1.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.1.0/manifests/dell-csm-operator.v1.1.0.clusterserviceversion.yaml
operators/dell-csm-operator/1.1.0/metadata/annotations.yaml
operators/dell-csm-operator/1.1.0/tests/scorecard/config.yaml

operator dell-csm-operator (1.1.0)

---

operators/pulsar-operator/0.16.0/bundle.Dockerfile
operators/pulsar-operator/0.16.0/manifests/pulsar-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulsar-operator/0.16.0/manifests/pulsar-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulsar-operator/0.16.0/manifests/pulsar-operator-pulsar-broker_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulsar-operator/0.16.0/manifests/pulsar-operator.clusterserviceversion.yaml
operators/pulsar-operator/0.16.0/manifests/pulsar.streamnative.io_pulsarbrokers.yaml
operators/pulsar-operator/0.16.0/manifests/pulsar.streamnative.io_pulsarproxies.yaml
operators/pulsar-operator/0.16.0/metadata/annotations.yaml
operators/pulsar-operator/0.16.0/tests/scorecard/config.yaml

Signed-off-by: streamnativebot [streamnativebot@streamnative.io](mailto:streamnativebot@streamnative.io)
--
1 If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need
2 For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

operator pulsar-operator (0.16.0)

---

operators/bookkeeper-operator/0.16.0/bundle.Dockerfile
operators/bookkeeper-operator/0.16.0/manifests/bookkeeper-operator-controller-manager-metrics-service_v1_service.yaml
operators/bookkeeper-operator/0.16.0/manifests/bookkeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bookkeeper-operator/0.16.0/manifests/bookkeeper-operator.clusterserviceversion.yaml
operators/bookkeeper-operator/0.16.0/manifests/bookkeeper.streamnative.io_bookkeeperclusters.yaml
operators/bookkeeper-operator/0.16.0/metadata/annotations.yaml
operators/bookkeeper-operator/0.16.0/tests/scorecard/config.yaml

Signed-off-by: streamnativebot [streamnativebot@streamnative.io](mailto:streamnativebot@streamnative.io)
--
1 If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need
2 For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

operator bookkeeper-operator (0.16.0)

---

operators/zookeeper-operator/0.16.0/bundle.Dockerfile
operators/zookeeper-operator/0.16.0/manifests/zookeeper-operator-controller-manager-metrics-service_v1_service.yaml
operators/zookeeper-operator/0.16.0/manifests/zookeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/zookeeper-operator/0.16.0/manifests/zookeeper-operator.clusterserviceversion.yaml
operators/zookeeper-operator/0.16.0/manifests/zookeeper.streamnative.io_zookeeperclusters.yaml
operators/zookeeper-operator/0.16.0/metadata/annotations.yaml
operators/zookeeper-operator/0.16.0/tests/scorecard/config.yaml

Signed-off-by: streamnativebot [streamnativebot@streamnative.io](mailto:streamnativebot@streamnative.io)
--
1 If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need
2 For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

operator zookeeper-operator (0.16.0)

---

operators/sn-operator/0.2.0-rc2/bundle.Dockerfile
operators/sn-operator/0.2.0-rc2/manifests/k8s.streamnative.io_flinks.yaml
operators/sn-operator/0.2.0-rc2/manifests/k8s.streamnative.io_pfsqlclusters.yaml
operators/sn-operator/0.2.0-rc2/manifests/k8s.streamnative.io_pulsarcoordinators.yaml
operators/sn-operator/0.2.0-rc2/manifests/k8s.streamnative.io_snconsoles.yaml
operators/sn-operator/0.2.0-rc2/manifests/sn-operator-controller-manager-metrics-service_v1_service.yaml
operators/sn-operator/0.2.0-rc2/manifests/sn-operator-global-config_v1_configmap.yaml
operators/sn-operator/0.2.0-rc2/manifests/sn-operator-manager-config_v1_configmap.yaml
operators/sn-operator/0.2.0-rc2/manifests/sn-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/sn-operator/0.2.0-rc2/manifests/sn-operator-troubleshooting-template-jvm_v1_configmap.yaml
operators/sn-operator/0.2.0-rc2/manifests/sn-operator-troubleshooting-template-pulsar_v1_configmap.yaml
operators/sn-operator/0.2.0-rc2/manifests/sn-operator-troubleshooting-template-system_v1_configmap.yaml
operators/sn-operator/0.2.0-rc2/manifests/sn-operator-webhook-service_v1_service.yaml
operators/sn-operator/0.2.0-rc2/manifests/sn-operator.clusterserviceversion.yaml
operators/sn-operator/0.2.0-rc2/metadata/annotations.yaml
operators/sn-operator/0.2.0-rc2/tests/scorecard/config.yaml

--
1 If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need
2 For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

operator sn-operator (0.2.0-rc2)

---

operators/verticadb-operator/1.10.2/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/1.10.2/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/1.10.2/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/1.10.2/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/1.10.2/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/1.10.2/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/1.10.2/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/1.10.2/metadata/annotations.yaml
operators/verticadb-operator/1.10.2/tests/scorecard/config.yaml

operator verticadb-operator (1.10.2)

---

operators/konveyor-operator/0.1.0/manifests/konveyor-operator.clusterserviceversion.yaml
operators/konveyor-operator/0.1.0/manifests/tackle.konveyor.io_addons.yaml
operators/konveyor-operator/0.1.0/manifests/tackle.konveyor.io_tackles.yaml
operators/konveyor-operator/0.1.0/metadata/annotations.yaml
operators/konveyor-operator/ci.yaml

operator [N] [CI] konveyor-operator (0.1.0)

---

operators/ibm-security-verify-directory-operator/23.4.0/manifests/ibm-security-verify-directory-operator.clusterserviceversion.yaml
operators/ibm-security-verify-directory-operator/23.4.0/manifests/ibm.com_ibmsecurityverifydirectories.yaml
operators/ibm-security-verify-directory-operator/23.4.0/manifests/verify-directory-operator-controller-manager-metrics-service_v1_service.yaml
operators/ibm-security-verify-directory-operator/23.4.0/manifests/verify-directory-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ibm-security-verify-directory-operator/23.4.0/manifests/verify-directory-operator-webhook-service_v1_service.yaml
operators/ibm-security-verify-directory-operator/23.4.0/metadata/annotations.yaml
operators/ibm-security-verify-directory-operator/23.4.0/tests/scorecard/config.yaml

operator ibm-security-verify-directory-operator (23.4.0)

---

operators/cockroachdb/6.0.0/bundle.Dockerfile
operators/cockroachdb/6.0.0/manifests/charts.operatorhub.io_cockroachdbs.yaml
operators/cockroachdb/6.0.0/manifests/cockroachdb-controller-manager-metrics-service_v1_service.yaml
operators/cockroachdb/6.0.0/manifests/cockroachdb-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cockroachdb/6.0.0/manifests/cockroachdb.clusterserviceversion.yaml
operators/cockroachdb/6.0.0/metadata/annotations.yaml
operators/cockroachdb/6.0.0/tests/scorecard/config.yaml

operator cockroachdb (6.0.0)

---

operators/cc-operator/0.5.0/manifests/cc-operator-controller-manager-metrics-service_v1_service.yaml
operators/cc-operator/0.5.0/manifests/cc-operator-manager-config_v1_configmap.yaml
operators/cc-operator/0.5.0/manifests/cc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cc-operator/0.5.0/manifests/cc-operator.clusterserviceversion.yaml
operators/cc-operator/0.5.0/manifests/confidentialcontainers.org_ccruntimes.yaml
operators/cc-operator/0.5.0/metadata/annotations.yaml
operators/cc-operator/0.5.0/tests/scorecard/config.yaml

* [ x] Modify more than one operator
* [ x] Modify an Operator you don't own
* [ x] Rename an operator - please remove and add with a different name instead
* [ x] Modify any files outside the above mentioned folders
* [ x] Contain more than one commit. **Please squash your commits.**
1. [ x] Description about the managed Application and where to find more information
2. [ x] Features and capabilities of your Operator and how to use it
3. [ x] Any manual steps about potential pre-requisites for using your Operator
* [ x] Human readable name and 1-liner description about your Operator
* [ x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-o …

operator cc-operator (0.5.0)

---

operators/windup-operator/0.0.13/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.13/manifests/windup.crd.yaml
operators/windup-operator/0.0.13/metadata/annotations.yaml

operator windup-operator (0.0.13)

---

operators/searchpe-operator/4.1.0/manifests/searchpe-operator.clusterserviceversion.yaml

operator [O] searchpe-operator (4.1.0)

---

operators/searchpe-operator/4.1.1/manifests/searchpe-operator.clusterserviceversion.yaml

operator [O] searchpe-operator (4.1.1)

---

operators/security-profiles-operator/0.8.0/manifests/metrics-token_v1_secret.yaml
operators/security-profiles-operator/0.8.0/manifests/security-profiles-operator-profile_v1_configmap.yaml
operators/security-profiles-operator/0.8.0/manifests/security-profiles-operator.clusterserviceversion.yaml
operators/security-profiles-operator/0.8.0/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
operators/security-profiles-operator/0.8.0/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
operators/security-profiles-operator/0.8.0/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
operators/security-profiles-operator/0.8.0/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
operators/security-profiles-operator/0.8.0/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
operators/security-profiles-operator/0.8.0/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
operators/security-profiles-operator/0.8.0/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
operators/security-profiles-operator/0.8.0/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
operators/security-profiles-operator/0.8.0/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.0/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.8.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.8.0/manifests/spo-webhook_v1_serviceaccount.yaml
operators/security-profiles-operator/0.8.0/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.0/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.0/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.8.0/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.8.0/manifests/spod_v1_serviceaccount.yaml
operators/security-profiles-operator/0.8.0/metadata/annotations.yaml
operators/security-profiles-operator/0.8.0/tests/scorecard/config.yaml

operator security-profiles-operator (0.8.0)

---

operators/parseable-operator/0.0.2/parseable-operator.v0.0.2.clusterserviceversion.yaml
operators/parseable-operator/0.0.2/parseable.io_parseabletenants.yaml
operators/parseable-operator/ci.yaml
operators/parseable-operator/parseable-operator.package.yaml

operator [N] [CI] parseable-operator (0.0.2)

---

operators/kube-loxilb-operator/0.8.3/manifests/kube-loxilb-operator-controller-manager-metrics-service_v1_service.yaml
operators/kube-loxilb-operator/0.8.3/manifests/kube-loxilb-operator-kube-loxilb_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kube-loxilb-operator/0.8.3/manifests/kube-loxilb-operator-kube-loxilb_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/kube-loxilb-operator/0.8.3/manifests/kube-loxilb-operator-kube-loxilb_v1_serviceaccount.yaml
operators/kube-loxilb-operator/0.8.3/manifests/kube-loxilb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kube-loxilb-operator/0.8.3/manifests/kube-loxilb-operator.clusterserviceversion.yaml
operators/kube-loxilb-operator/0.8.3/manifests/kubeloxilb.loxilb.io_kubeloxilbapps.yaml
operators/kube-loxilb-operator/0.8.3/metadata/annotations.yaml
operators/kube-loxilb-operator/0.8.3/tests/scorecard/config.yaml
operators/kube-loxilb-operator/ci.yaml

Signed-off-by: backguynn <backguyn@netlox.io>
--

operator [N] [CI] kube-loxilb-operator (0.8.3)

---

operators/argocd-operator/0.6.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml
operators/argocd-operator/0.6.0/argocd-operator-manager-config_v1_configmap.yaml
operators/argocd-operator/0.6.0/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/argocd-operator/0.6.0/argocd-operator.v0.6.0.clusterserviceversion.yaml
operators/argocd-operator/0.6.0/argoproj.io_applications.yaml
operators/argocd-operator/0.6.0/argoproj.io_applicationsets.yaml
operators/argocd-operator/0.6.0/argoproj.io_appprojects.yaml
operators/argocd-operator/0.6.0/argoproj.io_argocdexports.yaml
operators/argocd-operator/0.6.0/argoproj.io_argocds.yaml
operators/argocd-operator/argocd-operator.package.yaml

* [x ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
-- …

operator argocd-operator (0.6.0)

---

operators/dynatrace-operator/0.11.0/Dockerfile
operators/dynatrace-operator/0.11.0/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/0.11.0/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/0.11.0/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml
operators/dynatrace-operator/0.11.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.11.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.11.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.11.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.11.0/metadata/annotations.yaml

operator dynatrace-operator (0.11.0)

---

operators/loki-operator/0.3.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
operators/loki-operator/0.3.0/manifests/loki-operator-manager-config_v1_configmap.yaml
operators/loki-operator/0.3.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/loki-operator/0.3.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
operators/loki-operator/0.3.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/loki-operator/0.3.0/manifests/loki-operator-webhook-service_v1_service.yaml
operators/loki-operator/0.3.0/manifests/loki-operator.clusterserviceversion.yaml
operators/loki-operator/0.3.0/manifests/loki.grafana.com_alertingrules.yaml
operators/loki-operator/0.3.0/manifests/loki.grafana.com_lokistacks.yaml
operators/loki-operator/0.3.0/manifests/loki.grafana.com_recordingrules.yaml
operators/loki-operator/0.3.0/manifests/loki.grafana.com_rulerconfigs.yaml
operators/loki-operator/0.3.0/metadata/annotations.yaml
operators/loki-operator/0.3.0/tests/scorecard/config.yaml

operator loki-operator (0.3.0)

---

operators/pubsubplus-eventbroker-operator/1.0.0/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
operators/pubsubplus-eventbroker-operator/1.0.0/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
operators/pubsubplus-eventbroker-operator/1.0.0/metadata/annotations.yaml
operators/pubsubplus-eventbroker-operator/1.0.0/tests/scorecard/config.yaml
operators/pubsubplus-eventbroker-operator/ci.yaml

operator [N] [CI] pubsubplus-eventbroker-operator (1.0.0)

---

operators/trivy-operator/0.13.1/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.1/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.1/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.1/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.1/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.1/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.1/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.1/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.1/trivy-operator.v0.13.1.clusterserviceversion.yaml
operators/trivy-operator/0.13.1/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.13.1)

---

operators/gitlab-operator-kubernetes/0.19.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.19.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.19.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.19.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.19.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.19.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.19.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.19.0)

---

operators/project-quay/3.8.6/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.6/quayecosystems.crd.yaml
operators/project-quay/3.8.6/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.8.6 to community operators

operator project-quay (3.8.6)

---

operators/yaks/0.15.0/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.15.0/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.15.0/yaks.v0.15.0.clusterserviceversion.yaml
operators/yaks/yaks.package.yaml

operator yaks (0.15.0)

---

operators/trivy-operator/0.13.2/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.2/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.2/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.2/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.2/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.2/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.2/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.2/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.13.2/trivy-operator.v0.13.2.clusterserviceversion.yaml
operators/trivy-operator/0.13.2/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.13.2)

---

operators/pulp-operator/1.0.0-alpha.6/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.0.0-alpha.6/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.0.0-alpha.6/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-alpha.6/manifests/pulp-operator.clusterserviceversion.yaml
operators/pulp-operator/1.0.0-alpha.6/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.0.0-alpha.6/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.0.0-alpha.6/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.0.0-alpha.6/metadata/annotations.yaml
operators/pulp-operator/1.0.0-alpha.6/tests/scorecard/config.yaml

operator pulp-operator (1.0.0-alpha.6)

---

operators/galaxy-operator/ci.yaml

operator [CI] galaxy-operator

---

operators/knative-operator/1.10.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.10.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.10.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.10.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.10.0/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.10.0/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.10.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.10.0/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.10.0/manifests/knative-operator.v1.10.0.clusterserviceversion.yaml
operators/knative-operator/1.10.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.10.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.10.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.10.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.10.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.10.0/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.10.0/metadata/annotations.yaml
operators/knative-operator/1.10.0/tests/scorecard/config.yaml

operator knative-operator (1.10.0)

---

operators/clickhouse/0.18.4/clickhouse-operator.v0.18.4.clusterserviceversion.yaml
operators/clickhouse/0.18.4/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.18.4/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.18.4/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/clickhouse.package.yaml

operator clickhouse (0.18.4)

---

operators/dynatrace-operator/0.11.1/Dockerfile
operators/dynatrace-operator/0.11.1/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/0.11.1/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/0.11.1/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml
operators/dynatrace-operator/0.11.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.11.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.11.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.11.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.11.1/metadata/annotations.yaml

operator dynatrace-operator (0.11.1)

---

operators/project-quay/3.9.0-nightly.20230429/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230429/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230429 to community operators

operator project-quay (3.9.0-nightly.20230429)

---

operators/rabbitmq-messaging-topology-operator/1.10.3/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_bindings.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_exchanges.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_federations.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_permissions.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_policies.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_queues.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_schemareplications.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_shovels.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_superstreams.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_topicpermissions.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_users.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_vhosts.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.webhook-service.yaml
operators/rabbitmq-messaging-topology-operator/1.10.3/metadata/annotations.yaml

operator rabbitmq-messaging-topology-operator (1.10.3)

---

operators/self-node-remediation/0.6.0/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml
operators/self-node-remediation/0.6.0/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.6.0/manifests/self-node-remediation-manager-config_v1_configmap.yaml
operators/self-node-remediation/0.6.0/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.6.0/manifests/self-node-remediation-webhook-service_v1_service.yaml
operators/self-node-remediation/0.6.0/manifests/self-node-remediation.clusterserviceversion.yaml
operators/self-node-remediation/0.6.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
operators/self-node-remediation/0.6.0/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
operators/self-node-remediation/0.6.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
operators/self-node-remediation/0.6.0/metadata/annotations.yaml
operators/self-node-remediation/0.6.0/tests/scorecard/config.yaml
operators/self-node-remediation/ci.yaml

operator [CI] self-node-remediation (0.6.0)

---

operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmagents.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmalertmanagers.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmalerts.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmauths.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmclusters.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmnodescrapes.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmpodscrapes.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmprobes.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmrules.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmservicescrapes.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmsingles.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmstaticscrapes.yaml
operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmusers.yaml
operators/victoriametrics-operator/0.33.0/victoriametrics-operator.0.33.0.clusterserviceversion.yaml
operators/victoriametrics-operator/victoriametrics-operator.package.yaml

operator victoriametrics-operator (0.33.0)

---

operators/seldon-operator/1.16.0/manifests/machinelearning.seldon.io_seldondeployments.yaml
operators/seldon-operator/1.16.0/manifests/seldon-operator.clusterserviceversion.yaml
operators/seldon-operator/1.16.0/metadata/annotations.yaml
operators/seldon-operator/1.16.0/tests/scorecard/config.yaml

operator seldon-operator (1.16.0)

---

operators/windup-operator/0.0.14/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.14/manifests/windup.crd.yaml
operators/windup-operator/0.0.14/metadata/annotations.yaml

operator windup-operator (0.0.14)

---

operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml
operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml
operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-operator-manager-config_v1_configmap.yaml
operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-operator-webhook-service_v1_service.yaml
operators/aerospike-kubernetes-operator/2.5.0/manifests/asdb.aerospike.com_aerospikeclusters.yaml
operators/aerospike-kubernetes-operator/2.5.0/metadata/annotations.yaml
operators/aerospike-kubernetes-operator/2.5.0/tests/scorecard/config.yaml

operator aerospike-kubernetes-operator (2.5.0)

---

operators/mariadb-operator/0.12.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.12.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.12.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.12.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.12.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.12.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.12.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.12.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.12.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.12.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.12.0/metadata/annotations.yaml
operators/mariadb-operator/0.12.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.12.0) to community operators

operator mariadb-operator (0.12.0)

---

operators/node-healthcheck-operator/0.5.0/manifests/node-healthcheck-controller-manager-metrics-service_v1_service.yaml
operators/node-healthcheck-operator/0.5.0/manifests/node-healthcheck-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/node-healthcheck-operator/0.5.0/manifests/node-healthcheck-operator.clusterserviceversion.yaml
operators/node-healthcheck-operator/0.5.0/manifests/node-healthcheck-webhook-service_v1_service.yaml
operators/node-healthcheck-operator/0.5.0/manifests/remediation.medik8s.io_nodehealthchecks.yaml
operators/node-healthcheck-operator/0.5.0/metadata/annotations.yaml
operators/node-healthcheck-operator/0.5.0/metadata/dependencies.yaml
operators/node-healthcheck-operator/0.5.0/tests/scorecard/config.yaml

* [n/a] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
1. [n/a] Description about the managed Application and where to find more information
-- …

operator node-healthcheck-operator (0.5.0)

---

operators/gitlab-operator-kubernetes/0.19.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.19.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.19.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.19.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.19.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.19.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.19.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.19.1)

---

operators/aqua/2022.4.12/bundle.Dockerfile
operators/aqua/2022.4.12/manifests/aqua-operator.v2022.4.12.clusterserviceversion.yaml
operators/aqua/2022.4.12/manifests/aquacsps.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.12/manifests/aquadatabases.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.12/manifests/aquaenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.12/manifests/aquagateways.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.12/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.12/manifests/aquascanners.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.12/manifests/aquaservers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.12/manifests/aquastarboards.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.12/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.12/manifests/configauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.12/metadata/annotations.yaml
operators/aqua/ci.yaml

operator [CI] aqua (2022.4.12)

---

operators/mongodb-enterprise/1.19.1/bundle.Dockerfile
operators/mongodb-enterprise/1.19.1/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.19.1/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.19.1/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.19.1/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.19.1/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.19.1/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.19.1/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.19.1/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.19.1/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.19.1/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.19.1/metadata/annotations.yaml
operators/mongodb-enterprise/1.19.1/tests/scorecard/config.yaml

operator mongodb-enterprise (1.19.1)

---

operators/hyperfoil-bundle/0.24.2/hyperfoil-operator.v0.24.2.clusterserviceversion.yaml
operators/hyperfoil-bundle/0.24.2/hyperfoil.io_hyperfoils_crd.yaml
operators/hyperfoil-bundle/ci.yaml
operators/hyperfoil-bundle/hyperfoil-bundle.package.yaml

operator [CI] hyperfoil-bundle (0.24.2)

---

operators/awx-operator/2.1.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.1.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.1.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.1.0/manifests/awx-operator.v2.1.0.clusterserviceversion.yaml
operators/awx-operator/2.1.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.1.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.1.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.1.0/metadata/annotations.yaml
operators/awx-operator/2.1.0/tests/scorecard/config.yaml

operator awx-operator (2.1.0)

---

operators/clever-operator/0.5.5/bundle.Dockerfile
operators/clever-operator/0.5.5/manifests/clever-operator-config-provider.crd.yaml
operators/clever-operator/0.5.5/manifests/clever-operator-elasticsearch.crd.yaml
operators/clever-operator/0.5.5/manifests/clever-operator-mongodb.crd.yaml
operators/clever-operator/0.5.5/manifests/clever-operator-mysql.crd.yaml
operators/clever-operator/0.5.5/manifests/clever-operator-postgresql.crd.yaml
operators/clever-operator/0.5.5/manifests/clever-operator-pulsar.crd.yaml
operators/clever-operator/0.5.5/manifests/clever-operator-redis.crd.yaml
operators/clever-operator/0.5.5/manifests/clever-operator.clusterserviceversion.yaml
operators/clever-operator/0.5.5/metadata/annotations.yaml
operators/clever-operator/0.5.5/tests/scorecard/config.yaml

operator clever-operator (0.5.5)

---

operators/mariadb-operator/0.13.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.13.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.13.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.13.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.13.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.13.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.13.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.13.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.13.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.13.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.13.0/metadata/annotations.yaml
operators/mariadb-operator/0.13.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.13.0) to community operators

operator mariadb-operator (0.13.0)

---

operators/windup-operator/0.0.15/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.15/manifests/windup.crd.yaml
operators/windup-operator/0.0.15/metadata/annotations.yaml

operator windup-operator (0.0.15)

---

operators/clickhouse/0.19.0/clickhouse-operator.v0.19.0.clusterserviceversion.yaml
operators/clickhouse/0.19.0/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.19.0/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.19.0/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/clickhouse.package.yaml

operator clickhouse (0.19.0)

---

operators/project-quay/3.9.0-nightly.20230514/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230514/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230514 to community operators

operator project-quay (3.9.0-nightly.20230514)

---

operators/keda/2.10.1/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.10.1/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.10.1/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.10.1/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.10.1/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.10.1/manifests/keda.v2.10.1.clusterserviceversion.yaml
operators/keda/2.10.1/metadata/annotations.yaml
operators/keda/ci.yaml

Add joelsmith to keda reviewers list
--

operator [CI] keda (2.10.1)

---

operators/project-quay/3.9.0-nightly.20230515/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230515/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230515 to community operators

operator project-quay (3.9.0-nightly.20230515)

---

operators/clickhouse/0.19.1/clickhouse-operator.v0.19.1.clusterserviceversion.yaml
operators/clickhouse/0.19.1/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.19.1/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.19.1/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/clickhouse.package.yaml

operator clickhouse (0.19.1)

---

operators/seldon-operator/1.16.0/metadata/annotations.yaml

operator [O] seldon-operator (1.16.0)

---

operators/ndb-operator/1.0.2/bundle.Dockerfile
operators/ndb-operator/1.0.2/manifests/mysql.oracle.com_ndbclusters.yaml
operators/ndb-operator/1.0.2/manifests/ndb-operator-svc_v1_service.yaml
operators/ndb-operator/1.0.2/manifests/ndb-operator-webhook-service_v1_service.yaml
operators/ndb-operator/1.0.2/manifests/ndb-operator.clusterserviceversion.yaml
operators/ndb-operator/1.0.2/metadata/annotations.yaml
operators/ndb-operator/ci.yaml

operator [N] [CI] ndb-operator (1.0.2)

---

operators/knative-operator/1.10.1/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.10.1/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.10.1/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.10.1/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.10.1/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.10.1/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.10.1/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.10.1/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.10.1/manifests/knative-operator.v1.10.1.clusterserviceversion.yaml
operators/knative-operator/1.10.1/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.10.1/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.10.1/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.10.1/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.10.1/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.10.1/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.10.1/metadata/annotations.yaml
operators/knative-operator/1.10.1/tests/scorecard/config.yaml

operator knative-operator (1.10.1)

---

operators/clickhouse/0.19.2/clickhouse-operator.v0.19.2.clusterserviceversion.yaml
operators/clickhouse/0.19.2/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.19.2/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.19.2/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/clickhouse.package.yaml

operator clickhouse (0.19.2)

---

operators/authorino-operator/0.7.0/bundle.Dockerfile
operators/authorino-operator/0.7.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.7.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.7.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.7.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.7.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.7.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
operators/authorino-operator/0.7.0/manifests/authorino-operator-manager-config_v1_configmap.yaml
operators/authorino-operator/0.7.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.7.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.7.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.7.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.7.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.7.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.7.0/metadata/annotations.yaml
operators/authorino-operator/0.7.0/tests/scorecard/config.yaml

Signed-off-by: dd di cesare [didi@posteo.net](mailto:didi@posteo.net)
--

operator authorino-operator (0.7.0)

---

operators/mariadb-operator/0.14.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.14.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.14.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.14.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.14.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.14.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.14.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.14.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.14.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.14.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.14.0/metadata/annotations.yaml
operators/mariadb-operator/0.14.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.14.0) to community operators

operator mariadb-operator (0.14.0)

---

operators/project-quay/3.8.7/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.7/quayecosystems.crd.yaml
operators/project-quay/3.8.7/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.8.7 to community operators

operator project-quay (3.8.7)

---

operators/limitador-operator/0.5.0/bundle.Dockerfile
operators/limitador-operator/0.5.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml
operators/limitador-operator/0.5.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
operators/limitador-operator/0.5.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/limitador-operator/0.5.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/0.5.0/manifests/limitador.kuadrant.io_limitadors.yaml
operators/limitador-operator/0.5.0/metadata/annotations.yaml
operators/limitador-operator/0.5.0/tests/scorecard/config.yaml

Signed-off-by: dd di cesare didi@posteo.net
--

operator limitador-operator (0.5.0)

---

operators/dynatrace-operator/0.11.2/Dockerfile
operators/dynatrace-operator/0.11.2/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/0.11.2/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/0.11.2/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml
operators/dynatrace-operator/0.11.2/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.11.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.11.2/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.11.2/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.11.2/metadata/annotations.yaml

operator dynatrace-operator (0.11.2)

---

operators/verticadb-operator/1.11.0/manifests/vertica.com_eventtriggers.yaml
operators/verticadb-operator/1.11.0/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/1.11.0/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/1.11.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/1.11.0/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/1.11.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/1.11.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/1.11.0/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/1.11.0/metadata/annotations.yaml
operators/verticadb-operator/1.11.0/tests/scorecard/config.yaml

operator verticadb-operator (1.11.0)

---

operators/clickhouse/0.19.3/clickhouse-operator.v0.19.3.clusterserviceversion.yaml
operators/clickhouse/0.19.3/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.19.3/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.19.3/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/clickhouse.package.yaml

operator clickhouse (0.19.3)

---

operators/gitlab-operator-kubernetes/0.19.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.19.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.19.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.19.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.19.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.19.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.19.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.19.2)

---

operators/external-secrets-operator/0.8.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.8.2/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.8.2/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.8.2/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.8.2/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.8.2/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.8.2/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.8.2/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.8.2/metadata/annotations.yaml
operators/external-secrets-operator/0.8.2/tests/scorecard/config.yaml

bump external-secrets-operator 0.8.2

operator external-secrets-operator (0.8.2)

---

operators/mariadb-operator/0.15.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.15.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.15.0/metadata/annotations.yaml
operators/mariadb-operator/0.15.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.15.0) to community operators

operator mariadb-operator (0.15.0)

---

operators/clickhouse/0.20.1/clickhouse-operator.v0.20.1.clusterserviceversion.yaml
operators/clickhouse/0.20.1/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.20.1/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.20.1/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/clickhouse.package.yaml

operator clickhouse (0.20.1)

---

operators/cryostat-operator/2.3.0/Dockerfile
operators/cryostat-operator/2.3.0/manifests/cryostat-operator-cryostat-namespaced_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.3.0/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.3.0/manifests/cryostat-operator-manager-config_v1_configmap.yaml
operators/cryostat-operator/2.3.0/manifests/cryostat-operator-oauth-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.3.0/manifests/cryostat-operator.clusterserviceversion.yaml
operators/cryostat-operator/2.3.0/manifests/operator.cryostat.io_clustercryostats.yaml
operators/cryostat-operator/2.3.0/manifests/operator.cryostat.io_cryostats.yaml
operators/cryostat-operator/2.3.0/metadata/annotations.yaml
operators/cryostat-operator/2.3.0/tests/scorecard/config.yaml

operator cryostat-operator (2.3.0)

---

operators/project-quay/3.9.0-nightly.20230525/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230525/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230525 to community operators

operator project-quay (3.9.0-nightly.20230525)

---

operators/deployment-validation-operator/0.5.0/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.5.0/manifests/deploymentvalidationoperator.0.5.0.clusterserviceversion.yaml
operators/deployment-validation-operator/0.5.0/metadata/annotations.yaml
operators/deployment-validation-operator/0.5.0/tests/scorecard/config.yaml
operators/deployment-validation-operator/ci.yaml

operator [CI] deployment-validation-operator (0.5.0)

---

operators/klusterlet/0.11.0/klusterlet.clusterserviceversion.yaml
operators/klusterlet/0.11.0/operator.open-cluster-management.io_klusterlets.yaml
operators/klusterlet/klusterlet.package.yaml

operator klusterlet (0.11.0)

---

operators/external-secrets-operator/0.8.3/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.8.3/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.8.3/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.8.3/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.8.3/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.8.3/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.8.3/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.8.3/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.8.3/metadata/annotations.yaml
operators/external-secrets-operator/0.8.3/tests/scorecard/config.yaml

bump external-secrets-operator 0.8.3

operator external-secrets-operator (0.8.3)

---

operators/project-quay/3.9.0-nightly.20230526/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230526/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230526 to community operators

operator project-quay (3.9.0-nightly.20230526)

---

operators/project-quay/3.9.0-nightly.20230527/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230527/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230527 to community operators

operator project-quay (3.9.0-nightly.20230527)

---

operators/project-quay/3.9.0-nightly.20230528/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230528/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230528 to community operators

operator project-quay (3.9.0-nightly.20230528)

---

operators/mariadb-operator/0.15.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.15.1/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.15.1/metadata/annotations.yaml
operators/mariadb-operator/0.15.1/tests/scorecard/config.yaml

Add operator mariadb-operator (0.15.1) to community operators

operator mariadb-operator (0.15.1)

---

operators/project-quay/3.8.8/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.8/quayecosystems.crd.yaml
operators/project-quay/3.8.8/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.8.8 to community operators

operator project-quay (3.8.8)

---

operators/project-quay/3.9.0-nightly.20230529/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230529/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230529 to community operators

operator project-quay (3.9.0-nightly.20230529)

---

operators/gitlab-operator-kubernetes/0.19.3/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.19.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.19.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.19.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.19.3/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.19.3/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.19.3/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.19.3)

---

operators/clickhouse/0.20.2/clickhouse-operator.v0.20.2.clusterserviceversion.yaml
operators/clickhouse/0.20.2/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.20.2/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.20.2/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/clickhouse.package.yaml

operator clickhouse (0.20.2)

---

operators/gitlab-operator-kubernetes/0.19.4/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.19.4/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.19.4/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.19.4/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.19.4/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.19.4/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.19.4/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.19.4)

---

operators/grafana-operator/4.10.1/grafana-operator-controller-manager-metrics-service_v1_service.yaml
operators/grafana-operator/4.10.1/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/4.10.1/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/4.10.1/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/4.10.1/integreatly.org_grafanadashboards.yaml
operators/grafana-operator/4.10.1/integreatly.org_grafanadatasources.yaml
operators/grafana-operator/4.10.1/integreatly.org_grafanafolders.yaml
operators/grafana-operator/4.10.1/integreatly.org_grafananotificationchannels.yaml
operators/grafana-operator/4.10.1/integreatly.org_grafanas.yaml
operators/grafana-operator/grafana-operator.package.yaml

operator grafana-operator (4.10.1)

---

operators/project-quay/3.9.0-nightly.20230530/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230530/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230530 to community operators

operator project-quay (3.9.0-nightly.20230530)

---

operators/project-quay/3.9.0-nightly.20230531/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230531/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230531 to community operators

operator project-quay (3.9.0-nightly.20230531)

---

operators/elastic-cloud-eck/2.8.0/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.8.0/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.8.0/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.8.0/elastic-cloud-eck.v2.8.0.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.8.0/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.8.0/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.8.0/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.8.0/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.8.0/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.8.0/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.8.0/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml

Update the ECK operator to the latest version `2.8.0`.

operator elastic-cloud-eck (2.8.0)

---

operators/clickhouse/0.20.3/clickhouse-operator.v0.20.3.clusterserviceversion.yaml
operators/clickhouse/0.20.3/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.20.3/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.20.3/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/clickhouse.package.yaml

operator clickhouse (0.20.3)

---

operators/kuadrant-operator/0.3.0/bundle.Dockerfile
operators/kuadrant-operator/0.3.0/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
operators/kuadrant-operator/0.3.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.3.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.3.0/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.3.0/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.3.0/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.3.0/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.3.0/metadata/annotations.yaml
operators/kuadrant-operator/0.3.0/metadata/dependencies.yaml
operators/kuadrant-operator/0.3.0/tests/scorecard/config.yaml

operator kuadrant-operator (0.3.0)

---

operators/project-quay/3.9.0-nightly.20230602/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230602/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230602 to community operators

operator project-quay (3.9.0-nightly.20230602)

---

operators/kuadrant-operator/0.3.1/bundle.Dockerfile
operators/kuadrant-operator/0.3.1/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
operators/kuadrant-operator/0.3.1/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.3.1/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.3.1/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.3.1/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.3.1/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.3.1/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.3.1/metadata/annotations.yaml
operators/kuadrant-operator/0.3.1/metadata/dependencies.yaml
operators/kuadrant-operator/0.3.1/tests/scorecard/config.yaml

operator kuadrant-operator (0.3.1)

---

operators/rabbitmq-messaging-topology-operator/1.11.0/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_bindings.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_exchanges.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_federations.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_permissions.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_policies.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_queues.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_schemareplications.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_shovels.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_superstreams.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_topicpermissions.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_users.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_vhosts.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.webhook-service.yaml
operators/rabbitmq-messaging-topology-operator/1.11.0/metadata/annotations.yaml

operator rabbitmq-messaging-topology-operator (1.11.0)

---

operators/project-quay/3.9.0-nightly.20230603/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230603/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230605/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230605/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230605 to community operators

operator [R] project-quay (3.9.0-nightly.20230603 3.9.0-nightly.20230605)

---

operators/netobserv-operator/1.0.3/manifests/flows.netobserv.io_flowcollectors.yaml
operators/netobserv-operator/1.0.3/manifests/netobserv-manager-config_v1_configmap.yaml
operators/netobserv-operator/1.0.3/manifests/netobserv-metrics-service_v1_service.yaml
operators/netobserv-operator/1.0.3/manifests/netobserv-operator.clusterserviceversion.yaml
operators/netobserv-operator/1.0.3/manifests/netobserv-webhook-service_v1_service.yaml
operators/netobserv-operator/1.0.3/metadata/annotations.yaml

operator netobserv-operator (1.0.3)

---

operators/project-quay/3.9.0-nightly.20230606/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230606/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230606 to community operators

operator project-quay (3.9.0-nightly.20230606)

---

operators/tempo-operator/ci.yaml

operator [CI] tempo-operator

---

operators/gitlab-operator-kubernetes/0.20.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.20.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.20.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.20.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.20.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.20.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.20.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.20.0)

---

operators/clickhouse/0.21.0/clickhouse-operator.v0.21.0.clusterserviceversion.yaml
operators/clickhouse/0.21.0/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.21.0/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.21.0/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/clickhouse.package.yaml

operator clickhouse (0.21.0)

---

operators/trivy-operator/0.14.0/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.0/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.0/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.0/trivy-operator.v0.14.0.clusterserviceversion.yaml
operators/trivy-operator/0.14.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.14.0)

---

operators/grafana-operator/5.0.0/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.0.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.0.0/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.0.0/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.0.0/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.0.0/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.0.0/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.0.0/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/grafana-operator.package.yaml

operator grafana-operator (5.0.0)

---

operators/project-quay/3.9.0-nightly.20230609/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230609/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230609 to community operators

operator project-quay (3.9.0-nightly.20230609)

---

operators/project-quay/3.9.0-nightly.20230610/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230610/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230610 to community operators

operator project-quay (3.9.0-nightly.20230610)

---

operators/rabbitmq-cluster-operator/2.3.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.3.0/manifests/crds.yaml
operators/rabbitmq-cluster-operator/2.3.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.3.0/metadata/annotations.yaml

operator rabbitmq-cluster-operator (2.3.0)

---

operators/project-quay/3.9.0-nightly.20230611/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230611/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230611 to community operators

operator project-quay (3.9.0-nightly.20230611)

---

operators/trivy-operator/0.14.1/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.1/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.1/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.1/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.1/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.1/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.1/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.1/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.14.1/trivy-operator.v0.14.1.clusterserviceversion.yaml
operators/trivy-operator/0.14.1/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/trivy-operator.package.yaml

operator trivy-operator (0.14.1)

---

operators/gitlab-operator-kubernetes/0.20.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.20.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.20.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.20.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.20.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.20.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.20.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.20.2)

---

operators/gitlab-operator-kubernetes/0.20.3/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.20.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.20.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.20.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.20.3/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.20.3/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.20.3/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.20.3)

---

operators/project-quay/3.9.0-nightly.20230613/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230613/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230613 to community operators

operator project-quay (3.9.0-nightly.20230613)

---

operators/gitlab-operator-kubernetes/0.20.5/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.20.5/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.20.5/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.20.5/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.20.5/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.20.5/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.20.5/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.20.5)

---

operators/clickhouse/0.21.1/clickhouse-operator.v0.21.1.clusterserviceversion.yaml
operators/clickhouse/0.21.1/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.21.1/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.21.1/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/clickhouse.package.yaml

operator clickhouse (0.21.1)

---

operators/project-quay/3.9.0-nightly.20230614/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230614/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230614 to community operators

operator project-quay (3.9.0-nightly.20230614)

---

operators/edp-keycloak-operator/1.16.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.16.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.16.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.16.0/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.16.0)

---

operators/project-quay/3.9.0-nightly.20230616/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230616/quayregistries.crd.yaml
operators/project-quay/project-quay.package.yaml

Add 3.9.0-nightly.20230616 to community operators

operator project-quay (3.9.0-nightly.20230616)

---

operators/windup-operator/0.0.16/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.16/manifests/windup.crd.yaml
operators/windup-operator/0.0.16/metadata/annotations.yaml

operator windup-operator (0.0.16)

---

operators/apch-operator/0.0.1/bundle.Dockerfile
operators/apch-operator/0.0.1/manifests/apache-operator-controller-manager-metrics-service_v1_service.yaml
operators/apch-operator/0.0.1/manifests/apache-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/apch-operator/0.0.1/manifests/apache-operator.clusterserviceversion.yaml
operators/apch-operator/0.0.1/manifests/apacheweb.arsenal.dev_apachewebs.yaml
operators/apch-operator/0.0.1/metadata/annotations.yaml
operators/apch-operator/0.0.1/tests/scorecard/config.yaml
operators/apch-operator/ci.yaml

Signed-off-by: Oleksandr Krutko <alexander.krutko@gmail.com>
--

operator [N] [CI] apch-operator (0.0.1)

---

operators/ack-pipes-controller/ci.yaml

operator [CI] ack-pipes-controller

---

operators/microcks/1.7.1/microcks-operator.v1.7.1.clusterserviceversion.yaml
operators/microcks/1.7.1/microcksinstall.crd.yaml
operators/microcks/microcks.package.yaml

operator microcks (1.7.1)

---

operators/grafana-operator/5.0.1/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.0.1/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.0.1/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.0.1/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.0.1/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.0.1/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.0.1/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.0.1/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/grafana-operator.package.yaml

operator grafana-operator (5.0.1)

---

operators/gitlab-operator-kubernetes/0.20.6/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.20.6/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.20.6/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.20.6/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.20.6/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.20.6/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.20.6/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.20.6)

---

operators/self-node-remediation/0.6.1/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml
operators/self-node-remediation/0.6.1/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.6.1/manifests/self-node-remediation-manager-config_v1_configmap.yaml
operators/self-node-remediation/0.6.1/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.6.1/manifests/self-node-remediation-webhook-service_v1_service.yaml
operators/self-node-remediation/0.6.1/manifests/self-node-remediation.clusterserviceversion.yaml
operators/self-node-remediation/0.6.1/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
operators/self-node-remediation/0.6.1/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
operators/self-node-remediation/0.6.1/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
operators/self-node-remediation/0.6.1/metadata/annotations.yaml
operators/self-node-remediation/0.6.1/tests/scorecard/config.yaml

operator self-node-remediation (0.6.1)

---

operators/apch-operator/0.0.2/manifests/apache-operator-controller-manager-metrics-service_v1_service.yaml
operators/apch-operator/0.0.2/manifests/apache-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/apch-operator/0.0.2/manifests/apache-operator.clusterserviceversion.yaml
operators/apch-operator/0.0.2/manifests/apacheweb.arsenal.dev_apachewebs.yaml
operators/apch-operator/0.0.2/metadata/annotations.yaml
operators/apch-operator/0.0.2/tests/scorecard/config.yaml

Signed-off-by: Oleksandr Krutko <alexander.krutko@gmail.com>
--

operator apch-operator (0.0.2)

---

operators/external-secrets-operator/0.8.4/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.8.4/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.8.4/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.8.4/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.8.4/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.8.4/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.8.4/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.8.4/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.8.4/metadata/annotations.yaml
operators/external-secrets-operator/0.8.4/tests/scorecard/config.yaml

bump external-secrets-operator 0.8.4

operator external-secrets-operator (0.8.4)

---

operators/external-secrets-operator/0.9.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.0/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.0/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.0/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.0/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.0/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.0/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.0/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.0/metadata/annotations.yaml
operators/external-secrets-operator/0.9.0/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.0
towards https://github.com/external-secrets/external-secrets/issues/2440

operator external-secrets-operator (0.9.0)

---

operators/gitlab-operator-kubernetes/0.21.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.21.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.21.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.21.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.21.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.21.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.21.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.21.0)

---

operators/dynatrace-operator/0.12.0/Dockerfile
operators/dynatrace-operator/0.12.0/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml
operators/dynatrace-operator/0.12.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.12.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.12.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.12.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.12.0/metadata/annotations.yaml

operator dynatrace-operator (0.12.0)

---

operators/grafana-operator/5.0.2/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.0.2/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.0.2/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.0.2/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.0.2/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.0.2/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.0.2/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.0.2/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.0.2/metadata/annotations.yaml

operator grafana-operator (5.0.2)

---

ci/pipeline-config-k8s.yaml

[ISV-3683] Disable the package manifest format support.

---

operators/sonataflow-operator/1.40.0/manifests/sonataflow-operator-builder-config_v1_configmap.yaml
operators/sonataflow-operator/1.40.0/manifests/sonataflow-operator-controller-manager-metrics-service_v1_service.yaml
operators/sonataflow-operator/1.40.0/manifests/sonataflow-operator-manager-config_v1_configmap.yaml
operators/sonataflow-operator/1.40.0/manifests/sonataflow-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/sonataflow-operator/1.40.0/manifests/sonataflow-operator.clusterserviceversion.yaml
operators/sonataflow-operator/1.40.0/manifests/sonataflow.org_sonataflowbuilds.yaml
operators/sonataflow-operator/1.40.0/manifests/sonataflow.org_sonataflowplatforms.yaml
operators/sonataflow-operator/1.40.0/manifests/sonataflow.org_sonataflows.yaml
operators/sonataflow-operator/1.40.0/metadata/annotations.yaml
operators/sonataflow-operator/1.40.0/tests/scorecard/config.yaml

operator [N] sonataflow-operator (1.40.0)

---

operators/cass-operator-community/1.16.0/manifests/cass-operator-manager-config_v1_configmap.yaml
operators/cass-operator-community/1.16.0/manifests/cass-operator-webhook-service_v1_service.yaml
operators/cass-operator-community/1.16.0/manifests/cass-operator.clusterserviceversion.yaml
operators/cass-operator-community/1.16.0/manifests/cassandra.datastax.com_cassandradatacenters.yaml
operators/cass-operator-community/1.16.0/manifests/control.k8ssandra.io_cassandratasks.yaml
operators/cass-operator-community/1.16.0/metadata/annotations.yaml
operators/cass-operator-community/1.16.0/tests/scorecard/config.yaml

operator cass-operator-community (1.16.0)

---

operators/clickhouse/0.21.2/manifests/clickhouse-operator.v0.21.2.clusterserviceversion.yaml
operators/clickhouse/0.21.2/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.21.2/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.21.2/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.21.2/metadata/annotations.yaml

operator clickhouse (0.21.2)

---

operators/dell-csm-operator/1.2.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.2.0/manifests/dell-csm-operator.v1.2.0.clusterserviceversion.yaml
operators/dell-csm-operator/1.2.0/metadata/annotations.yaml
operators/dell-csm-operator/1.2.0/tests/scorecard/config.yaml

operator dell-csm-operator (1.2.0)

---

operators/gitlab-operator-kubernetes/0.21.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.21.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.21.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.21.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.21.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.21.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.21.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.21.1)

---

operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-create-user-job_ServiceAccount.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-migrate-database-job_ServiceAccount.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-operator-controller-manager-metrics-service_v1_service.yaml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-operator.clusterserviceversion.yaml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-pod-launcher-role_Role.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-pod-launcher-rolebinding_RoleBinding.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-pod-log-reader-role_Role.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-pod-log-reader-rolebinding_RoleBinding.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-postgresql_Role.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-postgresql_RoleBinding.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-postgresql_ServiceAccount.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-redis_Role.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-redis_RoleBinding.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-redis_ServiceAccount.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-scc-rolebinding_RoleBinding.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-scheduler_ServiceAccount.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-statsd_ServiceAccount.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-triggerer_ServiceAccount.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-webserver_ServiceAccount.yml
operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-worker_ServiceAccount.yml
operators/airflow-helm-operator/0.0.1/manifests/workflow.apache.org_airflows.yaml
operators/airflow-helm-operator/0.0.1/metadata/annotations.yaml
operators/airflow-helm-operator/0.0.1/tests/scorecard/config.yaml
operators/airflow-helm-operator/ci.yaml

operator [N] [CI] airflow-helm-operator (0.0.1)

---

operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-operator.clusterserviceversion.yaml

operator [N] airflow-helm-operator (0.0.1)

---

operators/stackgres/1.5.0/manifests/stackgres-helm-controller-manager-metrics-service_v1_service.yaml
operators/stackgres/1.5.0/manifests/stackgres-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/stackgres/1.5.0/manifests/stackgres.clusterserviceversion.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sgbackups.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sgclusters.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sgconfigs.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sgdbops.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sgdistributedlogs.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sginstanceprofiles.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sgobjectstorages.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sgpgconfigs.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sgpoolconfigs.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sgscripts.yaml
operators/stackgres/1.5.0/manifests/stackgres.io_sgshardedclusters.yaml
operators/stackgres/1.5.0/metadata/annotations.yaml
operators/stackgres/1.5.0/tests/scorecard/config.yaml
operators/stackgres/ci.yaml

operator [CI] stackgres (1.5.0)

---

operators/rabbitmq-messaging-topology-operator/1.12.0/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_bindings.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_exchanges.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_federations.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_permissions.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_policies.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_queues.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_schemareplications.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_shovels.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_superstreams.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_topicpermissions.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_users.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.com_vhosts.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/manifests/rabbitmq.webhook-service.yaml
operators/rabbitmq-messaging-topology-operator/1.12.0/metadata/annotations.yaml

operator rabbitmq-messaging-topology-operator (1.12.0)

---

operators/external-secrets-operator/0.8.5/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.8.5/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.8.5/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.8.5/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.8.5/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.8.5/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.8.5/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.8.5/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.8.5/metadata/annotations.yaml
operators/external-secrets-operator/0.8.5/tests/scorecard/config.yaml

bump external-secrets-operator 0.8.5

operator external-secrets-operator (0.8.5)

---

operators/external-secrets-operator/0.9.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.1/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.1/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.1/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.1/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.1/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.1/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.1/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.1/metadata/annotations.yaml
operators/external-secrets-operator/0.9.1/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.1

operator external-secrets-operator (0.9.1)

---

operators/gitlab-operator-kubernetes/0.21.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.21.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.21.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.21.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.21.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.21.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.21.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.21.2)

---

operators/grafana-operator/5.1.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.1.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.1.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.1.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.1.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.1.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.1.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.1.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.1.0/metadata/annotations.yaml

operator grafana-operator (5.1.0)

---

operators/authorino-operator/0.8.0/bundle.Dockerfile
operators/authorino-operator/0.8.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.8.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.8.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.8.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.8.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.8.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
operators/authorino-operator/0.8.0/manifests/authorino-operator-manager-config_v1_configmap.yaml
operators/authorino-operator/0.8.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.8.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.8.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.8.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.8.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.8.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.8.0/metadata/annotations.yaml
operators/authorino-operator/0.8.0/tests/scorecard/config.yaml

operator authorino-operator (0.8.0)

---

operators/project-quay/3.9.0-nightly.20230712/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230712/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230712/metadata/annotations.yaml

Add 3.9.0-nightly.20230712 to community operators

operator project-quay (3.9.0-nightly.20230712)

---

operators/grafana-operator/5.2.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.2.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.2.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.2.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.2.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.2.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.2.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.2.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.2.0/metadata/annotations.yaml

operator grafana-operator (5.2.0)

---

operators/ack-secretsmanager-controller/ci.yaml

operator [CI] ack-secretsmanager-controller

---

operators/project-quay/3.8.10/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.10/manifests/quayecosystems.crd.yaml
operators/project-quay/3.8.10/manifests/quayregistries.crd.yaml
operators/project-quay/3.8.10/metadata/annotations.yaml

Add 3.8.10 to community operators

operator project-quay (3.8.10)

---

operators/mariadb-operator/0.16.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.16.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.16.0/metadata/annotations.yaml
operators/mariadb-operator/0.16.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.16.0) to community operators

operator mariadb-operator (0.16.0)

---

operators/project-quay/3.9.0-nightly.20230714/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230714/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230714/metadata/annotations.yaml

Add 3.9.0-nightly.20230714 to community operators

operator project-quay (3.9.0-nightly.20230714)

---

operators/mariadb-operator/0.16.0/manifests/mariadb-operator.clusterserviceversion.yaml

Add operator mariadb-operator (0.16.0) to community operators

operator [O] mariadb-operator (0.16.0)

---

operators/project-quay/3.9.0-nightly.20230715/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230715/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230715/metadata/annotations.yaml

Add 3.9.0-nightly.20230715 to community operators

operator project-quay (3.9.0-nightly.20230715)

---

operators/project-quay/3.9.0-nightly.20230716/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230716/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230716/metadata/annotations.yaml

Add 3.9.0-nightly.20230716 to community operators

operator project-quay (3.9.0-nightly.20230716)

---

operators/mariadb-operator/0.17.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.17.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.17.0/metadata/annotations.yaml
operators/mariadb-operator/0.17.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.17.0) to community operators

operator mariadb-operator (0.17.0)

---

operators/sap-hana-express-operator/1.0.2/manifests/db.sap-redhat.io_hanaexpresses.yaml
operators/sap-hana-express-operator/1.0.2/manifests/sap-hana-express-operator-controller-manager-metrics-service_v1_service.yaml
operators/sap-hana-express-operator/1.0.2/manifests/sap-hana-express-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/sap-hana-express-operator/1.0.2/manifests/sap-hana-express-operator.clusterserviceversion.yaml
operators/sap-hana-express-operator/1.0.2/metadata/annotations.yaml
operators/sap-hana-express-operator/ci.yaml

operator [N] [CI] sap-hana-express-operator (1.0.2)

---

operators/parodos-operator/0.0.2/bundle.Dockerfile
operators/parodos-operator/0.0.2/manifests/charts.redhat.com_parodos.yaml
operators/parodos-operator/0.0.2/manifests/parodos-operator-controller-manager-metrics-service_v1_service.yaml
operators/parodos-operator/0.0.2/manifests/parodos-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/parodos-operator/0.0.2/manifests/parodos-operator.clusterserviceversion.yaml
operators/parodos-operator/0.0.2/metadata/annotations.yaml
operators/parodos-operator/0.0.2/tests/scorecard/config.yaml
operators/parodos-operator/ci.yaml

operator [CI] parodos-operator (0.0.2)

---

operators/flux/2.0.1/manifests/alert.crd.yaml
operators/flux/2.0.1/manifests/bucket.crd.yaml
operators/flux/2.0.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
operators/flux/2.0.1/manifests/crd-controller-flux-system.clusterrole.yaml
operators/flux/2.0.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml
operators/flux/2.0.1/manifests/flux-edit-flux-system.clusterrole.yaml
operators/flux/2.0.1/manifests/flux-view-flux-system.clusterrole.yaml
operators/flux/2.0.1/manifests/flux.v2.0.1.clusterserviceversion.yaml
operators/flux/2.0.1/manifests/gitrepository.crd.yaml
operators/flux/2.0.1/manifests/helmchart.crd.yaml
operators/flux/2.0.1/manifests/helmrelease.crd.yaml
operators/flux/2.0.1/manifests/helmrepository.crd.yaml
operators/flux/2.0.1/manifests/imagepolicy.crd.yaml
operators/flux/2.0.1/manifests/imagerepository.crd.yaml
operators/flux/2.0.1/manifests/imageupdateautomation.crd.yaml
operators/flux/2.0.1/manifests/kustomization.crd.yaml
operators/flux/2.0.1/manifests/notification-controller.service.yaml
operators/flux/2.0.1/manifests/ocirepository.crd.yaml
operators/flux/2.0.1/manifests/provider.crd.yaml
operators/flux/2.0.1/manifests/receiver.crd.yaml
operators/flux/2.0.1/manifests/source-controller.service.yaml
operators/flux/2.0.1/manifests/webhook-receiver.service.yaml
operators/flux/2.0.1/metadata/annotations.yaml
operators/flux/ci.yaml

operator [CI] flux (2.0.1)

---

operators/percona-xtradb-cluster-operator/1.13.0/manifests/percona-xtradb-cluster-operator.v1.13.0.clusterserviceversion.yaml
operators/percona-xtradb-cluster-operator/1.13.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.13.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.13.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.13.0/metadata/annotations.yaml

operator percona-xtradb-cluster-operator (1.13.0)

---

operators/kaoto-operator/0.0.6/manifests/designer.kaoto.io_kaotoes.yaml
operators/kaoto-operator/0.0.6/manifests/kaoto-backend_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kaoto-operator/0.0.6/manifests/kaoto-operator.v0.0.6.clusterserviceversion.yaml
operators/kaoto-operator/0.0.6/metadata/annotations.yaml
operators/kaoto-operator/0.0.6/tests/scorecard/config.yaml
operators/kaoto-operator/ci.yaml

operator [N] [CI] kaoto-operator (0.0.6)

---

operators/project-quay/3.9.0-nightly.20230720/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230720/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230720/metadata/annotations.yaml

Add 3.9.0-nightly.20230720 to community operators

operator project-quay (3.9.0-nightly.20230720)

---

operators/project-quay/3.9.0-nightly.20230721/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230721/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230721/metadata/annotations.yaml

Add 3.9.0-nightly.20230721 to community operators

operator project-quay (3.9.0-nightly.20230721)

---

operators/mariadb-operator/0.18.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.18.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.18.0/metadata/annotations.yaml
operators/mariadb-operator/0.18.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.18.0) to community operators

operator mariadb-operator (0.18.0)

---

operators/project-quay/3.9.0-nightly.20230722/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230722/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230722/metadata/annotations.yaml

Add 3.9.0-nightly.20230722 to community operators

operator project-quay (3.9.0-nightly.20230722)

---

operators/project-quay/3.9.0-nightly.20230723/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230723/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230723/metadata/annotations.yaml

Add 3.9.0-nightly.20230723 to community operators

operator project-quay (3.9.0-nightly.20230723)

---

operators/rabbitmq-cluster-operator/2.4.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.4.0/manifests/crds.yaml
operators/rabbitmq-cluster-operator/2.4.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.4.0/metadata/annotations.yaml

operator rabbitmq-cluster-operator (2.4.0)

---

operators/gitlab-operator-kubernetes/0.22.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.22.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.22.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.22.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.22.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.22.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.22.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.22.0)

---

operators/project-quay/3.9.0-nightly.20230724/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230724/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230724/metadata/annotations.yaml

Add 3.9.0-nightly.20230724 to community operators

operator project-quay (3.9.0-nightly.20230724)

---

operators/camel-k/2.0.0/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.0.0/manifests/camel-k.v2.0.0.clusterserviceversion.yaml
operators/camel-k/2.0.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.0.0/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.0.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.0.0/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.0.0/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/2.0.0/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.0.0/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.0.0/metadata/annotations.yaml
operators/camel-k/2.0.0/tests/scorecard/config.yaml

operator camel-k (2.0.0)

---

operators/sonataflow-operator/1.41.0/manifests/sonataflow-operator-builder-config_v1_configmap.yaml
operators/sonataflow-operator/1.41.0/manifests/sonataflow-operator-controller-manager-metrics-service_v1_service.yaml
operators/sonataflow-operator/1.41.0/manifests/sonataflow-operator-manager-config_v1_configmap.yaml
operators/sonataflow-operator/1.41.0/manifests/sonataflow-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/sonataflow-operator/1.41.0/manifests/sonataflow-operator.clusterserviceversion.yaml
operators/sonataflow-operator/1.41.0/manifests/sonataflow.org_sonataflowbuilds.yaml
operators/sonataflow-operator/1.41.0/manifests/sonataflow.org_sonataflowplatforms.yaml
operators/sonataflow-operator/1.41.0/manifests/sonataflow.org_sonataflows.yaml
operators/sonataflow-operator/1.41.0/metadata/annotations.yaml
operators/sonataflow-operator/1.41.0/tests/scorecard/config.yaml
operators/sonataflow-operator/ci.yaml

operator [CI] sonataflow-operator (1.41.0)

---

operators/grafana-operator/5.3.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.3.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.3.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.3.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.3.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.3.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.3.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.3.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.3.0/metadata/annotations.yaml

operator grafana-operator (5.3.0)

---

operators/deployment-validation-operator/0.6.0/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.6.0/manifests/deploymentvalidationoperator.0.6.0.clusterserviceversion.yaml
operators/deployment-validation-operator/0.6.0/metadata/annotations.yaml
operators/deployment-validation-operator/0.6.0/tests/scorecard/config.yaml

operator deployment-validation-operator (0.6.0)

---

operators/dynatrace-operator/0.12.1/Dockerfile
operators/dynatrace-operator/0.12.1/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/0.12.1/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/0.12.1/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml
operators/dynatrace-operator/0.12.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.12.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.12.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.12.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.12.1/metadata/annotations.yaml

operator dynatrace-operator (0.12.1)

---

operators/gitlab-operator-kubernetes/0.22.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.22.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.22.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.22.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.22.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.22.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.22.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.22.1)

---

operators/mariadb-operator/0.19.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.19.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.19.0/metadata/annotations.yaml
operators/mariadb-operator/0.19.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.19.0) to community operators

operator mariadb-operator (0.19.0)

---

operators/trivy-operator/0.15.0/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/manifests/trivy-operator.v0.15.1.clusterserviceversion.yaml
operators/trivy-operator/0.15.1/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.15.1/metadata/annotations.yaml

operator [R] trivy-operator (0.15.0 0.15.1)

---

operators/loki-operator/0.4.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
operators/loki-operator/0.4.0/manifests/loki-operator-manager-config_v1_configmap.yaml
operators/loki-operator/0.4.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/loki-operator/0.4.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
operators/loki-operator/0.4.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/loki-operator/0.4.0/manifests/loki-operator-webhook-service_v1_service.yaml
operators/loki-operator/0.4.0/manifests/loki-operator.clusterserviceversion.yaml
operators/loki-operator/0.4.0/manifests/loki.grafana.com_alertingrules.yaml
operators/loki-operator/0.4.0/manifests/loki.grafana.com_lokistacks.yaml
operators/loki-operator/0.4.0/manifests/loki.grafana.com_recordingrules.yaml
operators/loki-operator/0.4.0/manifests/loki.grafana.com_rulerconfigs.yaml
operators/loki-operator/0.4.0/metadata/annotations.yaml
operators/loki-operator/0.4.0/tests/scorecard/config.yaml

operator loki-operator (0.4.0)

---

operators/ack-cloudwatch-controller/ci.yaml

operator [CI] ack-cloudwatch-controller

---

operators/elastic-cloud-eck/2.9.0/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.9.0/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.9.0/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.9.0/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.9.0/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.9.0/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.9.0/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.9.0/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.9.0/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.9.0/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.9.0/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.9.0/metadata/annotations.yaml

Update the ECK operator to the latest version `2.9.0`.

operator elastic-cloud-eck (2.9.0)

---

operators/windup-operator/0.0.18/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.18/manifests/windup.crd.yaml
operators/windup-operator/0.0.18/metadata/annotations.yaml

operator windup-operator (0.0.18)

---

operators/tempo-operator/0.3.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.3.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.3.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.3.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.3.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.3.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.3.0/metadata/annotations.yaml
operators/tempo-operator/0.3.0/tests/scorecard/config.yaml

operator tempo-operator (0.3.0)

---

operators/windup-operator/0.0.19/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.19/manifests/windup.crd.yaml
operators/windup-operator/0.0.19/metadata/annotations.yaml

operator windup-operator (0.0.19)

---

operators/clickhouse/0.21.3/manifests/clickhouse-operator.v0.21.3.clusterserviceversion.yaml
operators/clickhouse/0.21.3/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.21.3/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.21.3/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.21.3/metadata/annotations.yaml

operator clickhouse (0.21.3)

---

operators/gitlab-operator-kubernetes/0.22.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.22.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.22.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.22.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.22.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.22.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.22.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.22.2)

---

operators/verticadb-operator/1.11.2/manifests/vertica.com_eventtriggers.yaml
operators/verticadb-operator/1.11.2/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/1.11.2/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/1.11.2/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/1.11.2/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/1.11.2/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/1.11.2/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/1.11.2/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/1.11.2/metadata/annotations.yaml
operators/verticadb-operator/1.11.2/tests/scorecard/config.yaml

operator verticadb-operator (1.11.2)

---

operators/aqua/2022.4.13/bundle.Dockerfile
operators/aqua/2022.4.13/manifests/aqua-operator.v2022.4.13.clusterserviceversion.yaml
operators/aqua/2022.4.13/manifests/aquacloudconnector.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.13/manifests/aquacsps.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.13/manifests/aquadatabases.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.13/manifests/aquaenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.13/manifests/aquagateways.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.13/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.13/manifests/aqualightnings.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.13/manifests/aquascanners.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.13/manifests/aquaservers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.13/manifests/aquastarboards.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.13/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.13/manifests/configauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.13/metadata/annotations.yaml
operators/aqua/ci.yaml

operator [CI] aqua (2022.4.13)

---

operators/gitlab-operator-kubernetes/0.22.3/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.22.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.22.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.22.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.22.3/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.22.3/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.22.3/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.22.3)

---

operators/oci-ccm-operator/0.0.9/manifests/ccm.oraclecloud.com_ocicloudmanagers.yaml
operators/oci-ccm-operator/0.0.9/manifests/ccm.oraclecloud.com_ocicsidrivers.yaml
operators/oci-ccm-operator/0.0.9/manifests/oci-ccm-operator-controller-manager-metrics-service_v1_service.yaml
operators/oci-ccm-operator/0.0.9/manifests/oci-ccm-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/oci-ccm-operator/0.0.9/manifests/oci-ccm-operator.clusterserviceversion.yaml
operators/oci-ccm-operator/0.0.9/metadata/annotations.yaml
operators/oci-ccm-operator/0.0.9/tests/scorecard/config.yaml
operators/oci-ccm-operator/ci.yaml

operator [N] [CI] oci-ccm-operator (0.0.9)

---

operators/external-secrets-operator/0.8.6/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.8.6/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.8.6/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.8.6/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.8.6/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.8.6/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.8.6/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.8.6/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.8.6/metadata/annotations.yaml
operators/external-secrets-operator/0.8.6/tests/scorecard/config.yaml

bump external-secrets-operator 0.8.6

operator external-secrets-operator (0.8.6)

---

operators/external-secrets-operator/0.9.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.2/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.2/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.2/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.2/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.2/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.2/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.2/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.2/metadata/annotations.yaml
operators/external-secrets-operator/0.9.2/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.2

operator external-secrets-operator (0.9.2)

---

operators/sonataflow-operator/1.42.0/manifests/sonataflow-operator-builder-config_v1_configmap.yaml
operators/sonataflow-operator/1.42.0/manifests/sonataflow-operator-controller-manager-metrics-service_v1_service.yaml
operators/sonataflow-operator/1.42.0/manifests/sonataflow-operator-manager-config_v1_configmap.yaml
operators/sonataflow-operator/1.42.0/manifests/sonataflow-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/sonataflow-operator/1.42.0/manifests/sonataflow-operator.clusterserviceversion.yaml
operators/sonataflow-operator/1.42.0/manifests/sonataflow.org_sonataflowbuilds.yaml
operators/sonataflow-operator/1.42.0/manifests/sonataflow.org_sonataflowplatforms.yaml
operators/sonataflow-operator/1.42.0/manifests/sonataflow.org_sonataflows.yaml
operators/sonataflow-operator/1.42.0/metadata/annotations.yaml
operators/sonataflow-operator/1.42.0/tests/scorecard/config.yaml

operator sonataflow-operator (1.42.0)

---

operators/aerospike-kubernetes-operator/3.0.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml

operator [O] aerospike-kubernetes-operator (3.0.0)

---

operators/argocd-operator/ci.yaml

operator [CI] argocd-operator

---

operators/project-quay/3.9.0-nightly.20230812/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0-nightly.20230812/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0-nightly.20230812/metadata/annotations.yaml

Add 3.9.0-nightly.20230812 to community operators

operator project-quay (3.9.0-nightly.20230812)

---

operators/project-quay/3.8.11/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.11/manifests/quayecosystems.crd.yaml
operators/project-quay/3.8.11/manifests/quayregistries.crd.yaml
operators/project-quay/3.8.11/metadata/annotations.yaml

Add 3.8.11 to community operators

operator project-quay (3.8.11)

---

operators/gitlab-operator-kubernetes/0.22.4/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.22.4/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.22.4/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.22.4/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.22.4/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.22.4/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.22.4/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.22.4)

---

operators/project-quay/3.9.0/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.0/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.0/metadata/annotations.yaml

Add 3.9.0 to community operators

operator project-quay (3.9.0)

---

operators/argocd-operator/0.7.0/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
operators/argocd-operator/0.7.0/manifests/argocd-operator-manager-config_v1_configmap.yaml
operators/argocd-operator/0.7.0/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/argocd-operator/0.7.0/manifests/argocd-operator.v0.7.0.clusterserviceversion.yaml
operators/argocd-operator/0.7.0/manifests/argoproj.io_applications.yaml
operators/argocd-operator/0.7.0/manifests/argoproj.io_applicationsets.yaml
operators/argocd-operator/0.7.0/manifests/argoproj.io_appprojects.yaml
operators/argocd-operator/0.7.0/manifests/argoproj.io_argocdexports.yaml
operators/argocd-operator/0.7.0/manifests/argoproj.io_argocds.yaml
operators/argocd-operator/0.7.0/metadata/annotations.yaml

Thanks in advance for reviews-- I would like to request extra attention towards making sure everything fits the new `bundle` format. I'm not positive if there needs to be similar changes made anywhere in our operator repository to support this new format- I simply copied the relevant release folder from [argocd-operator](https://github.com/argoproj-labs/argocd-operator)'s `deploy/olm-catalog/argocd-operator` folder into a new `v0.7.0/manifests` folder, then created the `v0.7.0/metadata` folder with the same `annotations.yaml` file as previous releases. I'm not sure if this is the right way to go about this... this is the first release we are doing with the `bundle` format since it was upgraded from `packagemanifests` format. 
________________________________________________________________ …

operator argocd-operator (0.7.0)

---

operators/sn-operator/0.2.0/bundle.Dockerfile
operators/sn-operator/0.2.0/manifests/k8s.streamnative.io_apikeys.yaml
operators/sn-operator/0.2.0/manifests/k8s.streamnative.io_oxiaclusters.yaml
operators/sn-operator/0.2.0/manifests/k8s.streamnative.io_pfsqlclusters.yaml
operators/sn-operator/0.2.0/manifests/k8s.streamnative.io_pulsarcoordinators.yaml
operators/sn-operator/0.2.0/manifests/k8s.streamnative.io_snconsoles.yaml
operators/sn-operator/0.2.0/manifests/sn-operator-controller-manager-metrics-service_v1_service.yaml
operators/sn-operator/0.2.0/manifests/sn-operator-global-config_v1_configmap.yaml
operators/sn-operator/0.2.0/manifests/sn-operator-manager-config_v1_configmap.yaml
operators/sn-operator/0.2.0/manifests/sn-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/sn-operator/0.2.0/manifests/sn-operator-troubleshooting-template-jvm_v1_configmap.yaml
operators/sn-operator/0.2.0/manifests/sn-operator-troubleshooting-template-pulsar_v1_configmap.yaml
operators/sn-operator/0.2.0/manifests/sn-operator-troubleshooting-template-system_v1_configmap.yaml
operators/sn-operator/0.2.0/manifests/sn-operator-webhook-service_v1_service.yaml
operators/sn-operator/0.2.0/manifests/sn-operator.clusterserviceversion.yaml
operators/sn-operator/0.2.0/metadata/annotations.yaml
operators/sn-operator/0.2.0/tests/scorecard/config.yaml

operator sn-operator (0.2.0)

---

operators/move2kube-operator/0.3.8/bundle.Dockerfile
operators/move2kube-operator/0.3.8/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.8/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.8/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
operators/move2kube-operator/0.3.8/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.8/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.8/metadata/annotations.yaml
operators/move2kube-operator/0.3.8/tests/scorecard/config.yaml
operators/move2kube-operator/ci.yaml

* [x ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x ] Have you tested your Operator with all Custom Resource Definitions?
* [x ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x ] Have you considered whether you want use [semantic versioning …

operator [N] [CI] move2kube-operator (0.3.8)

---

operators/external-secrets-operator/0.8.7/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.8.7/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.8.7/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.8.7/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.8.7/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.8.7/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.8.7/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.8.7/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.8.7/metadata/annotations.yaml
operators/external-secrets-operator/0.8.7/tests/scorecard/config.yaml

bump external-secrets-operator 0.8.7

operator external-secrets-operator (0.8.7)

---

operators/awx-operator/2.5.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.5.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.5.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.5.0/manifests/awx-operator.v2.5.0.clusterserviceversion.yaml
operators/awx-operator/2.5.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.5.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.5.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.5.0/metadata/annotations.yaml
operators/awx-operator/2.5.0/tests/scorecard/config.yaml

operator awx-operator (2.5.0)

---

operators/awx-operator/2.5.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.5.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.5.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.5.1/manifests/awx-operator.v2.5.1.clusterserviceversion.yaml
operators/awx-operator/2.5.1/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.5.1/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.5.1/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.5.1/metadata/annotations.yaml
operators/awx-operator/2.5.1/tests/scorecard/config.yaml

operator awx-operator (2.5.1)

---

operators/tempo-operator/0.4.0/bundle.Dockerfile
operators/tempo-operator/0.4.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.4.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.4.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.4.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.4.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.4.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.4.0/metadata/annotations.yaml
operators/tempo-operator/0.4.0/tests/scorecard/config.yaml

operator tempo-operator (0.4.0)

---

operators/pulsar-resources-operator/0.4.0-rc/bundle.Dockerfile
operators/pulsar-resources-operator/0.4.0-rc/manifests/pulsar-resources-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulsar-resources-operator/0.4.0-rc/manifests/pulsar-resources-operator-manager-config_v1_configmap.yaml
operators/pulsar-resources-operator/0.4.0-rc/manifests/pulsar-resources-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulsar-resources-operator/0.4.0-rc/manifests/pulsar-resources-operator.clusterserviceversion.yaml
operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsarconnections.yaml
operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsargeoreplications.yaml
operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsarnamespaces.yaml
operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsarpermissions.yaml
operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsartenants.yaml
operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsartopics.yaml
operators/pulsar-resources-operator/0.4.0-rc/metadata/annotations.yaml
operators/pulsar-resources-operator/0.4.0-rc/tests/scorecard/config.yaml

operator [N] pulsar-resources-operator (0.4.0-rc)

---

operators/api-testing-operator/0.0.1/manifests/core.linuxsuren.github.com_atests.yaml
operators/api-testing-operator/0.0.1/manifests/operator-controller-manager-metrics-service_v1_service.yaml
operators/api-testing-operator/0.0.1/manifests/operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/api-testing-operator/0.0.1/manifests/operator.clusterserviceversion.yaml
operators/api-testing-operator/0.0.1/metadata/annotations.yaml
operators/api-testing-operator/0.0.1/tests/scorecard/config.yaml
operators/api-testing-operator/ci.yaml

operator [N] [CI] api-testing-operator (0.0.1)

---

operators/dynatrace-operator/0.13.0/Dockerfile
operators/dynatrace-operator/0.13.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.13.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.13.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.13.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.13.0/metadata/annotations.yaml

operator dynatrace-operator (0.13.0)

---

operators/project-quay/3.10.0-nightly.20230818/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230818/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230818/metadata/annotations.yaml

Add 3.10.0-nightly.20230818 to community operators

operator project-quay (3.10.0-nightly.20230818)

---

operators/project-quay/3.10.0-nightly.20230819/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230819/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230819/metadata/annotations.yaml

Add 3.10.0-nightly.20230819 to community operators

operator project-quay (3.10.0-nightly.20230819)

---

operators/project-quay/3.10.0-nightly.20230820/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230820/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230820/metadata/annotations.yaml

Add 3.10.0-nightly.20230820 to community operators

operator project-quay (3.10.0-nightly.20230820)

---

operators/service-binding-operator/1.4.0/manifests/binding.operators.coreos.com_bindablekinds.yaml
operators/service-binding-operator/1.4.0/manifests/binding.operators.coreos.com_servicebindings.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-clusterworkloadresourcemappings-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-clusterworkloadresourcemappings-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-manager-config_v1_configmap.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-operator.clusterserviceversion.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/service-binding-operator/1.4.0/manifests/service-binding-webhook-service_v1_service.yaml
operators/service-binding-operator/1.4.0/manifests/servicebinding.io_clusterworkloadresourcemappings.yaml
operators/service-binding-operator/1.4.0/manifests/servicebinding.io_servicebindings.yaml
operators/service-binding-operator/1.4.0/metadata/annotations.yaml
operators/service-binding-operator/1.4.0/tests/scorecard/config.yaml

operator service-binding-operator (1.4.0)

---

operators/project-quay/3.10.0-nightly.20230822/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230822/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230822/metadata/annotations.yaml

Add 3.10.0-nightly.20230822 to community operators

operator project-quay (3.10.0-nightly.20230822)

---

operators/windup-operator/0.0.20/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.20/manifests/windup.crd.yaml
operators/windup-operator/0.0.20/metadata/annotations.yaml

operator windup-operator (0.0.20)

---

operators/project-quay/3.10.0-nightly.20230823/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230823/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230823/metadata/annotations.yaml

Add 3.10.0-nightly.20230823 to community operators

operator project-quay (3.10.0-nightly.20230823)

---

operators/victoriametrics-operator/ci.yaml

operator [CI] victoriametrics-operator

---

operators/move2kube-operator/0.3.9/bundle.Dockerfile
operators/move2kube-operator/0.3.9/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.9/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.9/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.9/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.9/metadata/annotations.yaml
operators/move2kube-operator/0.3.9/tests/scorecard/config.yaml

* [y] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [y] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [y] Have you tested your Operator with all Custom Resource Definitions?
* [y] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [y] Have you considered whether you want use [semantic versioning …

operator move2kube-operator (0.3.9)

---

operators/project-quay/3.10.0-nightly.20230824/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230824/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230824/metadata/annotations.yaml

Add 3.10.0-nightly.20230824 to community operators

operator project-quay (3.10.0-nightly.20230824)

---

operators/kubernetes-imagepuller-operator/1.0.6/manifests/che.eclipse.org_kubernetesimagepullers.yaml
operators/kubernetes-imagepuller-operator/1.0.6/manifests/controller-manager-metrics-service_v1_service.yaml
operators/kubernetes-imagepuller-operator/1.0.6/manifests/kubernetes-imagepuller-operator.v1.0.6.clusterserviceversion.yaml
operators/kubernetes-imagepuller-operator/1.0.6/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubernetes-imagepuller-operator/1.0.6/metadata/annotations.yaml
operators/kubernetes-imagepuller-operator/1.0.6/tests/scorecard/config.yaml

operator kubernetes-imagepuller-operator (1.0.6)

---

operators/external-secrets-operator/0.9.4/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.4/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.4/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.4/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.4/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.4/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.4/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.4/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.4/metadata/annotations.yaml
operators/external-secrets-operator/0.9.4/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.4

operator external-secrets-operator (0.9.4)

---

operators/gitlab-operator-kubernetes/0.23.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.23.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.23.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.23.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.23.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.23.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.23.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.23.0)

---

operators/mongodb-enterprise/1.21.0/bundle.Dockerfile
operators/mongodb-enterprise/1.21.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.21.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.21.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.21.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.21.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.21.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.21.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.21.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.21.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.21.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.21.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.21.0/tests/scorecard/config.yaml
operators/mongodb-enterprise/ci.yaml

This PR has been created by MongoDB Release Automation Tool (with a bit of help from me!).

operator [CI] mongodb-enterprise (1.21.0)

---

operators/sonataflow-operator/1.43.1/manifests/sonataflow-operator-builder-config_v1_configmap.yaml
operators/sonataflow-operator/1.43.1/manifests/sonataflow-operator-controller-manager-metrics-service_v1_service.yaml
operators/sonataflow-operator/1.43.1/manifests/sonataflow-operator-manager-config_v1_configmap.yaml
operators/sonataflow-operator/1.43.1/manifests/sonataflow-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/sonataflow-operator/1.43.1/manifests/sonataflow-operator.clusterserviceversion.yaml
operators/sonataflow-operator/1.43.1/manifests/sonataflow.org_sonataflowbuilds.yaml
operators/sonataflow-operator/1.43.1/manifests/sonataflow.org_sonataflowplatforms.yaml
operators/sonataflow-operator/1.43.1/manifests/sonataflow.org_sonataflows.yaml
operators/sonataflow-operator/1.43.1/metadata/annotations.yaml
operators/sonataflow-operator/1.43.1/tests/scorecard/config.yaml

operator sonataflow-operator (1.43.1)

---

operators/windup-operator/0.0.21/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.21/manifests/windup.crd.yaml
operators/windup-operator/0.0.21/metadata/annotations.yaml

operator windup-operator (0.0.21)

---

ci/pipeline-config-k8s.yaml

Bump kind version to v0.20.0

---

operators/rabbitmq-cluster-operator/2.5.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.5.0/manifests/crds.yaml
operators/rabbitmq-cluster-operator/2.5.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.5.0/metadata/annotations.yaml

operator rabbitmq-cluster-operator (2.5.0)

---

operators/dapr-kubernetes-operator/0.0.3/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
operators/dapr-kubernetes-operator/0.0.3/manifests/dapr.io_components.yaml
operators/dapr-kubernetes-operator/0.0.3/manifests/dapr.io_configurations.yaml
operators/dapr-kubernetes-operator/0.0.3/manifests/dapr.io_httpendpoints.yaml
operators/dapr-kubernetes-operator/0.0.3/manifests/dapr.io_resiliencies.yaml
operators/dapr-kubernetes-operator/0.0.3/manifests/dapr.io_subscriptions.yaml
operators/dapr-kubernetes-operator/0.0.3/manifests/operator.dapr.io_daprcontrolplanes.yaml
operators/dapr-kubernetes-operator/0.0.3/metadata/annotations.yaml
operators/dapr-kubernetes-operator/0.0.3/tests/scorecard/config.yaml
operators/dapr-kubernetes-operator/ci.yaml

operator [N] [CI] dapr-kubernetes-operator (0.0.3)

---

operators/edp-keycloak-operator/1.17.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.17.0/manifests/edp-keycloak-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/edp-keycloak-operator/1.17.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.17.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.17.0/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.17.0)

---

operators/mariadb-operator/0.20.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.20.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.20.0/metadata/annotations.yaml
operators/mariadb-operator/0.20.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.20.0) to community operators

operator mariadb-operator (0.20.0)

---

operators/gitlab-operator-kubernetes/0.23.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.23.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.23.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.23.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.23.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.23.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.23.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.23.1)

---

operators/jaeger/ci.yaml

operator [CI] jaeger

---

operators/edp-keycloak-operator/1.17.1/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.17.1/manifests/edp-keycloak-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/edp-keycloak-operator/1.17.1/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.17.1/metadata/annotations.yaml
operators/edp-keycloak-operator/1.17.1/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.17.1)

---

operators/temporal-operator/0.12.1/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.12.1/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.12.1/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.12.1/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.12.1/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.12.1/metadata/annotations.yaml

operator temporal-operator (0.12.1)

---

operators/grafana-operator/5.4.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.4.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.4.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.4.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.4.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.4.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.4.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.4.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.4.0/metadata/annotations.yaml

operator grafana-operator (5.4.0)

---

operators/trivy-operator/0.16.0/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.0/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.0/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.0/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.0/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.0/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.0/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.0/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.0/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.0/manifests/trivy-operator.v0.16.0.clusterserviceversion.yaml
operators/trivy-operator/0.16.0/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.0/metadata/annotations.yaml

operator trivy-operator (0.16.0)

---

operators/yaks/0.15.1/manifests/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.15.1/manifests/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.15.1/manifests/yaks.v0.15.1.clusterserviceversion.yaml
operators/yaks/0.15.1/metadata/annotations.yaml

operator yaks (0.15.1)

---

operators/pulp-operator/1.0.0-beta.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.0.0-beta.1/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.0.0-beta.1/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/pulp-operator/1.0.0-beta.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-beta.1/manifests/pulp-operator.clusterserviceversion.yaml
operators/pulp-operator/1.0.0-beta.1/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.0.0-beta.1/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.0.0-beta.1/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.0.0-beta.1/metadata/annotations.yaml
operators/pulp-operator/1.0.0-beta.1/tests/scorecard/config.yaml

operator pulp-operator (1.0.0-beta.1)

---

operators/awx-operator/2.5.2/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.5.2/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.5.2/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.5.2/manifests/awx-operator.v2.5.2.clusterserviceversion.yaml
operators/awx-operator/2.5.2/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.5.2/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.5.2/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.5.2/metadata/annotations.yaml
operators/awx-operator/2.5.2/tests/scorecard/config.yaml

operator awx-operator (2.5.2)

---

operators/gitlab-operator-kubernetes/0.23.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.23.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.23.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.23.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.23.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.23.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.23.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.23.2)

---

operators/kiali/1.73.0/bundle.Dockerfile
operators/kiali/1.73.0/manifests/kiali.crd.yaml
operators/kiali/1.73.0/manifests/kiali.v1.73.0.clusterserviceversion.yaml
operators/kiali/1.73.0/metadata/annotations.yaml

operator kiali (1.73.0)

---

operators/temporal-operator/ci.yaml

operator [CI] temporal-operator

---

operators/intel-device-plugins-operator/0.27.1/bundle.Dockerfile
operators/intel-device-plugins-operator/0.27.1/manifests/deviceplugin.intel.com_dlbdeviceplugins.yaml
operators/intel-device-plugins-operator/0.27.1/manifests/deviceplugin.intel.com_dsadeviceplugins.yaml
operators/intel-device-plugins-operator/0.27.1/manifests/deviceplugin.intel.com_fpgadeviceplugins.yaml
operators/intel-device-plugins-operator/0.27.1/manifests/deviceplugin.intel.com_gpudeviceplugins.yaml
operators/intel-device-plugins-operator/0.27.1/manifests/deviceplugin.intel.com_iaadeviceplugins.yaml
operators/intel-device-plugins-operator/0.27.1/manifests/deviceplugin.intel.com_qatdeviceplugins.yaml
operators/intel-device-plugins-operator/0.27.1/manifests/deviceplugin.intel.com_sgxdeviceplugins.yaml
operators/intel-device-plugins-operator/0.27.1/manifests/fpga.intel.com_acceleratorfunctions.yaml
operators/intel-device-plugins-operator/0.27.1/manifests/fpga.intel.com_fpgaregions.yaml
operators/intel-device-plugins-operator/0.27.1/manifests/intel-device-plugins-operator.clusterserviceversion.yaml
operators/intel-device-plugins-operator/0.27.1/metadata/annotations.yaml
operators/intel-device-plugins-operator/0.27.1/tests/scorecard/config.yaml

operator intel-device-plugins-operator (0.27.1)

---

operators/project-quay/3.9.1/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.1/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.1/metadata/annotations.yaml

Add 3.9.1 to community operators

operator project-quay (3.9.1)

---

operators/project-quay/3.10.0-nightly.20230911/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230911/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230911/metadata/annotations.yaml

Add 3.10.0-nightly.20230911 to community operators

operator project-quay (3.10.0-nightly.20230911)

---

operators/cass-operator-community/1.17.1/manifests/cass-operator-manager-config_v1_configmap.yaml
operators/cass-operator-community/1.17.1/manifests/cass-operator-webhook-service_v1_service.yaml
operators/cass-operator-community/1.17.1/manifests/cass-operator.clusterserviceversion.yaml
operators/cass-operator-community/1.17.1/manifests/cassandra.datastax.com_cassandradatacenters.yaml
operators/cass-operator-community/1.17.1/manifests/control.k8ssandra.io_cassandratasks.yaml
operators/cass-operator-community/1.17.1/metadata/annotations.yaml
operators/cass-operator-community/1.17.1/tests/scorecard/config.yaml

operator cass-operator-community (1.17.1)

---

operators/sonar-operator/3.1.0/manifests/edp.epam.com_sonargroups.yaml
operators/sonar-operator/3.1.0/manifests/edp.epam.com_sonarpermissiontemplates.yaml
operators/sonar-operator/3.1.0/manifests/edp.epam.com_sonarqualitygates.yaml
operators/sonar-operator/3.1.0/manifests/edp.epam.com_sonarqualityprofiles.yaml
operators/sonar-operator/3.1.0/manifests/edp.epam.com_sonars.yaml
operators/sonar-operator/3.1.0/manifests/edp.epam.com_sonarusers.yaml
operators/sonar-operator/3.1.0/manifests/sonar-operator.clusterserviceversion.yaml
operators/sonar-operator/3.1.0/metadata/annotations.yaml
operators/sonar-operator/3.1.0/tests/scorecard/config.yaml
operators/sonar-operator/ci.yaml

operator [N] [CI] sonar-operator (3.1.0)

---

operators/netobserv-operator/1.0.4/manifests/flows.netobserv.io_flowcollectors.yaml
operators/netobserv-operator/1.0.4/manifests/netobserv-manager-config_v1_configmap.yaml
operators/netobserv-operator/1.0.4/manifests/netobserv-metrics-service_v1_service.yaml
operators/netobserv-operator/1.0.4/manifests/netobserv-operator.clusterserviceversion.yaml
operators/netobserv-operator/1.0.4/manifests/netobserv-webhook-service_v1_service.yaml
operators/netobserv-operator/1.0.4/metadata/annotations.yaml

operator netobserv-operator (1.0.4)

---

operators/beegfs-csi-driver-operator/1.5.0/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml
operators/beegfs-csi-driver-operator/1.5.0/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml
operators/beegfs-csi-driver-operator/1.5.0/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/beegfs-csi-driver-operator/1.5.0/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml
operators/beegfs-csi-driver-operator/1.5.0/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml
operators/beegfs-csi-driver-operator/1.5.0/metadata/annotations.yaml
operators/beegfs-csi-driver-operator/1.5.0/tests/scorecard/config.yaml
operators/beegfs-csi-driver-operator/ci.yaml

operator [CI] beegfs-csi-driver-operator (1.5.0)

---

operators/grafana-operator/5.4.1/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.4.1/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.4.1/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.4.1/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.4.1/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.4.1/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.4.1/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.4.1/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.4.1/metadata/annotations.yaml

operator grafana-operator (5.4.1)

---

operators/project-quay/3.8.12/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.12/manifests/quayecosystems.crd.yaml
operators/project-quay/3.8.12/manifests/quayregistries.crd.yaml
operators/project-quay/3.8.12/metadata/annotations.yaml

Add 3.8.12 to community operators

operator project-quay (3.8.12)

---

operators/gitlab-operator-kubernetes/0.23.3/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.23.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.23.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.23.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.23.3/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.23.3/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.23.3/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.23.3)

---

operators/project-quay/3.10.0-nightly.20230913/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230913/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230913/metadata/annotations.yaml

Add 3.10.0-nightly.20230913 to community operators

operator project-quay (3.10.0-nightly.20230913)

---

operators/self-node-remediation/0.7.0/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml
operators/self-node-remediation/0.7.0/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.7.0/manifests/self-node-remediation-manager-config_v1_configmap.yaml
operators/self-node-remediation/0.7.0/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.7.0/manifests/self-node-remediation-webhook-service_v1_service.yaml
operators/self-node-remediation/0.7.0/manifests/self-node-remediation.clusterserviceversion.yaml
operators/self-node-remediation/0.7.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
operators/self-node-remediation/0.7.0/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
operators/self-node-remediation/0.7.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
operators/self-node-remediation/0.7.0/metadata/annotations.yaml
operators/self-node-remediation/0.7.0/tests/scorecard/config.yaml

operator self-node-remediation (0.7.0)

---

operators/pubsubplus-eventbroker-operator/1.0.1/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
operators/pubsubplus-eventbroker-operator/1.0.1/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
operators/pubsubplus-eventbroker-operator/1.0.1/metadata/annotations.yaml
operators/pubsubplus-eventbroker-operator/1.0.1/tests/scorecard/config.yaml

operator pubsubplus-eventbroker-operator (1.0.1)

---

operators/awx-operator/2.5.3/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.5.3/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.5.3/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.5.3/manifests/awx-operator.v2.5.3.clusterserviceversion.yaml
operators/awx-operator/2.5.3/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.5.3/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.5.3/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.5.3/metadata/annotations.yaml
operators/awx-operator/2.5.3/tests/scorecard/config.yaml

operator awx-operator (2.5.3)

---

operators/project-quay/3.10.0-nightly.20230914/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230914/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230914/metadata/annotations.yaml

Add 3.10.0-nightly.20230914 to community operators

operator project-quay (3.10.0-nightly.20230914)

---

operators/cryostat-operator/2.3.1/Dockerfile
operators/cryostat-operator/2.3.1/manifests/cryostat-operator-cryostat-namespaced_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.3.1/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.3.1/manifests/cryostat-operator-manager-config_v1_configmap.yaml
operators/cryostat-operator/2.3.1/manifests/cryostat-operator-oauth-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.3.1/manifests/cryostat-operator.clusterserviceversion.yaml
operators/cryostat-operator/2.3.1/manifests/operator.cryostat.io_clustercryostats.yaml
operators/cryostat-operator/2.3.1/manifests/operator.cryostat.io_cryostats.yaml
operators/cryostat-operator/2.3.1/metadata/annotations.yaml
operators/cryostat-operator/2.3.1/tests/scorecard/config.yaml
operators/cryostat-operator/ci.yaml

Signed-off-by: Ming Wang <miwan@redhat.com>

operator [CI] cryostat-operator (2.3.1)

---

operators/project-quay/3.10.0-nightly.20230915/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230915/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230915/metadata/annotations.yaml

Add 3.10.0-nightly.20230915 to community operators

operator project-quay (3.10.0-nightly.20230915)

---

operators/project-quay/3.10.0-nightly.20230916/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230916/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230916/metadata/annotations.yaml

Add 3.10.0-nightly.20230916 to community operators

operator project-quay (3.10.0-nightly.20230916)

---

operators/project-quay/3.10.0-nightly.20230917/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230917/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230917/metadata/annotations.yaml

Add 3.10.0-nightly.20230917 to community operators

operator project-quay (3.10.0-nightly.20230917)

---

operators/project-quay/3.10.0-nightly.20230918/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230918/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230918/metadata/annotations.yaml

Add 3.10.0-nightly.20230918 to community operators

operator project-quay (3.10.0-nightly.20230918)

---

operators/project-quay/3.10.0-nightly.20230919/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230919/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230919/metadata/annotations.yaml

Add 3.10.0-nightly.20230919 to community operators

operator project-quay (3.10.0-nightly.20230919)

---

operators/sonataflow-operator/1.44.1/manifests/sonataflow-operator-builder-config_v1_configmap.yaml
operators/sonataflow-operator/1.44.1/manifests/sonataflow-operator-controller-manager-metrics-service_v1_service.yaml
operators/sonataflow-operator/1.44.1/manifests/sonataflow-operator-manager-config_v1_configmap.yaml
operators/sonataflow-operator/1.44.1/manifests/sonataflow-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/sonataflow-operator/1.44.1/manifests/sonataflow-operator.clusterserviceversion.yaml
operators/sonataflow-operator/1.44.1/manifests/sonataflow.org_sonataflowbuilds.yaml
operators/sonataflow-operator/1.44.1/manifests/sonataflow.org_sonataflowplatforms.yaml
operators/sonataflow-operator/1.44.1/manifests/sonataflow.org_sonataflows.yaml
operators/sonataflow-operator/1.44.1/metadata/annotations.yaml
operators/sonataflow-operator/1.44.1/tests/scorecard/config.yaml

operator sonataflow-operator (1.44.1)

---

operators/project-quay/3.10.0-nightly.20230920/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230920/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230920/metadata/annotations.yaml

Add 3.10.0-nightly.20230920 to community operators

operator project-quay (3.10.0-nightly.20230920)

---

operators/node-maintenance-operator/0.16.0/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml
operators/node-maintenance-operator/0.16.0/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/node-maintenance-operator/0.16.0/manifests/node-maintenance-operator-webhook-service_v1_service.yaml
operators/node-maintenance-operator/0.16.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
operators/node-maintenance-operator/0.16.0/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml
operators/node-maintenance-operator/0.16.0/metadata/annotations.yaml
operators/node-maintenance-operator/0.16.0/tests/scorecard/config.yaml

Let NMO v0.16.0 be available on K8s community
--

operator node-maintenance-operator (0.16.0)

---

operators/project-quay/3.10.0-nightly.20230921/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230921/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230921/metadata/annotations.yaml

Add 3.10.0-nightly.20230921 to community operators

operator project-quay (3.10.0-nightly.20230921)

---

operators/external-secrets-operator/0.9.5/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.5/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.5/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.5/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.5/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.5/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.5/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.5/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.5/metadata/annotations.yaml
operators/external-secrets-operator/0.9.5/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.5

operator external-secrets-operator (0.9.5)

---

operators/gitlab-operator-kubernetes/0.23.4/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.23.4/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.23.4/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.23.4/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.23.4/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.23.4/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.23.4/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.23.4)

---

operators/project-quay/3.10.0-nightly.20230922/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230922/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230922/metadata/annotations.yaml

Add 3.10.0-nightly.20230922 to community operators

operator project-quay (3.10.0-nightly.20230922)

---

operators/node-healthcheck-operator/0.6.0/manifests/node-healthcheck-controller-manager-metrics-service_v1_service.yaml
operators/node-healthcheck-operator/0.6.0/manifests/node-healthcheck-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/node-healthcheck-operator/0.6.0/manifests/node-healthcheck-operator.clusterserviceversion.yaml
operators/node-healthcheck-operator/0.6.0/manifests/node-healthcheck-webhook-service_v1_service.yaml
operators/node-healthcheck-operator/0.6.0/manifests/remediation.medik8s.io_nodehealthchecks.yaml
operators/node-healthcheck-operator/0.6.0/metadata/annotations.yaml
operators/node-healthcheck-operator/0.6.0/metadata/dependencies.yaml
operators/node-healthcheck-operator/0.6.0/tests/scorecard/config.yaml

* [n/a] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [] Human readable name and 1-liner description about your Operator
--
<sup>2</sup> For more …

operator node-healthcheck-operator (0.6.0)

---

operators/snapscheduler/3.3.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml
operators/snapscheduler/3.3.0/manifests/snapscheduler-manager-config_v1_configmap.yaml
operators/snapscheduler/3.3.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/snapscheduler/3.3.0/manifests/snapscheduler.backube_snapshotschedules.yaml
operators/snapscheduler/3.3.0/manifests/snapscheduler.clusterserviceversion.yaml
operators/snapscheduler/3.3.0/metadata/annotations.yaml
operators/snapscheduler/3.3.0/tests/scorecard/config.yaml

operator snapscheduler (3.3.0)

---

operators/project-quay/3.10.0-nightly.20230923/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230923/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230923/metadata/annotations.yaml

Add 3.10.0-nightly.20230923 to community operators

operator project-quay (3.10.0-nightly.20230923)

---

operators/move2kube-operator/0.3.10-rc.0/bundle.Dockerfile
operators/move2kube-operator/0.3.10-rc.0/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.10-rc.0/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.10-rc.0/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.10-rc.0/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.10-rc.0/metadata/annotations.yaml
operators/move2kube-operator/0.3.10-rc.0/tests/scorecard/config.yaml

* [y] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [y] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [y] Have you tested your Operator with all Custom Resource Definitions?
* [y] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [y] Have you considered whether you want use [semantic versioning …

operator move2kube-operator (0.3.10-rc.0)

---

operators/move2kube-operator/0.3.10/bundle.Dockerfile
operators/move2kube-operator/0.3.10/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.10/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.10/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.10/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.10/metadata/annotations.yaml
operators/move2kube-operator/0.3.10/tests/scorecard/config.yaml

An automated PR to update move2kube-operator to v0.3.10

operator move2kube-operator (0.3.10)

---

operators/project-quay/3.10.0-nightly.20230925/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230925/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230925/metadata/annotations.yaml

Add 3.10.0-nightly.20230925 to community operators

operator project-quay (3.10.0-nightly.20230925)

---

operators/keda/2.11.2/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.11.2/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.11.2/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.11.2/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.11.2/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.11.2/manifests/keda.v2.11.2.clusterserviceversion.yaml
operators/keda/2.11.2/metadata/annotations.yaml

operator keda (2.11.2)

---

operators/project-quay/3.10.0-nightly.20230926/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230926/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230926/metadata/annotations.yaml

Add 3.10.0-nightly.20230926 to community operators

operator project-quay (3.10.0-nightly.20230926)

---

operators/trivy-operator/0.16.1/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.1/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.1/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.1/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.1/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.1/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.1/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.1/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.1/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.1/manifests/trivy-operator.v0.16.1.clusterserviceversion.yaml
operators/trivy-operator/0.16.1/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.1/metadata/annotations.yaml

operator trivy-operator (0.16.1)

---

operators/gitlab-operator-kubernetes/0.24.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.24.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.24.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.24.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.24.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.24.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.24.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.24.0)

---

operators/project-quay/3.9.2/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.2/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.2/metadata/annotations.yaml

Add 3.9.2 to community operators

operator project-quay (3.9.2)

---

operators/dapr-kubernetes-operator/0.0.4/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
operators/dapr-kubernetes-operator/0.0.4/manifests/dapr.io_components.yaml
operators/dapr-kubernetes-operator/0.0.4/manifests/dapr.io_configurations.yaml
operators/dapr-kubernetes-operator/0.0.4/manifests/dapr.io_httpendpoints.yaml
operators/dapr-kubernetes-operator/0.0.4/manifests/dapr.io_resiliencies.yaml
operators/dapr-kubernetes-operator/0.0.4/manifests/dapr.io_subscriptions.yaml
operators/dapr-kubernetes-operator/0.0.4/manifests/operator.dapr.io_daprcontrolplanes.yaml
operators/dapr-kubernetes-operator/0.0.4/metadata/annotations.yaml
operators/dapr-kubernetes-operator/0.0.4/tests/scorecard/config.yaml

operator dapr-kubernetes-operator (0.0.4)

---

operators/project-quay/3.10.0-nightly.20230929/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230929/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230929/metadata/annotations.yaml

Add 3.10.0-nightly.20230929 to community operators

operator project-quay (3.10.0-nightly.20230929)

---

operators/dell-csm-operator/1.3.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.3.0/manifests/dell-csm-operator.v1.3.0.clusterserviceversion.yaml
operators/dell-csm-operator/1.3.0/metadata/annotations.yaml
operators/dell-csm-operator/1.3.0/tests/scorecard/config.yaml

operator dell-csm-operator (1.3.0)

---

operators/limitador-operator/0.6.0/bundle.Dockerfile
operators/limitador-operator/0.6.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml
operators/limitador-operator/0.6.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
operators/limitador-operator/0.6.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/limitador-operator/0.6.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/0.6.0/manifests/limitador.kuadrant.io_limitadors.yaml
operators/limitador-operator/0.6.0/metadata/annotations.yaml
operators/limitador-operator/0.6.0/tests/scorecard/config.yaml

Signed-off-by: dd di cesare didi@posteo.net
--

operator limitador-operator (0.6.0)

---

operators/intel-device-plugins-operator/0.28.0/bundle.Dockerfile
operators/intel-device-plugins-operator/0.28.0/manifests/deviceplugin.intel.com_dlbdeviceplugins.yaml
operators/intel-device-plugins-operator/0.28.0/manifests/deviceplugin.intel.com_dsadeviceplugins.yaml
operators/intel-device-plugins-operator/0.28.0/manifests/deviceplugin.intel.com_fpgadeviceplugins.yaml
operators/intel-device-plugins-operator/0.28.0/manifests/deviceplugin.intel.com_gpudeviceplugins.yaml
operators/intel-device-plugins-operator/0.28.0/manifests/deviceplugin.intel.com_iaadeviceplugins.yaml
operators/intel-device-plugins-operator/0.28.0/manifests/deviceplugin.intel.com_qatdeviceplugins.yaml
operators/intel-device-plugins-operator/0.28.0/manifests/deviceplugin.intel.com_sgxdeviceplugins.yaml
operators/intel-device-plugins-operator/0.28.0/manifests/fpga.intel.com_acceleratorfunctions.yaml
operators/intel-device-plugins-operator/0.28.0/manifests/fpga.intel.com_fpgaregions.yaml
operators/intel-device-plugins-operator/0.28.0/manifests/intel-device-plugins-operator.clusterserviceversion.yaml
operators/intel-device-plugins-operator/0.28.0/metadata/annotations.yaml
operators/intel-device-plugins-operator/0.28.0/tests/scorecard/config.yaml

operator intel-device-plugins-operator (0.28.0)

---

operators/project-quay/3.10.0-nightly.20230930/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20230930/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20230930/metadata/annotations.yaml

Add 3.10.0-nightly.20230930 to community operators

operator project-quay (3.10.0-nightly.20230930)

---

operators/project-quay/3.10.0-nightly.20231001/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20231001/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20231001/metadata/annotations.yaml

Add 3.10.0-nightly.20231001 to community operators

operator project-quay (3.10.0-nightly.20231001)

---

operators/deployment-validation-operator/0.7.0/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.7.0/manifests/deploymentvalidationoperator.0.7.0.clusterserviceversion.yaml
operators/deployment-validation-operator/0.7.0/metadata/annotations.yaml
operators/deployment-validation-operator/0.7.0/tests/scorecard/config.yaml

operator deployment-validation-operator (0.7.0)

---

operators/gitlab-operator-kubernetes/0.24.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.24.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.24.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.24.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.24.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.24.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.24.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.24.1)

---

operators/debezium-operator/2.4.0/manifests/debezium-operator.v2.4.0.clusterserviceversion.yaml

Adding missing CRD metadata to 2.4.0 CSV.

operator [N] debezium-operator (2.4.0)

---

operators/project-quay/3.10.0-nightly.20231006/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20231006/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20231006/metadata/annotations.yaml

Add 3.10.0-nightly.20231006 to community operators

operator project-quay (3.10.0-nightly.20231006)

---

operators/project-quay/3.10.0-nightly.20231007/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20231007/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20231007/metadata/annotations.yaml

Add 3.10.0-nightly.20231007 to community operators

operator project-quay (3.10.0-nightly.20231007)

---

operators/kube-green/0.5.2/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml
operators/kube-green/0.5.2/manifests/kube-green-manager-config_v1_configmap.yaml
operators/kube-green/0.5.2/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kube-green/0.5.2/manifests/kube-green-webhook-service_v1_service.yaml
operators/kube-green/0.5.2/manifests/kube-green.clusterserviceversion.yaml
operators/kube-green/0.5.2/manifests/kube-green.com_sleepinfos.yaml
operators/kube-green/0.5.2/metadata/annotations.yaml
operators/kube-green/0.5.2/tests/scorecard/config.yaml

upgrade kube-green to version (0.5.2)

operator kube-green (0.5.2)

---

operators/project-quay/3.10.0-nightly.20231008/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20231008/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20231008/metadata/annotations.yaml

Add 3.10.0-nightly.20231008 to community operators

operator project-quay (3.10.0-nightly.20231008)

---

operators/project-quay/3.10.0-nightly.20231009/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20231009/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20231009/metadata/annotations.yaml

Add 3.10.0-nightly.20231009 to community operators

operator project-quay (3.10.0-nightly.20231009)

---

operators/cluster-manager/0.12.0/manifests/cluster-manager.clusterserviceversion.yaml
operators/cluster-manager/0.12.0/manifests/operator.open-cluster-management.io_clustermanagers.yaml
operators/cluster-manager/0.12.0/metadata/annotations.yaml

operator cluster-manager (0.12.0)

---

operators/cluster-manager/0.12.0/manifests/cluster-manager.clusterserviceversion.yaml

operator [O] cluster-manager (0.12.0)

---

operators/klusterlet/0.12.0/manifests/klusterlet.clusterserviceversion.yaml

operator [O] klusterlet (0.12.0)

---

operators/project-quay/3.10.0-nightly.20231010/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20231010/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20231010/metadata/annotations.yaml

Add 3.10.0-nightly.20231010 to community operators

operator project-quay (3.10.0-nightly.20231010)

---

operators/apicurio-registry/1.1.0-v2.4.12.final/bundle.Dockerfile
operators/apicurio-registry/1.1.0-v2.4.12.final/manifests/apicurio-registry-operator.clusterserviceversion.yaml
operators/apicurio-registry/1.1.0-v2.4.12.final/manifests/registry.apicur.io_apicurioregistries.yaml
operators/apicurio-registry/1.1.0-v2.4.12.final/metadata/annotations.yaml
operators/apicurio-registry/1.1.0-v2.4.12.final/tests/scorecard/config.yaml

operator apicurio-registry (1.1.0-v2.4.12.final)

---

operators/awx-operator/2.6.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.6.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.6.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.6.0/manifests/awx-operator.v2.6.0.clusterserviceversion.yaml
operators/awx-operator/2.6.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.6.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.6.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.6.0/metadata/annotations.yaml
operators/awx-operator/2.6.0/tests/scorecard/config.yaml

operator awx-operator (2.6.0)

---

operators/project-quay/3.10.0-nightly.20231011/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20231011/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20231011/metadata/annotations.yaml

Add 3.10.0-nightly.20231011 to community operators

operator project-quay (3.10.0-nightly.20231011)

---

operators/ndmspc-operator/0.3.2/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.3.2/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.3.2/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.3.2/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.3.2/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.3.2/metadata/annotations.yaml
operators/ndmspc-operator/0.3.2/tests/scorecard/config.yaml

operator ndmspc-operator (0.3.2)

---

operators/ndmspc-operator/0.3.3/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.3.3/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.3.3/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.3.3/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.3.3/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.3.3/metadata/annotations.yaml
operators/ndmspc-operator/0.3.3/tests/scorecard/config.yaml

operator ndmspc-operator (0.3.3)

---

operators/project-quay/3.10.0-nightly.20231012/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20231012/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20231012/metadata/annotations.yaml

Add 3.10.0-nightly.20231012 to community operators

operator project-quay (3.10.0-nightly.20231012)

---

operators/project-quay/3.10.0-nightly.20231013/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20231013/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20231013/metadata/annotations.yaml

Add 3.10.0-nightly.20231013 to community operators

operator project-quay (3.10.0-nightly.20231013)

---

operators/dapr-kubernetes-operator/0.0.5/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
operators/dapr-kubernetes-operator/0.0.5/manifests/dapr.io_components.yaml
operators/dapr-kubernetes-operator/0.0.5/manifests/dapr.io_configurations.yaml
operators/dapr-kubernetes-operator/0.0.5/manifests/dapr.io_httpendpoints.yaml
operators/dapr-kubernetes-operator/0.0.5/manifests/dapr.io_resiliencies.yaml
operators/dapr-kubernetes-operator/0.0.5/manifests/dapr.io_subscriptions.yaml
operators/dapr-kubernetes-operator/0.0.5/manifests/operator.dapr.io_daprcontrolplanes.yaml
operators/dapr-kubernetes-operator/0.0.5/metadata/annotations.yaml
operators/dapr-kubernetes-operator/0.0.5/tests/scorecard/config.yaml

Signed-off-by: Luca Burgazzoli <lburgazzoli@gmail.com>
--

operator dapr-kubernetes-operator (0.0.5)

---

operators/monocle-operator/0.0.2/manifests/monocle-operator-controller-manager-metrics-service_v1_service.yaml
operators/monocle-operator/0.0.2/manifests/monocle-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/monocle-operator/0.0.2/manifests/monocle-operator-monocle-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/monocle-operator/0.0.2/manifests/monocle-operator-monocle-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/monocle-operator/0.0.2/manifests/monocle-operator.clusterserviceversion.yaml
operators/monocle-operator/0.0.2/manifests/monocle.monocle.change-metrics.io_monocles.yaml
operators/monocle-operator/0.0.2/metadata/annotations.yaml
operators/monocle-operator/0.0.2/tests/scorecard/config.yaml

New version of the monocle-operator 0.0.2

operator monocle-operator (0.0.2)

---

operators/trivy-operator/0.16.2/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.2/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.2/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.2/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.2/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.2/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.2/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.2/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.2/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.2/manifests/trivy-operator.v0.16.2.clusterserviceversion.yaml
operators/trivy-operator/0.16.2/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.2/metadata/annotations.yaml

operator trivy-operator (0.16.2)

---

operators/ack-cloudwatchlogs-controller/ci.yaml

--
- Fixes: aws-controllers-k8s/community/issues/1923

operator [CI] ack-cloudwatchlogs-controller

---

operators/mariadb-operator/0.22.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.22.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.22.0/metadata/annotations.yaml
operators/mariadb-operator/0.22.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.22.0) to community operators

operator mariadb-operator (0.22.0)

---

operators/ndmspc-operator/0.4.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.4.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.4.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.4.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.4.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.4.0/metadata/annotations.yaml
operators/ndmspc-operator/0.4.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.4.0)

---

operators/project-quay/3.10.0-nightly.20231014/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0-nightly.20231014/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0-nightly.20231014/metadata/annotations.yaml

Add 3.10.0-nightly.20231014 to community operators

operator project-quay (3.10.0-nightly.20231014)

---

operators/windup-operator/0.0.22/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.22/manifests/windup.crd.yaml
operators/windup-operator/0.0.22/metadata/annotations.yaml

operator windup-operator (0.0.22)

---

operators/ndmspc-operator/0.5.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.5.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.5.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.5.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.5.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.5.0/metadata/annotations.yaml
operators/ndmspc-operator/0.5.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.5.0)

---

operators/ndmspc-operator/0.6.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.6.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.6.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.6.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.6.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.6.0/metadata/annotations.yaml
operators/ndmspc-operator/0.6.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.6.0)

---

operators/external-secrets-operator/0.9.6/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.6/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.6/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.6/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.6/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.6/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.6/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.6/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.6/metadata/annotations.yaml
operators/external-secrets-operator/0.9.6/tests/scorecard/config.yaml

chore: bump external secrets 0.9.6

operator external-secrets-operator (0.9.6)

---

operators/registry-operator/0.1.3/bundle.Dockerfile
operators/registry-operator/0.1.3/manifests/registry-operator-controller-manager-metrics-service_v1_service.yaml
operators/registry-operator/0.1.3/manifests/registry-operator-manager-config_v1_configmap.yaml
operators/registry-operator/0.1.3/manifests/registry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/registry-operator/0.1.3/manifests/registry-operator-webhook-service_v1_service.yaml
operators/registry-operator/0.1.3/manifests/registry-operator.clusterserviceversion.yaml
operators/registry-operator/0.1.3/manifests/registry.devfile.io_clusterdevfileregistrieslists.yaml
operators/registry-operator/0.1.3/manifests/registry.devfile.io_devfileregistries.yaml
operators/registry-operator/0.1.3/manifests/registry.devfile.io_devfileregistrieslists.yaml
operators/registry-operator/0.1.3/metadata/annotations.yaml
operators/registry-operator/0.1.3/tests/scorecard/config.yaml

operator [N] registry-operator (0.1.3)

---

operators/dynatrace-operator/0.14.0/Dockerfile
operators/dynatrace-operator/0.14.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/0.14.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.14.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.14.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.14.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.14.0/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/0.14.0/metadata/annotations.yaml

operator dynatrace-operator (0.14.0)

---

operators/mongodb-atlas-kubernetes/1.9.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/1.9.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/1.9.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/1.9.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/1.9.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/1.9.0/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (1.9.0)

---

operators/kaoto-operator/0.0.9/manifests/designer.kaoto.io_kaotoes.yaml
operators/kaoto-operator/0.0.9/manifests/kaoto-backend_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kaoto-operator/0.0.9/manifests/kaoto-operator.0.0.9.clusterserviceversion.yaml
operators/kaoto-operator/0.0.9/metadata/annotations.yaml
operators/kaoto-operator/0.0.9/tests/scorecard/config.yaml

Signed-off-by: Luca Burgazzoli <lburgazzoli@gmail.com>
--

operator kaoto-operator (0.0.9)

---

operators/pulp-operator/1.0.0-beta.2/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.0.0-beta.2/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.0.0-beta.2/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/pulp-operator/1.0.0-beta.2/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-beta.2/manifests/pulp-operator.clusterserviceversion.yaml
operators/pulp-operator/1.0.0-beta.2/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.0.0-beta.2/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.0.0-beta.2/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.0.0-beta.2/metadata/annotations.yaml
operators/pulp-operator/1.0.0-beta.2/tests/scorecard/config.yaml

operator pulp-operator (1.0.0-beta.2)

---

operators/yaks/0.16.0/manifests/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.16.0/manifests/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.16.0/manifests/yaks.v0.16.0.clusterserviceversion.yaml
operators/yaks/0.16.0/metadata/annotations.yaml
operators/yaks/0.16.0/tests/scorecard/config.yaml

operator yaks (0.16.0)

---

operators/project-quay/3.9.3/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.3/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.3/metadata/annotations.yaml

Add 3.9.3 to community operators

operator project-quay (3.9.3)

---

operators/sn-operator/ci.yaml

operator [CI] sn-operator

---

operators/cloudnative-pg/1.21.0/manifests/cloudnative-pg.clusterserviceversion.yaml
operators/cloudnative-pg/1.21.0/manifests/cnpg-default-monitoring_v1_configmap.yaml
operators/cloudnative-pg/1.21.0/manifests/cnpg-webhook-service_v1_service.yaml
operators/cloudnative-pg/1.21.0/manifests/postgresql.cnpg.io_backups.yaml
operators/cloudnative-pg/1.21.0/manifests/postgresql.cnpg.io_clusters.yaml
operators/cloudnative-pg/1.21.0/manifests/postgresql.cnpg.io_poolers.yaml
operators/cloudnative-pg/1.21.0/manifests/postgresql.cnpg.io_scheduledbackups.yaml
operators/cloudnative-pg/1.21.0/metadata/annotations.yaml
operators/cloudnative-pg/1.21.0/tests/scorecard/config.yaml
operators/cloudnative-pg/ci.yaml

operator [N] [CI] cloudnative-pg (1.21.0)

---

operators/aqua/2022.4.13/manifests/aqua-operator.v2022.4.13.clusterserviceversion.yaml

operator [O] aqua (2022.4.13)

---

operators/trivy-operator/0.16.3/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.3/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.3/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.3/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.3/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.3/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.3/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.3/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.3/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.3/manifests/trivy-operator.v0.16.3.clusterserviceversion.yaml
operators/trivy-operator/0.16.3/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.3/metadata/annotations.yaml

operator trivy-operator (0.16.3)

---

operators/pulsar-operator/ci.yaml

operator [CI] pulsar-operator

---

operators/bookkeeper-operator/ci.yaml

operator [CI] bookkeeper-operator

---

operators/zookeeper-operator/ci.yaml

operator [CI] zookeeper-operator

---

operators/pulsar-resources-operator/ci.yaml

operator [CI] pulsar-resources-operator

---

operators/function-mesh/ci.yaml

operator [CI] function-mesh

---

operators/authorino-operator/0.9.0/bundle.Dockerfile
operators/authorino-operator/0.9.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.9.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.9.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.9.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.9.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.9.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
operators/authorino-operator/0.9.0/manifests/authorino-operator-manager-config_v1_configmap.yaml
operators/authorino-operator/0.9.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.9.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.9.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.9.0/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.9.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.9.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.9.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.9.0/metadata/annotations.yaml
operators/authorino-operator/0.9.0/tests/scorecard/config.yaml

Signed-off-by: dd di cesare [didi@posteo.net](mailto:didi@posteo.net)
--

operator authorino-operator (0.9.0)

---

operators/sn-operator/0.3.0-rc.5/manifests/sn-operator.clusterserviceversion.yaml

operator [N] sn-operator (0.3.0-rc.5)

---

operators/external-secrets-operator/0.9.7/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.7/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.7/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.7/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.7/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.7/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.7/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.7/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.7/metadata/annotations.yaml
operators/external-secrets-operator/0.9.7/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.7

operator external-secrets-operator (0.9.7)

---

operators/gitlab-operator-kubernetes/0.25.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.25.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.25.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.25.0)

---

operators/windup-operator/0.0.23/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.23/manifests/windup.crd.yaml
operators/windup-operator/0.0.23/metadata/annotations.yaml

operator windup-operator (0.0.23)

---

operators/camel-k/2.1.0/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.1.0/manifests/camel-k.v2.1.0.clusterserviceversion.yaml
operators/camel-k/2.1.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.1.0/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.1.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.1.0/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.1.0/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/2.1.0/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.1.0/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.1.0/metadata/annotations.yaml
operators/camel-k/2.1.0/tests/scorecard/config.yaml

operator camel-k (2.1.0)

---

operators/dynatrace-operator/0.14.1/Dockerfile
operators/dynatrace-operator/0.14.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/0.14.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.14.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.14.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.14.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.14.1/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/0.14.1/metadata/annotations.yaml

operator dynatrace-operator (0.14.1)

---

operators/awx-operator/2.7.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.7.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.7.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.7.1/manifests/awx-operator.v2.7.1.clusterserviceversion.yaml
operators/awx-operator/2.7.1/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.7.1/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.7.1/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.7.1/metadata/annotations.yaml
operators/awx-operator/2.7.1/tests/scorecard/config.yaml

operator awx-operator (2.7.1)

---

operators/eginnovations-operator/0.0.6/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml
operators/eginnovations-operator/0.0.6/manifests/eginnovations-operator-manager-config_v1_configmap.yaml
operators/eginnovations-operator/0.0.6/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/eginnovations-operator/0.0.6/manifests/eginnovations-operator-webhook-service_v1_service.yaml
operators/eginnovations-operator/0.0.6/manifests/eginnovations-operator.clusterserviceversion.yaml
operators/eginnovations-operator/0.0.6/manifests/eginnovations.com_eguniversalagents.yaml
operators/eginnovations-operator/0.0.6/metadata/annotations.yaml
operators/eginnovations-operator/0.0.6/tests/scorecard/config.yaml

operator eginnovations-operator (0.0.6)

---

operators/deployment-validation-operator/0.7.1/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.7.1/manifests/deploymentvalidationoperator.0.7.1.clusterserviceversion.yaml
operators/deployment-validation-operator/0.7.1/metadata/annotations.yaml
operators/deployment-validation-operator/0.7.1/tests/scorecard/config.yaml

operator deployment-validation-operator (0.7.1)

---

operators/kuadrant-operator/0.4.0/bundle.Dockerfile
operators/kuadrant-operator/0.4.0/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
operators/kuadrant-operator/0.4.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.4.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.4.0/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.4.0/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.4.0/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.4.0/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.4.0/metadata/annotations.yaml
operators/kuadrant-operator/0.4.0/metadata/dependencies.yaml
operators/kuadrant-operator/0.4.0/tests/scorecard/config.yaml

operator kuadrant-operator (0.4.0)

---

operators/knative-operator/1.12.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.12.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.12.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.12.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.12.0/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.12.0/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.12.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.12.0/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.12.0/manifests/knative-operator.v1.12.0.clusterserviceversion.yaml
operators/knative-operator/1.12.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.12.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.12.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.12.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.12.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.12.0/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.12.0/metadata/annotations.yaml
operators/knative-operator/1.12.0/tests/scorecard/config.yaml

operator knative-operator (1.12.0)

---

operators/trivy-operator/0.16.4/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.4/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.4/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.4/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.4/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.4/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.4/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.4/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.4/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.4/manifests/trivy-operator.v0.16.4.clusterserviceversion.yaml
operators/trivy-operator/0.16.4/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.16.4/metadata/annotations.yaml

operator trivy-operator (0.16.4)

---

operators/aqua/2022.4.14/bundle.Dockerfile
operators/aqua/2022.4.14/manifests/aqua-operator.v2022.4.14.clusterserviceversion.yaml
operators/aqua/2022.4.14/manifests/aquacloudconnector.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.14/manifests/aquacsps.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.14/manifests/aquadatabases.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.14/manifests/aquaenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.14/manifests/aquagateways.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.14/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.14/manifests/aqualightnings.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.14/manifests/aquascanners.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.14/manifests/aquaservers.operator.aquasec.com.crd.yaml
operators/aqua/2022.4.14/manifests/aquastarboards.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.14/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.14/manifests/configauditreports.aquasecurity.github.io.crd.yaml
operators/aqua/2022.4.14/metadata/annotations.yaml

operator aqua (2022.4.14)

---

operators/gitlab-operator-kubernetes/0.25.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.25.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.25.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.25.1)

---

operators/project-quay/3.9.4/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.4/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.4/metadata/annotations.yaml

Add 3.9.4 to community operators

operator project-quay (3.9.4)

---

operators/grafana-operator/5.4.2/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.4.2/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.4.2/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.4.2/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.4.2/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.4.2/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.4.2/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.4.2/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.4.2/metadata/annotations.yaml

operator grafana-operator (5.4.2)

---

operators/skupper-operator/1.4.3/manifests/skupper-operator.v1.4.3.clusterserviceversion.yaml

operator [N] skupper-operator (1.4.3)

---

operators/rabbitmq-messaging-topology-operator/1.12.1/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_bindings.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_exchanges.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_federations.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_permissions.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_policies.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_queues.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_schemareplications.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_shovels.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_superstreams.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_topicpermissions.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_users.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_vhosts.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.webhook-service.yaml
operators/rabbitmq-messaging-topology-operator/1.12.1/metadata/annotations.yaml

operator rabbitmq-messaging-topology-operator (1.12.1)

---

operators/kuadrant-operator/0.4.1/bundle.Dockerfile
operators/kuadrant-operator/0.4.1/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
operators/kuadrant-operator/0.4.1/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.4.1/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.4.1/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.4.1/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.4.1/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.4.1/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.4.1/metadata/annotations.yaml
operators/kuadrant-operator/0.4.1/metadata/dependencies.yaml
operators/kuadrant-operator/0.4.1/tests/scorecard/config.yaml

operator kuadrant-operator (0.4.1)

---

operators/move2kube-operator/0.3.11/bundle.Dockerfile
operators/move2kube-operator/0.3.11/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.11/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.11/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.11/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.11/metadata/annotations.yaml
operators/move2kube-operator/0.3.11/tests/scorecard/config.yaml

An automated PR to update move2kube-operator to v0.3.11

operator move2kube-operator (0.3.11)

---

operators/awx-operator/2.7.2/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.7.2/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.7.2/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.7.2/manifests/awx-operator.v2.7.2.clusterserviceversion.yaml
operators/awx-operator/2.7.2/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.7.2/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.7.2/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.7.2/metadata/annotations.yaml
operators/awx-operator/2.7.2/tests/scorecard/config.yaml

operator awx-operator (2.7.2)

---

operators/ibm-application-gateway-operator/23.11.0/manifests/ibm-application-gateway-operator-ctrl-mgr-metrics-service_v1_service.yaml
operators/ibm-application-gateway-operator/23.11.0/manifests/ibm-application-gateway-operator-manager-config_v1_configmap.yaml
operators/ibm-application-gateway-operator/23.11.0/manifests/ibm-application-gateway-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ibm-application-gateway-operator/23.11.0/manifests/ibm-application-gateway-operator-webhook-service_v1_service.yaml
operators/ibm-application-gateway-operator/23.11.0/manifests/ibm-application-gateway-operator.clusterserviceversion.yaml
operators/ibm-application-gateway-operator/23.11.0/manifests/ibm.com_ibmapplicationgateways.yaml
operators/ibm-application-gateway-operator/23.11.0/metadata/annotations.yaml
operators/ibm-application-gateway-operator/23.11.0/tests/scorecard/config.yaml

operator ibm-application-gateway-operator (23.11.0)

---

operators/ack-cloudfront-controller/ci.yaml

operator [CI] ack-cloudfront-controller

---

operators/elastic-cloud-eck/2.10.0/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.10.0/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.10.0/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.10.0/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.10.0/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.10.0/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.10.0/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.10.0/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.10.0/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.10.0/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.10.0/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.10.0/metadata/annotations.yaml

Update the ECK operator to the latest version `2.10.0`.

operator elastic-cloud-eck (2.10.0)

---

operators/clickhouse/0.22.0/manifests/clickhouse-operator.v0.22.0.clusterserviceversion.yaml
operators/clickhouse/0.22.0/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.22.0/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.22.0/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.22.0/metadata/annotations.yaml

operator clickhouse (0.22.0)

---

operators/integration-operator/1.0.0/manifests/integration-operator.v1.0.0.clusterserviceversion.yaml
operators/integration-operator/1.0.0/manifests/integration.rock8s.com_plugs.yaml
operators/integration-operator/1.0.0/manifests/integration.rock8s.com_sockets.yaml
operators/integration-operator/1.0.0/metadata/annotations.yaml
operators/integration-operator/ci.yaml

operator [N] [CI] integration-operator (1.0.0)

---

operators/konveyor-operator/ci.yaml

This is really just meant to switch the konveyor-operator to use the semver-mode.

operator [CI] konveyor-operator

---

operators/skupper-operator/1.5.0/manifests/skupper-operator.v1.5.0.clusterserviceversion.yaml
operators/skupper-operator/1.5.0/metadata/annotations.yaml

operator skupper-operator (1.5.0)

---

operators/shipwright-operator/0.12.0/manifests/operator.shipwright.io_shipwrightbuilds.yaml
operators/shipwright-operator/0.12.0/manifests/shipwright-operator-manager-config_v1_configmap.yaml
operators/shipwright-operator/0.12.0/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/shipwright-operator/0.12.0/manifests/shipwright-operator-metrics-service_v1_service.yaml
operators/shipwright-operator/0.12.0/manifests/shipwright-operator.clusterserviceversion.yaml
operators/shipwright-operator/0.12.0/metadata/annotations.yaml
operators/shipwright-operator/0.12.0/tests/scorecard/config.yaml

Update Shipwright Operator to v0.12.0. From bundle ghcr.io/shipwright-io/operator/operator-bundle:v0.12.
--

operator shipwright-operator (0.12.0)

---

operators/external-secrets-operator/ci.yaml

operator [CI] external-secrets-operator

---

operators/external-secrets-operator/0.9.9/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.9/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.9/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.9/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.9/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.9/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.9/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.9/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.9/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.9/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.9/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.9/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.9/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.9/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.9/metadata/annotations.yaml
operators/external-secrets-operator/0.9.9/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.9

operator external-secrets-operator (0.9.9)

---

operators/node-healthcheck-operator/0.6.1/manifests/node-healthcheck-controller-manager-metrics-service_v1_service.yaml
operators/node-healthcheck-operator/0.6.1/manifests/node-healthcheck-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/node-healthcheck-operator/0.6.1/manifests/node-healthcheck-operator.clusterserviceversion.yaml
operators/node-healthcheck-operator/0.6.1/manifests/node-healthcheck-webhook-service_v1_service.yaml
operators/node-healthcheck-operator/0.6.1/manifests/remediation.medik8s.io_nodehealthchecks.yaml
operators/node-healthcheck-operator/0.6.1/metadata/annotations.yaml
operators/node-healthcheck-operator/0.6.1/metadata/dependencies.yaml
operators/node-healthcheck-operator/0.6.1/tests/scorecard/config.yaml

1. x ] Description about the managed Application and where to find more information
--

operator node-healthcheck-operator (0.6.1)

---

operators/edp-keycloak-operator/1.18.2/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.18.2/manifests/edp-keycloak-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/edp-keycloak-operator/1.18.2/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.18.2/metadata/annotations.yaml
operators/edp-keycloak-operator/1.18.2/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.18.2)

---

operators/yaks/0.17.1/manifests/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.17.1/manifests/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.17.1/manifests/yaks.v0.17.1.clusterserviceversion.yaml
operators/yaks/0.17.1/metadata/annotations.yaml
operators/yaks/0.17.1/tests/scorecard/config.yaml

operator yaks (0.17.1)

---

operators/edp-keycloak-operator/1.19.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.19.0/manifests/edp-keycloak-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/edp-keycloak-operator/1.19.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.19.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.19.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.19.0/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.19.0)

---

operators/pubsubplus-eventbroker-operator/1.0.2/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
operators/pubsubplus-eventbroker-operator/1.0.2/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
operators/pubsubplus-eventbroker-operator/1.0.2/metadata/annotations.yaml
operators/pubsubplus-eventbroker-operator/1.0.2/tests/scorecard/config.yaml

operator pubsubplus-eventbroker-operator (1.0.2)

---

operators/dynatrace-operator/0.14.2/Dockerfile
operators/dynatrace-operator/0.14.2/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/0.14.2/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.14.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.14.2/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.14.2/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.14.2/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/0.14.2/metadata/annotations.yaml

operator dynatrace-operator (0.14.2)

---

operators/deployment-validation-operator/0.7.3/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.7.3/manifests/deploymentvalidationoperator.0.7.3.clusterserviceversion.yaml
operators/deployment-validation-operator/0.7.3/metadata/annotations.yaml
operators/deployment-validation-operator/0.7.3/tests/scorecard/config.yaml

operator deployment-validation-operator (0.7.3)

---

operators/node-maintenance-operator/0.16.1/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml
operators/node-maintenance-operator/0.16.1/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/node-maintenance-operator/0.16.1/manifests/node-maintenance-operator-webhook-service_v1_service.yaml
operators/node-maintenance-operator/0.16.1/manifests/node-maintenance-operator.clusterserviceversion.yaml
operators/node-maintenance-operator/0.16.1/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml
operators/node-maintenance-operator/0.16.1/metadata/annotations.yaml
operators/node-maintenance-operator/0.16.1/tests/scorecard/config.yaml

Let NMO v0.16.1 be available on K8s community
--

operator node-maintenance-operator (0.16.1)

---

operators/gitlab-operator-kubernetes/0.25.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.25.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.25.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.25.2)

---

operators/ack-acmpca-controller/ci.yaml

operator [CI] ack-acmpca-controller

---

operators/ack-drs-controller/ci.yaml

operator [CI] ack-drs-controller

---

operators/gitlab-operator-kubernetes/0.26.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.26.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.26.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.26.0)

---

operators/intel-ethernet-operator/2.0.0/manifests/ethernet.intel.com_ethernetclusterconfigs.yaml
operators/intel-ethernet-operator/2.0.0/manifests/ethernet.intel.com_ethernetnodeconfigs.yaml
operators/intel-ethernet-operator/2.0.0/manifests/flowconfig.intel.com_clusterflowconfigs.yaml
operators/intel-ethernet-operator/2.0.0/manifests/flowconfig.intel.com_flowconfignodeagentdeployments.yaml
operators/intel-ethernet-operator/2.0.0/manifests/flowconfig.intel.com_nodeflowconfigs.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator-ethernetclusterconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator-ethernetclusterconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator-ethernetnodeconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator-ethernetnodeconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator-flowconfignodeagentdeployment-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator-flowconfignodeagentdeployment-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator-manager-config_v1_configmap.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator-nodeflowconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator-nodeflowconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator-webhook-service_v1_service.yaml
operators/intel-ethernet-operator/2.0.0/manifests/intel-ethernet-operator.clusterserviceversion.yaml
operators/intel-ethernet-operator/2.0.0/metadata/annotations.yaml
operators/intel-ethernet-operator/2.0.0/tests/scorecard/config.yaml
operators/intel-ethernet-operator/ci.yaml

operator [N] [CI] intel-ethernet-operator (2.0.0)

---

operators/cc-operator/0.8.0/manifests/cc-operator-controller-manager-metrics-service_v1_service.yaml
operators/cc-operator/0.8.0/manifests/cc-operator-manager-config_v1_configmap.yaml
operators/cc-operator/0.8.0/manifests/cc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cc-operator/0.8.0/manifests/cc-operator.clusterserviceversion.yaml
operators/cc-operator/0.8.0/manifests/confidentialcontainers.org_ccruntimes.yaml
operators/cc-operator/0.8.0/metadata/annotations.yaml
operators/cc-operator/0.8.0/tests/scorecard/config.yaml

operator cc-operator (0.8.0)

---

operators/project-quay/3.9.5/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.5/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.5/metadata/annotations.yaml

Add 3.9.5 to community operators

operator project-quay (3.9.5)

---

operators/registry-operator/0.2.0/bundle.Dockerfile
operators/registry-operator/0.2.0/manifests/registry-operator-controller-manager-metrics-service_v1_service.yaml
operators/registry-operator/0.2.0/manifests/registry-operator-manager-config_v1_configmap.yaml
operators/registry-operator/0.2.0/manifests/registry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/registry-operator/0.2.0/manifests/registry-operator-webhook-service_v1_service.yaml
operators/registry-operator/0.2.0/manifests/registry-operator.clusterserviceversion.yaml
operators/registry-operator/0.2.0/manifests/registry.devfile.io_clusterdevfileregistrieslists.yaml
operators/registry-operator/0.2.0/manifests/registry.devfile.io_devfileregistries.yaml
operators/registry-operator/0.2.0/manifests/registry.devfile.io_devfileregistrieslists.yaml
operators/registry-operator/0.2.0/metadata/annotations.yaml
operators/registry-operator/0.2.0/tests/scorecard/config.yaml
operators/registry-operator/ci.yaml

operator [CI] registry-operator (0.2.0)

---

operators/awx-operator/2.8.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.8.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.8.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.8.0/manifests/awx-operator.v2.8.0.clusterserviceversion.yaml
operators/awx-operator/2.8.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.8.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.8.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.8.0/metadata/annotations.yaml
operators/awx-operator/2.8.0/tests/scorecard/config.yaml

operator awx-operator (2.8.0)

---

operators/grafana-operator/5.5.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.5.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.5.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.5.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.5.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.5.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.5.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.5.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.5.0/metadata/annotations.yaml

operator grafana-operator (5.5.0)

---

operators/mondoo-operator/1.18.0/manifests/k8s.mondoo.com_mondooauditconfigs.yaml
operators/mondoo-operator/1.18.0/manifests/k8s.mondoo.com_mondoooperatorconfigs.yaml
operators/mondoo-operator/1.18.0/manifests/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
operators/mondoo-operator/1.18.0/manifests/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mondoo-operator/1.18.0/manifests/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/mondoo-operator/1.18.0/manifests/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
operators/mondoo-operator/1.18.0/manifests/mondoo-operator-manager-config_v1_configmap.yaml
operators/mondoo-operator/1.18.0/manifests/mondoo-operator-webhook_v1_serviceaccount.yaml
operators/mondoo-operator/1.18.0/manifests/mondoo-operator.clusterserviceversion.yaml
operators/mondoo-operator/1.18.0/metadata/annotations.yaml
operators/mondoo-operator/1.18.0/tests/scorecard/config.yaml

operator mondoo-operator (1.18.0)

---

operators/tempo-operator/0.6.0/bundle.Dockerfile
operators/tempo-operator/0.6.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.6.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.6.0/metadata/annotations.yaml
operators/tempo-operator/0.6.0/tests/scorecard/config.yaml

Release tempo-operator `0.6.0`.

operator tempo-operator (0.6.0)

---

operators/trivy-operator/0.17.0/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/manifests/trivy-operator.v0.17.0.clusterserviceversion.yaml
operators/trivy-operator/0.17.0/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.0/metadata/annotations.yaml

operator trivy-operator (0.17.0)

---

operators/grafana-operator/5.5.2/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.5.2/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.5.2/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.5.2/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.5.2/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.5.2/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.5.2/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.5.2/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.5.2/metadata/annotations.yaml

operator grafana-operator (5.5.2)

---

operators/authorino-operator/0.10.0/bundle.Dockerfile
operators/authorino-operator/0.10.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.10.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.10.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.10.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.10.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.10.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
operators/authorino-operator/0.10.0/manifests/authorino-operator-manager-config_v1_configmap.yaml
operators/authorino-operator/0.10.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.10.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.10.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.10.0/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.10.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.10.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.10.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.10.0/metadata/annotations.yaml
operators/authorino-operator/0.10.0/tests/scorecard/config.yaml

operator authorino-operator (0.10.0)

---

operators/trivy-operator/0.17.1/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/manifests/trivy-operator.v0.17.1.clusterserviceversion.yaml
operators/trivy-operator/0.17.1/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.17.1/metadata/annotations.yaml

operator trivy-operator (0.17.1)

---

operators/trident-operator/23.10.0/manifests/trident-operator.v22.10.0.clusterserviceversion.yaml
operators/trident-operator/23.10.0/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
operators/trident-operator/23.10.0/metadata/annotations.yaml

operator trident-operator (23.10.0)

---

operators/project-quay/3.10.0/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.0/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.0/metadata/annotations.yaml

Add 3.10.0 to community operators

operator project-quay (3.10.0)

---

operators/gitlab-operator-kubernetes/0.26.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.26.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.26.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.26.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.26.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.26.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.26.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.26.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.26.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.26.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.26.1)

---

operators/pulp-operator/1.0.0-beta.3/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.0.0-beta.3/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.0.0-beta.3/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/pulp-operator/1.0.0-beta.3/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-beta.3/manifests/pulp-operator.clusterserviceversion.yaml
operators/pulp-operator/1.0.0-beta.3/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.0.0-beta.3/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.0.0-beta.3/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.0.0-beta.3/metadata/annotations.yaml
operators/pulp-operator/1.0.0-beta.3/tests/scorecard/config.yaml

operator pulp-operator (1.0.0-beta.3)

---

operators/mariadb-operator/0.23.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.23.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.23.0/metadata/annotations.yaml
operators/mariadb-operator/0.23.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.23.0) to community operators

operator mariadb-operator (0.23.0)

---

operators/mariadb-operator/0.23.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.23.1/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.23.1/metadata/annotations.yaml
operators/mariadb-operator/0.23.1/tests/scorecard/config.yaml

Add operator mariadb-operator (0.23.1) to community operators

operator mariadb-operator (0.23.1)

---

operators/windup-operator/0.0.24/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.24/manifests/windup.crd.yaml
operators/windup-operator/0.0.24/metadata/annotations.yaml

operator windup-operator (0.0.24)

---

operators/limitador-operator/0.7.0/bundle.Dockerfile
operators/limitador-operator/0.7.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml
operators/limitador-operator/0.7.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
operators/limitador-operator/0.7.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/limitador-operator/0.7.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/0.7.0/manifests/limitador.kuadrant.io_limitadors.yaml
operators/limitador-operator/0.7.0/metadata/annotations.yaml
operators/limitador-operator/0.7.0/tests/scorecard/config.yaml

operator limitador-operator (0.7.0)
