operators/wildfly/0.5.2/bundle.Dockerfile, operators/wildfly/0.5.2/manifests/wildfly-operator.v0.5.2.clusterserviceversion.yaml, operators/wildfly/0.5.2/manifests/wildflyservers.wildfly.org.crd.yaml, operators/wildfly/0.5.2/metadata/annotations.yaml
This version uses the apiextensions.k8s.io/v1 CRD API instead of the
deprecated v1beta1
It replaces wildfly-operator 0.5.0.
Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>
=> operators wildfly (0.5.2)

operators/keycloak-operator/15.0.2/bundle.Dockerfile, operators/keycloak-operator/15.0.2/manifests/keycloak-operator.v15.0.2.clusterserviceversion.yaml, operators/keycloak-operator/15.0.2/manifests/keycloakbackups.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.2/manifests/keycloakclients.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.2/manifests/keycloakrealms.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.2/manifests/keycloaks.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.2/manifests/keycloakusers.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.2/metadata/annotations.yaml
=> Upgrade operator keycloak-operator (15.0.2)

operators/deployment-validation-operator/0.1.0/deploymentvalidationoperator.0.1.0.clusterserviceversion.yaml, operators/deployment-validation-operator/deployment-validation-operator.package.yaml
Signed-off-by: Feng Huang <fehuang@redhat.com>
=> operators deployment-validation-operator (0.1.0)

operators/cloud-native-postgresql/1.9.2/manifests/cloud-native-postgresql.clusterserviceversion.yaml, operators/cloud-native-postgresql/1.9.2/manifests/postgresql-operator-manager_v1_serviceaccount.yaml, operators/cloud-native-postgresql/1.9.2/manifests/postgresql.k8s.enterprisedb.io_backups.yaml, operators/cloud-native-postgresql/1.9.2/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml, operators/cloud-native-postgresql/1.9.2/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml, operators/cloud-native-postgresql/1.9.2/metadata/annotations.yaml
=> operators cloud-native-postgresql (1.9.2)

operators/opentelemetry-operator/0.39.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.39.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.39.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.39.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.39.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.39.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.39.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.39.0/tests/scorecard/config.yaml
This commit is based on
https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.39.0
Signed-off-by: Yuri Sa ysa@redhat.com
--
<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability …
=> operators opentelemetry-operator (0.39.0)

operators/postgresql/ci.yaml
=> operators [CI] postgresql

operators/ack-lambda-controller/0.0.8/bundle.Dockerfile, operators/ack-lambda-controller/0.0.8/manifests/ack-lambda-controller.clusterserviceversion.yaml, operators/ack-lambda-controller/0.0.8/manifests/ack-lambda-metrics-service_v1_service.yaml, operators/ack-lambda-controller/0.0.8/manifests/ack-lambda-reader_rbac.authorization.k8s.io_v1_role.yaml, operators/ack-lambda-controller/0.0.8/manifests/ack-lambda-writer_rbac.authorization.k8s.io_v1_role.yaml, operators/ack-lambda-controller/0.0.8/manifests/lambda.services.k8s.aws_aliases.yaml, operators/ack-lambda-controller/0.0.8/manifests/lambda.services.k8s.aws_codesigningconfigs.yaml, operators/ack-lambda-controller/0.0.8/manifests/lambda.services.k8s.aws_eventsourcemappings.yaml, operators/ack-lambda-controller/0.0.8/manifests/lambda.services.k8s.aws_functions.yaml, operators/ack-lambda-controller/0.0.8/metadata/annotations.yaml, operators/ack-lambda-controller/0.0.8/tests/scorecard/config.yaml
After the release of ACK [lambda-controller:v0.0.8](https://gallery.ecr.aws/aws-controllers-k8s/lambda-controller), the automation job failed to generate the PR for the OLM bundle.
So I am manually raising these PR by following the instructions mentioned in the issue [here](https://github.com/aws-controllers-k8s/community/issues/1164)
NOTE: `CreateContainerConfigError` is expected since `ACK controllers` have pre-installation steps to create resources in a cluster before the manager pod can come up.
=> operators ack-lambda-controller (0.0.8)

operators/tidb-operator/1.3.1/backups.pingcap.com.crd.yaml, operators/tidb-operator/1.3.1/backupschedules.pingcap.com.crd.yaml, operators/tidb-operator/1.3.1/dmclusters.pingcap.com.crd.yaml, operators/tidb-operator/1.3.1/restores.pingcap.com.crd.yaml, operators/tidb-operator/1.3.1/tidb-operator.v1.3.1.clusterserviceversion.yaml, operators/tidb-operator/1.3.1/tidbclusterautoscalers.pingcap.com.crd.yaml, operators/tidb-operator/1.3.1/tidbclusters.pingcap.com.crd.yaml, operators/tidb-operator/1.3.1/tidbinitializers.pingcap.com.crd.yaml, operators/tidb-operator/1.3.1/tidbmonitors.pingcap.com.crd.yaml, operators/tidb-operator/1.3.1/tidbngmonitorings.pingcap.com.crd.yaml, operators/tidb-operator/tidb-operator.package.yaml
Signed-off-by: Shiori <sihao.yu@pingcap.com>
--
=> operators tidb-operator (1.3.1)

operators/prometheus/0.47.0/prometheusoperator.0.47.0.clusterserviceversion.yaml
Signed-off-by: Zahar Pecherichny <zfrhv2010@gmail.com>
thanks to #1045 for mentioning
the operator tries to monitor all namespaces even in single namespace installation.
when the installation will be namespace scoped, the operator should work as previously.
when the operator is installed cluster scoped, he will manage all the `serviceMonitors`, `prometheusRules`... in all namespaces, and the `prometheus`, `alertmanager` instances only in his namespace.
i didnt checked the cluster scoped option yet, but the namespace scoped work as always worked before.
=> operators [O] prometheus (0.47.0)

README.md
**Description**
Update the readme with the info where the users can find the catalog
**Motivation**
Closes; https://github.com/k8s-operatorhub/community-operators/issues/382
=> doc: add source info into README

README.md
**Description**
Update the readme to make clear where the solutions should end up for those who want to publish in OKD/OCP
Closes: https://github.com/k8s-operatorhub/community-operators/issues/737
=> README: clarifies that this repository does not ship solutions on OCP

operators/windup-operator/ci.yaml
Signed-off-by: carlosthe19916 <2582866+carlosthe19916@users.noreply.github.com>
--
=> operator [CI] windup-operator

operators/trivy-operator/0.2.1/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml, operators/trivy-operator/0.2.1/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml, operators/trivy-operator/0.2.1/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml, operators/trivy-operator/0.2.1/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml, operators/trivy-operator/0.2.1/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml, operators/trivy-operator/0.2.1/trivy-operator.v0.2.1.clusterserviceversion.yaml, operators/trivy-operator/0.2.1/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml, operators/trivy-operator/trivy-operator.package.yaml
=> operator trivy-operator (0.2.1)

operators/kong/0.9.0/kong.v0.9.0.clusterserviceversion.yaml
This PR only adds a deprecation notice to kong operator (to be succeeded by https://github.com/k8s-operatorhub/community-operators/tree/main/operators/kong-gateway-operator)
=> operator [O] kong (0.9.0)

operators/dynatrace-operator/0.10.0/Dockerfile, operators/dynatrace-operator/0.10.0/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.10.0/metadata/annotations.yaml, operators/dynatrace-operator/ci.yaml
=> operator [CI] dynatrace-operator (0.10.0)

operators/hpe-csi-operator/2.4.0/Dockerfile, operators/hpe-csi-operator/2.4.0/manifests/hpe-csi-operator.v2.4.0.clusterserviceversion.yaml, operators/hpe-csi-operator/2.4.0/manifests/hpecsidrivers.storage.hpe.com.crd.yaml, operators/hpe-csi-operator/2.4.0/metadata/annotations.yaml
=> operator hpe-csi-operator (2.4.0)

operators/percona-server-mongodb-operator/1.15.0/manifests/percona-server-mongodb-operator.v1.15.0.clusterserviceversion.yaml, operators/percona-server-mongodb-operator/1.15.0/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.15.0/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.15.0/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.15.0/metadata/annotations.yaml
=> operator percona-server-mongodb-operator (1.15.0)

operators/microcks/1.8.0/manifests/microcks-operator.v1.8.0.clusterserviceversion.yaml, operators/microcks/1.8.0/manifests/microcksinstall.crd.yaml, operators/microcks/1.8.0/metadata/annotations.yaml
=> operator microcks (1.8.0)

operators/sn-operator/0.3.0-rc.5/manifests/sn-operator.clusterserviceversion.yaml
=> operator [N] sn-operator (0.3.0-rc.5)

operators/tempo-operator/0.5.0/bundle.Dockerfile, operators/tempo-operator/0.5.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator-manager-config_v1_configmap.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator-webhook-service_v1_service.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator.clusterserviceversion.yaml, operators/tempo-operator/0.5.0/manifests/tempo.grafana.com_tempostacks.yaml, operators/tempo-operator/0.5.0/metadata/annotations.yaml, operators/tempo-operator/0.5.0/tests/scorecard/config.yaml
=> operator tempo-operator (0.5.0)

operators/external-secrets-operator/ci.yaml
This PR updates the maintainers list of External Secrets Operator
WRT: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3541
=> operator [CI] external-secrets-operator

operators/skupper-operator/1.4.3/manifests/skupper-operator.v1.4.3.clusterserviceversion.yaml, operators/skupper-operator/1.4.3/metadata/annotations.yaml, operators/skupper-operator/ci.yaml
=> operator [N] [CI] skupper-operator (1.4.3)

operators/service-binding-operator/1.4.1/manifests/binding.operators.coreos.com_bindablekinds.yaml, operators/service-binding-operator/1.4.1/manifests/binding.operators.coreos.com_servicebindings.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-clusterworkloadresourcemappings-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-clusterworkloadresourcemappings-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-manager-config_v1_configmap.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-operator.clusterserviceversion.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/service-binding-operator/1.4.1/manifests/service-binding-webhook-service_v1_service.yaml, operators/service-binding-operator/1.4.1/manifests/servicebinding.io_clusterworkloadresourcemappings.yaml, operators/service-binding-operator/1.4.1/manifests/servicebinding.io_servicebindings.yaml, operators/service-binding-operator/1.4.1/metadata/annotations.yaml, operators/service-binding-operator/1.4.1/tests/scorecard/config.yaml
=> operator service-binding-operator (1.4.1)

operators/keda/2.12.0/manifests/keda.sh_clustertriggerauthentications.yaml, operators/keda/2.12.0/manifests/keda.sh_kedacontrollers.yaml, operators/keda/2.12.0/manifests/keda.sh_scaledjobs.yaml, operators/keda/2.12.0/manifests/keda.sh_scaledobjects.yaml, operators/keda/2.12.0/manifests/keda.sh_triggerauthentications.yaml, operators/keda/2.12.0/manifests/keda.v2.12.0.clusterserviceversion.yaml, operators/keda/2.12.0/metadata/annotations.yaml
=> operator keda (2.12.0)

operators/tektoncd-operator/0.68.1/manifests/config-logging_v1_configmap.yaml, operators/tektoncd-operator/0.68.1/manifests/operator.tekton.dev_tektonchains.yaml, operators/tektoncd-operator/0.68.1/manifests/operator.tekton.dev_tektonconfigs.yaml, operators/tektoncd-operator/0.68.1/manifests/operator.tekton.dev_tektondashboards.yaml, operators/tektoncd-operator/0.68.1/manifests/operator.tekton.dev_tektonhubs.yaml, operators/tektoncd-operator/0.68.1/manifests/operator.tekton.dev_tektoninstallersets.yaml, operators/tektoncd-operator/0.68.1/manifests/operator.tekton.dev_tektonpipelines.yaml, operators/tektoncd-operator/0.68.1/manifests/operator.tekton.dev_tektonresults.yaml, operators/tektoncd-operator/0.68.1/manifests/operator.tekton.dev_tektontriggers.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-config-defaults_v1_configmap.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-config-observability_v1_configmap.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-config-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-config-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_role.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-operator-info_v1_configmap.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-operator-webhook-certs_v1_secret.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-operator-webhook_v1_service.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-operator_v1_service.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-result-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/tektoncd-operator/0.68.1/manifests/tekton-result-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/tektoncd-operator/0.68.1/manifests/tektoncd-operator.clusterserviceversion.yaml, operators/tektoncd-operator/0.68.1/metadata/annotations.yaml, operators/tektoncd-operator/0.68.1/tests/scorecard/config.yaml
=> operator tektoncd-operator (0.68.1)

operators/lbconfig-operator/0.4.1/manifests/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml, operators/lbconfig-operator/0.4.1/manifests/lbconfig-operator-controller-manager-metrics-service_v1_service.yaml, operators/lbconfig-operator/0.4.1/manifests/lbconfig-operator-manager-config_v1_configmap.yaml, operators/lbconfig-operator/0.4.1/manifests/lbconfig-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/lbconfig-operator/0.4.1/manifests/lbconfig-operator.clusterserviceversion.yaml, operators/lbconfig-operator/0.4.1/metadata/annotations.yaml, operators/lbconfig-operator/0.4.1/tests/scorecard/config.yaml, operators/lbconfig-operator/0.4.1/tests/scorecard/kuttl/create-externalloadbalancer/01-assert.yaml, operators/lbconfig-operator/0.4.1/tests/scorecard/kuttl/create-externalloadbalancer/10-create-elb.yaml, operators/lbconfig-operator/0.4.1/tests/scorecard/kuttl/create-externalloadbalancer/11-assert.yaml, operators/lbconfig-operator/0.4.1/tests/scorecard/kuttl/kuttl-test.yaml
=> operator lbconfig-operator (0.4.1)

operators/nri-plugins-operator/0.3.2/manifests/config.nri_balloonspolicies.yaml, operators/nri-plugins-operator/0.3.2/manifests/config.nri_nriplugindeployments.yaml, operators/nri-plugins-operator/0.3.2/manifests/config.nri_templatepolicies.yaml, operators/nri-plugins-operator/0.3.2/manifests/config.nri_topologyawarepolicies.yaml, operators/nri-plugins-operator/0.3.2/manifests/nri-plugins-operator-controller-manager-metrics-service_v1_service.yaml, operators/nri-plugins-operator/0.3.2/manifests/nri-plugins-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/nri-plugins-operator/0.3.2/manifests/nri-plugins-operator.clusterserviceversion.yaml, operators/nri-plugins-operator/0.3.2/manifests/topology.node.k8s.io_noderesourcetopologies.yaml, operators/nri-plugins-operator/0.3.2/metadata/annotations.yaml, operators/nri-plugins-operator/0.3.2/tests/scorecard/config.yaml, operators/nri-plugins-operator/ci.yaml
Submit nri-plugins-operator (0.3.2) initial version.
=> operator [N] [CI] nri-plugins-operator (0.3.2)

.github/workflows/stale_issues.yaml
To address #3641 this PR modifies the stale issue workflow to never close issues. This configuration might not be ideal for maintainers but I didn't want to impose any changes without more feedback.
I believe the stale bot is a very important part of maintaining this repository. One alternative configuration I might suggest is only allowing the stale bot to close issues or mark them as stale after they have been triaged by a maintainer. This could be achieved using the only-labels or exempt-labels options in the workflow. 
For only-labels a maintainer would have to add a `needs-information` type label. If a user doesn't respond in 30 days when this label is active then the issue would be stale. This pattern is similar to one I've seen in Mozilla Firefox issue tracker. This setup favors …
=> 3641: made stale issues never close

operators/kubensync/0.3.1/bundle.Dockerfile, operators/kubensync/0.3.1/manifests/automation.kubensync.com_managedresources.yaml, operators/kubensync/0.3.1/manifests/kubensync-controller-manager-metrics-service_v1_service.yaml, operators/kubensync/0.3.1/manifests/kubensync-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kubensync/0.3.1/manifests/kubensync.clusterserviceversion.yaml, operators/kubensync/0.3.1/metadata/annotations.yaml, operators/kubensync/0.3.1/tests/scorecard/config.yaml
=> operator kubensync (0.3.1)

operators/cluster-aas-operator/0.1.5/manifests/argo_cd_cluser_rb.yaml, operators/cluster-aas-operator/0.1.5/manifests/argo_cd_cluster_role.yaml, operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml, operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator-repo-bridge.yaml, operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator-webhook-service_v1_service.yaml, operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator.clusterserviceversion.yaml, operators/cluster-aas-operator/0.1.5/manifests/cluster_templates_user_ct_role.yaml, operators/cluster-aas-operator/0.1.5/manifests/cluster_templates_user_role.yaml, operators/cluster-aas-operator/0.1.5/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml, operators/cluster-aas-operator/0.1.5/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml, operators/cluster-aas-operator/0.1.5/manifests/clustertemplate.openshift.io_clustertemplates.yaml, operators/cluster-aas-operator/0.1.5/manifests/clustertemplate.openshift.io_clustertemplatesetup.yaml, operators/cluster-aas-operator/0.1.5/manifests/clustertemplate.openshift.io_config.yaml, operators/cluster-aas-operator/0.1.5/metadata/annotations.yaml, operators/cluster-aas-operator/0.1.5/metadata/dependencies.yaml, operators/cluster-aas-operator/0.1.5/tests/scorecard/config.yaml
=> operator cluster-aas-operator (0.1.5)

operators/intel-device-plugins-operator/0.30.0/bundle.Dockerfile, operators/intel-device-plugins-operator/0.30.0/manifests/deviceplugin.intel.com_dlbdeviceplugins.yaml, operators/intel-device-plugins-operator/0.30.0/manifests/deviceplugin.intel.com_dsadeviceplugins.yaml, operators/intel-device-plugins-operator/0.30.0/manifests/deviceplugin.intel.com_fpgadeviceplugins.yaml, operators/intel-device-plugins-operator/0.30.0/manifests/deviceplugin.intel.com_gpudeviceplugins.yaml, operators/intel-device-plugins-operator/0.30.0/manifests/deviceplugin.intel.com_iaadeviceplugins.yaml, operators/intel-device-plugins-operator/0.30.0/manifests/deviceplugin.intel.com_qatdeviceplugins.yaml, operators/intel-device-plugins-operator/0.30.0/manifests/deviceplugin.intel.com_sgxdeviceplugins.yaml, operators/intel-device-plugins-operator/0.30.0/manifests/fpga.intel.com_acceleratorfunctions.yaml, operators/intel-device-plugins-operator/0.30.0/manifests/fpga.intel.com_fpgaregions.yaml, operators/intel-device-plugins-operator/0.30.0/manifests/intel-device-plugins-operator.clusterserviceversion.yaml, operators/intel-device-plugins-operator/0.30.0/metadata/annotations.yaml, operators/intel-device-plugins-operator/0.30.0/tests/scorecard/config.yaml
=> operator intel-device-plugins-operator (0.30.0)

operators/tempo-operator/0.12.0/bundle.Dockerfile, operators/tempo-operator/0.12.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml, operators/tempo-operator/0.12.0/manifests/tempo-operator-manager-config_v1_configmap.yaml, operators/tempo-operator/0.12.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/tempo-operator/0.12.0/manifests/tempo-operator-webhook-service_v1_service.yaml, operators/tempo-operator/0.12.0/manifests/tempo-operator.clusterserviceversion.yaml, operators/tempo-operator/0.12.0/manifests/tempo.grafana.com_tempomonolithics.yaml, operators/tempo-operator/0.12.0/manifests/tempo.grafana.com_tempostacks.yaml, operators/tempo-operator/0.12.0/metadata/annotations.yaml, operators/tempo-operator/0.12.0/tests/scorecard/config.yaml
Release tempo-operator `0.12.0`.
=> operator tempo-operator (0.12.0)

operators/registry-operator/0.3.0/bundle.Dockerfile, operators/registry-operator/0.3.0/manifests/registry-operator-controller-manager-metrics-service_v1_service.yaml, operators/registry-operator/0.3.0/manifests/registry-operator-manager-config_v1_configmap.yaml, operators/registry-operator/0.3.0/manifests/registry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/registry-operator/0.3.0/manifests/registry-operator-webhook-service_v1_service.yaml, operators/registry-operator/0.3.0/manifests/registry-operator.clusterserviceversion.yaml, operators/registry-operator/0.3.0/manifests/registry.devfile.io_clusterdevfileregistrieslists.yaml, operators/registry-operator/0.3.0/manifests/registry.devfile.io_devfileregistries.yaml, operators/registry-operator/0.3.0/manifests/registry.devfile.io_devfileregistrieslists.yaml, operators/registry-operator/0.3.0/metadata/annotations.yaml, operators/registry-operator/0.3.0/tests/scorecard/config.yaml
* [ x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
-- …
=> operator registry-operator (0.3.0)

operators/bpfman-operator/0.5.2/bundle.Dockerfile, operators/bpfman-operator/0.5.2/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-config_v1_configmap.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-daemon_v1_serviceaccount.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-operator.clusterserviceversion.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman.io_bpfapplications.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman.io_bpfprograms.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman.io_fentryprograms.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman.io_fexitprograms.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman.io_kprobeprograms.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman.io_tcprograms.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman.io_tracepointprograms.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman.io_uprobeprograms.yaml, operators/bpfman-operator/0.5.2/manifests/bpfman.io_xdpprograms.yaml, operators/bpfman-operator/0.5.2/metadata/annotations.yaml, operators/bpfman-operator/0.5.2/metadata/dependencies.yaml, operators/bpfman-operator/0.5.2/tests/scorecard/config.yaml
The bpfman-operator v0.5.2 release is a patch release that adds support for
ppc64le and s390x, and contains several minor internal updates.
--
<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability …
=> operator bpfman-operator (0.5.2)

operators/knative-operator/1.16.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/knative-operator/1.16.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/knative-operator/1.16.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/knative-operator/1.16.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/knative-operator/1.16.0/manifests/knative-operator-config-logging_v1_configmap.yaml, operators/knative-operator/1.16.0/manifests/knative-operator-config-observability_v1_configmap.yaml, operators/knative-operator/1.16.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml, operators/knative-operator/1.16.0/manifests/knative-operator-operator-webhook_v1_service.yaml, operators/knative-operator/1.16.0/manifests/knative-operator.v1.16.0.clusterserviceversion.yaml, operators/knative-operator/1.16.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/knative-operator/1.16.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/knative-operator/1.16.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/knative-operator/1.16.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/knative-operator/1.16.0/manifests/knativeeventings.operator.knative.dev.crd.yaml, operators/knative-operator/1.16.0/manifests/knativeservings.operator.knative.dev.crd.yaml, operators/knative-operator/1.16.0/metadata/annotations.yaml, operators/knative-operator/1.16.0/tests/scorecard/config.yaml
=> operator knative-operator (1.16.0)

operators/datasance-pot-operator/3.4.7/manifests/datasance-iofog-operator.clusterserviceversion.yaml, operators/datasance-pot-operator/3.4.7/manifests/datasance-pot-operator_clusterrole.yaml, operators/datasance-pot-operator/3.4.7/manifests/datasance-pot-operator_role.yaml, operators/datasance-pot-operator/3.4.7/manifests/datasance-pot-operator_rolebinding.yaml, operators/datasance-pot-operator/3.4.7/manifests/datasance.com-controlplanes_crd.yaml, operators/datasance-pot-operator/3.4.7/metadata/annotations.yaml, operators/datasance-pot-operator/ci.yaml
=> operator [N] [CI] datasance-pot-operator (3.4.7)

operators/victoriametrics-operator/0.49.1/manifests/victoriametrics-operator.clusterserviceversion.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vlogs.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmscrapeconfigs.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.50.0/manifests/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.50.0/manifests/victoriametrics-operator.clusterserviceversion.yaml, operators/victoriametrics-operator/0.50.0/manifests/vm-operator-metrics-service_v1_service.yaml, operators/victoriametrics-operator/0.50.0/manifests/vm-webhook-service_v1_service.yaml, operators/victoriametrics-operator/0.50.0/metadata/annotations.yaml, operators/victoriametrics-operator/0.50.0/tests/scorecard/config.yaml
victoriametrics-operator 0.50.0
=> operator [R] victoriametrics-operator (0.49.1 0.50.0)

operators/ibm-security-verify-access-operator/24.12.0/manifests/ibm-security-verify-access-operator.clusterserviceversion.yaml, operators/ibm-security-verify-access-operator/24.12.0/manifests/ibm.com_ibmsecurityverifyaccesses.yaml, operators/ibm-security-verify-access-operator/24.12.0/manifests/verify-access-operator-controller-manager-metrics-service_v1_service.yaml, operators/ibm-security-verify-access-operator/24.12.0/manifests/verify-access-operator-controller-manager-snapshot-service_v1_service.yaml, operators/ibm-security-verify-access-operator/24.12.0/manifests/verify-access-operator-manager-config_v1_configmap.yaml, operators/ibm-security-verify-access-operator/24.12.0/manifests/verify-access-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ibm-security-verify-access-operator/24.12.0/metadata/annotations.yaml, operators/ibm-security-verify-access-operator/24.12.0/tests/scorecard/config.yaml
=> operator ibm-security-verify-access-operator (24.12.0)

operators/kube-green/0.7.0/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml, operators/kube-green/0.7.0/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kube-green/0.7.0/manifests/kube-green-webhook-service_v1_service.yaml, operators/kube-green/0.7.0/manifests/kube-green.clusterserviceversion.yaml, operators/kube-green/0.7.0/manifests/kube-green.com_sleepinfos.yaml, operators/kube-green/0.7.0/metadata/annotations.yaml, operators/kube-green/0.7.0/tests/scorecard/config.yaml
=> operator kube-green (0.7.0)

operators/apicurio-registry-3/3.0.7/bundle.Dockerfile, operators/apicurio-registry-3/3.0.7/manifests/apicurio-registry-3.clusterserviceversion.yaml, operators/apicurio-registry-3/3.0.7/manifests/registry.apicur.io_apicurioregistries3.yaml, operators/apicurio-registry-3/3.0.7/metadata/annotations.yaml, operators/apicurio-registry-3/ci.yaml
=> operator [N] [CI] apicurio-registry-3 (3.0.7)

operators/strimzi-kafka-operator/0.46.0/manifests/strimzi-cluster-operator.v0.46.0.clusterserviceversion.yaml
This PR fixes a missing "get" permission within the CSV of the Strimzi operator 0.46.0
=> operator [O] strimzi-kafka-operator (0.46.0)

.github/workflows/command_merge.yaml, .github/workflows/operator_ci.yaml, .github/workflows/operator_test.yaml
=> fix(ISV-6142) Fix broken links created by automation.
