k8s-operatorhub/community-operators

- operators/strimzi-kafka-operator/0.20.0/strimzi-cluster-operator.v0.20.0.clusterserviceversion.yaml
- operators/strimzi-kafka-operator/ci.yaml
> operators [O] [CI] strimzi-kafka-operator (0.20.0)

- operators/strimzi-kafka-operator/0.20.1/strimzi-cluster-operator.v0.20.1.clusterserviceversion.yaml
- operators/strimzi-kafka-operator/ci.yaml
> operators [CI] strimzi-kafka-operator (0.20.1)

- operators/aqua/6.2.0/aqua-operator.v6.2.0.clusterserviceversion.yaml
Signed-off-by: Martin Vala <mavala@redhat.com>
> Aqua cosmetics

- operators/aqua/6.2.0/aqua-operator.v6.2.0.clusterserviceversion.yaml
Signed-off-by: Martin Vala <mavala@redhat.com>
> Rever aqua

- operators/pulp-operator/0.3.0/bundle.Dockerfile
- operators/pulp-operator/0.3.0/manifests/pulp-operator.v0.3.0.clusterserviceversion.yaml
- operators/pulp-operator/0.3.0/manifests/pulp.pulpproject.org_pulpbackups_crd.yaml
- operators/pulp-operator/0.3.0/manifests/pulp.pulpproject.org_pulprestores_crd.yaml
- operators/pulp-operator/0.3.0/manifests/pulp.pulpproject.org_pulps_crd.yaml
- operators/pulp-operator/0.3.0/metadata/annotations.yaml
- operators/pulp-operator/ci.yaml
https://pulpproject.org/
https://pulp-operator.readthedocs.io/en/latest/
--
> operators [N] [CI] pulp-operator (0.3.0)

- operators/snapscheduler/ci.yaml
> Set reviewers for snapscheduler

- operators/mongodb-enterprise/1.12.0/bundle.Dockerfile
- operators/mongodb-enterprise/1.12.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.12.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.12.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.12.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.12.0/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.12.0/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.12.0/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.12.0/metadata/annotations.yaml
- operators/mongodb-enterprise/1.12.0/tests/scorecard/config.yaml
- operators/mongodb-enterprise/ci.yaml
Signed-off-by: Ciprian Tibulca ciprian.tibulca@mongodb.com
--
> operators [CI] mongodb-enterprise (1.12.0)

- operators/kiali/1.37.0/bundle.Dockerfile
- operators/kiali/1.37.0/manifests/kiali.crd.yaml
- operators/kiali/1.37.0/manifests/kiali.v1.37.0.clusterserviceversion.yaml
- operators/kiali/1.37.0/metadata/annotations.yaml
> operators kiali (1.37.0)

- .github/workflows/operator_release.yaml
Trigger ohio on the new location
> trigger ohio new location

- operators/pmem-csi-operator/1.0.0/bundle.Dockerfile
- operators/pmem-csi-operator/1.0.0/manifests/pmem-csi-operator-metrics_v1_service.yaml
- operators/pmem-csi-operator/1.0.0/manifests/pmem-csi-operator.clusterserviceversion.yaml
- operators/pmem-csi-operator/1.0.0/manifests/pmem-csi-operator_v1_serviceaccount.yaml
- operators/pmem-csi-operator/1.0.0/manifests/pmem-csi.intel.com_pmemcsideployments.yaml
- operators/pmem-csi-operator/1.0.0/metadata/annotations.yaml
Signed-off-by: Amarnath Valluri <amarnath.valluri@intel.com>
* [c] Human readable name and 1-liner description about your Operator
* [c] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [c] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup> …
> operators pmem-csi-operator (1.0.0)

- operators/service-binding-operator/0.9.0/manifests/binding.operators.coreos.com_servicebindings.yaml
- operators/service-binding-operator/0.9.0/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.9.0/manifests/service-binding-manager-config_v1_configmap.yaml
- operators/service-binding-operator/0.9.0/manifests/service-binding-operator.clusterserviceversion.yaml
- operators/service-binding-operator/0.9.0/manifests/service-binding-operator_v1_serviceaccount.yaml
- operators/service-binding-operator/0.9.0/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.9.0/manifests/service-binding-webhook-service_v1_service.yaml
- operators/service-binding-operator/0.9.0/manifests/service.binding_servicebindings.yaml
- operators/service-binding-operator/0.9.0/metadata/annotations.yaml
> operators service-binding-operator (0.9.0)

- operators/klusterlet/0.4.0/klusterlet.v0.4.0.clusterserviceversion.yaml
- operators/klusterlet/0.4.0/operator.open-cluster-management.io_klusterlets.yaml
- operators/klusterlet/ci.yaml
- operators/klusterlet/klusterlet.package.yaml
> operators [CI] klusterlet (0.4.0)

- operators/cluster-manager/0.4.0/cluster-manager.v0.4.0.clusterserviceversion.yaml
- operators/cluster-manager/0.4.0/operator.open-cluster-management.io_clustermanagers.yaml
- operators/cluster-manager/ci.yaml
- operators/cluster-manager/cluster-manger.package.yaml
> operators [CI] cluster-manager (0.4.0)

- operators/grafana-operator/3.10.3/grafana-operator.v3.10.3.clusterserviceversion.yaml
- operators/grafana-operator/3.10.3/grafanadashboards.integreatly.org.crd.yaml
- operators/grafana-operator/3.10.3/grafanadatasources.integreatly.org.crd.yaml
- operators/grafana-operator/3.10.3/grafanas.integreatly.org.crd.yaml
- operators/grafana-operator/grafana-operator.package.yaml
Signed-off-by: Peter Braun pbraun@redhat.com
> operators grafana-operator (3.10.3)

- operators/metallb-operator/0.1.0/manifests/metallb-operator.clusterserviceversion.yaml
- operators/metallb-operator/0.1.0/manifests/metallb.io_metallbs.yaml
Syncing with changes done in https://github.com/metallb/metallb-operator/
> operators [N] metallb-operator (0.1.0)

- operators/dynatrace-operator/0.1.0/Dockerfile
- operators/dynatrace-operator/0.1.0/metadata/annotations.yaml
- operators/dynatrace-operator/0.2.1/Dockerfile
- operators/dynatrace-operator/0.2.1/manifests/dynatrace-operator.v0.2.1.clusterserviceversion.yaml
- operators/dynatrace-operator/0.2.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.2.1/metadata/annotations.yaml
- operators/dynatrace-operator/ci.yaml
Signed-off-by: Marco Mader <marco.mader@dynatrace.com>
> operators [R] [CI] dynatrace-operator (0.1.0 0.2.1)

- operators/eclipse-che/7.33.2/checlusters.org.eclipse.che.crd.yaml
- operators/eclipse-che/7.33.2/eclipse-che.v7.33.2.clusterserviceversion.yaml
- operators/eclipse-che/7.33.2/org.eclipse.che_chebackupserverconfigurations_crd.yaml
- operators/eclipse-che/7.33.2/org.eclipse.che_checlusterbackups_crd.yaml
- operators/eclipse-che/7.33.2/org.eclipse.che_checlusterrestores_crd.yaml
- operators/eclipse-che/eclipse-che.package.yaml
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
--
> operators eclipse-che (7.33.2)

- operators/mongodb-enterprise/1.11.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.11.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.12.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.12.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
Signed-off-by: Ciprian Tibulca <ciprian.tibulca@mongodb.com>
--
> operators [R] mongodb-enterprise (1.11.0 1.12.0)

- operators/kubernetes-nmstate-operator/0.47.0/kubernetes-nmstate-operator.v0.47.0.clusterserviceversion.yaml
- operators/kubernetes-nmstate-operator/0.47.0/nmstate-operator_v1_serviceaccount.yaml
- operators/kubernetes-nmstate-operator/0.47.0/nmstate.io_nmstates.yaml
- operators/kubernetes-nmstate-operator/kubernetes-nmstate-operator.package.yaml
- update version to 0.47.0
- change maintainer to rhrazdil@redhat.com
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>
* [ x ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ x ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ x ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ x ] Is your …
> operators kubernetes-nmstate-operator (0.47.0)

- operators/service-binding-operator/0.9.1/manifests/binding.operators.coreos.com_servicebindings.yaml
- operators/service-binding-operator/0.9.1/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.9.1/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/0.9.1/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.9.1/manifests/service-binding-manager-config_v1_configmap.yaml
- operators/service-binding-operator/0.9.1/manifests/service-binding-operator.clusterserviceversion.yaml
- operators/service-binding-operator/0.9.1/manifests/service-binding-operator_v1_serviceaccount.yaml
- operators/service-binding-operator/0.9.1/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.9.1/manifests/service-binding-webhook-service_v1_service.yaml
- operators/service-binding-operator/0.9.1/manifests/service.binding_servicebindings.yaml
- operators/service-binding-operator/0.9.1/metadata/annotations.yaml
> operators service-binding-operator (0.9.1)

- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.17.1/victoriametrics-operator.0.17.1.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.17.1/vm-operator-vm-operator-psp-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/victoriametrics-operator/0.17.1/vm-operator-vm-operator-psp-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/victoriametrics-operator/0.17.1/vm-operator-vm-operator_v1_serviceaccount.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.17.1)

- operators/openebs/2.10.0/openebs_v1alpha1_openebsinstalltemplate_crd.yaml
- operators/openebs/2.10.0/openebsoperator.v2.10.0.clusterserviceversion.yaml
- operators/openebs/openebs.package.yaml
Signed Off by Aamir Shaikh <aameer.shaikh@mayadata.io>
--
> operators openebs (2.10.0)

- operators/tf-operator/0.0.1-2011/Dockerfile
- operators/tf-operator/0.0.1-2011/manifests/tf-operator.v0.0.1-2011.clusterserviceversion.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_analyticsalarm_crd.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_analyticssnmp_crd.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_cassandras_crd.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_configs_crd.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_controls_crd.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_kubemanagers_crd.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_managers_crd.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_rabbitmqs_crd.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_vrouters_crd.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_webuis_crd.yaml
- operators/tf-operator/0.0.1-2011/manifests/tf.tungsten.io_zookeepers_crd.yaml
- operators/tf-operator/0.0.1-2011/metadata/annotations.yaml
- operators/tf-operator/ci.yaml
- operators/tf-operator/tf-operator.package.yaml
Signed-off-by: Ivan Timofeev <ivanv.timofeev@gmail.com>
* [ +] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ +] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ +] Have you tested your Operator with all Custom Resource Definitions?
* [ +] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ +] Have you considered whether …
> operators [N] [CI] tf-operator (0.0.1-2011)

- operators/cloud-native-postgresql/1.7.0/bundle.Dockerfile
- operators/cloud-native-postgresql/1.7.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.7.0/manifests/postgresql-operator-manager_v1_serviceaccount.yaml
- operators/cloud-native-postgresql/1.7.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.7.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.7.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.7.0/metadata/annotations.yaml
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>
> operators cloud-native-postgresql (1.7.0)

- README.md
> documentation default path

- operators/tf-operator/1.0.0/Dockerfile
- operators/tf-operator/1.0.0/manifests/tf-operator.v1.0.0.clusterserviceversion.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_analytics_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_analyticsalarm_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_analyticssnmp_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_cassandras_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_configs_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_controls_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_kubemanagers_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_managers_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_queryengine_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_rabbitmqs_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_redis_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_vrouters_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_webuis_crd.yaml
- operators/tf-operator/1.0.0/manifests/tf.tungsten.io_zookeepers_crd.yaml
- operators/tf-operator/1.0.0/metadata/annotations.yaml
Signed-off-by: Ivan Timofeev <ivanv.timofeev@gmail.com>
* [ +] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [+ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ +] Have you tested an update to your Operator when deployed via OLM?
* [ +] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [+] Modify more …
> operators [R] tf-operator (0.0.1-2011 1.0.0)

- operators/infinispan/2.1.5/infinispan-operator.v2.1.5.clusterserviceversion.yaml
- operators/infinispan/2.1.5/infinispan.org_backups_crd.yaml
- operators/infinispan/2.1.5/infinispan.org_batches_crd.yaml
- operators/infinispan/2.1.5/infinispan.org_caches_crd.yaml
- operators/infinispan/2.1.5/infinispan.org_infinispans_crd.yaml
- operators/infinispan/2.1.5/infinispan.org_restores_crd.yaml
- operators/infinispan/ci.yaml
- operators/infinispan/infinispan.package.yaml
Signed-off-by: Vittorio Rigamonti <vrigamon@redhat.com>
--
> operators [CI] infinispan (2.1.5)

- operators/portworx/1.5.0/core_v1_storagecluster_crd.yaml
- operators/portworx/1.5.0/core_v1_storagenode_crd.yaml
- operators/portworx/1.5.0/portworxoperator.v1.5.0.clusterserviceversion.yaml
- operators/portworx/portworx.package.yaml
> operators portworx (1.5.0)

- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.17.2/victoriametrics-operator.0.17.2.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.17.2/vm-operator-vm-operator-psp-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/victoriametrics-operator/0.17.2/vm-operator-vm-operator-psp-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/victoriametrics-operator/0.17.2/vm-operator-vm-operator_v1_serviceaccount.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.17.2)

- operators/tektoncd-operator/0.24.1-1/bundle.Dockerfile
- operators/tektoncd-operator/0.24.1-1/manifests/config-logging_v1_configmap.yaml
- operators/tektoncd-operator/0.24.1-1/manifests/operator.tekton.dev_tektonconfigs.yaml
- operators/tektoncd-operator/0.24.1-1/manifests/operator.tekton.dev_tektondashboards.yaml
- operators/tektoncd-operator/0.24.1-1/manifests/operator.tekton.dev_tektonpipelines.yaml
- operators/tektoncd-operator/0.24.1-1/manifests/operator.tekton.dev_tektontriggers.yaml
- operators/tektoncd-operator/0.24.1-1/manifests/tekton-config-defaults_v1_configmap.yaml
- operators/tektoncd-operator/0.24.1-1/manifests/tekton-operator_v1_serviceaccount.yaml
- operators/tektoncd-operator/0.24.1-1/manifests/tektoncd-operator.clusterserviceversion.yaml
- operators/tektoncd-operator/0.24.1-1/metadata/annotations.yaml
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>
--
> operators tektoncd-operator (0.24.1-1)

- operators/synapse-helm/0.0.1/bundle.Dockerfile
- operators/synapse-helm/0.0.1/manifests/opdev.io_synapses_crd.yaml
- operators/synapse-helm/0.0.1/manifests/synapse-helm.v0.0.1.clusterserviceversion.yaml
- operators/synapse-helm/0.0.1/metadata/annotations.yaml
- operators/synapse-helm/0.0.1/tests/scorecard/config.yaml
- operators/synapse-helm/ci.yaml
Signed-off-by: mgoerens <mgoerens@redhat.com>
--
> operators [N] [CI] synapse-helm (0.0.1)

- operators/snapscheduler/2.0.0/bundle.Dockerfile
- operators/snapscheduler/2.0.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml
- operators/snapscheduler/2.0.0/manifests/snapscheduler-controller-manager_v1_serviceaccount.yaml
- operators/snapscheduler/2.0.0/manifests/snapscheduler-manager-config_v1_configmap.yaml
- operators/snapscheduler/2.0.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/snapscheduler/2.0.0/manifests/snapscheduler.backube_snapshotschedules.yaml
- operators/snapscheduler/2.0.0/manifests/snapscheduler.clusterserviceversion.yaml
- operators/snapscheduler/2.0.0/metadata/annotations.yaml
- operators/snapscheduler/2.0.0/tests/scorecard/config.yaml
- operators/snapscheduler/ci.yaml
> operators [CI] snapscheduler (2.0.0)

- operators/pcc-operator/0.0.1/manifests/consoledefenders.pcc.paloaltonetworks.com.crd.yaml
- operators/pcc-operator/0.0.1/manifests/consoles.pcc.paloaltonetworks.com.crd.yaml
- operators/pcc-operator/0.0.1/manifests/defenders.pcc.paloaltonetworks.com.crd.yaml
- operators/pcc-operator/0.0.1/manifests/pcc-operator-controller-manager-metrics-service.service.yaml
- operators/pcc-operator/0.0.1/manifests/pcc-operator-controller-manager.serviceaccount.yaml
- operators/pcc-operator/0.0.1/manifests/pcc-operator-metrics-reader_rbac.authorization.k8s.io.clusterrole.yaml
- operators/pcc-operator/0.0.1/manifests/pcc-operator.v0.0.1.clusterserviceversion.yaml
- operators/pcc-operator/0.0.1/metadata/annotations.yaml
- operators/pcc-operator/0.0.1/tests/scorecard/config.yaml
- operators/pcc-operator/bundle.Dockerfile
Signed-off-by: Wyatt Gill <wgill@paloaltonetworks.com>
--
> operators [N] pcc-operator (0.0.1)

- operators/tagger/2.1.17/Containerfile
- operators/tagger/2.1.17/manifests/docker-webhooks_v1_service.yaml
- operators/tagger/2.1.17/manifests/metrics_v1_service.yaml
- operators/tagger/2.1.17/manifests/mirror-registry-config_v1_secret.yaml
- operators/tagger/2.1.17/manifests/mutating-webhooks_v1_service.yaml
- operators/tagger/2.1.17/manifests/quay-webhooks_v1_service.yaml
- operators/tagger/2.1.17/manifests/tagger.clusterserviceversion.yaml
- operators/tagger/2.1.17/manifests/tagger.dev_tags.yaml
- operators/tagger/2.1.17/manifests/tagger_v1_serviceaccount.yaml
- operators/tagger/2.1.17/manifests/tagio-external_v1_service.yaml
- operators/tagger/2.1.17/manifests/tagio_v1_service.yaml
- operators/tagger/2.1.17/metadata/annotations.yaml
- operators/tagger/ci.yaml
Signed-off-by: Ricardo Maraschini <rmarasch@redhat.com>
--
> operators [N] [CI] tagger (2.1.17)

- operators/portworx-essentials/ci.yaml
> operators [CI] portworx-essentials

- operators/portworx/ci.yaml
> operators [CI] portworx

- operators/elastic-cloud-eck/1.7.0/agents.agent.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.0/apmservers.apm.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.0/beats.beat.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.0/elastic-cloud-eck.v1.7.0.clusterserviceversion.yaml
- operators/elastic-cloud-eck/1.7.0/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.0/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.0/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.0/kibanas.kibana.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml
Signed-off-by: Idan Moyal <idan.moyal@elastic.co>
--
> operators elastic-cloud-eck (1.7.0)

- operators/starboard-operator/0.11.0/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.11.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.11.0/starboard-operator.v0.11.0.clusterserviceversion.yaml
- operators/starboard-operator/0.11.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.11.0)

- operators/keda/2.4.0/manifests/keda-olm-operator_v1_serviceaccount.yaml
- operators/keda/2.4.0/manifests/keda.sh_clustertriggerauthentications.yaml
- operators/keda/2.4.0/manifests/keda.sh_kedacontrollers.yaml
- operators/keda/2.4.0/manifests/keda.sh_scaledjobs.yaml
- operators/keda/2.4.0/manifests/keda.sh_scaledobjects.yaml
- operators/keda/2.4.0/manifests/keda.sh_triggerauthentications.yaml
- operators/keda/2.4.0/manifests/keda.v2.4.0.clusterserviceversion.yaml
- operators/keda/2.4.0/metadata/annotations.yaml
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
--
> operators keda (2.4.0)

- operators/flux/0.16.2/manifests/alert.crd.yaml
- operators/flux/0.16.2/manifests/bucket.crd.yaml
- operators/flux/0.16.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.16.2/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.16.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.16.2/manifests/flux.v0.16.2.clusterserviceversion.yaml
- operators/flux/0.16.2/manifests/gitrepository.crd.yaml
- operators/flux/0.16.2/manifests/helm-controller.serviceaccount.yaml
- operators/flux/0.16.2/manifests/helmchart.crd.yaml
- operators/flux/0.16.2/manifests/helmrelease.crd.yaml
- operators/flux/0.16.2/manifests/helmrepository.crd.yaml
- operators/flux/0.16.2/manifests/image-automation-controller.serviceaccount.yaml
- operators/flux/0.16.2/manifests/image-reflector-controller.serviceaccount.yaml
- operators/flux/0.16.2/manifests/imagepolicy.crd.yaml
- operators/flux/0.16.2/manifests/imagerepository.crd.yaml
- operators/flux/0.16.2/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.16.2/manifests/kustomization.crd.yaml
- operators/flux/0.16.2/manifests/kustomize-controller.serviceaccount.yaml
- operators/flux/0.16.2/manifests/notification-controller.service.yaml
- operators/flux/0.16.2/manifests/notification-controller.serviceaccount.yaml
- operators/flux/0.16.2/manifests/provider.crd.yaml
- operators/flux/0.16.2/manifests/receiver.crd.yaml
- operators/flux/0.16.2/manifests/source-controller.service.yaml
- operators/flux/0.16.2/manifests/source-controller.serviceaccount.yaml
- operators/flux/0.16.2/manifests/webhook-receiver.service.yaml
- operators/flux/0.16.2/metadata/annotations.yaml
> operators flux (0.16.2)

- operators/clickhouse/0.15.0/clickhouse-operator.v0.15.0.clusterserviceversion.yaml
- operators/clickhouse/0.15.0/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.15.0/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.15.0/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/clickhouse.package.yaml
> operators clickhouse (0.15.0)

- operators/hazelcast-enterprise-operator/0.3.7/hazelcast-enterprise-operator.v0.3.7.clusterserviceversion.yaml
- operators/hazelcast-enterprise-operator/0.3.7/hazelcastenterprises.hazelcast.com.crd.yaml
- operators/hazelcast-enterprise-operator/hazelcast-enterprise-operator.package.yaml
Signed-off-by: devOpsHelm <devopshelm@hazelcast.com>
> operators hazelcast-enterprise-operator (0.3.7)

- operators/hazelcast-operator/0.3.7/hazelcast-operator.v0.3.7.clusterserviceversion.yaml
- operators/hazelcast-operator/0.3.7/hazelcasts.hazelcast.com.crd.yaml
- operators/hazelcast-operator/hazelcast-operator.package.yaml
Signed-off-by: devOpsHelm <devopshelm@hazelcast.com>
> operators hazelcast-operator (0.3.7)

- operators/mongodb-atlas-kubernetes/0.4.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/0.6.1/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/0.6.1/manifests/atlas.mongodb.com_atlasclusters.yaml
- operators/mongodb-atlas-kubernetes/0.6.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/0.6.1/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/0.6.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/0.6.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/0.6.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/0.6.1/manifests/mongodb-atlas-operator_v1_serviceaccount.yaml
- operators/mongodb-atlas-kubernetes/0.6.1/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/0.6.1/tests/scorecard/config.yaml
Signed-off-by: fabritsius <anton_fabritsius@epam.com>
--
> operators [R] mongodb-atlas-kubernetes (0.4.0 0.5.0 0.6.1)

- operators/kubernetes-imagepuller-operator/0.0.8/che.eclipse.org_kubernetesimagepullers_crd.yaml
- operators/kubernetes-imagepuller-operator/0.0.8/kubernetes-imagepuller-operator.v0.0.8.clusterserviceversion.yaml
- operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
--
> operators kubernetes-imagepuller-operator (0.0.8)

- operators/keycloak-operator/15.0.0/bundle.Dockerfile
- operators/keycloak-operator/15.0.0/manifests/keycloak-operator.v15.0.0.clusterserviceversion.yaml
- operators/keycloak-operator/15.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml
- operators/keycloak-operator/15.0.0/manifests/keycloakclients.keycloak.org.crd.yaml
- operators/keycloak-operator/15.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml
- operators/keycloak-operator/15.0.0/manifests/keycloaks.keycloak.org.crd.yaml
- operators/keycloak-operator/15.0.0/manifests/keycloakusers.keycloak.org.crd.yaml
- operators/keycloak-operator/15.0.0/metadata/annotations.yaml
Signed-off-by: Václav Muzikář <vmuzikar@redhat.com>
--
> operators keycloak-operator (15.0.0)

- operators/kiali/1.38.1/bundle.Dockerfile
- operators/kiali/1.38.1/manifests/kiali.crd.yaml
- operators/kiali/1.38.1/manifests/kiali.v1.38.1.clusterserviceversion.yaml
- operators/kiali/1.38.1/metadata/annotations.yaml
> operators kiali (1.38.1)

- operators/skydive-operator/0.0.49/bundle.Dockerfile
- operators/skydive-operator/0.0.50/bundle.Dockerfile
- operators/skydive-operator/0.0.50/manifests/skydive-group.example.com_skydives.yaml
- operators/skydive-operator/0.0.50/manifests/skydive-operator-controller-manager-metrics-service_v1_service.yaml
- operators/skydive-operator/0.0.50/manifests/skydive-operator-controller-manager_v1_serviceaccount.yaml
- operators/skydive-operator/0.0.50/manifests/skydive-operator-manager-config_v1_configmap.yaml
- operators/skydive-operator/0.0.50/manifests/skydive-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/skydive-operator/0.0.50/manifests/skydive-operator.clusterserviceversion.yaml
- operators/skydive-operator/0.0.50/metadata/annotations.yaml
- operators/skydive-operator/0.0.50/tests/scorecard/config.yaml
- operators/skydive-operator/skydive-operator.package.yaml
Signed-off-by: oran-nahoum <saintoran@gmail.com>
--
> operators [R] skydive-operator (0.0.50)

- operators/machine-deletion-operator/0.0.1/manifests/machine-deletion-controller-manager-metrics-service_v1_service.yaml
- operators/machine-deletion-operator/0.0.1/manifests/machine-deletion-controller-manager_v1_serviceaccount.yaml
- operators/machine-deletion-operator/0.0.1/manifests/machine-deletion-machine-deletion-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/machine-deletion-operator/0.0.1/manifests/machine-deletion-manager-config_v1_configmap.yaml
- operators/machine-deletion-operator/0.0.1/manifests/machine-deletion-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/machine-deletion-operator/0.0.1/manifests/machine-deletion.clusterserviceversion.yaml
- operators/machine-deletion-operator/0.0.1/manifests/machine-deletion.medik8s.io_machinedeletions.yaml
- operators/machine-deletion-operator/0.0.1/manifests/machine-deletion.medik8s.io_machinedeletiontemplates.yaml
- operators/machine-deletion-operator/0.0.1/metadata/annotations.yaml
Signed-off-by: Michael Shitrit <mshitrit@redhat.com>
--
> operators [N] machine-deletion-operator (0.0.1)

- operators/keycloak-operator/15.0.1/bundle.Dockerfile
- operators/keycloak-operator/15.0.1/manifests/keycloak-operator.v15.0.1.clusterserviceversion.yaml
- operators/keycloak-operator/15.0.1/manifests/keycloakbackups.keycloak.org.crd.yaml
- operators/keycloak-operator/15.0.1/manifests/keycloakclients.keycloak.org.crd.yaml
- operators/keycloak-operator/15.0.1/manifests/keycloakrealms.keycloak.org.crd.yaml
- operators/keycloak-operator/15.0.1/manifests/keycloaks.keycloak.org.crd.yaml
- operators/keycloak-operator/15.0.1/manifests/keycloakusers.keycloak.org.crd.yaml
- operators/keycloak-operator/15.0.1/metadata/annotations.yaml
Signed-off-by: Václav Muzikář <vmuzikar@redhat.com>
--
> operators keycloak-operator (15.0.1)

- operators/tektoncd-operator/0.49.0/bundle.Dockerfile
- operators/tektoncd-operator/0.49.0/manifests/config-logging_v1_configmap.yaml
- operators/tektoncd-operator/0.49.0/manifests/operator.tekton.dev_tektonconfigs.yaml
- operators/tektoncd-operator/0.49.0/manifests/operator.tekton.dev_tektondashboards.yaml
- operators/tektoncd-operator/0.49.0/manifests/operator.tekton.dev_tektonpipelines.yaml
- operators/tektoncd-operator/0.49.0/manifests/operator.tekton.dev_tektonresults.yaml
- operators/tektoncd-operator/0.49.0/manifests/operator.tekton.dev_tektontriggers.yaml
- operators/tektoncd-operator/0.49.0/manifests/tekton-config-defaults_v1_configmap.yaml
- operators/tektoncd-operator/0.49.0/manifests/tekton-operator-webhook-certs_v1_secret.yaml
- operators/tektoncd-operator/0.49.0/manifests/tekton-operator-webhook_v1_service.yaml
- operators/tektoncd-operator/0.49.0/manifests/tekton-operator_v1_serviceaccount.yaml
- operators/tektoncd-operator/0.49.0/manifests/tektoncd-operator.clusterserviceversion.yaml
- operators/tektoncd-operator/0.49.0/metadata/annotations.yaml
Add tektoncd-operator v0.49.0 bundle
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>
* [] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
-- …
> operators tektoncd-operator (0.49.0)

- operators/sematext/1.0.33/sematext-operator.v1.0.33.clusterserviceversion.yaml
- operators/sematext/1.0.33/sematextagents.sematext.com.crd.yaml
- operators/sematext/sematext.package.yaml
> operators sematext (1.0.33)

- operators/dynatrace-operator/0.2.2/Dockerfile
- operators/dynatrace-operator/0.2.2/manifests/dynatrace-operator.v0.2.2.clusterserviceversion.yaml
- operators/dynatrace-operator/0.2.2/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.2.2/metadata/annotations.yaml
Signed-off-by: Marco Mader <marco.mader@dynatrace.com>
> operators dynatrace-operator (0.2.2)

- operators/cloud-native-postgresql/1.7.1/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.7.1/manifests/postgresql-operator-manager_v1_serviceaccount.yaml
- operators/cloud-native-postgresql/1.7.1/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.7.1/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.7.1/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.7.1/metadata/annotations.yaml
> operators cloud-native-postgresql (1.7.1)

- operators/cluster-impairment-operator/1.0.0/manifests/apps.redhat.com_clusterimpairments.yaml
- operators/cluster-impairment-operator/1.0.0/manifests/cluster-impairment-operator-controller-manager-metrics-service_v1_service.yaml
- operators/cluster-impairment-operator/1.0.0/manifests/cluster-impairment-operator-manager-config_v1_configmap.yaml
- operators/cluster-impairment-operator/1.0.0/manifests/cluster-impairment-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/cluster-impairment-operator/1.0.0/manifests/cluster-impairment-operator.clusterserviceversion.yaml
- operators/cluster-impairment-operator/1.0.0/manifests/network-access-sa_v1_serviceaccount.yaml
- operators/cluster-impairment-operator/1.0.0/metadata/annotations.yaml
- operators/cluster-impairment-operator/1.0.0/tests/scorecard/config.yaml
- operators/cluster-impairment-operator/ci.yaml
Signed-off-by: Jared O'Connell <joconnel@redhat.com>
--
> operators [N] [CI] cluster-impairment-operator (1.0.0)

- operators/submariner/0.10.1/submariner-gateway_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/submariner/0.10.1/submariner-gateway_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/submariner/0.10.1/submariner-gateway_rbac.authorization.k8s.io_v1_role.yaml
- operators/submariner/0.10.1/submariner-gateway_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/submariner/0.10.1/submariner-gateway_v1_serviceaccount.yaml
- operators/submariner/0.10.1/submariner-globalnet_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/submariner/0.10.1/submariner-globalnet_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/submariner/0.10.1/submariner-globalnet_rbac.authorization.k8s.io_v1_role.yaml
- operators/submariner/0.10.1/submariner-globalnet_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/submariner/0.10.1/submariner-globalnet_v1_serviceaccount.yaml
- operators/submariner/0.10.1/submariner-lighthouse-agent_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/submariner/0.10.1/submariner-lighthouse-agent_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/submariner/0.10.1/submariner-lighthouse-agent_v1_serviceaccount.yaml
- operators/submariner/0.10.1/submariner-lighthouse-coredns_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/submariner/0.10.1/submariner-lighthouse-coredns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/submariner/0.10.1/submariner-lighthouse-coredns_v1_serviceaccount.yaml
- operators/submariner/0.10.1/submariner-networkplugin-syncer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/submariner/0.10.1/submariner-networkplugin-syncer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/submariner/0.10.1/submariner-networkplugin-syncer_v1_serviceaccount.yaml
- operators/submariner/0.10.1/submariner-operator_v1_serviceaccount.yaml
- operators/submariner/0.10.1/submariner-routeagent_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/submariner/0.10.1/submariner-routeagent_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/submariner/0.10.1/submariner-routeagent_rbac.authorization.k8s.io_v1_role.yaml
- operators/submariner/0.10.1/submariner-routeagent_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/submariner/0.10.1/submariner-routeagent_v1_serviceaccount.yaml
- operators/submariner/0.10.1/submariner.io_brokers.yaml
- operators/submariner/0.10.1/submariner.io_submariners.yaml
- operators/submariner/0.10.1/submariner.v0.10.1.clusterserviceversion.yaml
- operators/submariner/submariner.package.yaml
> operators submariner (0.10.1)

- operators/qserv-operator/2021.8.1-rc2/manifests/qserv-operator-controller-manager-metrics-service_v1_service.yaml
- operators/qserv-operator/2021.8.1-rc2/manifests/qserv-operator-controller-manager_v1_serviceaccount.yaml
- operators/qserv-operator/2021.8.1-rc2/manifests/qserv-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/qserv-operator/2021.8.1-rc2/manifests/qserv-operator.clusterserviceversion.yaml
- operators/qserv-operator/2021.8.1-rc2/manifests/qserv.lsst.org_qservs.yaml
- operators/qserv-operator/2021.8.1-rc2/metadata/annotations.yaml
- operators/qserv-operator/2021.8.1-rc2/tests/scorecard/config.yaml
Signed-off-by: Fabrice Jammes <fabrice.jammes@in2p3.fr>
--
> operators qserv-operator (2021.8.1-rc2)

- operators/intel-device-plugins-operator/0.21.0/intel-device-plugins-operator.clusterserviceversion.yaml
this is a minor cosmetic change, so no version update is done
> operators [O] intel-device-plugins-operator (0.21.0)

- operators/opentelemetry-operator/0.33.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.33.0/manifests/opentelemetry-operator-controller-manager_v1_serviceaccount.yaml
- operators/opentelemetry-operator/0.33.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.33.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.33.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.33.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.33.0/metadata/annotations.yaml
Signed-off-by: Owais Lone <owais@lone.pw>
--
> operators opentelemetry-operator (0.33.0)

- operators/kiali/1.39.0/bundle.Dockerfile
- operators/kiali/1.39.0/manifests/kiali.crd.yaml
- operators/kiali/1.39.0/manifests/kiali.v1.39.0.clusterserviceversion.yaml
- operators/kiali/1.39.0/metadata/annotations.yaml
> operators kiali (1.39.0)

- operators/grafana-operator/4.0.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml
- operators/grafana-operator/4.0.0/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/4.0.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/4.0.0/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/4.0.0/integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/4.0.0/integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/4.0.0/integreatly.org_grafanas.yaml
- operators/grafana-operator/grafana-operator.package.yaml
> operators grafana-operator (4.0.0)

- operators/elastic-cloud-eck/1.7.1/agents.agent.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.1/apmservers.apm.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.1/beats.beat.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.1/elastic-cloud-eck.v1.7.1.clusterserviceversion.yaml
- operators/elastic-cloud-eck/1.7.1/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.1/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.1/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.7.1/kibanas.kibana.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml
Signed-off-by: Michael Morello <michael.morello@elastic.co>
--
> operators elastic-cloud-eck (1.7.1)

- operators/hive-operator/ci.yaml
Sync with current team members.
> operators [CI] hive-operator

- operators/qserv-operator/2021.8.1-rc3/manifests/qserv-operator-controller-manager-metrics-service_v1_service.yaml
- operators/qserv-operator/2021.8.1-rc3/manifests/qserv-operator-controller-manager_v1_serviceaccount.yaml
- operators/qserv-operator/2021.8.1-rc3/manifests/qserv-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/qserv-operator/2021.8.1-rc3/manifests/qserv-operator.clusterserviceversion.yaml
- operators/qserv-operator/2021.8.1-rc3/manifests/qserv.lsst.org_qservs.yaml
- operators/qserv-operator/2021.8.1-rc3/metadata/annotations.yaml
- operators/qserv-operator/2021.8.1-rc3/tests/scorecard/config.yaml
Signed-off-by: Fabrice Jammes <fabrice.jammes@in2p3.fr>
--
> operators qserv-operator (2021.8.1-rc3)

- operators/submariner/submariner.package.yaml
Signed-off-by: Steve Mattar <smattar@redhat.com>
--
> operators [PK] submariner ()

- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.18.0/victoriametrics-operator.0.18.0.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.18.0/vm-operator-vm-operator-psp-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/victoriametrics-operator/0.18.0/vm-operator-vm-operator-psp-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/victoriametrics-operator/0.18.0/vm-operator-vm-operator_v1_serviceaccount.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.18.0)

- operators/ibmcloud-operator/ci.yaml
Add myself and my teammates for approved reviews on our operator.
For reference, here's a previous release PR we merged in the old repos:
* https://github.com/operator-framework/community-operators/pull/2379
* https://github.com/operator-framework/community-operators/pull/2398
Signed-off-by: John Starich <johnstarich@johnstarich.com>
--
<sup>1</sup> If you feel your Operator does not fit any …
> operators [CI] ibmcloud-operator

- operators/ibmcloud-operator/1.0.10/apiextensions.k8s.io_v1beta1_customresourcedefinition_bindings.ibmcloud.ibm.com.yaml
- operators/ibmcloud-operator/1.0.10/apiextensions.k8s.io_v1beta1_customresourcedefinition_services.ibmcloud.ibm.com.yaml
- operators/ibmcloud-operator/1.0.10/ibmcloud_operator.v1.0.10.clusterserviceversion.yaml
- operators/ibmcloud-operator/ibmcloud-operator.package.yaml
Automated release of IBM Cloud Operator v1.0.10.
> operators ibmcloud-operator (1.0.10)

- operators/camel-k/1.5.1/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.5.1/camel-k.v1.5.1.clusterserviceversion.yaml
- operators/camel-k/1.5.1/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.5.1/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.5.1/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.5.1/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.5.1/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.5.1/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/camel-k.package.yaml
Signed-off-by: nicolaferraro <ni.ferraro@gmail.com>
--
> operators camel-k (1.5.1)

- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.18.1/victoriametrics-operator.0.18.1.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.18.1/vm-operator-vm-operator-psp-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/victoriametrics-operator/0.18.1/vm-operator-vm-operator-psp-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/victoriametrics-operator/0.18.1/vm-operator-vm-operator_v1_serviceaccount.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.18.1)

- operators/kubernetes-imagepuller-operator/0.0.9/che.eclipse.org_kubernetesimagepullers_crd.yaml
- operators/kubernetes-imagepuller-operator/0.0.9/kubernetes-imagepuller-operator.v0.0.9.clusterserviceversion.yaml
- operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
--
> operators kubernetes-imagepuller-operator (0.0.9)

- operators/noobaa-operator/5.8.0/backingstores.noobaa.io.crd.yaml
- operators/noobaa-operator/5.8.0/bucketclasses.noobaa.io.crd.yaml
- operators/noobaa-operator/5.8.0/namespacestores.noobaa.io.crd.yaml
- operators/noobaa-operator/5.8.0/noobaa-operator.v5.8.0.clusterserviceversion.yaml
- operators/noobaa-operator/5.8.0/noobaas.noobaa.io.crd.yaml
- operators/noobaa-operator/noobaa-operator.package.yaml
Signed-off-by: Kfir Payne <kfirpayne@gmail.com>
--
> operators noobaa-operator (5.8.0)

- operators/ibmcloud-operator/1.0.11/apiextensions.k8s.io_v1beta1_customresourcedefinition_bindings.ibmcloud.ibm.com.yaml
- operators/ibmcloud-operator/1.0.11/apiextensions.k8s.io_v1beta1_customresourcedefinition_services.ibmcloud.ibm.com.yaml
- operators/ibmcloud-operator/1.0.11/ibmcloud_operator.v1.0.11.clusterserviceversion.yaml
- operators/ibmcloud-operator/ibmcloud-operator.package.yaml
Automated release of IBM Cloud Operator v1.0.11.
> operators ibmcloud-operator (1.0.11)

- operators/redis-operator/0.8.0/manifests/redis-operator.v0.8.0.clusterserviceversion.yaml
- operators/redis-operator/0.8.0/manifests/redis.redis.redis.opstreelabs.in.crd.yaml
- operators/redis-operator/0.8.0/manifests/redisclusters.redis.redis.opstreelabs.in.crd.yaml
- operators/redis-operator/0.8.0/metadata/annotations.yaml
* [ X] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ X] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?
--
<sup>1</sup> If you feel …
> operators redis-operator (0.8.0)

- operators/ibm-spectrum-scale-csi-operator/2.3.0/csiscaleoperators.csi.ibm.com.crd.yaml
- operators/ibm-spectrum-scale-csi-operator/2.3.0/ibm-spectrum-scale-csi-operator.v2.3.0.clusterserviceversion.yaml
- operators/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
> operators ibm-spectrum-scale-csi-operator (2.3.0)

- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.18.2/victoriametrics-operator.0.18.2.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.18.2/vm-operator-vm-operator-psp-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/victoriametrics-operator/0.18.2/vm-operator-vm-operator-psp-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/victoriametrics-operator/0.18.2/vm-operator-vm-operator_v1_serviceaccount.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.18.2)

- operators/datatrucker-operator/1.3.1/bundle.Dockerfile
- operators/datatrucker-operator/1.3.1/manifests/datatrucker-operator-controller-manager-metrics-service_v1_service.yaml
- operators/datatrucker-operator/1.3.1/manifests/datatrucker-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/datatrucker-operator/1.3.1/manifests/datatrucker-operator.clusterserviceversion.yaml
- operators/datatrucker-operator/1.3.1/manifests/datatrucker.datatrucker.io_datatruckerconfigs.yaml
- operators/datatrucker-operator/1.3.1/manifests/datatrucker.datatrucker.io_datatruckerflows.yaml
- operators/datatrucker-operator/1.3.1/metadata/annotations.yaml
- operators/datatrucker-operator/1.3.1/tests/scorecard/config.yaml
Signed-off-by: Gaurav Shankar <gauravshankar.can@gmail.com>
* [ yes ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [yes ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [yes ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [yes ] Have you tested an update to your Operator when deployed via OLM?
* [ …
> operators datatrucker-operator (1.3.1)

- operators/camel-k/1.6.0/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.6.0/camel-k.v1.6.0.clusterserviceversion.yaml
- operators/camel-k/1.6.0/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.6.0/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.6.0/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.6.0/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.6.0/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.6.0/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/camel-k.package.yaml
Signed-off-by: nicolaferraro <ni.ferraro@gmail.com>
--
> operators camel-k (1.6.0)

- operators/snyk-operator/ci.yaml
Signed-off-by: Ivan Stanev <istanev93@gmail.com>
--
> operators [CI] snyk-operator

- operators/snyk-operator/1.66.6/snyk-operator.v1.66.6.clusterserviceversion.yaml
- operators/snyk-operator/1.66.6/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.66.6)

- operators/portworx/1.5.1/core_v1_storagecluster_crd.yaml
- operators/portworx/1.5.1/core_v1_storagenode_crd.yaml
- operators/portworx/1.5.1/portworxoperator.v1.5.1.clusterserviceversion.yaml
- operators/portworx/portworx.package.yaml
> operators portworx (1.5.1)

- operators/aws-auth-operator/0.1.0/manifests/auth.ops42.org_awsauthsyncconfigs.crd.yaml
- operators/aws-auth-operator/0.1.0/manifests/aws-auth-operator.v0.1.0.clusterserviceversion.yaml
- operators/aws-auth-operator/0.1.0/metadata/annotations.yaml
- operators/aws-auth-operator/ci.yaml
Signed-off-by: Gennady Potapov <gennadiy.potapov@gmail.com>
---
Initial contribution of AWS Auth Operator to operator hub.
> operators [N] [CI] aws-auth-operator (0.1.0)

- operators/hazelcast-jet-operator/0.6.0/hazelcast-jet-operator.v0.6.0.clusterserviceversion.yaml
- operators/hazelcast-jet-operator/0.6.0/hazelcastjets.hazelcast.com.crd.yaml
- operators/hazelcast-jet-operator/hazelcast-jet-operator.package.yaml
Signed-off-by: Ondrej Lukas <ondrej@hazelcast.com>
--
> operators hazelcast-jet-operator (0.6.0)

- operators/hazelcast-jet-enterprise-operator/0.6.0/hazelcast-jet-enterprise-operator.v0.6.0.clusterserviceversion.yaml
- operators/hazelcast-jet-enterprise-operator/0.6.0/hazelcastjetenterprises.hazelcast.com.crd.yaml
- operators/hazelcast-jet-enterprise-operator/hazelcast-jet-enterprise-operator.package.yaml
Signed-off-by: Ondrej Lukas <ondrej@hazelcast.com>
--
> operators hazelcast-jet-enterprise-operator (0.6.0)

- operators/atlasmap-operator/0.4.0/atlasmap-operator.clusterserviceversion.yaml
- operators/atlasmap-operator/0.4.0/atlasmap.io_atlasmaps.yaml
- operators/atlasmap-operator/0.4.1/atlasmap-operator.clusterserviceversion.yaml
- operators/atlasmap-operator/0.4.1/atlasmap.io_atlasmaps.yaml
- operators/atlasmap-operator/atlasmap-operator.package.yaml
Signed-off-by: Tomohisa Igarashi <tm.igarashi@gmail.com>
--
> operators [R] atlasmap-operator (0.4.0 0.4.1)

- operators/qserv-operator/2021.9.1-rc1/manifests/qserv-operator-controller-manager-metrics-service_v1_service.yaml
- operators/qserv-operator/2021.9.1-rc1/manifests/qserv-operator-controller-manager_v1_serviceaccount.yaml
- operators/qserv-operator/2021.9.1-rc1/manifests/qserv-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/qserv-operator/2021.9.1-rc1/manifests/qserv-operator.clusterserviceversion.yaml
- operators/qserv-operator/2021.9.1-rc1/manifests/qserv.lsst.org_qservs.yaml
- operators/qserv-operator/2021.9.1-rc1/metadata/annotations.yaml
- operators/qserv-operator/2021.9.1-rc1/tests/scorecard/config.yaml
Signed-off-by: Fabrice Jammes <fabrice.jammes@in2p3.fr>
--
> operators qserv-operator (2021.9.1-rc1)

- operators/cloud-native-postgresql/1.8.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.8.0/manifests/postgresql-operator-manager_v1_serviceaccount.yaml
- operators/cloud-native-postgresql/1.8.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.8.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.8.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.8.0/metadata/annotations.yaml
> operators cloud-native-postgresql (1.8.0)

- operators/service-binding-operator/0.10.0/manifests/binding.operators.coreos.com_servicebindings.yaml
- operators/service-binding-operator/0.10.0/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.10.0/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/0.10.0/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.10.0/manifests/service-binding-manager-config_v1_configmap.yaml
- operators/service-binding-operator/0.10.0/manifests/service-binding-operator.clusterserviceversion.yaml
- operators/service-binding-operator/0.10.0/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.10.0/manifests/service-binding-webhook-service_v1_service.yaml
- operators/service-binding-operator/0.10.0/manifests/service.binding_servicebindings.yaml
- operators/service-binding-operator/0.10.0/metadata/annotations.yaml
> operators service-binding-operator (0.10.0)

- operators/knative-operator/0.25.2/knative-operator.v0.25.2.clusterserviceversion.yaml
- operators/knative-operator/0.25.2/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/0.25.2/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/knative-operator.package.yaml
> operators knative-operator (0.25.2)

- operators/flux/0.17.1/manifests/alert.crd.yaml
- operators/flux/0.17.1/manifests/bucket.crd.yaml
- operators/flux/0.17.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.17.1/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.17.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.17.1/manifests/flux.v0.17.1.clusterserviceversion.yaml
- operators/flux/0.17.1/manifests/gitrepository.crd.yaml
- operators/flux/0.17.1/manifests/helm-controller.serviceaccount.yaml
- operators/flux/0.17.1/manifests/helmchart.crd.yaml
- operators/flux/0.17.1/manifests/helmrelease.crd.yaml
- operators/flux/0.17.1/manifests/helmrepository.crd.yaml
- operators/flux/0.17.1/manifests/image-automation-controller.serviceaccount.yaml
- operators/flux/0.17.1/manifests/image-reflector-controller.serviceaccount.yaml
- operators/flux/0.17.1/manifests/imagepolicy.crd.yaml
- operators/flux/0.17.1/manifests/imagerepository.crd.yaml
- operators/flux/0.17.1/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.17.1/manifests/kustomization.crd.yaml
- operators/flux/0.17.1/manifests/kustomize-controller.serviceaccount.yaml
- operators/flux/0.17.1/manifests/notification-controller.service.yaml
- operators/flux/0.17.1/manifests/notification-controller.serviceaccount.yaml
- operators/flux/0.17.1/manifests/provider.crd.yaml
- operators/flux/0.17.1/manifests/receiver.crd.yaml
- operators/flux/0.17.1/manifests/source-controller.service.yaml
- operators/flux/0.17.1/manifests/source-controller.serviceaccount.yaml
- operators/flux/0.17.1/manifests/webhook-receiver.service.yaml
- operators/flux/0.17.1/metadata/annotations.yaml
> operators flux (0.17.1)

- operators/universal-crossplane/1.3.1-up.1/manifests/universal-crossplane.1.3.1-up.1.clusterserviceversion.yaml
We accidentally left these in the `ClusterServiceVersion` and it [broke](https://github.com/upbound/universal-crossplane/issues/172#issuecomment-920148777) some users. This PR reverts security contexts back to their original value in the earlier releases.
--
<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your …
> operators [O] universal-crossplane (1.3.1-up.1)

- operators/starboard-operator/0.12.0/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.12.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.12.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.12.0/starboard-operator.v0.12.0.clusterserviceversion.yaml
- operators/starboard-operator/0.12.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.12.0)

- operators/portworx/1.5.2/core_v1_storagecluster_crd.yaml
- operators/portworx/1.5.2/core_v1_storagenode_crd.yaml
- operators/portworx/1.5.2/portworxoperator.v1.5.2.clusterserviceversion.yaml
- operators/portworx/portworx.package.yaml
> operators portworx (1.5.2)

- operators/kiali/1.40.1/bundle.Dockerfile
- operators/kiali/1.40.1/manifests/kiali.crd.yaml
- operators/kiali/1.40.1/manifests/kiali.v1.40.1.clusterserviceversion.yaml
- operators/kiali/1.40.1/metadata/annotations.yaml
> operators kiali (1.40.1)

- operators/cluster-impairment-operator/1.0.4/manifests/apps.redhat.com_clusterimpairments.yaml
- operators/cluster-impairment-operator/1.0.4/manifests/cluster-impairment-operator-controller-manager-metrics-service_v1_service.yaml
- operators/cluster-impairment-operator/1.0.4/manifests/cluster-impairment-operator-manager-config_v1_configmap.yaml
- operators/cluster-impairment-operator/1.0.4/manifests/cluster-impairment-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/cluster-impairment-operator/1.0.4/manifests/cluster-impairment-operator.clusterserviceversion.yaml
- operators/cluster-impairment-operator/1.0.4/manifests/network-access-sa_v1_serviceaccount.yaml
- operators/cluster-impairment-operator/1.0.4/metadata/annotations.yaml
- operators/cluster-impairment-operator/1.0.4/tests/scorecard/config.yaml
Signed-off-by: Jared O'Connell <joconnel@redhat.com>
--
> operators cluster-impairment-operator (1.0.4)

- operators/pcc-operator/0.1.1/bundle.Dockerfile
- operators/pcc-operator/0.1.1/manifests/consoledefenders.pcc.paloaltonetworks.com.crd.yaml
- operators/pcc-operator/0.1.1/manifests/consoles.pcc.paloaltonetworks.com.crd.yaml
- operators/pcc-operator/0.1.1/manifests/defenders.pcc.paloaltonetworks.com.crd.yaml
- operators/pcc-operator/0.1.1/manifests/pcc-operator.v0.1.1.clusterserviceversion.yaml
- operators/pcc-operator/0.1.1/metadata/annotations.yaml
- operators/pcc-operator/0.1.1/tests/scorecard/config.yaml
Signed-off-by: Wyatt Gill <wgill@paloaltonetworks.com>
--
> operators pcc-operator (0.1.1)

- operators/elastic-cloud-eck/1.8.0/agents.agent.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.8.0/apmservers.apm.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.8.0/beats.beat.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.8.0/elastic-cloud-eck.v1.8.0.clusterserviceversion.yaml
- operators/elastic-cloud-eck/1.8.0/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.8.0/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.8.0/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.8.0/kibanas.kibana.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml
Signed-off-by: Sebastien Guilloux sebastien.guilloux@elastic.co
--
> operators elastic-cloud-eck (1.8.0)

- operators/flux/0.17.2/manifests/alert.crd.yaml
- operators/flux/0.17.2/manifests/bucket.crd.yaml
- operators/flux/0.17.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.17.2/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.17.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.17.2/manifests/flux.v0.17.2.clusterserviceversion.yaml
- operators/flux/0.17.2/manifests/gitrepository.crd.yaml
- operators/flux/0.17.2/manifests/helm-controller.serviceaccount.yaml
- operators/flux/0.17.2/manifests/helmchart.crd.yaml
- operators/flux/0.17.2/manifests/helmrelease.crd.yaml
- operators/flux/0.17.2/manifests/helmrepository.crd.yaml
- operators/flux/0.17.2/manifests/image-automation-controller.serviceaccount.yaml
- operators/flux/0.17.2/manifests/image-reflector-controller.serviceaccount.yaml
- operators/flux/0.17.2/manifests/imagepolicy.crd.yaml
- operators/flux/0.17.2/manifests/imagerepository.crd.yaml
- operators/flux/0.17.2/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.17.2/manifests/kustomization.crd.yaml
- operators/flux/0.17.2/manifests/kustomize-controller.serviceaccount.yaml
- operators/flux/0.17.2/manifests/notification-controller.service.yaml
- operators/flux/0.17.2/manifests/notification-controller.serviceaccount.yaml
- operators/flux/0.17.2/manifests/provider.crd.yaml
- operators/flux/0.17.2/manifests/receiver.crd.yaml
- operators/flux/0.17.2/manifests/source-controller.service.yaml
- operators/flux/0.17.2/manifests/source-controller.serviceaccount.yaml
- operators/flux/0.17.2/manifests/webhook-receiver.service.yaml
- operators/flux/0.17.2/metadata/annotations.yaml
> operators flux (0.17.2)

- operators/openshift-qiskit-operator/0.2.1/openshift-qiskit-operator.v0.2.1.clusterserviceversion.yaml
- operators/openshift-qiskit-operator/0.2.1/qiskit.ibm.com_qiskitplaygrounds.yaml
- operators/openshift-qiskit-operator/ci.yaml
- operators/openshift-qiskit-operator/openshift-qiskit-operator.package.yaml
Signed-off-by: Oleg Silkin <16809287+osilkin98@users.noreply.github.com>
This PR removes the `"pvc": "claim-admin"` line from the example spec, which requires a `claim-admin` PVC to be manually deployed else the Deployment will fail to launch. 
-- …
> operators [CI] openshift-qiskit-operator (0.2.1)

- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.19.0/victoriametrics-operator.0.19.0.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.19.0/vm-operator-vm-operator_v1_serviceaccount.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.19.0)

- operators/knative-operator/0.26.1/knative-operator.v0.26.1.clusterserviceversion.yaml
- operators/knative-operator/0.26.1/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/0.26.1/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/knative-operator.package.yaml
> operators knative-operator (0.26.1)

- operators/openshift-qiskit-operator/0.2.1/openshift-qiskit-operator.v0.2.1.clusterserviceversion.yaml
> operators [O] openshift-qiskit-operator (0.2.1)

- operators/service-binding-operator/0.11.0/manifests/binding.operators.coreos.com_bindablekinds.yaml
- operators/service-binding-operator/0.11.0/manifests/binding.operators.coreos.com_servicebindings.yaml
- operators/service-binding-operator/0.11.0/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.11.0/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/0.11.0/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.11.0/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/0.11.0/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.11.0/manifests/service-binding-manager-config_v1_configmap.yaml
- operators/service-binding-operator/0.11.0/manifests/service-binding-operator.clusterserviceversion.yaml
- operators/service-binding-operator/0.11.0/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/0.11.0/manifests/service-binding-webhook-service_v1_service.yaml
- operators/service-binding-operator/0.11.0/manifests/servicebinding.io_servicebindings.yaml
- operators/service-binding-operator/0.11.0/metadata/annotations.yaml
> operators service-binding-operator (0.11.0)

- operators/dell-csi-operator/1.5.0/csiisilons.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.5.0/csipowermaxes.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.5.0/csipowermaxrevproxies.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.5.0/csipowerstores.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.5.0/csiunities.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.5.0/csivxflexoses.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.5.0/dell-csi-operator.v1.5.0.clusterserviceversion.yaml
- operators/dell-csi-operator/dell-csi-operator.package.yaml
> operators dell-csi-operator (1.5.0)

- operators/service-binding-operator/0.11.0/manifests/service-binding-operator.clusterserviceversion.yaml
> operators [O] service-binding-operator (0.11.0)

- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.19.1/victoriametrics-operator.0.19.1.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.19.1/vm-operator-vm-operator_v1_serviceaccount.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.19.1)

- operators/cloud-native-postgresql/1.9.1/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.9.1/manifests/postgresql-operator-manager_v1_serviceaccount.yaml
- operators/cloud-native-postgresql/1.9.1/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.9.1/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.9.1/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.9.1/metadata/annotations.yaml
> operators cloud-native-postgresql (1.9.1)

- operators/nfs-provisioner-operator/0.0.3/Dockerfile
- operators/nfs-provisioner-operator/0.0.3/manifests/cache.jhouse.com_nfsprovisioners.yaml
- operators/nfs-provisioner-operator/0.0.3/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml
- operators/nfs-provisioner-operator/0.0.3/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/nfs-provisioner-operator/0.0.3/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
- operators/nfs-provisioner-operator/0.0.3/manifests/nfs-provisioner-operator.clusterserviceversion.yaml
- operators/nfs-provisioner-operator/0.0.3/metadata/annotations.yaml
- operators/nfs-provisioner-operator/0.0.3/tests/scorecard/config.yaml
- operators/nfs-provisioner-operator/ci.yaml
Signed-off-by: Jooho Lee <ljhiyh@gmail.com>
* [V] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [V] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [V] Have you tested your Operator with all Custom Resource Definitions?
* [V] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [V] Have you considered whether you want use …
> operators [N] [CI] nfs-provisioner-operator (0.0.3)

- operators/kiali/1.41.0/bundle.Dockerfile
- operators/kiali/1.41.0/manifests/kiali.crd.yaml
- operators/kiali/1.41.0/manifests/kiali.v1.41.0.clusterserviceversion.yaml
- operators/kiali/1.41.0/metadata/annotations.yaml
> operators kiali (1.41.0)

- operators/microcks/1.4.1/microcks-operator.v1.4.1.clusterserviceversion.yaml
- operators/microcks/1.4.1/microcksinstall.crd.yaml
- operators/microcks/microcks.package.yaml
> operators microcks (1.4.1)

- operators/ibm-application-gateway-operator/21.9.0/ibm-application-gateway-operator.v21.9.0.clusterserviceversion.yaml
- operators/ibm-application-gateway-operator/21.9.0/ibmapplicationgateways.ibm.com.crd.yaml
- operators/ibm-application-gateway-operator/ibm-application-gateway-operator.package.yaml
Updated the IBM Application Gateway operator Signed-off-by: Keiran Robinson <krobinson@au1.ibm.com>
--
> operators ibm-application-gateway-operator (21.9.0)

- operators/snyk-operator/1.68.0/snyk-operator.v1.68.0.clusterserviceversion.yaml
- operators/snyk-operator/1.68.0/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/ci.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators [CI] snyk-operator (1.68.0)

- operators/deployment-validation-operator/0.1.1/deploymentvalidationoperator.0.1.1.clusterserviceversion.yaml
- operators/deployment-validation-operator/deployment-validation-operator.package.yaml
Signed-off-by: Feng Huang <fehuang@redhat.com>
> operators deployment-validation-operator (0.1.1)

- operators/hazelcast-operator/0.3.8/hazelcast-operator.v0.3.8.clusterserviceversion.yaml
- operators/hazelcast-operator/0.3.8/hazelcasts.hazelcast.com.crd.yaml
- operators/hazelcast-operator/hazelcast-operator.package.yaml
Signed-off-by: devOpsHelm <devopshelm@hazelcast.com>
> operators hazelcast-operator (0.3.8)

- operators/beegfs-csi-driver-operator/1.2.0/ci.yaml
- operators/beegfs-csi-driver-operator/1.2.0/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml
- operators/beegfs-csi-driver-operator/1.2.0/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml
- operators/beegfs-csi-driver-operator/1.2.0/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/beegfs-csi-driver-operator/1.2.0/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml
- operators/beegfs-csi-driver-operator/1.2.0/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml
- operators/beegfs-csi-driver-operator/1.2.0/metadata/annotations.yaml
- operators/beegfs-csi-driver-operator/1.2.0/tests/scorecard/config.yaml
Signed-off-by: Eric Weber <eric.weber2@netapp.com>
--
> operators [N] [CI] beegfs-csi-driver-operator (1.2.0)

- operators/integrity-shield-operator/0.1.3/tests/scorecard/config.yaml
- operators/integrity-shield-operator/0.1.4/tests/scorecard/config.yaml
- operators/integrity-shield-operator/0.1.5/tests/scorecard/config.yaml
- operators/integrity-shield-operator/0.1.6/tests/scorecard/config.yaml
- operators/integrity-shield-operator/0.3.0/manifests/apis.integrityshield.io_integrityshields.yaml
- operators/integrity-shield-operator/0.3.0/manifests/integrity-shield-operator-controller-manager-metrics-service_v1_service.yaml
- operators/integrity-shield-operator/0.3.0/manifests/integrity-shield-operator-controller-manager_v1_serviceaccount.yaml
- operators/integrity-shield-operator/0.3.0/manifests/integrity-shield-operator-manager-config_v1_configmap.yaml
- operators/integrity-shield-operator/0.3.0/manifests/integrity-shield-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/integrity-shield-operator/0.3.0/manifests/integrity-shield-operator.clusterserviceversion.yaml
- operators/integrity-shield-operator/0.3.0/metadata/annotations.yaml
- operators/integrity-shield-operator/0.3.0/tests/scorecard/config.yaml
Signed-off-by: Ruriko Kudo <rurikudo@ibm.com>
Co-authored-by: Kugamoorthy Gajananan <gajan@jp.ibm.com>
--
> operators [R] integrity-shield-operator (0.1.3 0.1.4 0.1.5 0.1.6 0.3.0)

- operators/aqua/6.5.0/aqua-operator.v6.5.0.clusterserviceversion.yaml
- operators/aqua/6.5.0/aquacsps.operator.aquasec.com.crd.yaml
- operators/aqua/6.5.0/aquadatabases.operator.aquasec.com.crd.yaml
- operators/aqua/6.5.0/aquaenforcers.operator.aquasec.com.crd.yaml
- operators/aqua/6.5.0/aquagateways.operator.aquasec.com.crd.yaml
- operators/aqua/6.5.0/aquakubeenforcers.operator.aquasec.com.crd.yaml
- operators/aqua/6.5.0/aquascanners.operator.aquasec.com.crd.yaml
- operators/aqua/6.5.0/aquaservers.operator.aquasec.com.crd.yaml
- operators/aqua/aqua-operator.package.yaml
- operators/aqua/ci.yaml
adding new reviewer
Signed-off-by: yossigilad-aquasec <yossi.gilad@aquasec.com>
--
> operators [CI] aqua (6.5.0)

- operators/percona-server-mongodb-operator/1.10.0/percona-server-mongodb-operator.v1.10.0.clusterserviceversion.yaml
- operators/percona-server-mongodb-operator/1.10.0/perconaservermongodbbackups.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.10.0/perconaservermongodbrestores.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.10.0/perconaservermongodbs.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/percona-server-mongodb-operator.package.yaml
> operators percona-server-mongodb-operator (1.10.0)

- operators/pulp-operator/0.4.0/bundle.Dockerfile
- operators/pulp-operator/0.4.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.4.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.4.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.4.0/manifests/pulp-operator.v0.4.0.clusterserviceversion.yaml
- operators/pulp-operator/0.4.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.4.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.4.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.4.0/metadata/annotations.yaml
- operators/pulp-operator/0.4.0/tests/scorecard/config.yaml
- operators/pulp-operator/ci.yaml
> operators [CI] pulp-operator (0.4.0)

- operators/carbonetes-operator/1.0.4/bundle.Dockerfile
- operators/carbonetes-operator/1.0.4/manifests/apps.docker.io_carbonetesanalyzers.yaml
- operators/carbonetes-operator/1.0.4/manifests/carbonetes-controller-manager-metrics-service_v1_service.yaml
- operators/carbonetes-operator/1.0.4/manifests/carbonetes-manager-config_v1_configmap.yaml
- operators/carbonetes-operator/1.0.4/manifests/carbonetes-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/carbonetes-operator/1.0.4/manifests/carbonetes-operator.clusterserviceversion.yaml
- operators/carbonetes-operator/1.0.4/metadata/annotations.yaml
- operators/carbonetes-operator/1.0.4/tests/scorecard/config.yaml
- operators/carbonetes-operator/ci.yaml
Signed-off-by: Jayson Santos <eng@carbonetes.com>
* [ x Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
-- …
> operators [N] [CI] carbonetes-operator (1.0.4)

- operators/istio-workspace-operator/0.4.0/manifests/istio-workspace-operator.clusterserviceversion.yaml
- operators/istio-workspace-operator/0.4.0/manifests/maistra.io_sessions.yaml
- operators/istio-workspace-operator/0.4.0/metadata/annotations.yaml
- operators/istio-workspace-operator/0.4.0/tests/scorecard/config.yaml
> operators istio-workspace-operator (0.4.0)

- operators/cluster-manager/0.5.0/cluster-manager.v0.5.0.clusterserviceversion.yaml
- operators/cluster-manager/0.5.0/operator.open-cluster-management.io_clustermanagers.yaml
- operators/cluster-manager/cluster-manger.package.yaml
> operators cluster-manager (0.5.0)

- operators/opentelemetry-operator/0.37.1/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.37.1/manifests/opentelemetry-operator-controller-manager_v1_serviceaccount.yaml
- operators/opentelemetry-operator/0.37.1/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.37.1/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.37.1/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.37.1/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.37.1/metadata/annotations.yaml
> operators opentelemetry-operator (0.37.1)

- operators/flux/0.20.1/manifests/alert.crd.yaml
- operators/flux/0.20.1/manifests/bucket.crd.yaml
- operators/flux/0.20.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.20.1/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.20.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.20.1/manifests/flux.v0.20.1.clusterserviceversion.yaml
- operators/flux/0.20.1/manifests/gitrepository.crd.yaml
- operators/flux/0.20.1/manifests/helm-controller.serviceaccount.yaml
- operators/flux/0.20.1/manifests/helmchart.crd.yaml
- operators/flux/0.20.1/manifests/helmrelease.crd.yaml
- operators/flux/0.20.1/manifests/helmrepository.crd.yaml
- operators/flux/0.20.1/manifests/image-automation-controller.serviceaccount.yaml
- operators/flux/0.20.1/manifests/image-reflector-controller.serviceaccount.yaml
- operators/flux/0.20.1/manifests/imagepolicy.crd.yaml
- operators/flux/0.20.1/manifests/imagerepository.crd.yaml
- operators/flux/0.20.1/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.20.1/manifests/kustomization.crd.yaml
- operators/flux/0.20.1/manifests/kustomize-controller.serviceaccount.yaml
- operators/flux/0.20.1/manifests/notification-controller.service.yaml
- operators/flux/0.20.1/manifests/notification-controller.serviceaccount.yaml
- operators/flux/0.20.1/manifests/provider.crd.yaml
- operators/flux/0.20.1/manifests/receiver.crd.yaml
- operators/flux/0.20.1/manifests/source-controller.service.yaml
- operators/flux/0.20.1/manifests/source-controller.serviceaccount.yaml
- operators/flux/0.20.1/manifests/webhook-receiver.service.yaml
- operators/flux/0.20.1/metadata/annotations.yaml
> operators flux (0.20.1)

- operators/knative-operator/1.0.0/knative-operator.v1.0.0.clusterserviceversion.yaml
- operators/knative-operator/1.0.0/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.0.0/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/knative-operator.package.yaml
> operators knative-operator (1.0.0)

- operators/ibm-security-verify-access-operator/ci.yaml
…operator.
Signed-off-by: SCOTT A. EXTON <scotte@au1.ibm.com>
--
> operators [CI] ibm-security-verify-access-operator

- operators/snyk-operator/1.70.1/snyk-operator.v1.70.1.clusterserviceversion.yaml
- operators/snyk-operator/1.70.1/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.70.1)

- operators/pulp-operator/0.5.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.5.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.5.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.5.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.5.0/manifests/pulp-operator.v0.5.0.clusterserviceversion.yaml
- operators/pulp-operator/0.5.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.5.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.5.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.5.0/metadata/annotations.yaml
- operators/pulp-operator/0.5.0/tests/scorecard/config.yaml
> operators pulp-operator (0.5.0)

- operators/flux/0.21.1/manifests/alert.crd.yaml
- operators/flux/0.21.1/manifests/bucket.crd.yaml
- operators/flux/0.21.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.21.1/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.21.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.21.1/manifests/flux.v0.21.1.clusterserviceversion.yaml
- operators/flux/0.21.1/manifests/gitrepository.crd.yaml
- operators/flux/0.21.1/manifests/helm-controller.serviceaccount.yaml
- operators/flux/0.21.1/manifests/helmchart.crd.yaml
- operators/flux/0.21.1/manifests/helmrelease.crd.yaml
- operators/flux/0.21.1/manifests/helmrepository.crd.yaml
- operators/flux/0.21.1/manifests/image-automation-controller.serviceaccount.yaml
- operators/flux/0.21.1/manifests/image-reflector-controller.serviceaccount.yaml
- operators/flux/0.21.1/manifests/imagepolicy.crd.yaml
- operators/flux/0.21.1/manifests/imagerepository.crd.yaml
- operators/flux/0.21.1/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.21.1/manifests/kustomization.crd.yaml
- operators/flux/0.21.1/manifests/kustomize-controller.serviceaccount.yaml
- operators/flux/0.21.1/manifests/notification-controller.service.yaml
- operators/flux/0.21.1/manifests/notification-controller.serviceaccount.yaml
- operators/flux/0.21.1/manifests/provider.crd.yaml
- operators/flux/0.21.1/manifests/receiver.crd.yaml
- operators/flux/0.21.1/manifests/source-controller.service.yaml
- operators/flux/0.21.1/manifests/source-controller.serviceaccount.yaml
- operators/flux/0.21.1/manifests/webhook-receiver.service.yaml
- operators/flux/0.21.1/metadata/annotations.yaml
> operators flux (0.21.1)

- operators/falcon-operator/0.3.1/manifests/falcon-operator-controller-manager-metrics-service_v1_service.yaml
- operators/falcon-operator/0.3.1/manifests/falcon-operator-manager-config_v1_configmap.yaml
- operators/falcon-operator/0.3.1/manifests/falcon-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/falcon-operator/0.3.1/manifests/falcon-operator.clusterserviceversion.yaml
- operators/falcon-operator/0.3.1/manifests/falcon.crowdstrike.com_falconcontainers.yaml
- operators/falcon-operator/0.3.1/manifests/falcon.crowdstrike.com_falconnodesensors.yaml
- operators/falcon-operator/0.3.1/metadata/annotations.yaml
- operators/falcon-operator/0.3.1/tests/scorecard/config.yaml
- operators/falcon-operator/ci.yaml
Signed-off-by: Simon Lukasik <simon.lukasik@crowdstrike.com>
--
> operators [N] [CI] falcon-operator (0.3.1)

- operators/snyk-operator/1.70.4/snyk-operator.v1.70.4.clusterserviceversion.yaml
- operators/snyk-operator/1.70.4/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.70.4)

- operators/flux/0.22.0/manifests/alert.crd.yaml
- operators/flux/0.22.0/manifests/bucket.crd.yaml
- operators/flux/0.22.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.22.0/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.22.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.22.0/manifests/flux.v0.22.0.clusterserviceversion.yaml
- operators/flux/0.22.0/manifests/gitrepository.crd.yaml
- operators/flux/0.22.0/manifests/helm-controller.serviceaccount.yaml
- operators/flux/0.22.0/manifests/helmchart.crd.yaml
- operators/flux/0.22.0/manifests/helmrelease.crd.yaml
- operators/flux/0.22.0/manifests/helmrepository.crd.yaml
- operators/flux/0.22.0/manifests/image-automation-controller.serviceaccount.yaml
- operators/flux/0.22.0/manifests/image-reflector-controller.serviceaccount.yaml
- operators/flux/0.22.0/manifests/imagepolicy.crd.yaml
- operators/flux/0.22.0/manifests/imagerepository.crd.yaml
- operators/flux/0.22.0/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.22.0/manifests/kustomization.crd.yaml
- operators/flux/0.22.0/manifests/kustomize-controller.serviceaccount.yaml
- operators/flux/0.22.0/manifests/notification-controller.service.yaml
- operators/flux/0.22.0/manifests/notification-controller.serviceaccount.yaml
- operators/flux/0.22.0/manifests/provider.crd.yaml
- operators/flux/0.22.0/manifests/receiver.crd.yaml
- operators/flux/0.22.0/manifests/source-controller.service.yaml
- operators/flux/0.22.0/manifests/source-controller.serviceaccount.yaml
- operators/flux/0.22.0/manifests/webhook-receiver.service.yaml
- operators/flux/0.22.0/metadata/annotations.yaml
> operators flux (0.22.0)

- operators/argocd-operator/0.1.0/argocd-operator.v0.1.0.clusterserviceversion.yaml
- operators/argocd-operator/0.1.0/argoproj.io_applications.yaml
- operators/argocd-operator/0.1.0/argoproj.io_applicationsets.yaml
- operators/argocd-operator/0.1.0/argoproj.io_appprojects.yaml
- operators/argocd-operator/0.1.0/argoproj.io_argocdexports.yaml
- operators/argocd-operator/0.1.0/argoproj.io_argocds.yaml
- operators/argocd-operator/argocd-operator.package.yaml
- operators/argocd-operator/ci.yaml
Signed-off-by: John Pitman <jpitman@redhat.com>
--
> operators [CI] argocd-operator (0.1.0)

- operators/topolvm-operator/2.0.0/manifests/topolvm-operator.clusterserviceversion.yaml
Signed-off-by: little-guy-lxr <xiaoren_luo@163.com>
--
> operators [N] topolvm-operator (2.0.0)

- operators/cloud-native-postgresql/ci.yaml
> operators [CI] cloud-native-postgresql

- operators/flux/0.22.1/manifests/alert.crd.yaml
- operators/flux/0.22.1/manifests/bucket.crd.yaml
- operators/flux/0.22.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.22.1/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.22.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.22.1/manifests/flux.v0.22.1.clusterserviceversion.yaml
- operators/flux/0.22.1/manifests/gitrepository.crd.yaml
- operators/flux/0.22.1/manifests/helm-controller.serviceaccount.yaml
- operators/flux/0.22.1/manifests/helmchart.crd.yaml
- operators/flux/0.22.1/manifests/helmrelease.crd.yaml
- operators/flux/0.22.1/manifests/helmrepository.crd.yaml
- operators/flux/0.22.1/manifests/image-automation-controller.serviceaccount.yaml
- operators/flux/0.22.1/manifests/image-reflector-controller.serviceaccount.yaml
- operators/flux/0.22.1/manifests/imagepolicy.crd.yaml
- operators/flux/0.22.1/manifests/imagerepository.crd.yaml
- operators/flux/0.22.1/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.22.1/manifests/kustomization.crd.yaml
- operators/flux/0.22.1/manifests/kustomize-controller.serviceaccount.yaml
- operators/flux/0.22.1/manifests/notification-controller.service.yaml
- operators/flux/0.22.1/manifests/notification-controller.serviceaccount.yaml
- operators/flux/0.22.1/manifests/provider.crd.yaml
- operators/flux/0.22.1/manifests/receiver.crd.yaml
- operators/flux/0.22.1/manifests/source-controller.service.yaml
- operators/flux/0.22.1/manifests/source-controller.serviceaccount.yaml
- operators/flux/0.22.1/manifests/webhook-receiver.service.yaml
- operators/flux/0.22.1/metadata/annotations.yaml
> operators flux (0.22.1)

- operators/cloud-native-postgresql/1.10.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.10.0/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.10.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.10.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.10.0/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.10.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.10.0/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.10.0/tests/scorecard/config.yaml
> operators cloud-native-postgresql (1.10.0)

- operators/yaks/0.6.0/instances.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.6.0/tests.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.6.0/yaks.v0.6.0.clusterserviceversion.yaml
- operators/yaks/yaks.package.yaml
> operators yaks (0.6.0)

- operators/starboard-operator/0.13.0/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.13.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.13.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.13.0/starboard-operator.v0.13.0.clusterserviceversion.yaml
- operators/starboard-operator/0.13.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.13.0)

- operators/flux/0.23.0/manifests/alert.crd.yaml
- operators/flux/0.23.0/manifests/bucket.crd.yaml
- operators/flux/0.23.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.23.0/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.23.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.23.0/manifests/flux.v0.23.0.clusterserviceversion.yaml
- operators/flux/0.23.0/manifests/gitrepository.crd.yaml
- operators/flux/0.23.0/manifests/helm-controller.serviceaccount.yaml
- operators/flux/0.23.0/manifests/helmchart.crd.yaml
- operators/flux/0.23.0/manifests/helmrelease.crd.yaml
- operators/flux/0.23.0/manifests/helmrepository.crd.yaml
- operators/flux/0.23.0/manifests/image-automation-controller.serviceaccount.yaml
- operators/flux/0.23.0/manifests/image-reflector-controller.serviceaccount.yaml
- operators/flux/0.23.0/manifests/imagepolicy.crd.yaml
- operators/flux/0.23.0/manifests/imagerepository.crd.yaml
- operators/flux/0.23.0/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.23.0/manifests/kustomization.crd.yaml
- operators/flux/0.23.0/manifests/kustomize-controller.serviceaccount.yaml
- operators/flux/0.23.0/manifests/notification-controller.service.yaml
- operators/flux/0.23.0/manifests/notification-controller.serviceaccount.yaml
- operators/flux/0.23.0/manifests/provider.crd.yaml
- operators/flux/0.23.0/manifests/receiver.crd.yaml
- operators/flux/0.23.0/manifests/source-controller.service.yaml
- operators/flux/0.23.0/manifests/source-controller.serviceaccount.yaml
- operators/flux/0.23.0/manifests/webhook-receiver.service.yaml
- operators/flux/0.23.0/metadata/annotations.yaml
> operators flux (0.23.0)

- operators/opentelemetry-operator/0.38.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.38.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.38.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.38.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.38.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.38.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.38.0/metadata/annotations.yaml
This commit is based on
https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.38.0
but incorporates the fixed CRD from
https://github.com/open-telemetry/opentelemetry-operator/pull/521
needed to work on Kubernetes 1.22.
Signed-off-by: Robert Kukura <rkukura@redhat.com>
--
<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue …
> operators opentelemetry-operator (0.38.0)

- operators/kiali/1.43.0/bundle.Dockerfile
- operators/kiali/1.43.0/manifests/kiali.crd.yaml
- operators/kiali/1.43.0/manifests/kiali.v1.43.0.clusterserviceversion.yaml
- operators/kiali/1.43.0/metadata/annotations.yaml
> operators kiali (1.43.0)

- operators/ack-s3-controller/0.0.7/bundle.Dockerfile
- operators/ack-s3-controller/0.0.7/manifests/ack-s3-controller.clusterserviceversion.yaml
- operators/ack-s3-controller/0.0.7/manifests/ack-s3-metrics-service_v1_service.yaml
- operators/ack-s3-controller/0.0.7/manifests/ack-s3-reader_rbac.authorization.k8s.io_v1_role.yaml
- operators/ack-s3-controller/0.0.7/manifests/ack-s3-writer_rbac.authorization.k8s.io_v1_role.yaml
- operators/ack-s3-controller/0.0.7/manifests/s3.services.k8s.aws_buckets.yaml
- operators/ack-s3-controller/0.0.7/metadata/annotations.yaml
- operators/ack-s3-controller/0.0.7/tests/scorecard/config.yaml
- operators/ack-s3-controller/ci.yaml
> operators [N] [CI] ack-s3-controller (0.0.7)

- operators/camel-k/1.7.0/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.7.0/camel-k.v1.7.0.clusterserviceversion.yaml
- operators/camel-k/1.7.0/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.7.0/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.7.0/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.7.0/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.7.0/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.7.0/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/camel-k.package.yaml
Signed-off-by: nicolaferraro <ni.ferraro@gmail.com>
--
> operators camel-k (1.7.0)

- operators/pcc-operator/0.2.0/bundle.Dockerfile
- operators/pcc-operator/0.2.0/manifests/consoledefenders.pcc.paloaltonetworks.com.crd.yaml
- operators/pcc-operator/0.2.0/manifests/consoles.pcc.paloaltonetworks.com.crd.yaml
- operators/pcc-operator/0.2.0/manifests/defenders.pcc.paloaltonetworks.com.crd.yaml
- operators/pcc-operator/0.2.0/manifests/pcc-operator.v0.2.0.clusterserviceversion.yaml
- operators/pcc-operator/0.2.0/metadata/annotations.yaml
- operators/pcc-operator/0.2.0/tests/scorecard/config.yaml
> operators pcc-operator (0.2.0)

- operators/tackle-operator/1.1.0/Dockerfile
- operators/tackle-operator/1.1.0/manifests/tackle-operator.v1.1.0.clusterserviceversion.yaml
- operators/tackle-operator/1.1.0/manifests/tackle.crd.yaml
- operators/tackle-operator/1.1.0/metadata/annotations.yaml
Signed-off-by: mrizzi <mrizzi@redhat.com>
--
> operators tackle-operator (1.1.0)

- operators/snyk-operator/1.72.0/snyk-operator.v1.72.0.clusterserviceversion.yaml
- operators/snyk-operator/1.72.0/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.72.0)

- operators/k8gb/ci.yaml
To be able to approve the PRs for k8gb operator, we need a way to do that. My hope is that this settings will assign the reviewers from the list.
Signed-off-by: Jirka Kremser <jiri.kremser@gmail.com>
> operators [CI] k8gb

- operators/datadog-operator/0.7.2/datadog-operator.clusterserviceversion.yaml
- operators/datadog-operator/0.7.2/datadoghq.com_datadogagents.yaml
- operators/datadog-operator/0.7.2/datadoghq.com_datadogmetrics.yaml
- operators/datadog-operator/0.7.2/datadoghq.com_datadogmonitors.yaml
- operators/datadog-operator/datadog-operator.package.yaml
> operators datadog-operator (0.7.2)

- operators/aiven-operator/0.2.0/bundle.Dockerfile
- operators/aiven-operator/0.2.0/manifests/aiven-operator-webhook-service_v1_service.yaml
- operators/aiven-operator/0.2.0/manifests/aiven-operator.v0.2.0.clusterserviceversion.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_connectionpools.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_databases.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_kafkaacls.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_kafkaconnectors.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_kafkaconnects.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_kafkas.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_kafkaschemas.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_kafkatopics.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_postgresqls.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_projects.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_projectvpcs.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_redis.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_serviceintegrations.yaml
- operators/aiven-operator/0.2.0/manifests/aiven.io_serviceusers.yaml
- operators/aiven-operator/0.2.0/metadata/annotations.yaml
- operators/aiven-operator/0.2.0/tests/scorecard/config.yaml
> operators aiven-operator (0.2.0)

- operators/k8gb/0.8.4/manifests/k8gb.v0.8.4.clusterserviceversion.yaml
:package: Update k8gb operator bundle :package:
N/A
This automated PR was created by [this action][1].
[1]: https://github.com/k8gb-io/k8gb/actions/runs/1481538260
> operators [O] k8gb (0.8.4)

- operators/ks-releaser-operator/0.0.1/devops.kubesphere.io_releasercontrollers.yaml
- operators/ks-releaser-operator/0.0.1/devops.kubesphere.io_releasers.yaml
- operators/ks-releaser-operator/0.0.1/ks-releaser-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ks-releaser-operator/0.0.1/ks-releaser-operator-manager-config_v1_configmap.yaml
- operators/ks-releaser-operator/0.0.1/ks-releaser-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ks-releaser-operator/0.0.1/ks-releaser-operator.0.0.1.clusterserviceversion.yaml
- operators/ks-releaser-operator/ci.yaml
- operators/ks-releaser-operator/ks-releaser-operator.package.yaml
> operators [N] [CI] ks-releaser-operator (0.0.1)

- operators/snyk-operator/1.73.0/snyk-operator.v1.73.0.clusterserviceversion.yaml
- operators/snyk-operator/1.73.0/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.73.0)

- operators/pmem-csi-operator/1.0.1/bundle.Dockerfile
- operators/pmem-csi-operator/1.0.1/manifests/pmem-csi-operator-metrics_v1_service.yaml
- operators/pmem-csi-operator/1.0.1/manifests/pmem-csi-operator.clusterserviceversion.yaml
- operators/pmem-csi-operator/1.0.1/manifests/pmem-csi-operator_v1_serviceaccount.yaml
- operators/pmem-csi-operator/1.0.1/manifests/pmem-csi.intel.com_pmemcsideployments.yaml
- operators/pmem-csi-operator/1.0.1/metadata/annotations.yaml
> operators pmem-csi-operator (1.0.1)

- operators/silicom-sts-operator/0.0.1/Dockerfile
- operators/silicom-sts-operator/0.0.1/manifests/silicom-sts-operator.clusterserviceversion.yaml
- operators/silicom-sts-operator/0.0.1/manifests/sts-controller-manager-metrics-service_v1_service.yaml
- operators/silicom-sts-operator/0.0.1/manifests/sts-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/silicom-sts-operator/0.0.1/manifests/sts.silicom.com_stsconfigs.yaml
- operators/silicom-sts-operator/0.0.1/manifests/sts.silicom.com_stsnodes.yaml
- operators/silicom-sts-operator/0.0.1/metadata/annotations.yaml
- operators/silicom-sts-operator/0.0.1/tests/scorecard/config.yaml
- operators/silicom-sts-operator/ci.yaml
Signed-off-by: rmr <rmr@silicom.dk>
--
> operators [N] [CI] silicom-sts-operator (0.0.1)

- operators/grafana-operator/4.0.2/grafana-operator-controller-manager-metrics-service_v1_service.yaml
- operators/grafana-operator/4.0.2/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/4.0.2/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/4.0.2/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/4.0.2/integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/4.0.2/integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/4.0.2/integreatly.org_grafananotificationchannels.yaml
- operators/grafana-operator/4.0.2/integreatly.org_grafanas.yaml
- operators/grafana-operator/grafana-operator.package.yaml
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>
--
> operators grafana-operator (4.0.2)

- operators/portworx/1.6.1/core_v1_storagecluster_crd.yaml
- operators/portworx/1.6.1/core_v1_storagenode_crd.yaml
- operators/portworx/1.6.1/portworxoperator.v1.6.1.clusterserviceversion.yaml
- operators/portworx/portworx.package.yaml
> operators portworx (1.6.1)

- operators/keda/2.5.0/manifests/keda.sh_clustertriggerauthentications.yaml
- operators/keda/2.5.0/manifests/keda.sh_kedacontrollers.yaml
- operators/keda/2.5.0/manifests/keda.sh_scaledjobs.yaml
- operators/keda/2.5.0/manifests/keda.sh_scaledobjects.yaml
- operators/keda/2.5.0/manifests/keda.sh_triggerauthentications.yaml
- operators/keda/2.5.0/manifests/keda.v2.5.0.clusterserviceversion.yaml
- operators/keda/2.5.0/metadata/annotations.yaml
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
--
> operators keda (2.5.0)

- operators/verticadb-operator/1.1.0/Dockerfile
- operators/verticadb-operator/1.1.0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/1.1.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/1.1.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/1.1.0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/1.1.0/metadata/annotations.yaml
- operators/verticadb-operator/1.1.0/tests/scorecard/config.yaml
- operators/verticadb-operator/ci.yaml
> operators [N] [CI] verticadb-operator (1.1.0)

- operators/instana-agent-operator/2.0.1/manifests/controller-manager-metrics-service_v1_service.yaml
- operators/instana-agent-operator/2.0.1/manifests/instana-agent-operator.clusterserviceversion.yaml
- operators/instana-agent-operator/2.0.1/manifests/instana.io_agents.yaml
- operators/instana-agent-operator/2.0.1/manifests/manager-config_v1_configmap.yaml
- operators/instana-agent-operator/2.0.1/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
- operators/instana-agent-operator/2.0.1/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/instana-agent-operator/2.0.1/manifests/webhook-service_v1_service.yaml
- operators/instana-agent-operator/2.0.1/metadata/annotations.yaml
- operators/instana-agent-operator/2.0.1/tests/scorecard/config.yaml
Signed-off-by: Miel Donkers <miel.donkers@instana.com>
--
> operators instana-agent-operator (2.0.1)

- operators/redis-operator/0.9.0/manifests/redis-operator.v0.9.0.clusterserviceversion.yaml
- operators/redis-operator/0.9.0/manifests/redis.redis.redis.opstreelabs.in.crd.yaml
- operators/redis-operator/0.9.0/manifests/redisclusters.redis.redis.opstreelabs.in.crd.yaml
- operators/redis-operator/0.9.0/metadata/annotations.yaml
> operators redis-operator (0.9.0)

- operators/verticadb-operator/1.1.0/manifests/verticadb-operator.clusterserviceversion.yaml
> operators [N] verticadb-operator (1.1.0)

- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.21.0/victoriametrics-operator.0.21.0.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.21.0/vm-operator-vm-operator_v1_serviceaccount.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.21.0)

- operators/ack-apigatewayv2-controller/ci.yaml
- operators/ack-dynamodb-controller/ci.yaml
- operators/ack-ecr-controller/ci.yaml
- operators/ack-elasticache-controller/ci.yaml
- operators/ack-mq-controller/ci.yaml
- operators/ack-opensearchservice-controller/ci.yaml
- operators/ack-rds-controller/ci.yaml
- operators/ack-sagemaker-controller/ci.yaml
> operators [CI] ack-apigatewayv2-controller

- operators/flux/0.24.0/manifests/alert.crd.yaml
- operators/flux/0.24.0/manifests/bucket.crd.yaml
- operators/flux/0.24.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.24.0/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.24.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.24.0/manifests/flux.v0.24.0.clusterserviceversion.yaml
- operators/flux/0.24.0/manifests/gitrepository.crd.yaml
- operators/flux/0.24.0/manifests/helm-controller.serviceaccount.yaml
- operators/flux/0.24.0/manifests/helmchart.crd.yaml
- operators/flux/0.24.0/manifests/helmrelease.crd.yaml
- operators/flux/0.24.0/manifests/helmrepository.crd.yaml
- operators/flux/0.24.0/manifests/image-automation-controller.serviceaccount.yaml
- operators/flux/0.24.0/manifests/image-reflector-controller.serviceaccount.yaml
- operators/flux/0.24.0/manifests/imagepolicy.crd.yaml
- operators/flux/0.24.0/manifests/imagerepository.crd.yaml
- operators/flux/0.24.0/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.24.0/manifests/kustomization.crd.yaml
- operators/flux/0.24.0/manifests/kustomize-controller.serviceaccount.yaml
- operators/flux/0.24.0/manifests/notification-controller.service.yaml
- operators/flux/0.24.0/manifests/notification-controller.serviceaccount.yaml
- operators/flux/0.24.0/manifests/provider.crd.yaml
- operators/flux/0.24.0/manifests/receiver.crd.yaml
- operators/flux/0.24.0/manifests/source-controller.service.yaml
- operators/flux/0.24.0/manifests/source-controller.serviceaccount.yaml
- operators/flux/0.24.0/manifests/webhook-receiver.service.yaml
- operators/flux/0.24.0/metadata/annotations.yaml
> operators flux (0.24.0)

- operators/grafana-operator/4.1.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml
- operators/grafana-operator/4.1.0/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/4.1.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/4.1.0/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/4.1.0/integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/4.1.0/integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/4.1.0/integreatly.org_grafananotificationchannels.yaml
- operators/grafana-operator/4.1.0/integreatly.org_grafanas.yaml
- operators/grafana-operator/grafana-operator.package.yaml
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>
--
> operators grafana-operator (4.1.0)

- operators/grafana-operator/ci.yaml
> operators [CI] grafana-operator

- operators/cass-operator-community/1.9.0/manifests/cass-operator-manager-config_v1_configmap.yaml
- operators/cass-operator-community/1.9.0/manifests/cass-operator-webhook-service_v1_service.yaml
- operators/cass-operator-community/1.9.0/manifests/cass-operator.clusterserviceversion.yaml
- operators/cass-operator-community/1.9.0/manifests/cassandra.datastax.com_cassandradatacenters.yaml
- operators/cass-operator-community/1.9.0/metadata/annotations.yaml
- operators/cass-operator-community/1.9.0/tests/scorecard/config.yaml
- operators/cass-operator-community/ci.yaml
> operators [N] [CI] cass-operator-community (1.9.0)

- operators/starboard-operator/0.13.1/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.13.1/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.13.1/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.13.1/starboard-operator.v0.13.1.clusterserviceversion.yaml
- operators/starboard-operator/0.13.1/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.13.1)

- operators/knative-operator/1.0.0/knative-operator.v1.0.0.clusterserviceversion.yaml
> operators [O] knative-operator (1.0.0)

- operators/dell-csi-operator/1.6.0/csiisilons.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.6.0/csipowermaxes.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.6.0/csipowermaxrevproxies.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.6.0/csipowerstores.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.6.0/csiunities.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.6.0/csivxflexoses.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.6.0/dell-csi-operator.v1.6.0.clusterserviceversion.yaml
- operators/dell-csi-operator/dell-csi-operator.package.yaml
> operators dell-csi-operator (1.6.0)

- operators/kiali/1.44.0/bundle.Dockerfile
- operators/kiali/1.44.0/manifests/kiali.crd.yaml
- operators/kiali/1.44.0/manifests/kiali.v1.44.0.clusterserviceversion.yaml
- operators/kiali/1.44.0/metadata/annotations.yaml
> operators kiali (1.44.0)

- operators/pulp-operator/0.6.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.6.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.6.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.6.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.6.0/manifests/pulp-operator.v0.6.0.clusterserviceversion.yaml
- operators/pulp-operator/0.6.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.6.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.6.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.6.0/metadata/annotations.yaml
- operators/pulp-operator/0.6.0/tests/scorecard/config.yaml
> operators pulp-operator (0.6.0)

- operators/instana-agent-operator/2.0.2/manifests/controller-manager-metrics-service_v1_service.yaml
- operators/instana-agent-operator/2.0.2/manifests/instana-agent-operator.clusterserviceversion.yaml
- operators/instana-agent-operator/2.0.2/manifests/instana.io_agents.yaml
- operators/instana-agent-operator/2.0.2/manifests/manager-config_v1_configmap.yaml
- operators/instana-agent-operator/2.0.2/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
- operators/instana-agent-operator/2.0.2/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/instana-agent-operator/2.0.2/manifests/webhook-service_v1_service.yaml
- operators/instana-agent-operator/2.0.2/metadata/annotations.yaml
- operators/instana-agent-operator/2.0.2/tests/scorecard/config.yaml
> operators instana-agent-operator (2.0.2)

- operators/elastic-cloud-eck/1.9.0/agents.agent.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.0/apmservers.apm.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.0/beats.beat.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.0/elastic-cloud-eck.v1.9.0.clusterserviceversion.yaml
- operators/elastic-cloud-eck/1.9.0/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.0/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.0/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.0/kibanas.kibana.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml
Signed-off-by: David Kowalski <david.kowalski@elastic.co>
--
> operators elastic-cloud-eck (1.9.0)

- operators/opentelemetry-operator/0.40.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.40.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.40.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.40.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.40.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.40.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.40.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.40.0/tests/scorecard/config.yaml
Signed-off-by: Yuri Sa <ysa@redhat.com>
Thanks for submitting your Operator. Please check the below list before you create your Pull Request.
--
> operators opentelemetry-operator (0.40.0)

- operators/pulp-operator/0.6.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.6.1/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.6.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.6.1/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.6.1/manifests/pulp-operator.v0.6.1.clusterserviceversion.yaml
- operators/pulp-operator/0.6.1/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.6.1/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.6.1/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.6.1/metadata/annotations.yaml
- operators/pulp-operator/0.6.1/tests/scorecard/config.yaml
> operators pulp-operator (0.6.1)

- operators/ibm-spectrum-scale-csi-operator/2.4.0/csiscaleoperators.csi.ibm.com.crd.yaml
- operators/ibm-spectrum-scale-csi-operator/2.4.0/ibm-spectrum-scale-csi-operator.v2.4.0.clusterserviceversion.yaml
- operators/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
> operators ibm-spectrum-scale-csi-operator (2.4.0)

- operators/flux/0.24.1/manifests/alert.crd.yaml
- operators/flux/0.24.1/manifests/bucket.crd.yaml
- operators/flux/0.24.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.24.1/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.24.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.24.1/manifests/flux.v0.24.1.clusterserviceversion.yaml
- operators/flux/0.24.1/manifests/gitrepository.crd.yaml
- operators/flux/0.24.1/manifests/helm-controller.serviceaccount.yaml
- operators/flux/0.24.1/manifests/helmchart.crd.yaml
- operators/flux/0.24.1/manifests/helmrelease.crd.yaml
- operators/flux/0.24.1/manifests/helmrepository.crd.yaml
- operators/flux/0.24.1/manifests/image-automation-controller.serviceaccount.yaml
- operators/flux/0.24.1/manifests/image-reflector-controller.serviceaccount.yaml
- operators/flux/0.24.1/manifests/imagepolicy.crd.yaml
- operators/flux/0.24.1/manifests/imagerepository.crd.yaml
- operators/flux/0.24.1/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.24.1/manifests/kustomization.crd.yaml
- operators/flux/0.24.1/manifests/kustomize-controller.serviceaccount.yaml
- operators/flux/0.24.1/manifests/notification-controller.service.yaml
- operators/flux/0.24.1/manifests/notification-controller.serviceaccount.yaml
- operators/flux/0.24.1/manifests/provider.crd.yaml
- operators/flux/0.24.1/manifests/receiver.crd.yaml
- operators/flux/0.24.1/manifests/source-controller.service.yaml
- operators/flux/0.24.1/manifests/source-controller.serviceaccount.yaml
- operators/flux/0.24.1/manifests/webhook-receiver.service.yaml
- operators/flux/0.24.1/metadata/annotations.yaml
> operators flux (0.24.1)

- operators/ack-iam-controller/ci.yaml
> operators [CI] ack-iam-controller

- operators/keycloak-operator/15.1.0/bundle.Dockerfile
- operators/keycloak-operator/15.1.0/manifests/keycloak-operator.v15.1.0.clusterserviceversion.yaml
- operators/keycloak-operator/15.1.0/manifests/keycloakbackups.keycloak.org.crd.yaml
- operators/keycloak-operator/15.1.0/manifests/keycloakclients.keycloak.org.crd.yaml
- operators/keycloak-operator/15.1.0/manifests/keycloakrealms.keycloak.org.crd.yaml
- operators/keycloak-operator/15.1.0/manifests/keycloaks.keycloak.org.crd.yaml
- operators/keycloak-operator/15.1.0/manifests/keycloakusers.keycloak.org.crd.yaml
- operators/keycloak-operator/15.1.0/metadata/annotations.yaml
> operators keycloak-operator (15.1.0)

- operators/yaks/0.7.0/instances.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.7.0/tests.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.7.0/yaks.v0.7.0.clusterserviceversion.yaml
- operators/yaks/yaks.package.yaml
> operators yaks (0.7.0)

- operators/external-secrets-operator/0.3.9/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.3.9/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.3.9/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.3.9/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.3.9/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.3.9/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.3.9/metadata/annotations.yaml
- operators/external-secrets-operator/0.3.9/tests/scorecard/config.yaml
notable changes:
1. pushing new version 0.3.9
2. forked [3scale-ops/external-secrets-operator](https://github.com/3scale-ops/external-secrets-operator) -> [external-secrets/external-secrets-helm-operator](https://github.com/external-secrets/external-secrets-helm-operator)
3. updates all images to point to the new resources
4. update csv links, maintainers, providers
---
--
<sup>1</sup> If you …
> operators external-secrets-operator (0.3.9)

- operators/external-secrets-operator/0.3.10/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.3.10/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.3.10/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.3.10/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.3.10/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.3.10/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.3.10/metadata/annotations.yaml
- operators/external-secrets-operator/0.3.10/tests/scorecard/config.yaml
This PR contains the latest version of external-secrets `v0.3.10`.
> operators external-secrets-operator (0.3.10)

- operators/grafana-operator/4.1.1/grafana-operator-controller-manager-metrics-service_v1_service.yaml
- operators/grafana-operator/4.1.1/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/4.1.1/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/4.1.1/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/4.1.1/integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/4.1.1/integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/4.1.1/integreatly.org_grafananotificationchannels.yaml
- operators/grafana-operator/4.1.1/integreatly.org_grafanas.yaml
- operators/grafana-operator/grafana-operator.package.yaml
> operators grafana-operator (4.1.1)

- operators/cloud-native-postgresql/1.11.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.11.0/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.11.0/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.11.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.11.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.11.0/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.11.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.11.0/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.11.0/tests/scorecard/config.yaml
> operators cloud-native-postgresql (1.11.0)

- operators/deployment-validation-operator/0.2.0/deploymentvalidationoperator.0.2.0.clusterserviceversion.yaml
- operators/deployment-validation-operator/deployment-validation-operator.package.yaml
> operators deployment-validation-operator (0.2.0)

- operators/knative-operator/1.1.0/knative-operator.v1.1.0.clusterserviceversion.yaml
- operators/knative-operator/1.1.0/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.1.0/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/knative-operator.package.yaml
> operators knative-operator (1.1.0)

- operators/mongodb-enterprise/1.14.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.14.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.14.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.14.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.14.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.14.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.14.0/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.14.0/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.14.0/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.14.0/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.14.0/metadata/annotations.yaml
- operators/mongodb-enterprise/1.14.0/tests/scorecard/config.yaml
> operators mongodb-enterprise (1.14.0)

- operators/elastic-cloud-eck/1.9.1/agents.agent.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.1/apmservers.apm.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.1/beats.beat.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.1/elastic-cloud-eck.v1.9.1.clusterserviceversion.yaml
- operators/elastic-cloud-eck/1.9.1/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.1/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.1/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/1.9.1/kibanas.kibana.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml
Signed-off-by: David Kowalski <david.kowalski@elastic.co>
--
> operators elastic-cloud-eck (1.9.1)

- operators/kubernetes-imagepuller-operator/0.1.0/che.eclipse.org_kubernetesimagepullers_crd.yaml
- operators/kubernetes-imagepuller-operator/0.1.0/controller-manager-metrics-service_v1_service.yaml
- operators/kubernetes-imagepuller-operator/0.1.0/kubernetes-image-puller-operator_v1_serviceaccount.yaml
- operators/kubernetes-imagepuller-operator/0.1.0/kubernetes-imagepuller-operator.v0.1.0.clusterserviceversion.yaml
- operators/kubernetes-imagepuller-operator/0.1.0/manager-config_v1_configmap.yaml
- operators/kubernetes-imagepuller-operator/0.1.0/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
--
> operators kubernetes-imagepuller-operator (0.1.0)

- operators/ovms-operator/0.2.0/Dockerfile
- operators/ovms-operator/0.2.0/manifests/intel.com_ovms.yaml
- operators/ovms-operator/0.2.0/manifests/ovms-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ovms-operator/0.2.0/manifests/ovms-operator-controller-manager_v1_serviceaccount.yaml
- operators/ovms-operator/0.2.0/manifests/ovms-operator-manager-config_v1_configmap.yaml
- operators/ovms-operator/0.2.0/manifests/ovms-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ovms-operator/0.2.0/manifests/ovms-operator.clusterserviceversion.yaml
- operators/ovms-operator/0.2.0/metadata/annotations.yaml
- operators/ovms-operator/0.2.0/tests/scorecard/config.yaml
> operators ovms-operator (0.2.0)

- operators/ack-applicationautoscaling-controller/ci.yaml
- operators/ack-ec2-controller/ci.yaml
- operators/ack-eks-controller/ci.yaml
- operators/ack-kms-controller/ci.yaml
- operators/ack-lambda-controller/ci.yaml
- operators/ack-sfn-controller/ci.yaml
- operators/ack-sns-controller/ci.yaml
- operators/ack-sqs-controller/ci.yaml
> operators [CI] ack-applicationautoscaling-controller

- operators/keycloak-operator/15.1.1/bundle.Dockerfile
- operators/keycloak-operator/15.1.1/manifests/keycloak-operator.v15.1.1.clusterserviceversion.yaml
- operators/keycloak-operator/15.1.1/manifests/keycloakbackups.keycloak.org.crd.yaml
- operators/keycloak-operator/15.1.1/manifests/keycloakclients.keycloak.org.crd.yaml
- operators/keycloak-operator/15.1.1/manifests/keycloakrealms.keycloak.org.crd.yaml
- operators/keycloak-operator/15.1.1/manifests/keycloaks.keycloak.org.crd.yaml
- operators/keycloak-operator/15.1.1/manifests/keycloakusers.keycloak.org.crd.yaml
- operators/keycloak-operator/15.1.1/metadata/annotations.yaml
Signed-off-by: jonathan <jvilalop@redhat.com>
--
> operators keycloak-operator (15.1.1)

- operators/snapscheduler/2.1.0/bundle.Dockerfile
- operators/snapscheduler/2.1.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml
- operators/snapscheduler/2.1.0/manifests/snapscheduler-manager-config_v1_configmap.yaml
- operators/snapscheduler/2.1.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/snapscheduler/2.1.0/manifests/snapscheduler.backube_snapshotschedules.yaml
- operators/snapscheduler/2.1.0/manifests/snapscheduler.clusterserviceversion.yaml
- operators/snapscheduler/2.1.0/metadata/annotations.yaml
- operators/snapscheduler/2.1.0/tests/scorecard/config.yaml
> operators snapscheduler (2.1.0)

- operators/starboard-operator/0.13.2/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.13.2/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.13.2/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.13.2/starboard-operator.v0.13.2.clusterserviceversion.yaml
- operators/starboard-operator/0.13.2/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.13.2)

- operators/opentelemetry-operator/0.41.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.41.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.41.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.41.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.41.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.41.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.41.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.41.0/tests/scorecard/config.yaml
Signed-off-by: Yuri Sa <ysa@redhat.com>
--
> operators opentelemetry-operator (0.41.0)

- operators/keycloak-operator/16.0.0/bundle.Dockerfile
- operators/keycloak-operator/16.0.0/manifests/keycloak-operator.v16.0.0.clusterserviceversion.yaml
- operators/keycloak-operator/16.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml
- operators/keycloak-operator/16.0.0/manifests/keycloakclients.keycloak.org.crd.yaml
- operators/keycloak-operator/16.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml
- operators/keycloak-operator/16.0.0/manifests/keycloaks.keycloak.org.crd.yaml
- operators/keycloak-operator/16.0.0/manifests/keycloakusers.keycloak.org.crd.yaml
- operators/keycloak-operator/16.0.0/metadata/annotations.yaml
> operators keycloak-operator (16.0.0)

- operators/beegfs-csi-driver-operator/1.2.1/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml
- operators/beegfs-csi-driver-operator/1.2.1/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml
- operators/beegfs-csi-driver-operator/1.2.1/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/beegfs-csi-driver-operator/1.2.1/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml
- operators/beegfs-csi-driver-operator/1.2.1/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml
- operators/beegfs-csi-driver-operator/1.2.1/metadata/annotations.yaml
- operators/beegfs-csi-driver-operator/1.2.1/tests/scorecard/config.yaml
- operators/beegfs-csi-driver-operator/ci.yaml
Signed-off-by: Eric Weber <eric.weber2@netapp.com>
--
> operators [CI] beegfs-csi-driver-operator (1.2.1)

- operators/instana-agent-operator/2.0.3/manifests/controller-manager-metrics-service_v1_service.yaml
- operators/instana-agent-operator/2.0.3/manifests/instana-agent-operator.clusterserviceversion.yaml
- operators/instana-agent-operator/2.0.3/manifests/instana.io_agents.yaml
- operators/instana-agent-operator/2.0.3/manifests/manager-config_v1_configmap.yaml
- operators/instana-agent-operator/2.0.3/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
- operators/instana-agent-operator/2.0.3/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/instana-agent-operator/2.0.3/manifests/webhook-service_v1_service.yaml
- operators/instana-agent-operator/2.0.3/metadata/annotations.yaml
- operators/instana-agent-operator/2.0.3/tests/scorecard/config.yaml
Signed-off-by: Miel Donkers <miel.donkers@instana.com>
--
> operators instana-agent-operator (2.0.3)

- operators/pulp-operator/0.7.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.7.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.7.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.7.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.7.0/manifests/pulp-operator.v0.7.0.clusterserviceversion.yaml
- operators/pulp-operator/0.7.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.7.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.7.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.7.0/metadata/annotations.yaml
- operators/pulp-operator/0.7.0/tests/scorecard/config.yaml
> operators pulp-operator (0.7.0)

- operators/percona-postgresql-operator/1.1.0/percona-postgresql-operator.v1.1.0.clusterserviceversion.yaml
- operators/percona-postgresql-operator/1.1.0/perconapgclusters.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.1.0/pgclusters.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.1.0/pgreplicas.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.1.0/pgtasks.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/ci.yaml
- operators/percona-postgresql-operator/percona-postgresql-operator.package.yaml
> operators [N] [CI] percona-postgresql-operator (1.1.0)

- operators/verticadb-operator/1.2.0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/1.2.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/1.2.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/1.2.0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/1.2.0/metadata/annotations.yaml
- operators/verticadb-operator/1.2.0/tests/scorecard/config.yaml
> operators verticadb-operator (1.2.0)

- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.22.0/victoriametrics-operator.0.22.0.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.22.0/vm-operator-vm-operator_v1_serviceaccount.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.22.0)

- operators/keycloak-operator/16.1.0/bundle.Dockerfile
- operators/keycloak-operator/16.1.0/manifests/keycloak-operator.v16.1.0.clusterserviceversion.yaml
- operators/keycloak-operator/16.1.0/manifests/keycloakbackups.keycloak.org.crd.yaml
- operators/keycloak-operator/16.1.0/manifests/keycloakclients.keycloak.org.crd.yaml
- operators/keycloak-operator/16.1.0/manifests/keycloakrealms.keycloak.org.crd.yaml
- operators/keycloak-operator/16.1.0/manifests/keycloaks.keycloak.org.crd.yaml
- operators/keycloak-operator/16.1.0/manifests/keycloakusers.keycloak.org.crd.yaml
- operators/keycloak-operator/16.1.0/metadata/annotations.yaml
Signed-off-by: jonathan <jvilalop@redhat.com>
--
> operators keycloak-operator (16.1.0)

- operators/percona-server-mongodb-operator/1.11.0/percona-server-mongodb-operator.v1.11.0.clusterserviceversion.yaml
- operators/percona-server-mongodb-operator/1.11.0/perconaservermongodbbackups.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.11.0/perconaservermongodbrestores.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.11.0/perconaservermongodbs.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/percona-server-mongodb-operator.package.yaml
> operators percona-server-mongodb-operator (1.11.0)

- operators/percona-xtradb-cluster-operator/1.10.0/percona-xtradb-cluster-operator.v1.10.0.clusterserviceversion.yaml
- operators/percona-xtradb-cluster-operator/1.10.0/perconaxtradbbackups.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.10.0/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.10.0/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.10.0/perconaxtradbclusters.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/percona-xtradb-cluster-operator.package.yaml
> operators percona-xtradb-cluster-operator (1.10.0)

- operators/ibm-application-gateway-operator/21.12.0/ibm-application-gateway-operator.v21.12.0.clusterserviceversion.yaml
- operators/ibm-application-gateway-operator/21.12.0/ibmapplicationgateways.ibm.com.crd.yaml
- operators/ibm-application-gateway-operator/ibm-application-gateway-operator.package.yaml
Signed-off-by: keiran <krobinson@au1.ibm.com>
--
> operators ibm-application-gateway-operator (21.12.0)

- operators/external-secrets-operator/0.3.11/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.3.11/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.3.11/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.3.11/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.3.11/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.3.11/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.3.11/metadata/annotations.yaml
- operators/external-secrets-operator/0.3.11/tests/scorecard/config.yaml
This PR contains the latest version of external-secrets v0.3.11.
> operators external-secrets-operator (0.3.11)

- operators/cloud-native-postgresql/1.12.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.12.0/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.12.0/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.12.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.12.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.12.0/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.12.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.12.0/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.12.0/tests/scorecard/config.yaml
> operators cloud-native-postgresql (1.12.0)

- operators/intel-device-plugins-operator/0.23.0/deviceplugin.intel.com_dlbdeviceplugins.yaml
- operators/intel-device-plugins-operator/0.23.0/deviceplugin.intel.com_dsadeviceplugins.yaml
- operators/intel-device-plugins-operator/0.23.0/deviceplugin.intel.com_fpgadeviceplugins.yaml
- operators/intel-device-plugins-operator/0.23.0/deviceplugin.intel.com_gpudeviceplugins.yaml
- operators/intel-device-plugins-operator/0.23.0/deviceplugin.intel.com_qatdeviceplugins.yaml
- operators/intel-device-plugins-operator/0.23.0/deviceplugin.intel.com_sgxdeviceplugins.yaml
- operators/intel-device-plugins-operator/0.23.0/fpga.intel.com_acceleratorfunctions.yaml
- operators/intel-device-plugins-operator/0.23.0/fpga.intel.com_fpgaregions.yaml
- operators/intel-device-plugins-operator/0.23.0/intel-device-plugins-operator.clusterserviceversion.yaml
- operators/intel-device-plugins-operator/intel-device-plugins-operator.package.yaml
Signed-off-by: Hyeongju Johannes Lee <hyeongju.lee@intel.com>
--
> operators intel-device-plugins-operator (0.23.0)

- operators/opentelemetry-operator/0.42.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.42.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.42.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.42.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.42.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.42.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.42.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.42.0/tests/scorecard/config.yaml
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
This PR adds a copy of https://github.com/open-telemetry/opentelemetry-operator/tree/v0.42.0/bundle
--
<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-c …
> operators opentelemetry-operator (0.42.0)

- operators/microcks/1.5.0/microcks-operator.v1.5.0.clusterserviceversion.yaml
- operators/microcks/1.5.0/microcksinstall.crd.yaml
- operators/microcks/microcks.package.yaml
> operators microcks (1.5.0)

- operators/clever-operator/0.3.5/bundle.Dockerfile
- operators/clever-operator/0.3.5/manifests/clever-operator-mongodb.crd.yaml
- operators/clever-operator/0.3.5/manifests/clever-operator-mysql.crd.yaml
- operators/clever-operator/0.3.5/manifests/clever-operator-postgresql.crd.yaml
- operators/clever-operator/0.3.5/manifests/clever-operator-pulsar.crd.yaml
- operators/clever-operator/0.3.5/manifests/clever-operator-redis.crd.yaml
- operators/clever-operator/0.3.5/manifests/clever-operator.clusterserviceversion.yaml
- operators/clever-operator/0.3.5/metadata/annotations.yaml
- operators/clever-operator/0.3.5/tests/scorecard/config.yaml
- operators/clever-operator/ci.yaml
> operators [N] [CI] clever-operator (0.3.5)

- operators/snyk-operator/1.80.0/snyk-operator.v1.80.0.clusterserviceversion.yaml
- operators/snyk-operator/1.80.0/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.80.0)

- operators/flux/0.25.2/manifests/alert.crd.yaml
- operators/flux/0.25.2/manifests/bucket.crd.yaml
- operators/flux/0.25.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.25.2/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.25.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.25.2/manifests/flux.v0.25.2.clusterserviceversion.yaml
- operators/flux/0.25.2/manifests/gitrepository.crd.yaml
- operators/flux/0.25.2/manifests/helmchart.crd.yaml
- operators/flux/0.25.2/manifests/helmrelease.crd.yaml
- operators/flux/0.25.2/manifests/helmrepository.crd.yaml
- operators/flux/0.25.2/manifests/imagepolicy.crd.yaml
- operators/flux/0.25.2/manifests/imagerepository.crd.yaml
- operators/flux/0.25.2/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.25.2/manifests/kustomization.crd.yaml
- operators/flux/0.25.2/manifests/notification-controller.service.yaml
- operators/flux/0.25.2/manifests/provider.crd.yaml
- operators/flux/0.25.2/manifests/receiver.crd.yaml
- operators/flux/0.25.2/manifests/source-controller.service.yaml
- operators/flux/0.25.2/manifests/webhook-receiver.service.yaml
- operators/flux/0.25.2/metadata/annotations.yaml
> operators flux (0.25.2)

- operators/yaks/0.8.0/instances.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.8.0/tests.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.8.0/yaks.v0.8.0.clusterserviceversion.yaml
- operators/yaks/yaks.package.yaml
> operators yaks (0.8.0)

- operators/clickhouse/0.16.0/clickhouse-operator.v0.16.0.clusterserviceversion.yaml
- operators/clickhouse/0.16.0/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.16.0/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.16.0/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/clickhouse.package.yaml
> operators clickhouse (0.16.0)

- operators/gitlab-operator-kubernetes/0.3.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.3.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.3.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.3.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.3.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.3.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.3.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.3.1/tests/scorecard/config.yaml
- operators/gitlab-operator-kubernetes/ci.yaml
> operators [N] [CI] gitlab-operator-kubernetes (0.3.1)

- operators/flux/0.25.3/manifests/alert.crd.yaml
- operators/flux/0.25.3/manifests/bucket.crd.yaml
- operators/flux/0.25.3/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.25.3/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.25.3/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.25.3/manifests/flux.v0.25.3.clusterserviceversion.yaml
- operators/flux/0.25.3/manifests/gitrepository.crd.yaml
- operators/flux/0.25.3/manifests/helmchart.crd.yaml
- operators/flux/0.25.3/manifests/helmrelease.crd.yaml
- operators/flux/0.25.3/manifests/helmrepository.crd.yaml
- operators/flux/0.25.3/manifests/imagepolicy.crd.yaml
- operators/flux/0.25.3/manifests/imagerepository.crd.yaml
- operators/flux/0.25.3/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.25.3/manifests/kustomization.crd.yaml
- operators/flux/0.25.3/manifests/notification-controller.service.yaml
- operators/flux/0.25.3/manifests/provider.crd.yaml
- operators/flux/0.25.3/manifests/receiver.crd.yaml
- operators/flux/0.25.3/manifests/source-controller.service.yaml
- operators/flux/0.25.3/manifests/webhook-receiver.service.yaml
- operators/flux/0.25.3/metadata/annotations.yaml
> operators flux (0.25.3)

- operators/gitlab-operator-kubernetes/ci.yaml
> operators [CI] gitlab-operator-kubernetes

- operators/nfd-operator/0.3.0/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
> operators [N] nfd-operator (0.3.0)

- operators/cluster-manager/0.6.0/cluster-manager.v0.6.0.clusterserviceversion.yaml
- operators/cluster-manager/0.6.0/operator.open-cluster-management.io_clustermanagers.yaml
- operators/cluster-manager/cluster-manger.package.yaml
> operators cluster-manager (0.6.0)

- operators/starboard-operator/0.14.0/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.14.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.14.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.14.0/starboard-operator.v0.14.0.clusterserviceversion.yaml
- operators/starboard-operator/0.14.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.14.0)

- operators/klusterlet/0.6.0/klusterlet.v0.6.0.clusterserviceversion.yaml
- operators/klusterlet/0.6.0/operator.open-cluster-management.io_klusterlets.yaml
- operators/klusterlet/klusterlet.package.yaml
> operators klusterlet (0.6.0)

- operators/api-operator/2.0.0/api-operator.v2.0.0.clusterserviceversion.yaml
> operators [O] api-operator (2.0.0)

- operators/kube-green/0.3.0/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml
- operators/kube-green/0.3.0/manifests/kube-green-manager-config_v1_configmap.yaml
- operators/kube-green/0.3.0/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kube-green/0.3.0/manifests/kube-green-webhook-service_v1_service.yaml
- operators/kube-green/0.3.0/manifests/kube-green.clusterserviceversion.yaml
- operators/kube-green/0.3.0/manifests/kube-green.com_sleepinfos.yaml
- operators/kube-green/0.3.0/metadata/annotations.yaml
- operators/kube-green/0.3.0/tests/scorecard/config.yaml
- operators/kube-green/ci.yaml
Signed-off-by: Davide Bianchi <bianchidavide12@gmail.com>
--
> operators [N] [CI] kube-green (0.3.0)

- operators/clickhouse/0.16.1/clickhouse-operator.v0.16.1.clusterserviceversion.yaml
- operators/clickhouse/0.16.1/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.16.1/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.16.1/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/clickhouse.package.yaml
> operators clickhouse (0.16.1)

- operators/camel-k/1.8.0/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.8.0/camel-k.v1.8.0.clusterserviceversion.yaml
- operators/camel-k/1.8.0/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.8.0/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.8.0/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.8.0/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.8.0/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.8.0/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/camel-k.package.yaml
> operators camel-k (1.8.0)

- operators/sosivio/1.2.0/manifests/sosivio-operator.clusterserviceversion.yaml
- operators/sosivio/1.2.0/manifests/sosivio.crd.yaml
- operators/sosivio/1.2.0/metadata/annotations.yaml
- operators/sosivio/ci.yaml
Signed-off-by: Dan Arlowski <dan@sosiv.io>
--
> operators [N] [CI] sosivio (1.2.0)

- operators/kiali/1.45.0/bundle.Dockerfile
- operators/kiali/1.45.0/manifests/kiali.crd.yaml
- operators/kiali/1.45.0/manifests/kiali.v1.45.0.clusterserviceversion.yaml
- operators/kiali/1.45.0/metadata/annotations.yaml
> operators kiali (1.45.0)

- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.22.1/victoriametrics-operator.0.22.1.clusterserviceversion.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.22.1)

- operators/clickhouse/0.17.0/clickhouse-operator.v0.17.0.clusterserviceversion.yaml
- operators/clickhouse/0.17.0/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.17.0/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.17.0/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/clickhouse.package.yaml
> operators clickhouse (0.17.0)

- operators/couchdb-operator/2.2.1/manifests/backups.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.1/manifests/buckets.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.1/manifests/couchdb-operator.clusterserviceversion.yaml
- operators/couchdb-operator/2.2.1/manifests/couchdbclusters.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.1/manifests/formationlocks.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.1/manifests/formations.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.1/manifests/recipes.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.1/manifests/recipetemplates.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.1/metadata/annotations.yaml
Updates in this release:
- containers built with latest UBI base images
- CouchDB search component (Clouseau) update, which removes Log4J v1 dependency
--
<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operato …
> operators couchdb-operator (2.2.1)

- operators/hpe-csi-operator/2.1.0/manifests/hpe-csi-operator.v2.1.0.clusterserviceversion.yaml
Signed-off-by: Raunak <raunak.kumar@hpe.com>
--
> operators [O] hpe-csi-operator (2.1.0)

- operators/starboard-operator/0.14.1/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.14.1/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.14.1/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.14.1/starboard-operator.v0.14.1.clusterserviceversion.yaml
- operators/starboard-operator/0.14.1/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.14.1)

- operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion-operator-manager-config_v1_configmap.yaml
- operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion-operator.clusterserviceversion.yaml
- operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dicomeventbridges.yaml
- operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dicomeventdriveningestions.yaml
- operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dicominstancebindings.yaml
- operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dicomstudybindings.yaml
- operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dicomwebingestionservices.yaml
- operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dimseingestionservices.yaml
- operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dimseproxies.yaml
- operators/alvearie-imaging-ingestion/0.0.3/metadata/annotations.yaml
- operators/alvearie-imaging-ingestion/0.0.3/tests/scorecard/config.yaml
Signed-off-by: Jeesmon Jacob <jjacob@us.ibm.com>
--
> operators alvearie-imaging-ingestion (0.0.3)

- operators/integrity-shield-operator/0.3.2/manifests/apis.integrityshield.io_integrityshields.yaml
- operators/integrity-shield-operator/0.3.2/manifests/integrity-shield-operator-controller-manager-metrics-service_v1_service.yaml
- operators/integrity-shield-operator/0.3.2/manifests/integrity-shield-operator-manager-config_v1_configmap.yaml
- operators/integrity-shield-operator/0.3.2/manifests/integrity-shield-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/integrity-shield-operator/0.3.2/manifests/integrity-shield-operator.clusterserviceversion.yaml
- operators/integrity-shield-operator/0.3.2/metadata/annotations.yaml
- operators/integrity-shield-operator/0.3.2/tests/scorecard/config.yaml
Signed-off-by: Ruriko Kudo <rurikudo@ibm.com>
--
> operators integrity-shield-operator (0.3.2)

- operators/eventing-kogito/1.1.0/manifests/config-logging_v1_configmap.yaml
- operators/eventing-kogito/1.1.0/manifests/config-observability_v1_configmap.yaml
- operators/eventing-kogito/1.1.0/manifests/eventing-kogito.clusterserviceversion.yaml
- operators/eventing-kogito/1.1.0/manifests/kogito-source-controller-manager_v1_service.yaml
- operators/eventing-kogito/1.1.0/manifests/kogito-source-observer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/eventing-kogito/1.1.0/manifests/kogito.knative.dev_kogitosources.yaml
- operators/eventing-kogito/1.1.0/metadata/annotations.yaml
- operators/eventing-kogito/1.1.0/metadata/dependencies.yaml
- operators/eventing-kogito/1.1.0/tests/scorecard/config.yaml
- operators/eventing-kogito/ci.yaml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
--
> operators [N] [CI] eventing-kogito (1.1.0)

- operators/qserv-operator/2022.1.1-rc1/manifests/qserv-operator-controller-manager-metrics-service_v1_service.yaml
- operators/qserv-operator/2022.1.1-rc1/manifests/qserv-operator-manager-config_v1_configmap.yaml
- operators/qserv-operator/2022.1.1-rc1/manifests/qserv-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/qserv-operator/2022.1.1-rc1/manifests/qserv-operator.clusterserviceversion.yaml
- operators/qserv-operator/2022.1.1-rc1/manifests/qserv.lsst.org_qservs.yaml
- operators/qserv-operator/2022.1.1-rc1/metadata/annotations.yaml
- operators/qserv-operator/2022.1.1-rc1/tests/scorecard/config.yaml
Signed-off-by: Fabrice Jammes <fabrice.jammes@in2p3.fr>
--
> operators qserv-operator (2022.1.1-rc1)

- operators/snyk-operator/1.81.1/snyk-operator.v1.81.1.clusterserviceversion.yaml
- operators/snyk-operator/1.81.1/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.81.1)

- operators/knative-operator/1.2.0/knative-operator.v1.2.0.clusterserviceversion.yaml
- operators/knative-operator/1.2.0/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.2.0/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/knative-operator.package.yaml
> operators knative-operator (1.2.0)

- operators/clickhouse/0.18.0/clickhouse-operator.v0.18.0.clusterserviceversion.yaml
- operators/clickhouse/0.18.0/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.18.0/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.18.0/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/clickhouse.package.yaml
> operators clickhouse (0.18.0)

- operators/deployment-validation-operator/0.2.1/deploymentvalidationoperator.0.2.1.clusterserviceversion.yaml
- operators/deployment-validation-operator/ci.yaml
- operators/deployment-validation-operator/deployment-validation-operator.package.yaml
Signed-off-by: Alex Njaastad <anjaastad@gmail.com>
* [ X ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ X ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ X ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ X ] Have you tested an update to your Operator when deployed via OLM?
* [ X ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/con …
> operators [CI] deployment-validation-operator (0.2.1)

- operators/tackle-operator/1.2.0/Dockerfile
- operators/tackle-operator/1.2.0/manifests/tackle-operator.v1.2.0.clusterserviceversion.yaml
- operators/tackle-operator/1.2.0/manifests/tackle.crd.yaml
- operators/tackle-operator/1.2.0/metadata/annotations.yaml
Signed-off-by: Carlos Esteban Feria Vila <2582866+carlosthe19916@users.noreply.github.com>
--
> operators tackle-operator (1.2.0)

- operators/keda/2.6.0/manifests/keda.sh_clustertriggerauthentications.yaml
- operators/keda/2.6.0/manifests/keda.sh_kedacontrollers.yaml
- operators/keda/2.6.0/manifests/keda.sh_scaledjobs.yaml
- operators/keda/2.6.0/manifests/keda.sh_scaledobjects.yaml
- operators/keda/2.6.0/manifests/keda.sh_triggerauthentications.yaml
- operators/keda/2.6.0/manifests/keda.v2.6.0.clusterserviceversion.yaml
- operators/keda/2.6.0/metadata/annotations.yaml
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
--
> operators keda (2.6.0)

- operators/eventing-kogito/1.2.0/manifests/config-logging_v1_configmap.yaml
- operators/eventing-kogito/1.2.0/manifests/config-observability_v1_configmap.yaml
- operators/eventing-kogito/1.2.0/manifests/eventing-kogito.clusterserviceversion.yaml
- operators/eventing-kogito/1.2.0/manifests/kogito-source-controller-manager_v1_service.yaml
- operators/eventing-kogito/1.2.0/manifests/kogito-source-observer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/eventing-kogito/1.2.0/manifests/kogito.knative.dev_kogitosources.yaml
- operators/eventing-kogito/1.2.0/metadata/annotations.yaml
- operators/eventing-kogito/1.2.0/metadata/dependencies.yaml
- operators/eventing-kogito/1.2.0/tests/scorecard/config.yaml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
--
> operators eventing-kogito (1.2.0)

- operators/ibm-application-gateway-operator/22.2.0/manifests/ibm-application-gateway-operator-ctrl-mgr-metrics-service_v1_service.yaml
- operators/ibm-application-gateway-operator/22.2.0/manifests/ibm-application-gateway-operator-manager-config_v1_configmap.yaml
- operators/ibm-application-gateway-operator/22.2.0/manifests/ibm-application-gateway-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ibm-application-gateway-operator/22.2.0/manifests/ibm-application-gateway-operator-webhook-service_v1_service.yaml
- operators/ibm-application-gateway-operator/22.2.0/manifests/ibm-application-gateway-operator.clusterserviceversion.yaml
- operators/ibm-application-gateway-operator/22.2.0/manifests/ibm.com_ibmapplicationgateways.yaml
- operators/ibm-application-gateway-operator/22.2.0/metadata/annotations.yaml
- operators/ibm-application-gateway-operator/22.2.0/tests/scorecard/config.yaml
Signed-off-by: SCOTT A. EXTON <scotte@au1.ibm.com>
--
> operators ibm-application-gateway-operator (22.2.0)

- operators/portworx/1.7.0/core_v1_storagecluster_crd.yaml
- operators/portworx/1.7.0/core_v1_storagenode_crd.yaml
- operators/portworx/1.7.0/portworxoperator.clusterserviceversion.yaml
- operators/portworx/portworx.package.yaml
Signed-off-by: HaibinMichaelXie <hxie@purestorage.com>
--
> operators portworx (1.7.0)

- operators/clickhouse/0.18.1/clickhouse-operator.v0.18.1.clusterserviceversion.yaml
- operators/clickhouse/0.18.1/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.18.1/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/0.18.1/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
- operators/clickhouse/clickhouse.package.yaml
> operators clickhouse (0.18.1)

- operators/knative-operator/1.2.0/knative-operator.v1.2.0.clusterserviceversion.yaml
> operators [O] knative-operator (1.2.0)

- operators/flux/0.26.0/manifests/alert.crd.yaml
- operators/flux/0.26.0/manifests/bucket.crd.yaml
- operators/flux/0.26.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.26.0/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.26.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.26.0/manifests/flux.v0.26.0.clusterserviceversion.yaml
- operators/flux/0.26.0/manifests/gitrepository.crd.yaml
- operators/flux/0.26.0/manifests/helmchart.crd.yaml
- operators/flux/0.26.0/manifests/helmrelease.crd.yaml
- operators/flux/0.26.0/manifests/helmrepository.crd.yaml
- operators/flux/0.26.0/manifests/imagepolicy.crd.yaml
- operators/flux/0.26.0/manifests/imagerepository.crd.yaml
- operators/flux/0.26.0/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.26.0/manifests/kustomization.crd.yaml
- operators/flux/0.26.0/manifests/notification-controller.service.yaml
- operators/flux/0.26.0/manifests/provider.crd.yaml
- operators/flux/0.26.0/manifests/receiver.crd.yaml
- operators/flux/0.26.0/manifests/source-controller.service.yaml
- operators/flux/0.26.0/manifests/webhook-receiver.service.yaml
- operators/flux/0.26.0/metadata/annotations.yaml
> operators flux (0.26.0)

- operators/trivy-operator/2.3.0/manifests/namespace-scanners.trivy-operator.devopstales.io.crd.yaml
- operators/trivy-operator/2.3.0/manifests/trivy-operator.service.yaml
- operators/trivy-operator/2.3.0/manifests/trivy-operator.v2.3.0.clusterserviceversion.yaml
- operators/trivy-operator/2.3.0/metadata/annotations.yaml
Signed-off-by: devopstales <42894256+devopstales@users.noreply.github.com>
--
> operators trivy-operator (2.3.0)

- operators/flux/0.26.1/manifests/alert.crd.yaml
- operators/flux/0.26.1/manifests/bucket.crd.yaml
- operators/flux/0.26.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.26.1/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.26.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.26.1/manifests/flux.v0.26.1.clusterserviceversion.yaml
- operators/flux/0.26.1/manifests/gitrepository.crd.yaml
- operators/flux/0.26.1/manifests/helmchart.crd.yaml
- operators/flux/0.26.1/manifests/helmrelease.crd.yaml
- operators/flux/0.26.1/manifests/helmrepository.crd.yaml
- operators/flux/0.26.1/manifests/imagepolicy.crd.yaml
- operators/flux/0.26.1/manifests/imagerepository.crd.yaml
- operators/flux/0.26.1/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.26.1/manifests/kustomization.crd.yaml
- operators/flux/0.26.1/manifests/notification-controller.service.yaml
- operators/flux/0.26.1/manifests/provider.crd.yaml
- operators/flux/0.26.1/manifests/receiver.crd.yaml
- operators/flux/0.26.1/manifests/source-controller.service.yaml
- operators/flux/0.26.1/manifests/webhook-receiver.service.yaml
- operators/flux/0.26.1/metadata/annotations.yaml
> operators flux (0.26.1)

- operators/shipwright-operator/0.8.0/manifests/operator.shipwright.io_shipwrightbuilds.yaml
- operators/shipwright-operator/0.8.0/manifests/shipwright-operator-manager-config_v1_configmap.yaml
- operators/shipwright-operator/0.8.0/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/shipwright-operator/0.8.0/manifests/shipwright-operator-metrics-service_v1_service.yaml
- operators/shipwright-operator/0.8.0/manifests/shipwright-operator.clusterserviceversion.yaml
- operators/shipwright-operator/0.8.0/metadata/annotations.yaml
- operators/shipwright-operator/0.8.0/tests/scorecard/config.yaml
Upgrade shipwright-operator to v0.8.0.
----
--
> operators shipwright-operator (0.8.0)

- operators/external-secrets-operator/0.4.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.4.1/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.4.1/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.4.1/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.4.1/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.4.1/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.4.1/metadata/annotations.yaml
- operators/external-secrets-operator/0.4.1/tests/scorecard/config.yaml
> operators external-secrets-operator (0.4.1)

- operators/druid-operator/0.0.7/druid-operator.v0.0.6.clusterserviceversion.yaml
- operators/druid-operator/0.0.7/druid.apache.org_druids.yaml
- operators/druid-operator/0.0.8/druid-operator.v0.0.6.clusterserviceversion.yaml
- operators/druid-operator/0.0.8/druid.apache.org_druids.yaml
- operators/druid-operator/ci.yaml
- operators/druid-operator/druid-operator.package.yaml
> operators [R] [CI] druid-operator (0.0.7 0.0.8)

- operators/aerospike-kubernetes-operator/2.0.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml
- operators/aerospike-kubernetes-operator/2.0.0/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml
- operators/aerospike-kubernetes-operator/2.0.0/manifests/aerospike-operator-manager-config_v1_configmap.yaml
- operators/aerospike-kubernetes-operator/2.0.0/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/aerospike-kubernetes-operator/2.0.0/manifests/aerospike-operator-webhook-service_v1_service.yaml
- operators/aerospike-kubernetes-operator/2.0.0/manifests/asdb.aerospike.com_aerospikeclusters.yaml
- operators/aerospike-kubernetes-operator/2.0.0/metadata/annotations.yaml
- operators/aerospike-kubernetes-operator/2.0.0/tests/scorecard/config.yaml
- operators/aerospike-kubernetes-operator/ci.yaml
Release aerospike-kubernetes-operator 2.0.0
Signed-off-by: davi17g <dgerchikov@aerospike.com>
--
> operators [N] [CI] aerospike-kubernetes-operator (2.0.0)

- operators/snyk-operator/1.82.1/snyk-operator.v1.82.1.clusterserviceversion.yaml
- operators/snyk-operator/1.82.1/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.82.1)

- operators/kiali/1.46.0/bundle.Dockerfile
- operators/kiali/1.46.0/manifests/kiali.crd.yaml
- operators/kiali/1.46.0/manifests/kiali.v1.46.0.clusterserviceversion.yaml
- operators/kiali/1.46.0/metadata/annotations.yaml
> operators kiali (1.46.0)

- operators/deployment-validation-operator/0.2.2/deploymentvalidationoperator.0.2.2.clusterserviceversion.yaml
- operators/deployment-validation-operator/deployment-validation-operator.package.yaml
> operators deployment-validation-operator (0.2.2)

- operators/patterns-operator/0.0.1/bundle.Dockerfile
- operators/patterns-operator/0.0.1/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.1/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.1/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.1/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.1/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.1/metadata/annotations.yaml
- operators/patterns-operator/0.0.1/tests/scorecard/config.yaml
- operators/patterns-operator/ci.yaml
Signed-off-by: Andrew Beekhof <andrew@beekhof.net>
* [ x ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ x ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ x ] Have you tested your Operator with all Custom Resource Definitions?
* [ x ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ x ] Have you considered whether …
> operators [N] [CI] patterns-operator (0.0.1)

- operators/keda/2.6.1/manifests/keda.sh_clustertriggerauthentications.yaml
- operators/keda/2.6.1/manifests/keda.sh_kedacontrollers.yaml
- operators/keda/2.6.1/manifests/keda.sh_scaledjobs.yaml
- operators/keda/2.6.1/manifests/keda.sh_scaledobjects.yaml
- operators/keda/2.6.1/manifests/keda.sh_triggerauthentications.yaml
- operators/keda/2.6.1/manifests/keda.v2.6.1.clusterserviceversion.yaml
- operators/keda/2.6.1/metadata/annotations.yaml
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
--
> operators keda (2.6.1)

- operators/elastic-cloud-eck/2.0.0/agents.agent.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.0.0/apmservers.apm.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.0.0/beats.beat.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.0.0/elastic-cloud-eck.v2.0.0.clusterserviceversion.yaml
- operators/elastic-cloud-eck/2.0.0/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.0.0/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.0.0/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.0.0/kibanas.kibana.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml
Signed-off-by: Peter Brachwitz [peter.brachwitz@elastic.co](mailto:peter.brachwitz@elastic.co)
--
> operators elastic-cloud-eck (2.0.0)

- operators/netobserv-operator/0.1.0/bundle.Dockerfile
- operators/netobserv-operator/0.1.0/manifests/flows.netobserv.io_flowcollectors.yaml
- operators/netobserv-operator/0.1.0/manifests/netobserv-manager-config_v1_configmap.yaml
- operators/netobserv-operator/0.1.0/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/netobserv-operator/0.1.0/manifests/netobserv-metrics-service_v1_service.yaml
- operators/netobserv-operator/0.1.0/manifests/network-observability-operator.clusterserviceversion.yaml
- operators/netobserv-operator/0.1.0/metadata/annotations.yaml
- operators/netobserv-operator/ci.yaml
> operators [N] [CI] netobserv-operator (0.1.0)

- operators/pmem-csi-operator/1.0.2/bundle.Dockerfile
- operators/pmem-csi-operator/1.0.2/manifests/pmem-csi-operator-metrics_v1_service.yaml
- operators/pmem-csi-operator/1.0.2/manifests/pmem-csi-operator.clusterserviceversion.yaml
- operators/pmem-csi-operator/1.0.2/manifests/pmem-csi.intel.com_pmemcsideployments.yaml
- operators/pmem-csi-operator/1.0.2/metadata/annotations.yaml
> operators pmem-csi-operator (1.0.2)

- operators/netobserv-operator/0.1.0/manifests/network-observability-operator.clusterserviceversion.yaml
> operators [N] netobserv-operator (0.1.0)

- operators/sosivio/1.2.1/manifests/sosivio-operator.clusterserviceversion.yaml
- operators/sosivio/1.2.1/manifests/sosivio.crd.yaml
- operators/sosivio/1.2.1/metadata/annotations.yaml
- operators/sosivio/ci.yaml
Signed-off-by: Dan Arlowski <dan@sosiv.io>
--
> operators [CI] sosivio (1.2.1)

- operators/mongodb-enterprise/1.15.0/manifests/appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.15.0/manifests/database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.15.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.15.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.15.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.15.0/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.15.0/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.15.0/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.15.0/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.15.0/manifests/ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.15.0/metadata/annotations.yaml
- operators/mongodb-enterprise/1.15.0/tests/scorecard/config.yaml
> operators mongodb-enterprise (1.15.0)

- operators/keycloak-operator/17.0.0/bundle.Dockerfile
- operators/keycloak-operator/17.0.0/manifests/keycloak-operator.v17.0.0.clusterserviceversion.yaml
- operators/keycloak-operator/17.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml
- operators/keycloak-operator/17.0.0/manifests/keycloakclients.keycloak.org.crd.yaml
- operators/keycloak-operator/17.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml
- operators/keycloak-operator/17.0.0/manifests/keycloaks.keycloak.org.crd.yaml
- operators/keycloak-operator/17.0.0/manifests/keycloakusers.keycloak.org.crd.yaml
- operators/keycloak-operator/17.0.0/metadata/annotations.yaml
Signed-off-by: Jonathan Vila <jvilalop@redhat.com>
* [ X] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [X ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [X ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [X ] Have you tested an update to your Operator when deployed via OLM?
* [ X] Is your …
> operators keycloak-operator (17.0.0)

- operators/external-secrets-operator/0.4.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.4.2/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.4.2/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.4.2/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.4.2/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.4.2/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.4.2/metadata/annotations.yaml
- operators/external-secrets-operator/0.4.2/tests/scorecard/config.yaml
bumping external secrets version to v0.4.2
Signed-off-by: Gustavo Carvalho <gustavo.carvalho@container-solutions.com>
> operators external-secrets-operator (0.4.2)

- operators/trident-operator/22.1.0/clusterrole.yaml
- operators/trident-operator/22.1.0/clusterrolebinding.yaml
- operators/trident-operator/22.1.0/trident-operator.v22.1.0.clusterserviceversion.yaml
- operators/trident-operator/22.1.0/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
- operators/trident-operator/ci.yaml
- operators/trident-operator/trident-operator.package.yaml
> operators [N] [CI] trident-operator (22.1.0)

- operators/opentelemetry-operator/0.43.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.43.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.43.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.43.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.43.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.43.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.43.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.43.0/tests/scorecard/config.yaml
> operators opentelemetry-operator (0.43.0)

- operators/couchbase-enterprise/1.1.0/manifests/couchbase-v1.1.0.clusterserviceversion.yaml
Signed-off-by: Martin Vala <mavala@redhat.com>
--
> operators [O] couchbase-enterprise (1.1.0)

- operators/cloud-native-postgresql/1.13.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.13.0/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.13.0/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.13.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.13.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.13.0/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.13.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.13.0/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.13.0/tests/scorecard/config.yaml
> operators cloud-native-postgresql (1.13.0)

- operators/nfd-operator/0.4.1/manifests/nfd-controller-manager-metrics-service_v1_service.yaml
- operators/nfd-operator/0.4.1/manifests/nfd-manager-config_v1_configmap.yaml
- operators/nfd-operator/0.4.1/manifests/nfd-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/nfd-operator/0.4.1/manifests/nfd.kubernetes.io_nodefeaturediscoveries.yaml
- operators/nfd-operator/0.4.1/manifests/nfd.kubernetes.io_nodefeaturerules.yaml
- operators/nfd-operator/0.4.1/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
- operators/nfd-operator/0.4.1/manifests/topology.node.k8s.io_noderesourcetopologies.yaml
- operators/nfd-operator/0.4.1/metadata/annotations.yaml
- operators/nfd-operator/0.4.1/tests/scorecard/config.yaml
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
--
> operators [R] nfd-operator (0.4.0 0.4.1)

- operators/external-secrets-operator/0.4.3/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.4.3/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.4.3/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.4.3/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.4.3/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.4.3/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.4.3/metadata/annotations.yaml
- operators/external-secrets-operator/0.4.3/tests/scorecard/config.yaml
Bumping external-secrets version to v0.4.3
Signed-off-by: Gustavo Carvalho <gusfcarvalho@gmail.com>
> operators external-secrets-operator (0.4.3)

- operators/fossul-operator/0.4.0/bundle.Dockerfile
- operators/fossul-operator/0.4.0/manifests/fossul-operator.v0.4.0.clusterserviceversion.yaml
- operators/fossul-operator/0.4.0/manifests/fossul.io_backupconfigs.yaml
- operators/fossul-operator/0.4.0/manifests/fossul.io_backups.yaml
- operators/fossul-operator/0.4.0/manifests/fossul.io_backupschedules.yaml
- operators/fossul-operator/0.4.0/manifests/fossul.io_fossuls.yaml
- operators/fossul-operator/0.4.0/manifests/fossul.io_restores.yaml
- operators/fossul-operator/0.4.0/metadata/annotations.yaml
- operators/fossul-operator/ci.yaml
Signed-off-by: ktenzer <ktenzer@redhat.com>
--
> operators [N] [CI] fossul-operator (0.4.0)

- operators/fossul-operator/0.5.0/bundle.Dockerfile
- operators/fossul-operator/0.5.0/manifests/fossul-operator.v0.5.0.clusterserviceversion.yaml
- operators/fossul-operator/0.5.0/manifests/fossul.io_backupconfigs.yaml
- operators/fossul-operator/0.5.0/manifests/fossul.io_backups.yaml
- operators/fossul-operator/0.5.0/manifests/fossul.io_backupschedules.yaml
- operators/fossul-operator/0.5.0/manifests/fossul.io_fossuls.yaml
- operators/fossul-operator/0.5.0/manifests/fossul.io_restores.yaml
- operators/fossul-operator/0.5.0/metadata/annotations.yaml
> operators fossul-operator (0.5.0)

- operators/flux/0.27.0/manifests/alert.crd.yaml
- operators/flux/0.27.0/manifests/bucket.crd.yaml
- operators/flux/0.27.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.27.0/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.27.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.27.0/manifests/flux.v0.27.0.clusterserviceversion.yaml
- operators/flux/0.27.0/manifests/gitrepository.crd.yaml
- operators/flux/0.27.0/manifests/helmchart.crd.yaml
- operators/flux/0.27.0/manifests/helmrelease.crd.yaml
- operators/flux/0.27.0/manifests/helmrepository.crd.yaml
- operators/flux/0.27.0/manifests/imagepolicy.crd.yaml
- operators/flux/0.27.0/manifests/imagerepository.crd.yaml
- operators/flux/0.27.0/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.27.0/manifests/kustomization.crd.yaml
- operators/flux/0.27.0/manifests/notification-controller.service.yaml
- operators/flux/0.27.0/manifests/provider.crd.yaml
- operators/flux/0.27.0/manifests/receiver.crd.yaml
- operators/flux/0.27.0/manifests/source-controller.service.yaml
- operators/flux/0.27.0/manifests/webhook-receiver.service.yaml
- operators/flux/0.27.0/metadata/annotations.yaml
> operators flux (0.27.0)

- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.23.3/victoriametrics-operator.0.23.3.clusterserviceversion.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.23.3)

- operators/external-secrets-operator/0.4.4/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.4.4/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.4.4/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.4.4/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.4.4/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.4.4/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.4.4/metadata/annotations.yaml
- operators/external-secrets-operator/0.4.4/tests/scorecard/config.yaml
bump external-secrets-operator 0.4.4
fixes: https://github.com/external-secrets/external-secrets/issues/746
> operators external-secrets-operator (0.4.4)

- operators/tidb-operator/1.3.0/backups.pingcap.com.crd.yaml
- operators/tidb-operator/1.3.0/backupschedules.pingcap.com.crd.yaml
- operators/tidb-operator/1.3.0/dmclusters.pingcap.com.crd.yaml
- operators/tidb-operator/1.3.0/restores.pingcap.com.crd.yaml
- operators/tidb-operator/1.3.0/tidb-operator.v1.3.0.clusterserviceversion.yaml
- operators/tidb-operator/1.3.0/tidbclusterautoscalers.pingcap.com.crd.yaml
- operators/tidb-operator/1.3.0/tidbclusters.pingcap.com.crd.yaml
- operators/tidb-operator/1.3.0/tidbinitializers.pingcap.com.crd.yaml
- operators/tidb-operator/1.3.0/tidbmonitors.pingcap.com.crd.yaml
- operators/tidb-operator/1.3.0/tidbngmonitorings.pingcap.com.crd.yaml
- operators/tidb-operator/tidb-operator.package.yaml
Signed-off-by: Shiori <sihao.yu@pingcap.com>
* [] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
--
<sup>2</sup> For more information …
> operators tidb-operator (1.3.0)

- operators/pulp-operator/0.7.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.7.1/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.7.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.7.1/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.7.1/manifests/pulp-operator.v0.7.1.clusterserviceversion.yaml
- operators/pulp-operator/0.7.1/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.7.1/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.7.1/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.7.1/metadata/annotations.yaml
- operators/pulp-operator/0.7.1/tests/scorecard/config.yaml
> operators pulp-operator (0.7.1)

- operators/metallb-operator/0.12.0/manifests/metallb-operator.clusterserviceversion.yaml
Adding description and displayNames to CSV.
> operators [N] metallb-operator (0.12.0)

- operators/service-binding-operator/1.0.1/manifests/binding.operators.coreos.com_bindablekinds.yaml
- operators/service-binding-operator/1.0.1/manifests/binding.operators.coreos.com_servicebindings.yaml
- operators/service-binding-operator/1.0.1/manifests/clusterrole-service-binding-controller-role.yaml
- operators/service-binding-operator/1.0.1/manifests/clusterrolebinding-service-binding-controller-rolebinding.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-manager-config_v1_configmap.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-operator.clusterserviceversion.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.0.1/manifests/service-binding-webhook-service_v1_service.yaml
- operators/service-binding-operator/1.0.1/manifests/servicebinding.io_servicebindings.yaml
- operators/service-binding-operator/1.0.1/metadata/annotations.yaml
> operators service-binding-operator (1.0.1)

- operators/clever-operator/0.4.0/bundle.Dockerfile
- operators/clever-operator/0.4.0/manifests/clever-operator-mongodb.crd.yaml
- operators/clever-operator/0.4.0/manifests/clever-operator-mysql.crd.yaml
- operators/clever-operator/0.4.0/manifests/clever-operator-postgresql.crd.yaml
- operators/clever-operator/0.4.0/manifests/clever-operator-pulsar.crd.yaml
- operators/clever-operator/0.4.0/manifests/clever-operator-redis.crd.yaml
- operators/clever-operator/0.4.0/manifests/clever-operator.clusterserviceversion.yaml
- operators/clever-operator/0.4.0/metadata/annotations.yaml
- operators/clever-operator/0.4.0/tests/scorecard/config.yaml
Signed-off-by: Florentin Dubois <florentin.dubois@clever-cloud.com>
--
> operators clever-operator (0.4.0)

- operators/verticadb-operator/1.3.0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/1.3.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/1.3.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/1.3.0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/1.3.0/metadata/annotations.yaml
- operators/verticadb-operator/1.3.0/tests/scorecard/config.yaml
> operators verticadb-operator (1.3.0)

- operators/flux/0.27.2/manifests/alert.crd.yaml
- operators/flux/0.27.2/manifests/bucket.crd.yaml
- operators/flux/0.27.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.27.2/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.27.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.27.2/manifests/flux.v0.27.2.clusterserviceversion.yaml
- operators/flux/0.27.2/manifests/gitrepository.crd.yaml
- operators/flux/0.27.2/manifests/helmchart.crd.yaml
- operators/flux/0.27.2/manifests/helmrelease.crd.yaml
- operators/flux/0.27.2/manifests/helmrepository.crd.yaml
- operators/flux/0.27.2/manifests/imagepolicy.crd.yaml
- operators/flux/0.27.2/manifests/imagerepository.crd.yaml
- operators/flux/0.27.2/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.27.2/manifests/kustomization.crd.yaml
- operators/flux/0.27.2/manifests/notification-controller.service.yaml
- operators/flux/0.27.2/manifests/provider.crd.yaml
- operators/flux/0.27.2/manifests/receiver.crd.yaml
- operators/flux/0.27.2/manifests/source-controller.service.yaml
- operators/flux/0.27.2/manifests/webhook-receiver.service.yaml
- operators/flux/0.27.2/metadata/annotations.yaml
> operators flux (0.27.2)

- operators/cert-manager/1.6.2-rc1/manifests/cert-manager.clusterserviceversion.yaml
Signed-off-by: Richard Wall <richard.wall@jetstack.io>
--
> operators [O] cert-manager (1.6.2-rc1)

- operators/opentelemetry-operator/0.44.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.44.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.44.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.44.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.44.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.44.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.44.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.44.0/tests/scorecard/config.yaml
> operators opentelemetry-operator (0.44.0)

- operators/tf-controller/0.9.0-rc.3/manifests/terraform.crd.yaml
- operators/tf-controller/0.9.0-rc.3/manifests/tf-cluster-reconciler.clusterrolebinding.yaml
- operators/tf-controller/0.9.0-rc.3/manifests/tf-controller.v0.9.0-rc.3.clusterserviceversion.yaml
- operators/tf-controller/0.9.0-rc.3/manifests/tf-leader-election-role.role.yaml
- operators/tf-controller/0.9.0-rc.3/manifests/tf-leader-election-rolebinding.rolebinding.yaml
- operators/tf-controller/0.9.0-rc.3/manifests/tf-manager-role.clusterrole.yaml
- operators/tf-controller/0.9.0-rc.3/manifests/tf-manager-rolebinding.clusterrolebinding.yaml
- operators/tf-controller/0.9.0-rc.3/manifests/tf-runner-role.clusterrole.yaml
- operators/tf-controller/0.9.0-rc.3/manifests/tf-runner-rolebinding.clusterrolebinding.yaml
- operators/tf-controller/0.9.0-rc.3/metadata/annotations.yaml
- operators/tf-controller/ci.yaml
> operators [N] [CI] tf-controller (0.9.0-rc.3)

- operators/camel-k/1.8.1/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.8.1/camel-k.v1.8.1.clusterserviceversion.yaml
- operators/camel-k/1.8.1/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.8.1/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.8.1/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.8.1/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.8.1/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.8.1/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/camel-k.package.yaml
> operators camel-k (1.8.1)

- operators/cass-operator-community/1.10.1/manifests/cass-operator-manager-config_v1_configmap.yaml
- operators/cass-operator-community/1.10.1/manifests/cass-operator-webhook-service_v1_service.yaml
- operators/cass-operator-community/1.10.1/manifests/cass-operator.clusterserviceversion.yaml
- operators/cass-operator-community/1.10.1/manifests/cassandra.datastax.com_cassandradatacenters.yaml
- operators/cass-operator-community/1.10.1/manifests/control.k8ssandra.io_cassandratasks.yaml
- operators/cass-operator-community/1.10.1/metadata/annotations.yaml
- operators/cass-operator-community/1.10.1/tests/scorecard/config.yaml
> operators cass-operator-community (1.10.1)

- operators/argocd-operator/0.2.1/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- operators/argocd-operator/0.2.1/argocd-operator-manager-config_v1_configmap.yaml
- operators/argocd-operator/0.2.1/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/argocd-operator/0.2.1/argocd-operator.v0.2.1.clusterserviceversion.yaml
- operators/argocd-operator/0.2.1/argoproj.io_applications.yaml
- operators/argocd-operator/0.2.1/argoproj.io_applicationsets.yaml
- operators/argocd-operator/0.2.1/argoproj.io_appprojects.yaml
- operators/argocd-operator/0.2.1/argoproj.io_argocdexports.yaml
- operators/argocd-operator/0.2.1/argoproj.io_argocds.yaml
- operators/argocd-operator/argocd-operator.package.yaml
Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>
--
> operators argocd-operator (0.2.1)

- operators/mondoo-operator/0.0.10/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.0.10/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/ci.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
Signed-off-by: Harsha <harshaisgud@gmail.com>
--
> operators [N] [CI] mondoo-operator (0.0.10)

- operators/mongodb-enterprise/1.15.1/manifests/appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.15.1/manifests/database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.15.1/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.15.1/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.15.1/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.15.1/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.15.1/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.15.1/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.15.1/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.15.1/manifests/ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.15.1/metadata/annotations.yaml
- operators/mongodb-enterprise/1.15.1/tests/scorecard/config.yaml
Signed-off-by: Rodrigo Valin <rodrigo.valin@mongodb.com>
--
> operators mongodb-enterprise (1.15.1)

- operators/verticadb-operator/1.3.1/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/1.3.1/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/1.3.1/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/1.3.1/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/1.3.1/metadata/annotations.yaml
- operators/verticadb-operator/1.3.1/tests/scorecard/config.yaml
> operators verticadb-operator (1.3.1)

- operators/kube-green/0.3.1/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml
- operators/kube-green/0.3.1/manifests/kube-green-manager-config_v1_configmap.yaml
- operators/kube-green/0.3.1/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kube-green/0.3.1/manifests/kube-green-webhook-service_v1_service.yaml
- operators/kube-green/0.3.1/manifests/kube-green.clusterserviceversion.yaml
- operators/kube-green/0.3.1/manifests/kube-green.com_sleepinfos.yaml
- operators/kube-green/0.3.1/metadata/annotations.yaml
- operators/kube-green/0.3.1/tests/scorecard/config.yaml
Signed-off-by: Davide Bianchi <bianchidavide12@gmail.com>
--
> operators kube-green (0.3.1)

- operators/mongodb-atlas-kubernetes/0.8.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/0.8.0/manifests/atlas.mongodb.com_atlasclusters.yaml
- operators/mongodb-atlas-kubernetes/0.8.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/0.8.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/0.8.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/0.8.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/0.8.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/0.8.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/0.8.0/tests/scorecard/config.yaml
Signed-off-by: fabritsius <anton_fabritsius@epam.com>
--
> operators mongodb-atlas-kubernetes (0.8.0)

- operators/camel-k/1.8.2/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.8.2/manifests/camel-k.v1.8.2.clusterserviceversion.yaml
- operators/camel-k/1.8.2/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.8.2/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.8.2/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.8.2/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.8.2/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.8.2/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/1.8.2/metadata/annotations.yaml
> operators camel-k (1.8.2)

- operators/netobserv-operator/0.1.1/bundle.Dockerfile
- operators/netobserv-operator/0.1.1/manifests/flows.netobserv.io_flowcollectors.yaml
- operators/netobserv-operator/0.1.1/manifests/netobserv-manager-config_v1_configmap.yaml
- operators/netobserv-operator/0.1.1/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/netobserv-operator/0.1.1/manifests/netobserv-metrics-service_v1_service.yaml
- operators/netobserv-operator/0.1.1/manifests/netobserv-operator.clusterserviceversion.yaml
- operators/netobserv-operator/0.1.1/metadata/annotations.yaml
> operators netobserv-operator (0.1.1)

- operators/couchdb-operator/2.2.2/manifests/backups.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.2/manifests/buckets.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.2/manifests/couchdb-operator.clusterserviceversion.yaml
- operators/couchdb-operator/2.2.2/manifests/couchdbclusters.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.2/manifests/formationlocks.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.2/manifests/formations.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.2/manifests/recipes.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.2/manifests/recipetemplates.couchdb.databases.cloud.ibm.com.crd.yaml
- operators/couchdb-operator/2.2.2/metadata/annotations.yaml
- operators/couchdb-operator/ci.yaml
The update contains:
- security fixes for all containers, provided by the base UBI images.
--
> operators [CI] couchdb-operator (2.2.2)

- operators/wildfly/0.5.3/bundle.Dockerfile
- operators/wildfly/0.5.3/manifests/wildfly-operator.v0.5.3.clusterserviceversion.yaml
- operators/wildfly/0.5.3/manifests/wildflyservers.wildfly.org.crd.yaml
- operators/wildfly/0.5.3/metadata/annotations.yaml
This version replaces the wildfly-operator 0.5.2
Release Notes:
https://github.com/wildfly/wildfly-operator/milestone/9?closed=1
Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>
> operators wildfly (0.5.3)

- operators/instana-agent-operator/2.0.4/manifests/controller-manager-metrics-service_v1_service.yaml
- operators/instana-agent-operator/2.0.4/manifests/instana-agent-operator.clusterserviceversion.yaml
- operators/instana-agent-operator/2.0.4/manifests/instana.io_agents.yaml
- operators/instana-agent-operator/2.0.4/manifests/manager-config_v1_configmap.yaml
- operators/instana-agent-operator/2.0.4/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
- operators/instana-agent-operator/2.0.4/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/instana-agent-operator/2.0.4/manifests/webhook-service_v1_service.yaml
- operators/instana-agent-operator/2.0.4/metadata/annotations.yaml
- operators/instana-agent-operator/2.0.4/metadata/dependencies.yaml
- operators/instana-agent-operator/2.0.4/tests/scorecard/config.yaml
- operators/instana-agent-operator/ci.yaml
Signed-off-by: Torsten Kohn <tkohn@users.noreply.github.com>
--
> operators [CI] instana-agent-operator (2.0.4)

- operators/app-director-operator/0.0.1/Dockerfile
- operators/app-director-operator/0.0.1/manifests/app-director-controller-manager-metrics-service_v1_service.yaml
- operators/app-director-operator/0.0.1/manifests/app-director-manager-config_v1_configmap.yaml
- operators/app-director-operator/0.0.1/manifests/app-director-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/app-director-operator/0.0.1/manifests/app-director-operator.clusterserviceversion.yaml
- operators/app-director-operator/0.0.1/manifests/appdirector.randoli.ca_clusterwideguvnors.yaml
- operators/app-director-operator/0.0.1/manifests/appdirector.randoli.ca_guvnors.yaml
- operators/app-director-operator/0.0.1/metadata/annotations.yaml
- operators/app-director-operator/0.0.1/tests/scorecard/config.yaml
- operators/app-director-operator/ci.yaml
> operators [N] [CI] app-director-operator (0.0.1)

- operators/seldon-operator/1.13.1/manifests/machinelearning.seldon.io_seldondeployments.yaml
- operators/seldon-operator/1.13.1/manifests/seldon-operator.clusterserviceversion.yaml
- operators/seldon-operator/1.13.1/metadata/annotations.yaml
- operators/seldon-operator/1.13.1/tests/scorecard/config.yaml
- operators/seldon-operator/ci.yaml
Update Seldon Community Operator to 1.13.1
Signed-off-by: Rafal Skolasinski <r.j.skolasinski@gmail.com>
> operators [CI] seldon-operator (1.13.1)

- operators/snyk-operator/1.85.2/snyk-operator.v1.85.2.clusterserviceversion.yaml
- operators/snyk-operator/1.85.2/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.85.2)

- operators/storageos/2.5.0/storageos-operator-leader-election_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/storageos/2.5.0/storageos-operator-webhook_v1_service.yaml
- operators/storageos/2.5.0/storageos-operator_v1_configmap.yaml
- operators/storageos/2.5.0/storageos-operator_v1_service.yaml
- operators/storageos/2.5.0/storageos-related-images_v1_configmap.yaml
- operators/storageos/2.5.0/storageos.com_storageosclusters.yaml
- operators/storageos/2.5.0/storageos_metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/storageos/2.5.0/storageos_operator-leader-election_rbac.authorization.k8s.io_v1_role.yaml
- operators/storageos/2.5.0/storageos_operator_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/storageos/2.5.0/storageos_operator_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/storageos/2.5.0/storageos_proxy_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/storageos/2.5.0/storageos_proxy_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/storageos/2.5.0/storageosoperator.clusterserviceversion.yaml
- operators/storageos/2.6.0/storageos-operator-leader-election_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/storageos/2.6.0/storageos-operator-webhook_v1_service.yaml
- operators/storageos/2.6.0/storageos-operator_v1_configmap.yaml
- operators/storageos/2.6.0/storageos-operator_v1_service.yaml
- operators/storageos/2.6.0/storageos-related-images_v1_configmap.yaml
- operators/storageos/2.6.0/storageos.com_storageosclusters.yaml
- operators/storageos/2.6.0/storageos_metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/storageos/2.6.0/storageos_operator-leader-election_rbac.authorization.k8s.io_v1_role.yaml
- operators/storageos/2.6.0/storageos_operator_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/storageos/2.6.0/storageos_operator_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/storageos/2.6.0/storageos_proxy_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/storageos/2.6.0/storageos_proxy_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/storageos/2.6.0/storageosoperator.clusterserviceversion.yaml
- operators/storageos/storageos.package.yaml
Add StorageOS v2.5.0 & v2.6.0
Signed-off-by: David Marchant david@ondat.io
> operators [R] storageos (2.5.0 2.6.0)

- operators/pulp-operator/0.8.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.8.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.8.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.8.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.8.0/manifests/pulp-operator.v0.8.0.clusterserviceversion.yaml
- operators/pulp-operator/0.8.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.8.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.8.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.8.0/metadata/annotations.yaml
- operators/pulp-operator/0.8.0/tests/scorecard/config.yaml
> operators pulp-operator (0.8.0)

- operators/knative-operator/1.3.1/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.3.1/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.3.1/knative-operator-operator-webhook-certs_v1_secret.yaml
- operators/knative-operator/1.3.1/knative-operator-operator-webhook_v1_service.yaml
- operators/knative-operator/1.3.1/knative-operator.v1.3.1.clusterserviceversion.yaml
- operators/knative-operator/1.3.1/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.3.1/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/knative-operator.package.yaml
> operators knative-operator (1.3.1)

- operators/dynatrace-operator/ci.yaml
Signed-off-by: Michael Rynkiewicz <michael.rynkiewicz@dynatrace.com>
--
> operators [CI] dynatrace-operator

- operators/ibmcloud-operator/1.1.0/apiextensions.k8s.io_v1_customresourcedefinition_bindings.ibmcloud.ibm.com.yaml
- operators/ibmcloud-operator/1.1.0/apiextensions.k8s.io_v1_customresourcedefinition_services.ibmcloud.ibm.com.yaml
- operators/ibmcloud-operator/1.1.0/ibmcloud_operator.v1.1.0.clusterserviceversion.yaml
- operators/ibmcloud-operator/ibmcloud-operator.package.yaml
Automated release of IBM Cloud Operator v1.1.0.
> operators ibmcloud-operator (1.1.0)

- operators/integrity-shield-operator/0.3.3/manifests/apis.integrityshield.io_integrityshields.yaml
- operators/integrity-shield-operator/0.3.3/manifests/integrity-shield-operator-controller-manager-metrics-service_v1_service.yaml
- operators/integrity-shield-operator/0.3.3/manifests/integrity-shield-operator-manager-config_v1_configmap.yaml
- operators/integrity-shield-operator/0.3.3/manifests/integrity-shield-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/integrity-shield-operator/0.3.3/manifests/integrity-shield-operator.clusterserviceversion.yaml
- operators/integrity-shield-operator/0.3.3/metadata/annotations.yaml
- operators/integrity-shield-operator/0.3.3/tests/scorecard/config.yaml
Signed-off-by: Ruriko Kudo <rurikudo@ibm.com>
--
> operators integrity-shield-operator (0.3.3)

- operators/kiali/1.47.0/bundle.Dockerfile
- operators/kiali/1.47.0/manifests/kiali.crd.yaml
- operators/kiali/1.47.0/manifests/kiali.v1.47.0.clusterserviceversion.yaml
- operators/kiali/1.47.0/metadata/annotations.yaml
- operators/kiali/1.48.0/bundle.Dockerfile
- operators/kiali/1.48.0/manifests/kiali.crd.yaml
- operators/kiali/1.48.0/manifests/kiali.v1.48.0.clusterserviceversion.yaml
- operators/kiali/1.48.0/metadata/annotations.yaml
> operators [R] kiali (1.47.0 1.48.0)

- operators/flux/0.27.4/manifests/alert.crd.yaml
- operators/flux/0.27.4/manifests/bucket.crd.yaml
- operators/flux/0.27.4/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.27.4/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.27.4/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.27.4/manifests/flux.v0.27.4.clusterserviceversion.yaml
- operators/flux/0.27.4/manifests/gitrepository.crd.yaml
- operators/flux/0.27.4/manifests/helmchart.crd.yaml
- operators/flux/0.27.4/manifests/helmrelease.crd.yaml
- operators/flux/0.27.4/manifests/helmrepository.crd.yaml
- operators/flux/0.27.4/manifests/imagepolicy.crd.yaml
- operators/flux/0.27.4/manifests/imagerepository.crd.yaml
- operators/flux/0.27.4/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.27.4/manifests/kustomization.crd.yaml
- operators/flux/0.27.4/manifests/notification-controller.service.yaml
- operators/flux/0.27.4/manifests/provider.crd.yaml
- operators/flux/0.27.4/manifests/receiver.crd.yaml
- operators/flux/0.27.4/manifests/source-controller.service.yaml
- operators/flux/0.27.4/manifests/webhook-receiver.service.yaml
- operators/flux/0.27.4/metadata/annotations.yaml
> operators flux (0.27.4)

- operators/tf-controller/0.9.0-rc.8/manifests/terraform.crd.yaml
- operators/tf-controller/0.9.0-rc.8/manifests/tf-cluster-reconciler.clusterrolebinding.yaml
- operators/tf-controller/0.9.0-rc.8/manifests/tf-controller.v0.9.0-rc.8.clusterserviceversion.yaml
- operators/tf-controller/0.9.0-rc.8/manifests/tf-leader-election-role.role.yaml
- operators/tf-controller/0.9.0-rc.8/manifests/tf-leader-election-rolebinding.rolebinding.yaml
- operators/tf-controller/0.9.0-rc.8/manifests/tf-manager-role.clusterrole.yaml
- operators/tf-controller/0.9.0-rc.8/manifests/tf-manager-rolebinding.clusterrolebinding.yaml
- operators/tf-controller/0.9.0-rc.8/manifests/tf-runner-role.clusterrole.yaml
- operators/tf-controller/0.9.0-rc.8/manifests/tf-runner-rolebinding.clusterrolebinding.yaml
- operators/tf-controller/0.9.0-rc.8/metadata/annotations.yaml
> operators tf-controller (0.9.0-rc.8)

- operators/telegraf-operator/1.3.5/Dockerfile
- operators/telegraf-operator/1.3.5/manifests/classes-secret.yaml
- operators/telegraf-operator/1.3.5/manifests/telegraf-operator-v1.3.5.clusterserviceversion.yaml
- operators/telegraf-operator/1.3.5/metadata/annotations.yaml
- operators/telegraf-operator/ci.yaml
This adds [telegraf-operator](https://github.com/influxdata/telegraf-operator) to community-operators.
The operator is not created using `operator-sdk` hence this submission is manually created. As mentioned in checklist below, I have tested it multiple times and it worked as expected.
-- …
> operators [N] [CI] telegraf-operator (1.3.5)

- operators/app-director-operator/0.0.2/Dockerfile
- operators/app-director-operator/0.0.2/manifests/app-director-controller-manager-metrics-service_v1_service.yaml
- operators/app-director-operator/0.0.2/manifests/app-director-manager-config_v1_configmap.yaml
- operators/app-director-operator/0.0.2/manifests/app-director-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/app-director-operator/0.0.2/manifests/app-director-operator.clusterserviceversion.yaml
- operators/app-director-operator/0.0.2/manifests/appdirector.randoli.ca_clusterwideguvnors.yaml
- operators/app-director-operator/0.0.2/manifests/appdirector.randoli.ca_guvnors.yaml
- operators/app-director-operator/0.0.2/metadata/annotations.yaml
- operators/app-director-operator/0.0.2/tests/scorecard/config.yaml
Signed-off-by: Rosa Lopes <josue.lopes@randoli.ca>
> operators [R] app-director-operator (0.0.1 0.0.2)

- operators/trident-operator/22.1.1/trident-operator.v22.1.1.clusterserviceversion.yaml
- operators/trident-operator/22.1.1/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
- operators/trident-operator/trident-operator.package.yaml
> operators trident-operator (22.1.1)

- operators/gitlab-runner-operator/1.7.0/bundle.Dockerfile
- operators/gitlab-runner-operator/1.7.0/ci.yaml
- operators/gitlab-runner-operator/1.7.0/manifests/apps.gitlab.com_runners.yaml
- operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml
- operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml
- operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml
- operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-webhook-service_v1_service.yaml
- operators/gitlab-runner-operator/1.7.0/metadata/annotations.yaml
- operators/gitlab-runner-operator/1.7.0/tests/scorecard/config.yaml
Signed-off-by: ggeorgiev_gitlab <ggeorgiev@gitlab.com>
--
> operators [N] [CI] gitlab-runner-operator (1.7.0)

- operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml
> operators [N] gitlab-runner-operator (1.7.0)

- operators/yaks/0.9.0/instances.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.9.0/tests.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.9.0/yaks.v0.9.0.clusterserviceversion.yaml
- operators/yaks/yaks.package.yaml
> operators yaks (0.9.0)

- operators/mongodb-enterprise/1.15.2/manifests/appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.15.2/manifests/database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.15.2/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.15.2/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.15.2/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.15.2/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.15.2/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.15.2/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.15.2/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.15.2/manifests/ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.15.2/metadata/annotations.yaml
- operators/mongodb-enterprise/1.15.2/tests/scorecard/config.yaml
> operators mongodb-enterprise (1.15.2)

- operators/prometheus/0.47.0/prometheusoperator.0.47.0.clusterserviceversion.yaml
Signed-off-by: Zahar Pecherichny <zfrhv2010@gmail.com>
just as mentioned in #942
> operators [O] prometheus (0.47.0)

- operators/mondoo-operator/0.2.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.2.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.2.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.2.0/mondoo-operator-nodes_rbac.authorization.k8s.io_v1_role.yaml
- operators/mondoo-operator/0.2.0/mondoo-operator-nodes_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mondoo-operator/0.2.0/mondoo-operator-nodes_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.0/mondoo-operator-workload_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.2.0/mondoo-operator-workload_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.0/mondoo-operator-workload_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/ci.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
Additionally, adding myself as a reviewer.
> operators [CI] mondoo-operator (0.2.0)

- operators/flux/0.28.3/manifests/alert.crd.yaml
- operators/flux/0.28.3/manifests/bucket.crd.yaml
- operators/flux/0.28.3/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.28.3/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.28.3/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.28.3/manifests/flux.v0.28.3.clusterserviceversion.yaml
- operators/flux/0.28.3/manifests/gitrepository.crd.yaml
- operators/flux/0.28.3/manifests/helmchart.crd.yaml
- operators/flux/0.28.3/manifests/helmrelease.crd.yaml
- operators/flux/0.28.3/manifests/helmrepository.crd.yaml
- operators/flux/0.28.3/manifests/imagepolicy.crd.yaml
- operators/flux/0.28.3/manifests/imagerepository.crd.yaml
- operators/flux/0.28.3/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.28.3/manifests/kustomization.crd.yaml
- operators/flux/0.28.3/manifests/notification-controller.service.yaml
- operators/flux/0.28.3/manifests/provider.crd.yaml
- operators/flux/0.28.3/manifests/receiver.crd.yaml
- operators/flux/0.28.3/manifests/source-controller.service.yaml
- operators/flux/0.28.3/manifests/webhook-receiver.service.yaml
- operators/flux/0.28.3/metadata/annotations.yaml
> operators flux (0.28.3)

- operators/dell-csm-operator/0.1.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/0.1.0/manifests/dell-csm-operator.v0.1.0.clusterserviceversion.yaml
- operators/dell-csm-operator/0.1.0/metadata/annotations.yaml
- operators/dell-csm-operator/ci.yaml
> operators [N] [CI] dell-csm-operator (0.1.0)

- operators/dell-csi-operator/1.7.0/csiisilons.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.7.0/csipowermaxes.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.7.0/csipowermaxrevproxies.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.7.0/csipowerstores.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.7.0/csiunities.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.7.0/csivxflexoses.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.7.0/dell-csi-operator.v1.7.0.clusterserviceversion.yaml
- operators/dell-csi-operator/dell-csi-operator.package.yaml
> operators dell-csi-operator (1.7.0)

- operators/cloud-native-postgresql/1.14.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.14.0/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.14.0/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.14.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.14.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.14.0/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.14.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.14.0/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.14.0/tests/scorecard/config.yaml
> operators cloud-native-postgresql (1.14.0)

- operators/telegraf-operator/1.3.6/Dockerfile
- operators/telegraf-operator/1.3.6/manifests/classes-secret.yaml
- operators/telegraf-operator/1.3.6/manifests/telegraf-operator-v1.3.6.clusterserviceversion.yaml
- operators/telegraf-operator/1.3.6/metadata/annotations.yaml
This is first update to telegraf-operator so I would like to request checking that I am not missing anything required for updating if using the semver mode.
-- …
> operators telegraf-operator (1.3.6)

- operators/klusterlet/0.7.0/klusterlet.v0.7.0.clusterserviceversion.yaml
- operators/klusterlet/0.7.0/operator.open-cluster-management.io_klusterlets.yaml
- operators/klusterlet/klusterlet.package.yaml
> operators klusterlet (0.7.0)

- operators/cluster-manager/0.7.0/cluster-manager.v0.7.0.clusterserviceversion.yaml
- operators/cluster-manager/0.7.0/operator.open-cluster-management.io_clustermanagers.yaml
- operators/cluster-manager/cluster-manger.package.yaml
> operators cluster-manager (0.7.0)

- operators/flux/0.28.4/manifests/alert.crd.yaml
- operators/flux/0.28.4/manifests/bucket.crd.yaml
- operators/flux/0.28.4/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.28.4/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.28.4/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.28.4/manifests/flux.v0.28.4.clusterserviceversion.yaml
- operators/flux/0.28.4/manifests/gitrepository.crd.yaml
- operators/flux/0.28.4/manifests/helmchart.crd.yaml
- operators/flux/0.28.4/manifests/helmrelease.crd.yaml
- operators/flux/0.28.4/manifests/helmrepository.crd.yaml
- operators/flux/0.28.4/manifests/imagepolicy.crd.yaml
- operators/flux/0.28.4/manifests/imagerepository.crd.yaml
- operators/flux/0.28.4/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.28.4/manifests/kustomization.crd.yaml
- operators/flux/0.28.4/manifests/notification-controller.service.yaml
- operators/flux/0.28.4/manifests/provider.crd.yaml
- operators/flux/0.28.4/manifests/receiver.crd.yaml
- operators/flux/0.28.4/manifests/source-controller.service.yaml
- operators/flux/0.28.4/manifests/webhook-receiver.service.yaml
- operators/flux/0.28.4/metadata/annotations.yaml
> operators flux (0.28.4)

- ci/pipeline-config-k8s.yaml
Signature migration, do not forget to upgrade pipeline afterwards.
> Signature migration

- operators/ibm-application-gateway-operator/22.3.0/manifests/ibm-application-gateway-operator-ctrl-mgr-metrics-service_v1_service.yaml
- operators/ibm-application-gateway-operator/22.3.0/manifests/ibm-application-gateway-operator-manager-config_v1_configmap.yaml
- operators/ibm-application-gateway-operator/22.3.0/manifests/ibm-application-gateway-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ibm-application-gateway-operator/22.3.0/manifests/ibm-application-gateway-operator-webhook-service_v1_service.yaml
- operators/ibm-application-gateway-operator/22.3.0/manifests/ibm-application-gateway-operator.clusterserviceversion.yaml
- operators/ibm-application-gateway-operator/22.3.0/manifests/ibm.com_ibmapplicationgateways.yaml
- operators/ibm-application-gateway-operator/22.3.0/metadata/annotations.yaml
- operators/ibm-application-gateway-operator/22.3.0/tests/scorecard/config.yaml
Signed-off-by: SCOTT A. EXTON <scotte@au1.ibm.com>
--
> operators ibm-application-gateway-operator (22.3.0)

- operators/ibm-spectrum-scale-csi-operator/2.5.0/csiscaleoperators.csi.ibm.com.crd.yaml
- operators/ibm-spectrum-scale-csi-operator/2.5.0/ibm-spectrum-scale-csi-operator.v2.5.0.clusterserviceversion.yaml
- operators/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
> operators ibm-spectrum-scale-csi-operator (2.5.0)

- operators/opentelemetry-operator/0.47.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.47.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.47.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.47.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.47.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.47.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.47.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.47.0/tests/scorecard/config.yaml
> operators opentelemetry-operator (0.47.0)

- operators/flux/0.28.5/manifests/alert.crd.yaml
- operators/flux/0.28.5/manifests/bucket.crd.yaml
- operators/flux/0.28.5/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.28.5/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.28.5/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.28.5/manifests/flux.v0.28.5.clusterserviceversion.yaml
- operators/flux/0.28.5/manifests/gitrepository.crd.yaml
- operators/flux/0.28.5/manifests/helmchart.crd.yaml
- operators/flux/0.28.5/manifests/helmrelease.crd.yaml
- operators/flux/0.28.5/manifests/helmrepository.crd.yaml
- operators/flux/0.28.5/manifests/imagepolicy.crd.yaml
- operators/flux/0.28.5/manifests/imagerepository.crd.yaml
- operators/flux/0.28.5/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.28.5/manifests/kustomization.crd.yaml
- operators/flux/0.28.5/manifests/notification-controller.service.yaml
- operators/flux/0.28.5/manifests/provider.crd.yaml
- operators/flux/0.28.5/manifests/receiver.crd.yaml
- operators/flux/0.28.5/manifests/source-controller.service.yaml
- operators/flux/0.28.5/manifests/webhook-receiver.service.yaml
- operators/flux/0.28.5/metadata/annotations.yaml
> operators flux (0.28.5)

- operators/mondoo-operator/0.2.1/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.2.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.2.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.2.1/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.2.1/mondoo-operator-nodes_rbac.authorization.k8s.io_v1_role.yaml
- operators/mondoo-operator/0.2.1/mondoo-operator-nodes_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mondoo-operator/0.2.1/mondoo-operator-nodes_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.1/mondoo-operator-workload_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.2.1/mondoo-operator-workload_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.1/mondoo-operator-workload_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.1/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operators mondoo-operator (0.2.1)

- operators/starboard-operator/0.15.0/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.0/clustercompliancedetailreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.0/clustercompliancereports.v1alpha1.aquasecurity.github.iocrd.yaml
- operators/starboard-operator/0.15.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.0/starboard-operator.v0.15.0.clusterserviceversion.yaml
- operators/starboard-operator/0.15.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.15.0)

- operators/snapscheduler/3.0.0/bundle.Dockerfile
- operators/snapscheduler/3.0.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml
- operators/snapscheduler/3.0.0/manifests/snapscheduler-manager-config_v1_configmap.yaml
- operators/snapscheduler/3.0.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/snapscheduler/3.0.0/manifests/snapscheduler.backube_snapshotschedules.yaml
- operators/snapscheduler/3.0.0/manifests/snapscheduler.clusterserviceversion.yaml
- operators/snapscheduler/3.0.0/metadata/annotations.yaml
- operators/snapscheduler/3.0.0/tests/scorecard/config.yaml
> operators snapscheduler (3.0.0)

- operators/fossul-operator/0.6.0/bundle.Dockerfile
- operators/fossul-operator/0.6.0/manifests/fossul-operator.v0.6.0.clusterserviceversion.yaml
- operators/fossul-operator/0.6.0/manifests/fossul.io_backupconfigs.yaml
- operators/fossul-operator/0.6.0/manifests/fossul.io_backups.yaml
- operators/fossul-operator/0.6.0/manifests/fossul.io_backupschedules.yaml
- operators/fossul-operator/0.6.0/manifests/fossul.io_fossuls.yaml
- operators/fossul-operator/0.6.0/manifests/fossul.io_restores.yaml
- operators/fossul-operator/0.6.0/metadata/annotations.yaml
> operators fossul-operator (0.6.0)

- operators/dynatrace-operator/0.5.0/Dockerfile
- operators/dynatrace-operator/0.5.0/manifests/dynatrace-activegate_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.5.0/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/0.5.0/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/0.5.0/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.5.0/metadata/annotations.yaml
Signed-off-by: Michael Rynkiewicz <michael.rynkiewicz@dynatrace.com>
--
> operators dynatrace-operator (0.5.0)

- operators/starboard-operator/0.15.1/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.1/clustercompliancedetailreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.1/clustercompliancereports.v1alpha1.aquasecurity.github.iocrd.yaml
- operators/starboard-operator/0.15.1/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.1/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.1/starboard-operator.v0.15.1.clusterserviceversion.yaml
- operators/starboard-operator/0.15.1/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.15.1)

- operators/external-secrets-operator/0.5.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.5.0/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.5.0/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.5.0/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.5.0/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.5.0/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.5.0/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.5.0/metadata/annotations.yaml
- operators/external-secrets-operator/0.5.0/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.0
> operators external-secrets-operator (0.5.0)

- operators/instana-agent-operator/2.0.5/manifests/controller-manager-metrics-service_v1_service.yaml
- operators/instana-agent-operator/2.0.5/manifests/instana-agent-operator.clusterserviceversion.yaml
- operators/instana-agent-operator/2.0.5/manifests/instana.io_agents.yaml
- operators/instana-agent-operator/2.0.5/manifests/manager-config_v1_configmap.yaml
- operators/instana-agent-operator/2.0.5/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
- operators/instana-agent-operator/2.0.5/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/instana-agent-operator/2.0.5/manifests/webhook-service_v1_service.yaml
- operators/instana-agent-operator/2.0.5/metadata/annotations.yaml
- operators/instana-agent-operator/2.0.5/metadata/dependencies.yaml
- operators/instana-agent-operator/2.0.5/tests/scorecard/config.yaml
Signed-off-by: Torsten Kohn <tkohn@users.noreply.github.com>
--
> operators instana-agent-operator (2.0.5)

- operators/security-profiles-operator/0.4.2/bundle.Dockerfile
- operators/security-profiles-operator/0.4.2/manifests/metrics-token_v1_secret.yaml
- operators/security-profiles-operator/0.4.2/manifests/security-profiles-operator-profile_v1_configmap.yaml
- operators/security-profiles-operator/0.4.2/manifests/security-profiles-operator.clusterserviceversion.yaml
- operators/security-profiles-operator/0.4.2/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
- operators/security-profiles-operator/0.4.2/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
- operators/security-profiles-operator/0.4.2/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
- operators/security-profiles-operator/0.4.2/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
- operators/security-profiles-operator/0.4.2/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
- operators/security-profiles-operator/0.4.2/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
- operators/security-profiles-operator/0.4.2/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
- operators/security-profiles-operator/0.4.2/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
- operators/security-profiles-operator/0.4.2/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/security-profiles-operator/0.4.2/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/security-profiles-operator/0.4.2/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/security-profiles-operator/0.4.2/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/security-profiles-operator/0.4.2/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
- operators/security-profiles-operator/0.4.2/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/security-profiles-operator/0.4.2/manifests/spo-webhook_v1_serviceaccount.yaml
- operators/security-profiles-operator/0.4.2/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/security-profiles-operator/0.4.2/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/security-profiles-operator/0.4.2/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
- operators/security-profiles-operator/0.4.2/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/security-profiles-operator/0.4.2/manifests/spod_v1_serviceaccount.yaml
- operators/security-profiles-operator/0.4.2/metadata/annotations.yaml
- operators/security-profiles-operator/0.4.2/tests/scorecard/config.yaml
- operators/security-profiles-operator/ci.yaml
Adds the currently latest version of the Security Profiles Operator:
https://github.com/kubernetes-sigs/security-profiles-operator
Signed-off-by: Jakub Hrozek <jhrozek@redhat.com>
-- …
> operators [N] [CI] security-profiles-operator (0.4.2)

- operators/gitlab-operator-kubernetes/0.6.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.6.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.6.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.6.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.6.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.6.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.6.2/tests/scorecard/config.yaml
Signed-off-by: Mitchell Nielsen <me@mitchn.io>
--
> operators gitlab-operator-kubernetes (0.6.2)

- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.48.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.48.0/tests/scorecard/config.yaml
> operators opentelemetry-operator (0.48.0)

- operators/kiali/1.49.0/bundle.Dockerfile
- operators/kiali/1.49.0/manifests/kiali.crd.yaml
- operators/kiali/1.49.0/manifests/kiali.v1.49.0.clusterserviceversion.yaml
- operators/kiali/1.49.0/metadata/annotations.yaml
> operators kiali (1.49.0)

- operators/dynatrace-operator/0.5.1/Dockerfile
- operators/dynatrace-operator/0.5.1/manifests/dynatrace-activegate_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.5.1/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/0.5.1/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/0.5.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.5.1/metadata/annotations.yaml
> operators dynatrace-operator (0.5.1)

- operators/microcks/1.5.1/microcks-operator.v1.5.1.clusterserviceversion.yaml
- operators/microcks/1.5.1/microcksinstall.crd.yaml
- operators/microcks/microcks.package.yaml
> operators microcks (1.5.1)

- operators/starboard-operator/0.15.2/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.2/clustercompliancedetailreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.2/clustercompliancereports.v1alpha1.aquasecurity.github.iocrd.yaml
- operators/starboard-operator/0.15.2/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.2/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.2/starboard-operator.v0.15.2.clusterserviceversion.yaml
- operators/starboard-operator/0.15.2/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/ci.yaml
- operators/starboard-operator/starboard-operator.package.yaml
[ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
[ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
[ ] Have you tested your Operator with all Custom Resource Definitions?
[ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
[ ] Have you considered whether you want use [semantic …
> operators [CI] starboard-operator (0.15.2)

- operators/dell-csm-operator/0.1.0/manifests/dell-csm-operator.v0.1.0.clusterserviceversion.yaml
> operators [N] dell-csm-operator (0.1.0)

- operators/shipwright-operator/0.9.0/manifests/operator.shipwright.io_shipwrightbuilds.yaml
- operators/shipwright-operator/0.9.0/manifests/shipwright-operator-manager-config_v1_configmap.yaml
- operators/shipwright-operator/0.9.0/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/shipwright-operator/0.9.0/manifests/shipwright-operator-metrics-service_v1_service.yaml
- operators/shipwright-operator/0.9.0/manifests/shipwright-operator.clusterserviceversion.yaml
- operators/shipwright-operator/0.9.0/metadata/annotations.yaml
- operators/shipwright-operator/0.9.0/tests/scorecard/config.yaml
Add Shipwright 0.9.0 to the community operators catalog.
--
> operators shipwright-operator (0.9.0)

- operators/mondoo-operator/0.2.3/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.2.3/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.2.3/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.2.3/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.2.3/mondoo-operator-nodes_rbac.authorization.k8s.io_v1_role.yaml
- operators/mondoo-operator/0.2.3/mondoo-operator-nodes_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mondoo-operator/0.2.3/mondoo-operator-nodes_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.3/mondoo-operator-workload_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.2.3/mondoo-operator-workload_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.3/mondoo-operator-workload_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.3/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/ci.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
Bundle for mondoo-operator v0.2.3.
Also update ci.yaml (adding @imilchev).
> operators [CI] mondoo-operator (0.2.3)

- operators/starboard-operator/0.15.3/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.3/clustercompliancedetailreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.3/clustercompliancereports.v1alpha1.aquasecurity.github.iocrd.yaml
- operators/starboard-operator/0.15.3/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.3/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.3/starboard-operator.v0.15.3.clusterserviceversion.yaml
- operators/starboard-operator/0.15.3/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.15.3)

- operators/pulp-operator/ci.yaml
> operators [CI] pulp-operator

- operators/gitlab-operator-kubernetes/0.6.3/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.6.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.6.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.6.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.6.3/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.6.3/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.6.3/tests/scorecard/config.yaml
Signed-off-by: Mitchell Nielsen <me@mitchn.io>
--
> operators gitlab-operator-kubernetes (0.6.3)

- operators/portworx/1.7.1/core_v1_storagecluster_crd.yaml
- operators/portworx/1.7.1/core_v1_storagenode_crd.yaml
- operators/portworx/1.7.1/portworxoperator.clusterserviceversion.yaml
- operators/portworx/portworx.package.yaml
> operators portworx (1.7.1)

- operators/portworx/1.8.0/core_v1_storagecluster_crd.yaml
- operators/portworx/1.8.0/core_v1_storagenode_crd.yaml
- operators/portworx/1.8.0/portworxoperator.clusterserviceversion.yaml
- operators/portworx/portworx.package.yaml
Signed-off-by: Jiafeng Liao <jliao@purestorage.com>
--
> operators portworx (1.8.0)

- operators/starboard-operator/0.15.4/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.4/clustercompliancedetailreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.4/clustercompliancereports.v1alpha1.aquasecurity.github.iocrd.yaml
- operators/starboard-operator/0.15.4/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.4/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.4/starboard-operator.v0.15.4.clusterserviceversion.yaml
- operators/starboard-operator/0.15.4/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.15.4)

- operators/percona-postgresql-operator/1.2.0/percona-postgresql-operator.v1.2.0.clusterserviceversion.yaml
- operators/percona-postgresql-operator/1.2.0/perconapgclusters.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.2.0/pgclusters.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.2.0/pgpolicies.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.2.0/pgreplicas.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.2.0/pgtasks.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/percona-postgresql-operator.package.yaml
> operators percona-postgresql-operator (1.2.0)

- operators/ack-memorydb-controller/ci.yaml
> operators [CI] ack-memorydb-controller

- operators/argocd-operator/0.3.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- operators/argocd-operator/0.3.0/argocd-operator-manager-config_v1_configmap.yaml
- operators/argocd-operator/0.3.0/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/argocd-operator/0.3.0/argocd-operator.v0.3.0.clusterserviceversion.yaml
- operators/argocd-operator/0.3.0/argoproj.io_applications.yaml
- operators/argocd-operator/0.3.0/argoproj.io_applicationsets.yaml
- operators/argocd-operator/0.3.0/argoproj.io_appprojects.yaml
- operators/argocd-operator/0.3.0/argoproj.io_argocdexports.yaml
- operators/argocd-operator/0.3.0/argoproj.io_argocds.yaml
- operators/argocd-operator/argocd-operator.package.yaml
Signed-off-by: ishitasequeira [ishiseq29@gmail.com](mailto:ishiseq29@@gmail.com)
--
> operators argocd-operator (0.3.0)

- operators/mondoo-operator/0.2.4/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.2.4/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.2.4/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.2.4/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.2.4/mondoo-operator-nodes_rbac.authorization.k8s.io_v1_role.yaml
- operators/mondoo-operator/0.2.4/mondoo-operator-nodes_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mondoo-operator/0.2.4/mondoo-operator-nodes_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.4/mondoo-operator-workload_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.2.4/mondoo-operator-workload_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.4/mondoo-operator-workload_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.4/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
Bundle for mondoo-operator v0.2.4.
> operators mondoo-operator (0.2.4)

- operators/knative-operator/1.3.2/manifests/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.3.2/manifests/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.3.2/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
- operators/knative-operator/1.3.2/manifests/knative-operator-operator-webhook_v1_service.yaml
- operators/knative-operator/1.3.2/manifests/knative-operator.v1.3.2.clusterserviceversion.yaml
- operators/knative-operator/1.3.2/manifests/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.3.2/manifests/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.3.2/metadata/annotations.yaml
> operators [R] knative-operator (1.3.2)

- operators/yaks/0.10.0/instances.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.10.0/tests.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.10.0/yaks.v0.10.0.clusterserviceversion.yaml
- operators/yaks/yaks.package.yaml
> operators yaks (0.10.0)

- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.24.0/victoriametrics-operator.0.24.0.clusterserviceversion.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.24.0)

- operators/cloud-native-postgresql/1.15.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.15.0/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.15.0/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.15.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.15.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.15.0/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.15.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.15.0/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.15.0/tests/scorecard/config.yaml
> operators cloud-native-postgresql (1.15.0)

- operators/knative-operator/1.2.0/manifests/knative-operator.v1.2.0.clusterserviceversion.yaml
- operators/knative-operator/1.2.0/tests/scorecard/config.yaml
> operators [N] knative-operator (1.2.0)

- operators/knative-operator/1.2.1/bundle.Dockerfile
- operators/knative-operator/1.2.1/manifests/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.2.1/manifests/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.2.1/manifests/knative-operator.v1.2.1.clusterserviceversion.yaml
- operators/knative-operator/1.2.1/manifests/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.2.1/manifests/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.2.1/metadata/annotations.yaml
- operators/knative-operator/1.2.1/tests/scorecard/config.yaml
- operators/knative-operator/1.2.2/bundle.Dockerfile
- operators/knative-operator/1.2.2/manifests/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.2.2/manifests/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.2.2/manifests/knative-operator.v1.2.2.clusterserviceversion.yaml
- operators/knative-operator/1.2.2/manifests/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.2.2/manifests/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.2.2/metadata/annotations.yaml
- operators/knative-operator/1.2.2/tests/scorecard/config.yaml
> operators [R] knative-operator (1.2.0 1.2.1 1.2.2)

- operators/knative-operator/1.3.2/bundle.Dockerfile
- operators/knative-operator/1.3.2/manifests/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.3.2/manifests/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.3.2/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
- operators/knative-operator/1.3.2/manifests/knative-operator-operator-webhook_v1_service.yaml
- operators/knative-operator/1.3.2/manifests/knative-operator.v1.3.2.clusterserviceversion.yaml
- operators/knative-operator/1.3.2/manifests/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.3.2/manifests/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.3.2/metadata/annotations.yaml
- operators/knative-operator/1.3.2/tests/scorecard/config.yaml
> operators knative-operator (1.3.2)

- operators/knative-operator/1.4.0/bundle.Dockerfile
- operators/knative-operator/1.4.0/manifests/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.4.0/manifests/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.4.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
- operators/knative-operator/1.4.0/manifests/knative-operator-operator-webhook_v1_service.yaml
- operators/knative-operator/1.4.0/manifests/knative-operator.v1.4.0.clusterserviceversion.yaml
- operators/knative-operator/1.4.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.4.0/manifests/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.4.0/metadata/annotations.yaml
- operators/knative-operator/1.4.0/tests/scorecard/config.yaml
> operators knative-operator (1.4.0)

- operators/snyk-operator/1.88.4/snyk-operator.v1.88.4.clusterserviceversion.yaml
- operators/snyk-operator/1.88.4/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.88.4)

- operators/camel-k/1.5.0/metadata/annotations.yaml
- operators/camel-k/1.5.1/metadata/annotations.yaml
- operators/camel-k/1.6.0/metadata/annotations.yaml
- operators/camel-k/1.6.1/metadata/annotations.yaml
- operators/camel-k/1.7.0/metadata/annotations.yaml
- operators/camel-k/1.8.0/metadata/annotations.yaml
- operators/camel-k/1.8.1/metadata/annotations.yaml
- operators/camel-k/1.8.2/metadata/annotations.yaml
- operators/camel-k/1.9.0/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.9.0/manifests/camel-k.v1.9.0.clusterserviceversion.yaml
- operators/camel-k/1.9.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.9.0/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.9.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.9.0/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.9.0/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.9.0/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/1.9.0/metadata/annotations.yaml
- operators/camel-k/1.9.0/tests/scorecard/config.yaml
> operators [R] camel-k (1.5.0 1.5.1 1.6.0 1.6.1 1.7.0 1.8.0 1.8.1 1.8.2 1.9.0)

- operators/grafana-operator/4.3.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml
- operators/grafana-operator/4.3.0/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/4.3.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/4.3.0/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/4.3.0/integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/4.3.0/integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/4.3.0/integreatly.org_grafananotificationchannels.yaml
- operators/grafana-operator/4.3.0/integreatly.org_grafanas.yaml
- operators/grafana-operator/grafana-operator.package.yaml
Signed-off-by: edvin norling <edvin.norling@xenit.se>
--
> operators grafana-operator (4.3.0)

- operators/pulp-operator/0.9.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.9.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.9.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.9.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.9.0/manifests/pulp-operator.v0.9.0.clusterserviceversion.yaml
- operators/pulp-operator/0.9.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.9.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.9.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.9.0/metadata/annotations.yaml
- operators/pulp-operator/0.9.0/tests/scorecard/config.yaml
> operators pulp-operator (0.9.0)

- operators/external-secrets-operator/0.5.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.5.2/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.5.2/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.5.2/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.5.2/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.5.2/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.5.2/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.5.2/metadata/annotations.yaml
- operators/external-secrets-operator/0.5.2/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.2
> operators external-secrets-operator (0.5.2)

- operators/knative-operator/1.4.0/manifests/knative-operator.v1.4.0.clusterserviceversion.yaml
> operators [N] knative-operator (1.4.0)

- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.48.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.48.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.48.0/tests/scorecard/config.yaml
- operators/opentelemetry-operator/0.49.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.49.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.49.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.49.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.49.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.49.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.49.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.49.0/tests/scorecard/config.yaml
> operators opentelemetry-operator (0.49.0)

- operators/splunk/1.1.0/manifests/splunk-operator.clusterserviceversion.yaml
Signed-off-by: vivekr-splunk <94569031+vivekr-splunk@users.noreply.github.com>
--
> operators [N] splunk (1.1.0)

- operators/kiali/1.50.0/bundle.Dockerfile
- operators/kiali/1.50.0/manifests/kiali.crd.yaml
- operators/kiali/1.50.0/manifests/kiali.v1.50.0.clusterserviceversion.yaml
- operators/kiali/1.50.0/metadata/annotations.yaml
> operators kiali (1.50.0)

- operators/trident-operator/22.4.0/trident-operator.v22.4.0.clusterserviceversion.yaml
- operators/trident-operator/22.4.0/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
- operators/trident-operator/trident-operator.package.yaml
> operators trident-operator (22.4.0)

- operators/ecr-secret-operator/0.2.0/manifests/ecr-secret-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ecr-secret-operator/0.2.0/manifests/ecr-secret-operator-manager-config_v1_configmap.yaml
- operators/ecr-secret-operator/0.2.0/manifests/ecr-secret-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ecr-secret-operator/0.2.0/manifests/ecr-secret-operator.clusterserviceversion.yaml
- operators/ecr-secret-operator/0.2.0/manifests/ecr-secret_ecr.mobb.redhat.com_v1alpha1_secret.yaml
- operators/ecr-secret-operator/0.2.0/manifests/ecr.mobb.redhat.com_secrets.yaml
- operators/ecr-secret-operator/0.2.0/manifests/secret-sample_ecr.mobb.redhat.com_v1alpha1_secret.yaml
- operators/ecr-secret-operator/0.2.0/metadata/annotations.yaml
- operators/ecr-secret-operator/0.2.0/tests/scorecard/config.yaml
- operators/ecr-secret-operator/ci.yaml
Signed-off-by: Shaozhen Ding <shading@redhat.com>
--
> operators [N] [CI] ecr-secret-operator (0.2.0)

- operators/verticadb-operator/1.4.0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/1.4.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/1.4.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/1.4.0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/1.4.0/metadata/annotations.yaml
- operators/verticadb-operator/1.4.0/tests/scorecard/config.yaml
* [] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
-- …
> operators verticadb-operator (1.4.0)

- operators/netobserv-operator/0.1.2/bundle.Dockerfile
- operators/netobserv-operator/0.1.2/manifests/flows.netobserv.io_flowcollectors.yaml
- operators/netobserv-operator/0.1.2/manifests/netobserv-manager-config_v1_configmap.yaml
- operators/netobserv-operator/0.1.2/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/netobserv-operator/0.1.2/manifests/netobserv-metrics-service_v1_service.yaml
- operators/netobserv-operator/0.1.2/manifests/netobserv-operator.clusterserviceversion.yaml
- operators/netobserv-operator/0.1.2/metadata/annotations.yaml
> operators netobserv-operator (0.1.2)

- operators/mongodb-enterprise/1.16.0/bundle.Dockerfile
- operators/mongodb-enterprise/1.16.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.16.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.16.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.16.0/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.16.0/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.16.0/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.16.0/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.16.0/metadata/annotations.yaml
- operators/mongodb-enterprise/1.16.0/tests/scorecard/config.yaml
- operators/mongodb-enterprise/ci.yaml
> operators [CI] mongodb-enterprise (1.16.0)

- operators/mondoo-operator/0.2.7/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.2.7/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.2.7/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.2.7/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.2.7/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.7/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.7/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.2.7/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operators mondoo-operator (0.2.7)

- operators/ibm-spectrum-scale-csi-operator/2.5.1/csiscaleoperators.csi.ibm.com.crd.yaml
- operators/ibm-spectrum-scale-csi-operator/2.5.1/ibm-spectrum-scale-csi-operator.v2.5.1.clusterserviceversion.yaml
- operators/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
> operators ibm-spectrum-scale-csi-operator (2.5.1)

- operators/grafana-operator/4.4.1/grafana-operator-controller-manager-metrics-service_v1_service.yaml
- operators/grafana-operator/4.4.1/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/4.4.1/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/4.4.1/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/4.4.1/integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/4.4.1/integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/4.4.1/integreatly.org_grafananotificationchannels.yaml
- operators/grafana-operator/4.4.1/integreatly.org_grafanas.yaml
- operators/grafana-operator/grafana-operator.package.yaml
> operators grafana-operator (4.4.1)

- operators/app-director-operator/0.0.3/Dockerfile
- operators/app-director-operator/0.0.3/manifests/app-director-controller-manager-metrics-service_v1_service.yaml
- operators/app-director-operator/0.0.3/manifests/app-director-manager-config_v1_configmap.yaml
- operators/app-director-operator/0.0.3/manifests/app-director-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/app-director-operator/0.0.3/manifests/app-director-operator.clusterserviceversion.yaml
- operators/app-director-operator/0.0.3/manifests/appdirector.randoli.ca_clusterwideguvnors.yaml
- operators/app-director-operator/0.0.3/manifests/appdirector.randoli.ca_guvnors.yaml
- operators/app-director-operator/0.0.3/metadata/annotations.yaml
- operators/app-director-operator/0.0.3/tests/scorecard/config.yaml
- operators/app-director-operator/ci.yaml
Signed-off-by: Vanessa Rakoczy <vanessa.rakoczy@randoli.ca>
--
> operators [R] [CI] app-director-operator (0.0.2 0.0.3)

- operators/mongodb-atlas-kubernetes/0.8.1/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/0.8.1/manifests/atlas.mongodb.com_atlasclusters.yaml
- operators/mongodb-atlas-kubernetes/0.8.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/0.8.1/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/0.8.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/0.8.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/0.8.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/0.8.1/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/0.8.1/tests/scorecard/config.yaml
Signed-off-by: Igor Karpukhin <karpukhinigor@gmail.com>
--
> operators mongodb-atlas-kubernetes (0.8.1)

- operators/elastic-cloud-eck/2.2.0/agents.agent.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.2.0/apmservers.apm.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.2.0/beats.beat.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.2.0/elastic-cloud-eck.v2.2.0.clusterserviceversion.yaml
- operators/elastic-cloud-eck/2.2.0/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.2.0/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.2.0/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.2.0/kibanas.kibana.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml
Updates ECK Elasticsearch operator to the latest version 2.2.0
> operators elastic-cloud-eck (2.2.0)

- operators/external-secrets-operator/0.5.3/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.5.3/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.5.3/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.5.3/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.5.3/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.5.3/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.5.3/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.5.3/metadata/annotations.yaml
- operators/external-secrets-operator/0.5.3/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.3
> operators external-secrets-operator (0.5.3)

- operators/beegfs-csi-driver-operator/1.2.2/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml
- operators/beegfs-csi-driver-operator/1.2.2/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml
- operators/beegfs-csi-driver-operator/1.2.2/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/beegfs-csi-driver-operator/1.2.2/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml
- operators/beegfs-csi-driver-operator/1.2.2/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml
- operators/beegfs-csi-driver-operator/1.2.2/metadata/annotations.yaml
- operators/beegfs-csi-driver-operator/1.2.2/tests/scorecard/config.yaml
Signed-off-by: Eric Weber <eric.weber2@netapp.com>
--
> operators beegfs-csi-driver-operator (1.2.2)

- operators/meshery-operator/0.0.1/manifests/meshery-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/meshery-operator/0.0.1/manifests/meshery-operator-metrics-service_v1_service.yaml
- operators/meshery-operator/0.0.1/manifests/meshery-operator.clusterserviceversion.yaml
- operators/meshery-operator/0.0.1/manifests/meshery.layer5.io_brokers.yaml
- operators/meshery-operator/0.0.1/manifests/meshery.layer5.io_meshsyncs.yaml
- operators/meshery-operator/0.0.1/metadata/annotations.yaml
- operators/meshery-operator/0.0.1/tests/scorecard/config.yaml
- operators/meshery-operator/ci.yaml
Signed-off-by: aisuko <urakiny@gmail.com>
--
> operators [N] [CI] meshery-operator (0.0.1)

- operators/mondoo-operator/0.2.10/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.2.10/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.2.10/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.2.10/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.2.10/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.10/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.10/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.2.10/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operators mondoo-operator (0.2.10)

- operators/camel-k/1.9.1/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.9.1/manifests/camel-k.v1.9.1.clusterserviceversion.yaml
- operators/camel-k/1.9.1/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.9.1/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.9.1/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.9.1/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.9.1/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.9.1/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/1.9.1/metadata/annotations.yaml
- operators/camel-k/1.9.1/tests/scorecard/config.yaml
> operators camel-k (1.9.1)

- operators/pulp-operator/0.10.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.10.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.10.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.10.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.10.0/manifests/pulp-operator.v0.10.0.clusterserviceversion.yaml
- operators/pulp-operator/0.10.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.10.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.10.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.10.0/metadata/annotations.yaml
- operators/pulp-operator/0.10.0/tests/scorecard/config.yaml
> operators pulp-operator (0.10.0)

- operators/cass-operator-community/1.10.4/manifests/cass-operator-manager-config_v1_configmap.yaml
- operators/cass-operator-community/1.10.4/manifests/cass-operator-webhook-service_v1_service.yaml
- operators/cass-operator-community/1.10.4/manifests/cass-operator.clusterserviceversion.yaml
- operators/cass-operator-community/1.10.4/manifests/cassandra.datastax.com_cassandradatacenters.yaml
- operators/cass-operator-community/1.10.4/manifests/control.k8ssandra.io_cassandratasks.yaml
- operators/cass-operator-community/1.10.4/metadata/annotations.yaml
- operators/cass-operator-community/1.10.4/tests/scorecard/config.yaml
> operators cass-operator-community (1.10.4)

- README.md
**Description**
Update the readme
> :book: update readme with k8s deprecations info

- README.md
**description**
Readme: nit to be less verbose
> Readme: nit to be less verbose

- README.md
Signed-off-by: Camila Macedo <cmacedo@redhat.com>
fix typo-issue README
> fix typo-issue README

- operators/nfs-provisioner-operator/0.0.4/Dockerfile
- operators/nfs-provisioner-operator/0.0.4/manifests/cache.jhouse.com_nfsprovisioners.yaml
- operators/nfs-provisioner-operator/0.0.4/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml
- operators/nfs-provisioner-operator/0.0.4/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/nfs-provisioner-operator/0.0.4/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
- operators/nfs-provisioner-operator/0.0.4/manifests/nfs-provisioner-operator.clusterserviceversion.yaml
- operators/nfs-provisioner-operator/0.0.4/metadata/annotations.yaml
- operators/nfs-provisioner-operator/0.0.4/tests/scorecard/config.yaml
Signed-off-by: jooho <jlee@redhat.com>
* [X ] A quadratic logo
--
> operators nfs-provisioner-operator (0.0.4)

- operators/mondoo-operator/0.2.12/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.2.12/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.2.12/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.2.12/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.2.12/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.12/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.12/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.2.12/mondoo-operator-workload_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.12/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operators mondoo-operator (0.2.12)

- operators/mondoo-operator/0.2.13/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.2.13/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.2.13/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.2.13/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.2.13/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.13/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.13/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.2.13/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operators mondoo-operator (0.2.13)

- operators/mondoo-operator/0.2.14/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.2.14/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.2.14/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.2.14/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.2.14/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.14/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.14/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.2.14/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operators mondoo-operator (0.2.14)

- operators/microcks/1.5.2/microcks-operator.v1.5.2.clusterserviceversion.yaml
- operators/microcks/1.5.2/microcksinstall.crd.yaml
- operators/microcks/microcks.package.yaml
> operators microcks (1.5.2)

- operators/tackle-operator/ci.yaml
> operators [CI] tackle-operator

- operators/mercury-operator/1.0.2/manifests/mercury-operator.v1.0.2.clusterserviceversion.yaml
> operators [N] mercury-operator (1.0.2)

- operators/pulp-operator/0.10.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.10.1/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.10.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.10.1/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.10.1/manifests/pulp-operator.v0.10.1.clusterserviceversion.yaml
- operators/pulp-operator/0.10.1/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.10.1/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.10.1/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.10.1/metadata/annotations.yaml
- operators/pulp-operator/0.10.1/tests/scorecard/config.yaml
> operators pulp-operator (0.10.1)

- operators/tackle-operator/2.0.0-beta.0/manifests/tackle-operator.clusterserviceversion.yaml
- operators/tackle-operator/2.0.0-beta.0/manifests/tackle.konveyor.io_addons.yaml
- operators/tackle-operator/2.0.0-beta.0/manifests/tackle.konveyor.io_tackles.yaml
- operators/tackle-operator/2.0.0-beta.0/metadata/annotations.yaml
> operators tackle-operator (2.0.0-beta.0)

- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.25.0/victoriametrics-operator.0.25.0.clusterserviceversion.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.25.0)

- operators/clever-operator/0.5.1/bundle.Dockerfile
- operators/clever-operator/0.5.1/manifests/clever-operator-config-elasticsearch.crd.yaml
- operators/clever-operator/0.5.1/manifests/clever-operator-config-provider.crd.yaml
- operators/clever-operator/0.5.1/manifests/clever-operator-mongodb.crd.yaml
- operators/clever-operator/0.5.1/manifests/clever-operator-mysql.crd.yaml
- operators/clever-operator/0.5.1/manifests/clever-operator-postgresql.crd.yaml
- operators/clever-operator/0.5.1/manifests/clever-operator-pulsar.crd.yaml
- operators/clever-operator/0.5.1/manifests/clever-operator-redis.crd.yaml
- operators/clever-operator/0.5.1/manifests/clever-operator.clusterserviceversion.yaml
- operators/clever-operator/0.5.1/metadata/annotations.yaml
- operators/clever-operator/0.5.1/tests/scorecard/config.yaml
Signed-off-by: Florentin Dubois <florentin.dubois@clever-cloud.com>
--
> operators clever-operator (0.5.1)

- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.25.1/victoriametrics-operator.0.25.1.clusterserviceversion.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operators victoriametrics-operator (0.25.1)

- operators/ovms-operator/1.0.0/Dockerfile
- operators/ovms-operator/1.0.0/manifests/intel.com_model_servers.yaml
- operators/ovms-operator/1.0.0/manifests/openvino-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ovms-operator/1.0.0/manifests/openvino-operator-manager-config_v1_configmap.yaml
- operators/ovms-operator/1.0.0/manifests/openvino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ovms-operator/1.0.0/manifests/openvino-operator.clusterserviceversion.yaml
- operators/ovms-operator/1.0.0/metadata/annotations.yaml
- operators/ovms-operator/1.0.0/tests/scorecard/config.yaml
- operators/ovms-operator/ovms-operator-package.yaml
Signed-off-by: rasapala <rafal.a.sapala@intel.com>
--
> operators ovms-operator (1.0.0)

- operators/mongodb-atlas-kubernetes/1.0.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/1.0.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/1.0.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/1.0.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/1.0.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/1.0.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/1.0.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/1.0.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/1.0.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/1.0.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/1.0.0/tests/scorecard/config.yaml
Signed-off-by: fabritsius <anton_fabritsius@epam.com>
--
> operators mongodb-atlas-kubernetes (1.0.0)

- operators/camel-k/1.9.2/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.9.2/manifests/camel-k.v1.9.2.clusterserviceversion.yaml
- operators/camel-k/1.9.2/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.9.2/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.9.2/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.9.2/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.9.2/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.9.2/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/1.9.2/metadata/annotations.yaml
- operators/camel-k/1.9.2/tests/scorecard/config.yaml
> operators camel-k (1.9.2)

- operators/keda/2.7.1/manifests/keda.sh_clustertriggerauthentications.yaml
- operators/keda/2.7.1/manifests/keda.sh_kedacontrollers.yaml
- operators/keda/2.7.1/manifests/keda.sh_scaledjobs.yaml
- operators/keda/2.7.1/manifests/keda.sh_scaledobjects.yaml
- operators/keda/2.7.1/manifests/keda.sh_triggerauthentications.yaml
- operators/keda/2.7.1/manifests/keda.v2.7.1.clusterserviceversion.yaml
- operators/keda/2.7.1/metadata/annotations.yaml
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>
--
> operators keda (2.7.1)

- operators/datadog-operator/0.8.0/manifests/datadog-operator.clusterserviceversion.yaml
- operators/datadog-operator/0.8.0/manifests/datadoghq.com_datadogagents.yaml
- operators/datadog-operator/0.8.0/manifests/datadoghq.com_datadogmetrics.yaml
- operators/datadog-operator/0.8.0/manifests/datadoghq.com_datadogmonitors.yaml
- operators/datadog-operator/0.8.0/metadata/annotations.yaml
- operators/datadog-operator/0.8.0/tests/scorecard/config.yaml
Signed-off-by: Vincent Boulineau <vincent.boulineau@datadoghq.com>
--
> operators datadog-operator (0.8.0)

- operators/mondoo-operator/0.2.15/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.2.15/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.2.15/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.2.15/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.2.15/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.2.15/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.2.15/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.2.15/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operators mondoo-operator (0.2.15)

- operators/snyk-operator/1.90.1/snyk-operator.v1.90.1.clusterserviceversion.yaml
- operators/snyk-operator/1.90.1/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.90.1)

- operators/flux/0.30.2/manifests/alert.crd.yaml
- operators/flux/0.30.2/manifests/bucket.crd.yaml
- operators/flux/0.30.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.30.2/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.30.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.30.2/manifests/flux.v0.30.2.clusterserviceversion.yaml
- operators/flux/0.30.2/manifests/gitrepository.crd.yaml
- operators/flux/0.30.2/manifests/helmchart.crd.yaml
- operators/flux/0.30.2/manifests/helmrelease.crd.yaml
- operators/flux/0.30.2/manifests/helmrepository.crd.yaml
- operators/flux/0.30.2/manifests/imagepolicy.crd.yaml
- operators/flux/0.30.2/manifests/imagerepository.crd.yaml
- operators/flux/0.30.2/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.30.2/manifests/kustomization.crd.yaml
- operators/flux/0.30.2/manifests/notification-controller.service.yaml
- operators/flux/0.30.2/manifests/provider.crd.yaml
- operators/flux/0.30.2/manifests/receiver.crd.yaml
- operators/flux/0.30.2/manifests/source-controller.service.yaml
- operators/flux/0.30.2/manifests/webhook-receiver.service.yaml
- operators/flux/0.30.2/metadata/annotations.yaml
> operators flux (0.30.2)

- operators/zookeeper-operator/0.10.3/bundle.Dockerfile
- operators/zookeeper-operator/0.10.3/manifests/zookeeper-operator-controller-manager-metrics-service_v1_service.yaml
- operators/zookeeper-operator/0.10.3/manifests/zookeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/zookeeper-operator/0.10.3/manifests/zookeeper-operator.clusterserviceversion.yaml
- operators/zookeeper-operator/0.10.3/manifests/zookeeper.streamnative.io_zookeeperclusters.yaml
- operators/zookeeper-operator/0.10.3/metadata/annotations.yaml
- operators/zookeeper-operator/0.10.3/tests/scorecard/config.yaml
> operators [N] zookeeper-operator (0.10.3)

- operators/bookkeeper-operator/0.10.3/bundle.Dockerfile
- operators/bookkeeper-operator/0.10.3/manifests/bookkeeper-operator-controller-manager-metrics-service_v1_service.yaml
- operators/bookkeeper-operator/0.10.3/manifests/bookkeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bookkeeper-operator/0.10.3/manifests/bookkeeper-operator.clusterserviceversion.yaml
- operators/bookkeeper-operator/0.10.3/manifests/bookkeeper.streamnative.io_bookkeeperclusters.yaml
- operators/bookkeeper-operator/0.10.3/metadata/annotations.yaml
- operators/bookkeeper-operator/0.10.3/tests/scorecard/config.yaml
> operators [N] bookkeeper-operator (0.10.3)

- operators/pulsar-operator/0.10.3/bundle.Dockerfile
- operators/pulsar-operator/0.10.3/manifests/pulsar-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulsar-operator/0.10.3/manifests/pulsar-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulsar-operator/0.10.3/manifests/pulsar-operator-pulsar-broker_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulsar-operator/0.10.3/manifests/pulsar-operator.clusterserviceversion.yaml
- operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsarbrokers.yaml
- operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsarconnections.yaml
- operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsarnamespaces.yaml
- operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsarpermissions.yaml
- operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsarproxies.yaml
- operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsartenants.yaml
- operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsartopics.yaml
- operators/pulsar-operator/0.10.3/metadata/annotations.yaml
- operators/pulsar-operator/0.10.3/tests/scorecard/config.yaml
> operators [N] pulsar-operator (0.10.3)

- operators/intel-device-plugins-operator/0.20.0/manifests/intel-device-plugins-operator.clusterserviceversion.yaml
- operators/intel-device-plugins-operator/0.24.0/metadata/annotations.yaml
Signed-off-by: Martin Vala <mavala@redhat.com>
--
> operators [R] intel-device-plugins-operator (0.20.0 0.24.0)

- operators/kiali/1.51.0/bundle.Dockerfile
- operators/kiali/1.51.0/manifests/kiali.crd.yaml
- operators/kiali/1.51.0/manifests/kiali.v1.51.0.clusterserviceversion.yaml
- operators/kiali/1.51.0/metadata/annotations.yaml
> operators kiali (1.51.0)

- operators/clever-operator/0.5.2/bundle.Dockerfile
- operators/clever-operator/0.5.2/manifests/clever-operator-config-elasticsearch.crd.yaml
- operators/clever-operator/0.5.2/manifests/clever-operator-config-provider.crd.yaml
- operators/clever-operator/0.5.2/manifests/clever-operator-mongodb.crd.yaml
- operators/clever-operator/0.5.2/manifests/clever-operator-mysql.crd.yaml
- operators/clever-operator/0.5.2/manifests/clever-operator-postgresql.crd.yaml
- operators/clever-operator/0.5.2/manifests/clever-operator-pulsar.crd.yaml
- operators/clever-operator/0.5.2/manifests/clever-operator-redis.crd.yaml
- operators/clever-operator/0.5.2/manifests/clever-operator.clusterserviceversion.yaml
- operators/clever-operator/0.5.2/metadata/annotations.yaml
- operators/clever-operator/0.5.2/tests/scorecard/config.yaml
Signed-off-by: Florentin Dubois <florentin.dubois@clever-cloud.com>
--
> operators clever-operator (0.5.2)

- operators/external-secrets-operator/0.5.4/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.5.4/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.5.4/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.5.4/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.5.4/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.5.4/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.5.4/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.5.4/metadata/annotations.yaml
- operators/external-secrets-operator/0.5.4/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.4
> operators external-secrets-operator (0.5.4)

- operators/snyk-operator/1.90.2/snyk-operator.v1.90.2.clusterserviceversion.yaml
- operators/snyk-operator/1.90.2/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.90.2)

- operators/cloud-native-postgresql/1.15.1/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.15.1/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.15.1/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.15.1/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.15.1/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.15.1/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.15.1/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.15.1/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.15.1/tests/scorecard/config.yaml
> operators cloud-native-postgresql (1.15.1)

- operators/gitlab-runner-operator/1.9.0/bundle.Dockerfile
- operators/gitlab-runner-operator/1.9.0/manifests/apps.gitlab.com_runners.yaml
- operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml
- operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml
- operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml
- operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-webhook-service_v1_service.yaml
- operators/gitlab-runner-operator/1.9.0/metadata/annotations.yaml
- operators/gitlab-runner-operator/1.9.0/tests/scorecard/config.yaml
> operators gitlab-runner-operator (1.9.0)

- operators/bookkeeper-operator/0.11.0/bundle.Dockerfile
- operators/bookkeeper-operator/0.11.0/manifests/bookkeeper-operator-controller-manager-metrics-service_v1_service.yaml
- operators/bookkeeper-operator/0.11.0/manifests/bookkeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bookkeeper-operator/0.11.0/manifests/bookkeeper-operator.clusterserviceversion.yaml
- operators/bookkeeper-operator/0.11.0/manifests/bookkeeper.streamnative.io_bookkeeperclusters.yaml
- operators/bookkeeper-operator/0.11.0/metadata/annotations.yaml
- operators/bookkeeper-operator/0.11.0/tests/scorecard/config.yaml
> operators bookkeeper-operator (0.11.0)

- operators/pulsar-operator/0.11.0/bundle.Dockerfile
- operators/pulsar-operator/0.11.0/manifests/pulsar-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulsar-operator/0.11.0/manifests/pulsar-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulsar-operator/0.11.0/manifests/pulsar-operator-pulsar-broker_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulsar-operator/0.11.0/manifests/pulsar-operator.clusterserviceversion.yaml
- operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsarbrokers.yaml
- operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsarconnections.yaml
- operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsarnamespaces.yaml
- operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsarpermissions.yaml
- operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsarproxies.yaml
- operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsartenants.yaml
- operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsartopics.yaml
- operators/pulsar-operator/0.11.0/metadata/annotations.yaml
- operators/pulsar-operator/0.11.0/tests/scorecard/config.yaml
> operators pulsar-operator (0.11.0)

- operators/starboard-operator/0.15.6/ciskubebenchreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.6/clustercompliancedetailreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.6/clustercompliancereports.v1alpha1.aquasecurity.github.iocrd.yaml
- operators/starboard-operator/0.15.6/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.6/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/0.15.6/starboard-operator.v0.15.4.clusterserviceversion.yaml
- operators/starboard-operator/0.15.6/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/starboard-operator/starboard-operator.package.yaml
> operators starboard-operator (0.15.6)

- operators/external-secrets-operator/0.5.6/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.5.6/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.5.6/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.5.6/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.5.6/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.5.6/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.5.6/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.5.6/metadata/annotations.yaml
- operators/external-secrets-operator/0.5.6/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.6
> operators external-secrets-operator (0.5.6)

- operators/telegraf-operator/1.3.7/Dockerfile
- operators/telegraf-operator/1.3.7/manifests/classes-secret.yaml
- operators/telegraf-operator/1.3.7/manifests/telegraf-operator-v1.3.7.clusterserviceversion.yaml
- operators/telegraf-operator/1.3.7/metadata/annotations.yaml
Update to new release of telegraf-operator.
--
> operators telegraf-operator (1.3.7)

- operators/knative-operator/1.5.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.5.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.5.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.5.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.5.0/manifests/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.5.0/manifests/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.5.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
- operators/knative-operator/1.5.0/manifests/knative-operator-operator-webhook_v1_service.yaml
- operators/knative-operator/1.5.0/manifests/knative-operator.v1.5.0.clusterserviceversion.yaml
- operators/knative-operator/1.5.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.5.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.5.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.5.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.5.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.5.0/manifests/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.5.0/metadata/annotations.yaml
- operators/knative-operator/1.5.0/tests/scorecard/config.yaml
> operators knative-operator (1.5.0)

- operators/pulp-operator/0.11.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.11.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.11.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.11.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.11.0/manifests/pulp-operator.v0.11.0.clusterserviceversion.yaml
- operators/pulp-operator/0.11.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.11.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.11.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.11.0/metadata/annotations.yaml
- operators/pulp-operator/0.11.0/tests/scorecard/config.yaml
> operators pulp-operator (0.11.0)

- operators/shipwright-operator/0.10.0/manifests/operator.shipwright.io_shipwrightbuilds.yaml
- operators/shipwright-operator/0.10.0/manifests/shipwright-operator-manager-config_v1_configmap.yaml
- operators/shipwright-operator/0.10.0/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/shipwright-operator/0.10.0/manifests/shipwright-operator-metrics-service_v1_service.yaml
- operators/shipwright-operator/0.10.0/manifests/shipwright-operator.clusterserviceversion.yaml
- operators/shipwright-operator/0.10.0/metadata/annotations.yaml
- operators/shipwright-operator/0.10.0/tests/scorecard/config.yaml
Add Shipwright v0.10.0 to the k8s community operators catalog.
--
> operators shipwright-operator (0.10.0)

- operators/verticadb-operator/1.5.0/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/1.5.0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/1.5.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/1.5.0/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/verticadb-operator/1.5.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/1.5.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/1.5.0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/1.5.0/metadata/annotations.yaml
- operators/verticadb-operator/1.5.0/tests/scorecard/config.yaml
> operators verticadb-operator (1.5.0)

- operators/tackle-operator/2.0.0-beta.1/manifests/tackle-operator.clusterserviceversion.yaml
- operators/tackle-operator/2.0.0-beta.1/manifests/tackle.konveyor.io_addons.yaml
- operators/tackle-operator/2.0.0-beta.1/manifests/tackle.konveyor.io_tackles.yaml
- operators/tackle-operator/2.0.0-beta.1/metadata/annotations.yaml
> operators tackle-operator (2.0.0-beta.1)

- operators/service-binding-operator/1.1.0/manifests/binding.operators.coreos.com_bindablekinds.yaml
- operators/service-binding-operator/1.1.0/manifests/binding.operators.coreos.com_servicebindings.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-manager-config_v1_configmap.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-operator.clusterserviceversion.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.0/manifests/service-binding-webhook-service_v1_service.yaml
- operators/service-binding-operator/1.1.0/manifests/servicebinding.io_clusterworkloadresourcemappings.yaml
- operators/service-binding-operator/1.1.0/manifests/servicebinding.io_servicebindings.yaml
- operators/service-binding-operator/1.1.0/metadata/annotations.yaml
Creating a release for SBO v1.1.0
Signed-off-by: shruthihub <shruthi.shruthz@gmail.com>
--
> operators service-binding-operator (1.1.0)

- operators/service-binding-operator/1.1.0/manifests/service-binding-operator.clusterserviceversion.yaml
> operators [O] service-binding-operator (1.1.0)

- operators/pulp-operator/0.11.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.11.1/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.11.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.11.1/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.11.1/manifests/pulp-operator.v0.11.1.clusterserviceversion.yaml
- operators/pulp-operator/0.11.1/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.11.1/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.11.1/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.11.1/metadata/annotations.yaml
- operators/pulp-operator/0.11.1/tests/scorecard/config.yaml
> operators pulp-operator (0.11.1)

- operators/snyk-operator/1.92.0/snyk-operator.v1.92.0.clusterserviceversion.yaml
- operators/snyk-operator/1.92.0/snykmonitors.charts.helm.k8s.io.crd.yaml
- operators/snyk-operator/snyk-operator.package.yaml
> operators snyk-operator (1.92.0)

- operators/project-quay/3.7.1/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.7.1/quayecosystems.crd.yaml
- operators/project-quay/3.7.1/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
* Adds Quay 3.7.1
* Identical to https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1281
> operators project-quay (3.7.1)

- operators/kiali/1.52.0/bundle.Dockerfile
- operators/kiali/1.52.0/manifests/kiali.crd.yaml
- operators/kiali/1.52.0/manifests/kiali.v1.52.0.clusterserviceversion.yaml
- operators/kiali/1.52.0/metadata/annotations.yaml
> operators kiali (1.52.0)

- operators/opentelemetry-operator/ci.yaml
> Add pavolloffay to reviewers in OTEL operator

- operators/mondoo-operator/0.4.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.4.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.4.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.4.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.4.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.4.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.4.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.4.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operators mondoo-operator (0.4.0)

- operators/tackle-operator/2.0.0/manifests/tackle-operator.clusterserviceversion.yaml
- operators/tackle-operator/2.0.0/manifests/tackle.konveyor.io_addons.yaml
- operators/tackle-operator/2.0.0/manifests/tackle.konveyor.io_tackles.yaml
- operators/tackle-operator/2.0.0/metadata/annotations.yaml
- operators/tackle-operator/ci.yaml
> operators [CI] tackle-operator (2.0.0)

- operators/pulp-operator/0.12.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.12.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.12.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.12.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.12.0/manifests/pulp-operator.v0.12.0.clusterserviceversion.yaml
- operators/pulp-operator/0.12.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.12.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.12.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.12.0/metadata/annotations.yaml
- operators/pulp-operator/0.12.0/tests/scorecard/config.yaml
> operators pulp-operator (0.12.0)

- operators/ack-emrcontainers-controller/ci.yaml
> operators [CI] ack-emrcontainers-controller

- operators/hazelcast-platform-operator/ci.yaml
> operators [CI] hazelcast-platform-operator

- operators/service-binding-operator/ci.yaml
> operators [CI] service-binding-operator

- operators/telegraf-operator/1.3.8/Dockerfile
- operators/telegraf-operator/1.3.8/manifests/classes-secret.yaml
- operators/telegraf-operator/1.3.8/manifests/telegraf-operator-v1.3.8.clusterserviceversion.yaml
- operators/telegraf-operator/1.3.8/metadata/annotations.yaml
> operators telegraf-operator (1.3.8)

- operators/service-binding-operator/1.1.1/manifests/binding.operators.coreos.com_bindablekinds.yaml
- operators/service-binding-operator/1.1.1/manifests/binding.operators.coreos.com_servicebindings.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-clusterworkloadresourcemappings-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-clusterworkloadresourcemappings-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-manager-config_v1_configmap.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-operator.clusterserviceversion.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.1.1/manifests/service-binding-webhook-service_v1_service.yaml
- operators/service-binding-operator/1.1.1/manifests/servicebinding.io_clusterworkloadresourcemappings.yaml
- operators/service-binding-operator/1.1.1/manifests/servicebinding.io_servicebindings.yaml
- operators/service-binding-operator/1.1.1/metadata/annotations.yaml
Creating a PR for Release of SBO - v1.1.1
Signed-off-by: shruthihub <shruthi.shruthz@gmail.com>
--
> operators service-binding-operator (1.1.1)

- operators/mondoo-operator/0.4.2/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.4.2/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.4.2/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.4.2/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.4.2/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.4.2/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.4.2/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.4.2/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operators mondoo-operator (0.4.2)

- operators/external-secrets-operator/0.5.7/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.5.7/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.5.7/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.5.7/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.5.7/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.5.7/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.5.7/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.5.7/metadata/annotations.yaml
- operators/external-secrets-operator/0.5.7/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.7
> operators external-secrets-operator (0.5.7)

- operators/portworx/1.8.1/core_v1_storagecluster_crd.yaml
- operators/portworx/1.8.1/core_v1_storagenode_crd.yaml
- operators/portworx/1.8.1/portworxoperator.clusterserviceversion.yaml
- operators/portworx/portworx.package.yaml
Signed-off-by: Jiafeng Liao <jliao@purestorage.com>
--
> operators portworx (1.8.1)

- operators/project-quay/3.7.2/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.7.2/quayecosystems.crd.yaml
- operators/project-quay/3.7.2/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Copy of https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1325
> operators project-quay (3.7.2)

- operators/dynatrace-operator/0.7.0/Dockerfile
- operators/dynatrace-operator/0.7.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/0.7.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/0.7.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml
- operators/dynatrace-operator/0.7.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/dynatrace-operator/0.7.0/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.7.0/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/0.7.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/0.7.0/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/0.7.0/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.7.0/metadata/annotations.yaml
> operators dynatrace-operator (0.7.0)

- operators/ibm-spectrum-scale-csi-operator/2.6.0/csiscaleoperators.csi.ibm.com.crd.yaml
- operators/ibm-spectrum-scale-csi-operator/2.6.0/ibm-spectrum-scale-csi-operator.v2.6.0.clusterserviceversion.yaml
- operators/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
> operator ibm-spectrum-scale-csi-operator (2.6.0)

- operators/kubernetes-imagepuller-operator/1.0.1/che.eclipse.org_kubernetesimagepullers_crd.yaml
- operators/kubernetes-imagepuller-operator/1.0.1/controller-manager-metrics-service_v1_service.yaml
- operators/kubernetes-imagepuller-operator/1.0.1/kubernetes-imagepuller-operator.v1.0.1.clusterserviceversion.yaml
- operators/kubernetes-imagepuller-operator/1.0.1/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: David Kwon <dakwon@redhat.com>
--
> operator kubernetes-imagepuller-operator (1.0.1)

- operators/mongodb-enterprise/1.16.2/bundle.Dockerfile
- operators/mongodb-enterprise/1.16.2/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.16.2/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.16.2/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.2/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.2/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.2/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.16.2/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.16.2/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.16.2/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.16.2/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.16.2/metadata/annotations.yaml
- operators/mongodb-enterprise/1.16.2/tests/scorecard/config.yaml
> operator mongodb-enterprise (1.16.2)

- operators/netobserv-operator/0.1.3/bundle.Dockerfile
- operators/netobserv-operator/0.1.3/manifests/flows.netobserv.io_flowcollectors.yaml
- operators/netobserv-operator/0.1.3/manifests/netobserv-manager-config_v1_configmap.yaml
- operators/netobserv-operator/0.1.3/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/netobserv-operator/0.1.3/manifests/netobserv-metrics-service_v1_service.yaml
- operators/netobserv-operator/0.1.3/manifests/netobserv-operator.clusterserviceversion.yaml
- operators/netobserv-operator/0.1.3/metadata/annotations.yaml
> operator netobserv-operator (0.1.3)

- operators/zookeeper-operator/0.11.5/bundle.Dockerfile
- operators/zookeeper-operator/0.11.5/manifests/zookeeper-operator-controller-manager-metrics-service_v1_service.yaml
- operators/zookeeper-operator/0.11.5/manifests/zookeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/zookeeper-operator/0.11.5/manifests/zookeeper-operator.clusterserviceversion.yaml
- operators/zookeeper-operator/0.11.5/manifests/zookeeper.streamnative.io_zookeeperclusters.yaml
- operators/zookeeper-operator/0.11.5/metadata/annotations.yaml
- operators/zookeeper-operator/0.11.5/tests/scorecard/config.yaml
> operator zookeeper-operator (0.11.5)

- operators/bookkeeper-operator/0.11.5/bundle.Dockerfile
- operators/bookkeeper-operator/0.11.5/manifests/bookkeeper-operator-controller-manager-metrics-service_v1_service.yaml
- operators/bookkeeper-operator/0.11.5/manifests/bookkeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bookkeeper-operator/0.11.5/manifests/bookkeeper-operator.clusterserviceversion.yaml
- operators/bookkeeper-operator/0.11.5/manifests/bookkeeper.streamnative.io_bookkeeperclusters.yaml
- operators/bookkeeper-operator/0.11.5/metadata/annotations.yaml
- operators/bookkeeper-operator/0.11.5/tests/scorecard/config.yaml
> operator bookkeeper-operator (0.11.5)

- operators/verticadb-operator/1.6.0/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/1.6.0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/1.6.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/1.6.0/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/verticadb-operator/1.6.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/1.6.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/1.6.0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/1.6.0/metadata/annotations.yaml
- operators/verticadb-operator/1.6.0/tests/scorecard/config.yaml
Signed-off-by: Matt Spilchen <matt.spilchen@microfocus.com>
--
> operator verticadb-operator (1.6.0)

- operators/flux/0.31.3/manifests/alert.crd.yaml
- operators/flux/0.31.3/manifests/bucket.crd.yaml
- operators/flux/0.31.3/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.31.3/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.31.3/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.31.3/manifests/flux.v0.31.3.clusterserviceversion.yaml
- operators/flux/0.31.3/manifests/gitrepository.crd.yaml
- operators/flux/0.31.3/manifests/helmchart.crd.yaml
- operators/flux/0.31.3/manifests/helmrelease.crd.yaml
- operators/flux/0.31.3/manifests/helmrepository.crd.yaml
- operators/flux/0.31.3/manifests/imagepolicy.crd.yaml
- operators/flux/0.31.3/manifests/imagerepository.crd.yaml
- operators/flux/0.31.3/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.31.3/manifests/kustomization.crd.yaml
- operators/flux/0.31.3/manifests/notification-controller.service.yaml
- operators/flux/0.31.3/manifests/provider.crd.yaml
- operators/flux/0.31.3/manifests/receiver.crd.yaml
- operators/flux/0.31.3/manifests/source-controller.service.yaml
- operators/flux/0.31.3/manifests/webhook-receiver.service.yaml
- operators/flux/0.31.3/metadata/annotations.yaml
- operators/flux/ci.yaml
> operator [CI] flux (0.31.3)

- operators/falcon-operator/0.5.4/manifests/falcon-operator-controller-manager-metrics-service_v1_service.yaml
- operators/falcon-operator/0.5.4/manifests/falcon-operator-manager-config_v1_configmap.yaml
- operators/falcon-operator/0.5.4/manifests/falcon-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/falcon-operator/0.5.4/manifests/falcon-operator.clusterserviceversion.yaml
- operators/falcon-operator/0.5.4/manifests/falcon.crowdstrike.com_falconcontainers.yaml
- operators/falcon-operator/0.5.4/manifests/falcon.crowdstrike.com_falconnodesensors.yaml
- operators/falcon-operator/0.5.4/metadata/annotations.yaml
- operators/falcon-operator/0.5.4/tests/scorecard/config.yaml
Signed-off-by: Simon Lukasik <simon.lukasik@crowdstrike.com>
--
> operator falcon-operator (0.5.4)

- operators/pulp-operator/0.13.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.13.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.13.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.13.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.13.0/manifests/pulp-operator.v0.13.0.clusterserviceversion.yaml
- operators/pulp-operator/0.13.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.13.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.13.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.13.0/metadata/annotations.yaml
- operators/pulp-operator/0.13.0/tests/scorecard/config.yaml
> operator pulp-operator (0.13.0)

- operators/tektoncd-operator/ci.yaml
Add Shivam Mukhade as a reviewer for tektoncd-operator
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>
> operator [CI] tektoncd-operator

- operators/trivy-operator/0.1.0/trivy-operator.v0.1.0.clusterserviceversion.yaml
> operator [N] trivy-operator (0.1.0)

- operators/knative-operator/1.5.1/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.5.1/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.5.1/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.5.1/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.5.1/manifests/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.5.1/manifests/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.5.1/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
- operators/knative-operator/1.5.1/manifests/knative-operator-operator-webhook_v1_service.yaml
- operators/knative-operator/1.5.1/manifests/knative-operator.v1.5.1.clusterserviceversion.yaml
- operators/knative-operator/1.5.1/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.5.1/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.5.1/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.5.1/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.5.1/manifests/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.5.1/manifests/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.5.1/metadata/annotations.yaml
- operators/knative-operator/1.5.1/tests/scorecard/config.yaml
> operator knative-operator (1.5.1)

- operators/kiali/1.53.0/bundle.Dockerfile
- operators/kiali/1.53.0/manifests/kiali.crd.yaml
- operators/kiali/1.53.0/manifests/kiali.v1.53.0.clusterserviceversion.yaml
- operators/kiali/1.53.0/metadata/annotations.yaml
> operator kiali (1.53.0)

- operators/project-quay/3.7.3/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.7.3/quayecosystems.crd.yaml
- operators/project-quay/3.7.3/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.7.3 to community operators
> operator project-quay (3.7.3)

- operators/nfs-provisioner-operator/0.0.5/Dockerfile
- operators/nfs-provisioner-operator/0.0.5/manifests/cache.jhouse.com_nfsprovisioners.yaml
- operators/nfs-provisioner-operator/0.0.5/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml
- operators/nfs-provisioner-operator/0.0.5/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/nfs-provisioner-operator/0.0.5/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
- operators/nfs-provisioner-operator/0.0.5/manifests/nfs-provisioner-operator.clusterserviceversion.yaml
- operators/nfs-provisioner-operator/0.0.5/metadata/annotations.yaml
- operators/nfs-provisioner-operator/0.0.5/tests/scorecard/config.yaml
Signed-off-by: jooho <jlee@redhat.com>
--
> operator nfs-provisioner-operator (0.0.5)

- operators/dell-csm-operator/0.2.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/0.2.0/manifests/dell-csm-operator.v0.2.0.clusterserviceversion.yaml
- operators/dell-csm-operator/0.2.0/metadata/annotations.yaml
- operators/dell-csm-operator/0.2.0/tests/scorecard/config.yaml
> operator dell-csm-operator (0.2.0)

- operators/mondoo-operator/0.5.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.5.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.5.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.5.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.5.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.5.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.5.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.5.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (0.5.0)

- operators/tektoncd-operator/0.60.0/bundle.Dockerfile
- operators/tektoncd-operator/0.60.0/manifests/config-logging_v1_configmap.yaml
- operators/tektoncd-operator/0.60.0/manifests/operator.tekton.dev_tektonchains.yaml
- operators/tektoncd-operator/0.60.0/manifests/operator.tekton.dev_tektonconfigs.yaml
- operators/tektoncd-operator/0.60.0/manifests/operator.tekton.dev_tektondashboards.yaml
- operators/tektoncd-operator/0.60.0/manifests/operator.tekton.dev_tektonhubs.yaml
- operators/tektoncd-operator/0.60.0/manifests/operator.tekton.dev_tektoninstallersets.yaml
- operators/tektoncd-operator/0.60.0/manifests/operator.tekton.dev_tektonpipelines.yaml
- operators/tektoncd-operator/0.60.0/manifests/operator.tekton.dev_tektonresults.yaml
- operators/tektoncd-operator/0.60.0/manifests/operator.tekton.dev_tektontriggers.yaml
- operators/tektoncd-operator/0.60.0/manifests/tekton-config-defaults_v1_configmap.yaml
- operators/tektoncd-operator/0.60.0/manifests/tekton-config-observability_v1_configmap.yaml
- operators/tektoncd-operator/0.60.0/manifests/tekton-config-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tektoncd-operator/0.60.0/manifests/tekton-config-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tektoncd-operator/0.60.0/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_role.yaml
- operators/tektoncd-operator/0.60.0/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tektoncd-operator/0.60.0/manifests/tekton-operator-info_v1_configmap.yaml
- operators/tektoncd-operator/0.60.0/manifests/tekton-operator-webhook-certs_v1_secret.yaml
- operators/tektoncd-operator/0.60.0/manifests/tekton-operator-webhook_v1_service.yaml
- operators/tektoncd-operator/0.60.0/manifests/tekton-operator_v1_service.yaml
- operators/tektoncd-operator/0.60.0/manifests/tektoncd-operator.clusterserviceversion.yaml
- operators/tektoncd-operator/0.60.0/metadata/annotations.yaml
Add tektoncd-operator v0.60.0 bundle
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
--
> operator tektoncd-operator (0.60.0)

- operators/redis-operator/0.11.0/manifests/redis-operator.v0.11.0.clusterserviceversion.yaml
- operators/redis-operator/0.11.0/manifests/redis.redis.redis.opstreelabs.in.crd.yaml
- operators/redis-operator/0.11.0/manifests/redisclusters.redis.redis.opstreelabs.in.crd.yaml
- operators/redis-operator/0.11.0/metadata/annotations.yaml
> operator redis-operator (0.11.0)

- operators/clever-operator/0.5.3/bundle.Dockerfile
- operators/clever-operator/0.5.3/manifests/clever-operator-config-elasticsearch.crd.yaml
- operators/clever-operator/0.5.3/manifests/clever-operator-config-provider.crd.yaml
- operators/clever-operator/0.5.3/manifests/clever-operator-mongodb.crd.yaml
- operators/clever-operator/0.5.3/manifests/clever-operator-mysql.crd.yaml
- operators/clever-operator/0.5.3/manifests/clever-operator-postgresql.crd.yaml
- operators/clever-operator/0.5.3/manifests/clever-operator-pulsar.crd.yaml
- operators/clever-operator/0.5.3/manifests/clever-operator-redis.crd.yaml
- operators/clever-operator/0.5.3/manifests/clever-operator.clusterserviceversion.yaml
- operators/clever-operator/0.5.3/metadata/annotations.yaml
- operators/clever-operator/0.5.3/tests/scorecard/config.yaml
Signed-off-by: Florentin Dubois <florentin.dubois@clever-cloud.com>
--
> operator clever-operator (0.5.3)

- operators/flink-kubernetes-operator/1.0.1/manifests/flink-kubernetes-operator.clusterserviceversion.yaml
Signed-off-by: ted chang <htchang@us.ibm.com>
--
> operator [N] flink-kubernetes-operator (1.0.1)

- operators/opentelemetry-operator/ci.yaml
> operator [CI] opentelemetry-operator

- operators/trivy-operator/0.1.3/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.3/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.3/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.3/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.3/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.3/trivy-operator.v0.1.3.clusterserviceversion.yaml
- operators/trivy-operator/0.1.3/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.1.3)

- operators/mondoo-operator/0.6.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.6.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.6.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.6.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.6.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.6.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.6.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.6.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (0.6.0)

- operators/knative-operator/1.6.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.6.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.6.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.6.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.6.0/manifests/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.6.0/manifests/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.6.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
- operators/knative-operator/1.6.0/manifests/knative-operator-operator-webhook_v1_service.yaml
- operators/knative-operator/1.6.0/manifests/knative-operator.v1.6.0.clusterserviceversion.yaml
- operators/knative-operator/1.6.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.6.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.6.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.6.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.6.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.6.0/manifests/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.6.0/metadata/annotations.yaml
- operators/knative-operator/1.6.0/tests/scorecard/config.yaml
> operator knative-operator (1.6.0)

- operators/mongodb-atlas-kubernetes/1.1.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/1.1.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/1.1.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/1.1.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/1.1.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/1.1.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/1.1.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/1.1.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/1.1.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/1.1.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/1.1.0/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (1.1.0)

- operators/opentelemetry-operator/0.55.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.55.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.55.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.55.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.55.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.55.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.55.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.55.0/tests/scorecard/config.yaml
> operator opentelemetry-operator (0.55.0)

- operators/mongodb-enterprise/1.16.3/bundle.Dockerfile
- operators/mongodb-enterprise/1.16.3/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.16.3/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.16.3/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.3/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.3/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.3/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.16.3/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.16.3/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.16.3/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.16.3/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.16.3/metadata/annotations.yaml
- operators/mongodb-enterprise/1.16.3/tests/scorecard/config.yaml
> operator mongodb-enterprise (1.16.3)

- operators/datadog-operator/0.8.1/manifests/datadog-operator.clusterserviceversion.yaml
- operators/datadog-operator/0.8.1/manifests/datadoghq.com_datadogagents.yaml
- operators/datadog-operator/0.8.1/manifests/datadoghq.com_datadogmetrics.yaml
- operators/datadog-operator/0.8.1/manifests/datadoghq.com_datadogmonitors.yaml
- operators/datadog-operator/0.8.1/metadata/annotations.yaml
- operators/datadog-operator/0.8.1/tests/scorecard/config.yaml
Signed-off-by: Celene Chang <celene@datadoghq.com>
--
> operator datadog-operator (0.8.1)

- operators/istio-workspace-operator/0.5.1/manifests/istio-workspace-operator.clusterserviceversion.yaml
- operators/istio-workspace-operator/0.5.1/manifests/workspace.maistra.io_sessions.yaml
- operators/istio-workspace-operator/0.5.1/metadata/annotations.yaml
- operators/istio-workspace-operator/0.5.1/tests/scorecard/config.yaml
> operator istio-workspace-operator (0.5.1)

- operators/metallb-operator/0.13.3/manifests/metallb-operator.clusterserviceversion.yaml
- operators/metallb-operator/0.13.3/manifests/metallb.io_addresspools.yaml
- operators/metallb-operator/0.13.3/manifests/metallb.io_bfdprofiles.yaml
- operators/metallb-operator/0.13.3/manifests/metallb.io_bgpadvertisements.yaml
- operators/metallb-operator/0.13.3/manifests/metallb.io_bgppeers.yaml
- operators/metallb-operator/0.13.3/manifests/metallb.io_communities.yaml
- operators/metallb-operator/0.13.3/manifests/metallb.io_ipaddresspools.yaml
- operators/metallb-operator/0.13.3/manifests/metallb.io_l2advertisements.yaml
- operators/metallb-operator/0.13.3/manifests/metallb.io_metallbs.yaml
- operators/metallb-operator/0.13.3/manifests/webhook-server-cert_v1_secret.yaml
- operators/metallb-operator/0.13.3/manifests/webhook-service_v1_service.yaml
- operators/metallb-operator/0.13.3/metadata/annotations.yaml
- operators/metallb-operator/0.13.3/tests/scorecard/config.yaml
Adding the latest version of the operator
> operator metallb-operator (0.13.3)

- ci/pipeline-config-k8s.yaml
> otc-rds-operator to exceptions

- operators/mondoo-operator/0.7.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.7.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.7.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.7.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.7.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.7.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.7.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.7.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (0.7.0)

- operators/trivy-operator/0.1.4/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.4/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.4/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.4/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.4/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.4/trivy-operator.v0.1.4.clusterserviceversion.yaml
- operators/trivy-operator/0.1.4/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.1.4)

- operators/mondoo-operator/0.7.1/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.7.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.7.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.7.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.7.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.7.1/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.7.1/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.7.1/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (0.7.1)

- operators/trivy-operator/0.1.5/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.5/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.5/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.5/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.5/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.5/trivy-operator.v0.1.5.clusterserviceversion.yaml
- operators/trivy-operator/0.1.5/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.1.5)

- operators/grafana-operator/4.5.1/grafana-operator-controller-manager-metrics-service_v1_service.yaml
- operators/grafana-operator/4.5.1/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/4.5.1/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/4.5.1/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/4.5.1/integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/4.5.1/integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/4.5.1/integreatly.org_grafananotificationchannels.yaml
- operators/grafana-operator/4.5.1/integreatly.org_grafanas.yaml
- operators/grafana-operator/grafana-operator.package.yaml
> operator grafana-operator (4.5.1)

- operators/hpe-csi-operator/2.2.0/Dockerfile
- operators/hpe-csi-operator/2.2.0/manifests/hpe-csi-operator.v2.2.0.clusterserviceversion.yaml
- operators/hpe-csi-operator/2.2.0/manifests/hpecsidrivers.storage.hpe.com.crd.yaml
- operators/hpe-csi-operator/2.2.0/metadata/annotations.yaml
- operators/hpe-csi-operator/ci.yaml
> operator [CI] hpe-csi-operator (2.2.0)

- operators/cloud-native-postgresql/1.16.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.16.0/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.16.0/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.16.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.16.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.16.0/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.16.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.16.0/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.16.0/tests/scorecard/config.yaml
> operator cloud-native-postgresql (1.16.0)

- operators/flux/0.31.4/manifests/alert.crd.yaml
- operators/flux/0.31.4/manifests/bucket.crd.yaml
- operators/flux/0.31.4/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.31.4/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.31.4/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.31.4/manifests/flux.v0.31.4.clusterserviceversion.yaml
- operators/flux/0.31.4/manifests/gitrepository.crd.yaml
- operators/flux/0.31.4/manifests/helmchart.crd.yaml
- operators/flux/0.31.4/manifests/helmrelease.crd.yaml
- operators/flux/0.31.4/manifests/helmrepository.crd.yaml
- operators/flux/0.31.4/manifests/imagepolicy.crd.yaml
- operators/flux/0.31.4/manifests/imagerepository.crd.yaml
- operators/flux/0.31.4/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.31.4/manifests/kustomization.crd.yaml
- operators/flux/0.31.4/manifests/notification-controller.service.yaml
- operators/flux/0.31.4/manifests/provider.crd.yaml
- operators/flux/0.31.4/manifests/receiver.crd.yaml
- operators/flux/0.31.4/manifests/source-controller.service.yaml
- operators/flux/0.31.4/manifests/webhook-receiver.service.yaml
- operators/flux/0.31.4/metadata/annotations.yaml
> operator flux (0.31.4)

- operators/aqua/2022.4.3/bundle.Dockerfile
- operators/aqua/2022.4.3/manifests/aqua-operator.v2022.4.2.clusterserviceversion.yaml
- operators/aqua/2022.4.3/manifests/aquacsps.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.3/manifests/aquadatabases.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.3/manifests/aquaenforcers.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.3/manifests/aquagateways.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.3/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.3/manifests/aquascanners.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.3/manifests/aquaservers.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.3/manifests/aquastarboards.aquasecurity.github.io.crd.yaml
- operators/aqua/2022.4.3/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml
- operators/aqua/2022.4.3/manifests/configauditreports.aquasecurity.github.io.crd.yaml
- operators/aqua/2022.4.3/metadata/annotations.yaml
- operators/aqua/ci.yaml
Signed-off-by: koppularajender <koppularajender18@gmail.com>
--
> operator [CI] aqua (2022.4.3)

- operators/klusterlet/0.8.0/klusterlet.v0.8.0.clusterserviceversion.yaml
- operators/klusterlet/0.8.0/operator.open-cluster-management.io_klusterlets.yaml
- operators/klusterlet/klusterlet.package.yaml
> operator klusterlet (0.8.0)

- operators/cluster-manager/0.8.0/cluster-manager.v0.8.0.clusterserviceversion.yaml
- operators/cluster-manager/0.8.0/operator.open-cluster-management.io_clustermanagers.yaml
- operators/cluster-manager/cluster-manger.package.yaml
> operator cluster-manager (0.8.0)

- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.26.2/victoriametrics-operator.0.26.2.clusterserviceversion.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operator victoriametrics-operator (0.26.2)

- operators/seldon-operator/1.13.1/manifests/seldon-operator.clusterserviceversion.yaml
- operators/seldon-operator/1.13.1/metadata/annotations.yaml
Update `seldon-operator` to run on OpenShift 4.10
---
--
> operator [O] seldon-operator (1.13.1)

- operators/mondoo-operator/0.8.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.8.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.8.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.8.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.8.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.8.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.8.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.8.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (0.8.0)

- operators/rabbitmq-cluster-operator/1.14.0/bundle.Dockerfile
- operators/rabbitmq-cluster-operator/1.14.0/manifests/crds.yaml
- operators/rabbitmq-cluster-operator/1.14.0/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-cluster-operator/1.14.0/metadata/annotations.yaml
- operators/rabbitmq-cluster-operator/ci.yaml
> operator [N] [CI] rabbitmq-cluster-operator (1.14.0)

- operators/hpe-csi-operator/2.2.1/Dockerfile
- operators/hpe-csi-operator/2.2.1/manifests/hpe-csi-operator.v2.2.1.clusterserviceversion.yaml
- operators/hpe-csi-operator/2.2.1/manifests/hpecsidrivers.storage.hpe.com.crd.yaml
- operators/hpe-csi-operator/2.2.1/metadata/annotations.yaml
Signed-off-by: bhagyashree_sarawate <bhagyashree.sarawate@hpe.com>
--
> operator hpe-csi-operator (2.2.1)

- operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml
- operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml
- operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-operator-manager-config_v1_configmap.yaml
- operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-operator-webhook-service_v1_service.yaml
- operators/aerospike-kubernetes-operator/2.1.0/manifests/asdb.aerospike.com_aerospikeclusters.yaml
- operators/aerospike-kubernetes-operator/2.1.0/metadata/annotations.yaml
- operators/aerospike-kubernetes-operator/2.1.0/tests/scorecard/config.yaml
- operators/aerospike-kubernetes-operator/ci.yaml
Release aerospike-kubernetes-operator 2.1.0
Signed-off-by: Ashish Shinde <ashish@aerospike.com>
--
> operator [CI] aerospike-kubernetes-operator (2.1.0)

- operators/argocd-operator/0.4.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- operators/argocd-operator/0.4.0/argocd-operator-manager-config_v1_configmap.yaml
- operators/argocd-operator/0.4.0/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/argocd-operator/0.4.0/argocd-operator.v0.4.0.clusterserviceversion.yaml
- operators/argocd-operator/0.4.0/argoproj.io_applications.yaml
- operators/argocd-operator/0.4.0/argoproj.io_applicationsets.yaml
- operators/argocd-operator/0.4.0/argoproj.io_appprojects.yaml
- operators/argocd-operator/0.4.0/argoproj.io_argocdexports.yaml
- operators/argocd-operator/0.4.0/argoproj.io_argocds.yaml
- operators/argocd-operator/argocd-operator.package.yaml
- operators/argocd-operator/ci.yaml
Signed-off-by: ishitasequeira [ishiseq29@gmail.com](mailto:ishiseq29@@gmail.com)
--
> operator [CI] argocd-operator (0.4.0)

- operators/pulsar-operator/0.12.0/bundle.Dockerfile
- operators/pulsar-operator/0.12.0/manifests/pulsar-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulsar-operator/0.12.0/manifests/pulsar-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulsar-operator/0.12.0/manifests/pulsar-operator-pulsar-broker_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulsar-operator/0.12.0/manifests/pulsar-operator.clusterserviceversion.yaml
- operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsarbrokers.yaml
- operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsarconnections.yaml
- operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsarnamespaces.yaml
- operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsarpermissions.yaml
- operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsarproxies.yaml
- operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsartenants.yaml
- operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsartopics.yaml
- operators/pulsar-operator/0.12.0/metadata/annotations.yaml
- operators/pulsar-operator/0.12.0/tests/scorecard/config.yaml
> operator pulsar-operator (0.12.0)

- operators/snapscheduler/3.1.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml
- operators/snapscheduler/3.1.0/manifests/snapscheduler-manager-config_v1_configmap.yaml
- operators/snapscheduler/3.1.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/snapscheduler/3.1.0/manifests/snapscheduler.backube_snapshotschedules.yaml
- operators/snapscheduler/3.1.0/manifests/snapscheduler.clusterserviceversion.yaml
- operators/snapscheduler/3.1.0/metadata/annotations.yaml
- operators/snapscheduler/3.1.0/tests/scorecard/config.yaml
> operator snapscheduler (3.1.0)

- operators/seldon-operator/1.14.0/manifests/machinelearning.seldon.io_seldondeployments.yaml
- operators/seldon-operator/1.14.0/manifests/seldon-operator.clusterserviceversion.yaml
- operators/seldon-operator/1.14.0/metadata/annotations.yaml
- operators/seldon-operator/1.14.0/tests/scorecard/config.yaml
Signed-off-by: Rafal Skolasinski <r.j.skolasinski@gmail.com>
--
> operator seldon-operator (1.14.0)

- operators/portworx/1.9.0/core_v1_storagecluster_crd.yaml
- operators/portworx/1.9.0/core_v1_storagenode_crd.yaml
- operators/portworx/1.9.0/portworxoperator.clusterserviceversion.yaml
- operators/portworx/ci.yaml
- operators/portworx/portworx.package.yaml
Signed-off-by: HaibinMichaelXie <hxie@purestorage.com>
--
> operator [CI] portworx (1.9.0)

- operators/mondoo-operator/0.8.2/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/0.8.2/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/0.8.2/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/0.8.2/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/0.8.2/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/0.8.2/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/0.8.2/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/0.8.2/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (0.8.2)

- operators/mongodb-enterprise/1.16.4/bundle.Dockerfile
- operators/mongodb-enterprise/1.16.4/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.16.4/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.16.4/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.4/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.4/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.16.4/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.16.4/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.16.4/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.16.4/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.16.4/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.16.4/metadata/annotations.yaml
- operators/mongodb-enterprise/1.16.4/tests/scorecard/config.yaml
> operator mongodb-enterprise (1.16.4)

- operators/mondoo-operator/1.0.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.0.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.0.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.0.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.0.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.0.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.0.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.0.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.0.0)

- operators/project-quay/3.7.5/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.7.5/quayecosystems.crd.yaml
- operators/project-quay/3.7.5/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.7.5 to community operators
> operator project-quay (3.7.5)

- operators/splunk/2.0.0/bundle.Dockerfile
- operators/splunk/2.0.0/manifests/enterprise.splunk.com_clustermasters.yaml
- operators/splunk/2.0.0/manifests/enterprise.splunk.com_indexerclusters.yaml
- operators/splunk/2.0.0/manifests/enterprise.splunk.com_licensemasters.yaml
- operators/splunk/2.0.0/manifests/enterprise.splunk.com_monitoringconsoles.yaml
- operators/splunk/2.0.0/manifests/enterprise.splunk.com_searchheadclusters.yaml
- operators/splunk/2.0.0/manifests/enterprise.splunk.com_standalones.yaml
- operators/splunk/2.0.0/manifests/splunk-operator-config_v1_configmap.yaml
- operators/splunk/2.0.0/manifests/splunk-operator-controller-manager-metrics-service_v1_service.yaml
- operators/splunk/2.0.0/manifests/splunk-operator-controller-manager-service_v1_service.yaml
- operators/splunk/2.0.0/manifests/splunk-operator-manager-config_v1_configmap.yaml
- operators/splunk/2.0.0/manifests/splunk-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/splunk/2.0.0/manifests/splunk-operator.clusterserviceversion.yaml
- operators/splunk/2.0.0/metadata/annotations.yaml
- operators/splunk/2.0.0/tests/scorecard/config.yaml
Signed-off-by: vivekr-splunk <94569031+vivekr-splunk@users.noreply.github.com>
--
> operator splunk (2.0.0)

- operators/trident-operator/22.7.0/trident-operator.v22.7.0.clusterserviceversion.yaml
- operators/trident-operator/22.7.0/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
- operators/trident-operator/trident-operator.package.yaml
Signed-off-by: Chris Reeder <reederc42@gmail.com>
--
> operator trident-operator (22.7.0)

- operators/external-secrets-operator/0.5.9/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.5.9/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.5.9/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.5.9/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.5.9/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.5.9/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.5.9/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.5.9/metadata/annotations.yaml
- operators/external-secrets-operator/0.5.9/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.9
> operator external-secrets-operator (0.5.9)

- operators/kiali/1.54.0/bundle.Dockerfile
- operators/kiali/1.54.0/manifests/kiali.crd.yaml
- operators/kiali/1.54.0/manifests/kiali.v1.54.0.clusterserviceversion.yaml
- operators/kiali/1.54.0/metadata/annotations.yaml
> operator kiali (1.54.0)

- operators/kubernetes-imagepuller-operator/1.0.2/che.eclipse.org_kubernetesimagepullers_crd.yaml
- operators/kubernetes-imagepuller-operator/1.0.2/controller-manager-metrics-service_v1_service.yaml
- operators/kubernetes-imagepuller-operator/1.0.2/kubernetes-imagepuller-operator.v1.0.2.clusterserviceversion.yaml
- operators/kubernetes-imagepuller-operator/1.0.2/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: David Kwon <dakwon@redhat.com>
--
> operator kubernetes-imagepuller-operator (1.0.2)

- operators/hyperfoil-bundle/0.21.0/hyperfoil-operator.v0.21.0.clusterserviceversion.yaml
- operators/hyperfoil-bundle/0.21.0/hyperfoil.io_hyperfoils_crd.yaml
- operators/hyperfoil-bundle/ci.yaml
- operators/hyperfoil-bundle/hyperfoil-bundle.package.yaml
Hello, I've updated operator previously published for Openshift-only to support vanilla K8s deployments (handles route.openshift.io not present), therefore submitting for general use.
--
> operator [N] [CI] hyperfoil-bundle (0.21.0)

- operators/cloud-native-postgresql/1.15.2/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.15.2/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.15.2/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.15.2/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.15.2/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.15.2/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.15.2/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.15.2/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.15.2/tests/scorecard/config.yaml
> operator cloud-native-postgresql (1.15.2)

- operators/gitlab-operator-kubernetes/0.10.2/manifests/acme.cert-manager.io_challenges.yaml
- operators/gitlab-operator-kubernetes/0.10.2/manifests/acme.cert-manager.io_orders.yaml
- operators/gitlab-operator-kubernetes/0.10.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.10.2/manifests/cert-manager.io_certificaterequests.yaml
- operators/gitlab-operator-kubernetes/0.10.2/manifests/cert-manager.io_certificates.yaml
- operators/gitlab-operator-kubernetes/0.10.2/manifests/cert-manager.io_clusterissuers.yaml
- operators/gitlab-operator-kubernetes/0.10.2/manifests/cert-manager.io_issuers.yaml
- operators/gitlab-operator-kubernetes/0.10.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.10.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.10.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.10.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.10.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.10.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.10.2)

- operators/seldon-operator/1.14.1/manifests/machinelearning.seldon.io_seldondeployments.yaml
- operators/seldon-operator/1.14.1/manifests/seldon-operator.clusterserviceversion.yaml
- operators/seldon-operator/1.14.1/metadata/annotations.yaml
- operators/seldon-operator/1.14.1/tests/scorecard/config.yaml
Signed-off-by: Rafal Skolasinski <r.j.skolasinski@gmail.com>
--
> operator seldon-operator (1.14.1)

- operators/istio-workspace-operator/0.5.2/manifests/istio-workspace-operator.clusterserviceversion.yaml
- operators/istio-workspace-operator/0.5.2/manifests/workspace.maistra.io_sessions.yaml
- operators/istio-workspace-operator/0.5.2/metadata/annotations.yaml
- operators/istio-workspace-operator/0.5.2/tests/scorecard/config.yaml
> operator istio-workspace-operator (0.5.2)

- operators/splunk/2.0.0/manifests/enterprise.splunk.com_clustermasters.yaml
- operators/splunk/2.0.0/manifests/enterprise.splunk.com_licensemasters.yaml
- operators/splunk/2.0.0/manifests/enterprise.splunk.com_searchheadclusters.yaml
- operators/splunk/2.0.0/manifests/enterprise.splunk.com_standalones.yaml
- operators/splunk/2.0.0/manifests/splunk-operator-config_v1_configmap.yaml
- operators/splunk/2.0.0/manifests/splunk-operator-controller-manager-metrics-service_v1_service.yaml
- operators/splunk/2.0.0/manifests/splunk-operator-controller-manager-service_v1_service.yaml
- operators/splunk/2.0.0/manifests/splunk-operator-manager-config_v1_configmap.yaml
- operators/splunk/2.0.0/manifests/splunk-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/splunk/2.0.0/manifests/splunk-operator.clusterserviceversion.yaml
- operators/splunk/2.0.0/tests/scorecard/config.yaml
- operators/splunk/2.0.0/tests/scorecard/kuttl/kuttl-test.yaml
Signed-off-by: vivekr-splunk <94569031+vivekr-splunk@users.noreply.github.com>
--
> operator [O] splunk (2.0.0)

- operators/netobserv-operator/0.1.4/bundle.Dockerfile
- operators/netobserv-operator/0.1.4/manifests/flows.netobserv.io_flowcollectors.yaml
- operators/netobserv-operator/0.1.4/manifests/netobserv-manager-config_v1_configmap.yaml
- operators/netobserv-operator/0.1.4/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/netobserv-operator/0.1.4/manifests/netobserv-metrics-service_v1_service.yaml
- operators/netobserv-operator/0.1.4/manifests/netobserv-operator.clusterserviceversion.yaml
- operators/netobserv-operator/0.1.4/metadata/annotations.yaml
> operator netobserv-operator (0.1.4)

- operators/mondoo-operator/1.0.1/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.0.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.0.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.0.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.0.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.0.1/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.0.1/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.0.1/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.0.1)

- operators/function-mesh/0.4.0/bundle.Dockerfile
- operators/function-mesh/0.4.0/manifests/compute.functionmesh.io_functionmeshes.yaml
- operators/function-mesh/0.4.0/manifests/compute.functionmesh.io_functions.yaml
- operators/function-mesh/0.4.0/manifests/compute.functionmesh.io_sinks.yaml
- operators/function-mesh/0.4.0/manifests/compute.functionmesh.io_sources.yaml
- operators/function-mesh/0.4.0/manifests/function-mesh-controller-manager-metrics-service_v1_service.yaml
- operators/function-mesh/0.4.0/manifests/function-mesh-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
- operators/function-mesh/0.4.0/manifests/function-mesh-webhook-service_v1_service.yaml
- operators/function-mesh/0.4.0/manifests/function-mesh.clusterserviceversion.yaml
- operators/function-mesh/0.4.0/manifests/mesh-test-pulsar_v1_configmap.yaml
- operators/function-mesh/0.4.0/manifests/test-auth_v1_secret.yaml
- operators/function-mesh/0.4.0/manifests/test-pulsar_v1_configmap.yaml
- operators/function-mesh/0.4.0/manifests/test-secret_v1_secret.yaml
- operators/function-mesh/0.4.0/manifests/test-sink_v1_configmap.yaml
- operators/function-mesh/0.4.0/manifests/test-source_v1_configmap.yaml
- operators/function-mesh/0.4.0/manifests/test-tls_v1_secret.yaml
- operators/function-mesh/0.4.0/metadata/annotations.yaml
- operators/function-mesh/0.4.0/tests/scorecard/config.yaml
Signed-off-by: Rui Fu <freelz@gmail.com>
--
> operator function-mesh (0.4.0)

- operators/project-quay/3.7.6/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.7.6/quayecosystems.crd.yaml
- operators/project-quay/3.7.6/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.7.6 to community operators
> operator project-quay (3.7.6)

- operators/project-quay/ci.yaml
* Adds @quay-devel as approved user for Quay
> operator [CI] project-quay

- operators/ack-prometheusservice-controller/ci.yaml
> operator [CI] ack-prometheusservice-controller

- operators/dynatrace-operator/0.8.0/Dockerfile
- operators/dynatrace-operator/0.8.0/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml
- operators/dynatrace-operator/0.8.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/0.8.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/0.8.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml
- operators/dynatrace-operator/0.8.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/dynatrace-operator/0.8.0/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.8.0/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/0.8.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/0.8.0/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/0.8.0/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.8.0/metadata/annotations.yaml
> operator dynatrace-operator (0.8.0)

- operators/telegraf-operator/1.3.9/Dockerfile
- operators/telegraf-operator/1.3.9/manifests/classes-secret.yaml
- operators/telegraf-operator/1.3.9/manifests/telegraf-operator-v1.3.9.clusterserviceversion.yaml
- operators/telegraf-operator/1.3.9/metadata/annotations.yaml
Signed-off-by: Wojciech Kocjan <wkocjan@influxdata.com>
--
> operator telegraf-operator (1.3.9)

- operators/cloud-native-postgresql/1.15.3/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.15.3/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.15.3/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.15.3/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.15.3/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.15.3/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.15.3/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.15.3/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.15.3/tests/scorecard/config.yaml
> operator cloud-native-postgresql (1.15.3)

- operators/cloud-native-postgresql/1.16.1/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.16.1/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.16.1/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.16.1/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.16.1/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.16.1/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.16.1/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.16.1/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.16.1/tests/scorecard/config.yaml
> operator cloud-native-postgresql (1.16.1)

- operators/mondoo-operator/1.1.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.1.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.1.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.1.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.1.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.1.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.1.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.1.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.1.0)

- operators/lbconfig-operator/0.2.0/manifests/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml
- operators/lbconfig-operator/0.2.0/manifests/lbconfig-operator-controller-manager-metrics-service_v1_service.yaml
- operators/lbconfig-operator/0.2.0/manifests/lbconfig-operator-manager-config_v1_configmap.yaml
- operators/lbconfig-operator/0.2.0/manifests/lbconfig-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/lbconfig-operator/0.2.0/manifests/lbconfig-operator.clusterserviceversion.yaml
- operators/lbconfig-operator/0.2.0/metadata/annotations.yaml
- operators/lbconfig-operator/0.2.0/tests/scorecard/config.yaml
- operators/lbconfig-operator/ci.yaml
> operator [N] [CI] lbconfig-operator (0.2.0)

- operators/cloud-native-postgresql/1.15.2/metadata/annotations.yaml
Replace `null` channel with `stable` channel
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>
--
> operator [O] cloud-native-postgresql (1.15.2)

- operators/mondoo-operator/1.1.1/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.1.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.1.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.1.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.1.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.1.1/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.1.1/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.1.1/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.1.1)

- operators/horreum-operator/0.0.2/horreum-operator.v0.0.2.clusterserviceversion.yaml
- operators/horreum-operator/0.0.2/hyperfoil.io_horreums_crd.yaml
- operators/horreum-operator/ci.yaml
- operators/horreum-operator/horreum-operator.package.yaml
> operator [N] [CI] horreum-operator (0.0.2)

- operators/kiali/1.55.0/bundle.Dockerfile
- operators/kiali/1.55.0/manifests/kiali.crd.yaml
- operators/kiali/1.55.0/manifests/kiali.v1.55.0.clusterserviceversion.yaml
- operators/kiali/1.55.0/metadata/annotations.yaml
> operator kiali (1.55.0)

- operators/grafana-operator/4.6.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml
- operators/grafana-operator/4.6.0/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/4.6.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/4.6.0/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/4.6.0/integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/4.6.0/integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/4.6.0/integreatly.org_grafananotificationchannels.yaml
- operators/grafana-operator/4.6.0/integreatly.org_grafanas.yaml
- operators/grafana-operator/grafana-operator.package.yaml
> operator grafana-operator (4.6.0)

- operators/trivy-operator/0.1.6/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.6/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.6/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.6/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.6/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.6/trivy-operator.v0.1.6.clusterserviceversion.yaml
- operators/trivy-operator/0.1.6/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.1.6)

- operators/limitador-operator/0.3.0/bundle.Dockerfile
- operators/limitador-operator/0.3.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml
- operators/limitador-operator/0.3.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
- operators/limitador-operator/0.3.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/limitador-operator/0.3.0/manifests/limitador-operator.clusterserviceversion.yaml
- operators/limitador-operator/0.3.0/manifests/limitador.kuadrant.io_limitadors.yaml
- operators/limitador-operator/0.3.0/metadata/annotations.yaml
- operators/limitador-operator/0.3.0/tests/scorecard/config.yaml
- operators/limitador-operator/ci.yaml
Limitador Operator `v0.3.0`
--
> operator [N] [CI] limitador-operator (0.3.0)

- operators/kube-green/0.4.0/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml
- operators/kube-green/0.4.0/manifests/kube-green-manager-config_v1_configmap.yaml
- operators/kube-green/0.4.0/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kube-green/0.4.0/manifests/kube-green-webhook-service_v1_service.yaml
- operators/kube-green/0.4.0/manifests/kube-green.clusterserviceversion.yaml
- operators/kube-green/0.4.0/manifests/kube-green.com_sleepinfos.yaml
- operators/kube-green/0.4.0/metadata/annotations.yaml
- operators/kube-green/0.4.0/tests/scorecard/config.yaml
> operator kube-green (0.4.0)

- operators/apicast-community-operator/0.5.1/bundle.Dockerfile
- operators/apicast-community-operator/0.5.1/manifests/apicast-operator-controller-manager-metrics-service_v1_service.yaml
- operators/apicast-community-operator/0.5.1/manifests/apicast-operator.clusterserviceversion.yaml
- operators/apicast-community-operator/0.5.1/manifests/apps.3scale.net_apicasts.yaml
- operators/apicast-community-operator/0.5.1/metadata/annotations.yaml
- operators/apicast-community-operator/0.5.1/tests/scorecard/config.yaml
> operator apicast-community-operator (0.5.1)

- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.27.2/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.27.2/victoriametrics-operator.0.27.2.clusterserviceversion.yaml
- operators/victoriametrics-operator/victoriametrics-operator.package.yaml
> operator victoriametrics-operator (0.27.2)

- operators/function-mesh/0.5.0/bundle.Dockerfile
- operators/function-mesh/0.5.0/manifests/compute.functionmesh.io_functionmeshes.yaml
- operators/function-mesh/0.5.0/manifests/compute.functionmesh.io_functions.yaml
- operators/function-mesh/0.5.0/manifests/compute.functionmesh.io_sinks.yaml
- operators/function-mesh/0.5.0/manifests/compute.functionmesh.io_sources.yaml
- operators/function-mesh/0.5.0/manifests/function-mesh-controller-manager-metrics-service_v1_service.yaml
- operators/function-mesh/0.5.0/manifests/function-mesh-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
- operators/function-mesh/0.5.0/manifests/function-mesh-webhook-service_v1_service.yaml
- operators/function-mesh/0.5.0/manifests/function-mesh.clusterserviceversion.yaml
- operators/function-mesh/0.5.0/manifests/mesh-test-pulsar_v1_configmap.yaml
- operators/function-mesh/0.5.0/manifests/test-auth_v1_secret.yaml
- operators/function-mesh/0.5.0/manifests/test-pulsar_v1_configmap.yaml
- operators/function-mesh/0.5.0/manifests/test-secret_v1_secret.yaml
- operators/function-mesh/0.5.0/manifests/test-sink_v1_configmap.yaml
- operators/function-mesh/0.5.0/manifests/test-source_v1_configmap.yaml
- operators/function-mesh/0.5.0/manifests/test-tls_v1_secret.yaml
- operators/function-mesh/0.5.0/metadata/annotations.yaml
- operators/function-mesh/0.5.0/tests/scorecard/config.yaml
Signed-off-by: Rui Fu <freelz@gmail.com>
--
> operator function-mesh (0.5.0)

- operators/apicast-community-operator/0.6.0/bundle.Dockerfile
- operators/apicast-community-operator/0.6.0/manifests/apicast-operator-controller-manager-metrics-service_v1_service.yaml
- operators/apicast-community-operator/0.6.0/manifests/apicast-operator.clusterserviceversion.yaml
- operators/apicast-community-operator/0.6.0/manifests/apps.3scale.net_apicasts.yaml
- operators/apicast-community-operator/0.6.0/metadata/annotations.yaml
- operators/apicast-community-operator/0.6.0/tests/scorecard/config.yaml
> operator apicast-community-operator (0.6.0)

- operators/mondoo-operator/1.2.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.2.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.2.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.2.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.2.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.2.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.2.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.2.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.2.0)

- operators/app-director-operator/0.8.0/Dockerfile
- operators/app-director-operator/0.8.0/manifests/app-director-controller-manager-metrics-service_v1_service.yaml
- operators/app-director-operator/0.8.0/manifests/app-director-manager-config_v1_configmap.yaml
- operators/app-director-operator/0.8.0/manifests/app-director-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/app-director-operator/0.8.0/manifests/app-director-operator.clusterserviceversion.yaml
- operators/app-director-operator/0.8.0/manifests/appdirector.randoli.ca_clusterwideguvnors.yaml
- operators/app-director-operator/0.8.0/manifests/appdirector.randoli.ca_guvnors.yaml
- operators/app-director-operator/0.8.0/metadata/annotations.yaml
- operators/app-director-operator/0.8.0/tests/scorecard/config.yaml
Signed-off-by: Vanessa Rakoczy <vanessa.rakoczy@randoli.ca>
--
> operator app-director-operator (0.8.0)

- operators/authorino-operator/0.0.1/bundle.Dockerfile
- operators/authorino-operator/0.0.1/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
- operators/authorino-operator/0.0.1/manifests/authorino-operator-manager-config_v1_configmap.yaml
- operators/authorino-operator/0.0.1/manifests/authorino-operator.clusterserviceversion.yaml
- operators/authorino-operator/0.0.1/manifests/authorino.3scale.net_authconfigs.yaml
- operators/authorino-operator/0.0.1/manifests/operator.authorino.kuadrant.io_authorinos.yaml
- operators/authorino-operator/0.0.1/metadata/annotations.yaml
- operators/authorino-operator/0.0.1/tests/scorecard/config.yaml
- operators/authorino-operator/ci.yaml
> operator [N] [CI] authorino-operator (0.0.1)

- operators/rabbitmq-messaging-topology-operator/1.8.0/bundle.Dockerfile
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_bindings.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_exchanges.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_federations.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_permissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_policies.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_queues.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_schemareplications.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_shovels.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_superstreams.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_users.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_vhosts.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.webhook-service.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/metadata/annotations.yaml
- operators/rabbitmq-messaging-topology-operator/ci.yaml
> operator [N] [CI] rabbitmq-messaging-topology-operator (1.8.0)

- ci/pipeline-config-k8s.yaml
> bump kind_kube_version

- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_bindings.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_exchanges.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_federations.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_permissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_policies.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_queues.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_schemareplications.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_shovels.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_superstreams.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_users.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_vhosts.yaml
- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.webhook-service.yaml
> operator [N] rabbitmq-messaging-topology-operator (1.8.0)

- operators/trivy-operator/0.1.7/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.7/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.7/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.7/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.7/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.7/trivy-operator.v0.1.7.clusterserviceversion.yaml
- operators/trivy-operator/0.1.7/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.1.7)

- operators/trivy-operator/0.1.8/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.8/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.8/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.8/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.8/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.8/trivy-operator.v0.1.8.clusterserviceversion.yaml
- operators/trivy-operator/0.1.8/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.1.8)

- operators/beegfs-csi-driver-operator/1.3.0/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml
- operators/beegfs-csi-driver-operator/1.3.0/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml
- operators/beegfs-csi-driver-operator/1.3.0/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/beegfs-csi-driver-operator/1.3.0/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml
- operators/beegfs-csi-driver-operator/1.3.0/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml
- operators/beegfs-csi-driver-operator/1.3.0/metadata/annotations.yaml
- operators/beegfs-csi-driver-operator/1.3.0/tests/scorecard/config.yaml
Signed-off-by: Eric Weber <eric.weber2@netapp.com>
--
> operator beegfs-csi-driver-operator (1.3.0)

- operators/mondoo-operator/1.2.1/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.2.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.2.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.2.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.2.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.2.1/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.2.1/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.2.1/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.2.1)

- operators/dynatrace-operator/0.8.1/Dockerfile
- operators/dynatrace-operator/0.8.1/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml
- operators/dynatrace-operator/0.8.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/0.8.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/0.8.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml
- operators/dynatrace-operator/0.8.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/dynatrace-operator/0.8.1/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.8.1/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/0.8.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/0.8.1/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/0.8.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.8.1/metadata/annotations.yaml
> operator dynatrace-operator (0.8.1)

- operators/mongodb-atlas-kubernetes/1.2.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/1.2.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/1.2.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/1.2.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/1.2.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/1.2.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/1.2.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/1.2.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/1.2.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/1.2.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/1.2.0/tests/scorecard/config.yaml
Signed-off-by: fabritsius <anton_fabritsius@epam.com>
--
> operator mongodb-atlas-kubernetes (1.2.0)

- operators/knative-operator/1.7.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.7.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.7.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.7.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.7.0/manifests/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.7.0/manifests/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.7.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
- operators/knative-operator/1.7.0/manifests/knative-operator-operator-webhook_v1_service.yaml
- operators/knative-operator/1.7.0/manifests/knative-operator.v1.7.0.clusterserviceversion.yaml
- operators/knative-operator/1.7.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.7.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.7.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.7.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.7.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.7.0/manifests/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.7.0/metadata/annotations.yaml
- operators/knative-operator/1.7.0/tests/scorecard/config.yaml
> operator knative-operator (1.7.0)

- operators/trivy-operator/0.1.9/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.9/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.9/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.9/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.9/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.1.9/trivy-operator.v0.1.9.clusterserviceversion.yaml
- operators/trivy-operator/0.1.9/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.1.9)

- operators/tektoncd-operator/0.61.0/manifests/config-logging_v1_configmap.yaml
- operators/tektoncd-operator/0.61.0/manifests/operator.tekton.dev_tektonchains.yaml
- operators/tektoncd-operator/0.61.0/manifests/operator.tekton.dev_tektonconfigs.yaml
- operators/tektoncd-operator/0.61.0/manifests/operator.tekton.dev_tektondashboards.yaml
- operators/tektoncd-operator/0.61.0/manifests/operator.tekton.dev_tektonhubs.yaml
- operators/tektoncd-operator/0.61.0/manifests/operator.tekton.dev_tektoninstallersets.yaml
- operators/tektoncd-operator/0.61.0/manifests/operator.tekton.dev_tektonpipelines.yaml
- operators/tektoncd-operator/0.61.0/manifests/operator.tekton.dev_tektonresults.yaml
- operators/tektoncd-operator/0.61.0/manifests/operator.tekton.dev_tektontriggers.yaml
- operators/tektoncd-operator/0.61.0/manifests/tekton-config-defaults_v1_configmap.yaml
- operators/tektoncd-operator/0.61.0/manifests/tekton-config-observability_v1_configmap.yaml
- operators/tektoncd-operator/0.61.0/manifests/tekton-config-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tektoncd-operator/0.61.0/manifests/tekton-config-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tektoncd-operator/0.61.0/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_role.yaml
- operators/tektoncd-operator/0.61.0/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tektoncd-operator/0.61.0/manifests/tekton-operator-info_v1_configmap.yaml
- operators/tektoncd-operator/0.61.0/manifests/tekton-operator-webhook-certs_v1_secret.yaml
- operators/tektoncd-operator/0.61.0/manifests/tekton-operator-webhook_v1_service.yaml
- operators/tektoncd-operator/0.61.0/manifests/tekton-operator_v1_service.yaml
- operators/tektoncd-operator/0.61.0/manifests/tektoncd-operator.clusterserviceversion.yaml
- operators/tektoncd-operator/0.61.0/metadata/annotations.yaml
Add tektoncd-operator v0.61.0 bundle
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
--
> operator tektoncd-operator (0.61.0)

- operators/gitlab-operator-kubernetes/0.11.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.11.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.11.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.11.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.11.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.11.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.11.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.11.0)

- operators/self-node-remediation/0.4.0/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml
- operators/self-node-remediation/0.4.0/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/self-node-remediation/0.4.0/manifests/self-node-remediation-manager-config_v1_configmap.yaml
- operators/self-node-remediation/0.4.0/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/self-node-remediation/0.4.0/manifests/self-node-remediation-webhook-service_v1_service.yaml
- operators/self-node-remediation/0.4.0/manifests/self-node-remediation.clusterserviceversion.yaml
- operators/self-node-remediation/0.4.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
- operators/self-node-remediation/0.4.0/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
- operators/self-node-remediation/0.4.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
- operators/self-node-remediation/0.4.0/metadata/annotations.yaml
- operators/self-node-remediation/0.4.0/tests/scorecard/config.yaml
- operators/self-node-remediation/ci.yaml
Signed-off-by: Michael Shitrit <mshitrit@redhat.com>
--
> operator [N] [CI] self-node-remediation (0.4.0)

- operators/elastic-cloud-eck/2.4.0/agents.agent.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.4.0/apmservers.apm.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.4.0/beats.beat.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.4.0/elastic-cloud-eck.v2.4.0.clusterserviceversion.yaml
- operators/elastic-cloud-eck/2.4.0/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.4.0/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.4.0/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/2.4.0/kibanas.kibana.k8s.elastic.co.crd.yaml
- operators/elastic-cloud-eck/elastic-cloud-eck.package.yaml
Updates ECK Elasticsearch operator to the latest version 2.4.0
> operator elastic-cloud-eck (2.4.0)

- operators/dynatrace-operator/0.8.2/Dockerfile
- operators/dynatrace-operator/0.8.2/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml
- operators/dynatrace-operator/0.8.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/0.8.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/0.8.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml
- operators/dynatrace-operator/0.8.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/dynatrace-operator/0.8.2/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.8.2/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/0.8.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/0.8.2/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/0.8.2/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.8.2/metadata/annotations.yaml
> operator dynatrace-operator (0.8.2)

- operators/rabbitmq-single-active-consumer-operator/0.2.2/bundle.Dockerfile
- operators/rabbitmq-single-active-consumer-operator/0.2.2/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-single-active-consumer-operator/0.2.2/manifests/rabbitmq.com_superstreamconsumers.yaml
- operators/rabbitmq-single-active-consumer-operator/0.2.2/manifests/rabbitmq.config-map.yaml
- operators/rabbitmq-single-active-consumer-operator/0.2.2/manifests/rabbitmq.webhook-service.yaml
- operators/rabbitmq-single-active-consumer-operator/0.2.2/metadata/annotations.yaml
- operators/rabbitmq-single-active-consumer-operator/ci.yaml
> operator [N] [CI] rabbitmq-single-active-consumer-operator (0.2.2)

- operators/gitlab-operator-kubernetes/0.11.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.11.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.11.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.11.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.11.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.11.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.11.1/tests/scorecard/config.yaml
Signed-off-by: Hossein Pursultani <hpursultani@gitlab.com>
--
> operator gitlab-operator-kubernetes (0.11.1)

- operators/project-quay/3.7.7/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.7.7/quayecosystems.crd.yaml
- operators/project-quay/3.7.7/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.7.7 to community operators
> operator project-quay (3.7.7)

- operators/mondoo-operator/1.3.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.3.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.3.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.3.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.3.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.3.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.3.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.3.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.3.0)

- operators/authorino-operator/0.4.0/bundle.Dockerfile
- operators/authorino-operator/0.4.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.4.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.4.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.4.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.4.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.4.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
- operators/authorino-operator/0.4.0/manifests/authorino-operator-manager-config_v1_configmap.yaml
- operators/authorino-operator/0.4.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.4.0/manifests/authorino-operator.clusterserviceversion.yaml
- operators/authorino-operator/0.4.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.4.0/manifests/authorino.kuadrant.io_authconfigs.yaml
- operators/authorino-operator/0.4.0/manifests/manager-config_v1_configmap.yaml
- operators/authorino-operator/0.4.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
- operators/authorino-operator/0.4.0/metadata/annotations.yaml
- operators/authorino-operator/0.4.0/tests/scorecard/config.yaml
> operator authorino-operator (0.4.0)

- operators/mondoo-operator/1.3.1/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.3.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.3.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.3.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.3.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.3.1/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.3.1/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.3.1/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.3.1)

- operators/project-quay/3.8.0-rc.1/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.8.0-rc.1/quayecosystems.crd.yaml
- operators/project-quay/3.8.0-rc.1/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
> operator project-quay (3.8.0-rc.1)

- operators/project-quay/3.8.0-rc.2/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.8.0-rc.2/quayecosystems.crd.yaml
- operators/project-quay/3.8.0-rc.2/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.8.0-rc.2 to community operators
> operator project-quay (3.8.0-rc.2)

- operators/camel-k/1.10.0/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.10.0/manifests/camel-k.v1.10.0.clusterserviceversion.yaml
- operators/camel-k/1.10.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.10.0/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.10.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.10.0/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.10.0/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.10.0/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/1.10.0/metadata/annotations.yaml
- operators/camel-k/1.10.0/tests/scorecard/config.yaml
- operators/camel-k/1.8.0/metadata/annotations.yaml
- operators/camel-k/1.8.1/metadata/annotations.yaml
- operators/camel-k/1.8.2/metadata/annotations.yaml
- operators/camel-k/1.9.1/metadata/annotations.yaml
- operators/camel-k/1.9.2/metadata/annotations.yaml
> operator [R] camel-k (1.10.0 1.8.0 1.8.1 1.8.2 1.9.0 1.9.1 1.9.2)

- operators/security-profiles-operator/0.4.3/bundle.Dockerfile
- operators/security-profiles-operator/0.4.3/manifests/metrics-token_v1_secret.yaml
- operators/security-profiles-operator/0.4.3/manifests/security-profiles-operator-profile_v1_configmap.yaml
- operators/security-profiles-operator/0.4.3/manifests/security-profiles-operator.clusterserviceversion.yaml
- operators/security-profiles-operator/0.4.3/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
- operators/security-profiles-operator/0.4.3/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
- operators/security-profiles-operator/0.4.3/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
- operators/security-profiles-operator/0.4.3/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
- operators/security-profiles-operator/0.4.3/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
- operators/security-profiles-operator/0.4.3/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
- operators/security-profiles-operator/0.4.3/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
- operators/security-profiles-operator/0.4.3/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
- operators/security-profiles-operator/0.4.3/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/security-profiles-operator/0.4.3/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/security-profiles-operator/0.4.3/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/security-profiles-operator/0.4.3/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/security-profiles-operator/0.4.3/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
- operators/security-profiles-operator/0.4.3/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/security-profiles-operator/0.4.3/manifests/spo-webhook_v1_serviceaccount.yaml
- operators/security-profiles-operator/0.4.3/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/security-profiles-operator/0.4.3/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/security-profiles-operator/0.4.3/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
- operators/security-profiles-operator/0.4.3/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/security-profiles-operator/0.4.3/manifests/spod_v1_serviceaccount.yaml
- operators/security-profiles-operator/0.4.3/metadata/annotations.yaml
- operators/security-profiles-operator/0.4.3/tests/scorecard/config.yaml
> operator security-profiles-operator (0.4.3)

- operators/cloud-native-postgresql/1.15.4/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.15.4/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.15.4/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.15.4/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.15.4/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.15.4/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.15.4/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.15.4/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.15.4/tests/scorecard/config.yaml
> operator cloud-native-postgresql (1.15.4)

- operators/kiali/1.56.0/bundle.Dockerfile
- operators/kiali/1.56.0/manifests/kiali.crd.yaml
- operators/kiali/1.56.0/manifests/kiali.v1.56.0.clusterserviceversion.yaml
- operators/kiali/1.56.0/metadata/annotations.yaml
> operator kiali (1.56.0)

- operators/mondoo-operator/1.3.2/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.3.2/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.3.2/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.3.2/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.3.2/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.3.2/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.3.2/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.3.2/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.3.2)

- operators/gitlab-operator-kubernetes/0.11.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.11.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.11.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.11.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.11.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.11.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.11.2/tests/scorecard/config.yaml
Signed-off-by: Hossein Pursultani <hpursultani@gitlab.com>
--
> operator gitlab-operator-kubernetes (0.11.2)

- operators/tackle-operator/2.1.0/manifests/tackle-operator.clusterserviceversion.yaml
- operators/tackle-operator/2.1.0/manifests/tackle.konveyor.io_addons.yaml
- operators/tackle-operator/2.1.0/manifests/tackle.konveyor.io_tackles.yaml
- operators/tackle-operator/2.1.0/metadata/annotations.yaml
- operators/tackle-operator/ci.yaml
> operator [CI] tackle-operator (2.1.0)

- operators/service-binding-operator/1.2.0/manifests/binding.operators.coreos.com_bindablekinds.yaml
- operators/service-binding-operator/1.2.0/manifests/binding.operators.coreos.com_servicebindings.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-clusterworkloadresourcemappings-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-clusterworkloadresourcemappings-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-manager-config_v1_configmap.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-operator.clusterserviceversion.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.2.0/manifests/service-binding-webhook-service_v1_service.yaml
- operators/service-binding-operator/1.2.0/manifests/servicebinding.io_clusterworkloadresourcemappings.yaml
- operators/service-binding-operator/1.2.0/manifests/servicebinding.io_servicebindings.yaml
- operators/service-binding-operator/1.2.0/metadata/annotations.yaml
Creating a PR for release of SBO - v1.2.0
Signed-off-by: Feny Mehta <fbm3307@gmail.com>
--
> operator service-binding-operator (1.2.0)

- operators/service-binding-operator/ci.yaml
> operator [CI] service-binding-operator

- operators/cloud-native-postgresql/1.16.2/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.16.2/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.16.2/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.16.2/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.16.2/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.16.2/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.16.2/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.16.2/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.16.2/tests/scorecard/config.yaml
> operator cloud-native-postgresql (1.16.2)

- operators/cloud-native-postgresql/1.17.0/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.17.0/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.17.0/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.17.0/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.17.0/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.17.0/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.17.0/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.17.0/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.17.0/tests/scorecard/config.yaml
> operator cloud-native-postgresql (1.17.0)

- operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml
- operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml
- operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-operator-manager-config_v1_configmap.yaml
- operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-operator-webhook-service_v1_service.yaml
- operators/aerospike-kubernetes-operator/2.2.0/manifests/asdb.aerospike.com_aerospikeclusters.yaml
- operators/aerospike-kubernetes-operator/2.2.0/metadata/annotations.yaml
- operators/aerospike-kubernetes-operator/2.2.0/tests/scorecard/config.yaml
Release aerospike-kubernetes-operator 2.2.0
Signed-off-by: Ashish Shinde [ashish@aerospike.com](mailto:ashish@aerospike.com)
--
> operator aerospike-kubernetes-operator (2.2.0)

- operators/gitlab-runner-operator/1.10.0/bundle.Dockerfile
- operators/gitlab-runner-operator/1.10.0/manifests/apps.gitlab.com_runners.yaml
- operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml
- operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml
- operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml
- operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-webhook-service_v1_service.yaml
- operators/gitlab-runner-operator/1.10.0/metadata/annotations.yaml
- operators/gitlab-runner-operator/1.10.0/tests/scorecard/config.yaml
> operator gitlab-runner-operator (1.10.0)

- operators/bookkeeper-operator/0.12.2/bundle.Dockerfile
- operators/bookkeeper-operator/0.12.2/manifests/bookkeeper-operator-controller-manager-metrics-service_v1_service.yaml
- operators/bookkeeper-operator/0.12.2/manifests/bookkeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bookkeeper-operator/0.12.2/manifests/bookkeeper-operator.clusterserviceversion.yaml
- operators/bookkeeper-operator/0.12.2/manifests/bookkeeper.streamnative.io_bookkeeperclusters.yaml
- operators/bookkeeper-operator/0.12.2/metadata/annotations.yaml
- operators/bookkeeper-operator/0.12.2/tests/scorecard/config.yaml
> operator bookkeeper-operator (0.12.2)

- operators/multi-nic-cni-operator/1.0.2/bundle.Dockerfile
- operators/multi-nic-cni-operator/1.0.2/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml
- operators/multi-nic-cni-operator/1.0.2/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
- operators/multi-nic-cni-operator/1.0.2/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/multi-nic-cni-operator/1.0.2/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
- operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_cidrs.yaml
- operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_configs.yaml
- operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_deviceclasses.yaml
- operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_hostinterfaces.yaml
- operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_ippools.yaml
- operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_multinicnetworks.yaml
- operators/multi-nic-cni-operator/1.0.2/metadata/annotations.yaml
- operators/multi-nic-cni-operator/1.0.2/tests/scorecard/config.yaml
- operators/multi-nic-cni-operator/ci.yaml
Signed-off-by: Sunyanan Choochotkaew <sunyanan.choochotkaew1@ibm.com>
--
> operator [N] [CI] multi-nic-cni-operator (1.0.2)

- operators/node-maintenance-operator/0.13.1/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml
- operators/node-maintenance-operator/0.13.1/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/node-maintenance-operator/0.13.1/manifests/node-maintenance-operator-webhook-service_v1_service.yaml
- operators/node-maintenance-operator/0.13.1/manifests/node-maintenance-operator.clusterserviceversion.yaml
- operators/node-maintenance-operator/0.13.1/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml
- operators/node-maintenance-operator/0.13.1/metadata/annotations.yaml
- operators/node-maintenance-operator/0.13.1/tests/scorecard/config.yaml
- operators/node-maintenance-operator/ci.yaml
Signed-off-by: oraz <oraz@redhat.com>
--
> operator [N] [CI] node-maintenance-operator (0.13.1)

- operators/shipwright-operator/0.11.0/manifests/operator.shipwright.io_shipwrightbuilds.yaml
- operators/shipwright-operator/0.11.0/manifests/shipwright-operator-manager-config_v1_configmap.yaml
- operators/shipwright-operator/0.11.0/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/shipwright-operator/0.11.0/manifests/shipwright-operator-metrics-service_v1_service.yaml
- operators/shipwright-operator/0.11.0/manifests/shipwright-operator.clusterserviceversion.yaml
- operators/shipwright-operator/0.11.0/metadata/annotations.yaml
- operators/shipwright-operator/0.11.0/tests/scorecard/config.yaml
Update shipwright-operator to v0.11.0
Signed-off-by: Adam Kaplan <adam@adambkaplan.com>
--
> operator shipwright-operator (0.11.0)

- operators/lbconfig-operator/0.4.0/manifests/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml
- operators/lbconfig-operator/0.4.0/manifests/lbconfig-operator-controller-manager-metrics-service_v1_service.yaml
- operators/lbconfig-operator/0.4.0/manifests/lbconfig-operator-manager-config_v1_configmap.yaml
- operators/lbconfig-operator/0.4.0/manifests/lbconfig-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/lbconfig-operator/0.4.0/manifests/lbconfig-operator.clusterserviceversion.yaml
- operators/lbconfig-operator/0.4.0/metadata/annotations.yaml
- operators/lbconfig-operator/0.4.0/tests/scorecard/config.yaml
- operators/lbconfig-operator/0.4.0/tests/scorecard/kuttl/create-externalloadbalancer/01-assert.yaml
- operators/lbconfig-operator/0.4.0/tests/scorecard/kuttl/create-externalloadbalancer/10-create-elb.yaml
- operators/lbconfig-operator/0.4.0/tests/scorecard/kuttl/create-externalloadbalancer/11-assert.yaml
- operators/lbconfig-operator/0.4.0/tests/scorecard/kuttl/kuttl-test.yaml
> operator lbconfig-operator (0.4.0)

- operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.6.0-rc1/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.6.0-rc1/metadata/annotations.yaml
- operators/external-secrets-operator/0.6.0-rc1/tests/scorecard/config.yaml
bump external-secrets-operator 0.6.0-rc1
> operator external-secrets-operator (0.6.0-rc1)

- operators/microcks/1.6.0/microcks-operator.v1.6.0.clusterserviceversion.yaml
- operators/microcks/1.6.0/microcksinstall.crd.yaml
- operators/microcks/microcks.package.yaml
> operator microcks (1.6.0)

- operators/project-quay/3.8.0-rc.3/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.8.0-rc.3/quayecosystems.crd.yaml
- operators/project-quay/3.8.0-rc.3/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.8.0-rc.3 to community operators
> operator project-quay (3.8.0-rc.3)

- operators/project-quay/3.7.8/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.7.8/quayecosystems.crd.yaml
- operators/project-quay/3.7.8/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.7.8 to community operators
> operator project-quay (3.7.8)

- operators/verticadb-operator/1.7.0/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/1.7.0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/1.7.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/1.7.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/1.7.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/1.7.0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/1.7.0/metadata/annotations.yaml
- operators/verticadb-operator/1.7.0/tests/scorecard/config.yaml
> operator verticadb-operator (1.7.0)

- operators/yaks/0.11.0/instances.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.11.0/tests.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.11.0/yaks.v0.11.0.clusterserviceversion.yaml
- operators/yaks/yaks.package.yaml
> operator yaks (0.11.0)

- operators/mondoo-operator/1.4.1/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.4.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.4.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.4.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.4.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.4.1/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.4.1/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.4.1/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.4.1)

- operators/node-healthcheck-operator/0.3.2/manifests/node-healthcheck-operator-controller-manager-metrics-service_v1_service.yaml
- operators/node-healthcheck-operator/0.3.2/manifests/node-healthcheck-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/node-healthcheck-operator/0.3.2/manifests/node-healthcheck-operator.clusterserviceversion.yaml
- operators/node-healthcheck-operator/0.3.2/manifests/remediation.medik8s.io_nodehealthchecks.yaml
- operators/node-healthcheck-operator/0.3.2/metadata/annotations.yaml
- operators/node-healthcheck-operator/0.3.2/metadata/dependencies.yaml
- operators/node-healthcheck-operator/0.3.2/tests/scorecard/config.yaml
- operators/node-healthcheck-operator/ci.yaml
Signed-off-by: oraz <oraz@redhat.com>
--
> operator [CI] node-healthcheck-operator (0.3.2)

- operators/kong-gateway-operator/0.0.3/manifests/gateway-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kong-gateway-operator/0.0.3/manifests/gateway-operator-manager-config_v1_configmap.yaml
- operators/kong-gateway-operator/0.0.3/manifests/gateway-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kong-gateway-operator/0.0.3/manifests/gateway-operator.konghq.com_controlplanes.yaml
- operators/kong-gateway-operator/0.0.3/manifests/gateway-operator.konghq.com_dataplanes.yaml
- operators/kong-gateway-operator/0.0.3/manifests/gateway-operator.konghq.com_gatewayconfigurations.yaml
- operators/kong-gateway-operator/0.0.3/manifests/kong-gateway-operator.clusterserviceversion.yaml
- operators/kong-gateway-operator/0.0.3/metadata/annotations.yaml
- operators/kong-gateway-operator/0.0.3/tests/scorecard/config.yaml
> operator [N] kong-gateway-operator (0.0.3)

- operators/trivy-operator/0.2.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.2.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.2.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.2.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.2.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.2.0/trivy-operator.v0.2.0.clusterserviceversion.yaml
- operators/trivy-operator/0.2.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.2.0)

- operators/kong-gateway-operator/0.1.0/bundle.Dockerfile
- operators/kong-gateway-operator/0.1.0/manifests/gateway-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kong-gateway-operator/0.1.0/manifests/gateway-operator-manager-config_v1_configmap.yaml
- operators/kong-gateway-operator/0.1.0/manifests/gateway-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kong-gateway-operator/0.1.0/manifests/gateway-operator.konghq.com_controlplanes.yaml
- operators/kong-gateway-operator/0.1.0/manifests/gateway-operator.konghq.com_dataplanes.yaml
- operators/kong-gateway-operator/0.1.0/manifests/gateway-operator.konghq.com_gatewayconfigurations.yaml
- operators/kong-gateway-operator/0.1.0/manifests/kong-gateway-operator.clusterserviceversion.yaml
- operators/kong-gateway-operator/0.1.0/metadata/annotations.yaml
- operators/kong-gateway-operator/0.1.0/tests/scorecard/config.yaml
- operators/kong-gateway-operator/ci.yaml
> operator [CI] kong-gateway-operator (0.1.0)

- operators/mongodb-enterprise/1.17.0/bundle.Dockerfile
- operators/mongodb-enterprise/1.17.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.17.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.17.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.17.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.17.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.17.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.17.0/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.17.0/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.17.0/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.17.0/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.17.0/metadata/annotations.yaml
- operators/mongodb-enterprise/1.17.0/tests/scorecard/config.yaml
> operator mongodb-enterprise (1.17.0)

- operators/falcon-operator/0.5.5/manifests/falcon-operator-controller-manager-metrics-service_v1_service.yaml
- operators/falcon-operator/0.5.5/manifests/falcon-operator-manager-config_v1_configmap.yaml
- operators/falcon-operator/0.5.5/manifests/falcon-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/falcon-operator/0.5.5/manifests/falcon-operator.clusterserviceversion.yaml
- operators/falcon-operator/0.5.5/manifests/falcon.crowdstrike.com_falconcontainers.yaml
- operators/falcon-operator/0.5.5/manifests/falcon.crowdstrike.com_falconnodesensors.yaml
- operators/falcon-operator/0.5.5/metadata/annotations.yaml
- operators/falcon-operator/0.5.5/tests/scorecard/config.yaml
Signed-off-by: Simon Lukasik <simon.lukasik@crowdstrike.com>
--
> operator falcon-operator (0.5.5)

- operators/temporal-operator/0.1.0/bundle.Dockerfile
- operators/temporal-operator/0.1.0/manifests/temporal-operator.clusterserviceversion.yaml
- operators/temporal-operator/0.1.0/manifests/temporal.io_temporals.yaml
- operators/temporal-operator/0.1.0/metadata/annotations.yaml
- operators/temporal-operator/0.1.0/tests/scorecard/config.yaml
- operators/temporal-operator/ci.yaml
> operator [N] [CI] temporal-operator (0.1.0)

- operators/pulp-operator/0.14.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.14.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.14.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.14.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.14.0/manifests/pulp-operator.v0.14.0.clusterserviceversion.yaml
- operators/pulp-operator/0.14.0/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.14.0/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.14.0/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.14.0/metadata/annotations.yaml
- operators/pulp-operator/0.14.0/tests/scorecard/config.yaml
- operators/pulp-operator/ci.yaml
> operator [CI] pulp-operator (0.14.0)

- operators/mondoo-operator/1.5.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.5.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.5.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.5.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.5.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.5.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.5.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.5.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.5.0)

- operators/mondoo-operator/1.6.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.6.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.6.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.6.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.6.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.6.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.6.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.6.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.6.0)

- operators/rabbitmq-cluster-operator/2.0.0/bundle.Dockerfile
- operators/rabbitmq-cluster-operator/2.0.0/manifests/crds.yaml
- operators/rabbitmq-cluster-operator/2.0.0/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-cluster-operator/2.0.0/metadata/annotations.yaml
> operator rabbitmq-cluster-operator (2.0.0)

- operators/gitlab-operator-kubernetes/0.11.3/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.11.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.11.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.11.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.11.3/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.11.3/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.11.3/tests/scorecard/config.yaml
Signed-off-by: Mitchell Nielsen <me@mitchn.io>
--
> operator gitlab-operator-kubernetes (0.11.3)

- operators/temporal-operator/0.6.2/manifests/apps.alexandrevilain.dev_temporalclusterclients.yaml
- operators/temporal-operator/0.6.2/manifests/apps.alexandrevilain.dev_temporalclusters.yaml
- operators/temporal-operator/0.6.2/manifests/apps.alexandrevilain.dev_temporalnamespaces.yaml
- operators/temporal-operator/0.6.2/manifests/temporal-operator.clusterserviceversion.yaml
- operators/temporal-operator/0.6.2/metadata/annotations.yaml
> operator temporal-operator (0.6.2)

- operators/trivy-operator/0.3.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.3.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.3.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.3.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.3.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.3.0/trivy-operator.v0.3.0.clusterserviceversion.yaml
- operators/trivy-operator/0.3.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.3.0)

- operators/cc-operator/0.1.0/bundle-0.1.0.Dockerfile
- operators/cc-operator/0.1.0/manifests/cc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/cc-operator/0.1.0/manifests/cc-operator-manager-config_v1_configmap.yaml
- operators/cc-operator/0.1.0/manifests/cc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/cc-operator/0.1.0/manifests/cc-operator.clusterserviceversion.yaml
- operators/cc-operator/0.1.0/manifests/confidentialcontainers.org_ccruntimes.yaml
- operators/cc-operator/0.1.0/metadata/annotations.yaml
- operators/cc-operator/0.1.0/tests/scorecard/config.yaml
- operators/cc-operator/ci.yaml
Signed-off-by: Jens Freimann <jfreimann@redhat.com>
--
> operator [N] [CI] cc-operator (0.1.0)

- operators/function-mesh/0.6.0/bundle.Dockerfile
- operators/function-mesh/0.6.0/manifests/compute.functionmesh.io_functionmeshes.yaml
- operators/function-mesh/0.6.0/manifests/compute.functionmesh.io_functions.yaml
- operators/function-mesh/0.6.0/manifests/compute.functionmesh.io_sinks.yaml
- operators/function-mesh/0.6.0/manifests/compute.functionmesh.io_sources.yaml
- operators/function-mesh/0.6.0/manifests/function-mesh-controller-manager-metrics-service_v1_service.yaml
- operators/function-mesh/0.6.0/manifests/function-mesh-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
- operators/function-mesh/0.6.0/manifests/function-mesh-webhook-service_v1_service.yaml
- operators/function-mesh/0.6.0/manifests/function-mesh.clusterserviceversion.yaml
- operators/function-mesh/0.6.0/manifests/mesh-test-pulsar_v1_configmap.yaml
- operators/function-mesh/0.6.0/manifests/test-auth_v1_secret.yaml
- operators/function-mesh/0.6.0/manifests/test-pulsar_v1_configmap.yaml
- operators/function-mesh/0.6.0/manifests/test-secret_v1_secret.yaml
- operators/function-mesh/0.6.0/manifests/test-sink_v1_configmap.yaml
- operators/function-mesh/0.6.0/manifests/test-source_v1_configmap.yaml
- operators/function-mesh/0.6.0/manifests/test-tls_v1_secret.yaml
- operators/function-mesh/0.6.0/metadata/annotations.yaml
- operators/function-mesh/0.6.0/tests/scorecard/config.yaml
Signed-off-by: Rui Fu <freelz@gmail.com>
--
> operator function-mesh (0.6.0)

- operators/gitlab-operator-kubernetes/0.12.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.12.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.12.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.12.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.12.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.12.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.12.0/tests/scorecard/config.yaml
Signed-off-by: Hossein Pursultani <hpursultani@gitlab.com>
--
> operator gitlab-operator-kubernetes (0.12.0)

- operators/percona-postgresql-operator/1.3.0/percona-postgresql-operator.v1.3.0.clusterserviceversion.yaml
- operators/percona-postgresql-operator/1.3.0/perconapgclusters.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.3.0/pgclusters.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.3.0/pgpolicies.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.3.0/pgreplicas.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/1.3.0/pgtasks.pg.percona.com.crd.yaml
- operators/percona-postgresql-operator/percona-postgresql-operator.package.yaml
Signed-off-by: Ivan Pylypenko <ivan.pylypenko@percona.com>
* [x ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
--
<sup>2</sup> For more information …
> operator percona-postgresql-operator (1.3.0)

- operators/project-quay/3.8.0-rc.4/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.8.0-rc.4/quayecosystems.crd.yaml
- operators/project-quay/3.8.0-rc.4/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.8.0-rc.4 to community operators
> operator project-quay (3.8.0-rc.4)

- operators/rocketmq-operator/0.3.0/brokers.rocketmq.apache.org.crd.yaml
- operators/rocketmq-operator/0.3.0/consoles.rocketmq.apache.org.crd.yaml
- operators/rocketmq-operator/0.3.0/nameservices.rocketmq.apache.org.crd.yaml
- operators/rocketmq-operator/0.3.0/rocketmq-operator.0.3.0.clusterserviceversion.yaml
- operators/rocketmq-operator/0.3.0/topictransfers.rocketmq.apache.org.crd.yaml
- operators/rocketmq-operator/ci.yaml
- operators/rocketmq-operator/rocketmq-operator.package.yaml
Signed-off-by: caigy <csgytsai@163.com>
--
> operator [CI] rocketmq-operator (0.3.0)

- operators/mondoo-operator/1.6.1/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.6.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.6.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.6.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.6.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.6.1/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.6.1/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.6.1/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.6.1)

- operators/dynatrace-operator/0.9.0/Dockerfile
- operators/dynatrace-operator/0.9.0/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.9.0/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml
- operators/dynatrace-operator/0.9.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/0.9.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/0.9.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml
- operators/dynatrace-operator/0.9.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/dynatrace-operator/0.9.0/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.9.0/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/0.9.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/0.9.0/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/0.9.0/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.9.0/metadata/annotations.yaml
> operator dynatrace-operator (0.9.0)

- operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml
- operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml
- operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-operator-manager-config_v1_configmap.yaml
- operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-operator-webhook-service_v1_service.yaml
- operators/aerospike-kubernetes-operator/2.2.1/manifests/asdb.aerospike.com_aerospikeclusters.yaml
- operators/aerospike-kubernetes-operator/2.2.1/metadata/annotations.yaml
- operators/aerospike-kubernetes-operator/2.2.1/tests/scorecard/config.yaml
Signed-off-by: Ashish Shinde <ashish@aerospike.com>
--
> operator aerospike-kubernetes-operator (2.2.1)

- operators/cass-operator-community/1.13.0/manifests/cass-operator-manager-config_v1_configmap.yaml
- operators/cass-operator-community/1.13.0/manifests/cass-operator-webhook-service_v1_service.yaml
- operators/cass-operator-community/1.13.0/manifests/cass-operator.clusterserviceversion.yaml
- operators/cass-operator-community/1.13.0/manifests/cassandra.datastax.com_cassandradatacenters.yaml
- operators/cass-operator-community/1.13.0/manifests/control.k8ssandra.io_cassandratasks.yaml
- operators/cass-operator-community/1.13.0/metadata/annotations.yaml
- operators/cass-operator-community/1.13.0/tests/scorecard/config.yaml
> operator cass-operator-community (1.13.0)

- operators/deployment-validation-operator/0.3.0/manifests/deploymentvalidationoperator.0.3.0.clusterserviceversion.yaml
> operator [O] deployment-validation-operator (0.3.0)

- operators/dell-csi-operator/1.9.0/csiisilons.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.9.0/csipowermaxes.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.9.0/csipowermaxrevproxies.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.9.0/csipowerstores.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.9.0/csiunities.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.9.0/csivxflexoses.storage.dell.com.crd.yaml
- operators/dell-csi-operator/1.9.0/dell-csi-operator.v1.9.0.clusterserviceversion.yaml
- operators/dell-csi-operator/dell-csi-operator.package.yaml
> operator dell-csi-operator (1.9.0)

- operators/temporal-operator/0.7.0/manifests/temporal-operator.clusterserviceversion.yaml
- operators/temporal-operator/0.7.0/manifests/temporal.io_temporalclusterclients.yaml
- operators/temporal-operator/0.7.0/manifests/temporal.io_temporalclusters.yaml
- operators/temporal-operator/0.7.0/manifests/temporal.io_temporalnamespaces.yaml
- operators/temporal-operator/0.7.0/metadata/annotations.yaml
> operator temporal-operator (0.7.0)

- operators/pulp-operator/0.14.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/0.14.1/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.14.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/0.14.1/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml
- operators/pulp-operator/0.14.1/manifests/pulp-operator.v0.14.1.clusterserviceversion.yaml
- operators/pulp-operator/0.14.1/manifests/pulp.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/0.14.1/manifests/pulp.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/0.14.1/manifests/pulp.pulpproject.org_pulps.yaml
- operators/pulp-operator/0.14.1/metadata/annotations.yaml
- operators/pulp-operator/0.14.1/tests/scorecard/config.yaml
> operator pulp-operator (0.14.1)

- operators/edp-keycloak-operator/1.13.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloakclients.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
- operators/edp-keycloak-operator/1.13.0/manifests/v1.edp.epam.com_keycloaks.yaml
- operators/edp-keycloak-operator/1.13.0/metadata/annotations.yaml
- operators/edp-keycloak-operator/1.13.0/tests/scorecard/config.yaml
- operators/edp-keycloak-operator/ci.yaml
Signed-off-by: Sergiy Kulanov <sergiy_kulanov@epam.com>
--
> operator [N] [CI] edp-keycloak-operator (1.13.0)

- operators/tackle-operator/2.1.1/manifests/tackle-operator.clusterserviceversion.yaml
- operators/tackle-operator/2.1.1/manifests/tackle.konveyor.io_addons.yaml
- operators/tackle-operator/2.1.1/manifests/tackle.konveyor.io_tackles.yaml
- operators/tackle-operator/2.1.1/metadata/annotations.yaml
> operator tackle-operator (2.1.1)

- operators/kube-green/0.4.1/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml
- operators/kube-green/0.4.1/manifests/kube-green-manager-config_v1_configmap.yaml
- operators/kube-green/0.4.1/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kube-green/0.4.1/manifests/kube-green-webhook-service_v1_service.yaml
- operators/kube-green/0.4.1/manifests/kube-green.clusterserviceversion.yaml
- operators/kube-green/0.4.1/manifests/kube-green.com_sleepinfos.yaml
- operators/kube-green/0.4.1/metadata/annotations.yaml
- operators/kube-green/0.4.1/tests/scorecard/config.yaml
* [] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
-- …
> operator kube-green (0.4.1)

- operators/eginnovations-operator/0.0.2/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml
- operators/eginnovations-operator/0.0.2/manifests/eginnovations-operator-manager-config_v1_configmap.yaml
- operators/eginnovations-operator/0.0.2/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/eginnovations-operator/0.0.2/manifests/eginnovations-operator-webhook-service_v1_service.yaml
- operators/eginnovations-operator/0.0.2/manifests/eginnovations-operator.clusterserviceversion.yaml
- operators/eginnovations-operator/0.0.2/manifests/eginnovations.com_eguniversalagents.yaml
- operators/eginnovations-operator/0.0.2/metadata/annotations.yaml
- operators/eginnovations-operator/0.0.2/tests/scorecard/config.yaml
- operators/eginnovations-operator/ci.yaml
Signed-off-by: Gaurav Singh <gauravsingh.r@eginnovations.com>
--
> operator [CI] eginnovations-operator (0.0.2)

- operators/rabbitmq-messaging-topology-operator/1.9.0/bundle.Dockerfile
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_bindings.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_exchanges.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_federations.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_permissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_policies.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_queues.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_schemareplications.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_shovels.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_superstreams.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_topicpermissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_users.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.com_vhosts.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/manifests/rabbitmq.webhook-service.yaml
- operators/rabbitmq-messaging-topology-operator/1.9.0/metadata/annotations.yaml
> operator rabbitmq-messaging-topology-operator (1.9.0)

- operators/grafana-operator/4.7.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml
- operators/grafana-operator/4.7.0/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/4.7.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/4.7.0/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/4.7.0/integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/4.7.0/integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/4.7.0/integreatly.org_grafanafolders.yaml
- operators/grafana-operator/4.7.0/integreatly.org_grafananotificationchannels.yaml
- operators/grafana-operator/4.7.0/integreatly.org_grafanas.yaml
- operators/grafana-operator/grafana-operator.package.yaml
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>
--
> operator grafana-operator (4.7.0)

- operators/mongodb-enterprise/1.17.1/bundle.Dockerfile
- operators/mongodb-enterprise/1.17.1/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.17.1/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.17.1/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.17.1/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.17.1/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.17.1/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.17.1/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.17.1/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.17.1/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.17.1/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.17.1/metadata/annotations.yaml
- operators/mongodb-enterprise/1.17.1/tests/scorecard/config.yaml
> operator mongodb-enterprise (1.17.1)

- operators/cloud-native-postgresql/1.15.5/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.15.5/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.15.5/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.15.5/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.15.5/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.15.5/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.15.5/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.15.5/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.15.5/tests/scorecard/config.yaml
> operator cloud-native-postgresql (1.15.5)

- operators/service-binding-operator/1.3.0/manifests/binding.operators.coreos.com_bindablekinds.yaml
- operators/service-binding-operator/1.3.0/manifests/binding.operators.coreos.com_servicebindings.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-clusterworkloadresourcemappings-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-clusterworkloadresourcemappings-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-manager-config_v1_configmap.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-operator.clusterserviceversion.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.0/manifests/service-binding-webhook-service_v1_service.yaml
- operators/service-binding-operator/1.3.0/manifests/servicebinding.io_clusterworkloadresourcemappings.yaml
- operators/service-binding-operator/1.3.0/manifests/servicebinding.io_servicebindings.yaml
- operators/service-binding-operator/1.3.0/metadata/annotations.yaml
> operator service-binding-operator (1.3.0)

- operators/cloud-native-postgresql/1.16.3/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.16.3/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.16.3/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.16.3/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.16.3/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.16.3/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.16.3/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.16.3/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.16.3/tests/scorecard/config.yaml
> operator cloud-native-postgresql (1.16.3)

- operators/cloud-native-postgresql/1.17.1/manifests/cloud-native-postgresql.clusterserviceversion.yaml
- operators/cloud-native-postgresql/1.17.1/manifests/postgresql-operator-default-monitoring_v1_configmap.yaml
- operators/cloud-native-postgresql/1.17.1/manifests/postgresql-operator-webhook-service_v1_service.yaml
- operators/cloud-native-postgresql/1.17.1/manifests/postgresql.k8s.enterprisedb.io_backups.yaml
- operators/cloud-native-postgresql/1.17.1/manifests/postgresql.k8s.enterprisedb.io_clusters.yaml
- operators/cloud-native-postgresql/1.17.1/manifests/postgresql.k8s.enterprisedb.io_poolers.yaml
- operators/cloud-native-postgresql/1.17.1/manifests/postgresql.k8s.enterprisedb.io_scheduledbackups.yaml
- operators/cloud-native-postgresql/1.17.1/metadata/annotations.yaml
- operators/cloud-native-postgresql/1.17.1/tests/scorecard/config.yaml
> operator cloud-native-postgresql (1.17.1)

- operators/app-director-operator/0.8.0/manifests/app-director-operator.clusterserviceversion.yaml
Signed-off-by: Rosa Lopes <rosa.lopes@randoli.ca>
--
> operator [O] app-director-operator (0.8.0)

- operators/datadog-operator/0.8.2/manifests/datadog-operator.clusterserviceversion.yaml
- operators/datadog-operator/0.8.2/manifests/datadoghq.com_datadogagents.yaml
- operators/datadog-operator/0.8.2/manifests/datadoghq.com_datadogmetrics.yaml
- operators/datadog-operator/0.8.2/manifests/datadoghq.com_datadogmonitors.yaml
- operators/datadog-operator/0.8.2/metadata/annotations.yaml
- operators/datadog-operator/0.8.2/tests/scorecard/config.yaml
> operator datadog-operator (0.8.2)

- operators/external-secrets-operator/0.6.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.6.0/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.6.0/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.6.0/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.6.0/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.6.0/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.6.0/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.6.0/metadata/annotations.yaml
- operators/external-secrets-operator/0.6.0/tests/scorecard/config.yaml
bump external-secrets-operator 0.6.0
> operator external-secrets-operator (0.6.0)

- operators/mondoo-operator/1.6.3/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.6.3/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.6.3/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.6.3/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.6.3/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.6.3/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.6.3/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.6.3/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.6.3)

- operators/ibm-security-verify-access-operator/22.10.0/manifests/ibm-security-verify-access-operator.clusterserviceversion.yaml
- operators/ibm-security-verify-access-operator/22.10.0/manifests/ibm.com_ibmsecurityverifyaccesses.yaml
- operators/ibm-security-verify-access-operator/22.10.0/manifests/verify-access-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ibm-security-verify-access-operator/22.10.0/manifests/verify-access-operator-controller-manager-snapshot-service_v1_service.yaml
- operators/ibm-security-verify-access-operator/22.10.0/manifests/verify-access-operator-manager-config_v1_configmap.yaml
- operators/ibm-security-verify-access-operator/22.10.0/manifests/verify-access-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ibm-security-verify-access-operator/22.10.0/metadata/annotations.yaml
- operators/ibm-security-verify-access-operator/22.10.0/tests/scorecard/config.yaml
Signed-off-by: asha <ashashiv@au1.ibm.com>
--
> operator ibm-security-verify-access-operator (22.10.0)

- operators/awx-operator/0.30.0/bundle.Dockerfile
- operators/awx-operator/0.30.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/0.30.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/0.30.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/0.30.0/manifests/awx-operator.v0.30.0.clusterserviceversion.yaml
- operators/awx-operator/0.30.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/0.30.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/0.30.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/0.30.0/metadata/annotations.yaml
- operators/awx-operator/0.30.0/tests/scorecard/config.yaml
- operators/awx-operator/ci.yaml
https://github.com/ansible/awx
https://github.com/ansible/awx-operator
Signed-off-by: Ompragash Viswanathan <ompragash@proton.me>
Thanks for submitting your Operator. Please check the below list before you create your Pull Request.
--
<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-l …
> operator [N] [CI] awx-operator (0.30.0)

- operators/camel-k/1.10.1/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.10.1/manifests/camel-k.v1.10.1.clusterserviceversion.yaml
- operators/camel-k/1.10.1/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.10.1/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.10.1/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.10.1/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.10.1/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.10.1/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/1.10.1/metadata/annotations.yaml
- operators/camel-k/1.10.1/tests/scorecard/config.yaml
> operator camel-k (1.10.1)

- operators/redis-operator/0.12.0/manifests/redis-operator.v0.12.0.clusterserviceversion.yaml
- operators/redis-operator/0.12.0/manifests/redis.redis.redis.opstreelabs.in.crd.yaml
- operators/redis-operator/0.12.0/manifests/redisclusters.redis.redis.opstreelabs.in.crd.yaml
- operators/redis-operator/0.12.0/metadata/annotations.yaml
> operator redis-operator (0.12.0)

- operators/redis-operator/0.12.0/manifests/redis-operator.v0.12.0.clusterserviceversion.yaml
> operator [O] redis-operator (0.12.0)

- operators/camel-karavan-operator/3.18.5/manifests/camel-karavan-operator.v3.18.5.clusterserviceversion.yaml
- operators/camel-karavan-operator/3.18.5/manifests/karavans.camel.apache.org.crd.yml
Signed-off-by: Marat Gubaidullin <marat.gubaidullin@gmail.com>
--
> operator [N] camel-karavan-operator (3.18.5)

- operators/project-quay/3.7.9/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.7.9/quayecosystems.crd.yaml
- operators/project-quay/3.7.9/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.7.9 to community operators
> operator project-quay (3.7.9)

- operators/mongodb-enterprise/1.17.2/bundle.Dockerfile
- operators/mongodb-enterprise/1.17.2/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
- operators/mongodb-enterprise/1.17.2/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/mongodb-enterprise/1.17.2/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.17.2/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.17.2/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
- operators/mongodb-enterprise/1.17.2/manifests/mongodb-enterprise.clusterserviceversion.yaml
- operators/mongodb-enterprise/1.17.2/manifests/mongodb.com_mongodb.yaml
- operators/mongodb-enterprise/1.17.2/manifests/mongodb.com_mongodbmulti.yaml
- operators/mongodb-enterprise/1.17.2/manifests/mongodb.com_mongodbusers.yaml
- operators/mongodb-enterprise/1.17.2/manifests/mongodb.com_opsmanagers.yaml
- operators/mongodb-enterprise/1.17.2/metadata/annotations.yaml
- operators/mongodb-enterprise/1.17.2/tests/scorecard/config.yaml
> operator mongodb-enterprise (1.17.2)

- operators/security-profiles-operator/0.5.0/bundle.Dockerfile
- operators/security-profiles-operator/0.5.0/manifests/metrics-token_v1_secret.yaml
- operators/security-profiles-operator/0.5.0/manifests/security-profiles-operator-profile_v1_configmap.yaml
- operators/security-profiles-operator/0.5.0/manifests/security-profiles-operator.clusterserviceversion.yaml
- operators/security-profiles-operator/0.5.0/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
- operators/security-profiles-operator/0.5.0/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
- operators/security-profiles-operator/0.5.0/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
- operators/security-profiles-operator/0.5.0/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
- operators/security-profiles-operator/0.5.0/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
- operators/security-profiles-operator/0.5.0/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
- operators/security-profiles-operator/0.5.0/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
- operators/security-profiles-operator/0.5.0/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
- operators/security-profiles-operator/0.5.0/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/security-profiles-operator/0.5.0/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/security-profiles-operator/0.5.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/security-profiles-operator/0.5.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/security-profiles-operator/0.5.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
- operators/security-profiles-operator/0.5.0/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/security-profiles-operator/0.5.0/manifests/spo-webhook_v1_serviceaccount.yaml
- operators/security-profiles-operator/0.5.0/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/security-profiles-operator/0.5.0/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/security-profiles-operator/0.5.0/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
- operators/security-profiles-operator/0.5.0/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/security-profiles-operator/0.5.0/manifests/spod_v1_serviceaccount.yaml
- operators/security-profiles-operator/0.5.0/metadata/annotations.yaml
- operators/security-profiles-operator/0.5.0/tests/scorecard/config.yaml
--
Refers to https://github.com/kubernetes-sigs/security-profiles-operator/issues/1144
> operator security-profiles-operator (0.5.0)

- operators/mondoo-operator/1.6.4/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.6.4/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.6.4/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.6.4/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.6.4/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.6.4/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.6.4/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.6.4/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.6.4)

- operators/trivy-operator/0.4.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.4.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.4.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.4.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.4.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.4.0/trivy-operator.v0.4.0.clusterserviceversion.yaml
- operators/trivy-operator/0.4.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.4.0)

- operators/kiali/1.57.0/bundle.Dockerfile
- operators/kiali/1.57.0/manifests/kiali.crd.yaml
- operators/kiali/1.57.0/manifests/kiali.v1.57.0.clusterserviceversion.yaml
- operators/kiali/1.57.0/metadata/annotations.yaml
- operators/kiali/1.58.0/bundle.Dockerfile
- operators/kiali/1.58.0/manifests/kiali.crd.yaml
- operators/kiali/1.58.0/manifests/kiali.v1.58.0.clusterserviceversion.yaml
- operators/kiali/1.58.0/metadata/annotations.yaml
> operator [R] kiali (1.57.0 1.58.0)

- operators/app-director-operator/0.9.0/Dockerfile
- operators/app-director-operator/0.9.0/manifests/app-director-controller-manager-metrics-service_v1_service.yaml
- operators/app-director-operator/0.9.0/manifests/app-director-manager-config_v1_configmap.yaml
- operators/app-director-operator/0.9.0/manifests/app-director-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/app-director-operator/0.9.0/manifests/app-director-operator.clusterserviceversion.yaml
- operators/app-director-operator/0.9.0/manifests/appdirector.randoli.ca_appdirectoragents.yaml
- operators/app-director-operator/0.9.0/manifests/appdirector.randoli.ca_clusterwideappdirectoragents.yaml
- operators/app-director-operator/0.9.0/metadata/annotations.yaml
- operators/app-director-operator/0.9.0/tests/scorecard/config.yaml
Signed-off-by: Rosa Lopes <rosa.lopes@randoli.ca>
--
> operator app-director-operator (0.9.0)

- operators/camel-k/1.10.2/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/1.10.2/manifests/camel-k.v1.10.2.clusterserviceversion.yaml
- operators/camel-k/1.10.2/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/1.10.2/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/1.10.2/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/1.10.2/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/1.10.2/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/1.10.2/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/1.10.2/metadata/annotations.yaml
- operators/camel-k/1.10.2/tests/scorecard/config.yaml
> operator camel-k (1.10.2)

- operators/dynatrace-operator/0.9.1/Dockerfile
- operators/dynatrace-operator/0.9.1/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.9.1/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml
- operators/dynatrace-operator/0.9.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/0.9.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/0.9.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml
- operators/dynatrace-operator/0.9.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/dynatrace-operator/0.9.1/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.9.1/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/0.9.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/0.9.1/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/0.9.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.9.1/metadata/annotations.yaml
> operator dynatrace-operator (0.9.1)

- operators/function-mesh/0.7.0/bundle.Dockerfile
- operators/function-mesh/0.7.0/manifests/compute.functionmesh.io_functionmeshes.yaml
- operators/function-mesh/0.7.0/manifests/compute.functionmesh.io_functions.yaml
- operators/function-mesh/0.7.0/manifests/compute.functionmesh.io_sinks.yaml
- operators/function-mesh/0.7.0/manifests/compute.functionmesh.io_sources.yaml
- operators/function-mesh/0.7.0/manifests/function-mesh-controller-manager-metrics-service_v1_service.yaml
- operators/function-mesh/0.7.0/manifests/function-mesh-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
- operators/function-mesh/0.7.0/manifests/function-mesh-webhook-service_v1_service.yaml
- operators/function-mesh/0.7.0/manifests/function-mesh.clusterserviceversion.yaml
- operators/function-mesh/0.7.0/manifests/mesh-test-pulsar_v1_configmap.yaml
- operators/function-mesh/0.7.0/manifests/test-auth_v1_secret.yaml
- operators/function-mesh/0.7.0/manifests/test-pulsar_v1_configmap.yaml
- operators/function-mesh/0.7.0/manifests/test-secret_v1_secret.yaml
- operators/function-mesh/0.7.0/manifests/test-sink_v1_configmap.yaml
- operators/function-mesh/0.7.0/manifests/test-source_v1_configmap.yaml
- operators/function-mesh/0.7.0/manifests/test-tls_v1_secret.yaml
- operators/function-mesh/0.7.0/metadata/annotations.yaml
- operators/function-mesh/0.7.0/tests/scorecard/config.yaml
Signed-off-by: Rui Fu <freelz@gmail.com>
--
> operator function-mesh (0.7.0)

- operators/flux/0.35.0/manifests/alert.crd.yaml
- operators/flux/0.35.0/manifests/bucket.crd.yaml
- operators/flux/0.35.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.35.0/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.35.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.35.0/manifests/flux.v0.35.0.clusterserviceversion.yaml
- operators/flux/0.35.0/manifests/gitrepository.crd.yaml
- operators/flux/0.35.0/manifests/helmchart.crd.yaml
- operators/flux/0.35.0/manifests/helmrelease.crd.yaml
- operators/flux/0.35.0/manifests/helmrepository.crd.yaml
- operators/flux/0.35.0/manifests/imagepolicy.crd.yaml
- operators/flux/0.35.0/manifests/imagerepository.crd.yaml
- operators/flux/0.35.0/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.35.0/manifests/kustomization.crd.yaml
- operators/flux/0.35.0/manifests/notification-controller.service.yaml
- operators/flux/0.35.0/manifests/ocirepository.crd.yaml
- operators/flux/0.35.0/manifests/provider.crd.yaml
- operators/flux/0.35.0/manifests/receiver.crd.yaml
- operators/flux/0.35.0/manifests/source-controller.service.yaml
- operators/flux/0.35.0/manifests/webhook-receiver.service.yaml
- operators/flux/0.35.0/metadata/annotations.yaml
> operator flux (0.35.0)

- operators/grafana-operator/4.7.1/grafana-operator-controller-manager-metrics-service_v1_service.yaml
- operators/grafana-operator/4.7.1/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/4.7.1/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/4.7.1/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/4.7.1/integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/4.7.1/integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/4.7.1/integreatly.org_grafanafolders.yaml
- operators/grafana-operator/4.7.1/integreatly.org_grafananotificationchannels.yaml
- operators/grafana-operator/4.7.1/integreatly.org_grafanas.yaml
- operators/grafana-operator/grafana-operator.package.yaml
> operator grafana-operator (4.7.1)

- operators/service-binding-operator/1.3.1/manifests/binding.operators.coreos.com_bindablekinds.yaml
- operators/service-binding-operator/1.3.1/manifests/binding.operators.coreos.com_servicebindings.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-bindablekinds-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-bindablekinds-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-cloud-native-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-clusterworkloadresourcemappings-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-clusterworkloadresourcemappings-viewer-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-controller-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-crunchy-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-manager-config_v1_configmap.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-operator.clusterserviceversion.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-opstree-redis-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-percona-mongodb-view_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-percona-mysql-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-rabbitmq-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/service-binding-operator/1.3.1/manifests/service-binding-webhook-service_v1_service.yaml
- operators/service-binding-operator/1.3.1/manifests/servicebinding.io_clusterworkloadresourcemappings.yaml
- operators/service-binding-operator/1.3.1/manifests/servicebinding.io_servicebindings.yaml
- operators/service-binding-operator/1.3.1/metadata/annotations.yaml
- operators/service-binding-operator/1.3.1/tests/scorecard/config.yaml
Signed-off-by: Andy Sadler <ansadler@redhat.com>
--
> operator service-binding-operator (1.3.1)

- operators/kubero-operator/0.0.70/manifests/application.kubero.dev_kuberoapps.yaml
- operators/kubero-operator/0.0.70/manifests/application.kubero.dev_kuberoes.yaml
- operators/kubero-operator/0.0.70/manifests/application.kubero.dev_kuberopipelines.yaml
- operators/kubero-operator/0.0.70/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kubero-operator/0.0.70/manifests/kubero-operator-manager-config_v1_configmap.yaml
- operators/kubero-operator/0.0.70/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kubero-operator/0.0.70/manifests/kubero-operator.clusterserviceversion.yaml
- operators/kubero-operator/0.0.70/metadata/annotations.yaml
- operators/kubero-operator/0.0.70/tests/scorecard/config.yaml
- operators/kubero-operator/ci.yaml
> operator [N] [CI] kubero-operator (0.0.70)

- operators/gitlab-operator-kubernetes/0.12.3/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.12.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.12.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.12.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.12.3/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.12.3/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.12.3/tests/scorecard/config.yaml
Signed-off-by: Hossein Pursultani <hpursultani@gitlab.com>
--
> operator gitlab-operator-kubernetes (0.12.3)

- operators/flux/0.36.0/manifests/alert.crd.yaml
- operators/flux/0.36.0/manifests/bucket.crd.yaml
- operators/flux/0.36.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/0.36.0/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/0.36.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/0.36.0/manifests/flux.v0.36.0.clusterserviceversion.yaml
- operators/flux/0.36.0/manifests/gitrepository.crd.yaml
- operators/flux/0.36.0/manifests/helmchart.crd.yaml
- operators/flux/0.36.0/manifests/helmrelease.crd.yaml
- operators/flux/0.36.0/manifests/helmrepository.crd.yaml
- operators/flux/0.36.0/manifests/imagepolicy.crd.yaml
- operators/flux/0.36.0/manifests/imagerepository.crd.yaml
- operators/flux/0.36.0/manifests/imageupdateautomation.crd.yaml
- operators/flux/0.36.0/manifests/kustomization.crd.yaml
- operators/flux/0.36.0/manifests/notification-controller.service.yaml
- operators/flux/0.36.0/manifests/ocirepository.crd.yaml
- operators/flux/0.36.0/manifests/provider.crd.yaml
- operators/flux/0.36.0/manifests/receiver.crd.yaml
- operators/flux/0.36.0/manifests/source-controller.service.yaml
- operators/flux/0.36.0/manifests/webhook-receiver.service.yaml
- operators/flux/0.36.0/metadata/annotations.yaml
> operator flux (0.36.0)

- operators/portworx/1.10.0/core_v1_storagecluster_crd.yaml
- operators/portworx/1.10.0/core_v1_storagenode_crd.yaml
- operators/portworx/1.10.0/portworxoperator.clusterserviceversion.yaml
- operators/portworx/portworx.package.yaml
Signed-off-by: Jiafeng Liao <jliao@purestorage.com>
--
> operator portworx (1.10.0)

- operators/gitlab-operator-kubernetes/ci.yaml
> operator [CI] gitlab-operator-kubernetes

- operators/netobserv-operator/0.2.0/bundle.Dockerfile
- operators/netobserv-operator/0.2.0/manifests/flows.netobserv.io_flowcollectors.yaml
- operators/netobserv-operator/0.2.0/manifests/netobserv-manager-config_v1_configmap.yaml
- operators/netobserv-operator/0.2.0/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/netobserv-operator/0.2.0/manifests/netobserv-metrics-service_v1_service.yaml
- operators/netobserv-operator/0.2.0/manifests/netobserv-operator.clusterserviceversion.yaml
- operators/netobserv-operator/0.2.0/metadata/annotations.yaml
> operator netobserv-operator (0.2.0)

- operators/mondoo-operator/1.7.0/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.7.0/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.7.0/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.7.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.7.0/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.7.0/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.7.0/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.7.0/mondoo-operator-webhook_v1_serviceaccount.yaml
- operators/mondoo-operator/1.7.0/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.7.0)

- operators/flink-kubernetes-operator/1.1.0/manifests/flink-kubernetes-operator.clusterserviceversion.yaml
- operators/flink-kubernetes-operator/1.2.0/manifests/flink-kubernetes-operator.clusterserviceversion.yaml
Signed-off-by: James Busche <jbusche@us.ibm.com>
--
> operator [R] flink-kubernetes-operator (1.1.0 1.2.0)

- operators/flink-kubernetes-operator/1.0.1/manifests/flink-kubernetes-operator.clusterserviceversion.yaml
- operators/flink-kubernetes-operator/1.1.0/manifests/flink-kubernetes-operator.clusterserviceversion.yaml
- operators/flink-kubernetes-operator/1.2.0/manifests/flink-kubernetes-operator.clusterserviceversion.yaml
Signed-off-by: James Busche <jbusche@us.ibm.com>
--
> operator [R] flink-kubernetes-operator (1.0.1 1.1.0 1.2.0)

- operators/kubero-operator/0.0.71/manifests/application.kubero.dev_kuberoapps.yaml
- operators/kubero-operator/0.0.71/manifests/application.kubero.dev_kuberoes.yaml
- operators/kubero-operator/0.0.71/manifests/application.kubero.dev_kuberopipelines.yaml
- operators/kubero-operator/0.0.71/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kubero-operator/0.0.71/manifests/kubero-operator-manager-config_v1_configmap.yaml
- operators/kubero-operator/0.0.71/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kubero-operator/0.0.71/manifests/kubero-operator.clusterserviceversion.yaml
- operators/kubero-operator/0.0.71/metadata/annotations.yaml
- operators/kubero-operator/0.0.71/tests/scorecard/config.yaml
> operator kubero-operator (0.0.71)

- operators/gitlab-operator-kubernetes/0.13.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.13.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.13.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.13.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.13.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.13.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.13.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.13.0)

- operators/mongodb-atlas-kubernetes/1.4.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/1.4.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/1.4.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/1.4.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/1.4.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/1.4.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/1.4.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/1.4.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/1.4.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/1.4.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/1.4.0/tests/scorecard/config.yaml
Signed-off-by: Timur_Akhmadiev <Timur_Akhmadiev@epam.com>
--
> operator mongodb-atlas-kubernetes (1.4.0)

- operators/gitlab-operator-kubernetes/0.13.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.13.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.13.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.13.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.13.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.13.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.13.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.13.1)

- operators/external-secrets-operator/0.6.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.6.1/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.6.1/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.6.1/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.6.1/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.6.1/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.6.1/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.6.1/metadata/annotations.yaml
- operators/external-secrets-operator/0.6.1/tests/scorecard/config.yaml
bump external-secrets-operator 0.6.1
> operator external-secrets-operator (0.6.1)

- operators/trivy-operator/0.5.0/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.5.0/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.5.0/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.5.0/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.5.0/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/0.5.0/trivy-operator.v0.5.0.clusterserviceversion.yaml
- operators/trivy-operator/0.5.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- operators/trivy-operator/trivy-operator.package.yaml
> operator trivy-operator (0.5.0)

- operators/cluster-manager/0.9.1/cluster-manager.clusterserviceversion.yaml
- operators/cluster-manager/0.9.1/operator.open-cluster-management.io_clustermanagers.yaml
- operators/cluster-manager/cluster-manger.package.yaml
> operator cluster-manager (0.9.1)

- operators/klusterlet/0.9.1/klusterlet.clusterserviceversion.yaml
- operators/klusterlet/0.9.1/operator.open-cluster-management.io_klusterlets.yaml
- operators/klusterlet/klusterlet.package.yaml
> operator klusterlet (0.9.1)

- operators/knative-operator/1.8.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.8.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.8.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.8.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.8.0/manifests/knative-operator-config-logging_v1_configmap.yaml
- operators/knative-operator/1.8.0/manifests/knative-operator-config-observability_v1_configmap.yaml
- operators/knative-operator/1.8.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
- operators/knative-operator/1.8.0/manifests/knative-operator-operator-webhook_v1_service.yaml
- operators/knative-operator/1.8.0/manifests/knative-operator.v1.8.0.clusterserviceversion.yaml
- operators/knative-operator/1.8.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.8.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.8.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/knative-operator/1.8.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/knative-operator/1.8.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.8.0/manifests/knativeservings.operator.knative.dev.crd.yaml
- operators/knative-operator/1.8.0/metadata/annotations.yaml
- operators/knative-operator/1.8.0/tests/scorecard/config.yaml
> operator knative-operator (1.8.0)

- operators/project-quay/3.8.0-rc.5/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.8.0-rc.5/quayecosystems.crd.yaml
- operators/project-quay/3.8.0-rc.5/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.8.0-rc.5 to community operators
> operator project-quay (3.8.0-rc.5)

- operators/project-quay/3.7.10/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.7.10/quayecosystems.crd.yaml
- operators/project-quay/3.7.10/quayregistries.crd.yaml
- operators/project-quay/project-quay.package.yaml
Add v3.7.10 to community operators
> operator project-quay (3.7.10)

- operators/mondoo-operator/1.7.1/k8s.mondoo.com_mondooauditconfigs.yaml
- operators/mondoo-operator/1.7.1/k8s.mondoo.com_mondoooperatorconfigs.yaml
- operators/mondoo-operator/1.7.1/mondoo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/mondoo-operator/1.7.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mondoo-operator/1.7.1/mondoo-operator-k8s-resources-scanning_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/mondoo-operator/1.7.1/mondoo-operator-k8s-resources-scanning_v1_serviceaccount.yaml
- operators/mondoo-operator/1.7.1/mondoo-operator-manager-config_v1_configmap.yaml
- operators/mondoo-operator/1.7.1/mondoo-operator-webhook_v1_serviceaccount.yaml
- operators/mondoo-operator/1.7.1/mondoo-operator.clusterserviceversion.yaml
- operators/mondoo-operator/mondoo-operator.package.yaml
> operator mondoo-operator (1.7.1)

- operators/windup-operator/0.0.11/manifests/windup-operator.clusterserviceversion.yaml
- operators/windup-operator/0.0.11/manifests/windup.crd.yaml
- operators/windup-operator/0.0.11/metadata/annotations.yaml
> operator [N] windup-operator (0.0.11)

- operators/ibm-application-gateway-operator/22.11.0/manifests/ibm-application-gateway-operator-ctrl-mgr-metrics-service_v1_service.yaml
- operators/ibm-application-gateway-operator/22.11.0/manifests/ibm-application-gateway-operator-manager-config_v1_configmap.yaml
- operators/ibm-application-gateway-operator/22.11.0/manifests/ibm-application-gateway-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ibm-application-gateway-operator/22.11.0/manifests/ibm-application-gateway-operator-webhook-service_v1_service.yaml
- operators/ibm-application-gateway-operator/22.11.0/manifests/ibm-application-gateway-operator.clusterserviceversion.yaml
- operators/ibm-application-gateway-operator/22.11.0/manifests/ibm.com_ibmapplicationgateways.yaml
- operators/ibm-application-gateway-operator/22.11.0/metadata/annotations.yaml
- operators/ibm-application-gateway-operator/22.11.0/tests/scorecard/config.yaml
- operators/ibm-application-gateway-operator/ci.yaml
Signed-off-by: KEIRAN ROBINSON <krobinson@au1.ibm.com>
--
> operator [CI] ibm-application-gateway-operator (22.11.0)

- operators/gitlab-operator-kubernetes/0.13.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.13.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.13.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.13.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.13.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.13.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.13.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.13.2)

- operators/pulp-operator/1.0.0-alpha.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/1.0.0-alpha.1/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/1.0.0-alpha.1/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/1.0.0-alpha.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/1.0.0-alpha.1/manifests/pulp-operator.v1.0.0-alpha.1.clusterserviceversion.yaml
- operators/pulp-operator/1.0.0-alpha.1/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/1.0.0-alpha.1/manifests/repo-manager.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/1.0.0-alpha.1/manifests/repo-manager.pulpproject.org_pulps.yaml
- operators/pulp-operator/1.0.0-alpha.1/metadata/annotations.yaml
- operators/pulp-operator/1.0.0-alpha.1/tests/scorecard/config.yaml
> operator [R] pulp-operator (0.14.1 1.0.0-alpha.1)
