k8s-operatorhub/community-operators

operators/clickhouse/0.22.1/manifests/clickhouse-operator.v0.22.1.clusterserviceversion.yaml
operators/clickhouse/0.22.1/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.22.1/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.22.1/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.22.1/metadata/annotations.yaml

operator clickhouse (0.22.1)

---

operators/kuadrant-operator/0.5.0/bundle.Dockerfile
operators/kuadrant-operator/0.5.0/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
operators/kuadrant-operator/0.5.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.5.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.5.0/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.5.0/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.5.0/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.5.0/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.5.0/metadata/annotations.yaml
operators/kuadrant-operator/0.5.0/metadata/dependencies.yaml
operators/kuadrant-operator/0.5.0/tests/scorecard/config.yaml

operator kuadrant-operator (0.5.0)

---

operators/ack-keyspaces-controller/ci.yaml

operator [CI] ack-keyspaces-controller

---

operators/awx-operator/2.9.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.9.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.9.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.9.0/manifests/awx-operator.v2.9.0.clusterserviceversion.yaml
operators/awx-operator/2.9.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.9.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.9.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.9.0/metadata/annotations.yaml
operators/awx-operator/2.9.0/tests/scorecard/config.yaml

operator awx-operator (2.9.0)

---

operators/skupper-operator/1.5.1/manifests/skupper-operator.v1.5.1.clusterserviceversion.yaml
operators/skupper-operator/1.5.1/metadata/annotations.yaml

operator skupper-operator (1.5.1)

---

operators/mongodb-atlas-kubernetes/2.0.1/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.0.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.0.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.0.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.0.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.0.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.0.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.0.1/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.0.1/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.0.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.0.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.0.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.0.1/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.0.1/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.0.1)

---

operators/nexus-operator/3.0.0/manifests/edp.epam.com_nexuses.yaml
operators/nexus-operator/3.0.0/manifests/edp.epam.com_nexusrepositories.yaml
operators/nexus-operator/3.0.0/manifests/edp.epam.com_nexusroles.yaml
operators/nexus-operator/3.0.0/manifests/edp.epam.com_nexususers.yaml
operators/nexus-operator/3.0.0/manifests/nexus-operator.clusterserviceversion.yaml
operators/nexus-operator/3.0.0/metadata/annotations.yaml
operators/nexus-operator/3.0.0/tests/scorecard/config.yaml
operators/nexus-operator/ci.yaml

operator [N] [CI] nexus-operator (3.0.0)

---

operators/rabbitmq-cluster-operator/2.6.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.6.0/manifests/crds.yaml
operators/rabbitmq-cluster-operator/2.6.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.6.0/metadata/annotations.yaml

operator rabbitmq-cluster-operator (2.6.0)

---

operators/rabbitmq-messaging-topology-operator/1.12.2/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_bindings.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_exchanges.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_federations.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_permissions.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_policies.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_queues.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_schemareplications.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_shovels.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_superstreams.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_topicpermissions.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_users.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_vhosts.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.webhook-service.yaml
operators/rabbitmq-messaging-topology-operator/1.12.2/metadata/annotations.yaml

operator rabbitmq-messaging-topology-operator (1.12.2)

---

operators/grafana-operator/5.6.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.6.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.6.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.6.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.6.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.6.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.6.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.6.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.6.0/metadata/annotations.yaml

operator grafana-operator (5.6.0)

---

operators/cryostat-operator/2.4.0/Dockerfile
operators/cryostat-operator/2.4.0/manifests/cryostat-operator-cryostat-namespaced_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.4.0/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.4.0/manifests/cryostat-operator-manager-config_v1_configmap.yaml
operators/cryostat-operator/2.4.0/manifests/cryostat-operator-oauth-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/2.4.0/manifests/cryostat-operator.clusterserviceversion.yaml
operators/cryostat-operator/2.4.0/manifests/operator.cryostat.io_clustercryostats.yaml
operators/cryostat-operator/2.4.0/manifests/operator.cryostat.io_cryostats.yaml
operators/cryostat-operator/2.4.0/metadata/annotations.yaml
operators/cryostat-operator/2.4.0/tests/scorecard/config.yaml

Signed-off-by: Ming Wang [miwan@redhat.com](mailto:miwan@redhat.com)
--

operator [CI] cryostat-operator (2.4.0)

---

operators/flux/2.2.0/manifests/alert.crd.yaml
operators/flux/2.2.0/manifests/bucket.crd.yaml
operators/flux/2.2.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
operators/flux/2.2.0/manifests/crd-controller-flux-system.clusterrole.yaml
operators/flux/2.2.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
operators/flux/2.2.0/manifests/flux-edit-flux-system.clusterrole.yaml
operators/flux/2.2.0/manifests/flux-view-flux-system.clusterrole.yaml
operators/flux/2.2.0/manifests/flux.v2.2.0.clusterserviceversion.yaml
operators/flux/2.2.0/manifests/gitrepository.crd.yaml
operators/flux/2.2.0/manifests/helmchart.crd.yaml
operators/flux/2.2.0/manifests/helmrelease.crd.yaml
operators/flux/2.2.0/manifests/helmrepository.crd.yaml
operators/flux/2.2.0/manifests/imagepolicy.crd.yaml
operators/flux/2.2.0/manifests/imagerepository.crd.yaml
operators/flux/2.2.0/manifests/imageupdateautomation.crd.yaml
operators/flux/2.2.0/manifests/kustomization.crd.yaml
operators/flux/2.2.0/manifests/notification-controller.service.yaml
operators/flux/2.2.0/manifests/ocirepository.crd.yaml
operators/flux/2.2.0/manifests/provider.crd.yaml
operators/flux/2.2.0/manifests/receiver.crd.yaml
operators/flux/2.2.0/manifests/source-controller.service.yaml
operators/flux/2.2.0/manifests/webhook-receiver.service.yaml
operators/flux/2.2.0/metadata/annotations.yaml

operator flux (2.2.0)

---

operators/project-quay/3.10.1/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.1/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.1/metadata/annotations.yaml

Add 3.10.1 to community operators

operator project-quay (3.10.1)

---

operators/dynatrace-operator/0.15.0/Dockerfile
operators/dynatrace-operator/0.15.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/0.15.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/0.15.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/0.15.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/0.15.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/0.15.0/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/0.15.0/metadata/annotations.yaml

operator dynatrace-operator (0.15.0)

---

operators/external-secrets-operator/0.9.10/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.10/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.10/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.10/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.10/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.10/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.10/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.10/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.10/metadata/annotations.yaml
operators/external-secrets-operator/0.9.10/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.10

operator external-secrets-operator (0.9.10)

---

operators/gitlab-operator-kubernetes/0.26.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.26.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.26.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.26.2)

---

operators/security-profiles-operator/0.8.2/manifests/metrics-token_v1_secret.yaml
operators/security-profiles-operator/0.8.2/manifests/security-profiles-operator-profile_v1_configmap.yaml
operators/security-profiles-operator/0.8.2/manifests/security-profiles-operator.clusterserviceversion.yaml
operators/security-profiles-operator/0.8.2/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
operators/security-profiles-operator/0.8.2/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
operators/security-profiles-operator/0.8.2/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
operators/security-profiles-operator/0.8.2/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
operators/security-profiles-operator/0.8.2/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
operators/security-profiles-operator/0.8.2/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
operators/security-profiles-operator/0.8.2/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
operators/security-profiles-operator/0.8.2/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
operators/security-profiles-operator/0.8.2/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.2/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.2/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.2/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.2/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.8.2/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.8.2/manifests/spo-webhook_v1_serviceaccount.yaml
operators/security-profiles-operator/0.8.2/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.2/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.2/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.8.2/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.8.2/manifests/spod_v1_serviceaccount.yaml
operators/security-profiles-operator/0.8.2/metadata/annotations.yaml
operators/security-profiles-operator/0.8.2/tests/scorecard/config.yaml

Refers to https://github.com/kubernetes-sigs/security-profiles-operator/issues/1986

operator security-profiles-operator (0.8.2)

---

operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmagents.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmalertmanagers.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmalerts.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmauths.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmclusters.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmnodescrapes.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmpodscrapes.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmprobes.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmrules.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmservicescrapes.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmsingles.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmstaticscrapes.yaml
operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmusers.yaml
operators/victoriametrics-operator/0.39.4/manifests/victoriametrics-operator.clusterserviceversion.yaml
operators/victoriametrics-operator/0.39.4/metadata/annotations.yaml

operator victoriametrics-operator (0.39.4)

---

operators/mongodb-enterprise/1.24.0/bundle.Dockerfile
operators/mongodb-enterprise/1.24.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.24.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.24.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.24.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.24.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.24.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.24.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.24.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.24.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.24.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.24.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.24.0/tests/scorecard/config.yaml

operator mongodb-enterprise (1.24.0)

---

operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberocouchdbs.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberoelasticsearches.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberokafkas.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberomails.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberomemcacheds.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberomongodbs.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberomysqls.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberopostgresqls.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberorabbitmqs.yaml
operators/kubero-operator/0.0.147/manifests/application.kubero.dev_kuberoredis.yaml
operators/kubero-operator/0.0.147/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.0.147/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.0.147/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.0.147/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.0.147/metadata/annotations.yaml
operators/kubero-operator/0.0.147/tests/scorecard/config.yaml

operator kubero-operator (0.0.147)

---

operators/gitlab-operator-kubernetes/0.27.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.27.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.27.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.27.0)

---

operators/external-secrets-operator/0.9.11/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.11/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.11/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.11/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.11/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.11/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.11/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.11/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.11/metadata/annotations.yaml
operators/external-secrets-operator/0.9.11/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.11

operator external-secrets-operator (0.9.11)

---

operators/flux/2.2.2/manifests/alert.crd.yaml
operators/flux/2.2.2/manifests/bucket.crd.yaml
operators/flux/2.2.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
operators/flux/2.2.2/manifests/crd-controller-flux-system.clusterrole.yaml
operators/flux/2.2.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml
operators/flux/2.2.2/manifests/flux-edit-flux-system.clusterrole.yaml
operators/flux/2.2.2/manifests/flux-view-flux-system.clusterrole.yaml
operators/flux/2.2.2/manifests/flux.v2.2.2.clusterserviceversion.yaml
operators/flux/2.2.2/manifests/gitrepository.crd.yaml
operators/flux/2.2.2/manifests/helmchart.crd.yaml
operators/flux/2.2.2/manifests/helmrelease.crd.yaml
operators/flux/2.2.2/manifests/helmrepository.crd.yaml
operators/flux/2.2.2/manifests/imagepolicy.crd.yaml
operators/flux/2.2.2/manifests/imagerepository.crd.yaml
operators/flux/2.2.2/manifests/imageupdateautomation.crd.yaml
operators/flux/2.2.2/manifests/kustomization.crd.yaml
operators/flux/2.2.2/manifests/notification-controller.service.yaml
operators/flux/2.2.2/manifests/ocirepository.crd.yaml
operators/flux/2.2.2/manifests/provider.crd.yaml
operators/flux/2.2.2/manifests/receiver.crd.yaml
operators/flux/2.2.2/manifests/source-controller.service.yaml
operators/flux/2.2.2/manifests/webhook-receiver.service.yaml
operators/flux/2.2.2/metadata/annotations.yaml

operator flux (2.2.2)

---

operators/mariadb-operator/0.24.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.24.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_backups.yaml
operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_connections.yaml
operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_databases.yaml
operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_grants.yaml
operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_mariadbs.yaml
operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_restores.yaml
operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_sqljobs.yaml
operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_users.yaml
operators/mariadb-operator/0.24.0/metadata/annotations.yaml
operators/mariadb-operator/0.24.0/tests/scorecard/config.yaml

Add operator mariadb-operator (0.24.0) to community operators

operator mariadb-operator (0.24.0)

---

operators/awx-operator/2.10.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.10.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.10.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.10.0/manifests/awx-operator.v2.10.0.clusterserviceversion.yaml
operators/awx-operator/2.10.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.10.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.10.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.10.0/metadata/annotations.yaml
operators/awx-operator/2.10.0/tests/scorecard/config.yaml

operator awx-operator (2.10.0)

operator awx-operator (2.10.0)

---

operators/ack-organizations-controller/ci.yaml

--
- Fixes: aws-controllers-k8s/community#1970

operator [CI] ack-organizations-controller

---

operators/trivy-operator/0.18.0/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/manifests/trivy-operator.v0.18.0.clusterserviceversion.yaml
operators/trivy-operator/0.18.0/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.0/metadata/annotations.yaml

operator trivy-operator (0.18.0)

---

operators/temporal-operator/0.12.2/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.12.2/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.12.2/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.12.2/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.12.2/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.12.2/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.12.2/metadata/annotations.yaml

operator temporal-operator (0.12.2)

---

operators/temporal-operator/0.13.0/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.13.0/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.13.0/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.13.0/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.13.0/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.13.0/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.13.0/metadata/annotations.yaml

operator temporal-operator (0.13.0)

---

operators/temporal-operator/0.13.1/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.13.1/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.13.1/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.13.1/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.13.1/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.13.1/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.13.1/metadata/annotations.yaml

operator temporal-operator (0.13.1)

---

operators/temporal-operator/0.13.2/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.13.2/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.13.2/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.13.2/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.13.2/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.13.2/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.13.2/metadata/annotations.yaml

operator temporal-operator (0.13.2)

---

operators/temporal-operator/0.13.3/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.13.3/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.13.3/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.13.3/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.13.3/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.13.3/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.13.3/metadata/annotations.yaml

operator temporal-operator (0.13.3)

---

operators/temporal-operator/0.14.0/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.14.0/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.14.0/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.14.0/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.14.0/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.14.0/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.14.0/metadata/annotations.yaml

operator temporal-operator (0.14.0)

---

operators/temporal-operator/0.15.0/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.15.0/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.15.0/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.15.0/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.15.0/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.15.0/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.15.0/metadata/annotations.yaml

operator temporal-operator (0.15.0)

---

operators/camel-k/2.2.0/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.2.0/manifests/camel-k.v2.2.0.clusterserviceversion.yaml
operators/camel-k/2.2.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.2.0/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.2.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.2.0/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.2.0/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/2.2.0/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.2.0/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.2.0/metadata/annotations.yaml
operators/camel-k/2.2.0/tests/scorecard/config.yaml

operator camel-k (2.2.0)

---

operators/clickhouse/0.22.2/manifests/clickhouse-operator.v0.22.2.clusterserviceversion.yaml
operators/clickhouse/0.22.2/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.22.2/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.22.2/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.22.2/metadata/annotations.yaml

operator clickhouse (0.22.2)

---

operators/temporal-operator/0.15.1/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.15.1/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.15.1/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.15.1/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.15.1/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.15.1/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.15.1/metadata/annotations.yaml

operator temporal-operator (0.15.1)

---

operators/temporal-operator/0.15.2/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.15.2/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.15.2/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.15.2/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.15.2/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.15.2/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.15.2/metadata/annotations.yaml

operator temporal-operator (0.15.2)

---

operators/temporal-operator/0.15.3/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.15.3/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.15.3/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.15.3/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.15.3/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.15.3/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.15.3/metadata/annotations.yaml

operator temporal-operator (0.15.3)

---

operators/temporal-operator/0.15.4/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.15.4/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.15.4/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.15.4/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.15.4/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.15.4/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.15.4/metadata/annotations.yaml

operator temporal-operator (0.15.4)

---

operators/temporal-operator/0.16.0/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.16.0/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.16.0/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.16.0/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.16.0/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.16.0/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.16.0/metadata/annotations.yaml

operator temporal-operator (0.16.0)

---

operators/temporal-operator/0.16.1/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.16.1/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.16.1/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.16.1/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.16.1/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.16.1/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.16.1/metadata/annotations.yaml

operator temporal-operator (0.16.1)

---

operators/temporal-operator/0.16.2/manifests/temporal-operator-webhook-service_v1_service.yaml
operators/temporal-operator/0.16.2/manifests/temporal-operator.clusterserviceversion.yaml
operators/temporal-operator/0.16.2/manifests/temporal.io_temporalclusterclients.yaml
operators/temporal-operator/0.16.2/manifests/temporal.io_temporalclusters.yaml
operators/temporal-operator/0.16.2/manifests/temporal.io_temporalnamespaces.yaml
operators/temporal-operator/0.16.2/manifests/temporal.io_temporalworkerprocesses.yaml
operators/temporal-operator/0.16.2/metadata/annotations.yaml

operator temporal-operator (0.16.2)

---

operators/ibm-security-verify-access-operator/23.12.0/manifests/ibm-security-verify-access-operator.clusterserviceversion.yaml
operators/ibm-security-verify-access-operator/23.12.0/manifests/ibm.com_ibmsecurityverifyaccesses.yaml
operators/ibm-security-verify-access-operator/23.12.0/manifests/verify-access-operator-controller-manager-metrics-service_v1_service.yaml
operators/ibm-security-verify-access-operator/23.12.0/manifests/verify-access-operator-controller-manager-snapshot-service_v1_service.yaml
operators/ibm-security-verify-access-operator/23.12.0/manifests/verify-access-operator-manager-config_v1_configmap.yaml
operators/ibm-security-verify-access-operator/23.12.0/manifests/verify-access-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ibm-security-verify-access-operator/23.12.0/metadata/annotations.yaml
operators/ibm-security-verify-access-operator/23.12.0/tests/scorecard/config.yaml
operators/ibm-security-verify-access-operator/ci.yaml

operator [CI] ibm-security-verify-access-operator (23.12.0)

---

operators/trivy-operator/0.18.1/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/manifests/trivy-operator.v0.18.1.clusterserviceversion.yaml
operators/trivy-operator/0.18.1/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.1/metadata/annotations.yaml
operators/trivy-operator/ci.yaml

operator [CI] trivy-operator (0.18.1)

---

operators/nexus-operator/3.1.0/manifests/edp.epam.com_nexuses.yaml
operators/nexus-operator/3.1.0/manifests/edp.epam.com_nexusrepositories.yaml
operators/nexus-operator/3.1.0/manifests/edp.epam.com_nexusroles.yaml
operators/nexus-operator/3.1.0/manifests/edp.epam.com_nexusscripts.yaml
operators/nexus-operator/3.1.0/manifests/edp.epam.com_nexususers.yaml
operators/nexus-operator/3.1.0/manifests/nexus-operator-webhook-service_v1_service.yaml
operators/nexus-operator/3.1.0/manifests/nexus-operator.clusterserviceversion.yaml
operators/nexus-operator/3.1.0/metadata/annotations.yaml
operators/nexus-operator/3.1.0/tests/scorecard/config.yaml

operator nexus-operator (3.1.0)

---

operators/edp-keycloak-operator/1.20.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.20.0/manifests/edp-keycloak-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/edp-keycloak-operator/1.20.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.20.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.20.0/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.20.0)

---

operators/tempo-operator/0.7.0/bundle.Dockerfile
operators/tempo-operator/0.7.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.7.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.7.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.7.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.7.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.7.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.7.0/metadata/annotations.yaml
operators/tempo-operator/0.7.0/tests/scorecard/config.yaml

Release tempo-operator `0.7.0`.

operator tempo-operator (0.7.0)

---

operators/gitlab-operator-kubernetes/0.27.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.27.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.27.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.27.1)

---

operators/verticadb-operator/2.0.1/manifests/vertica.com_eventtriggers.yaml
operators/verticadb-operator/2.0.1/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/2.0.1/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/2.0.1/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/2.0.1/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/2.0.1/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/2.0.1/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/2.0.1/metadata/annotations.yaml
operators/verticadb-operator/2.0.1/tests/scorecard/config.yaml

operator verticadb-operator (2.0.1)

---

operators/microcks/1.8.1/manifests/microcks-operator.v1.8.1.clusterserviceversion.yaml
operators/microcks/1.8.1/manifests/microcksinstall.crd.yaml
operators/microcks/1.8.1/metadata/annotations.yaml

operator microcks (1.8.1)

---

operators/dell-csm-operator/1.4.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.4.0/manifests/dell-csm-operator.v1.4.0.clusterserviceversion.yaml
operators/dell-csm-operator/1.4.0/metadata/annotations.yaml
operators/dell-csm-operator/1.4.0/tests/scorecard/config.yaml

operator dell-csm-operator (1.4.0)

---

operators/deployment-validation-operator/0.7.4/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.7.4/manifests/deploymentvalidationoperator.0.7.4.clusterserviceversion.yaml
operators/deployment-validation-operator/0.7.4/metadata/annotations.yaml
operators/deployment-validation-operator/0.7.4/tests/scorecard/config.yaml

operator deployment-validation-operator (0.7.4)

---

operators/project-quay/3.10.2/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.2/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.2/metadata/annotations.yaml

Add 3.10.2 to community operators

operator project-quay (3.10.2)

---

operators/elastic-cloud-eck/2.11.0/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.0/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.0/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.0/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.11.0/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.0/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.0/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.0/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.0/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.0/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.0/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.0/metadata/annotations.yaml

Update the ECK operator to the latest version `2.11.0`.

operator elastic-cloud-eck (2.11.0)

---

operators/trivy-operator/0.18.2/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/manifests/trivy-operator.v0.18.2.clusterserviceversion.yaml
operators/trivy-operator/0.18.2/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.2/metadata/annotations.yaml

operator trivy-operator (0.18.2)

---

operators/project-quay/3.10.0/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.0-rc.1/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.8.0/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.6/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.6/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.6/metadata/annotations.yaml

Add 3.9.6 to community operators

operator [R] project-quay (3.10.0 3.8.0 3.8.0-rc.1 3.9.0 3.9.6)

---

operators/pulp-operator/1.0.0-beta.4/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.0.0-beta.4/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.0.0-beta.4/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/pulp-operator/1.0.0-beta.4/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0-beta.4/manifests/pulp-operator.clusterserviceversion.yaml
operators/pulp-operator/1.0.0-beta.4/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.0.0-beta.4/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.0.0-beta.4/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.0.0-beta.4/metadata/annotations.yaml
operators/pulp-operator/1.0.0-beta.4/tests/scorecard/config.yaml

operator pulp-operator (1.0.0-beta.4)

---

operators/skupper-operator/1.5.3/manifests/skupper-operator.v1.5.3.clusterserviceversion.yaml
operators/skupper-operator/1.5.3/metadata/annotations.yaml

operator skupper-operator (1.5.3)

---

operators/ndb-operator/1.3.0/bundle.Dockerfile
operators/ndb-operator/1.3.0/manifests/mysql.oracle.com_ndbclusters.yaml
operators/ndb-operator/1.3.0/manifests/ndb-operator-svc_v1_service.yaml
operators/ndb-operator/1.3.0/manifests/ndb-operator-webhook-service_v1_service.yaml
operators/ndb-operator/1.3.0/manifests/ndb-operator.clusterserviceversion.yaml
operators/ndb-operator/1.3.0/metadata/annotations.yaml
operators/ndb-operator/ci.yaml

operator [CI] ndb-operator (1.3.0)

---

operators/gitlab-operator-kubernetes/0.28.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.28.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.28.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.28.0)

---

operators/windup-operator/0.0.25/manifests/windup-operator.clusterserviceversion.yaml
operators/windup-operator/0.0.25/manifests/windup.crd.yaml
operators/windup-operator/0.0.25/metadata/annotations.yaml

operator windup-operator (0.0.25)

---

operators/ndmspc-operator/0.7.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.7.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.7.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.7.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.7.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.7.0/metadata/annotations.yaml
operators/ndmspc-operator/0.7.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.7.0)

---

operators/ndb-operator/1.3.0/metadata/annotations.yaml

operator [O] ndb-operator (1.3.0)

---

operators/rabbitmq-cluster-operator/2.7.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.7.0/manifests/crds.yaml
operators/rabbitmq-cluster-operator/2.7.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.7.0/metadata/annotations.yaml

operator rabbitmq-cluster-operator (2.7.0)

---

operators/eginnovations-operator/0.0.7/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml
operators/eginnovations-operator/0.0.7/manifests/eginnovations-operator-manager-config_v1_configmap.yaml
operators/eginnovations-operator/0.0.7/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/eginnovations-operator/0.0.7/manifests/eginnovations-operator-webhook-service_v1_service.yaml
operators/eginnovations-operator/0.0.7/manifests/eginnovations-operator.clusterserviceversion.yaml
operators/eginnovations-operator/0.0.7/manifests/eginnovations.com_eguniversalagents.yaml
operators/eginnovations-operator/0.0.7/metadata/annotations.yaml
operators/eginnovations-operator/0.0.7/tests/scorecard/config.yaml

operator eginnovations-operator (0.0.7)

---

operators/ceph-s3-operator/0.3.6/bundle.Dockerfile
operators/ceph-s3-operator/0.3.6/manifests/ceph-s3-operator-controller-manager-config_v1_secret.yaml
operators/ceph-s3-operator/0.3.6/manifests/ceph-s3-operator-controller-manager-metrics-service_v1_service.yaml
operators/ceph-s3-operator/0.3.6/manifests/ceph-s3-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ceph-s3-operator/0.3.6/manifests/ceph-s3-operator-webhook-service_v1_service.yaml
operators/ceph-s3-operator/0.3.6/manifests/ceph-s3-operator.clusterserviceversion.yaml
operators/ceph-s3-operator/0.3.6/manifests/s3.snappcloud.io_s3buckets.yaml
operators/ceph-s3-operator/0.3.6/manifests/s3.snappcloud.io_s3userclaims.yaml
operators/ceph-s3-operator/0.3.6/manifests/s3.snappcloud.io_s3users.yaml
operators/ceph-s3-operator/0.3.6/metadata/annotations.yaml
operators/ceph-s3-operator/0.3.6/tests/scorecard/config.yaml
operators/ceph-s3-operator/ci.yaml

operator [N] [CI] ceph-s3-operator (0.3.6)

---

operators/ndmspc-operator/0.7.3/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.7.3/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.7.3/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.7.3/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.7.3/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.7.3/metadata/annotations.yaml
operators/ndmspc-operator/0.7.3/tests/scorecard/config.yaml

operator ndmspc-operator (0.7.3)

---

operators/ndmspc-operator/0.7.4/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.7.4/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.7.4/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.7.4/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.7.4/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.7.4/metadata/annotations.yaml
operators/ndmspc-operator/0.7.4/tests/scorecard/config.yaml

operator ndmspc-operator (0.7.4)

---

operators/trivy-operator/0.18.3/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/manifests/trivy-operator.v0.18.3.clusterserviceversion.yaml
operators/trivy-operator/0.18.3/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.3/metadata/annotations.yaml

operator trivy-operator (0.18.3)

---

operators/elastic-cloud-eck/2.11.1/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.1/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.1/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.1/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.11.1/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.1/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.1/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.1/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.1/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.1/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.1/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.11.1/metadata/annotations.yaml

Update the ECK operator to the latest version `2.11.1`.

operator elastic-cloud-eck (2.11.1)

---

operators/awx-operator/2.11.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.11.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.11.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.11.0/manifests/awx-operator.v2.11.0.clusterserviceversion.yaml
operators/awx-operator/2.11.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.11.0/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.11.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.11.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.11.0/metadata/annotations.yaml
operators/awx-operator/2.11.0/tests/scorecard/config.yaml

operator awx-operator (2.11.0)

operator awx-operator (2.11.0)

---

operators/kuadrant-operator/0.6.1/bundle.Dockerfile
operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator-dnsrecord-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator-dnsrecord-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_dnshealthcheckprobes.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_dnspolicies.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_dnsrecords.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_managedzones.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_tlspolicies.yaml
operators/kuadrant-operator/0.6.1/metadata/annotations.yaml
operators/kuadrant-operator/0.6.1/metadata/dependencies.yaml
operators/kuadrant-operator/0.6.1/tests/scorecard/config.yaml

operator kuadrant-operator (0.6.1)

---

operators/project-quay/3.10.3/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.3/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.3/metadata/annotations.yaml

Add 3.10.3 to community operators

operator project-quay (3.10.3)

---

operators/rabbitmq-messaging-topology-operator/1.13.0/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_bindings.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_exchanges.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_federations.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_operatorpolicies.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_permissions.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_policies.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_queues.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_schemareplications.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_shovels.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_superstreams.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_topicpermissions.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_users.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_vhosts.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.webhook-service.yaml
operators/rabbitmq-messaging-topology-operator/1.13.0/metadata/annotations.yaml

operator rabbitmq-messaging-topology-operator (1.13.0)

---

operators/project-quay/3.10.3/manifests/quay-operator.clusterserviceversion.yaml

Add 3.10.3 to community operators

operator [O] project-quay (3.10.3)

---

operators/leaksignal-operator/1.3.1/manifests/leaksignal-cluster.crd.yaml
operators/leaksignal-operator/1.3.1/manifests/leaksignal.clusterserviceversion.yaml
operators/leaksignal-operator/1.3.1/manifests/leaksignal.crd.yaml
operators/leaksignal-operator/1.3.1/metadata/annotations.yaml
operators/leaksignal-operator/ci.yaml

operator [N] [CI] leaksignal-operator (1.3.1)

---

operators/clickhouse/0.23.0/manifests/clickhouse-operator.v0.23.0.clusterserviceversion.yaml
operators/clickhouse/0.23.0/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.0/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.0/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.0/metadata/annotations.yaml

operator clickhouse (0.23.0)

---

operators/trivy-operator/0.18.4/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/manifests/trivy-operator.v0.18.4.clusterserviceversion.yaml
operators/trivy-operator/0.18.4/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.4/metadata/annotations.yaml

operator trivy-operator (0.18.4)

---

operators/tempo-operator/0.8.0/bundle.Dockerfile
operators/tempo-operator/0.8.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.8.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.8.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.8.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.8.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.8.0/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.8.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.8.0/metadata/annotations.yaml
operators/tempo-operator/0.8.0/tests/scorecard/config.yaml

Release tempo-operator `0.8.0`.

operator tempo-operator (0.8.0)

---

operators/knative-operator/1.13.1/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.13.1/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.13.1/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.13.1/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.13.1/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.13.1/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.13.1/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.13.1/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.13.1/manifests/knative-operator.v1.13.1.clusterserviceversion.yaml
operators/knative-operator/1.13.1/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.13.1/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.13.1/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.13.1/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.13.1/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.13.1/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.13.1/metadata/annotations.yaml
operators/knative-operator/1.13.1/tests/scorecard/config.yaml

operator knative-operator (1.13.1)

---

operators/kaoto-operator/0.0.10/manifests/designer.kaoto.io_kaotoes.yaml
operators/kaoto-operator/0.0.10/manifests/kaoto-operator.clusterserviceversion.yaml
operators/kaoto-operator/0.0.10/metadata/annotations.yaml
operators/kaoto-operator/0.0.10/tests/scorecard/config.yaml

operator kaoto-operator (0.0.10)

---

operators/ndmspc-operator/0.8.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.8.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.8.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.8.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.8.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.8.0/metadata/annotations.yaml
operators/ndmspc-operator/0.8.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.8.0)

---

operators/grafana-operator/5.6.1/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.6.1/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.6.1/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.6.1/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.6.1/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.6.1/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.6.1/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.6.1/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.6.1/metadata/annotations.yaml

operator grafana-operator (5.6.1)

---

operators/grafana-operator/5.6.2/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.6.2/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.6.2/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.6.2/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.6.2/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.6.2/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.6.2/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.6.2/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.6.2/metadata/annotations.yaml

operator grafana-operator (5.6.2)

---

operators/kaoto-operator/0.0.12/manifests/designer.kaoto.io_kaotoes.yaml
operators/kaoto-operator/0.0.12/manifests/kaoto-operator.clusterserviceversion.yaml
operators/kaoto-operator/0.0.12/metadata/annotations.yaml
operators/kaoto-operator/0.0.12/tests/scorecard/config.yaml

operator kaoto-operator (0.0.12)

---

operators/trivy-operator/0.18.5/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/manifests/trivy-operator.v0.18.5.clusterserviceversion.yaml
operators/trivy-operator/0.18.5/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.18.5/metadata/annotations.yaml

operator trivy-operator (0.18.5)

---

operators/external-secrets-operator/0.9.12/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.12/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.12/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.12/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.12/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.12/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.12/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.12/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.12/metadata/annotations.yaml
operators/external-secrets-operator/0.9.12/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.12

operator external-secrets-operator (0.9.12)

---

operators/grafana-operator/5.6.3/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.6.3/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.6.3/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.6.3/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.6.3/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.6.3/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.6.3/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.6.3/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.6.3/metadata/annotations.yaml

operator grafana-operator (5.6.3)

---

operators/gitlab-operator-kubernetes/0.28.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.28.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.28.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.28.2)

---

operators/ndmspc-operator/0.9.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.9.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.9.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.9.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.9.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.9.0/metadata/annotations.yaml
operators/ndmspc-operator/0.9.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.9.0)

---

operators/ack-efs-controller/ci.yaml

operator [CI] ack-efs-controller

---

operators/keda/2.12.1/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.12.1/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.12.1/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.12.1/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.12.1/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.12.1/manifests/keda.v2.12.1.clusterserviceversion.yaml
operators/keda/2.12.1/metadata/annotations.yaml
operators/keda/ci.yaml

operator [CI] keda (2.12.1)

---

operators/awx-operator/2.12.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.12.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.12.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.12.0/manifests/awx-operator.v2.12.0.clusterserviceversion.yaml
operators/awx-operator/2.12.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.12.0/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.12.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.12.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.12.0/metadata/annotations.yaml
operators/awx-operator/2.12.0/tests/scorecard/config.yaml

operator awx-operator (2.12.0)

operator awx-operator (2.12.0)

---

operators/leaksignal-operator/1.6.0/manifests/leaksignal-cluster.crd.yaml
operators/leaksignal-operator/1.6.0/manifests/leaksignal.clusterserviceversion.yaml
operators/leaksignal-operator/1.6.0/manifests/leaksignal.crd.yaml
operators/leaksignal-operator/1.6.0/manifests/service.yaml
operators/leaksignal-operator/1.6.0/metadata/annotations.yaml

operator leaksignal-operator (1.6.0)

---

operators/leaksignal-operator/1.6.1/manifests/leaksignal-cluster.crd.yaml
operators/leaksignal-operator/1.6.1/manifests/leaksignal.clusterserviceversion.yaml
operators/leaksignal-operator/1.6.1/manifests/leaksignal.crd.yaml
operators/leaksignal-operator/1.6.1/manifests/priority-class.yaml
operators/leaksignal-operator/1.6.1/manifests/service.yaml
operators/leaksignal-operator/1.6.1/metadata/annotations.yaml

operator leaksignal-operator (1.6.1)

---

operators/leaksignal-operator/1.6.2/manifests/leaksignal-cluster.crd.yaml
operators/leaksignal-operator/1.6.2/manifests/leaksignal.clusterserviceversion.yaml
operators/leaksignal-operator/1.6.2/manifests/leaksignal.crd.yaml
operators/leaksignal-operator/1.6.2/manifests/priority-class.yaml
operators/leaksignal-operator/1.6.2/manifests/service.yaml
operators/leaksignal-operator/1.6.2/metadata/annotations.yaml

operator leaksignal-operator (1.6.2)

---

operators/awx-operator/2.12.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.12.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.12.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.12.1/manifests/awx-operator.v2.12.1.clusterserviceversion.yaml
operators/awx-operator/2.12.1/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.12.1/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.12.1/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.12.1/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.12.1/metadata/annotations.yaml
operators/awx-operator/2.12.1/tests/scorecard/config.yaml

operator awx-operator (2.12.1)

operator awx-operator (2.12.1)

---

operators/external-secrets-operator/0.9.13/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.13/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.13/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.13/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.13/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.13/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.13/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.9.13/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.13/metadata/annotations.yaml
operators/external-secrets-operator/0.9.13/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.13

operator external-secrets-operator (0.9.13)

---

operators/verticadb-operator/2.0.2/manifests/vertica.com_eventtriggers.yaml
operators/verticadb-operator/2.0.2/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/2.0.2/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/2.0.2/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/2.0.2/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/2.0.2/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/verticadb-operator/2.0.2/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/2.0.2/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/2.0.2/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/2.0.2/metadata/annotations.yaml
operators/verticadb-operator/2.0.2/tests/scorecard/config.yaml

operator verticadb-operator (2.0.2)

---

operators/gitlab-operator-kubernetes/0.29.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.29.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.29.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.29.0)

---

operators/clickhouse/0.23.1/manifests/clickhouse-operator.v0.23.1.clusterserviceversion.yaml
operators/clickhouse/0.23.1/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.1/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.1/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.23.1/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.1/metadata/annotations.yaml

operator clickhouse (0.23.1)

---

operators/netobserv-operator/1.0.5/manifests/flows.netobserv.io_flowcollectors.yaml
operators/netobserv-operator/1.0.5/manifests/flows.netobserv.io_flowmetrics.yaml
operators/netobserv-operator/1.0.5/manifests/netobserv-manager-config_v1_configmap.yaml
operators/netobserv-operator/1.0.5/manifests/netobserv-metrics-service_v1_service.yaml
operators/netobserv-operator/1.0.5/manifests/netobserv-operator.clusterserviceversion.yaml
operators/netobserv-operator/1.0.5/manifests/netobserv-webhook-service_v1_service.yaml
operators/netobserv-operator/1.0.5/metadata/annotations.yaml

operator netobserv-operator (1.0.5)

---

operators/ack-documentdb-controller/ci.yaml

operator [CI] ack-documentdb-controller

---

operators/mongodb-atlas-kubernetes/2.1.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.1.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.1.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.1.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.1.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.1.0/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.1.0)

---

operators/mongodb-atlas-kubernetes/ci.yaml

operator [CI] mongodb-atlas-kubernetes

---

operators/ack-elbv2-controller/ci.yaml

operator [CI] ack-elbv2-controller

---

operators/ack-ecs-controller/ci.yaml

operator [CI] ack-ecs-controller

---

operators/datadog-operator/ci.yaml

This PR update the list of allowed user for the `datadog-operator` chart. 
--

operator [CI] datadog-operator

---

operators/clickhouse/0.23.2/manifests/clickhouse-operator.v0.23.2.clusterserviceversion.yaml
operators/clickhouse/0.23.2/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.2/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.2/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.23.2/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.2/metadata/annotations.yaml

operator clickhouse (0.23.2)

---

operators/leaksignal-operator/1.6.3/manifests/leaksignal-cluster.crd.yaml
operators/leaksignal-operator/1.6.3/manifests/leaksignal.clusterserviceversion.yaml
operators/leaksignal-operator/1.6.3/manifests/leaksignal.crd.yaml
operators/leaksignal-operator/1.6.3/manifests/priority-class.yaml
operators/leaksignal-operator/1.6.3/manifests/service.yaml
operators/leaksignal-operator/1.6.3/metadata/annotations.yaml

operator leaksignal-operator (1.6.3)

---

operators/gitlab-operator-kubernetes/0.29.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.29.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.29.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.29.1)

---

operators/move2kube-operator/0.3.12-rc.0/bundle.Dockerfile
operators/move2kube-operator/0.3.12-rc.0/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.12-rc.0/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.12-rc.0/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.12-rc.0/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.12-rc.0/metadata/annotations.yaml
operators/move2kube-operator/0.3.12-rc.0/tests/scorecard/config.yaml

An automated PR to update move2kube-operator to v0.3.12-rc.0

operator move2kube-operator (0.3.12-rc.0)

---

operators/move2kube-operator/0.3.12/bundle.Dockerfile
operators/move2kube-operator/0.3.12/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.12/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.12/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.12/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.12/metadata/annotations.yaml
operators/move2kube-operator/0.3.12/tests/scorecard/config.yaml

An automated PR to update move2kube-operator to v0.3.12

operator move2kube-operator (0.3.12)

---

operators/dell-csm-operator/1.4.2/manifests/apexconnectivityclients.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.4.2/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.4.2/manifests/dell-csm-operator.v1.4.2.clusterserviceversion.yaml
operators/dell-csm-operator/1.4.2/metadata/annotations.yaml
operators/dell-csm-operator/1.4.2/tests/scorecard/config.yaml

operator dell-csm-operator (1.4.2)

---

operators/skupper-operator/1.6.0/manifests/skupper-operator.v1.6.0.clusterserviceversion.yaml
operators/skupper-operator/1.6.0/metadata/annotations.yaml

operator skupper-operator (1.6.0)

---

operators/project-quay/3.10.4/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.4/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.4/metadata/annotations.yaml

Add 3.10.4 to community operators

operator project-quay (3.10.4)

---

operators/beegfs-csi-driver-operator/1.6.0/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml
operators/beegfs-csi-driver-operator/1.6.0/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml
operators/beegfs-csi-driver-operator/1.6.0/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/beegfs-csi-driver-operator/1.6.0/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml
operators/beegfs-csi-driver-operator/1.6.0/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml
operators/beegfs-csi-driver-operator/1.6.0/metadata/annotations.yaml
operators/beegfs-csi-driver-operator/1.6.0/tests/scorecard/config.yaml

operator beegfs-csi-driver-operator (1.6.0)

---

operators/self-node-remediation/0.8.0/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml
operators/self-node-remediation/0.8.0/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.8.0/manifests/self-node-remediation-manager-config_v1_configmap.yaml
operators/self-node-remediation/0.8.0/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.8.0/manifests/self-node-remediation-webhook-service_v1_service.yaml
operators/self-node-remediation/0.8.0/manifests/self-node-remediation.clusterserviceversion.yaml
operators/self-node-remediation/0.8.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
operators/self-node-remediation/0.8.0/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
operators/self-node-remediation/0.8.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
operators/self-node-remediation/0.8.0/metadata/annotations.yaml
operators/self-node-remediation/0.8.0/tests/scorecard/config.yaml

operator self-node-remediation (0.8.0)

---

operators/cluster-manager/0.13.0/manifests/cluster-manager.clusterserviceversion.yaml
operators/cluster-manager/0.13.0/manifests/operator.open-cluster-management.io_clustermanagers.yaml
operators/cluster-manager/0.13.0/metadata/annotations.yaml

operator cluster-manager (0.13.0)

---

operators/klusterlet/0.13.0/manifests/klusterlet.clusterserviceversion.yaml
operators/klusterlet/0.13.0/manifests/operator.open-cluster-management.io_klusterlets.yaml
operators/klusterlet/0.13.0/metadata/annotations.yaml

operator klusterlet (0.13.0)

---

operators/gitlab-operator-kubernetes/0.29.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.29.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.29.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.29.2)

---

operators/node-healthcheck-operator/0.7.0/manifests/node-healthcheck-controller-manager-metrics-service_v1_service.yaml
operators/node-healthcheck-operator/0.7.0/manifests/node-healthcheck-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/node-healthcheck-operator/0.7.0/manifests/node-healthcheck-operator.clusterserviceversion.yaml
operators/node-healthcheck-operator/0.7.0/manifests/node-healthcheck-webhook-service_v1_service.yaml
operators/node-healthcheck-operator/0.7.0/manifests/remediation.medik8s.io_nodehealthchecks.yaml
operators/node-healthcheck-operator/0.7.0/metadata/annotations.yaml
operators/node-healthcheck-operator/0.7.0/metadata/dependencies.yaml
operators/node-healthcheck-operator/0.7.0/tests/scorecard/config.yaml

operator node-healthcheck-operator (0.7.0)

---

operators/verticadb-operator/2.1.0/manifests/vertica.com_eventtriggers.yaml
operators/verticadb-operator/2.1.0/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/2.1.0/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/2.1.0/manifests/vertica.com_verticarestorepointsqueries.yaml
operators/verticadb-operator/2.1.0/manifests/vertica.com_verticascrutinizers.yaml
operators/verticadb-operator/2.1.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/2.1.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/2.1.0/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/verticadb-operator/2.1.0/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/2.1.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/2.1.0/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/2.1.0/metadata/annotations.yaml
operators/verticadb-operator/2.1.0/tests/scorecard/config.yaml

operator verticadb-operator (2.1.0)

---

operators/dell-csm-operator/1.4.3/manifests/apexconnectivityclients.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.4.3/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.4.3/manifests/dell-csm-operator.v1.4.3.clusterserviceversion.yaml
operators/dell-csm-operator/1.4.3/metadata/annotations.yaml
operators/dell-csm-operator/1.4.3/tests/scorecard/config.yaml

operator dell-csm-operator (1.4.3)

---

operators/apicurio-registry/1.1.1-v2.5.9.final/bundle.Dockerfile
operators/apicurio-registry/1.1.1-v2.5.9.final/manifests/apicurio-registry-operator.clusterserviceversion.yaml
operators/apicurio-registry/1.1.1-v2.5.9.final/manifests/registry.apicur.io_apicurioregistries.yaml
operators/apicurio-registry/1.1.1-v2.5.9.final/metadata/annotations.yaml
operators/apicurio-registry/1.1.1-v2.5.9.final/tests/scorecard/config.yaml

operator apicurio-registry (1.1.1-v2.5.9.final)

---

operators/ndmspc-operator/0.10.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.10.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.10.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.10.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.10.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.10.0/metadata/annotations.yaml
operators/ndmspc-operator/0.10.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.10.0)

---

operators/ndmspc-operator/0.10.2/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.10.2/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.10.2/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.10.2/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.10.2/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.10.2/metadata/annotations.yaml
operators/ndmspc-operator/0.10.2/tests/scorecard/config.yaml

operator ndmspc-operator (0.10.2)

---

operators/deployment-validation-operator/0.7.5/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.7.5/manifests/deploymentvalidationoperator.0.7.5.clusterserviceversion.yaml
operators/deployment-validation-operator/0.7.5/metadata/annotations.yaml
operators/deployment-validation-operator/0.7.5/tests/scorecard/config.yaml

operator deployment-validation-operator (0.7.5)

---

operators/awx-operator/2.13.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.13.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.13.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.13.0/manifests/awx-operator.v2.13.0.clusterserviceversion.yaml
operators/awx-operator/2.13.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.13.0/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.13.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.13.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.13.0/metadata/annotations.yaml
operators/awx-operator/2.13.0/tests/scorecard/config.yaml

operator awx-operator (2.13.0)

operator awx-operator (2.13.0)

---

operators/grafana-operator/5.7.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.7.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.7.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.7.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.7.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.7.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.7.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.7.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.7.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.7.0/metadata/annotations.yaml

operator grafana-operator (5.7.0)

---

operators/percona-xtradb-cluster-operator/1.14.0/manifests/percona-xtradb-cluster-operator.v1.14.0.clusterserviceversion.yaml
operators/percona-xtradb-cluster-operator/1.14.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.14.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.14.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.14.0/metadata/annotations.yaml

operator percona-xtradb-cluster-operator (1.14.0)

---

operators/authorino-operator/0.11.0/bundle.Dockerfile
operators/authorino-operator/0.11.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
operators/authorino-operator/0.11.0/manifests/authorino-operator-manager-config_v1_configmap.yaml
operators/authorino-operator/0.11.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.11.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.0/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.11.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.11.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.11.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.11.0/metadata/annotations.yaml
operators/authorino-operator/0.11.0/tests/scorecard/config.yaml

operator authorino-operator (0.11.0)

---

operators/authorino-operator/0.11.1/bundle.Dockerfile
operators/authorino-operator/0.11.1/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.1/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.1/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.1/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.1/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.1/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
operators/authorino-operator/0.11.1/manifests/authorino-operator-manager-config_v1_configmap.yaml
operators/authorino-operator/0.11.1/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.1/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.11.1/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.11.1/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.11.1/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.11.1/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.11.1/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.11.1/metadata/annotations.yaml
operators/authorino-operator/0.11.1/tests/scorecard/config.yaml

operator authorino-operator (0.11.1)

---

operators/ndmspc-operator/0.11.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.11.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.11.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.11.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.11.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.11.0/metadata/annotations.yaml
operators/ndmspc-operator/0.11.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.11.0)

---

operators/awx-operator/2.13.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.13.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.13.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.13.1/manifests/awx-operator.v2.13.1.clusterserviceversion.yaml
operators/awx-operator/2.13.1/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.13.1/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.13.1/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.13.1/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.13.1/metadata/annotations.yaml
operators/awx-operator/2.13.1/tests/scorecard/config.yaml

operator awx-operator (2.13.1)

operator awx-operator (2.13.1)

---

operators/ndmspc-operator/0.11.1/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.11.1/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.11.1/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.11.1/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.11.1/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.11.1/metadata/annotations.yaml
operators/ndmspc-operator/0.11.1/tests/scorecard/config.yaml

operator ndmspc-operator (0.11.1)

---

operators/ndmspc-operator/0.11.2/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.11.2/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.11.2/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.11.2/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.11.2/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.11.2/metadata/annotations.yaml
operators/ndmspc-operator/0.11.2/tests/scorecard/config.yaml

operator ndmspc-operator (0.11.2)

---

operators/ndmspc-operator/0.11.3/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.11.3/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.11.3/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.11.3/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.11.3/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.11.3/metadata/annotations.yaml
operators/ndmspc-operator/0.11.3/tests/scorecard/config.yaml

operator ndmspc-operator (0.11.3)

---

operators/trivy-operator/0.19.0/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/manifests/trivy-operator.v0.19.0.clusterserviceversion.yaml
operators/trivy-operator/0.19.0/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.0/metadata/annotations.yaml

operator trivy-operator (0.19.0)

---

operators/nri-plugins-operator/0.4.1/manifests/config.nri_balloonspolicies.yaml
operators/nri-plugins-operator/0.4.1/manifests/config.nri_nriplugindeployments.yaml
operators/nri-plugins-operator/0.4.1/manifests/config.nri_templatepolicies.yaml
operators/nri-plugins-operator/0.4.1/manifests/config.nri_topologyawarepolicies.yaml
operators/nri-plugins-operator/0.4.1/manifests/nri-plugins-operator-controller-manager-metrics-service_v1_service.yaml
operators/nri-plugins-operator/0.4.1/manifests/nri-plugins-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nri-plugins-operator/0.4.1/manifests/nri-plugins-operator.clusterserviceversion.yaml
operators/nri-plugins-operator/0.4.1/manifests/topology.node.k8s.io_noderesourcetopologies.yaml
operators/nri-plugins-operator/0.4.1/metadata/annotations.yaml
operators/nri-plugins-operator/0.4.1/tests/scorecard/config.yaml

Submit nri-plugins-operator ([0.4.1](https://github.com/containers/nri-plugins/releases/tag/v0.4.1)) version.

operator nri-plugins-operator (0.4.1)

---

operators/node-maintenance-operator/0.17.0/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml
operators/node-maintenance-operator/0.17.0/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/node-maintenance-operator/0.17.0/manifests/node-maintenance-operator-webhook-service_v1_service.yaml
operators/node-maintenance-operator/0.17.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
operators/node-maintenance-operator/0.17.0/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml
operators/node-maintenance-operator/0.17.0/metadata/annotations.yaml
operators/node-maintenance-operator/0.17.0/tests/scorecard/config.yaml

Let NMO v0.17.0 be available on K8s community
--

operator node-maintenance-operator (0.17.0)

---

operators/debezium-operator/2.5.1/manifests/debezium-operator.v2.5.1.clusterserviceversion.yaml

This PR contains a security fix removing leaked credentials. The leaked credentials were since revoked and this PR just sanitises the affected files.

operator [O] debezium-operator (2.5.1)

---

operators/ndmspc-operator/0.11.4/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.11.4/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.11.4/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.11.4/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.11.4/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.11.4/metadata/annotations.yaml
operators/ndmspc-operator/0.11.4/metadata/dependencies.yaml
operators/ndmspc-operator/0.11.4/tests/scorecard/config.yaml

operator ndmspc-operator (0.11.4)

---

operators/wildfly/1.0.0/bundle.Dockerfile
operators/wildfly/1.0.0/manifests/wildfly-operator.v1.0.0.clusterserviceversion.yaml
operators/wildfly/1.0.0/manifests/wildflyservers.wildfly.org.crd.yaml
operators/wildfly/1.0.0/metadata/annotations.yaml

Upgrade WildFly Operator to 1.0.0
Signed-off-by: Yeray Borges <yborgess@redhat.com>

operator wildfly (1.0.0)

---

operators/clickhouse/0.23.3/manifests/clickhouse-operator.v0.23.3.clusterserviceversion.yaml
operators/clickhouse/0.23.3/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.3/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.3/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.23.3/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.3/metadata/annotations.yaml

operator clickhouse (0.23.3)

---

operators/ndmspc-operator/0.11.5/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.11.5/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.11.5/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.11.5/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.11.5/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.11.5/metadata/annotations.yaml
operators/ndmspc-operator/0.11.5/tests/scorecard/config.yaml

operator ndmspc-operator (0.11.5)

---

operators/ndmspc-operator/0.11.6/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.11.6/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.11.6/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.11.6/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.11.6/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.11.6/metadata/annotations.yaml
operators/ndmspc-operator/0.11.6/tests/scorecard/config.yaml

operator ndmspc-operator (0.11.6)

---

operators/trivy-operator/0.19.1/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/manifests/trivy-operator.v0.19.1.clusterserviceversion.yaml
operators/trivy-operator/0.19.1/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.1/metadata/annotations.yaml

operator trivy-operator (0.19.1)

---

operators/mongodb-atlas-kubernetes/2.2.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.2.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.2.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.2.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.2.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.2.0/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.2.0)

---

operators/ceph-s3-operator/0.3.7/manifests/ceph-s3-operator-controller-manager-config_v1_secret.yaml
operators/ceph-s3-operator/0.3.7/manifests/ceph-s3-operator-controller-manager-metrics-service_v1_service.yaml
operators/ceph-s3-operator/0.3.7/manifests/ceph-s3-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ceph-s3-operator/0.3.7/manifests/ceph-s3-operator-webhook-service_v1_service.yaml
operators/ceph-s3-operator/0.3.7/manifests/ceph-s3-operator.clusterserviceversion.yaml
operators/ceph-s3-operator/0.3.7/manifests/s3.snappcloud.io_s3buckets.yaml
operators/ceph-s3-operator/0.3.7/manifests/s3.snappcloud.io_s3userclaims.yaml
operators/ceph-s3-operator/0.3.7/manifests/s3.snappcloud.io_s3users.yaml
operators/ceph-s3-operator/0.3.7/metadata/annotations.yaml
operators/ceph-s3-operator/0.3.7/tests/scorecard/config.yaml

operator ceph-s3-operator (0.3.7)

---

operators/hpe-csi-operator/2.4.1/Dockerfile
operators/hpe-csi-operator/2.4.1/manifests/hpe-csi-operator-controller-manager-metrics-service_v1_service.yaml
operators/hpe-csi-operator/2.4.1/manifests/hpe-csi-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/hpe-csi-operator/2.4.1/manifests/hpe-csi-operator.v2.4.1.clusterserviceversion.yaml
operators/hpe-csi-operator/2.4.1/manifests/storage.hpe.com_hpecsidrivers.yaml
operators/hpe-csi-operator/2.4.1/metadata/annotations.yaml
operators/hpe-csi-operator/2.4.1/tests/scorecard/config.yaml

operator hpe-csi-operator (2.4.1)

---

operators/grafana-operator/5.8.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.8.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.8.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.8.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.8.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.8.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.8.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.8.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.8.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.8.0/metadata/annotations.yaml

This also updates the reviewers to the current maintainers of the Grafana Operator (cc @NissesSenap)
--

operator grafana-operator (5.8.0)

---

operators/grafana-operator/ci.yaml

This updates the reviewers of the Grafana Operator to reflect the current core-team

operator [CI] grafana-operator

---

operators/gitlab-operator-kubernetes/0.30.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.30.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.30.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.30.0)

---

operators/awx-operator/2.14.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.14.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.14.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.14.0/manifests/awx-operator.v2.14.0.clusterserviceversion.yaml
operators/awx-operator/2.14.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.14.0/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.14.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.14.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.14.0/metadata/annotations.yaml
operators/awx-operator/2.14.0/tests/scorecard/config.yaml

operator awx-operator (2.14.0)

operator awx-operator (2.14.0)

---

operators/customized-user-remediation/0.1.0/manifests/customized-user-remediation-controller-manager-metrics-service_v1_service.yaml
operators/customized-user-remediation/0.1.0/manifests/customized-user-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/customized-user-remediation/0.1.0/manifests/customized-user-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/customized-user-remediation/0.1.0/manifests/customized-user-remediation-webhook-service_v1_service.yaml
operators/customized-user-remediation/0.1.0/manifests/customized-user-remediation.clusterserviceversion.yaml
operators/customized-user-remediation/0.1.0/manifests/customized-user-remediation.medik8s.io_customizeduserremediationconfigs.yaml
operators/customized-user-remediation/0.1.0/manifests/customized-user-remediation.medik8s.io_customizeduserremediations.yaml
operators/customized-user-remediation/0.1.0/manifests/customized-user-remediation.medik8s.io_customizeduserremediationtemplates.yaml
operators/customized-user-remediation/0.1.0/metadata/annotations.yaml
operators/customized-user-remediation/0.1.0/tests/scorecard/config.yaml
operators/customized-user-remediation/ci.yaml

operator [N] [CI] customized-user-remediation (0.1.0)

---

operators/elastic-cloud-eck/2.12.0/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.0/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.0/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.0/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.12.0/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.0/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.0/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.0/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.0/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.0/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.0/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.0/metadata/annotations.yaml
operators/elastic-cloud-eck/ci.yaml

Update the ECK operator to the latest version `2.12.0`.

operator [CI] elastic-cloud-eck (2.12.0)

---

operators/elastic-cloud-eck/2.12.1/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.1/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.1/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.1/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.12.1/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.1/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.1/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.1/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.1/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.1/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.1/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.12.1/metadata/annotations.yaml

Update the ECK operator to the latest version `2.12.1`.

operator elastic-cloud-eck (2.12.1)

---

operators/microcks/1.9.0/manifests/microcks-operator.v1.9.0.clusterserviceversion.yaml
operators/microcks/1.9.0/manifests/microcksinstall.crd.yaml
operators/microcks/1.9.0/metadata/annotations.yaml

operator microcks (1.9.0)

---

operators/trivy-operator/0.19.2/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/manifests/trivy-operator.v0.19.2.clusterserviceversion.yaml
operators/trivy-operator/0.19.2/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.2/metadata/annotations.yaml

operator trivy-operator (0.19.2)

---

operators/gitlab-operator-kubernetes/0.30.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.30.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.30.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.30.1)

---

operators/trivy-operator/0.19.3/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/manifests/trivy-operator.v0.19.3.clusterserviceversion.yaml
operators/trivy-operator/0.19.3/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.3/metadata/annotations.yaml

operator trivy-operator (0.19.3)

---

operators/cass-operator-community/1.19.1/manifests/cass-operator-manager-config_v1_configmap.yaml
operators/cass-operator-community/1.19.1/manifests/cass-operator-webhook-service_v1_service.yaml
operators/cass-operator-community/1.19.1/manifests/cass-operator.clusterserviceversion.yaml
operators/cass-operator-community/1.19.1/manifests/cassandra.datastax.com_cassandradatacenters.yaml
operators/cass-operator-community/1.19.1/manifests/control.k8ssandra.io_cassandratasks.yaml
operators/cass-operator-community/1.19.1/metadata/annotations.yaml
operators/cass-operator-community/1.19.1/tests/scorecard/config.yaml

operator cass-operator-community (1.19.1)

---

operators/nri-plugins-operator/0.5.1/manifests/config.nri_balloonspolicies.yaml
operators/nri-plugins-operator/0.5.1/manifests/config.nri_nriplugindeployments.yaml
operators/nri-plugins-operator/0.5.1/manifests/config.nri_templatepolicies.yaml
operators/nri-plugins-operator/0.5.1/manifests/config.nri_topologyawarepolicies.yaml
operators/nri-plugins-operator/0.5.1/manifests/nri-plugins-operator-controller-manager-metrics-service_v1_service.yaml
operators/nri-plugins-operator/0.5.1/manifests/nri-plugins-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nri-plugins-operator/0.5.1/manifests/nri-plugins-operator.clusterserviceversion.yaml
operators/nri-plugins-operator/0.5.1/manifests/topology.node.k8s.io_noderesourcetopologies.yaml
operators/nri-plugins-operator/0.5.1/metadata/annotations.yaml
operators/nri-plugins-operator/0.5.1/tests/scorecard/config.yaml

Submit nri-plugins-operator ([0.5.1](https://github.com/containers/nri-plugins/releases/tag/v0.5.1)) version.

operator nri-plugins-operator (0.5.1)

---

operators/external-secrets-operator/0.9.14/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.14/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.14/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.14/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.14/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.14/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.14/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.9.14/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.14/metadata/annotations.yaml
operators/external-secrets-operator/0.9.14/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.14

operator external-secrets-operator (0.9.14)

---

operators/project-quay/3.11.0/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.11.0/manifests/quayregistries.crd.yaml
operators/project-quay/3.11.0/metadata/annotations.yaml

Add 3.11.0 to community operators

operator project-quay (3.11.0)

---

operators/ibm-application-gateway-operator/24.4.0/manifests/ibm-application-gateway-operator-ctrl-mgr-metrics-service_v1_service.yaml
operators/ibm-application-gateway-operator/24.4.0/manifests/ibm-application-gateway-operator-manager-config_v1_configmap.yaml
operators/ibm-application-gateway-operator/24.4.0/manifests/ibm-application-gateway-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ibm-application-gateway-operator/24.4.0/manifests/ibm-application-gateway-operator-webhook-service_v1_service.yaml
operators/ibm-application-gateway-operator/24.4.0/manifests/ibm-application-gateway-operator.clusterserviceversion.yaml
operators/ibm-application-gateway-operator/24.4.0/manifests/ibm.com_ibmapplicationgateways.yaml
operators/ibm-application-gateway-operator/24.4.0/metadata/annotations.yaml
operators/ibm-application-gateway-operator/24.4.0/tests/scorecard/config.yaml

operator ibm-application-gateway-operator (24.4.0)

---

operators/dynatrace-operator/1.0.0/Dockerfile
operators/dynatrace-operator/1.0.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.0.0/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.0.0/metadata/annotations.yaml

operator dynatrace-operator (1.0.0)

---

operators/dapr-kubernetes-operator/0.0.6/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
operators/dapr-kubernetes-operator/0.0.6/manifests/operator.dapr.io_daprcontrolplanes.yaml
operators/dapr-kubernetes-operator/0.0.6/manifests/operator.dapr.io_daprcruiscontrols.yaml
operators/dapr-kubernetes-operator/0.0.6/manifests/operator.dapr.io_daprinstances.yaml
operators/dapr-kubernetes-operator/0.0.6/metadata/annotations.yaml
operators/dapr-kubernetes-operator/0.0.6/tests/scorecard/config.yaml

operator dapr-kubernetes-operator (0.0.6)

---

operators/yaks/0.18.0/manifests/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.18.0/manifests/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.18.0/manifests/yaks.v0.18.0.clusterserviceversion.yaml
operators/yaks/0.18.0/metadata/annotations.yaml
operators/yaks/0.18.0/tests/scorecard/config.yaml

operator yaks (0.18.0)

---

operators/trivy-operator/0.19.4/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/manifests/trivy-operator.v0.19.4.clusterserviceversion.yaml
operators/trivy-operator/0.19.4/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.19.4/metadata/annotations.yaml

operator trivy-operator (0.19.4)

---

operators/verticadb-operator/2.1.2/manifests/vertica.com_eventtriggers.yaml
operators/verticadb-operator/2.1.2/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/2.1.2/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/2.1.2/manifests/vertica.com_verticarestorepointsqueries.yaml
operators/verticadb-operator/2.1.2/manifests/vertica.com_verticascrutinizers.yaml
operators/verticadb-operator/2.1.2/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/2.1.2/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/2.1.2/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/verticadb-operator/2.1.2/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/2.1.2/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/2.1.2/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/2.1.2/metadata/annotations.yaml
operators/verticadb-operator/2.1.2/tests/scorecard/config.yaml

operator verticadb-operator (2.1.2)

---

operators/camel-k/2.3.0/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.3.0/manifests/camel-k.v2.3.0.clusterserviceversion.yaml
operators/camel-k/2.3.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.3.0/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.3.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.3.0/manifests/integrationprofiles.camel.apache.org.crd.yaml
operators/camel-k/2.3.0/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.3.0/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/2.3.0/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.3.0/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.3.0/metadata/annotations.yaml
operators/camel-k/2.3.0/tests/scorecard/config.yaml

operator camel-k (2.3.0)

---

operators/security-profiles-operator/0.8.3/manifests/metrics-token_v1_secret.yaml
operators/security-profiles-operator/0.8.3/manifests/security-profiles-operator-profile_v1_configmap.yaml
operators/security-profiles-operator/0.8.3/manifests/security-profiles-operator.clusterserviceversion.yaml
operators/security-profiles-operator/0.8.3/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
operators/security-profiles-operator/0.8.3/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
operators/security-profiles-operator/0.8.3/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
operators/security-profiles-operator/0.8.3/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
operators/security-profiles-operator/0.8.3/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
operators/security-profiles-operator/0.8.3/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
operators/security-profiles-operator/0.8.3/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
operators/security-profiles-operator/0.8.3/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
operators/security-profiles-operator/0.8.3/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.3/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.3/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.3/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.3/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.8.3/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.8.3/manifests/spo-webhook_v1_serviceaccount.yaml
operators/security-profiles-operator/0.8.3/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.3/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.3/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.8.3/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.8.3/manifests/spod_v1_serviceaccount.yaml
operators/security-profiles-operator/0.8.3/metadata/annotations.yaml
operators/security-profiles-operator/0.8.3/tests/scorecard/config.yaml

Refers to https://github.com/kubernetes-sigs/security-profiles-operator/issues/2194

operator security-profiles-operator (0.8.3)

---

operators/dapr-kubernetes-operator/0.0.7/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
operators/dapr-kubernetes-operator/0.0.7/manifests/operator.dapr.io_daprcontrolplanes.yaml
operators/dapr-kubernetes-operator/0.0.7/manifests/operator.dapr.io_daprcruiscontrols.yaml
operators/dapr-kubernetes-operator/0.0.7/manifests/operator.dapr.io_daprinstances.yaml
operators/dapr-kubernetes-operator/0.0.7/metadata/annotations.yaml
operators/dapr-kubernetes-operator/0.0.7/tests/scorecard/config.yaml

Signed-off-by: Luca Burgazzoli <lburgazzoli@gmail.com>
--

operator dapr-kubernetes-operator (0.0.7)

---

operators/cloudnative-pg/ci.yaml

operator [CI] cloudnative-pg

---

operators/yaks/0.19.0/manifests/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.19.0/manifests/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.19.0/manifests/yaks.v0.19.0.clusterserviceversion.yaml
operators/yaks/0.19.0/metadata/annotations.yaml
operators/yaks/0.19.0/tests/scorecard/config.yaml

operator yaks (0.19.0)

---

operators/awx-operator/2.15.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.15.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.15.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.15.0/manifests/awx-operator.v2.15.0.clusterserviceversion.yaml
operators/awx-operator/2.15.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.15.0/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.15.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.15.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.15.0/metadata/annotations.yaml
operators/awx-operator/2.15.0/tests/scorecard/config.yaml

operator awx-operator (2.15.0)

operator awx-operator (2.15.0)

---

operators/cluster-manager/0.13.1/manifests/cluster-manager.clusterserviceversion.yaml
operators/cluster-manager/0.13.1/manifests/operator.open-cluster-management.io_clustermanagers.yaml
operators/cluster-manager/0.13.1/metadata/annotations.yaml

operator cluster-manager (0.13.1)

---

operators/argocd-operator/0.9.0/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
operators/argocd-operator/0.9.0/manifests/argocd-operator-manager-config_v1_configmap.yaml
operators/argocd-operator/0.9.0/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/argocd-operator/0.9.0/manifests/argocd-operator-webhook-service_v1_service.yaml
operators/argocd-operator/0.9.0/manifests/argocd-operator.v0.9.0.clusterserviceversion.yaml
operators/argocd-operator/0.9.0/manifests/argoproj.io_applications.yaml
operators/argocd-operator/0.9.0/manifests/argoproj.io_applicationsets.yaml
operators/argocd-operator/0.9.0/manifests/argoproj.io_appprojects.yaml
operators/argocd-operator/0.9.0/manifests/argoproj.io_argocdexports.yaml
operators/argocd-operator/0.9.0/manifests/argoproj.io_argocds.yaml
operators/argocd-operator/0.9.0/metadata/annotations.yaml

operator argocd-operator (0.9.0)

---

operators/argocd-operator/0.9.1/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
operators/argocd-operator/0.9.1/manifests/argocd-operator-manager-config_v1_configmap.yaml
operators/argocd-operator/0.9.1/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/argocd-operator/0.9.1/manifests/argocd-operator-webhook-service_v1_service.yaml
operators/argocd-operator/0.9.1/manifests/argocd-operator.v0.9.1.clusterserviceversion.yaml
operators/argocd-operator/0.9.1/manifests/argoproj.io_applications.yaml
operators/argocd-operator/0.9.1/manifests/argoproj.io_applicationsets.yaml
operators/argocd-operator/0.9.1/manifests/argoproj.io_appprojects.yaml
operators/argocd-operator/0.9.1/manifests/argoproj.io_argocdexports.yaml
operators/argocd-operator/0.9.1/manifests/argoproj.io_argocds.yaml
operators/argocd-operator/0.9.1/metadata/annotations.yaml

operator argocd-operator (0.9.1)

---

operators/ndmspc-operator/0.20240412.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.20240412.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.20240412.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.20240412.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.20240412.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.20240412.0/metadata/annotations.yaml
operators/ndmspc-operator/0.20240412.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.20240412.0)

---

operators/dapr-kubernetes-operator/0.0.8/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
operators/dapr-kubernetes-operator/0.0.8/manifests/operator.dapr.io_daprcontrolplanes.yaml
operators/dapr-kubernetes-operator/0.0.8/manifests/operator.dapr.io_daprcruiscontrols.yaml
operators/dapr-kubernetes-operator/0.0.8/manifests/operator.dapr.io_daprinstances.yaml
operators/dapr-kubernetes-operator/0.0.8/metadata/annotations.yaml
operators/dapr-kubernetes-operator/0.0.8/tests/scorecard/config.yaml

Signed-off-by: Luca Burgazzoli <lburgazzoli@gmail.com>
--

operator dapr-kubernetes-operator (0.0.8)

---

operators/external-secrets-operator/0.9.15-2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.15-2/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.15-2/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.15-2/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.15-2/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.15-2/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.15-2/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.9.15-2/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.15-2/metadata/annotations.yaml
operators/external-secrets-operator/0.9.15-2/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.15-2

operator external-secrets-operator (0.9.15-2)

---

operators/gitlab-operator-kubernetes/0.30.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.30.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.30.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.30.2)

---

operators/gitlab-operator-kubernetes/0.30.3/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.30.3/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.30.3/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.30.3)

---

operators/trident-operator/24.2.0/manifests/trident-operator.v24.2.0.clusterserviceversion.yaml
operators/trident-operator/24.2.0/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
operators/trident-operator/24.2.0/metadata/annotations.yaml
operators/trident-operator/ci.yaml

operator [CI] trident-operator (24.2.0)

---

operators/clickhouse/0.23.5/manifests/clickhouse-operator.v0.23.5.clusterserviceversion.yaml
operators/clickhouse/0.23.5/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.5/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.5/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.23.5/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.5/metadata/annotations.yaml

operator clickhouse (0.23.5)

---

operators/moodle-operator/0.6.12/manifests/m4e.krestomat.io_moodles.yaml
operators/moodle-operator/0.6.12/manifests/m4e.krestomat.io_nginxes.yaml
operators/moodle-operator/0.6.12/manifests/m4e.krestomat.io_phpfpms.yaml
operators/moodle-operator/0.6.12/manifests/m4e.krestomat.io_routines.yaml
operators/moodle-operator/0.6.12/manifests/moodle-operator-controller-manager-metrics-service_v1_service.yaml
operators/moodle-operator/0.6.12/manifests/moodle-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.12/manifests/moodle-operator.clusterserviceversion.yaml
operators/moodle-operator/0.6.12/metadata/annotations.yaml
operators/moodle-operator/0.6.12/tests/scorecard/config.yaml
operators/moodle-operator/ci.yaml

operator [N] [CI] moodle-operator (0.6.12)

---

operators/postgres-operator-krestomatio/0.3.7/manifests/postgres-operator-controller-manager-metrics-service_v1_service.yaml
operators/postgres-operator-krestomatio/0.3.7/manifests/postgres-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/postgres-operator-krestomatio/0.3.7/manifests/postgres-operator.clusterserviceversion.yaml
operators/postgres-operator-krestomatio/0.3.7/manifests/postgres.krestomat.io_postgres.yaml
operators/postgres-operator-krestomatio/0.3.7/metadata/annotations.yaml
operators/postgres-operator-krestomatio/0.3.7/tests/scorecard/config.yaml
operators/postgres-operator-krestomatio/ci.yaml

operator [N] [CI] postgres-operator-krestomatio (0.3.7)

---

operators/keydb-operator/0.3.7/manifests/keydb-operator-controller-manager-metrics-service_v1_service.yaml
operators/keydb-operator/0.3.7/manifests/keydb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/keydb-operator/0.3.7/manifests/keydb-operator.clusterserviceversion.yaml
operators/keydb-operator/0.3.7/manifests/keydb.krestomat.io_keydbs.yaml
operators/keydb-operator/0.3.7/metadata/annotations.yaml
operators/keydb-operator/0.3.7/tests/scorecard/config.yaml
operators/keydb-operator/ci.yaml

operator [N] [CI] keydb-operator (0.3.7)

---

operators/nfs-operator/0.4.7/manifests/nfs-operator-controller-manager-metrics-service_v1_service.yaml
operators/nfs-operator/0.4.7/manifests/nfs-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nfs-operator/0.4.7/manifests/nfs-operator.clusterserviceversion.yaml
operators/nfs-operator/0.4.7/manifests/nfs.krestomat.io_ganeshas.yaml
operators/nfs-operator/0.4.7/manifests/nfs.krestomat.io_routines.yaml
operators/nfs-operator/0.4.7/metadata/annotations.yaml
operators/nfs-operator/0.4.7/tests/scorecard/config.yaml
operators/nfs-operator/ci.yaml

operator [N] [CI] nfs-operator (0.4.7)

---

operators/susql-operator/0.0.3/manifests/susql-operator-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.3/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.3/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.3/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.3/metadata/annotations.yaml
operators/susql-operator/0.0.3/tests/scorecard/config.yaml

operator susql-operator (0.0.3)

---

operators/susql-operator/0.0.4/manifests/susql-operator-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.4/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.4/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.4/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.4/metadata/annotations.yaml
operators/susql-operator/0.0.4/tests/scorecard/config.yaml

operator susql-operator (0.0.4)

---

operators/hpe-csi-operator/2.4.2/Dockerfile
operators/hpe-csi-operator/2.4.2/manifests/hpe-csi-operator-controller-manager-metrics-service_v1_service.yaml
operators/hpe-csi-operator/2.4.2/manifests/hpe-csi-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/hpe-csi-operator/2.4.2/manifests/hpe-csi-operator.v2.4.2.clusterserviceversion.yaml
operators/hpe-csi-operator/2.4.2/manifests/storage.hpe.com_hpecsidrivers.yaml
operators/hpe-csi-operator/2.4.2/metadata/annotations.yaml
operators/hpe-csi-operator/2.4.2/tests/scorecard/config.yaml

operator hpe-csi-operator (2.4.2)

---

operators/external-secrets-operator/0.9.16/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.16/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.16/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.16/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.16/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.16/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.16/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.9.16/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.16/metadata/annotations.yaml
operators/external-secrets-operator/0.9.16/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.16

operator external-secrets-operator (0.9.16)

---

operators/susql-operator/0.0.5/manifests/susql-operator-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.5/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.5/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.5/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.5/metadata/annotations.yaml
operators/susql-operator/0.0.5/tests/scorecard/config.yaml

operator susql-operator (0.0.5)

---

operators/moodle-operator/0.6.17/manifests/m4e.krestomat.io_moodles.yaml
operators/moodle-operator/0.6.17/manifests/m4e.krestomat.io_nginxes.yaml
operators/moodle-operator/0.6.17/manifests/m4e.krestomat.io_phpfpms.yaml
operators/moodle-operator/0.6.17/manifests/m4e.krestomat.io_routines.yaml
operators/moodle-operator/0.6.17/manifests/moodle-operator-controller-manager-metrics-service_v1_service.yaml
operators/moodle-operator/0.6.17/manifests/moodle-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.17/manifests/moodle-operator.clusterserviceversion.yaml
operators/moodle-operator/0.6.17/metadata/annotations.yaml
operators/moodle-operator/0.6.17/tests/scorecard/config.yaml

operator moodle-operator (0.6.17)

---

operators/keydb-operator/0.3.13/manifests/keydb-operator-controller-manager-metrics-service_v1_service.yaml
operators/keydb-operator/0.3.13/manifests/keydb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/keydb-operator/0.3.13/manifests/keydb-operator.clusterserviceversion.yaml
operators/keydb-operator/0.3.13/manifests/keydb.krestomat.io_keydbs.yaml
operators/keydb-operator/0.3.13/metadata/annotations.yaml
operators/keydb-operator/0.3.13/tests/scorecard/config.yaml

operator keydb-operator (0.3.13)

---

operators/nfs-operator/0.4.12/manifests/nfs-operator-controller-manager-metrics-service_v1_service.yaml
operators/nfs-operator/0.4.12/manifests/nfs-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nfs-operator/0.4.12/manifests/nfs-operator.clusterserviceversion.yaml
operators/nfs-operator/0.4.12/manifests/nfs.krestomat.io_ganeshas.yaml
operators/nfs-operator/0.4.12/manifests/nfs.krestomat.io_routines.yaml
operators/nfs-operator/0.4.12/metadata/annotations.yaml
operators/nfs-operator/0.4.12/tests/scorecard/config.yaml

operator nfs-operator (0.4.12)

---

operators/postgres-operator-krestomatio/0.3.12/manifests/postgres-operator-controller-manager-metrics-service_v1_service.yaml
operators/postgres-operator-krestomatio/0.3.12/manifests/postgres-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/postgres-operator-krestomatio/0.3.12/manifests/postgres-operator.clusterserviceversion.yaml
operators/postgres-operator-krestomatio/0.3.12/manifests/postgres.krestomat.io_postgres.yaml
operators/postgres-operator-krestomatio/0.3.12/metadata/annotations.yaml
operators/postgres-operator-krestomatio/0.3.12/tests/scorecard/config.yaml

operator postgres-operator-krestomatio (0.3.12)

---

operators/susql-operator/0.0.6/manifests/susql-operator-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.6/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.6/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.6/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.6/metadata/annotations.yaml
operators/susql-operator/0.0.6/tests/scorecard/config.yaml

operator susql-operator (0.0.6)

---

operators/lms-moodle-operator/0.4.5/manifests/lms-moodle-operator-controller-manager-metrics-service_v1_service.yaml
operators/lms-moodle-operator/0.4.5/manifests/lms-moodle-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/lms-moodle-operator/0.4.5/manifests/lms-moodle-operator.clusterserviceversion.yaml
operators/lms-moodle-operator/0.4.5/manifests/lms.krestomat.io_lmsmoodles.yaml
operators/lms-moodle-operator/0.4.5/manifests/lms.krestomat.io_lmsmoodletemplates.yaml
operators/lms-moodle-operator/0.4.5/metadata/annotations.yaml
operators/lms-moodle-operator/0.4.5/metadata/dependencies.yaml
operators/lms-moodle-operator/0.4.5/tests/scorecard/config.yaml

operator [N] lms-moodle-operator (0.4.5)

---

operators/tektoncd-operator/0.70.0/manifests/config-logging_v1_configmap.yaml
operators/tektoncd-operator/0.70.0/manifests/operator.tekton.dev_tektonchains.yaml
operators/tektoncd-operator/0.70.0/manifests/operator.tekton.dev_tektonconfigs.yaml
operators/tektoncd-operator/0.70.0/manifests/operator.tekton.dev_tektondashboards.yaml
operators/tektoncd-operator/0.70.0/manifests/operator.tekton.dev_tektonhubs.yaml
operators/tektoncd-operator/0.70.0/manifests/operator.tekton.dev_tektoninstallersets.yaml
operators/tektoncd-operator/0.70.0/manifests/operator.tekton.dev_tektonpipelines.yaml
operators/tektoncd-operator/0.70.0/manifests/operator.tekton.dev_tektonresults.yaml
operators/tektoncd-operator/0.70.0/manifests/operator.tekton.dev_tektontriggers.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-config-defaults_v1_configmap.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-config-observability_v1_configmap.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-config-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-config-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-operator-controller-config-leader-election_v1_configmap.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_role.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-operator-info_v1_configmap.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-operator-webhook-certs_v1_secret.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-operator-webhook-config-leader-election_v1_configmap.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-operator-webhook_v1_service.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-operator_v1_service.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-result-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tektoncd-operator/0.70.0/manifests/tekton-result-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/tektoncd-operator/0.70.0/manifests/tektoncd-operator.clusterserviceversion.yaml
operators/tektoncd-operator/0.70.0/metadata/annotations.yaml
operators/tektoncd-operator/0.70.0/tests/scorecard/config.yaml

operator tektoncd-operator (0.70.0)

---

operators/move2kube-operator/0.3.13/bundle.Dockerfile
operators/move2kube-operator/0.3.13/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.13/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.13/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.13/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.13/metadata/annotations.yaml
operators/move2kube-operator/0.3.13/tests/scorecard/config.yaml

An automated PR to update move2kube-operator to v0.3.13

operator move2kube-operator (0.3.13)

---

operators/dell-csm-operator/1.5.0/manifests/apexconnectivityclients.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.5.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.5.0/manifests/dell-csm-operator.v1.5.0.clusterserviceversion.yaml
operators/dell-csm-operator/1.5.0/metadata/annotations.yaml
operators/dell-csm-operator/1.5.0/tests/scorecard/config.yaml

operator dell-csm-operator (1.5.0)

---

operators/trivy-operator/0.20.0/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/manifests/trivy-operator.v0.20.0.clusterserviceversion.yaml
operators/trivy-operator/0.20.0/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.0/metadata/annotations.yaml

operator trivy-operator (0.20.0)

---

operators/gitlab-operator-kubernetes/0.31.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.31.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.31.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.31.0)

---

operators/deployment-validation-operator/0.7.6/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.7.6/manifests/deploymentvalidationoperator.0.7.6.clusterserviceversion.yaml
operators/deployment-validation-operator/0.7.6/metadata/annotations.yaml
operators/deployment-validation-operator/0.7.6/tests/scorecard/config.yaml

operator deployment-validation-operator (0.7.6)

---

operators/project-quay/3.10.5/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.5/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.5/metadata/annotations.yaml

Add 3.10.5 to community operators

operator [R] project-quay (3.10.5 3.11.0)

---

operators/debezium-operator/ci.yaml

Add @obabec as allowed reviewer

operator [CI] debezium-operator

---

operators/susql-operator/0.0.7/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.7/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.7/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.7/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.7/metadata/annotations.yaml
operators/susql-operator/0.0.7/tests/scorecard/config.yaml

operator susql-operator (0.0.7)

---

operators/awx-operator/2.16.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.16.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.16.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.16.0/manifests/awx-operator.v2.16.0.clusterserviceversion.yaml
operators/awx-operator/2.16.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.16.0/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.16.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.16.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.16.0/metadata/annotations.yaml
operators/awx-operator/2.16.0/tests/scorecard/config.yaml

operator awx-operator (2.16.0)

operator awx-operator (2.16.0)

---

operators/trivy-operator/0.20.1/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/manifests/trivy-operator.v0.20.1.clusterserviceversion.yaml
operators/trivy-operator/0.20.1/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.20.1/metadata/annotations.yaml

operator trivy-operator (0.20.1)

---

operators/yaks/0.19.1/manifests/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.19.1/manifests/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.19.1/manifests/yaks.v0.19.1.clusterserviceversion.yaml
operators/yaks/0.19.1/metadata/annotations.yaml
operators/yaks/0.19.1/tests/scorecard/config.yaml

operator yaks (0.19.1)

---

operators/susql-operator/0.0.8/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.8/manifests/susql-operator-susql-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
operators/susql-operator/0.0.8/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.8/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.8/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.8/metadata/annotations.yaml
operators/susql-operator/0.0.8/metadata/dependencies.yaml
operators/susql-operator/0.0.8/tests/scorecard/config.yaml

operator susql-operator (0.0.8)

---

operators/mongodb-atlas-kubernetes/2.2.2/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.2.2/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.2.2/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.2.2/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.2.2/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.2.2/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.2.2)

---

operators/kernel-module-management/2.1.0/manifests/kernel-module-management.clusterserviceversion.yaml

operator [O] kernel-module-management (2.1.0)

---

operators/pubsubplus-eventbroker-operator/1.0.3/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
operators/pubsubplus-eventbroker-operator/1.0.3/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
operators/pubsubplus-eventbroker-operator/1.0.3/metadata/annotations.yaml
operators/pubsubplus-eventbroker-operator/1.0.3/tests/scorecard/config.yaml

operator pubsubplus-eventbroker-operator (1.0.3)

---

operators/susql-operator/0.0.9/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.9/manifests/susql-operator-susql-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
operators/susql-operator/0.0.9/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.9/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.9/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.9/metadata/annotations.yaml
operators/susql-operator/0.0.9/metadata/dependencies.yaml
operators/susql-operator/0.0.9/tests/scorecard/config.yaml

operator susql-operator (0.0.9)

---

operators/cluster-aas-operator/0.1.4/manifests/argo_cd_cluser_rb.yaml
operators/cluster-aas-operator/0.1.4/manifests/argo_cd_cluster_role.yaml
operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml
operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml
operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator-repo-bridge.yaml
operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator-webhook-service_v1_service.yaml
operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator.clusterserviceversion.yaml
operators/cluster-aas-operator/0.1.4/manifests/cluster_templates_user_ct_role.yaml
operators/cluster-aas-operator/0.1.4/manifests/cluster_templates_user_role.yaml
operators/cluster-aas-operator/0.1.4/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml
operators/cluster-aas-operator/0.1.4/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml
operators/cluster-aas-operator/0.1.4/manifests/clustertemplate.openshift.io_clustertemplates.yaml
operators/cluster-aas-operator/0.1.4/manifests/clustertemplate.openshift.io_clustertemplatesetup.yaml
operators/cluster-aas-operator/0.1.4/manifests/clustertemplate.openshift.io_config.yaml
operators/cluster-aas-operator/0.1.4/metadata/annotations.yaml
operators/cluster-aas-operator/0.1.4/metadata/dependencies.yaml
operators/cluster-aas-operator/0.1.4/tests/scorecard/config.yaml

operator cluster-aas-operator (0.1.4)

---

operators/gitlab-operator-kubernetes/0.31.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.31.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.31.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.31.1)

---

operators/susql-operator/0.0.13/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.13/manifests/susql-operator-susql-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
operators/susql-operator/0.0.13/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.13/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.13/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.13/metadata/annotations.yaml
operators/susql-operator/0.0.13/metadata/dependencies.yaml
operators/susql-operator/0.0.13/tests/scorecard/config.yaml

operator susql-operator (0.0.13)

---

operators/kaoto-operator/ci.yaml

operator [CI] kaoto-operator

---

operators/awx-operator/2.16.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.16.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.16.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.16.1/manifests/awx-operator.v2.16.1.clusterserviceversion.yaml
operators/awx-operator/2.16.1/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.16.1/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.16.1/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.16.1/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.16.1/metadata/annotations.yaml
operators/awx-operator/2.16.1/tests/scorecard/config.yaml

operator awx-operator (2.16.1)

operator awx-operator (2.16.1)

---

operators/mongodb-enterprise/1.25.0/bundle.Dockerfile
operators/mongodb-enterprise/1.25.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.25.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.25.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.25.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.25.0/manifests/mongodb-enterprise-operator-service_v1_service.yaml
operators/mongodb-enterprise/1.25.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.25.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.25.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.25.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.25.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.25.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.25.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.25.0/tests/scorecard/config.yaml

operator mongodb-enterprise (1.25.0)

---

operators/knative-operator/1.14.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.14.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.14.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.14.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.14.0/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.14.0/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.14.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.14.0/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.14.0/manifests/knative-operator.v1.14.0.clusterserviceversion.yaml
operators/knative-operator/1.14.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.14.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.14.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.14.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.14.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.14.0/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.14.0/metadata/annotations.yaml
operators/knative-operator/1.14.0/tests/scorecard/config.yaml

operator knative-operator (1.14.0)

---

operators/external-secrets-operator/0.9.17/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.17/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.17/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.17/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.17/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.17/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.17/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.9.17/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.17/metadata/annotations.yaml
operators/external-secrets-operator/0.9.17/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.17

operator external-secrets-operator (0.9.17)

---

operators/apicurio-registry/1.1.2-v2.5.11.final/bundle.Dockerfile
operators/apicurio-registry/1.1.2-v2.5.11.final/manifests/apicurio-registry-operator.clusterserviceversion.yaml
operators/apicurio-registry/1.1.2-v2.5.11.final/manifests/registry.apicur.io_apicurioregistries.yaml
operators/apicurio-registry/1.1.2-v2.5.11.final/metadata/annotations.yaml
operators/apicurio-registry/1.1.2-v2.5.11.final/tests/scorecard/config.yaml

operator apicurio-registry (1.1.2-v2.5.11.final)

---

operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberocouchdbs.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberoelasticsearches.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberokafkas.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberomails.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberomemcacheds.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberomongodbs.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberomysqls.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberopostgresqls.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberorabbitmqs.yaml
operators/kubero-operator/0.0.159/manifests/application.kubero.dev_kuberoredis.yaml
operators/kubero-operator/0.0.159/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.0.159/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.0.159/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.0.159/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.0.159/metadata/annotations.yaml
operators/kubero-operator/0.0.159/tests/scorecard/config.yaml

operator kubero-operator (0.0.159)

---

operators/dns-operator/0.2.0/manifests/dns-operator-controller-manager-metrics-service_v1_service.yaml
operators/dns-operator/0.2.0/manifests/dns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dns-operator/0.2.0/manifests/dns-operator.clusterserviceversion.yaml
operators/dns-operator/0.2.0/manifests/kuadrant.io_dnsrecords.yaml
operators/dns-operator/0.2.0/manifests/kuadrant.io_managedzones.yaml
operators/dns-operator/0.2.0/metadata/annotations.yaml
operators/dns-operator/0.2.0/tests/scorecard/config.yaml

operator dns-operator (0.2.0)

---

operators/limitador-operator/0.8.0/bundle.Dockerfile
operators/limitador-operator/0.8.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml
operators/limitador-operator/0.8.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
operators/limitador-operator/0.8.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/limitador-operator/0.8.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/0.8.0/manifests/limitador.kuadrant.io_limitadors.yaml
operators/limitador-operator/0.8.0/metadata/annotations.yaml
operators/limitador-operator/0.8.0/tests/scorecard/config.yaml

operator limitador-operator (0.8.0)

---

operators/camel-k/2.3.1/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.3.1/manifests/camel-k.v2.3.1.clusterserviceversion.yaml
operators/camel-k/2.3.1/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.3.1/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.3.1/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.3.1/manifests/integrationprofiles.camel.apache.org.crd.yaml
operators/camel-k/2.3.1/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.3.1/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/2.3.1/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.3.1/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.3.1/metadata/annotations.yaml
operators/camel-k/2.3.1/tests/scorecard/config.yaml

* [] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
-- …

operator camel-k (2.3.1)

---

operators/dynatrace-operator/1.1.0/Dockerfile
operators/dynatrace-operator/1.1.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.1.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.1.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.1.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.1.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.1.0/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.1.0/metadata/annotations.yaml

operator dynatrace-operator (1.1.0)

---

operators/bpfman-operator/0.4.1/bundle.Dockerfile
operators/bpfman-operator/0.4.1/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-config_v1_configmap.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-daemon_v1_serviceaccount.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-operator.clusterserviceversion.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman.io_bpfprograms.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman.io_fentryprograms.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman.io_fexitprograms.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman.io_kprobeprograms.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman.io_tcprograms.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman.io_tracepointprograms.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman.io_uprobeprograms.yaml
operators/bpfman-operator/0.4.1/manifests/bpfman.io_xdpprograms.yaml
operators/bpfman-operator/0.4.1/metadata/annotations.yaml
operators/bpfman-operator/0.4.1/metadata/dependencies.yaml
operators/bpfman-operator/0.4.1/tests/scorecard/config.yaml
operators/bpfman-operator/ci.yaml

operator [N] [CI] bpfman-operator (0.4.1)

---

operators/skupper-operator/1.7.0/manifests/skupper-operator.v1.7.0.clusterserviceversion.yaml
operators/skupper-operator/1.7.0/metadata/annotations.yaml

operator skupper-operator (1.7.0)

---

operators/snapscheduler/3.4.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml
operators/snapscheduler/3.4.0/manifests/snapscheduler-manager-config_v1_configmap.yaml
operators/snapscheduler/3.4.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/snapscheduler/3.4.0/manifests/snapscheduler.backube_snapshotschedules.yaml
operators/snapscheduler/3.4.0/manifests/snapscheduler.clusterserviceversion.yaml
operators/snapscheduler/3.4.0/metadata/annotations.yaml
operators/snapscheduler/3.4.0/tests/scorecard/config.yaml

operator snapscheduler (3.4.0)

---

operators/gitlab-operator-kubernetes/0.31.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.31.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.31.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.31.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.31.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.31.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.31.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.31.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.31.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.31.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.31.2)

---

operators/external-secrets-operator/0.9.18/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.18/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.18/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.18/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.18/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.18/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.18/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.9.18/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.18/metadata/annotations.yaml
operators/external-secrets-operator/0.9.18/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.18

operator external-secrets-operator (0.9.18)

---

operators/verticadb-operator/ci.yaml

operator [CI] verticadb-operator

---

operators/flux/2.3.0/manifests/alert.crd.yaml
operators/flux/2.3.0/manifests/bucket.crd.yaml
operators/flux/2.3.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
operators/flux/2.3.0/manifests/crd-controller-flux-system.clusterrole.yaml
operators/flux/2.3.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
operators/flux/2.3.0/manifests/flux-edit-flux-system.clusterrole.yaml
operators/flux/2.3.0/manifests/flux-view-flux-system.clusterrole.yaml
operators/flux/2.3.0/manifests/flux.v2.3.0.clusterserviceversion.yaml
operators/flux/2.3.0/manifests/gitrepository.crd.yaml
operators/flux/2.3.0/manifests/helmchart.crd.yaml
operators/flux/2.3.0/manifests/helmrelease.crd.yaml
operators/flux/2.3.0/manifests/helmrepository.crd.yaml
operators/flux/2.3.0/manifests/imagepolicy.crd.yaml
operators/flux/2.3.0/manifests/imagerepository.crd.yaml
operators/flux/2.3.0/manifests/imageupdateautomation.crd.yaml
operators/flux/2.3.0/manifests/kustomization.crd.yaml
operators/flux/2.3.0/manifests/notification-controller.service.yaml
operators/flux/2.3.0/manifests/ocirepository.crd.yaml
operators/flux/2.3.0/manifests/provider.crd.yaml
operators/flux/2.3.0/manifests/receiver.crd.yaml
operators/flux/2.3.0/manifests/source-controller.service.yaml
operators/flux/2.3.0/manifests/webhook-receiver.service.yaml
operators/flux/2.3.0/metadata/annotations.yaml

operator flux (2.3.0)

---

operators/rabbitmq-messaging-topology-operator/1.14.1/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_bindings.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_exchanges.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_federations.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_operatorpolicies.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_permissions.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_policies.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_queues.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_schemareplications.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_shovels.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_superstreams.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_topicpermissions.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_users.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_vhosts.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.webhook-service.yaml
operators/rabbitmq-messaging-topology-operator/1.14.1/metadata/annotations.yaml

operator rabbitmq-messaging-topology-operator (1.14.1)

---

operators/project-quay/3.12.0-nightly.20240516/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.0-nightly.20240516/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.0-nightly.20240516/metadata/annotations.yaml

Add 3.12.0-nightly.20240516 to community operators

operator project-quay (3.12.0-nightly.20240516)

---

operators/rabbitmq-cluster-operator/2.9.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.9.0/manifests/crds.yaml
operators/rabbitmq-cluster-operator/2.9.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.9.0/metadata/annotations.yaml

* [] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [] Have you tested your Operator with all Custom Resource Definitions?
* [] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [] Have you considered whether you want use [semantic versioning …

operator rabbitmq-cluster-operator (2.9.0)

---

operators/edp-keycloak-operator/1.21.0/manifests/client-secret-policy-sample_v1_secret.yaml
operators/edp-keycloak-operator/1.21.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.21.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.21.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.21.0/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.21.0)

---

operators/knative-operator/1.14.1/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.14.1/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.14.1/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.14.1/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.14.1/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.14.1/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.14.1/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.14.1/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.14.1/manifests/knative-operator.v1.14.1.clusterserviceversion.yaml
operators/knative-operator/1.14.1/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.14.1/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.14.1/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.14.1/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.14.1/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.14.1/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.14.1/metadata/annotations.yaml
operators/knative-operator/1.14.1/tests/scorecard/config.yaml

operator knative-operator (1.14.1)

---

operators/gitlab-operator-kubernetes/1.0.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.0.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.0.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.0.0)

---

operators/tempo-operator/0.10.0/bundle.Dockerfile
operators/tempo-operator/0.10.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.10.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.10.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.10.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.10.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.10.0/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.10.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.10.0/metadata/annotations.yaml
operators/tempo-operator/0.10.0/tests/scorecard/config.yaml

Release tempo-operator `0.10.0`.

operator tempo-operator (0.10.0)

---

operators/trivy-operator/0.21.0/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/manifests/trivy-operator.v0.21.0.clusterserviceversion.yaml
operators/trivy-operator/0.21.0/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.0/metadata/annotations.yaml

operator trivy-operator (0.21.0)

---

operators/trivy-operator/0.21.1/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/manifests/trivy-operator.v0.21.1.clusterserviceversion.yaml
operators/trivy-operator/0.21.1/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.1/metadata/annotations.yaml

operator trivy-operator (0.21.1)

---

operators/argocd-operator/0.10.0/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
operators/argocd-operator/0.10.0/manifests/argocd-operator-manager-config_v1_configmap.yaml
operators/argocd-operator/0.10.0/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/argocd-operator/0.10.0/manifests/argocd-operator-webhook-service_v1_service.yaml
operators/argocd-operator/0.10.0/manifests/argocd-operator.v0.10.0.clusterserviceversion.yaml
operators/argocd-operator/0.10.0/manifests/argoproj.io_applications.yaml
operators/argocd-operator/0.10.0/manifests/argoproj.io_applicationsets.yaml
operators/argocd-operator/0.10.0/manifests/argoproj.io_appprojects.yaml
operators/argocd-operator/0.10.0/manifests/argoproj.io_argocdexports.yaml
operators/argocd-operator/0.10.0/manifests/argoproj.io_argocds.yaml
operators/argocd-operator/0.10.0/manifests/argoproj.io_notificationsconfigurations.yaml
operators/argocd-operator/0.10.0/metadata/annotations.yaml

operator argocd-operator (0.10.0)

---

operators/awx-operator/2.17.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.17.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.17.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.17.0/manifests/awx-operator.v2.17.0.clusterserviceversion.yaml
operators/awx-operator/2.17.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.17.0/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.17.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.17.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.17.0/metadata/annotations.yaml
operators/awx-operator/2.17.0/tests/scorecard/config.yaml

operator awx-operator (2.17.0)

operator awx-operator (2.17.0)

---

operators/gitlab-operator-kubernetes/1.0.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.0.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.0.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.0.1)

---

operators/instana-agent-operator/ci.yaml

operator [CI] instana-agent-operator

---

operators/layer7-operator/1.0.6/manifests/layer7-operator-controller-manager-metrics-service_v1_service.yaml
operators/layer7-operator/1.0.6/manifests/layer7-operator-manager-config_v1_configmap.yaml
operators/layer7-operator/1.0.6/manifests/layer7-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/layer7-operator/1.0.6/manifests/layer7-operator-webhook-service_v1_service.yaml
operators/layer7-operator/1.0.6/manifests/layer7-operator.clusterserviceversion.yaml
operators/layer7-operator/1.0.6/manifests/security.brcmlabs.com_gateways.yaml
operators/layer7-operator/1.0.6/manifests/security.brcmlabs.com_l7apis.yaml
operators/layer7-operator/1.0.6/manifests/security.brcmlabs.com_l7portals.yaml
operators/layer7-operator/1.0.6/manifests/security.brcmlabs.com_repositories.yaml
operators/layer7-operator/1.0.6/metadata/annotations.yaml
operators/layer7-operator/1.0.6/tests/scorecard/config.yaml

operator layer7-operator (1.0.6)

---

operators/ovms-operator/1.2.0/Dockerfile
operators/ovms-operator/1.2.0/manifests/intel.com_model_servers.yaml
operators/ovms-operator/1.2.0/manifests/openvino-operator-controller-manager-metrics-service_v1_service.yaml
operators/ovms-operator/1.2.0/manifests/openvino-operator-manager-config_v1_configmap.yaml
operators/ovms-operator/1.2.0/manifests/openvino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ovms-operator/1.2.0/manifests/openvino-operator.clusterserviceversion.yaml
operators/ovms-operator/1.2.0/metadata/annotations.yaml
operators/ovms-operator/1.2.0/tests/scorecard/config.yaml

Signed-off-by: dtrawins [Dariusz.Trawinski@intel.com](mailto:Dariusz.Trawinski@intel.com)
--

operator ovms-operator (1.2.0)

---

operators/netobserv-operator/1.6.0-community/manifests/flows.netobserv.io_flowcollectors.yaml
operators/netobserv-operator/1.6.0-community/manifests/flows.netobserv.io_flowmetrics.yaml
operators/netobserv-operator/1.6.0-community/manifests/netobserv-manager-config_v1_configmap.yaml
operators/netobserv-operator/1.6.0-community/manifests/netobserv-metrics-service_v1_service.yaml
operators/netobserv-operator/1.6.0-community/manifests/netobserv-operator.clusterserviceversion.yaml
operators/netobserv-operator/1.6.0-community/manifests/netobserv-webhook-service_v1_service.yaml
operators/netobserv-operator/1.6.0-community/metadata/annotations.yaml

operator netobserv-operator (1.6.0-community)

---

operators/project-quay/3.11.1/manifests/quay-operator.clusterserviceversion.yaml

Add 3.11.1 to community operators

operator [O] project-quay (3.11.1)

---

operators/hawtio-operator/1.1.0/manifests/hawt.io_hawtios.yaml
operators/hawtio-operator/1.1.0/manifests/hawtio-operator.v1.1.0.clusterserviceversion.yaml
operators/hawtio-operator/1.1.0/metadata/annotations.yaml
operators/hawtio-operator/1.1.0/tests/scorecard/config.yaml

operator hawtio-operator (1.1.0)

---

operators/susql-operator/0.0.16/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.16/manifests/susql-operator-susql-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
operators/susql-operator/0.0.16/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.16/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.16/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.16/metadata/annotations.yaml
operators/susql-operator/0.0.16/metadata/dependencies.yaml
operators/susql-operator/0.0.16/tests/scorecard/config.yaml

operator susql-operator (0.0.16)

---

operators/grafana-operator/5.9.2/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.9.2/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.9.2/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.9.2/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.9.2/metadata/annotations.yaml

operator grafana-operator (5.9.2)

---

operators/project-quay/3.11.1/manifests/quay-operator.clusterserviceversion.yaml

Add 3.11.1 to community operators

operator project-quay (3.11.1)

---

operators/camel-k/2.3.2/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.3.2/manifests/camel-k.v2.3.2.clusterserviceversion.yaml
operators/camel-k/2.3.2/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.3.2/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.3.2/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.3.2/manifests/integrationprofiles.camel.apache.org.crd.yaml
operators/camel-k/2.3.2/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.3.2/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/2.3.2/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.3.2/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.3.2/metadata/annotations.yaml
operators/camel-k/2.3.2/tests/scorecard/config.yaml

operator camel-k (2.3.2)

---

operators/trivy-operator/0.21.2/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/manifests/trivy-operator.v0.21.2.clusterserviceversion.yaml
operators/trivy-operator/0.21.2/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.2/metadata/annotations.yaml

operator trivy-operator (0.21.2)

---

operators/security-profiles-operator/0.8.4/manifests/metrics-token_v1_secret.yaml
operators/security-profiles-operator/0.8.4/manifests/security-profiles-operator-profile_v1_configmap.yaml
operators/security-profiles-operator/0.8.4/manifests/security-profiles-operator.clusterserviceversion.yaml
operators/security-profiles-operator/0.8.4/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
operators/security-profiles-operator/0.8.4/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
operators/security-profiles-operator/0.8.4/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
operators/security-profiles-operator/0.8.4/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
operators/security-profiles-operator/0.8.4/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
operators/security-profiles-operator/0.8.4/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
operators/security-profiles-operator/0.8.4/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
operators/security-profiles-operator/0.8.4/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
operators/security-profiles-operator/0.8.4/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.4/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.4/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.4/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.4/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.8.4/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.8.4/manifests/spo-webhook_v1_serviceaccount.yaml
operators/security-profiles-operator/0.8.4/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.8.4/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.8.4/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.8.4/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.8.4/manifests/spod_v1_serviceaccount.yaml
operators/security-profiles-operator/0.8.4/metadata/annotations.yaml
operators/security-profiles-operator/0.8.4/tests/scorecard/config.yaml

Refers to https://github.com/kubernetes-sigs/security-profiles-operator/issues/2194

operator security-profiles-operator (0.8.4)

---

operators/external-secrets-operator/0.9.19/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.19/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.19/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.19/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.19/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.19/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.19/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.9.19/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.19/metadata/annotations.yaml
operators/external-secrets-operator/0.9.19/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.19

operator external-secrets-operator (0.9.19)

---

operators/awx-operator/2.18.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.18.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.18.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.18.0/manifests/awx-operator.v2.18.0.clusterserviceversion.yaml
operators/awx-operator/2.18.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.18.0/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.18.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.18.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.18.0/metadata/annotations.yaml
operators/awx-operator/2.18.0/tests/scorecard/config.yaml

operator awx-operator (2.18.0)

operator awx-operator (2.18.0)

---

operators/project-quay/3.12.0-nightly.20240605/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.0-nightly.20240605/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.0-nightly.20240605/metadata/annotations.yaml

Add 3.12.0-nightly.20240605 to community operators

operator project-quay (3.12.0-nightly.20240605)

---

operators/elastic-cloud-eck/2.13.0/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.13.0/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.13.0/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.13.0/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.13.0/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.13.0/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.13.0/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.13.0/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.13.0/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.13.0/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.13.0/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.13.0/metadata/annotations.yaml

Update the ECK operator to the latest version `2.13.0`.

operator elastic-cloud-eck (2.13.0)

---

operators/trivy-operator/0.21.3/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/manifests/trivy-operator.v0.21.3.clusterserviceversion.yaml
operators/trivy-operator/0.21.3/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.21.3/metadata/annotations.yaml

operator trivy-operator (0.21.3)

---

operators/rabbitmq-messaging-topology-operator/1.14.2/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_bindings.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_exchanges.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_federations.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_operatorpolicies.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_permissions.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_policies.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_queues.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_schemareplications.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_shovels.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_superstreams.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_topicpermissions.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_users.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_vhosts.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.webhook-service.yaml
operators/rabbitmq-messaging-topology-operator/1.14.2/metadata/annotations.yaml

operator rabbitmq-messaging-topology-operator (1.14.2)

---

operators/trustee-operator/0.1.0/manifests/confidentialcontainers.org_kbsconfigs.yaml
operators/trustee-operator/0.1.0/manifests/kbs-config-sample_v1_configmap.yaml
operators/trustee-operator/0.1.0/manifests/rvps-reference-values-sample_v1_configmap.yaml
operators/trustee-operator/0.1.0/manifests/trustee-operator-controller-manager-metrics-service_v1_service.yaml
operators/trustee-operator/0.1.0/manifests/trustee-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/trustee-operator/0.1.0/manifests/trustee-operator.clusterserviceversion.yaml
operators/trustee-operator/0.1.0/metadata/annotations.yaml
operators/trustee-operator/0.1.0/tests/scorecard/config.yaml
operators/trustee-operator/ci.yaml

Introduced the operator trustee-operator

operator [N] [CI] trustee-operator (0.1.0)

---

operators/yaks/0.19.2/manifests/instances.yaks.citrusframework.org.crd.yaml
operators/yaks/0.19.2/manifests/tests.yaks.citrusframework.org.crd.yaml
operators/yaks/0.19.2/manifests/yaks.v0.19.2.clusterserviceversion.yaml
operators/yaks/0.19.2/metadata/annotations.yaml
operators/yaks/0.19.2/tests/scorecard/config.yaml

operator yaks (0.19.2)

---

operators/camel-k/2.3.3/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.3.3/manifests/camel-k.v2.3.3.clusterserviceversion.yaml
operators/camel-k/2.3.3/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.3.3/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.3.3/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.3.3/manifests/integrationprofiles.camel.apache.org.crd.yaml
operators/camel-k/2.3.3/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.3.3/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/2.3.3/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.3.3/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.3.3/metadata/annotations.yaml
operators/camel-k/2.3.3/tests/scorecard/config.yaml

operator camel-k (2.3.3)

---

operators/keda/2.13.1/manifests/eventing.keda.sh_cloudeventsources.yaml
operators/keda/2.13.1/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.13.1/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.13.1/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.13.1/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.13.1/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.13.1/manifests/keda.v2.13.1.clusterserviceversion.yaml
operators/keda/2.13.1/metadata/annotations.yaml

operator keda (2.13.1)

---

operators/hyperfoil-bundle/0.26.0/manifests/hyperfoil-operator-controller-manager-metrics-service_v1_service.yaml
operators/hyperfoil-bundle/0.26.0/manifests/hyperfoil-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/hyperfoil-bundle/0.26.0/manifests/hyperfoil-operator.clusterserviceversion.yaml
operators/hyperfoil-bundle/0.26.0/manifests/hyperfoil.io_hyperfoils.yaml
operators/hyperfoil-bundle/0.26.0/metadata/annotations.yaml
operators/hyperfoil-bundle/0.26.0/tests/scorecard/config.yaml

operator hyperfoil-bundle (0.26.0)

---

operators/argocd-operator/0.10.1/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
operators/argocd-operator/0.10.1/manifests/argocd-operator-manager-config_v1_configmap.yaml
operators/argocd-operator/0.10.1/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/argocd-operator/0.10.1/manifests/argocd-operator-webhook-service_v1_service.yaml
operators/argocd-operator/0.10.1/manifests/argocd-operator.v0.10.1.clusterserviceversion.yaml
operators/argocd-operator/0.10.1/manifests/argoproj.io_applications.yaml
operators/argocd-operator/0.10.1/manifests/argoproj.io_applicationsets.yaml
operators/argocd-operator/0.10.1/manifests/argoproj.io_appprojects.yaml
operators/argocd-operator/0.10.1/manifests/argoproj.io_argocdexports.yaml
operators/argocd-operator/0.10.1/manifests/argoproj.io_argocds.yaml
operators/argocd-operator/0.10.1/manifests/argoproj.io_notificationsconfigurations.yaml
operators/argocd-operator/0.10.1/metadata/annotations.yaml

operator argocd-operator (0.10.1)

---

operators/skupper-operator/1.7.1/manifests/skupper-operator.v1.7.1.clusterserviceversion.yaml
operators/skupper-operator/1.7.1/metadata/annotations.yaml

operator skupper-operator (1.7.1)

---

operators/gitlab-operator-kubernetes/1.0.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.0.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.0.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.0.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.0.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.0.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.0.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.0.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.0.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.0.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.0.2)

---

operators/cluster-manager/0.13.2/manifests/cluster-manager.clusterserviceversion.yaml
operators/cluster-manager/0.13.2/manifests/operator.open-cluster-management.io_clustermanagers.yaml
operators/cluster-manager/0.13.2/metadata/annotations.yaml

operator cluster-manager (0.13.2)

---

operators/klusterlet/0.13.2/manifests/klusterlet.clusterserviceversion.yaml
operators/klusterlet/0.13.2/manifests/operator.open-cluster-management.io_klusterlets.yaml
operators/klusterlet/0.13.2/metadata/annotations.yaml

operator klusterlet (0.13.2)

---

operators/project-quay/3.10.6/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.6/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.6/metadata/annotations.yaml

Add 3.10.6 to community operators

operator project-quay (3.10.6)

---

operators/susql-operator/0.0.19/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.19/manifests/susql-operator-susql-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
operators/susql-operator/0.0.19/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.19/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.19/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.19/metadata/annotations.yaml
operators/susql-operator/0.0.19/metadata/dependencies.yaml
operators/susql-operator/0.0.19/tests/scorecard/config.yaml

operator susql-operator (0.0.19)

---

operators/project-quay/3.12.0-nightly.20240615/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.0-nightly.20240615/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.0-nightly.20240615/metadata/annotations.yaml

Add 3.12.0-nightly.20240615 to community operators

operator project-quay (3.12.0-nightly.20240615)

---

operators/dynatrace-operator/1.1.1/Dockerfile
operators/dynatrace-operator/1.1.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.1.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.1.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.1.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.1.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.1.1/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.1.1/metadata/annotations.yaml

operator dynatrace-operator (1.1.1)

---

operators/argocd-operator/0.10.0/manifests/argocd-operator.v0.10.0.clusterserviceversion.yaml
operators/argocd-operator/0.9.2/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
operators/argocd-operator/0.9.2/manifests/argocd-operator-manager-config_v1_configmap.yaml
operators/argocd-operator/0.9.2/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/argocd-operator/0.9.2/manifests/argocd-operator-webhook-service_v1_service.yaml
operators/argocd-operator/0.9.2/manifests/argocd-operator.v0.9.2.clusterserviceversion.yaml
operators/argocd-operator/0.9.2/manifests/argoproj.io_applications.yaml
operators/argocd-operator/0.9.2/manifests/argoproj.io_applicationsets.yaml
operators/argocd-operator/0.9.2/manifests/argoproj.io_appprojects.yaml
operators/argocd-operator/0.9.2/manifests/argoproj.io_argocdexports.yaml
operators/argocd-operator/0.9.2/manifests/argoproj.io_argocds.yaml
operators/argocd-operator/0.9.2/metadata/annotations.yaml

operator [R] argocd-operator (0.10.0 0.9.2)

---

operators/klusterlet/0.13.3/manifests/klusterlet.clusterserviceversion.yaml
operators/klusterlet/0.13.3/manifests/operator.open-cluster-management.io_klusterlets.yaml
operators/klusterlet/0.13.3/metadata/annotations.yaml

operator klusterlet (0.13.3)

---

operators/cluster-manager/0.13.3/manifests/cluster-manager.clusterserviceversion.yaml
operators/cluster-manager/0.13.3/manifests/operator.open-cluster-management.io_clustermanagers.yaml
operators/cluster-manager/0.13.3/metadata/annotations.yaml

operator cluster-manager (0.13.3)

---

operators/keda/2.14.0/manifests/eventing.keda.sh_cloudeventsources.yaml
operators/keda/2.14.0/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.14.0/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.14.0/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.14.0/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.14.0/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.14.0/manifests/keda.v2.14.0.clusterserviceversion.yaml
operators/keda/2.14.0/metadata/annotations.yaml

operator keda (2.14.0)

---

operators/mongodb-enterprise/1.26.0/bundle.Dockerfile
operators/mongodb-enterprise/1.26.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.26.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.26.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.26.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.26.0/manifests/mongodb-enterprise-operator-service_v1_service.yaml
operators/mongodb-enterprise/1.26.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.26.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.26.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.26.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.26.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.26.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.26.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.26.0/tests/scorecard/config.yaml

operator mongodb-enterprise (1.26.0)

---

operators/deployment-validation-operator/0.7.7/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.7.7/manifests/deploymentvalidationoperator.0.7.7.clusterserviceversion.yaml
operators/deployment-validation-operator/0.7.7/metadata/annotations.yaml
operators/deployment-validation-operator/0.7.7/tests/scorecard/config.yaml

operator deployment-validation-operator (0.7.7)

---

operators/awx-operator/2.19.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.19.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.19.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.19.0/manifests/awx-operator.v2.19.0.clusterserviceversion.yaml
operators/awx-operator/2.19.0/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.19.0/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.19.0/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.19.0/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.19.0/metadata/annotations.yaml
operators/awx-operator/2.19.0/tests/scorecard/config.yaml

operator awx-operator (2.19.0)

operator awx-operator (2.19.0)

---

operators/klusterlet/0.14.0/manifests/klusterlet.clusterserviceversion.yaml
operators/klusterlet/0.14.0/manifests/operator.open-cluster-management.io_klusterlets.yaml
operators/klusterlet/0.14.0/metadata/annotations.yaml

operator klusterlet (0.14.0)

---

operators/cluster-manager/0.14.0/manifests/cluster-manager.clusterserviceversion.yaml
operators/cluster-manager/0.14.0/manifests/operator.open-cluster-management.io_clustermanagers.yaml
operators/cluster-manager/0.14.0/metadata/annotations.yaml

operator cluster-manager (0.14.0)

---

operators/instana-agent-operator/2.1.1/manifests/controller-manager-metrics-service_v1_service.yaml
operators/instana-agent-operator/2.1.1/manifests/instana-agent-operator.clusterserviceversion.yaml
operators/instana-agent-operator/2.1.1/manifests/instana.io_agents.yaml
operators/instana-agent-operator/2.1.1/manifests/manager-config_v1_configmap.yaml
operators/instana-agent-operator/2.1.1/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
operators/instana-agent-operator/2.1.1/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/instana-agent-operator/2.1.1/metadata/annotations.yaml
operators/instana-agent-operator/2.1.1/tests/scorecard/config.yaml

operator instana-agent-operator (2.1.1)

---

operators/dynatrace-operator/1.2.0/Dockerfile
operators/dynatrace-operator/1.2.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.2.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.2.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.2.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.2.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.2.0/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.2.0/metadata/annotations.yaml

operator dynatrace-operator (1.2.0)

---

operators/clickhouse/0.23.6/manifests/clickhouse-operator.v0.23.6.clusterserviceversion.yaml
operators/clickhouse/0.23.6/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.6/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.6/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.23.6/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.6/metadata/annotations.yaml

operator clickhouse (0.23.6)

---

operators/susql-operator/0.0.20/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.20/manifests/susql-operator-susql-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
operators/susql-operator/0.0.20/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.20/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.20/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.20/metadata/annotations.yaml
operators/susql-operator/0.0.20/metadata/dependencies.yaml
operators/susql-operator/0.0.20/tests/scorecard/config.yaml

operator susql-operator (0.0.20)

---

operators/gitlab-operator-kubernetes/1.1.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.1.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.1.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.1.1)

---

operators/instana-agent-operator/2.1.2/manifests/controller-manager-metrics-service_v1_service.yaml
operators/instana-agent-operator/2.1.2/manifests/instana-agent-operator.clusterserviceversion.yaml
operators/instana-agent-operator/2.1.2/manifests/instana.io_agents.yaml
operators/instana-agent-operator/2.1.2/manifests/manager-config_v1_configmap.yaml
operators/instana-agent-operator/2.1.2/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
operators/instana-agent-operator/2.1.2/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/instana-agent-operator/2.1.2/metadata/annotations.yaml
operators/instana-agent-operator/2.1.2/tests/scorecard/config.yaml

Instana Operator v2.1.2 release

operator instana-agent-operator (2.1.2)

---

operators/susql-operator/0.0.21/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.21/manifests/susql-operator-susql-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
operators/susql-operator/0.0.21/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.21/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.21/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.21/metadata/annotations.yaml
operators/susql-operator/0.0.21/metadata/dependencies.yaml
operators/susql-operator/0.0.21/tests/scorecard/config.yaml

operator susql-operator (0.0.21)

---

operators/awx-operator/2.19.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
operators/awx-operator/2.19.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
operators/awx-operator/2.19.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/awx-operator/2.19.1/manifests/awx-operator.v2.19.1.clusterserviceversion.yaml
operators/awx-operator/2.19.1/manifests/awx.ansible.com_awxbackups.yaml
operators/awx-operator/2.19.1/manifests/awx.ansible.com_awxmeshingresses.yaml
operators/awx-operator/2.19.1/manifests/awx.ansible.com_awxrestores.yaml
operators/awx-operator/2.19.1/manifests/awx.ansible.com_awxs.yaml
operators/awx-operator/2.19.1/metadata/annotations.yaml
operators/awx-operator/2.19.1/tests/scorecard/config.yaml

operator awx-operator (2.19.1)

operator awx-operator (2.19.1)

---

operators/pubsubplus-eventbroker-operator/1.1.0/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
operators/pubsubplus-eventbroker-operator/1.1.0/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
operators/pubsubplus-eventbroker-operator/1.1.0/metadata/annotations.yaml
operators/pubsubplus-eventbroker-operator/1.1.0/tests/scorecard/config.yaml

operator pubsubplus-eventbroker-operator (1.1.0)

---

operators/nri-plugins-operator/0.7.0/manifests/config.nri_balloonspolicies.yaml
operators/nri-plugins-operator/0.7.0/manifests/config.nri_nriplugindeployments.yaml
operators/nri-plugins-operator/0.7.0/manifests/config.nri_templatepolicies.yaml
operators/nri-plugins-operator/0.7.0/manifests/config.nri_topologyawarepolicies.yaml
operators/nri-plugins-operator/0.7.0/manifests/nri-plugins-operator-controller-manager-metrics-service_v1_service.yaml
operators/nri-plugins-operator/0.7.0/manifests/nri-plugins-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nri-plugins-operator/0.7.0/manifests/nri-plugins-operator.clusterserviceversion.yaml
operators/nri-plugins-operator/0.7.0/manifests/topology.node.k8s.io_noderesourcetopologies.yaml
operators/nri-plugins-operator/0.7.0/metadata/annotations.yaml
operators/nri-plugins-operator/0.7.0/tests/scorecard/config.yaml

Submit nri-plugins-operator ([0.7.0](https://github.com/containers/nri-plugins/releases/tag/v0.7.0)) version.

operator nri-plugins-operator (0.7.0)

---

operators/trustify-operator/ci.yaml

operator [CI] trustify-operator

---

operators/netobserv-operator/1.6.1-community/manifests/flows.netobserv.io_flowcollectors.yaml
operators/netobserv-operator/1.6.1-community/manifests/flows.netobserv.io_flowmetrics.yaml
operators/netobserv-operator/1.6.1-community/manifests/netobserv-manager-config_v1_configmap.yaml
operators/netobserv-operator/1.6.1-community/manifests/netobserv-metrics-service_v1_service.yaml
operators/netobserv-operator/1.6.1-community/manifests/netobserv-operator.clusterserviceversion.yaml
operators/netobserv-operator/1.6.1-community/manifests/netobserv-webhook-service_v1_service.yaml
operators/netobserv-operator/1.6.1-community/metadata/annotations.yaml

operator netobserv-operator (1.6.1-community)

---

operators/trivy-operator/0.22.0/manifests/clustercompliancereports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/clusterconfigauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/clusterinfraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/clusterrbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/clustersbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/clustervulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/configauditreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/exposedsecretreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/infraassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/rbacassessmentreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/sbomreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/manifests/trivy-operator.v0.22.0.clusterserviceversion.yaml
operators/trivy-operator/0.22.0/manifests/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
operators/trivy-operator/0.22.0/metadata/annotations.yaml

operator trivy-operator (0.22.0)

---

operators/trustify-operator/0.1.0-alpha.2/manifests/trustify-operator.clusterserviceversion.yaml

operator [O] trustify-operator (0.1.0-alpha.2)

---

operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmagents.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmalertmanagers.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmalerts.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmauths.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmclusters.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmnodescrapes.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmpodscrapes.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmprobes.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmrules.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmscrapeconfigs.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmservicescrapes.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmsingles.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmstaticscrapes.yaml
operators/victoriametrics-operator/0.46.2/manifests/operator.victoriametrics.com_vmusers.yaml
operators/victoriametrics-operator/0.46.2/manifests/victoriametrics-operator.clusterserviceversion.yaml
operators/victoriametrics-operator/0.46.2/manifests/vm-webhook-service_v1_service.yaml
operators/victoriametrics-operator/0.46.2/metadata/annotations.yaml
operators/victoriametrics-operator/ci.yaml

operator [R] [CI] victoriametrics-operator (0.46.2)

---

operators/trustify-operator/0.1.0-alpha.2/manifests/trustify-operator.clusterserviceversion.yaml
operators/trustify-operator/ci.yaml

operator [O] [CI] trustify-operator (0.1.0-alpha.2)

---

operators/cryostat-operator/3.0.0/Dockerfile
operators/cryostat-operator/3.0.0/manifests/cryostat-operator-cryostat-namespaced_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/3.0.0/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/3.0.0/manifests/cryostat-operator-manager-config_v1_configmap.yaml
operators/cryostat-operator/3.0.0/manifests/cryostat-operator-oauth-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/3.0.0/manifests/cryostat-operator-webhook-service_v1_service.yaml
operators/cryostat-operator/3.0.0/manifests/cryostat-operator.clusterserviceversion.yaml
operators/cryostat-operator/3.0.0/manifests/operator.cryostat.io_cryostats.yaml
operators/cryostat-operator/3.0.0/metadata/annotations.yaml
operators/cryostat-operator/3.0.0/tests/scorecard/config.yaml

Signed-off-by: Ming Wang [miwan@redhat.com](mailto:miwan@redhat.com)
--

operator cryostat-operator (3.0.0)

---

operators/external-secrets-operator/0.9.20/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.9.20/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.9.20/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.9.20/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.9.20/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.9.20/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.9.20/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.9.20/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.9.20/metadata/annotations.yaml
operators/external-secrets-operator/0.9.20/tests/scorecard/config.yaml

bump external-secrets-operator 0.9.20

operator external-secrets-operator (0.9.20)

---

operators/susql-operator/0.0.22/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.22/manifests/susql-operator-susql-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
operators/susql-operator/0.0.22/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.22/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.22/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.22/metadata/annotations.yaml
operators/susql-operator/0.0.22/metadata/dependencies.yaml
operators/susql-operator/0.0.22/tests/scorecard/config.yaml

operator susql-operator (0.0.22)

---

operators/trident-operator/24.6.0/manifests/trident-operator.v24.6.0.clusterserviceversion.yaml
operators/trident-operator/24.6.0/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
operators/trident-operator/24.6.0/metadata/annotations.yaml

operator trident-operator (24.6.0)

---

operators/gitlab-operator-kubernetes/1.1.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.1.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.1.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.1.2)

---

operators/cass-operator-community/1.21.1/manifests/cass-operator-manager-config_v1_configmap.yaml
operators/cass-operator-community/1.21.1/manifests/cass-operator-webhook-service_v1_service.yaml
operators/cass-operator-community/1.21.1/manifests/cass-operator.clusterserviceversion.yaml
operators/cass-operator-community/1.21.1/manifests/cassandra.datastax.com_cassandradatacenters.yaml
operators/cass-operator-community/1.21.1/manifests/control.k8ssandra.io_cassandratasks.yaml
operators/cass-operator-community/1.21.1/metadata/annotations.yaml
operators/cass-operator-community/1.21.1/tests/scorecard/config.yaml

operator cass-operator-community (1.21.1)

---

operators/project-quay/3.12.0-nightly.20240716/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.0-nightly.20240716/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.0-nightly.20240716/metadata/annotations.yaml

Add 3.12.0-nightly.20240716 to community operators

operator project-quay (3.12.0-nightly.20240716)

---

operators/mongodb-atlas-kubernetes/2.4.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.4.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.4.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.4.0/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.4.0)

---

operators/skupper-operator/1.7.3/manifests/skupper-operator.v1.7.3.clusterserviceversion.yaml
operators/skupper-operator/1.7.3/metadata/annotations.yaml

operator skupper-operator (1.7.3)

---

operators/grafana-operator/5.10.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.10.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.10.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.10.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.10.0/metadata/annotations.yaml

operator grafana-operator (5.10.0)

---

operators/argocd-operator/0.11.0/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
operators/argocd-operator/0.11.0/manifests/argocd-operator-manager-config_v1_configmap.yaml
operators/argocd-operator/0.11.0/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/argocd-operator/0.11.0/manifests/argocd-operator-webhook-service_v1_service.yaml
operators/argocd-operator/0.11.0/manifests/argocd-operator.v0.11.0.clusterserviceversion.yaml
operators/argocd-operator/0.11.0/manifests/argoproj.io_applications.yaml
operators/argocd-operator/0.11.0/manifests/argoproj.io_applicationsets.yaml
operators/argocd-operator/0.11.0/manifests/argoproj.io_appprojects.yaml
operators/argocd-operator/0.11.0/manifests/argoproj.io_argocdexports.yaml
operators/argocd-operator/0.11.0/manifests/argoproj.io_argocds.yaml
operators/argocd-operator/0.11.0/manifests/argoproj.io_notificationsconfigurations.yaml
operators/argocd-operator/0.11.0/metadata/annotations.yaml

operator argocd-operator (0.11.0)

---

operators/gitlab-operator-kubernetes/1.2.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.2.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.2.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.2.0)

---

operators/dynatrace-operator/1.2.1/Dockerfile
operators/dynatrace-operator/1.2.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.2.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.2.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.2.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.2.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.2.1/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.2.1/metadata/annotations.yaml

operator dynatrace-operator (1.2.1)

---

operators/move2kube-operator/0.3.14-rc.0/bundle.Dockerfile
operators/move2kube-operator/0.3.14-rc.0/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.14-rc.0/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.14-rc.0/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.14-rc.0/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.14-rc.0/metadata/annotations.yaml
operators/move2kube-operator/0.3.14-rc.0/tests/scorecard/config.yaml

An automated PR to update move2kube-operator to v0.3.14-rc.0

operator move2kube-operator (0.3.14-rc.0)

---

operators/intel-device-plugins-operator/0.30.0/manifests/intel-device-plugins-operator.clusterserviceversion.yaml

operator [O] intel-device-plugins-operator (0.30.0)

---

operators/self-node-remediation/0.9.0/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml
operators/self-node-remediation/0.9.0/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.9.0/manifests/self-node-remediation-manager-config_v1_configmap.yaml
operators/self-node-remediation/0.9.0/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/self-node-remediation/0.9.0/manifests/self-node-remediation-webhook-service_v1_service.yaml
operators/self-node-remediation/0.9.0/manifests/self-node-remediation.clusterserviceversion.yaml
operators/self-node-remediation/0.9.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
operators/self-node-remediation/0.9.0/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
operators/self-node-remediation/0.9.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
operators/self-node-remediation/0.9.0/metadata/annotations.yaml
operators/self-node-remediation/0.9.0/tests/scorecard/config.yaml

operator self-node-remediation (0.9.0)

---

operators/gitlab-operator-kubernetes/1.2.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.2.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.2.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.2.1)

---

operators/tempo-operator/0.11.0/bundle.Dockerfile
operators/tempo-operator/0.11.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.11.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.11.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.11.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.11.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.11.0/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.11.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.11.0/metadata/annotations.yaml
operators/tempo-operator/0.11.0/tests/scorecard/config.yaml

Release tempo-operator `0.11.0`.

operator tempo-operator (0.11.0)

---

operators/tempo-operator/0.11.1/bundle.Dockerfile
operators/tempo-operator/0.11.1/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.11.1/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.11.1/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.11.1/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.11.1/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.11.1/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.11.1/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.11.1/metadata/annotations.yaml
operators/tempo-operator/0.11.1/tests/scorecard/config.yaml

Release tempo-operator `0.11.1`.

operator tempo-operator (0.11.1)

---

operators/edp-keycloak-operator/1.22.0/manifests/client-secret-policy-sample_v1_secret.yaml
operators/edp-keycloak-operator/1.22.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.22.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.22.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.22.0/tests/scorecard/config.yaml

* [ x Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
-- …

operator edp-keycloak-operator (1.22.0)

---

operators/knative-operator/1.15.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.15.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.15.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.15.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.15.0/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.15.0/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.15.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.15.0/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.15.0/manifests/knative-operator.v1.15.0.clusterserviceversion.yaml
operators/knative-operator/1.15.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.15.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.15.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.15.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.15.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.15.0/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.15.0/metadata/annotations.yaml
operators/knative-operator/1.15.0/tests/scorecard/config.yaml

operator knative-operator (1.15.0)

---

operators/project-quay/3.11.3/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.11.3/manifests/quayregistries.crd.yaml
operators/project-quay/3.11.3/metadata/annotations.yaml

Add 3.11.3 to community operators

operator [R] project-quay (3.11.3 3.12.0)

---

operators/mongodb-atlas-kubernetes/2.4.1/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.4.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.4.1/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.4.1/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.4.1)

---

operators/instana-agent-operator/2.1.5/manifests/controller-manager-metrics-service_v1_service.yaml
operators/instana-agent-operator/2.1.5/manifests/instana-agent-operator.clusterserviceversion.yaml
operators/instana-agent-operator/2.1.5/manifests/instana.io_agents.yaml
operators/instana-agent-operator/2.1.5/manifests/manager-config_v1_configmap.yaml
operators/instana-agent-operator/2.1.5/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
operators/instana-agent-operator/2.1.5/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/instana-agent-operator/2.1.5/metadata/annotations.yaml
operators/instana-agent-operator/2.1.5/tests/scorecard/config.yaml

Instana Operator v2.1.5 release

operator instana-agent-operator (2.1.5)

---

operators/hpe-csi-operator/2.5.0/Dockerfile
operators/hpe-csi-operator/2.5.0/manifests/hpe-csi-operator-controller-manager-metrics-service_v1_service.yaml
operators/hpe-csi-operator/2.5.0/manifests/hpe-csi-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/hpe-csi-operator/2.5.0/manifests/hpe-csi-operator.v2.5.0.clusterserviceversion.yaml
operators/hpe-csi-operator/2.5.0/manifests/storage.hpe.com_hpecsidrivers.yaml
operators/hpe-csi-operator/2.5.0/metadata/annotations.yaml
operators/hpe-csi-operator/2.5.0/tests/scorecard/config.yaml

operator hpe-csi-operator (2.5.0)

---

operators/hpe-csi-operator/2.5.1/Dockerfile
operators/hpe-csi-operator/2.5.1/manifests/hpe-csi-operator-controller-manager-metrics-service_v1_service.yaml
operators/hpe-csi-operator/2.5.1/manifests/hpe-csi-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/hpe-csi-operator/2.5.1/manifests/hpe-csi-operator.v2.5.1.clusterserviceversion.yaml
operators/hpe-csi-operator/2.5.1/manifests/storage.hpe.com_hpecsidrivers.yaml
operators/hpe-csi-operator/2.5.1/metadata/annotations.yaml
operators/hpe-csi-operator/2.5.1/tests/scorecard/config.yaml

operator hpe-csi-operator (2.5.1)

---

operators/pubsubplus-eventbroker-operator/1.1.1/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
operators/pubsubplus-eventbroker-operator/1.1.1/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
operators/pubsubplus-eventbroker-operator/1.1.1/metadata/annotations.yaml
operators/pubsubplus-eventbroker-operator/1.1.1/tests/scorecard/config.yaml

operator pubsubplus-eventbroker-operator (1.1.1)

---

operators/keda/2.14.1/manifests/eventing.keda.sh_cloudeventsources.yaml
operators/keda/2.14.1/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.14.1/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.14.1/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.14.1/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.14.1/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.14.1/manifests/keda.v2.14.1.clusterserviceversion.yaml
operators/keda/2.14.1/metadata/annotations.yaml

operator keda (2.14.1)

---

operators/external-secrets-operator/0.10.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.10.0/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.10.0/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.10.0/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.10.0/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.10.0/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.10.0/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.10.0/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.10.0/metadata/annotations.yaml
operators/external-secrets-operator/0.10.0/tests/scorecard/config.yaml

bump external-secrets-operator 0.10.0

operator external-secrets-operator (0.10.0)

---

operators/cc-operator/0.9.0/manifests/cc-operator-controller-manager-metrics-service_v1_service.yaml
operators/cc-operator/0.9.0/manifests/cc-operator-manager-config_v1_configmap.yaml
operators/cc-operator/0.9.0/manifests/cc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cc-operator/0.9.0/manifests/cc-operator.clusterserviceversion.yaml
operators/cc-operator/0.9.0/manifests/confidentialcontainers.org_ccruntimes.yaml
operators/cc-operator/0.9.0/metadata/annotations.yaml
operators/cc-operator/0.9.0/tests/scorecard/config.yaml

operator cc-operator (0.9.0)

---

operators/camel-k/2.4.0/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.4.0/manifests/camel-k.v2.4.0.clusterserviceversion.yaml
operators/camel-k/2.4.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.4.0/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.4.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.4.0/manifests/integrationprofiles.camel.apache.org.crd.yaml
operators/camel-k/2.4.0/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.4.0/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/2.4.0/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.4.0/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.4.0/metadata/annotations.yaml
operators/camel-k/2.4.0/tests/scorecard/config.yaml

operator camel-k (2.4.0)

---

operators/grafana-operator/5.12.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.12.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.12.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.12.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.12.0/metadata/annotations.yaml

operator grafana-operator (5.12.0)

---

operators/gitlab-operator-kubernetes/1.2.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.2.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.2.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.2.2)

---

operators/instana-agent-operator/2.1.6/manifests/controller-manager-metrics-service_v1_service.yaml
operators/instana-agent-operator/2.1.6/manifests/instana-agent-operator.clusterserviceversion.yaml
operators/instana-agent-operator/2.1.6/manifests/instana.io_agents.yaml
operators/instana-agent-operator/2.1.6/manifests/manager-config_v1_configmap.yaml
operators/instana-agent-operator/2.1.6/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml
operators/instana-agent-operator/2.1.6/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/instana-agent-operator/2.1.6/metadata/annotations.yaml
operators/instana-agent-operator/2.1.6/tests/scorecard/config.yaml

Instana Operator v2.1.6 release

operator instana-agent-operator (2.1.6)

---

operators/bpfman-operator/0.5.0/bundle.Dockerfile
operators/bpfman-operator/0.5.0/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-config_v1_configmap.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-daemon_v1_serviceaccount.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-operator.clusterserviceversion.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman.io_bpfapplications.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman.io_bpfprograms.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman.io_fentryprograms.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman.io_fexitprograms.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman.io_kprobeprograms.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman.io_tcprograms.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman.io_tracepointprograms.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman.io_uprobeprograms.yaml
operators/bpfman-operator/0.5.0/manifests/bpfman.io_xdpprograms.yaml
operators/bpfman-operator/0.5.0/metadata/annotations.yaml
operators/bpfman-operator/0.5.0/metadata/dependencies.yaml
operators/bpfman-operator/0.5.0/tests/scorecard/config.yaml
operators/bpfman-operator/ci.yaml

operator [CI] bpfman-operator (0.5.0)

---

operators/dynatrace-operator/1.2.2/Dockerfile
operators/dynatrace-operator/1.2.2/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.2.2/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.2.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.2.2/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.2.2/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.2.2/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.2.2/metadata/annotations.yaml

operator dynatrace-operator (1.2.2)

---

operators/layer7-operator/1.0.7/manifests/layer7-operator-controller-manager-metrics-service_v1_service.yaml
operators/layer7-operator/1.0.7/manifests/layer7-operator-manager-config_v1_configmap.yaml
operators/layer7-operator/1.0.7/manifests/layer7-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/layer7-operator/1.0.7/manifests/layer7-operator-webhook-service_v1_service.yaml
operators/layer7-operator/1.0.7/manifests/layer7-operator.clusterserviceversion.yaml
operators/layer7-operator/1.0.7/manifests/security.brcmlabs.com_gateways.yaml
operators/layer7-operator/1.0.7/manifests/security.brcmlabs.com_l7apis.yaml
operators/layer7-operator/1.0.7/manifests/security.brcmlabs.com_l7portals.yaml
operators/layer7-operator/1.0.7/manifests/security.brcmlabs.com_repositories.yaml
operators/layer7-operator/1.0.7/metadata/annotations.yaml
operators/layer7-operator/1.0.7/tests/scorecard/config.yaml
operators/layer7-operator/ci.yaml

operator [CI] layer7-operator (1.0.7)

---

operators/keda/2.15.0/manifests/eventing.keda.sh_cloudeventsources.yaml
operators/keda/2.15.0/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.15.0/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.15.0/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.15.0/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.15.0/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.15.0/manifests/keda.v2.15.0.clusterserviceversion.yaml
operators/keda/2.15.0/metadata/annotations.yaml

operator keda (2.15.0)

---

operators/ack-wafv2-controller/ci.yaml

--
- Relates: aws-controllers-k8s/community#2127

operator [CI] ack-wafv2-controller

---

operators/ack-ses-controller/ci.yaml

operator [CI] ack-ses-controller

---

operators/verticadb-operator/2.2.0/manifests/vertica.com_eventtriggers.yaml
operators/verticadb-operator/2.2.0/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/2.2.0/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/2.2.0/manifests/vertica.com_verticareplicators.yaml
operators/verticadb-operator/2.2.0/manifests/vertica.com_verticarestorepointsqueries.yaml
operators/verticadb-operator/2.2.0/manifests/vertica.com_verticascrutinizers.yaml
operators/verticadb-operator/2.2.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/2.2.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/2.2.0/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/verticadb-operator/2.2.0/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/2.2.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/2.2.0/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/2.2.0/metadata/annotations.yaml
operators/verticadb-operator/2.2.0/tests/scorecard/config.yaml

operator verticadb-operator (2.2.0)

---

operators/keda/2.15.1/manifests/eventing.keda.sh_cloudeventsources.yaml
operators/keda/2.15.1/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.15.1/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.15.1/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.15.1/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.15.1/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.15.1/manifests/keda.v2.15.1.clusterserviceversion.yaml
operators/keda/2.15.1/metadata/annotations.yaml

operator keda (2.15.1)

---

operators/clickhouse/0.23.7/manifests/clickhouse-operator.v0.23.7.clusterserviceversion.yaml
operators/clickhouse/0.23.7/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.7/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.7/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.23.7/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.23.7/metadata/annotations.yaml

operator clickhouse (0.23.7)

---

operators/ack-apigateway-controller/ci.yaml

operator [CI] ack-apigateway-controller

---

operators/ack-athena-controller/ci.yaml

operator [CI] ack-athena-controller

---

operators/ack-cognitoidentity-controller/ci.yaml

operator [CI] ack-cognitoidentity-controller

---

operators/ack-ebs-controller/ci.yaml

operator [CI] ack-ebs-controller

---

operators/ack-recyclebin-controller/ci.yaml

operator [CI] ack-recyclebin-controller

---

operators/gitlab-operator-kubernetes/1.3.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.3.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.3.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.3.0)

---

operators/dell-csm-operator/1.6.0/manifests/apexconnectivityclients.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.6.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.6.0/manifests/dell-csm-operator.v1.6.0.clusterserviceversion.yaml
operators/dell-csm-operator/1.6.0/metadata/annotations.yaml
operators/dell-csm-operator/1.6.0/tests/scorecard/config.yaml

operator dell-csm-operator (1.6.0)

---

operators/bpfman-operator/0.5.1/bundle.Dockerfile
operators/bpfman-operator/0.5.1/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-config_v1_configmap.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-daemon_v1_serviceaccount.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-operator.clusterserviceversion.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman.io_bpfapplications.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman.io_bpfprograms.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman.io_fentryprograms.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman.io_fexitprograms.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman.io_kprobeprograms.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman.io_tcprograms.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman.io_tracepointprograms.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman.io_uprobeprograms.yaml
operators/bpfman-operator/0.5.1/manifests/bpfman.io_xdpprograms.yaml
operators/bpfman-operator/0.5.1/metadata/annotations.yaml
operators/bpfman-operator/0.5.1/metadata/dependencies.yaml
operators/bpfman-operator/0.5.1/tests/scorecard/config.yaml

operator bpfman-operator (0.5.1)

---

operators/datadog-operator/1.8.0/manifests/datadog-operator-webhook-service_v1_service.yaml
operators/datadog-operator/1.8.0/manifests/datadog-operator.clusterserviceversion.yaml
operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogagentprofiles.yaml
operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogagents.yaml
operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogmetrics.yaml
operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogmonitors.yaml
operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogpodautoscalers.yaml
operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogslos.yaml
operators/datadog-operator/1.8.0/metadata/annotations.yaml
operators/datadog-operator/1.8.0/tests/scorecard/config.yaml

operator datadog-operator (1.8.0)

---

operators/gitlab-operator-kubernetes/1.3.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.3.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.3.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.3.1)

---

operators/project-quay/3.11.4/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.11.4/manifests/quayregistries.crd.yaml
operators/project-quay/3.11.4/metadata/annotations.yaml

Add 3.11.4 to community operators

operator project-quay (3.11.4)

---

operators/project-quay/3.12.1/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.1/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.1/metadata/annotations.yaml

Add 3.12.1 to community operators

operator project-quay (3.12.1)

---

operators/netobserv-operator/1.6.2-community/manifests/flows.netobserv.io_flowcollectors.yaml
operators/netobserv-operator/1.6.2-community/manifests/flows.netobserv.io_flowmetrics.yaml
operators/netobserv-operator/1.6.2-community/manifests/netobserv-manager-config_v1_configmap.yaml
operators/netobserv-operator/1.6.2-community/manifests/netobserv-metrics-service_v1_service.yaml
operators/netobserv-operator/1.6.2-community/manifests/netobserv-operator.clusterserviceversion.yaml
operators/netobserv-operator/1.6.2-community/manifests/netobserv-webhook-service_v1_service.yaml
operators/netobserv-operator/1.6.2-community/metadata/annotations.yaml
operators/netobserv-operator/ci.yaml

operator [CI] netobserv-operator (1.6.2-community)

---

operators/susql-operator/0.0.24/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.24/manifests/susql-operator-susql-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
operators/susql-operator/0.0.24/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.24/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.24/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.24/metadata/annotations.yaml
operators/susql-operator/0.0.24/metadata/dependencies.yaml
operators/susql-operator/0.0.24/tests/scorecard/config.yaml

operator susql-operator (0.0.24)

---

operators/mongodb-enterprise/1.27.0/bundle.Dockerfile
operators/mongodb-enterprise/1.27.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.27.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.27.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.27.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.27.0/manifests/mongodb-enterprise-operator-service_v1_service.yaml
operators/mongodb-enterprise/1.27.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.27.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.27.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.27.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.27.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.27.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.27.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.27.0/tests/scorecard/config.yaml

operator mongodb-enterprise (1.27.0)

---

operators/move2kube-operator/0.3.14/bundle.Dockerfile
operators/move2kube-operator/0.3.14/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.14/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.14/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.14/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.14/metadata/annotations.yaml
operators/move2kube-operator/0.3.14/tests/scorecard/config.yaml

An automated PR to update move2kube-operator to v0.3.14

operator move2kube-operator (0.3.14)

---

operators/knative-operator/1.15.4/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.15.4/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.15.4/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.15.4/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.15.4/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.15.4/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.15.4/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.15.4/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.15.4/manifests/knative-operator.v1.15.4.clusterserviceversion.yaml
operators/knative-operator/1.15.4/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.15.4/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.15.4/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.15.4/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.15.4/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.15.4/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.15.4/metadata/annotations.yaml
operators/knative-operator/1.15.4/tests/scorecard/config.yaml

operator knative-operator (1.15.4)

---

operators/external-secrets-operator/0.10.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.10.1/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.10.1/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.10.1/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.10.1/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.10.1/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.10.1/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.10.1/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.10.1/metadata/annotations.yaml
operators/external-secrets-operator/0.10.1/tests/scorecard/config.yaml

bump external-secrets-operator 0.10.1

operator external-secrets-operator (0.10.1)

---

operators/tempo-operator/0.13.0/bundle.Dockerfile
operators/tempo-operator/0.13.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.13.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.13.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.13.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.13.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.13.0/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.13.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.13.0/metadata/annotations.yaml
operators/tempo-operator/0.13.0/tests/scorecard/config.yaml

Release tempo-operator `0.13.0`.

operator tempo-operator (0.13.0)

---

operators/percona-xtradb-cluster-operator/1.15.0/manifests/percona-xtradb-cluster-operator.v1.15.0.clusterserviceversion.yaml
operators/percona-xtradb-cluster-operator/1.15.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.15.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.15.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.15.0/metadata/annotations.yaml

operator percona-xtradb-cluster-operator (1.15.0)

---

operators/wildfly/1.1.0/bundle.Dockerfile
operators/wildfly/1.1.0/manifests/wildfly-operator.v1.1.0.clusterserviceversion.yaml
operators/wildfly/1.1.0/manifests/wildflyservers.wildfly.org.crd.yaml
operators/wildfly/1.1.0/metadata/annotations.yaml

Upgrade WildFly Operator to 1.1.0
Signed-off-by: Yeray Borges [yborgess@redhat.com](mailto:yborgess@redhat.com)

operator wildfly (1.1.0)

---

operators/skupper-operator/1.8.0/manifests/skupper-operator.v1.8.0.clusterserviceversion.yaml
operators/skupper-operator/1.8.0/metadata/annotations.yaml

operator skupper-operator (1.8.0)

---

operators/registry-operator/ci.yaml

operator [CI] registry-operator

---

operators/external-secrets-operator/0.10.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.10.2/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.10.2/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.10.2/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.10.2/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.10.2/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.10.2/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.10.2/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.10.2/metadata/annotations.yaml
operators/external-secrets-operator/0.10.2/tests/scorecard/config.yaml

bump external-secrets-operator 0.10.2

operator external-secrets-operator (0.10.2)

---

operators/dapr-kubernetes-operator/0.0.9/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
operators/dapr-kubernetes-operator/0.0.9/manifests/operator.dapr.io_daprcontrolplanes.yaml
operators/dapr-kubernetes-operator/0.0.9/manifests/operator.dapr.io_daprcruiscontrols.yaml
operators/dapr-kubernetes-operator/0.0.9/manifests/operator.dapr.io_daprinstances.yaml
operators/dapr-kubernetes-operator/0.0.9/metadata/annotations.yaml
operators/dapr-kubernetes-operator/0.0.9/tests/scorecard/config.yaml

operator dapr-kubernetes-operator (0.0.9)

---

operators/susql-operator/0.0.27/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.27/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.27/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.27/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.27/metadata/annotations.yaml
operators/susql-operator/0.0.27/tests/scorecard/config.yaml

operator susql-operator (0.0.27)

---

operators/rabbitmq-cluster-operator/2.10.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.10.0/manifests/crds.yaml
operators/rabbitmq-cluster-operator/2.10.0/manifests/rabbitmq.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.10.0/metadata/annotations.yaml

operator rabbitmq-cluster-operator (2.10.0)

---

operators/susql-operator/0.0.28/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.28/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.28/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.28/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.28/metadata/annotations.yaml
operators/susql-operator/0.0.28/tests/scorecard/config.yaml

operator susql-operator (0.0.28)

---

operators/project-quay/3.12.2/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.2/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.2/metadata/annotations.yaml

Add 3.12.2 to community operators

operator project-quay (3.12.2)

---

operators/skupper-operator/1.8.1/manifests/skupper-operator.v1.8.1.clusterserviceversion.yaml
operators/skupper-operator/1.8.1/metadata/annotations.yaml

operator skupper-operator (1.8.1)

---

operators/external-secrets-operator/0.10.3/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.10.3/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.10.3/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.10.3/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.10.3/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.10.3/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.10.3/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_uuids.yaml
operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.10.3/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.10.3/metadata/annotations.yaml
operators/external-secrets-operator/0.10.3/tests/scorecard/config.yaml

bump external-secrets-operator 0.10.3

operator external-secrets-operator (0.10.3)

---

operators/susql-operator/0.0.30/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.30/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.30/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.30/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.30/metadata/annotations.yaml
operators/susql-operator/0.0.30/tests/scorecard/config.yaml

operator susql-operator (0.0.30)

---

operators/grafana-operator/5.13.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.13.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.13.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.13.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.13.0/metadata/annotations.yaml

operator grafana-operator (5.13.0)

---

operators/deployment-validation-operator/0.7.8/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.7.8/manifests/deploymentvalidationoperator.0.7.7.clusterserviceversion.yaml
operators/deployment-validation-operator/0.7.8/metadata/annotations.yaml
operators/deployment-validation-operator/0.7.8/tests/scorecard/config.yaml

operator deployment-validation-operator (0.7.8)

---

operators/lbconfig-operator/0.5.0/manifests/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml
operators/lbconfig-operator/0.5.0/manifests/lbconfig-operator-controller-manager-metrics-service_v1_service.yaml
operators/lbconfig-operator/0.5.0/manifests/lbconfig-operator-manager-config_v1_configmap.yaml
operators/lbconfig-operator/0.5.0/manifests/lbconfig-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/lbconfig-operator/0.5.0/manifests/lbconfig-operator.clusterserviceversion.yaml
operators/lbconfig-operator/0.5.0/metadata/annotations.yaml
operators/lbconfig-operator/0.5.0/tests/scorecard/config.yaml
operators/lbconfig-operator/0.5.0/tests/scorecard/kuttl/create-externalloadbalancer/01-assert.yaml
operators/lbconfig-operator/0.5.0/tests/scorecard/kuttl/create-externalloadbalancer/10-create-elb.yaml
operators/lbconfig-operator/0.5.0/tests/scorecard/kuttl/create-externalloadbalancer/11-assert.yaml
operators/lbconfig-operator/0.5.0/tests/scorecard/kuttl/kuttl-test.yaml

operator lbconfig-operator (0.5.0)

---

operators/project-quay/3.11.5/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.11.5/manifests/quayregistries.crd.yaml
operators/project-quay/3.11.5/metadata/annotations.yaml

Add 3.11.5 to community operators

operator project-quay (3.11.5)

---

operators/gitlab-operator-kubernetes/1.3.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.3.2/metadata/annotations.yaml

operator gitlab-operator-kubernetes (1.3.2)

---

operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberobuilds.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberocouchdbs.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberoelasticsearches.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberokafkas.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberomails.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberomemcacheds.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberomongodbs.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberomysqls.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberopostgresqls.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberoprometheuses.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberorabbitmqs.yaml
operators/kubero-operator/0.1.3/manifests/application.kubero.dev_kuberoredis.yaml
operators/kubero-operator/0.1.3/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.1.3/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.1.3/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.1.3/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.1.3/metadata/annotations.yaml
operators/kubero-operator/0.1.3/tests/scorecard/config.yaml

operator kubero-operator (0.1.3)

---

operators/pubsubplus-eventbroker-operator/1.2.0/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
operators/pubsubplus-eventbroker-operator/1.2.0/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
operators/pubsubplus-eventbroker-operator/1.2.0/metadata/annotations.yaml
operators/pubsubplus-eventbroker-operator/1.2.0/tests/scorecard/config.yaml

operator pubsubplus-eventbroker-operator (1.2.0)

---

operators/apicurio-registry/1.1.3-v2.6.4.final/bundle.Dockerfile
operators/apicurio-registry/1.1.3-v2.6.4.final/manifests/apicurio-registry-operator.clusterserviceversion.yaml
operators/apicurio-registry/1.1.3-v2.6.4.final/manifests/registry.apicur.io_apicurioregistries.yaml
operators/apicurio-registry/1.1.3-v2.6.4.final/metadata/annotations.yaml
operators/apicurio-registry/1.1.3-v2.6.4.final/tests/scorecard/config.yaml

operator apicurio-registry (1.1.3-v2.6.4.final)

---

operators/gitlab-operator-kubernetes/1.3.3/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.3.3/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.3.3/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.3.3)

---

operators/gitlab-operator-kubernetes/1.4.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.4.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.4.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.4.0)

---

operators/authorino-operator/0.12.0/bundle.Dockerfile
operators/authorino-operator/0.12.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.12.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.12.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.12.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.12.0/manifests/authorino-operator-metrics_v1_service.yaml
operators/authorino-operator/0.12.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.12.0/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.12.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.12.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.12.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.12.0/metadata/annotations.yaml
operators/authorino-operator/0.12.0/tests/scorecard/config.yaml

operator authorino-operator (0.12.0)

---

operators/cryostat-operator/3.0.1/Dockerfile
operators/cryostat-operator/3.0.1/manifests/cryostat-operator-cryostat-namespaced_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/3.0.1/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/3.0.1/manifests/cryostat-operator-manager-config_v1_configmap.yaml
operators/cryostat-operator/3.0.1/manifests/cryostat-operator-oauth-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/3.0.1/manifests/cryostat-operator-webhook-service_v1_service.yaml
operators/cryostat-operator/3.0.1/manifests/cryostat-operator.clusterserviceversion.yaml
operators/cryostat-operator/3.0.1/manifests/operator.cryostat.io_cryostats.yaml
operators/cryostat-operator/3.0.1/metadata/annotations.yaml
operators/cryostat-operator/3.0.1/tests/scorecard/config.yaml
operators/cryostat-operator/ci.yaml

operator [CI] cryostat-operator (3.0.1)

---

operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberobuilds.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberocouchdbs.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberoelasticsearches.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberokafkas.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberomails.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberomemcacheds.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberomongodbs.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberomysqls.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberopostgresqls.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberoprometheuses.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberorabbitmqs.yaml
operators/kubero-operator/0.1.4/manifests/application.kubero.dev_kuberoredis.yaml
operators/kubero-operator/0.1.4/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.1.4/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.1.4/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.1.4/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.1.4/metadata/annotations.yaml
operators/kubero-operator/0.1.4/tests/scorecard/config.yaml

operator kubero-operator (0.1.4)

---

operators/nri-plugins-operator/0.7.1/manifests/config.nri_balloonspolicies.yaml
operators/nri-plugins-operator/0.7.1/manifests/config.nri_nriplugindeployments.yaml
operators/nri-plugins-operator/0.7.1/manifests/config.nri_templatepolicies.yaml
operators/nri-plugins-operator/0.7.1/manifests/config.nri_topologyawarepolicies.yaml
operators/nri-plugins-operator/0.7.1/manifests/nri-plugins-operator-controller-manager-metrics-service_v1_service.yaml
operators/nri-plugins-operator/0.7.1/manifests/nri-plugins-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nri-plugins-operator/0.7.1/manifests/nri-plugins-operator.clusterserviceversion.yaml
operators/nri-plugins-operator/0.7.1/manifests/topology.node.k8s.io_noderesourcetopologies.yaml
operators/nri-plugins-operator/0.7.1/metadata/annotations.yaml
operators/nri-plugins-operator/0.7.1/tests/scorecard/config.yaml

Submit nri-plugins-operator ([0.7.1](https://github.com/containers/nri-plugins/releases/tag/v0.7.1)) version.

operator nri-plugins-operator (0.7.1)

---

operators/dynatrace-operator/1.3.0/Dockerfile
operators/dynatrace-operator/1.3.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.3.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.3.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.3.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.3.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.3.0/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.3.0/metadata/annotations.yaml

operator dynatrace-operator (1.3.0)

---

operators/external-secrets-operator/0.10.4/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.10.4/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.10.4/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.10.4/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.10.4/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.10.4/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.10.4/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_uuids.yaml
operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.10.4/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.10.4/metadata/annotations.yaml
operators/external-secrets-operator/0.10.4/tests/scorecard/config.yaml

bump external-secrets-operator 0.10.4

operator external-secrets-operator (0.10.4)

---

operators/gitlab-operator-kubernetes/1.4.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.4.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.4.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.4.1)

---

operators/limitador-operator/0.10.0/bundle.Dockerfile
operators/limitador-operator/0.10.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
operators/limitador-operator/0.10.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/limitador-operator/0.10.0/manifests/limitador-operator-metrics_v1_service.yaml
operators/limitador-operator/0.10.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/0.10.0/manifests/limitador.kuadrant.io_limitadors.yaml
operators/limitador-operator/0.10.0/metadata/annotations.yaml
operators/limitador-operator/0.10.0/tests/scorecard/config.yaml
operators/limitador-operator/0.4.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/0.5.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/0.7.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/0.8.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/ci.yaml

operator [R] [CI] limitador-operator (0.10.0 0.4.0 0.5.0 0.6.0 0.7.0 0.8.0)

---

operators/dns-operator/0.6.0/manifests/dns-operator-controller-manager-metrics-service_v1_service.yaml
operators/dns-operator/0.6.0/manifests/dns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dns-operator/0.6.0/manifests/dns-operator.clusterserviceversion.yaml
operators/dns-operator/0.6.0/manifests/kuadrant.io_dnsrecords.yaml
operators/dns-operator/0.6.0/metadata/annotations.yaml
operators/dns-operator/0.6.0/tests/scorecard/config.yaml
operators/dns-operator/ci.yaml

operator [R] [CI] dns-operator (0.2.0 0.6.0)

---

operators/kuadrant-operator/0.10.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.10.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.10.0/manifests/kuadrant-operator-metrics_v1_service.yaml
operators/kuadrant-operator/0.10.0/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.10.0/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.10.0/manifests/kuadrant.io_dnspolicies.yaml
operators/kuadrant-operator/0.10.0/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.10.0/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.10.0/manifests/kuadrant.io_tlspolicies.yaml
operators/kuadrant-operator/0.10.0/metadata/annotations.yaml
operators/kuadrant-operator/0.10.0/metadata/dependencies.yaml
operators/kuadrant-operator/0.10.0/tests/scorecard/config.yaml
operators/kuadrant-operator/0.2.1/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.3.1/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.4.1/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.5.0/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.6.0/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.7.0/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.7.1/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/ci.yaml

operator [R] [CI] kuadrant-operator (0.10.0 0.2.1 0.3.0 0.3.1 0.4.1 0.5.0 0.6.0 0.6.1 0.7.0 0.7.1)

---

operators/mariadb-operator/0.32.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/0.32.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.32.0/metadata/annotations.yaml
operators/mariadb-operator/0.32.0/tests/scorecard/config.yaml

Added operator mariadb-operator (0.32.0)

operator mariadb-operator (0.32.0)

---

operators/susql-operator/0.0.32/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.32/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.32/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.32/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.32/metadata/annotations.yaml
operators/susql-operator/0.0.32/tests/scorecard/config.yaml

operator susql-operator (0.0.32)

---

operators/intel-device-plugins-operator/0.31.0/bundle.Dockerfile
operators/intel-device-plugins-operator/0.31.0/manifests/deviceplugin.intel.com_dlbdeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.0/manifests/deviceplugin.intel.com_dsadeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.0/manifests/deviceplugin.intel.com_fpgadeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.0/manifests/deviceplugin.intel.com_gpudeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.0/manifests/deviceplugin.intel.com_iaadeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.0/manifests/deviceplugin.intel.com_qatdeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.0/manifests/deviceplugin.intel.com_sgxdeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.0/manifests/fpga.intel.com_acceleratorfunctions.yaml
operators/intel-device-plugins-operator/0.31.0/manifests/fpga.intel.com_fpgaregions.yaml
operators/intel-device-plugins-operator/0.31.0/manifests/intel-device-plugins-operator.clusterserviceversion.yaml
operators/intel-device-plugins-operator/0.31.0/metadata/annotations.yaml
operators/intel-device-plugins-operator/0.31.0/tests/scorecard/config.yaml

operator intel-device-plugins-operator (0.31.0)

---

operators/intel-device-plugins-operator/0.31.0/manifests/intel-device-plugins-operator.clusterserviceversion.yaml

operator [O] intel-device-plugins-operator (0.31.0)

---

operators/project-quay/3.11.6/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.11.6/manifests/quayregistries.crd.yaml
operators/project-quay/3.11.6/metadata/annotations.yaml

Add 3.11.6 to community operators

operator project-quay (3.11.6)

---

operators/cc-operator/0.10.0/manifests/cc-operator-controller-manager-metrics-service_v1_service.yaml
operators/cc-operator/0.10.0/manifests/cc-operator-manager-config_v1_configmap.yaml
operators/cc-operator/0.10.0/manifests/cc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cc-operator/0.10.0/manifests/cc-operator.clusterserviceversion.yaml
operators/cc-operator/0.10.0/manifests/confidentialcontainers.org_ccruntimes.yaml
operators/cc-operator/0.10.0/metadata/annotations.yaml
operators/cc-operator/0.10.0/tests/scorecard/config.yaml

operator cc-operator (0.10.0)

---

operators/mongodb-enterprise/1.28.0/bundle.Dockerfile
operators/mongodb-enterprise/1.28.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.28.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.28.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.28.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.28.0/manifests/mongodb-enterprise-operator-service_v1_service.yaml
operators/mongodb-enterprise/1.28.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.28.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.28.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.28.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.28.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.28.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.28.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.28.0/tests/scorecard/config.yaml

operator mongodb-enterprise (1.28.0)

---

operators/limitador-operator/0.11.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
operators/limitador-operator/0.11.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/limitador-operator/0.11.0/manifests/limitador-operator-metrics_v1_service.yaml
operators/limitador-operator/0.11.0/manifests/limitador-operator.clusterserviceversion.yaml
operators/limitador-operator/0.11.0/manifests/limitador.kuadrant.io_limitadors.yaml
operators/limitador-operator/0.11.0/metadata/annotations.yaml
operators/limitador-operator/0.11.0/tests/scorecard/config.yaml

operator limitador-operator (0.11.0)

---

operators/authorino-operator/0.13.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.13.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.13.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.13.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.13.0/manifests/authorino-operator-metrics_v1_service.yaml
operators/authorino-operator/0.13.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.13.0/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.13.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.13.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.13.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.13.0/metadata/annotations.yaml
operators/authorino-operator/0.13.0/tests/scorecard/config.yaml

operator authorino-operator (0.13.0)

---

operators/kuadrant-operator/0.11.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.11.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.11.0/manifests/kuadrant-operator-metrics_v1_service.yaml
operators/kuadrant-operator/0.11.0/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.11.0/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.11.0/manifests/kuadrant.io_dnspolicies.yaml
operators/kuadrant-operator/0.11.0/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.11.0/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.11.0/manifests/kuadrant.io_tlspolicies.yaml
operators/kuadrant-operator/0.11.0/metadata/annotations.yaml
operators/kuadrant-operator/0.11.0/metadata/dependencies.yaml
operators/kuadrant-operator/0.11.0/tests/scorecard/config.yaml

operator kuadrant-operator (0.11.0)

---

operators/project-quay/3.12.3/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.3/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.3/metadata/annotations.yaml

Add 3.12.3 to community operators

operator project-quay (3.12.3)

---

operators/mariadb-operator/0.34.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/0.34.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.34.0/metadata/annotations.yaml
operators/mariadb-operator/0.34.0/tests/scorecard/config.yaml

Added operator mariadb-operator (0.34.0)

operator mariadb-operator (0.34.0)

---

operators/mariadb-operator/0.34.0/manifests/mariadb-operator.clusterserviceversion.yaml

Added operator mariadb-operator (0.34.0)

operator [O] mariadb-operator (0.34.0)

---

operators/datadog-operator/1.9.0/manifests/datadog-operator-webhook-service_v1_service.yaml
operators/datadog-operator/1.9.0/manifests/datadog-operator.clusterserviceversion.yaml
operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogagentprofiles.yaml
operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogagents.yaml
operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogdashboards.yaml
operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogmetrics.yaml
operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogmonitors.yaml
operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogpodautoscalers.yaml
operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogslos.yaml
operators/datadog-operator/1.9.0/metadata/annotations.yaml
operators/datadog-operator/1.9.0/tests/scorecard/config.yaml

operator datadog-operator (1.9.0)

---

operators/verticadb-operator/24.4.0-0/manifests/vertica.com_eventtriggers.yaml
operators/verticadb-operator/24.4.0-0/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/24.4.0-0/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/24.4.0-0/manifests/vertica.com_verticareplicators.yaml
operators/verticadb-operator/24.4.0-0/manifests/vertica.com_verticarestorepointsqueries.yaml
operators/verticadb-operator/24.4.0-0/manifests/vertica.com_verticascrutinizers.yaml
operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/24.4.0-0/metadata/annotations.yaml
operators/verticadb-operator/24.4.0-0/tests/scorecard/config.yaml

operator verticadb-operator (24.4.0-0)

---

operators/gitlab-operator-kubernetes/1.4.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.4.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.4.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.4.2)

---

operators/wandb-operator/1.0.0/manifests/apps.wandb.com_weightsandbiases.yaml
operators/wandb-operator/1.0.0/manifests/operator.clusterserviceversion.yaml
operators/wandb-operator/1.0.0/metadata/annotations.yaml
operators/wandb-operator/1.0.0/tests/scorecard/config.yaml
operators/wandb-operator/ci.yaml

operator [N] [CI] wandb-operator (1.0.0)

---

operators/dell-csm-operator/1.6.1/manifests/apexconnectivityclients.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.6.1/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.6.1/manifests/dell-csm-operator.v1.6.1.clusterserviceversion.yaml
operators/dell-csm-operator/1.6.1/metadata/annotations.yaml
operators/dell-csm-operator/1.6.1/tests/scorecard/config.yaml

operator dell-csm-operator (1.6.1)

---

operators/grafana-operator/5.14.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.14.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.14.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.14.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.14.0/metadata/annotations.yaml

operator grafana-operator (5.14.0)

---

operators/dynatrace-operator/1.3.1/Dockerfile
operators/dynatrace-operator/1.3.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.3.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.3.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.3.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.3.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.3.1/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.3.1/metadata/annotations.yaml

operator dynatrace-operator (1.3.1)

---

operators/wandb-operator/1.0.0/bundle.Dockerfile
operators/wandb-operator/1.0.0/manifests/wandb-operator-manager_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/wandb-operator/1.0.0/manifests/wandb-operator-manager_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/wandb-operator/1.0.0/manifests/wandb-operator.clusterserviceversion.yaml
operators/wandb-operator/1.0.0/metadata/annotations.yaml

operator [N] wandb-operator (1.0.0)

---

operators/clickhouse/0.24.0/manifests/clickhouse-operator.v0.24.0.clusterserviceversion.yaml
operators/clickhouse/0.24.0/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.0/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.0/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.24.0/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.0/metadata/annotations.yaml

operator clickhouse (0.24.0)

---

operators/bpfman-operator/0.5.4/bundle.Dockerfile
operators/bpfman-operator/0.5.4/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-config_v1_configmap.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-daemon_v1_serviceaccount.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-operator.clusterserviceversion.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman.io_bpfapplications.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman.io_bpfprograms.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman.io_fentryprograms.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman.io_fexitprograms.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman.io_kprobeprograms.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman.io_tcprograms.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman.io_tracepointprograms.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman.io_uprobeprograms.yaml
operators/bpfman-operator/0.5.4/manifests/bpfman.io_xdpprograms.yaml
operators/bpfman-operator/0.5.4/metadata/annotations.yaml
operators/bpfman-operator/0.5.4/metadata/dependencies.yaml
operators/bpfman-operator/0.5.4/tests/scorecard/config.yaml

bpfman-operator release v0.5.4
--

operator bpfman-operator (0.5.4)

---

operators/intel-device-plugins-operator/0.31.1/bundle.Dockerfile
operators/intel-device-plugins-operator/0.31.1/manifests/deviceplugin.intel.com_dlbdeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.1/manifests/deviceplugin.intel.com_dsadeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.1/manifests/deviceplugin.intel.com_fpgadeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.1/manifests/deviceplugin.intel.com_gpudeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.1/manifests/deviceplugin.intel.com_iaadeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.1/manifests/deviceplugin.intel.com_qatdeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.1/manifests/deviceplugin.intel.com_sgxdeviceplugins.yaml
operators/intel-device-plugins-operator/0.31.1/manifests/fpga.intel.com_acceleratorfunctions.yaml
operators/intel-device-plugins-operator/0.31.1/manifests/fpga.intel.com_fpgaregions.yaml
operators/intel-device-plugins-operator/0.31.1/manifests/intel-device-plugins-operator.clusterserviceversion.yaml
operators/intel-device-plugins-operator/0.31.1/metadata/annotations.yaml
operators/intel-device-plugins-operator/0.31.1/tests/scorecard/config.yaml

operator intel-device-plugins-operator (0.31.1)

---

operators/move2kube-operator/0.3.15-rc.0/bundle.Dockerfile
operators/move2kube-operator/0.3.15-rc.0/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.15-rc.0/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.15-rc.0/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.15-rc.0/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.15-rc.0/metadata/annotations.yaml
operators/move2kube-operator/0.3.15-rc.0/tests/scorecard/config.yaml

An automated PR to update move2kube-operator to v0.3.15-rc.0

operator move2kube-operator (0.3.15-rc.0)

---

operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberoapps.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberobuilds.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberocouchdbs.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberoelasticsearches.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberoes.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberokafkas.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberomails.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberomemcacheds.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberomongodbs.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberomysqls.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberopipelines.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberopostgresqls.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberoprometheuses.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberorabbitmqs.yaml
operators/kubero-operator/0.1.5/manifests/application.kubero.dev_kuberoredis.yaml
operators/kubero-operator/0.1.5/manifests/kubero-operator-controller-manager-metrics-service_v1_service.yaml
operators/kubero-operator/0.1.5/manifests/kubero-operator-manager-config_v1_configmap.yaml
operators/kubero-operator/0.1.5/manifests/kubero-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kubero-operator/0.1.5/manifests/kubero-operator.clusterserviceversion.yaml
operators/kubero-operator/0.1.5/metadata/annotations.yaml
operators/kubero-operator/0.1.5/tests/scorecard/config.yaml

operator kubero-operator (0.1.5)

---

operators/mariadb-operator/0.35.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/0.35.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.35.0/metadata/annotations.yaml
operators/mariadb-operator/0.35.0/tests/scorecard/config.yaml

Added operator mariadb-operator (0.35.0)

operator mariadb-operator (0.35.0)

---

operators/dynatrace-operator/1.3.2/Dockerfile
operators/dynatrace-operator/1.3.2/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.3.2/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.3.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.3.2/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.3.2/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.3.2/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.3.2/metadata/annotations.yaml

operator dynatrace-operator (1.3.2)

---

operators/mariadb-operator/0.35.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/0.35.1/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.35.1/metadata/annotations.yaml
operators/mariadb-operator/0.35.1/tests/scorecard/config.yaml

Added operator mariadb-operator (0.35.1)

operator mariadb-operator (0.35.1)

---

operators/external-secrets-operator/0.10.5/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.10.5/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.10.5/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.10.5/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.10.5/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.10.5/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.10.5/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_uuids.yaml
operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.10.5/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.10.5/metadata/annotations.yaml
operators/external-secrets-operator/0.10.5/tests/scorecard/config.yaml

bump external-secrets-operator 0.10.5

operator external-secrets-operator (0.10.5)

---

operators/mongodb-atlas-kubernetes/2.5.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.5.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.5.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.5.0/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.5.0)

---

operators/tempo-operator/0.14.0/bundle.Dockerfile
operators/tempo-operator/0.14.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.14.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.14.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.14.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.14.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.14.0/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.14.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.14.0/metadata/annotations.yaml
operators/tempo-operator/0.14.0/tests/scorecard/config.yaml

Release tempo-operator `0.14.0`.

operator tempo-operator (0.14.0)

---

operators/gitlab-operator-kubernetes/1.6.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.6.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.6.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.6.0)

---

operators/percona-server-mongodb-operator/1.17.0/manifests/percona-server-mongodb-operator.v1.17.0.clusterserviceversion.yaml
operators/percona-server-mongodb-operator/1.17.0/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.17.0/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.17.0/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.17.0/metadata/annotations.yaml

operator percona-server-mongodb-operator (1.17.0)

---

operators/percona-xtradb-cluster-operator/1.15.1/manifests/percona-xtradb-cluster-operator.v1.15.1.clusterserviceversion.yaml
operators/percona-xtradb-cluster-operator/1.15.1/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.15.1/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.15.1/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.15.1/metadata/annotations.yaml

operator percona-xtradb-cluster-operator (1.15.1)

---

operators/beegfs-csi-driver-operator/1.7.0/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml
operators/beegfs-csi-driver-operator/1.7.0/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml
operators/beegfs-csi-driver-operator/1.7.0/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/beegfs-csi-driver-operator/1.7.0/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml
operators/beegfs-csi-driver-operator/1.7.0/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml
operators/beegfs-csi-driver-operator/1.7.0/metadata/annotations.yaml
operators/beegfs-csi-driver-operator/1.7.0/tests/scorecard/config.yaml

operator beegfs-csi-driver-operator (1.7.0)

---

operators/project-quay/3.12.4/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.4/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.4/metadata/annotations.yaml

Add 3.12.4 to community operators

operator project-quay (3.12.4)

---

operators/camel-k/2.5.0/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.5.0/manifests/camel-k.v2.5.0.clusterserviceversion.yaml
operators/camel-k/2.5.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.5.0/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.5.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.5.0/manifests/integrationprofiles.camel.apache.org.crd.yaml
operators/camel-k/2.5.0/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.5.0/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/2.5.0/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.5.0/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.5.0/metadata/annotations.yaml
operators/camel-k/2.5.0/tests/scorecard/config.yaml

operator camel-k (2.5.0)

---

operators/trident-operator/24.10.0/manifests/trident-operator.v24.10.0.clusterserviceversion.yaml
operators/trident-operator/24.10.0/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
operators/trident-operator/24.10.0/metadata/annotations.yaml

operator trident-operator (24.10.0)

---

operators/cluster-manager/0.15.1/manifests/cluster-manager.clusterserviceversion.yaml
operators/cluster-manager/0.15.1/manifests/operator.open-cluster-management.io_clustermanagers.yaml
operators/cluster-manager/0.15.1/metadata/annotations.yaml

operator cluster-manager (0.15.1)

---

operators/klusterlet/0.15.1/manifests/klusterlet.clusterserviceversion.yaml
operators/klusterlet/0.15.1/manifests/operator.open-cluster-management.io_klusterlets.yaml
operators/klusterlet/0.15.1/metadata/annotations.yaml

operator klusterlet (0.15.1)

---

operators/instaslice-operator/0.0.2/manifests/inference.redhat.com_instaslices.yaml
operators/instaslice-operator/0.0.2/manifests/instaslice-operator-controller-manager-metrics-service_v1_service.yaml
operators/instaslice-operator/0.0.2/manifests/instaslice-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/instaslice-operator/0.0.2/manifests/instaslice-operator-webhook-service_v1_service.yaml
operators/instaslice-operator/0.0.2/manifests/instaslice-operator.clusterserviceversion.yaml
operators/instaslice-operator/0.0.2/metadata/annotations.yaml
operators/instaslice-operator/0.0.2/tests/scorecard/config.yaml
operators/instaslice-operator/ci.yaml

operator [CI] instaslice-operator (0.0.2)

---

operators/instaslice-operator/0.0.2/manifests/instaslice-operator.clusterserviceversion.yaml

operator [O] instaslice-operator (0.0.2)

---

operators/project-quay/3.13.0/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.13.0/manifests/quayregistries.crd.yaml
operators/project-quay/3.13.0/metadata/annotations.yaml

Add 3.13.0 to community operators

operator project-quay (3.13.0)

---

operators/skupper-operator/1.8.2/manifests/skupper-operator.v1.8.2.clusterserviceversion.yaml
operators/skupper-operator/1.8.2/metadata/annotations.yaml

operator skupper-operator (1.8.2)

---

operators/loki-operator/0.7.0/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
operators/loki-operator/0.7.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
operators/loki-operator/0.7.0/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/loki-operator/0.7.0/manifests/loki-operator-manager-config_v1_configmap.yaml
operators/loki-operator/0.7.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/loki-operator/0.7.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
operators/loki-operator/0.7.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/loki-operator/0.7.0/manifests/loki-operator-webhook-service_v1_service.yaml
operators/loki-operator/0.7.0/manifests/loki-operator.clusterserviceversion.yaml
operators/loki-operator/0.7.0/manifests/loki.grafana.com_alertingrules.yaml
operators/loki-operator/0.7.0/manifests/loki.grafana.com_lokistacks.yaml
operators/loki-operator/0.7.0/manifests/loki.grafana.com_recordingrules.yaml
operators/loki-operator/0.7.0/manifests/loki.grafana.com_rulerconfigs.yaml
operators/loki-operator/0.7.0/metadata/annotations.yaml
operators/loki-operator/0.7.0/tests/scorecard/config.yaml
operators/loki-operator/ci.yaml

operator [CI] loki-operator (0.7.0)

---

operators/mariadb-operator/0.36.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/0.36.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.36.0/metadata/annotations.yaml
operators/mariadb-operator/0.36.0/tests/scorecard/config.yaml

Added operator mariadb-operator (0.36.0)

operator mariadb-operator (0.36.0)

---

operators/tempo-operator/0.14.1/bundle.Dockerfile
operators/tempo-operator/0.14.1/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.14.1/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.14.1/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.14.1/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.14.1/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.14.1/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.14.1/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.14.1/metadata/annotations.yaml
operators/tempo-operator/0.14.1/tests/scorecard/config.yaml

Release tempo-operator `0.14.1`.

operator tempo-operator (0.14.1)

---

operators/datadog-operator/1.10.0/manifests/datadog-operator-webhook-service_v1_service.yaml
operators/datadog-operator/1.10.0/manifests/datadog-operator.clusterserviceversion.yaml
operators/datadog-operator/1.10.0/manifests/datadoghq.com_datadogagentprofiles.yaml
operators/datadog-operator/1.10.0/manifests/datadoghq.com_datadogagents.yaml
operators/datadog-operator/1.10.0/manifests/datadoghq.com_datadogdashboards.yaml
operators/datadog-operator/1.10.0/manifests/datadoghq.com_datadogmetrics.yaml
operators/datadog-operator/1.10.0/manifests/datadoghq.com_datadogmonitors.yaml
operators/datadog-operator/1.10.0/manifests/datadoghq.com_datadogpodautoscalers.yaml
operators/datadog-operator/1.10.0/manifests/datadoghq.com_datadogslos.yaml
operators/datadog-operator/1.10.0/metadata/annotations.yaml
operators/datadog-operator/1.10.0/tests/scorecard/config.yaml

Update operator datadog-operator (1.10.0)
--

operator datadog-operator (1.10.0)

---

operators/keda/2.16.0/manifests/eventing.keda.sh_cloudeventsources.yaml
operators/keda/2.16.0/manifests/eventing.keda.sh_clustercloudeventsources.yaml
operators/keda/2.16.0/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.16.0/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.16.0/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.16.0/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.16.0/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.16.0/manifests/keda.v2.16.0.clusterserviceversion.yaml
operators/keda/2.16.0/metadata/annotations.yaml

operator keda (2.16.0)

---

operators/kube-green/0.6.0/manifests/kube-green-aggregate-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kube-green/0.6.0/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml
operators/kube-green/0.6.0/manifests/kube-green-manager-config_v1_configmap.yaml
operators/kube-green/0.6.0/manifests/kube-green-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kube-green/0.6.0/manifests/kube-green-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/kube-green/0.6.0/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kube-green/0.6.0/manifests/kube-green-webhook-service_v1_service.yaml
operators/kube-green/0.6.0/manifests/kube-green.clusterserviceversion.yaml
operators/kube-green/0.6.0/manifests/kube-green.com_sleepinfos.yaml
operators/kube-green/0.6.0/metadata/annotations.yaml
operators/kube-green/0.6.0/tests/scorecard/config.yaml

operator kube-green (0.6.0)

---

operators/loki-operator/0.7.1/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
operators/loki-operator/0.7.1/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
operators/loki-operator/0.7.1/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/loki-operator/0.7.1/manifests/loki-operator-manager-config_v1_configmap.yaml
operators/loki-operator/0.7.1/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/loki-operator/0.7.1/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
operators/loki-operator/0.7.1/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/loki-operator/0.7.1/manifests/loki-operator-webhook-service_v1_service.yaml
operators/loki-operator/0.7.1/manifests/loki-operator.clusterserviceversion.yaml
operators/loki-operator/0.7.1/manifests/loki.grafana.com_alertingrules.yaml
operators/loki-operator/0.7.1/manifests/loki.grafana.com_lokistacks.yaml
operators/loki-operator/0.7.1/manifests/loki.grafana.com_recordingrules.yaml
operators/loki-operator/0.7.1/manifests/loki.grafana.com_rulerconfigs.yaml
operators/loki-operator/0.7.1/metadata/annotations.yaml
operators/loki-operator/0.7.1/tests/scorecard/config.yaml

operator loki-operator (0.7.1)

---

operators/grafana-operator/5.15.1/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.15.1/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.15.1/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.15.1/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.15.1/metadata/annotations.yaml

operator grafana-operator (5.15.1)

---

operators/gitlab-operator-kubernetes/1.6.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.6.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.6.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.6.1)

---

operators/layer7-operator/1.1.0/manifests/layer7-operator-controller-manager-metrics-service_v1_service.yaml
operators/layer7-operator/1.1.0/manifests/layer7-operator-manager-config_v1_configmap.yaml
operators/layer7-operator/1.1.0/manifests/layer7-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/layer7-operator/1.1.0/manifests/layer7-operator-webhook-service_v1_service.yaml
operators/layer7-operator/1.1.0/manifests/layer7-operator.clusterserviceversion.yaml
operators/layer7-operator/1.1.0/manifests/security.brcmlabs.com_gateways.yaml
operators/layer7-operator/1.1.0/manifests/security.brcmlabs.com_l7apis.yaml
operators/layer7-operator/1.1.0/manifests/security.brcmlabs.com_l7portals.yaml
operators/layer7-operator/1.1.0/manifests/security.brcmlabs.com_repositories.yaml
operators/layer7-operator/1.1.0/metadata/annotations.yaml
operators/layer7-operator/1.1.0/tests/scorecard/config.yaml

operator layer7-operator (1.1.0)

---

operators/elastic-cloud-eck/2.15.0/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.15.0/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.15.0/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.15.0/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.15.0/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.15.0/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.15.0/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.15.0/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.15.0/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.15.0/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.15.0/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.15.0/metadata/annotations.yaml

Update the ECK operator to the latest version `2.15.0`.

operator elastic-cloud-eck (2.15.0)

---

operators/datasance-pot-operator/3.4.9/manifests/datasance-iofog-operator.clusterserviceversion.yaml
operators/datasance-pot-operator/3.4.9/manifests/datasance-pot-operator_clusterrole.yaml
operators/datasance-pot-operator/3.4.9/manifests/datasance-pot-operator_role.yaml
operators/datasance-pot-operator/3.4.9/manifests/datasance-pot-operator_rolebinding.yaml
operators/datasance-pot-operator/3.4.9/manifests/datasance.com-controlplanes_crd.yaml
operators/datasance-pot-operator/3.4.9/metadata/annotations.yaml
operators/datasance-pot-operator/ci.yaml

operator [CI] datasance-pot-operator (3.4.9)

---

operators/mongodb-enterprise/1.29.0/bundle.Dockerfile
operators/mongodb-enterprise/1.29.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.29.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.29.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.29.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.29.0/manifests/mongodb-enterprise-operator-service_v1_service.yaml
operators/mongodb-enterprise/1.29.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.29.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.29.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.29.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.29.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.29.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.29.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.29.0/tests/scorecard/config.yaml

operator mongodb-enterprise (1.29.0)

---

operators/authorino-operator/0.13.1/bundle.Dockerfile
operators/authorino-operator/0.13.1/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.13.1/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.13.1/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.13.1/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.13.1/manifests/authorino-operator-metrics_v1_service.yaml
operators/authorino-operator/0.13.1/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.13.1/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.13.1/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.13.1/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.13.1/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.13.1/metadata/annotations.yaml
operators/authorino-operator/0.13.1/tests/scorecard/config.yaml

operator authorino-operator (0.13.1)

---

operators/authorino-operator/0.14.0/bundle.Dockerfile
operators/authorino-operator/0.14.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.14.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.14.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.14.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.14.0/manifests/authorino-operator-metrics_v1_service.yaml
operators/authorino-operator/0.14.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.14.0/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.14.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.14.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.14.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.14.0/metadata/annotations.yaml
operators/authorino-operator/0.14.0/tests/scorecard/config.yaml

operator authorino-operator (0.14.0)

---

operators/quay-api-operator/1.0.0/manifests/quay-api-operator-controller-manager-metrics-service_v1_service.yaml
operators/quay-api-operator/1.0.0/manifests/quay-api-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/quay-api-operator/1.0.0/manifests/quay-api-operator.clusterserviceversion.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_apitokens.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_applications.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_defaultperms.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_dockertokens.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_firstusers.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_manifestlabels.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_messages.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_notifications.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_organizations.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_proxycaches.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_quotas.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_repositories.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_repositorymirrors.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_robots.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_tags.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_teamldaps.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_teamoidcs.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_teams.yaml
operators/quay-api-operator/1.0.0/manifests/quay.herve4m.github.io_users.yaml
operators/quay-api-operator/1.0.0/metadata/annotations.yaml
operators/quay-api-operator/1.0.0/tests/scorecard/config.yaml

operator quay-api-operator (1.0.0)

---

operators/edp-keycloak-operator/1.23.0/manifests/client-secret-policy-sample_v1_secret.yaml
operators/edp-keycloak-operator/1.23.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.23.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.23.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.23.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.23.0/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.23.0)

---

operators/project-quay/3.13.1/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.13.1/manifests/quayregistries.crd.yaml
operators/project-quay/3.13.1/metadata/annotations.yaml

Add 3.13.1 to community operators

operator [R] project-quay (3.13.0 3.13.1)

---

operators/hawtio-operator/1.1.1/manifests/hawt.io_hawtios.yaml
operators/hawtio-operator/1.1.1/manifests/hawtio-operator.clusterserviceversion.yaml
operators/hawtio-operator/1.1.1/metadata/annotations.yaml
operators/hawtio-operator/1.1.1/tests/scorecard/config.yaml

operator hawtio-operator (1.1.1)

---

operators/gitlab-operator-kubernetes/1.7.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.7.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.7.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.7.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.7.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.7.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.7.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.7.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.7.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.7.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.7.0)

---

operators/external-secrets-operator/0.10.7/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.10.7/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.10.7/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.10.7/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.10.7/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.10.7/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.10.7/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_stssessiontokens.yaml
operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_uuids.yaml
operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.10.7/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.10.7/metadata/annotations.yaml
operators/external-secrets-operator/0.10.7/tests/scorecard/config.yaml

bump external-secrets-operator 0.10.7

operator external-secrets-operator (0.10.7)

---

operators/authorino-operator/0.15.0/bundle.Dockerfile
operators/authorino-operator/0.15.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.15.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.15.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.15.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.15.0/manifests/authorino-operator-metrics_v1_service.yaml
operators/authorino-operator/0.15.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.15.0/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.15.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.15.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.15.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.15.0/metadata/annotations.yaml
operators/authorino-operator/0.15.0/tests/scorecard/config.yaml

operator authorino-operator (0.15.0)

---

operators/authorino-operator/0.15.1/bundle.Dockerfile
operators/authorino-operator/0.15.1/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.15.1/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.15.1/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.15.1/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.15.1/manifests/authorino-operator-metrics_v1_service.yaml
operators/authorino-operator/0.15.1/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.15.1/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.15.1/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.15.1/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.15.1/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.15.1/metadata/annotations.yaml
operators/authorino-operator/0.15.1/tests/scorecard/config.yaml

operator authorino-operator (0.15.1)

---

operators/authorino-operator/0.16.0/bundle.Dockerfile
operators/authorino-operator/0.16.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.16.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.16.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.16.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/authorino-operator/0.16.0/manifests/authorino-operator-metrics_v1_service.yaml
operators/authorino-operator/0.16.0/manifests/authorino-operator.clusterserviceversion.yaml
operators/authorino-operator/0.16.0/manifests/authorino-webhooks_v1_service.yaml
operators/authorino-operator/0.16.0/manifests/authorino.kuadrant.io_authconfigs.yaml
operators/authorino-operator/0.16.0/manifests/manager-config_v1_configmap.yaml
operators/authorino-operator/0.16.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
operators/authorino-operator/0.16.0/metadata/annotations.yaml
operators/authorino-operator/0.16.0/tests/scorecard/config.yaml

operator authorino-operator (0.16.0)

---

operators/project-quay/3.12.5/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.5/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.5/metadata/annotations.yaml

Add 3.12.5 to community operators

operator project-quay (3.12.5)

---

operators/tektoncd-operator/0.74.0/manifests/config-logging_v1_configmap.yaml
operators/tektoncd-operator/0.74.0/manifests/operator.tekton.dev_manualapprovalgates.yaml
operators/tektoncd-operator/0.74.0/manifests/operator.tekton.dev_tektonchains.yaml
operators/tektoncd-operator/0.74.0/manifests/operator.tekton.dev_tektonconfigs.yaml
operators/tektoncd-operator/0.74.0/manifests/operator.tekton.dev_tektondashboards.yaml
operators/tektoncd-operator/0.74.0/manifests/operator.tekton.dev_tektonhubs.yaml
operators/tektoncd-operator/0.74.0/manifests/operator.tekton.dev_tektoninstallersets.yaml
operators/tektoncd-operator/0.74.0/manifests/operator.tekton.dev_tektonpipelines.yaml
operators/tektoncd-operator/0.74.0/manifests/operator.tekton.dev_tektonresults.yaml
operators/tektoncd-operator/0.74.0/manifests/operator.tekton.dev_tektontriggers.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-config-defaults_v1_configmap.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-config-observability_v1_configmap.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-config-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-config-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-operator-controller-config-leader-election_v1_configmap.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_role.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-operator-info_v1_configmap.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-operator-webhook-certs_v1_secret.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-operator-webhook-config-leader-election_v1_configmap.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-operator-webhook_v1_service.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-operator_v1_service.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-result-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tektoncd-operator/0.74.0/manifests/tekton-result-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/tektoncd-operator/0.74.0/manifests/tektoncd-operator.clusterserviceversion.yaml
operators/tektoncd-operator/0.74.0/metadata/annotations.yaml
operators/tektoncd-operator/0.74.0/tests/scorecard/config.yaml

operator tektoncd-operator (0.74.0)

---

operators/quay-api-operator/1.1.0/manifests/quay-api-operator-controller-manager-metrics-service_v1_service.yaml
operators/quay-api-operator/1.1.0/manifests/quay-api-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/quay-api-operator/1.1.0/manifests/quay-api-operator.clusterserviceversion.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_apitokens.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_applications.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_defaultperms.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_dockertokens.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_firstusers.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_manifestlabels.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_messages.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_notifications.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_organizationprunes.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_organizations.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_proxycaches.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_quotas.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_repositories.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_repositorymirrors.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_repositoryprunes.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_robots.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_tags.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_teamldaps.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_teamoidcs.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_teams.yaml
operators/quay-api-operator/1.1.0/manifests/quay.herve4m.github.io_users.yaml
operators/quay-api-operator/1.1.0/metadata/annotations.yaml
operators/quay-api-operator/1.1.0/tests/scorecard/config.yaml

operator quay-api-operator (1.1.0)

---

operators/gitlab-operator-kubernetes/1.7.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.7.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.7.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.7.1)

---

operators/clickhouse/0.24.1/manifests/clickhouse-operator.v0.24.1.clusterserviceversion.yaml
operators/clickhouse/0.24.1/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.1/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.1/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.24.1/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.1/metadata/annotations.yaml

operator clickhouse (0.24.1)

---

operators/apicurio-api-controller/0.0.1/bundle.Dockerfile
operators/apicurio-api-controller/0.0.1/manifests/apicurio-api-controller.clusterserviceversion.yaml
operators/apicurio-api-controller/0.0.1/manifests/registry.apicur.io_apicurioregistries3.yaml
operators/apicurio-api-controller/0.0.1/metadata/annotations.yaml
operators/apicurio-api-controller/ci.yaml

operator [N] [CI] apicurio-api-controller (0.0.1)

---

operators/hawtio-operator/1.2.0/manifests/hawt.io_hawtios.yaml
operators/hawtio-operator/1.2.0/manifests/hawtio-operator.clusterserviceversion.yaml
operators/hawtio-operator/1.2.0/metadata/annotations.yaml
operators/hawtio-operator/1.2.0/tests/scorecard/config.yaml

operator hawtio-operator (1.2.0)

---

operators/external-secrets-operator/0.11.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
operators/external-secrets-operator/0.11.0/manifests/external-secrets-operator.clusterserviceversion.yaml
operators/external-secrets-operator/0.11.0/manifests/external-secrets.io_clusterexternalsecrets.yaml
operators/external-secrets-operator/0.11.0/manifests/external-secrets.io_clustersecretstores.yaml
operators/external-secrets-operator/0.11.0/manifests/external-secrets.io_externalsecrets.yaml
operators/external-secrets-operator/0.11.0/manifests/external-secrets.io_pushsecrets.yaml
operators/external-secrets-operator/0.11.0/manifests/external-secrets.io_secretstores.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_acraccesstokens.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_clustergenerators.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_fakes.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_gcraccesstokens.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_githubaccesstokens.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_passwords.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_stssessiontokens.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_uuids.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_webhooks.yaml
operators/external-secrets-operator/0.11.0/manifests/operator.external-secrets.io_operatorconfigs.yaml
operators/external-secrets-operator/0.11.0/metadata/annotations.yaml
operators/external-secrets-operator/0.11.0/tests/scorecard/config.yaml

bump external-secrets-operator 0.11.0

operator external-secrets-operator (0.11.0)

---

operators/clickhouse/0.24.2/manifests/clickhouse-operator.v0.24.2.clusterserviceversion.yaml
operators/clickhouse/0.24.2/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.2/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.2/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.24.2/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.2/metadata/annotations.yaml

operator clickhouse (0.24.2)

---

operators/dynatrace-operator/1.4.0/Dockerfile
operators/dynatrace-operator/1.4.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-collector_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_role.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-controller_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-logmonitoring_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-logmonitoring_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-node-config-collector_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.4.0/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.4.0/manifests/install-config_v1_configmap.yaml
operators/dynatrace-operator/1.4.0/metadata/annotations.yaml

operator dynatrace-operator (1.4.0)

---

operators/gitlab-operator-kubernetes/1.7.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.7.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.7.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.7.2)

---

operators/infinispan/2.4.7/manifests/infinispan-operator-manager-config_v1_configmap.yaml
operators/infinispan/2.4.7/manifests/infinispan-operator.clusterserviceversion.yaml
operators/infinispan/2.4.7/manifests/infinispan.org_backups.yaml
operators/infinispan/2.4.7/manifests/infinispan.org_batches.yaml
operators/infinispan/2.4.7/manifests/infinispan.org_caches.yaml
operators/infinispan/2.4.7/manifests/infinispan.org_infinispans.yaml
operators/infinispan/2.4.7/manifests/infinispan.org_restores.yaml
operators/infinispan/2.4.7/metadata/annotations.yaml
operators/infinispan/2.4.7/tests/scorecard/config.yaml

operator infinispan (2.4.7)

---

operators/nri-plugins-operator/0.8.0/manifests/config.nri_balloonspolicies.yaml
operators/nri-plugins-operator/0.8.0/manifests/config.nri_nriplugindeployments.yaml
operators/nri-plugins-operator/0.8.0/manifests/config.nri_templatepolicies.yaml
operators/nri-plugins-operator/0.8.0/manifests/config.nri_topologyawarepolicies.yaml
operators/nri-plugins-operator/0.8.0/manifests/nri-plugins-operator-controller-manager-metrics-service_v1_service.yaml
operators/nri-plugins-operator/0.8.0/manifests/nri-plugins-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nri-plugins-operator/0.8.0/manifests/nri-plugins-operator.clusterserviceversion.yaml
operators/nri-plugins-operator/0.8.0/manifests/topology.node.k8s.io_noderesourcetopologies.yaml
operators/nri-plugins-operator/0.8.0/metadata/annotations.yaml
operators/nri-plugins-operator/0.8.0/tests/scorecard/config.yaml

Submit nri-plugins-operator ([0.8.0](https://github.com/containers/nri-plugins/releases/tag/v0.8.0)) version.

operator nri-plugins-operator (0.8.0)

---

operators/elastic-cloud-eck/2.16.0/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.0/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.0/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.0/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.16.0/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.0/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.0/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.0/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.0/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.0/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.0/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.0/metadata/annotations.yaml

Update the ECK operator to the latest version `2.16.0`.

operator elastic-cloud-eck (2.16.0)

---

operators/project-quay/3.10.7/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.7/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.7/metadata/annotations.yaml

Add 3.10.7 to community operators

operator project-quay (3.10.7)

---

operators/eginnovations-operator/0.0.9/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml
operators/eginnovations-operator/0.0.9/manifests/eginnovations-operator-eguniversalagent-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/eginnovations-operator/0.0.9/manifests/eginnovations-operator-eguniversalagent-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/eginnovations-operator/0.0.9/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/eginnovations-operator/0.0.9/manifests/eginnovations-operator-webhook-service_v1_service.yaml
operators/eginnovations-operator/0.0.9/manifests/eginnovations-operator.clusterserviceversion.yaml
operators/eginnovations-operator/0.0.9/manifests/eginnovations.com_eguniversalagents.yaml
operators/eginnovations-operator/0.0.9/metadata/annotations.yaml
operators/eginnovations-operator/0.0.9/tests/scorecard/config.yaml

operator eginnovations-operator (0.0.9)

---

operators/project-quay/3.13.2/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.13.2/manifests/quayregistries.crd.yaml
operators/project-quay/3.13.2/metadata/annotations.yaml

Add 3.13.2 to community operators

operator project-quay (3.13.2)

---

operators/project-quay/3.9.9/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.9/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.9/metadata/annotations.yaml

Add 3.9.9 to community operators

operator project-quay (3.9.9)

---

operators/infinispan/2.4.8/manifests/infinispan-operator-manager-config_v1_configmap.yaml
operators/infinispan/2.4.8/manifests/infinispan-operator.clusterserviceversion.yaml
operators/infinispan/2.4.8/manifests/infinispan.org_backups.yaml
operators/infinispan/2.4.8/manifests/infinispan.org_batches.yaml
operators/infinispan/2.4.8/manifests/infinispan.org_caches.yaml
operators/infinispan/2.4.8/manifests/infinispan.org_infinispans.yaml
operators/infinispan/2.4.8/manifests/infinispan.org_restores.yaml
operators/infinispan/2.4.8/metadata/annotations.yaml
operators/infinispan/2.4.8/tests/scorecard/config.yaml

operator infinispan (2.4.8)

---

operators/gitlab-operator-kubernetes/1.8.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.8.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.8.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.8.0)

---

operators/verticadb-operator/25.1.0-0/manifests/vertica.com_eventtriggers.yaml
operators/verticadb-operator/25.1.0-0/manifests/vertica.com_verticaautoscalers.yaml
operators/verticadb-operator/25.1.0-0/manifests/vertica.com_verticadbs.yaml
operators/verticadb-operator/25.1.0-0/manifests/vertica.com_verticareplicators.yaml
operators/verticadb-operator/25.1.0-0/manifests/vertica.com_verticarestorepointsqueries.yaml
operators/verticadb-operator/25.1.0-0/manifests/vertica.com_verticascrutinizers.yaml
operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator-metrics-service_v1_service.yaml
operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator-webhook-service_v1_service.yaml
operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator.clusterserviceversion.yaml
operators/verticadb-operator/25.1.0-0/metadata/annotations.yaml
operators/verticadb-operator/25.1.0-0/tests/scorecard/config.yaml
operators/verticadb-operator/ci.yaml

operator [CI] verticadb-operator (25.1.0-0)

---

operators/project-quay/3.12.6/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.6/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.6/metadata/annotations.yaml

Add 3.12.6 to community operators

operator project-quay (3.12.6)

---

operators/aerospike-kubernetes-operator/3.4.1/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml

operator [O] aerospike-kubernetes-operator (3.4.1)

---

operators/mongodb-enterprise/1.30.0/bundle.Dockerfile
operators/mongodb-enterprise/1.30.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.30.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.30.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.30.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.30.0/manifests/mongodb-enterprise-operator-service_v1_service.yaml
operators/mongodb-enterprise/1.30.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.30.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.30.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.30.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.30.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.30.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.30.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.30.0/tests/scorecard/config.yaml
operators/mongodb-enterprise/ci.yaml

operator [CI] mongodb-enterprise (1.30.0)

---

operators/quay-api-operator/1.1.1/manifests/quay-api-operator-controller-manager-metrics-service_v1_service.yaml
operators/quay-api-operator/1.1.1/manifests/quay-api-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/quay-api-operator/1.1.1/manifests/quay-api-operator.clusterserviceversion.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_apitokens.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_applications.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_defaultperms.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_dockertokens.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_firstusers.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_manifestlabels.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_messages.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_notifications.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_organizationprunes.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_organizations.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_proxycaches.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_quotas.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_repositories.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_repositorymirrors.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_repositoryprunes.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_robots.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_tags.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_teamldaps.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_teamoidcs.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_teams.yaml
operators/quay-api-operator/1.1.1/manifests/quay.herve4m.github.io_users.yaml
operators/quay-api-operator/1.1.1/metadata/annotations.yaml
operators/quay-api-operator/1.1.1/tests/scorecard/config.yaml

operator quay-api-operator (1.1.1)

---

operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexusblobstores.yaml
operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexuscleanuppolicies.yaml
operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexuses.yaml
operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexusrepositories.yaml
operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexusroles.yaml
operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexusscripts.yaml
operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexususers.yaml
operators/nexus-operator/3.3.0/manifests/nexus-operator-webhook-service_v1_service.yaml
operators/nexus-operator/3.3.0/manifests/nexus-operator.clusterserviceversion.yaml
operators/nexus-operator/3.3.0/metadata/annotations.yaml
operators/nexus-operator/3.3.0/tests/scorecard/config.yaml

operator nexus-operator (3.3.0)

---

operators/gitlab-operator-kubernetes/1.8.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.8.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.8.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.8.1)

---

operators/layer7-operator/1.1.1/manifests/layer7-operator-controller-manager-metrics-service_v1_service.yaml
operators/layer7-operator/1.1.1/manifests/layer7-operator-manager-config_v1_configmap.yaml
operators/layer7-operator/1.1.1/manifests/layer7-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/layer7-operator/1.1.1/manifests/layer7-operator-webhook-service_v1_service.yaml
operators/layer7-operator/1.1.1/manifests/layer7-operator.clusterserviceversion.yaml
operators/layer7-operator/1.1.1/manifests/security.brcmlabs.com_gateways.yaml
operators/layer7-operator/1.1.1/manifests/security.brcmlabs.com_l7apis.yaml
operators/layer7-operator/1.1.1/manifests/security.brcmlabs.com_l7portals.yaml
operators/layer7-operator/1.1.1/manifests/security.brcmlabs.com_repositories.yaml
operators/layer7-operator/1.1.1/metadata/annotations.yaml
operators/layer7-operator/1.1.1/tests/scorecard/config.yaml

operator [R] layer7-operator (1.1.1)

---

operators/percona-xtradb-cluster-operator/1.16.0/manifests/percona-xtradb-cluster-operator.v1.16.0.clusterserviceversion.yaml
operators/percona-xtradb-cluster-operator/1.16.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.16.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.16.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.16.0/metadata/annotations.yaml
operators/percona-xtradb-cluster-operator/ci.yaml

operator [CI] percona-xtradb-cluster-operator (1.16.0)

---

operators/percona-xtradb-cluster-operator/1.16.1/manifests/percona-xtradb-cluster-operator.v1.16.1.clusterserviceversion.yaml
operators/percona-xtradb-cluster-operator/1.16.1/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.16.1/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.16.1/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.16.1/metadata/annotations.yaml

operator percona-xtradb-cluster-operator (1.16.1)

---

operators/gitlab-operator-kubernetes/1.8.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.8.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.8.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.8.2)

---

operators/lbconfig-operator/0.5.1/manifests/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml
operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator-controller-manager-metrics-service_v1_service.yaml
operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator-externalloadbalancer-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator-externalloadbalancer-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator-manager-config_v1_configmap.yaml
operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator.clusterserviceversion.yaml
operators/lbconfig-operator/0.5.1/metadata/annotations.yaml
operators/lbconfig-operator/0.5.1/tests/scorecard/config.yaml
operators/lbconfig-operator/0.5.1/tests/scorecard/kuttl/create-externalloadbalancer/01-assert.yaml
operators/lbconfig-operator/0.5.1/tests/scorecard/kuttl/create-externalloadbalancer/10-create-elb.yaml
operators/lbconfig-operator/0.5.1/tests/scorecard/kuttl/create-externalloadbalancer/11-assert.yaml
operators/lbconfig-operator/0.5.1/tests/scorecard/kuttl/kuttl-test.yaml

operator lbconfig-operator (0.5.1)

---

operators/skupper-operator/1.8.3/manifests/skupper-operator.v1.8.3.clusterserviceversion.yaml
operators/skupper-operator/1.8.3/metadata/annotations.yaml

operator skupper-operator (1.8.3)

---

operators/gitlab-operator-kubernetes/1.8.3/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.8.3/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.8.3/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.8.3)

---

operators/grafana-operator/5.16.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.16.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.16.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.16.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafananotificationtemplates.yaml
operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.16.0/metadata/annotations.yaml

operator grafana-operator (5.16.0)

---

operators/gitlab-operator-kubernetes/1.9.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.9.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.9.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.9.0)

---

operators/susql-operator/0.0.33/manifests/susql-operator-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.33/manifests/susql-operator-labelgroup-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.33/manifests/susql-operator-labelgroup-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.33/manifests/susql-operator-metrics-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.33/manifests/susql-operator-metrics-auth-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/susql-operator/0.0.33/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.33/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.33/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.33/metadata/annotations.yaml
operators/susql-operator/0.0.33/tests/scorecard/config.yaml

operator susql-operator (0.0.33)

---

operators/elastic-cloud-eck/2.16.1/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.1/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.1/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.1/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/2.16.1/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.1/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.1/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.1/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.1/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.1/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.1/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/2.16.1/metadata/annotations.yaml

Update the ECK operator to the latest version `2.16.1`.

operator elastic-cloud-eck (2.16.1)

---

operators/project-quay/3.13.3/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.13.3/manifests/quayregistries.crd.yaml
operators/project-quay/3.13.3/metadata/annotations.yaml

Add 3.13.3 to community operators

operator project-quay (3.13.3)

---

operators/gitlab-operator-kubernetes/1.9.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.9.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.9.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.9.1)

---

operators/percona-server-mongodb-operator/1.19.0/manifests/percona-server-mongodb-operator.clusterserviceversion.yaml
operators/percona-server-mongodb-operator/1.19.0/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.19.0/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.19.0/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.19.0/metadata/annotations.yaml

operator percona-server-mongodb-operator (1.19.0)

---

operators/cc-operator/0.12.0/manifests/cc-operator-controller-manager-metrics-service_v1_service.yaml
operators/cc-operator/0.12.0/manifests/cc-operator-manager-config_v1_configmap.yaml
operators/cc-operator/0.12.0/manifests/cc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cc-operator/0.12.0/manifests/cc-operator.clusterserviceversion.yaml
operators/cc-operator/0.12.0/manifests/confidentialcontainers.org_ccruntimes.yaml
operators/cc-operator/0.12.0/metadata/annotations.yaml
operators/cc-operator/0.12.0/tests/scorecard/config.yaml

operator cc-operator (0.12.0)

---

operators/knative-operator/1.17.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.17.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.17.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.17.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.17.0/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.17.0/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.17.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.17.0/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.17.0/manifests/knative-operator.v1.17.0.clusterserviceversion.yaml
operators/knative-operator/1.17.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.17.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.17.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.17.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.17.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.17.0/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.17.0/metadata/annotations.yaml
operators/knative-operator/1.17.0/tests/scorecard/config.yaml

operator knative-operator (1.17.0)

---

operators/mariadb-operator/0.37.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/0.37.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.37.0/metadata/annotations.yaml
operators/mariadb-operator/0.37.0/tests/scorecard/config.yaml

Added operator mariadb-operator (0.37.0)

operator mariadb-operator (0.37.0)

---

operators/mariadb-operator/0.37.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/0.37.1/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.37.1/metadata/annotations.yaml
operators/mariadb-operator/0.37.1/tests/scorecard/config.yaml

Added operator mariadb-operator (0.37.1)

operator mariadb-operator (0.37.1)

---

operators/ndmspc-operator/0.20250131.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.20250131.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.20250131.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.20250131.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.20250131.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.20250131.0/metadata/annotations.yaml
operators/ndmspc-operator/0.20250131.0/tests/scorecard/config.yaml
operators/ndmspc-operator/ci.yaml

operator [CI] ndmspc-operator (0.20250131.0)

---

operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml
operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator-eguniversalagent-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator-eguniversalagent-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator-webhook-service_v1_service.yaml
operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator.clusterserviceversion.yaml
operators/eginnovations-operator/0.0.10/manifests/eginnovations.com_eguniversalagents.yaml
operators/eginnovations-operator/0.0.10/metadata/annotations.yaml
operators/eginnovations-operator/0.0.10/tests/scorecard/config.yaml

operator eginnovations-operator (0.0.10)

---

operators/oracle-database-operator/1.1.0/manifests/oracle-database-operator.clusterserviceversion.yaml

operator [N] oracle-database-operator (1.1.0)

---

operators/mongodb-atlas-kubernetes/2.7.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlascustomroles.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.7.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.7.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.7.0/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.7.0)

---

operators/project-quay/3.11.8/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.11.8/manifests/quayregistries.crd.yaml
operators/project-quay/3.11.8/metadata/annotations.yaml

Add 3.11.8 to community operators

operator project-quay (3.11.8)

---

operators/edp-keycloak-operator/1.24.0/manifests/client-secret-authorization-sample_v1_secret.yaml
operators/edp-keycloak-operator/1.24.0/manifests/client-secret-policy-sample_v1_secret.yaml
operators/edp-keycloak-operator/1.24.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.24.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.24.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.24.0/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.24.0)

---

operators/project-quay/3.10.8/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.8/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.8/metadata/annotations.yaml

Add 3.10.8 to community operators

operator project-quay (3.10.8)

---

operators/camel-k/2.5.1/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.5.1/manifests/camel-k.v2.5.1.clusterserviceversion.yaml
operators/camel-k/2.5.1/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.5.1/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.5.1/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.5.1/manifests/integrationprofiles.camel.apache.org.crd.yaml
operators/camel-k/2.5.1/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.5.1/manifests/kameletbindings.camel.apache.org.crd.yaml
operators/camel-k/2.5.1/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.5.1/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.5.1/metadata/annotations.yaml
operators/camel-k/2.5.1/tests/scorecard/config.yaml

operator camel-k (2.5.1)

---

operators/ndmspc-operator/0.20250209.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.20250209.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.20250209.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.20250209.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.20250209.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.20250209.0/metadata/annotations.yaml
operators/ndmspc-operator/0.20250209.0/metadata/dependency.yaml
operators/ndmspc-operator/0.20250209.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.20250209.0)

---

operators/mongodb-enterprise/1.31.0/bundle.Dockerfile
operators/mongodb-enterprise/1.31.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.31.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.31.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.31.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.31.0/manifests/mongodb-enterprise-operator-service_v1_service.yaml
operators/mongodb-enterprise/1.31.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.31.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.31.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.31.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.31.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.31.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.31.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.31.0/tests/scorecard/config.yaml
operators/mongodb-enterprise/ci.yaml

operator [CI] mongodb-enterprise (1.31.0)

---

operators/kubearmor-operator/1.5.2/bundle.Dockerfile
operators/kubearmor-operator/1.5.2/manifests/kubearmor-operator.clusterserviceversion.yaml
operators/kubearmor-operator/1.5.2/manifests/operator.kubearmor.com_kubearmorconfigs.yaml
operators/kubearmor-operator/1.5.2/metadata/annotations.yaml

operator [N] kubearmor-operator (1.5.2)

---

operators/intel-device-plugins-operator/0.32.0/bundle.Dockerfile
operators/intel-device-plugins-operator/0.32.0/manifests/deviceplugin.intel.com_dlbdeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.0/manifests/deviceplugin.intel.com_dsadeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.0/manifests/deviceplugin.intel.com_fpgadeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.0/manifests/deviceplugin.intel.com_gpudeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.0/manifests/deviceplugin.intel.com_iaadeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.0/manifests/deviceplugin.intel.com_qatdeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.0/manifests/deviceplugin.intel.com_sgxdeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.0/manifests/fpga.intel.com_acceleratorfunctions.yaml
operators/intel-device-plugins-operator/0.32.0/manifests/fpga.intel.com_fpgaregions.yaml
operators/intel-device-plugins-operator/0.32.0/manifests/intel-device-plugins-operator.clusterserviceversion.yaml
operators/intel-device-plugins-operator/0.32.0/metadata/annotations.yaml

operator intel-device-plugins-operator (0.32.0)

---

operators/gitlab-operator-kubernetes/1.9.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.9.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.9.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.9.2)

---

operators/dynatrace-operator/1.4.1/Dockerfile
operators/dynatrace-operator/1.4.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-collector_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_role.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-controller_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-logmonitoring_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-logmonitoring_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-node-config-collector_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.4.1/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.4.1/metadata/annotations.yaml

operator dynatrace-operator (1.4.1)

---

operators/accuknox-operator/0.7.1/manifests/accuknox-operator.clusterserviceversion.yaml
operators/accuknox-operator/0.7.1/manifests/operator.accuknox.com_accuknoxconfigs.yaml
operators/accuknox-operator/0.7.1/metadata/annotations.yaml

operator [N] accuknox-operator (0.7.1)

---

operators/cass-operator-community/1.23.0/manifests/cass-operator-manager-config_v1_configmap.yaml
operators/cass-operator-community/1.23.0/manifests/cass-operator-webhook-service_v1_service.yaml
operators/cass-operator-community/1.23.0/manifests/cass-operator.clusterserviceversion.yaml
operators/cass-operator-community/1.23.0/manifests/cassandra.datastax.com_cassandradatacenters.yaml
operators/cass-operator-community/1.23.0/manifests/control.k8ssandra.io_cassandratasks.yaml
operators/cass-operator-community/1.23.0/metadata/annotations.yaml
operators/cass-operator-community/1.23.0/tests/scorecard/config.yaml

operator cass-operator-community (1.23.0)

---

operators/mongodb-atlas-kubernetes/2.7.1/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlascustomroles.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.7.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.7.1/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.7.1/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.7.1)

---

operators/trustee-operator/0.3.0/manifests/confidentialcontainers.org_kbsconfigs.yaml
operators/trustee-operator/0.3.0/manifests/trustee-operator-controller-manager-metrics-service_v1_service.yaml
operators/trustee-operator/0.3.0/manifests/trustee-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/trustee-operator/0.3.0/manifests/trustee-operator.clusterserviceversion.yaml
operators/trustee-operator/0.3.0/metadata/annotations.yaml
operators/trustee-operator/0.3.0/tests/scorecard/config.yaml

This new operator version supports trustee v0.11.0

operator trustee-operator (0.3.0)

---

operators/camel-k/2.6.0/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.6.0/manifests/camel-k.v2.6.0.clusterserviceversion.yaml
operators/camel-k/2.6.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.6.0/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.6.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.6.0/manifests/integrationprofiles.camel.apache.org.crd.yaml
operators/camel-k/2.6.0/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.6.0/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.6.0/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.6.0/metadata/annotations.yaml
operators/camel-k/2.6.0/tests/scorecard/config.yaml

operator camel-k (2.6.0)

---

operators/flux-operator/0.14.0/manifests/flux-operator.clusterserviceversion.yaml
operators/flux-operator/0.14.0/manifests/fluxinstances.fluxcd.controlplane.io.crd.yaml
operators/flux-operator/0.14.0/manifests/fluxreports.fluxcd.controlplane.io.crd.yaml
operators/flux-operator/0.14.0/manifests/resourcesetinputproviders.fluxcd.controlplane.io.crd.yaml
operators/flux-operator/0.14.0/manifests/resourcesets.fluxcd.controlplane.io.crd.yaml
operators/flux-operator/0.14.0/metadata/annotations.yaml
operators/flux-operator/0.14.0/tests/scorecard/config.yaml

operator flux-operator (0.14.0)

---

operators/clickhouse/0.24.3/manifests/clickhouse-operator.v0.24.3.clusterserviceversion.yaml
operators/clickhouse/0.24.3/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.3/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.3/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.24.3/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.3/metadata/annotations.yaml

operator clickhouse (0.24.3)

---

operators/tempo-operator/0.15.0/bundle.Dockerfile
operators/tempo-operator/0.15.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.15.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.15.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.15.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.15.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.15.0/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.15.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.15.0/metadata/annotations.yaml
operators/tempo-operator/0.15.0/tests/scorecard/config.yaml

Release tempo-operator `0.15.0`.

operator tempo-operator (0.15.0)

---

operators/tempo-operator/0.15.1/bundle.Dockerfile
operators/tempo-operator/0.15.1/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.15.1/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.15.1/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.15.1/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.15.1/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.15.1/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.15.1/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.15.1/metadata/annotations.yaml
operators/tempo-operator/0.15.1/tests/scorecard/config.yaml

Release tempo-operator `0.15.1`.

operator tempo-operator (0.15.1)

---

operators/perses-operator/0.1.1/manifests/perses-operator-controller-manager-metrics-service_v1_service.yaml
operators/perses-operator/0.1.1/manifests/perses-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/perses-operator/0.1.1/manifests/perses-operator.clusterserviceversion.yaml
operators/perses-operator/0.1.1/manifests/perses.dev_perses.yaml
operators/perses-operator/0.1.1/manifests/perses.dev_persesdashboards.yaml
operators/perses-operator/0.1.1/manifests/perses.dev_persesdatasources.yaml
operators/perses-operator/0.1.1/metadata/annotations.yaml
operators/perses-operator/0.1.1/tests/scorecard/config.yaml
operators/perses-operator/ci.yaml

operator [N] [CI] perses-operator (0.1.1)

---

operators/gitlab-operator-kubernetes/1.10.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.10.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.10.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.10.0)

---

operators/clickhouse/0.24.4/manifests/clickhouse-operator.v0.24.4.clusterserviceversion.yaml
operators/clickhouse/0.24.4/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.4/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.4/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.24.4/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.4/metadata/annotations.yaml

operator clickhouse (0.24.4)

---

operators/percona-server-mongodb-operator/1.19.1/manifests/percona-server-mongodb-operator.clusterserviceversion.yaml
operators/percona-server-mongodb-operator/1.19.1/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.19.1/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.19.1/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.19.1/metadata/annotations.yaml

operator percona-server-mongodb-operator (1.19.1)

---

operators/tempo-operator/0.15.2/bundle.Dockerfile
operators/tempo-operator/0.15.2/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.15.2/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.15.2/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.15.2/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.15.2/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.15.2/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.15.2/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.15.2/metadata/annotations.yaml
operators/tempo-operator/0.15.2/tests/scorecard/config.yaml

Release tempo-operator `0.15.2`.

operator tempo-operator (0.15.2)

---

operators/gitlab-operator-kubernetes/1.10.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.10.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.10.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.10.1)

---

operators/tempo-operator/0.15.3/bundle.Dockerfile
operators/tempo-operator/0.15.3/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.15.3/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.15.3/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.15.3/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.15.3/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.15.3/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.15.3/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.15.3/metadata/annotations.yaml
operators/tempo-operator/0.15.3/tests/scorecard/config.yaml

Release tempo-operator `0.15.3`.

operator tempo-operator (0.15.3)

---

operators/cloudnative-pg/1.25.1/manifests/cloudnative-pg.clusterserviceversion.yaml
operators/cloudnative-pg/1.25.1/manifests/cnpg-database-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cloudnative-pg/1.25.1/manifests/cnpg-database-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cloudnative-pg/1.25.1/manifests/cnpg-default-monitoring_v1_configmap.yaml
operators/cloudnative-pg/1.25.1/manifests/cnpg-publication-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cloudnative-pg/1.25.1/manifests/cnpg-publication-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cloudnative-pg/1.25.1/manifests/cnpg-subscription-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cloudnative-pg/1.25.1/manifests/cnpg-subscription-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cloudnative-pg/1.25.1/manifests/cnpg-webhook-service_v1_service.yaml
operators/cloudnative-pg/1.25.1/manifests/postgresql.cnpg.io_backups.yaml
operators/cloudnative-pg/1.25.1/manifests/postgresql.cnpg.io_clusterimagecatalogs.yaml
operators/cloudnative-pg/1.25.1/manifests/postgresql.cnpg.io_clusters.yaml
operators/cloudnative-pg/1.25.1/manifests/postgresql.cnpg.io_databases.yaml
operators/cloudnative-pg/1.25.1/manifests/postgresql.cnpg.io_imagecatalogs.yaml
operators/cloudnative-pg/1.25.1/manifests/postgresql.cnpg.io_poolers.yaml
operators/cloudnative-pg/1.25.1/manifests/postgresql.cnpg.io_publications.yaml
operators/cloudnative-pg/1.25.1/manifests/postgresql.cnpg.io_scheduledbackups.yaml
operators/cloudnative-pg/1.25.1/manifests/postgresql.cnpg.io_subscriptions.yaml
operators/cloudnative-pg/1.25.1/metadata/annotations.yaml
operators/cloudnative-pg/1.25.1/tests/scorecard/config.yaml

operator cloudnative-pg (1.25.1)

---

operators/shipwright-operator/0.15.2/manifests/operator.shipwright.io_shipwrightbuilds.yaml
operators/shipwright-operator/0.15.2/manifests/shipwright-operator-manager-config_v1_configmap.yaml
operators/shipwright-operator/0.15.2/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/shipwright-operator/0.15.2/manifests/shipwright-operator-metrics-service_v1_service.yaml
operators/shipwright-operator/0.15.2/manifests/shipwright-operator.clusterserviceversion.yaml
operators/shipwright-operator/0.15.2/metadata/annotations.yaml
operators/shipwright-operator/0.15.2/tests/scorecard/config.yaml

operator shipwright-operator (0.15.2)

---

operators/galaxy-operator/2024.5.8/manifests/galaxy-operator-controller-manager-metrics-service_v1_service.yaml
operators/galaxy-operator/2024.5.8/manifests/galaxy-operator-galaxy-operator-config_v1_configmap.yaml
operators/galaxy-operator/2024.5.8/manifests/galaxy-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/galaxy-operator/2024.5.8/manifests/galaxy-operator.clusterserviceversion.yaml
operators/galaxy-operator/2024.5.8/manifests/galaxy.ansible.com_galaxies.yaml
operators/galaxy-operator/2024.5.8/manifests/galaxy.ansible.com_galaxybackups.yaml
operators/galaxy-operator/2024.5.8/manifests/galaxy.ansible.com_galaxyrestores.yaml
operators/galaxy-operator/2024.5.8/metadata/annotations.yaml
operators/galaxy-operator/2024.5.8/tests/scorecard/config.yaml
operators/galaxy-operator/ci.yaml

https://galaxy-operator.readthedocs.io/
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
-- …

operator [CI] galaxy-operator (2024.5.8)

---

operators/infinispan/2.4.11/manifests/infinispan-operator-manager-config_v1_configmap.yaml
operators/infinispan/2.4.11/manifests/infinispan-operator.clusterserviceversion.yaml
operators/infinispan/2.4.11/manifests/infinispan.org_backups.yaml
operators/infinispan/2.4.11/manifests/infinispan.org_batches.yaml
operators/infinispan/2.4.11/manifests/infinispan.org_caches.yaml
operators/infinispan/2.4.11/manifests/infinispan.org_infinispans.yaml
operators/infinispan/2.4.11/manifests/infinispan.org_restores.yaml
operators/infinispan/2.4.11/metadata/annotations.yaml
operators/infinispan/2.4.11/tests/scorecard/config.yaml

operator infinispan (2.4.11)

---

operators/project-quay/3.12.8/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.8/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.8/metadata/annotations.yaml

Add 3.12.8 to community operators

operator project-quay (3.12.8)

---

operators/project-quay/3.11.9/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.11.9/manifests/quayregistries.crd.yaml
operators/project-quay/3.11.9/metadata/annotations.yaml

Add 3.11.9 to community operators

operator project-quay (3.11.9)

---

operators/project-quay/3.10.9/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.9/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.9/metadata/annotations.yaml

Add 3.10.9 to community operators

operator project-quay (3.10.9)

---

operators/mongodb-atlas-kubernetes/2.8.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlascustomroles.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasnetworkcontainers.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasnetworkpeerings.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.8.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.8.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.8.0/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.8.0)

---

operators/trident-operator/24.10.1/manifests/trident-operator.v24.10.1.clusterserviceversion.yaml
operators/trident-operator/24.10.1/manifests/trident.netapp.io_tridentconfigurators_crd.yaml
operators/trident-operator/24.10.1/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
operators/trident-operator/24.10.1/metadata/annotations.yaml

operator trident-operator (24.10.1)

---

operators/move2kube-operator/0.3.15/bundle.Dockerfile
operators/move2kube-operator/0.3.15/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
operators/move2kube-operator/0.3.15/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/move2kube-operator/0.3.15/manifests/move2kube-operator.clusterserviceversion.yaml
operators/move2kube-operator/0.3.15/manifests/move2kube.konveyor.io_move2kubes.yaml
operators/move2kube-operator/0.3.15/metadata/annotations.yaml
operators/move2kube-operator/0.3.15/tests/scorecard/config.yaml

An automated PR to update move2kube-operator to v0.3.15

operator move2kube-operator (0.3.15)

---

operators/mongodb-enterprise/1.32.0/bundle.Dockerfile
operators/mongodb-enterprise/1.32.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-enterprise/1.32.0/manifests/mongodb-enterprise-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-enterprise/1.32.0/manifests/mongodb-enterprise-appdb_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.32.0/manifests/mongodb-enterprise-database-pods_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.32.0/manifests/mongodb-enterprise-operator-service_v1_service.yaml
operators/mongodb-enterprise/1.32.0/manifests/mongodb-enterprise-ops-manager_v1_serviceaccount.yaml
operators/mongodb-enterprise/1.32.0/manifests/mongodb-enterprise.clusterserviceversion.yaml
operators/mongodb-enterprise/1.32.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-enterprise/1.32.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-enterprise/1.32.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-enterprise/1.32.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-enterprise/1.32.0/metadata/annotations.yaml
operators/mongodb-enterprise/1.32.0/tests/scorecard/config.yaml

operator mongodb-enterprise (1.32.0)

---

operators/trident-operator/25.2.1/manifests/trident-operator.v25.2.1.clusterserviceversion.yaml
operators/trident-operator/25.2.1/manifests/trident.netapp.io_tridentconfigurators_crd.yaml
operators/trident-operator/25.2.1/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
operators/trident-operator/25.2.1/metadata/annotations.yaml

operator trident-operator (25.2.1)

---

operators/gitlab-operator-kubernetes/1.10.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.10.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.10.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.10.2)

---

operators/project-quay/3.9.10/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.10/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.10/metadata/annotations.yaml

Add 3.9.10 to community operators

operator project-quay (3.9.10)

---

operators/cass-operator-community/1.23.1/manifests/cass-operator-manager-config_v1_configmap.yaml
operators/cass-operator-community/1.23.1/manifests/cass-operator-webhook-service_v1_service.yaml
operators/cass-operator-community/1.23.1/manifests/cass-operator.clusterserviceversion.yaml
operators/cass-operator-community/1.23.1/manifests/cassandra.datastax.com_cassandradatacenters.yaml
operators/cass-operator-community/1.23.1/manifests/control.k8ssandra.io_cassandratasks.yaml
operators/cass-operator-community/1.23.1/metadata/annotations.yaml
operators/cass-operator-community/1.23.1/tests/scorecard/config.yaml

operator cass-operator-community (1.23.1)

---

operators/loki-operator/0.8.0/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
operators/loki-operator/0.8.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
operators/loki-operator/0.8.0/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/loki-operator/0.8.0/manifests/loki-operator-manager-config_v1_configmap.yaml
operators/loki-operator/0.8.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/loki-operator/0.8.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
operators/loki-operator/0.8.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/loki-operator/0.8.0/manifests/loki-operator-webhook-service_v1_service.yaml
operators/loki-operator/0.8.0/manifests/loki-operator.clusterserviceversion.yaml
operators/loki-operator/0.8.0/manifests/loki.grafana.com_alertingrules.yaml
operators/loki-operator/0.8.0/manifests/loki.grafana.com_lokistacks.yaml
operators/loki-operator/0.8.0/manifests/loki.grafana.com_recordingrules.yaml
operators/loki-operator/0.8.0/manifests/loki.grafana.com_rulerconfigs.yaml
operators/loki-operator/0.8.0/metadata/annotations.yaml
operators/loki-operator/0.8.0/tests/scorecard/config.yaml

operator loki-operator (0.8.0)

---

operators/edp-keycloak-operator/1.25.0/manifests/client-secret-authorization-sample_v1_secret.yaml
operators/edp-keycloak-operator/1.25.0/manifests/client-secret-policy-sample_v1_secret.yaml
operators/edp-keycloak-operator/1.25.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
operators/edp-keycloak-operator/1.25.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakclients.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloaks.yaml
operators/edp-keycloak-operator/1.25.0/metadata/annotations.yaml
operators/edp-keycloak-operator/1.25.0/tests/scorecard/config.yaml

operator edp-keycloak-operator (1.25.0)

---

operators/cass-operator-community/1.23.2/manifests/cass-operator-manager-config_v1_configmap.yaml
operators/cass-operator-community/1.23.2/manifests/cass-operator-webhook-service_v1_service.yaml
operators/cass-operator-community/1.23.2/manifests/cass-operator.clusterserviceversion.yaml
operators/cass-operator-community/1.23.2/manifests/cassandra.datastax.com_cassandradatacenters.yaml
operators/cass-operator-community/1.23.2/manifests/control.k8ssandra.io_cassandratasks.yaml
operators/cass-operator-community/1.23.2/metadata/annotations.yaml
operators/cass-operator-community/1.23.2/tests/scorecard/config.yaml

operator cass-operator-community (1.23.2)

---

operators/gitlab-operator-kubernetes/1.11.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.11.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.11.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.11.0)

---

operators/clickhouse/0.24.5/manifests/clickhouse-operator.v0.24.5.clusterserviceversion.yaml
operators/clickhouse/0.24.5/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.5/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.5/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.24.5/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.24.5/metadata/annotations.yaml

operator clickhouse (0.24.5)

---

operators/cluster-manager/0.16.0/manifests/cluster-manager.clusterserviceversion.yaml
operators/cluster-manager/0.16.0/manifests/operator.open-cluster-management.io_clustermanagers.yaml
operators/cluster-manager/0.16.0/metadata/annotations.yaml

operator cluster-manager (0.16.0)

---

operators/mariadb-operator/0.38.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/0.38.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.38.0/metadata/annotations.yaml
operators/mariadb-operator/0.38.0/tests/scorecard/config.yaml

Added operator mariadb-operator (0.38.0)

operator mariadb-operator (0.38.0)

---

operators/gitlab-operator-kubernetes/1.11.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.11.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.11.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.11.1)

---

operators/skupper-operator/1.8.4/manifests/skupper-operator.v1.8.4.clusterserviceversion.yaml
operators/skupper-operator/1.8.4/metadata/annotations.yaml

operator skupper-operator (1.8.4)

---

operators/nri-plugins-operator/0.9.3/manifests/config.nri_balloonspolicies.yaml
operators/nri-plugins-operator/0.9.3/manifests/config.nri_nriplugindeployments.yaml
operators/nri-plugins-operator/0.9.3/manifests/config.nri_templatepolicies.yaml
operators/nri-plugins-operator/0.9.3/manifests/config.nri_topologyawarepolicies.yaml
operators/nri-plugins-operator/0.9.3/manifests/nri-plugins-operator-controller-manager-metrics-service_v1_service.yaml
operators/nri-plugins-operator/0.9.3/manifests/nri-plugins-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nri-plugins-operator/0.9.3/manifests/nri-plugins-operator.clusterserviceversion.yaml
operators/nri-plugins-operator/0.9.3/manifests/topology.node.k8s.io_noderesourcetopologies.yaml
operators/nri-plugins-operator/0.9.3/metadata/annotations.yaml
operators/nri-plugins-operator/0.9.3/tests/scorecard/config.yaml

operator nri-plugins-operator ([0.9.3](https://github.com/containers/nri-plugins/releases/tag/v0.9.3))

operator nri-plugins-operator (0.9.3)

---

operators/gitlab-operator-kubernetes/1.11.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.11.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.11.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.11.2)

---

operators/project-quay/3.14.0/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.14.0/manifests/quayregistries.crd.yaml
operators/project-quay/3.14.0/metadata/annotations.yaml

Add 3.14.0 to community operators

operator project-quay (3.14.0)

---

operators/dynatrace-operator/1.4.2/Dockerfile
operators/dynatrace-operator/1.4.2/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-collector_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_role.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-controller_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-logmonitoring_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-logmonitoring_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-node-config-collector_v1_serviceaccount.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.4.2/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.4.2/metadata/annotations.yaml

operator dynatrace-operator (1.4.2)

---

operators/dell-csm-operator/1.8.1/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.8.1/manifests/dell-csm-operator.v1.8.1.clusterserviceversion.yaml
operators/dell-csm-operator/1.8.1/metadata/annotations.yaml
operators/dell-csm-operator/1.8.1/tests/scorecard/config.yaml
operators/dell-csm-operator/ci.yaml

This is a patch to dell-csm-operator 1.8.0. One of the images is updated along with the updated Operator image.
--

operator [CI] dell-csm-operator (1.8.1)

---

operators/skupper-operator/1.9.0/manifests/skupper-operator.v1.9.0.clusterserviceversion.yaml
operators/skupper-operator/1.9.0/metadata/annotations.yaml

operator skupper-operator (1.9.0)

---

operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_autonomouscontainerdatabases.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_autonomousdatabasebackups.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_autonomousdatabaserestores.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_autonomousdatabases.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_cdbs.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_dataguardbrokers.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_dbcssystems.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_lrests.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_lrpdbs.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_oraclerestdataservices.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_ordssrvs.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_pdbs.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_shardingdatabases.yaml
operators/oracle-database-operator/1.2.0/manifests/database.oracle.com_singleinstancedatabases.yaml
operators/oracle-database-operator/1.2.0/manifests/observability.oracle.com_databaseobservers.yaml
operators/oracle-database-operator/1.2.0/manifests/oracle-database-operator-controller-manager-metrics-service_v1_service.yaml
operators/oracle-database-operator/1.2.0/manifests/oracle-database-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/oracle-database-operator/1.2.0/manifests/oracle-database-operator-webhook-service_v1_service.yaml
operators/oracle-database-operator/1.2.0/manifests/oracle-database-operator.clusterserviceversion.yaml
operators/oracle-database-operator/1.2.0/metadata/annotations.yaml
operators/oracle-database-operator/ci.yaml

operator [CI] oracle-database-operator (1.2.0)

---

operators/grafana-operator/5.17.1/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.17.1/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.17.1/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.17.1/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanalibrarypanels.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanamutetimings.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafananotificationpolicyroutes.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafananotificationtemplates.yaml
operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.17.1/metadata/annotations.yaml

operator grafana-operator (5.17.1)

---

operators/ndb-operator/1.7.0/bundle.Dockerfile
operators/ndb-operator/1.7.0/manifests/mysql.oracle.com_ndbclusters.yaml
operators/ndb-operator/1.7.0/manifests/ndb-operator-svc_v1_service.yaml
operators/ndb-operator/1.7.0/manifests/ndb-operator-webhook-service_v1_service.yaml
operators/ndb-operator/1.7.0/manifests/ndb-operator.clusterserviceversion.yaml
operators/ndb-operator/1.7.0/metadata/annotations.yaml

operator ndb-operator (1.7.0)

---

operators/gitlab-operator-kubernetes/1.11.3/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.11.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.11.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.11.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.11.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.11.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.11.3/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.11.3/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.11.3/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.11.3/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.11.3)

---

operators/nri-plugins-operator/0.9.4/manifests/config.nri_balloonspolicies.yaml
operators/nri-plugins-operator/0.9.4/manifests/config.nri_nriplugindeployments.yaml
operators/nri-plugins-operator/0.9.4/manifests/config.nri_templatepolicies.yaml
operators/nri-plugins-operator/0.9.4/manifests/config.nri_topologyawarepolicies.yaml
operators/nri-plugins-operator/0.9.4/manifests/nri-plugins-operator-controller-manager-metrics-service_v1_service.yaml
operators/nri-plugins-operator/0.9.4/manifests/nri-plugins-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nri-plugins-operator/0.9.4/manifests/nri-plugins-operator.clusterserviceversion.yaml
operators/nri-plugins-operator/0.9.4/manifests/topology.node.k8s.io_noderesourcetopologies.yaml
operators/nri-plugins-operator/0.9.4/metadata/annotations.yaml
operators/nri-plugins-operator/0.9.4/tests/scorecard/config.yaml

operator nri-plugins-operator ([0.9.4](https://github.com/containers/nri-plugins/releases/tag/v0.9.4))

operator nri-plugins-operator (0.9.4)

---

operators/elastic-cloud-eck/3.0.0/manifests/agents.agent.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/3.0.0/manifests/apmservers.apm.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/3.0.0/manifests/beats.beat.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/3.0.0/manifests/elastic-cloud-eck.clusterserviceversion.yaml
operators/elastic-cloud-eck/3.0.0/manifests/elasticmapsservers.maps.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/3.0.0/manifests/elasticsearchautoscalers.autoscaling.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/3.0.0/manifests/elasticsearches.elasticsearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/3.0.0/manifests/enterprisesearches.enterprisesearch.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/3.0.0/manifests/kibanas.kibana.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/3.0.0/manifests/logstashes.logstash.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/3.0.0/manifests/stackconfigpolicies.stackconfigpolicy.k8s.elastic.co.crd.yaml
operators/elastic-cloud-eck/3.0.0/metadata/annotations.yaml

Update the ECK operator to the latest version `3.0.0`.

operator elastic-cloud-eck (3.0.0)

---

operators/mariadb-operator/0.38.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/0.38.1/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/0.38.1/metadata/annotations.yaml
operators/mariadb-operator/0.38.1/tests/scorecard/config.yaml

Added operator mariadb-operator (0.38.1)

operator mariadb-operator (0.38.1)

---

operators/percona-xtradb-cluster-operator/1.17.0/manifests/percona-xtradb-cluster-operator.v1.17.0.clusterserviceversion.yaml
operators/percona-xtradb-cluster-operator/1.17.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.17.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.17.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.17.0/metadata/annotations.yaml

operator percona-xtradb-cluster-operator (1.17.0)

---

operators/security-profiles-operator/0.9.1/manifests/metrics-token_v1_secret.yaml
operators/security-profiles-operator/0.9.1/manifests/security-profiles-operator-profile_v1_configmap.yaml
operators/security-profiles-operator/0.9.1/manifests/security-profiles-operator.clusterserviceversion.yaml
operators/security-profiles-operator/0.9.1/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
operators/security-profiles-operator/0.9.1/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
operators/security-profiles-operator/0.9.1/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
operators/security-profiles-operator/0.9.1/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
operators/security-profiles-operator/0.9.1/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
operators/security-profiles-operator/0.9.1/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
operators/security-profiles-operator/0.9.1/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
operators/security-profiles-operator/0.9.1/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
operators/security-profiles-operator/0.9.1/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.9.1/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.9.1/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.9.1/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.9.1/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.9.1/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.9.1/manifests/spo-webhook_v1_serviceaccount.yaml
operators/security-profiles-operator/0.9.1/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/security-profiles-operator/0.9.1/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/security-profiles-operator/0.9.1/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
operators/security-profiles-operator/0.9.1/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/security-profiles-operator/0.9.1/manifests/spod_v1_serviceaccount.yaml
operators/security-profiles-operator/0.9.1/metadata/annotations.yaml
operators/security-profiles-operator/0.9.1/tests/scorecard/config.yaml

operator security-profiles-operator (0.9.1)

---

operators/keda/2.16.1/manifests/eventing.keda.sh_cloudeventsources.yaml
operators/keda/2.16.1/manifests/eventing.keda.sh_clustercloudeventsources.yaml
operators/keda/2.16.1/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.16.1/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.16.1/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.16.1/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.16.1/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.16.1/manifests/keda.v2.16.1.clusterserviceversion.yaml
operators/keda/2.16.1/metadata/annotations.yaml

operator keda (2.16.1)

---

operators/keda/2.17.0/manifests/eventing.keda.sh_cloudeventsources.yaml
operators/keda/2.17.0/manifests/eventing.keda.sh_clustercloudeventsources.yaml
operators/keda/2.17.0/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.17.0/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.17.0/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.17.0/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.17.0/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.17.0/manifests/keda.v2.17.0.clusterserviceversion.yaml
operators/keda/2.17.0/metadata/annotations.yaml

operator keda (2.17.0)

---

operators/gitlab-operator-kubernetes/1.12.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.12.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.12.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.12.0)

---

operators/tektoncd-operator/0.75.0/manifests/config-logging_v1_configmap.yaml
operators/tektoncd-operator/0.75.0/manifests/operator.tekton.dev_manualapprovalgates.yaml
operators/tektoncd-operator/0.75.0/manifests/operator.tekton.dev_tektonchains.yaml
operators/tektoncd-operator/0.75.0/manifests/operator.tekton.dev_tektonconfigs.yaml
operators/tektoncd-operator/0.75.0/manifests/operator.tekton.dev_tektondashboards.yaml
operators/tektoncd-operator/0.75.0/manifests/operator.tekton.dev_tektonhubs.yaml
operators/tektoncd-operator/0.75.0/manifests/operator.tekton.dev_tektoninstallersets.yaml
operators/tektoncd-operator/0.75.0/manifests/operator.tekton.dev_tektonpipelines.yaml
operators/tektoncd-operator/0.75.0/manifests/operator.tekton.dev_tektonresults.yaml
operators/tektoncd-operator/0.75.0/manifests/operator.tekton.dev_tektontriggers.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-config-defaults_v1_configmap.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-config-observability_v1_configmap.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-config-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-config-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-operator-controller-config-leader-election_v1_configmap.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_role.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-operator-info_v1_configmap.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-operator-webhook-certs_v1_secret.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-operator-webhook-config-leader-election_v1_configmap.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-operator-webhook_v1_service.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-operator_v1_service.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-result-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tektoncd-operator/0.75.0/manifests/tekton-result-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/tektoncd-operator/0.75.0/manifests/tektoncd-operator.clusterserviceversion.yaml
operators/tektoncd-operator/0.75.0/metadata/annotations.yaml
operators/tektoncd-operator/0.75.0/tests/scorecard/config.yaml

operator tektoncd-operator (0.75.0)

---

operators/ndb-operator/1.8.0/bundle.Dockerfile
operators/ndb-operator/1.8.0/manifests/mysql.oracle.com_ndbclusters.yaml
operators/ndb-operator/1.8.0/manifests/ndb-operator-svc_v1_service.yaml
operators/ndb-operator/1.8.0/manifests/ndb-operator-webhook-service_v1_service.yaml
operators/ndb-operator/1.8.0/manifests/ndb-operator.clusterserviceversion.yaml
operators/ndb-operator/1.8.0/metadata/annotations.yaml

operator ndb-operator (1.8.0)

---

operators/infinispan/2.4.12/manifests/infinispan-operator-manager-config_v1_configmap.yaml
operators/infinispan/2.4.12/manifests/infinispan-operator.clusterserviceversion.yaml
operators/infinispan/2.4.12/manifests/infinispan.org_backups.yaml
operators/infinispan/2.4.12/manifests/infinispan.org_batches.yaml
operators/infinispan/2.4.12/manifests/infinispan.org_caches.yaml
operators/infinispan/2.4.12/manifests/infinispan.org_infinispans.yaml
operators/infinispan/2.4.12/manifests/infinispan.org_restores.yaml
operators/infinispan/2.4.12/metadata/annotations.yaml
operators/infinispan/2.4.12/tests/scorecard/config.yaml

operator infinispan (2.4.12)

---

operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonargroups.yaml
operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonarpermissiontemplates.yaml
operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonarqualitygates.yaml
operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonarqualityprofiles.yaml
operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonars.yaml
operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonarusers.yaml
operators/sonar-operator/3.2.0/manifests/sonar-operator.clusterserviceversion.yaml
operators/sonar-operator/3.2.0/metadata/annotations.yaml
operators/sonar-operator/3.2.0/tests/scorecard/config.yaml

operator sonar-operator (3.2.0)

---

operators/gitlab-operator-kubernetes/1.12.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.12.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.12.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.12.1)

---

operators/pulp-operator/1.0.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.0.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.0.0/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/pulp-operator/1.0.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.0.0/manifests/pulp-operator.clusterserviceversion.yaml
operators/pulp-operator/1.0.0/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.0.0/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.0.0/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.0.0/manifests/settings_v1_configmap.yaml
operators/pulp-operator/1.0.0/metadata/annotations.yaml
operators/pulp-operator/1.0.0/tests/scorecard/config.yaml

operator pulp-operator (1.0.0)

---

operators/dynatrace-operator/1.5.0/Dockerfile
operators/dynatrace-operator/1.5.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_role.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-extensions-controller_v1_serviceaccount.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-logmonitoring_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-logmonitoring_v1_serviceaccount.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-node-config-collector_v1_serviceaccount.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-opentelemetry-collector_v1_serviceaccount.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-telemetry-ingest_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-telemetry-ingest_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.5.0/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.5.0/metadata/annotations.yaml

operator dynatrace-operator (1.5.0)

---

operators/mongodb-atlas-kubernetes/2.8.1/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlascustomroles.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasnetworkcontainers.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasnetworkpeerings.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.8.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.8.1/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.8.1/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.8.1)

---

operators/knative-operator/1.18.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.18.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.18.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.18.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.18.0/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.18.0/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.18.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.18.0/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.18.0/manifests/knative-operator.v1.18.0.clusterserviceversion.yaml
operators/knative-operator/1.18.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.18.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.18.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.18.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.18.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.18.0/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.18.0/metadata/annotations.yaml
operators/knative-operator/1.18.0/tests/scorecard/config.yaml

operator knative-operator (1.18.0)

---

operators/dynatrace-operator/1.5.1/Dockerfile
operators/dynatrace-operator/1.5.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_role.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-extensions-controller_v1_serviceaccount.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-logmonitoring_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-logmonitoring_v1_serviceaccount.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-node-config-collector_v1_serviceaccount.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-opentelemetry-collector_v1_serviceaccount.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-telemetry-ingest_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-telemetry-ingest_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.5.1/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.5.1/metadata/annotations.yaml

operator dynatrace-operator (1.5.1)

---

operators/project-quay/3.12.9/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.9/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.9/metadata/annotations.yaml

Add 3.12.9 to community operators

operator [R] project-quay (3.12.9)

---

operators/project-quay/3.11.10/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.11.10/manifests/quayregistries.crd.yaml
operators/project-quay/3.11.10/metadata/annotations.yaml

Add 3.11.10 to community operators

operator [R] project-quay (3.11.10 3.14.0)

---

operators/project-quay/3.10.10/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.10/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.10/metadata/annotations.yaml

Add 3.10.10 to community operators

operator project-quay (3.10.10)

---

operators/mongodb-kubernetes/1.0.0/bundle.Dockerfile
operators/mongodb-kubernetes/1.0.0/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodb-kubernetes-appdb_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodb-kubernetes-database-pods_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodb-kubernetes-operator-service_v1_service.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodb-kubernetes-ops-manager_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodb-kubernetes.clusterserviceversion.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-kubernetes/1.0.0/manifests/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
operators/mongodb-kubernetes/1.0.0/metadata/annotations.yaml
operators/mongodb-kubernetes/1.0.0/tests/scorecard/config.yaml
operators/mongodb-kubernetes/ci.yaml

operator [N] [CI] mongodb-kubernetes (1.0.0)

---

operators/pubsubplus-eventbroker-operator/1.3.0/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
operators/pubsubplus-eventbroker-operator/1.3.0/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
operators/pubsubplus-eventbroker-operator/1.3.0/metadata/annotations.yaml
operators/pubsubplus-eventbroker-operator/1.3.0/tests/scorecard/config.yaml

operator pubsubplus-eventbroker-operator (1.3.0)

---

operators/gitlab-operator-kubernetes/1.12.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/1.12.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/1.12.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (1.12.2)

---

operators/ndb-operator/1.8.1/bundle.Dockerfile
operators/ndb-operator/1.8.1/manifests/mysql.oracle.com_ndbclusters.yaml
operators/ndb-operator/1.8.1/manifests/ndb-operator-svc_v1_service.yaml
operators/ndb-operator/1.8.1/manifests/ndb-operator-webhook-service_v1_service.yaml
operators/ndb-operator/1.8.1/manifests/ndb-operator.clusterserviceversion.yaml
operators/ndb-operator/1.8.1/metadata/annotations.yaml

operator ndb-operator (1.8.1)

---

operators/project-quay/3.10.10/manifests/quay-operator.clusterserviceversion.yaml

Add 3.10.10 to community operators

operator [O] project-quay (3.10.10)

---

operators/hawtio-operator/1.3.0/manifests/hawt.io_hawtios.yaml
operators/hawtio-operator/1.3.0/manifests/hawtio-operator.clusterserviceversion.yaml
operators/hawtio-operator/1.3.0/metadata/annotations.yaml
operators/hawtio-operator/1.3.0/tests/scorecard/config.yaml

operator hawtio-operator (1.3.0)

---

operators/wildfly/1.1.2/manifests/wildfly-operator.v1.1.2.clusterserviceversion.yaml
operators/wildfly/1.1.2/manifests/wildflyservers.wildfly.org.crd.yaml
operators/wildfly/1.1.2/metadata/annotations.yaml

Upgrade WildFly Operator to 1.1.2
Signed-off-by: Yeray Borges <yborgess@redhat.com>

operator wildfly (1.1.2)

---

operators/cass-operator-community/1.24.0/manifests/cass-operator-controller-manager-metrics-service_v1_service.yaml
operators/cass-operator-community/1.24.0/manifests/cass-operator-manager-config_v1_configmap.yaml
operators/cass-operator-community/1.24.0/manifests/cass-operator-webhook-service_v1_service.yaml
operators/cass-operator-community/1.24.0/manifests/cass-operator.clusterserviceversion.yaml
operators/cass-operator-community/1.24.0/manifests/cassandra.datastax.com_cassandradatacenters.yaml
operators/cass-operator-community/1.24.0/manifests/control.k8ssandra.io_cassandratasks.yaml
operators/cass-operator-community/1.24.0/manifests/control.k8ssandra.io_scheduledtasks.yaml
operators/cass-operator-community/1.24.0/metadata/annotations.yaml
operators/cass-operator-community/1.24.0/tests/scorecard/config.yaml

operator cass-operator-community (1.24.0)

---

operators/intel-device-plugins-operator/0.32.1/bundle.Dockerfile
operators/intel-device-plugins-operator/0.32.1/manifests/deviceplugin.intel.com_dlbdeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.1/manifests/deviceplugin.intel.com_dsadeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.1/manifests/deviceplugin.intel.com_fpgadeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.1/manifests/deviceplugin.intel.com_gpudeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.1/manifests/deviceplugin.intel.com_iaadeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.1/manifests/deviceplugin.intel.com_qatdeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.1/manifests/deviceplugin.intel.com_sgxdeviceplugins.yaml
operators/intel-device-plugins-operator/0.32.1/manifests/fpga.intel.com_acceleratorfunctions.yaml
operators/intel-device-plugins-operator/0.32.1/manifests/fpga.intel.com_fpgaregions.yaml
operators/intel-device-plugins-operator/0.32.1/manifests/intel-device-plugins-operator.clusterserviceversion.yaml
operators/intel-device-plugins-operator/0.32.1/metadata/annotations.yaml

operator intel-device-plugins-operator (0.32.1)

---

operators/mongodb-kubernetes/1.0.1/bundle.Dockerfile
operators/mongodb-kubernetes/1.0.1/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodb-kubernetes-appdb_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodb-kubernetes-database-pods_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodb-kubernetes-operator-service_v1_service.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodb-kubernetes-ops-manager_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodb-kubernetes.clusterserviceversion.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodb.com_mongodb.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-kubernetes/1.0.1/manifests/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
operators/mongodb-kubernetes/1.0.1/metadata/annotations.yaml
operators/mongodb-kubernetes/1.0.1/tests/scorecard/config.yaml

operator mongodb-kubernetes (1.0.1)

---

operators/gitlab-operator-kubernetes/2.0.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/2.0.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.0.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.0.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/2.0.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.0.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/2.0.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/2.0.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.0.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/2.0.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (2.0.0)

---

operators/grafana-operator/5.18.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.18.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.18.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.18.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanalibrarypanels.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanamutetimings.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafananotificationpolicyroutes.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafananotificationtemplates.yaml
operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.18.0/metadata/annotations.yaml

operator grafana-operator (5.18.0)

---

operators/multi-nic-cni-operator/1.0.3/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.0.4/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.0.5/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.1.0/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.0/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.1/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.2/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.3/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.4/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.5/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.6/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.7/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.3.0/manifests/multi-nic-cni-operator.clusterserviceversion.yaml

operator [R] multi-nic-cni-operator (1.0.3 1.0.4 1.0.5 1.1.0 1.2.0 1.2.1 1.2.2 1.2.3 1.2.4 1.2.5 1.2.6 1.2.7 1.3.0)

---

operators/project-quay/3.13.5/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.13.5/manifests/quayregistries.crd.yaml
operators/project-quay/3.13.5/metadata/annotations.yaml

Add 3.13.5 to community operators

operator project-quay (3.13.5)

---

operators/project-quay/3.14.1/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.14.1/manifests/quayregistries.crd.yaml
operators/project-quay/3.14.1/metadata/annotations.yaml

Add 3.14.1 to community operators

operator project-quay (3.14.1)

---

operators/postgresql/5.8.2/manifests/postgresoperator.clusterserviceversion.yaml

operator [O] postgresql (5.8.2)

---

operators/gitlab-operator-kubernetes/2.0.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.0.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/2.0.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (2.0.1)

---

operators/dell-csm-operator/1.9.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
operators/dell-csm-operator/1.9.0/manifests/dell-csm-operator.v1.9.0.clusterserviceversion.yaml
operators/dell-csm-operator/1.9.0/metadata/annotations.yaml
operators/dell-csm-operator/1.9.0/tests/scorecard/config.yaml

operator dell-csm-operator (1.9.0)

---

operators/mongodb-kubernetes/1.1.0/bundle.Dockerfile
operators/mongodb-kubernetes/1.1.0/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb-kubernetes-appdb_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb-kubernetes-database-pods_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb-kubernetes-operator-service_v1_service.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb-kubernetes-ops-manager_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb-kubernetes.clusterserviceversion.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb.com_mongodbsearch.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-kubernetes/1.1.0/manifests/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
operators/mongodb-kubernetes/1.1.0/metadata/annotations.yaml
operators/mongodb-kubernetes/1.1.0/tests/scorecard/config.yaml

operator mongodb-kubernetes (1.1.0)

---

operators/multi-nic-cni-operator/1.2.4/bundle.Dockerfile
operators/multi-nic-cni-operator/1.2.4/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml
operators/multi-nic-cni-operator/1.2.4/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
operators/multi-nic-cni-operator/1.2.4/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/multi-nic-cni-operator/1.2.4/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_cidrs.yaml
operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_configs.yaml
operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_deviceclasses.yaml
operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_hostinterfaces.yaml
operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_ippools.yaml
operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_multinicnetworks.yaml
operators/multi-nic-cni-operator/1.2.4/metadata/annotations.yaml
operators/multi-nic-cni-operator/1.2.4/tests/scorecard/config.yaml

operator multi-nic-cni-operator (1.2.4)

---

operators/multi-nic-cni-operator/1.2.5/bundle.Dockerfile
operators/multi-nic-cni-operator/1.2.5/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml
operators/multi-nic-cni-operator/1.2.5/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
operators/multi-nic-cni-operator/1.2.5/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/multi-nic-cni-operator/1.2.5/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_cidrs.yaml
operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_configs.yaml
operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_deviceclasses.yaml
operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_hostinterfaces.yaml
operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_ippools.yaml
operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_multinicnetworks.yaml
operators/multi-nic-cni-operator/1.2.5/metadata/annotations.yaml
operators/multi-nic-cni-operator/1.2.5/tests/scorecard/config.yaml

operator multi-nic-cni-operator (1.2.5)

---

operators/multi-nic-cni-operator/1.2.6/bundle.Dockerfile
operators/multi-nic-cni-operator/1.2.6/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
operators/multi-nic-cni-operator/1.2.6/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.6/manifests/multinic.fms.io_cidrs.yaml
operators/multi-nic-cni-operator/1.2.6/manifests/multinic.fms.io_configs.yaml
operators/multi-nic-cni-operator/1.2.6/manifests/multinic.fms.io_deviceclasses.yaml
operators/multi-nic-cni-operator/1.2.6/manifests/multinic.fms.io_hostinterfaces.yaml
operators/multi-nic-cni-operator/1.2.6/manifests/multinic.fms.io_ippools.yaml
operators/multi-nic-cni-operator/1.2.6/manifests/multinic.fms.io_multinicnetworks.yaml
operators/multi-nic-cni-operator/1.2.6/metadata/annotations.yaml
operators/multi-nic-cni-operator/1.2.6/tests/scorecard/config.yaml

operator multi-nic-cni-operator (1.2.6)

---

operators/multi-nic-cni-operator/1.3.0/bundle.Dockerfile
operators/multi-nic-cni-operator/1.3.0/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml
operators/multi-nic-cni-operator/1.3.0/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
operators/multi-nic-cni-operator/1.3.0/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/multi-nic-cni-operator/1.3.0/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_cidrs.yaml
operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_configs.yaml
operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_deviceclasses.yaml
operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_hostinterfaces.yaml
operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_ippools.yaml
operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_multinicnetworks.yaml
operators/multi-nic-cni-operator/1.3.0/metadata/annotations.yaml
operators/multi-nic-cni-operator/1.3.0/tests/scorecard/config.yaml

operator multi-nic-cni-operator (1.3.0)

---

operators/apicurio-registry-3/3.0.8/bundle.Dockerfile
operators/apicurio-registry-3/3.0.8/manifests/apicurio-registry-3.clusterserviceversion.yaml
operators/apicurio-registry-3/3.0.8/manifests/registry.apicur.io_apicurioregistries3.yaml
operators/apicurio-registry-3/3.0.8/metadata/annotations.yaml

operator apicurio-registry-3 (3.0.8)

---

operators/keda/2.17.1/manifests/eventing.keda.sh_cloudeventsources.yaml
operators/keda/2.17.1/manifests/eventing.keda.sh_clustercloudeventsources.yaml
operators/keda/2.17.1/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.17.1/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.17.1/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.17.1/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.17.1/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.17.1/manifests/keda.v2.17.1.clusterserviceversion.yaml
operators/keda/2.17.1/metadata/annotations.yaml

operator keda (2.17.1)

---

operators/project-quay/3.11.11/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.11.11/manifests/quayregistries.crd.yaml
operators/project-quay/3.11.11/metadata/annotations.yaml

Add 3.11.11 to community operators

operator project-quay (3.11.11)

---

operators/kuadrant-operator/0.11.1/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
operators/kuadrant-operator/0.11.1/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/kuadrant-operator/0.11.1/manifests/kuadrant-operator-metrics_v1_service.yaml
operators/kuadrant-operator/0.11.1/manifests/kuadrant-operator.clusterserviceversion.yaml
operators/kuadrant-operator/0.11.1/manifests/kuadrant.io_authpolicies.yaml
operators/kuadrant-operator/0.11.1/manifests/kuadrant.io_dnspolicies.yaml
operators/kuadrant-operator/0.11.1/manifests/kuadrant.io_kuadrants.yaml
operators/kuadrant-operator/0.11.1/manifests/kuadrant.io_ratelimitpolicies.yaml
operators/kuadrant-operator/0.11.1/manifests/kuadrant.io_tlspolicies.yaml
operators/kuadrant-operator/0.11.1/metadata/annotations.yaml
operators/kuadrant-operator/0.11.1/metadata/dependencies.yaml

Adding deprecation note in favor of https://docs.kuadrant.io/
--

operator kuadrant-operator (v0.11.1)

---

operators/klusterlet/1.0.0/manifests/klusterlet.clusterserviceversion.yaml
operators/klusterlet/1.0.0/manifests/operator.open-cluster-management.io_klusterlets.yaml
operators/klusterlet/1.0.0/metadata/annotations.yaml

operator klusterlet (1.0.0)

---

operators/dapr-kubernetes-operator/0.0.10/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
operators/dapr-kubernetes-operator/0.0.10/manifests/operator.dapr.io_daprcontrolplanes.yaml
operators/dapr-kubernetes-operator/0.0.10/manifests/operator.dapr.io_daprcruiscontrols.yaml
operators/dapr-kubernetes-operator/0.0.10/manifests/operator.dapr.io_daprinstances.yaml
operators/dapr-kubernetes-operator/0.0.10/metadata/annotations.yaml
operators/dapr-kubernetes-operator/0.0.10/tests/scorecard/config.yaml

operator dapr-kubernetes-operator (0.0.10)

---

operators/gitlab-operator-kubernetes/2.1.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.1.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/2.1.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (2.1.0)

---

operators/skupper-operator/1.9.2/manifests/skupper-operator.v1.9.2.clusterserviceversion.yaml
operators/skupper-operator/1.9.2/metadata/annotations.yaml
operators/skupper-operator/ci.yaml

operator [CI] skupper-operator (1.9.2)

---

operators/project-quay/3.10.11/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.11/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.11/metadata/annotations.yaml

Add 3.10.11 to community operators

operator project-quay (3.10.11)

---

operators/rabbitmq-cluster-operator/2.13.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.13.0/manifests/rabbitmq-cluster-operator.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.13.0/manifests/rabbitmq.com_rabbitmqcluster.yaml
operators/rabbitmq-cluster-operator/2.13.0/metadata/annotations.yaml
operators/rabbitmq-cluster-operator/ci.yaml

operator [CI] rabbitmq-cluster-operator (2.13.0)

---

operators/rabbitmq-cluster-operator/2.14.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.14.0/manifests/rabbitmq-cluster-operator.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.14.0/manifests/rabbitmq.com_rabbitmqcluster.yaml
operators/rabbitmq-cluster-operator/2.14.0/metadata/annotations.yaml

Update operator rabbitmq-cluster-operator (2.14.0)

operator rabbitmq-cluster-operator (2.14.0)

---

operators/mongodb-atlas-kubernetes/2.9.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlascustomroles.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasnetworkcontainers.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasnetworkpeerings.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasthirdpartyintegrations.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.9.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.9.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.9.0/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.9.0)

---

operators/bpfman-operator/ci.yaml

Two of the maintainers are no longer working on the project, so remove them and add two replacement maintainers as reviewers.
--

operator [CI] bpfman-operator

---

operators/rabbitmq-cluster-operator/2.15.0/bundle.Dockerfile
operators/rabbitmq-cluster-operator/2.15.0/manifests/rabbitmq-cluster-operator.clusterserviceversion.yaml
operators/rabbitmq-cluster-operator/2.15.0/manifests/rabbitmq.com_rabbitmqcluster.yaml
operators/rabbitmq-cluster-operator/2.15.0/metadata/annotations.yaml

Update operator rabbitmq-cluster-operator (2.15.0)

operator rabbitmq-cluster-operator (2.15.0)

---

operators/moodle-operator/0.6.31/manifests/m4e.krestomat.io_moodles.yaml
operators/moodle-operator/0.6.31/manifests/m4e.krestomat.io_nginxes.yaml
operators/moodle-operator/0.6.31/manifests/m4e.krestomat.io_phpfpms.yaml
operators/moodle-operator/0.6.31/manifests/m4e.krestomat.io_routines.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator-controller-manager-metrics-service_v1_service.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator-moodle-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator-moodle-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator-nginx-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator-nginx-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator-phpfpm-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator-phpfpm-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator-routine-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator-routine-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/moodle-operator/0.6.31/manifests/moodle-operator.clusterserviceversion.yaml
operators/moodle-operator/0.6.31/metadata/annotations.yaml
operators/moodle-operator/0.6.31/tests/scorecard/config.yaml

operator moodle-operator (0.6.31)

---

operators/postgres-operator-krestomatio/0.3.25/manifests/postgres-operator-controller-manager-metrics-service_v1_service.yaml
operators/postgres-operator-krestomatio/0.3.25/manifests/postgres-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/postgres-operator-krestomatio/0.3.25/manifests/postgres-operator-postgres-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/postgres-operator-krestomatio/0.3.25/manifests/postgres-operator-postgres-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/postgres-operator-krestomatio/0.3.25/manifests/postgres-operator.clusterserviceversion.yaml
operators/postgres-operator-krestomatio/0.3.25/manifests/postgres.krestomat.io_postgres.yaml
operators/postgres-operator-krestomatio/0.3.25/metadata/annotations.yaml
operators/postgres-operator-krestomatio/0.3.25/tests/scorecard/config.yaml

operator postgres-operator-krestomatio (0.3.25)

---

operators/nfs-operator/0.4.25/manifests/nfs-operator-controller-manager-metrics-service_v1_service.yaml
operators/nfs-operator/0.4.25/manifests/nfs-operator-ganesha-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nfs-operator/0.4.25/manifests/nfs-operator-ganesha-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nfs-operator/0.4.25/manifests/nfs-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nfs-operator/0.4.25/manifests/nfs-operator-routine-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nfs-operator/0.4.25/manifests/nfs-operator-routine-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/nfs-operator/0.4.25/manifests/nfs-operator.clusterserviceversion.yaml
operators/nfs-operator/0.4.25/manifests/nfs.krestomat.io_ganeshas.yaml
operators/nfs-operator/0.4.25/manifests/nfs.krestomat.io_routines.yaml
operators/nfs-operator/0.4.25/metadata/annotations.yaml
operators/nfs-operator/0.4.25/tests/scorecard/config.yaml

operator nfs-operator (0.4.25)

---

operators/mongodb-atlas-kubernetes/2.9.1/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlascustomroles.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasnetworkcontainers.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasnetworkpeerings.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasthirdpartyintegrations.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.9.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.9.1/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.9.1/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.9.1)

---

operators/trident-operator/25.6.0/manifests/trident-operator.v25.6.0.clusterserviceversion.yaml
operators/trident-operator/25.6.0/manifests/trident.netapp.io_tridentconfigurators_crd.yaml
operators/trident-operator/25.6.0/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
operators/trident-operator/25.6.0/metadata/annotations.yaml

operator trident-operator (25.6.0)

---

operators/percona-server-mongodb-operator/1.20.1/manifests/percona-server-mongodb-operator.clusterserviceversion.yaml
operators/percona-server-mongodb-operator/1.20.1/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.20.1/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.20.1/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml
operators/percona-server-mongodb-operator/1.20.1/metadata/annotations.yaml

operator percona-server-mongodb-operator (1.20.1)

---

operators/mongodb-kubernetes/1.2.0/bundle.Dockerfile
operators/mongodb-kubernetes/1.2.0/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb-kubernetes-appdb_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb-kubernetes-database-pods_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb-kubernetes-operator-service_v1_service.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb-kubernetes-ops-manager_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb-kubernetes.clusterserviceversion.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb.com_clustermongodbroles.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb.com_mongodbsearch.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-kubernetes/1.2.0/manifests/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
operators/mongodb-kubernetes/1.2.0/metadata/annotations.yaml
operators/mongodb-kubernetes/1.2.0/tests/scorecard/config.yaml

operator mongodb-kubernetes (1.2.0)

---

operators/netobserv-operator/1.6.3-community/manifests/flows.netobserv.io_flowcollectors.yaml
operators/netobserv-operator/1.6.3-community/manifests/flows.netobserv.io_flowmetrics.yaml
operators/netobserv-operator/1.6.3-community/manifests/netobserv-manager-config_v1_configmap.yaml
operators/netobserv-operator/1.6.3-community/manifests/netobserv-metrics-service_v1_service.yaml
operators/netobserv-operator/1.6.3-community/manifests/netobserv-operator.clusterserviceversion.yaml
operators/netobserv-operator/1.6.3-community/manifests/netobserv-webhook-service_v1_service.yaml
operators/netobserv-operator/1.6.3-community/metadata/annotations.yaml

operator netobserv-operator (1.6.3-community)

---

operators/keda/2.17.2/manifests/eventing.keda.sh_cloudeventsources.yaml
operators/keda/2.17.2/manifests/eventing.keda.sh_clustercloudeventsources.yaml
operators/keda/2.17.2/manifests/keda.sh_clustertriggerauthentications.yaml
operators/keda/2.17.2/manifests/keda.sh_kedacontrollers.yaml
operators/keda/2.17.2/manifests/keda.sh_scaledjobs.yaml
operators/keda/2.17.2/manifests/keda.sh_scaledobjects.yaml
operators/keda/2.17.2/manifests/keda.sh_triggerauthentications.yaml
operators/keda/2.17.2/manifests/keda.v2.17.2.clusterserviceversion.yaml
operators/keda/2.17.2/metadata/annotations.yaml

operator keda (2.17.2)

---

operators/multi-nic-cni-operator/1.2.8/bundle.Dockerfile
operators/multi-nic-cni-operator/1.2.8/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
operators/multi-nic-cni-operator/1.2.8/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
operators/multi-nic-cni-operator/1.2.8/manifests/multinic.fms.io_cidrs.yaml
operators/multi-nic-cni-operator/1.2.8/manifests/multinic.fms.io_configs.yaml
operators/multi-nic-cni-operator/1.2.8/manifests/multinic.fms.io_deviceclasses.yaml
operators/multi-nic-cni-operator/1.2.8/manifests/multinic.fms.io_hostinterfaces.yaml
operators/multi-nic-cni-operator/1.2.8/manifests/multinic.fms.io_ippools.yaml
operators/multi-nic-cni-operator/1.2.8/manifests/multinic.fms.io_multinicnetworks.yaml
operators/multi-nic-cni-operator/1.2.8/metadata/annotations.yaml
operators/multi-nic-cni-operator/1.2.8/tests/scorecard/config.yaml

operator multi-nic-cni-operator (1.2.8)

---

operators/susql-operator/0.0.34/manifests/susql-operator-controller-manager-metrics-service_v1_service.yaml
operators/susql-operator/0.0.34/manifests/susql-operator-labelgroup-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.34/manifests/susql-operator-labelgroup-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.34/manifests/susql-operator-metrics-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.34/manifests/susql-operator-metrics-auth-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/susql-operator/0.0.34/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/susql-operator/0.0.34/manifests/susql-operator.clusterserviceversion.yaml
operators/susql-operator/0.0.34/manifests/susql.ibm.com_labelgroups.yaml
operators/susql-operator/0.0.34/metadata/annotations.yaml
operators/susql-operator/0.0.34/tests/scorecard/config.yaml

operator susql-operator (0.0.34)

---

operators/wildfly/1.1.3/manifests/wildfly-operator.v1.1.3.clusterserviceversion.yaml
operators/wildfly/1.1.3/manifests/wildflyservers.wildfly.org.crd.yaml
operators/wildfly/1.1.3/metadata/annotations.yaml

WildFly Operator 1.1.3
Signed-off-by: Yeray Borges <yborgess@redhat.com>

operator wildfly (1.1.3)

---

operators/rabbitmq-messaging-topology-operator/1.15.0/bundle.Dockerfile
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq-messaging-topology-operator.clusterserviceversion.yaml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_binding.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_exchange.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_federation.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_operatorpolicy.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_permission.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_policy.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_queue.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_schemareplication.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_shovel.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_superstream.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_topicpermission.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_user.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/manifests/rabbitmq.com_vhost.yml
operators/rabbitmq-messaging-topology-operator/1.15.0/metadata/annotations.yaml
operators/rabbitmq-messaging-topology-operator/1.15.0/metadata/dependencies.yaml

Update operator messaging-topology-operator 1.15.0

operator rabbitmq-messaging-topology-operator (1.15.0)

---

operators/project-quay/3.15.0/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.15.0/manifests/quayregistries.crd.yaml
operators/project-quay/3.15.0/metadata/annotations.yaml
operators/project-quay/3.9.12/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.12/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.12/metadata/annotations.yaml

Add 3.15.0 to community operators

operator [R] project-quay (3.15.0 3.9.12)

---

operators/project-quay/3.9.12/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.12/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.12/metadata/annotations.yaml
operators/project-quay/3.9.13/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.13/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.13/metadata/annotations.yaml

Add 3.9.13 to community operators

operator [R] project-quay (3.9.12 3.9.13)

---

operators/gitlab-operator-kubernetes/2.2.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/2.2.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.2.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.2.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/2.2.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.2.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/2.2.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/2.2.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.2.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/2.2.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (2.2.0)

---

operators/project-quay/3.14.3/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.14.3/manifests/quayregistries.crd.yaml
operators/project-quay/3.14.3/metadata/annotations.yaml

Add 3.14.3 to community operators

operator [R] project-quay (3.14.3 3.15.0)

---

operators/dynatrace-operator/1.6.1/Dockerfile
operators/dynatrace-operator/1.6.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.6.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.6.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.6.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.6.1/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.6.1/metadata/annotations.yaml

operator dynatrace-operator (1.6.1)

---

operators/mariadb-operator/25.8.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/25.8.0/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/25.8.0/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/25.8.0/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/25.8.0/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/25.8.0/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/25.8.0/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/25.8.0/manifests/k8s.mariadb.com_physicalbackups.yaml
operators/mariadb-operator/25.8.0/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/25.8.0/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/25.8.0/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/25.8.0/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/25.8.0/metadata/annotations.yaml
operators/mariadb-operator/25.8.0/tests/scorecard/config.yaml

Added operator mariadb-operator (25.8.0)

operator mariadb-operator (25.8.0)

---

operators/gitlab-operator-kubernetes/2.2.1/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/2.2.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.2.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.2.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/2.2.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.2.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/2.2.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/2.2.1/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.2.1/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/2.2.1/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (2.2.1)

---

operators/quay-api-operator/1.2.0/manifests/quay-api-operator-controller-manager-metrics-service_v1_service.yaml
operators/quay-api-operator/1.2.0/manifests/quay-api-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/quay-api-operator/1.2.0/manifests/quay-api-operator.clusterserviceversion.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_apitokens.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_applications.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_defaultperms.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_dockertokens.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_firstusers.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_manifestlabels.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_messages.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_notifications.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_organizationprunes.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_organizations.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_proxycaches.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_quotas.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_repositories.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_repositorymirrors.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_repositoryprunes.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_robots.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_tags.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_teamldaps.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_teamoidcs.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_teams.yaml
operators/quay-api-operator/1.2.0/manifests/quay.herve4m.github.io_users.yaml
operators/quay-api-operator/1.2.0/metadata/annotations.yaml
operators/quay-api-operator/1.2.0/tests/scorecard/config.yaml

operator quay-api-operator (1.2.0)

---

operators/mariadb-operator/25.8.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/25.8.1/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/25.8.1/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/25.8.1/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/25.8.1/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/25.8.1/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/25.8.1/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/25.8.1/manifests/k8s.mariadb.com_physicalbackups.yaml
operators/mariadb-operator/25.8.1/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/25.8.1/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/25.8.1/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/25.8.1/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/25.8.1/metadata/annotations.yaml
operators/mariadb-operator/25.8.1/tests/scorecard/config.yaml

Added operator mariadb-operator (25.8.1)

operator mariadb-operator (25.8.1)

---

operators/knative-operator/1.19.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.19.0/manifests/knative-eventing-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.19.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.19.0/manifests/knative-eventing-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.19.0/manifests/knative-operator-config-logging_v1_configmap.yaml
operators/knative-operator/1.19.0/manifests/knative-operator-config-observability_v1_configmap.yaml
operators/knative-operator/1.19.0/manifests/knative-operator-operator-webhook-certs_v1_secret.yaml
operators/knative-operator/1.19.0/manifests/knative-operator-operator-webhook_v1_service.yaml
operators/knative-operator/1.19.0/manifests/knative-operator.v1.19.0.clusterserviceversion.yaml
operators/knative-operator/1.19.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.19.0/manifests/knative-serving-operator-aggregated-stable_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.19.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/knative-operator/1.19.0/manifests/knative-serving-operator-aggregated_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/knative-operator/1.19.0/manifests/knativeeventings.operator.knative.dev.crd.yaml
operators/knative-operator/1.19.0/manifests/knativeservings.operator.knative.dev.crd.yaml
operators/knative-operator/1.19.0/metadata/annotations.yaml
operators/knative-operator/1.19.0/tests/scorecard/config.yaml

operator knative-operator (1.19.0)

---

operators/shipwright-operator/0.16.0/manifests/operator.shipwright.io_shipwrightbuilds.yaml
operators/shipwright-operator/0.16.0/manifests/shipwright-operator-manager-config_v1_configmap.yaml
operators/shipwright-operator/0.16.0/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/shipwright-operator/0.16.0/manifests/shipwright-operator-metrics-service_v1_service.yaml
operators/shipwright-operator/0.16.0/manifests/shipwright-operator.clusterserviceversion.yaml
operators/shipwright-operator/0.16.0/metadata/annotations.yaml
operators/shipwright-operator/0.16.0/tests/scorecard/config.yaml

operator shipwright-operator (0.16.0)

---

operators/shipwright-operator/ci.yaml

- Adding psrvere to ci.yaml file to help release shipwright operator to Operator Hub
--

operator [CI] shipwright-operator

---

operators/mariadb-operator/25.8.2/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_physicalbackups.yaml
operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/25.8.2/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/25.8.2/metadata/annotations.yaml
operators/mariadb-operator/25.8.2/tests/scorecard/config.yaml

Added operator mariadb-operator (25.8.2)

operator mariadb-operator (25.8.2)

---

operators/project-quay/3.12.11/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.12.11/manifests/quayregistries.crd.yaml
operators/project-quay/3.12.11/metadata/annotations.yaml

Add 3.12.11 to community operators

operator project-quay (3.12.11)

---

operators/clickhouse/0.25.3/manifests/clickhouse-operator.v0.25.3.clusterserviceversion.yaml
operators/clickhouse/0.25.3/manifests/clickhouseinstallations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.25.3/manifests/clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.25.3/manifests/clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
operators/clickhouse/0.25.3/manifests/clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
operators/clickhouse/0.25.3/metadata/annotations.yaml

operator clickhouse (0.25.3)

---

operators/flux-operator/0.27.0/manifests/flux-operator.clusterserviceversion.yaml
operators/flux-operator/0.27.0/manifests/flux-operator.service.yaml
operators/flux-operator/0.27.0/manifests/fluxinstances.fluxcd.controlplane.io.crd.yaml
operators/flux-operator/0.27.0/manifests/fluxreports.fluxcd.controlplane.io.crd.yaml
operators/flux-operator/0.27.0/manifests/resourcesetinputproviders.fluxcd.controlplane.io.crd.yaml
operators/flux-operator/0.27.0/manifests/resourcesets.fluxcd.controlplane.io.crd.yaml
operators/flux-operator/0.27.0/metadata/annotations.yaml
operators/flux-operator/0.27.0/tests/scorecard/config.yaml

operator flux-operator (0.27.0)

---

operators/mariadb-operator/25.8.3/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_backups.yaml
operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_connections.yaml
operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_databases.yaml
operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_grants.yaml
operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_mariadbs.yaml
operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_maxscales.yaml
operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_physicalbackups.yaml
operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_restores.yaml
operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_sqljobs.yaml
operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_users.yaml
operators/mariadb-operator/25.8.3/manifests/mariadb-operator.clusterserviceversion.yaml
operators/mariadb-operator/25.8.3/metadata/annotations.yaml
operators/mariadb-operator/25.8.3/tests/scorecard/config.yaml

Added operator mariadb-operator (25.8.3)

operator mariadb-operator (25.8.3)

---

operators/project-quay/3.9.14/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.14/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.14/metadata/annotations.yaml

Add 3.9.14 to community operators

operator project-quay (3.9.14)

---

operators/gitlab-operator-kubernetes/2.2.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/2.2.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.2.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.2.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/2.2.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.2.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/2.2.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/2.2.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.2.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/2.2.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (2.2.2)

---

operators/apicurio-registry-3/3.0.12/bundle.Dockerfile
operators/apicurio-registry-3/3.0.12/manifests/apicurio-registry-3.clusterserviceversion.yaml
operators/apicurio-registry-3/3.0.12/manifests/registry.apicur.io_apicurioregistries3.yaml
operators/apicurio-registry-3/3.0.12/metadata/annotations.yaml

operator apicurio-registry-3 (3.0.12)

---

operators/project-quay/3.10.13/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.13/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.13/metadata/annotations.yaml

Add 3.10.13 to community operators

operator project-quay (3.10.13)

---

operators/project-quay/3.14.4/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.14.4/manifests/quayregistries.crd.yaml
operators/project-quay/3.14.4/metadata/annotations.yaml

Add 3.14.4 to community operators

operator project-quay (3.14.4)

---

operators/gitlab-operator-kubernetes/2.2.3/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/2.2.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.2.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.2.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/2.2.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.2.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/2.2.3/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/2.2.3/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.2.3/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/2.2.3/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (2.2.3)

---

operators/percona-xtradb-cluster-operator/1.18.0/manifests/percona-xtradb-cluster-operator.v1.18.0.clusterserviceversion.yaml
operators/percona-xtradb-cluster-operator/1.18.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.18.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.18.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
operators/percona-xtradb-cluster-operator/1.18.0/metadata/annotations.yaml

operator percona-xtradb-cluster-operator (1.18.0)

---

operators/grafana-operator/5.19.4/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.19.4/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.19.4/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.19.4/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanalibrarypanels.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanamutetimings.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafananotificationpolicyroutes.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafananotificationtemplates.yaml
operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.19.4/metadata/annotations.yaml

operator grafana-operator (5.19.4)

---

operators/gitlab-operator-kubernetes/2.3.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/2.3.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.3.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.3.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/2.3.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.3.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/2.3.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/2.3.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.3.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/2.3.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (2.3.0)

---

operators/cryostat-operator/4.0.2/manifests/cryostat-operator-cryostat-namespaced_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/4.0.2/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/4.0.2/manifests/cryostat-operator-manager-config_v1_configmap.yaml
operators/cryostat-operator/4.0.2/manifests/cryostat-operator-oauth-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/cryostat-operator/4.0.2/manifests/cryostat-operator-webhook-service_v1_service.yaml
operators/cryostat-operator/4.0.2/manifests/cryostat-operator.clusterserviceversion.yaml
operators/cryostat-operator/4.0.2/manifests/operator.cryostat.io_cryostats.yaml
operators/cryostat-operator/4.0.2/metadata/annotations.yaml
operators/cryostat-operator/4.0.2/tests/scorecard/config.yaml

operator cryostat-operator (4.0.2)

---

operators/infinispan/2.4.17/manifests/infinispan-operator-manager-config_v1_configmap.yaml
operators/infinispan/2.4.17/manifests/infinispan-operator.clusterserviceversion.yaml
operators/infinispan/2.4.17/manifests/infinispan.org_backups.yaml
operators/infinispan/2.4.17/manifests/infinispan.org_batches.yaml
operators/infinispan/2.4.17/manifests/infinispan.org_caches.yaml
operators/infinispan/2.4.17/manifests/infinispan.org_infinispans.yaml
operators/infinispan/2.4.17/manifests/infinispan.org_restores.yaml
operators/infinispan/2.4.17/metadata/annotations.yaml
operators/infinispan/2.4.17/tests/scorecard/config.yaml

operator infinispan (2.4.17)

---

operators/mongodb-kubernetes/1.3.0/bundle.Dockerfile
operators/mongodb-kubernetes/1.3.0/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb-kubernetes-appdb_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb-kubernetes-database-pods_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb-kubernetes-operator-service_v1_service.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb-kubernetes-ops-manager_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb-kubernetes.clusterserviceversion.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb.com_clustermongodbroles.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb.com_mongodbsearch.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-kubernetes/1.3.0/manifests/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
operators/mongodb-kubernetes/1.3.0/metadata/annotations.yaml
operators/mongodb-kubernetes/1.3.0/tests/scorecard/config.yaml

operator mongodb-kubernetes (1.3.0)

---

operators/cert-monitor-operator/0.1.0/manifests/cert-monitor-operator.clusterserviceversion.yaml
operators/cert-monitor-operator/0.1.0/manifests/certmonitor.nachoperator.io_certificatemonitors.yaml
operators/cert-monitor-operator/0.1.0/metadata/annotations.yaml

The Certificate Monitor Operator automatically monitors SSL/TLS certificates stored in Kubernetes secrets and sends notifications when they approach expiration. This operator helps prevent service outages caused by expired certificates by providing proactive monitoring and alerting.
More information: https://github.com/nachoperator/nacho-operators
- 🔍 **Automatic certificate monitoring**: Continuously scans TLS secrets across namespaces
- ⏰ **Configurable expiration thresholds**: Set custom warning periods (1-365 days before expiration)  
- 📢 **Multiple notification channels**: Slack webhooks and OpsGenie integration
- 🏷️ **Namespace-scoped monitoring**: Monitor certificates in specific namespaces
- 📊 **Rich status information**: Detailed status reporting with conditions and metrics
- 🔄 …

operator [N] cert-monitor-operator (0.1.0)

---

operators/gitlab-operator-kubernetes/2.3.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.3.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/2.3.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (2.3.2)

---

operators/mongodb-kubernetes/1.4.0/bundle.Dockerfile
operators/mongodb-kubernetes/1.4.0/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_role.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb-kubernetes-appdb_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb-kubernetes-appdb_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb-kubernetes-database-pods_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb-kubernetes-operator-service_v1_service.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb-kubernetes-ops-manager_v1_serviceaccount.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb-kubernetes.clusterserviceversion.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb.com_clustermongodbroles.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb.com_mongodb.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb.com_mongodbmulticluster.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb.com_mongodbsearch.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb.com_mongodbusers.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodb.com_opsmanagers.yaml
operators/mongodb-kubernetes/1.4.0/manifests/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
operators/mongodb-kubernetes/1.4.0/metadata/annotations.yaml
operators/mongodb-kubernetes/1.4.0/tests/scorecard/config.yaml

operator mongodb-kubernetes (1.4.0)

---

operators/tempo-operator/0.18.0/bundle.Dockerfile
operators/tempo-operator/0.18.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.18.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.18.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.18.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.18.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.18.0/manifests/tempo.grafana.com_tempomonolithics.yaml
operators/tempo-operator/0.18.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.18.0/metadata/annotations.yaml
operators/tempo-operator/0.18.0/tests/scorecard/config.yaml

Release tempo-operator `0.18.0`.

operator tempo-operator (0.18.0)

---

operators/gitlab-operator-kubernetes/2.4.0/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/2.4.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.4.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.4.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/2.4.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/2.4.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/2.4.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/2.4.0/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/2.4.0/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/2.4.0/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (2.4.0)

---

operators/pulp-operator/1.1.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
operators/pulp-operator/1.1.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
operators/pulp-operator/1.1.0/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/pulp-operator/1.1.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/pulp-operator/1.1.0/manifests/pulp-operator.clusterserviceversion.yaml
operators/pulp-operator/1.1.0/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
operators/pulp-operator/1.1.0/manifests/repo-manager.pulpproject.org_pulprestores.yaml
operators/pulp-operator/1.1.0/manifests/repo-manager.pulpproject.org_pulps.yaml
operators/pulp-operator/1.1.0/manifests/settings_v1_configmap.yaml
operators/pulp-operator/1.1.0/metadata/annotations.yaml
operators/pulp-operator/1.1.0/tests/scorecard/config.yaml

operator pulp-operator (1.1.0)

---

operators/camel-k/2.8.0/manifests/builds.camel.apache.org.crd.yaml
operators/camel-k/2.8.0/manifests/camel-k.v2.8.0.clusterserviceversion.yaml
operators/camel-k/2.8.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
operators/camel-k/2.8.0/manifests/integrationkits.camel.apache.org.crd.yaml
operators/camel-k/2.8.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
operators/camel-k/2.8.0/manifests/integrationprofiles.camel.apache.org.crd.yaml
operators/camel-k/2.8.0/manifests/integrations.camel.apache.org.crd.yaml
operators/camel-k/2.8.0/manifests/kamelets.camel.apache.org.crd.yaml
operators/camel-k/2.8.0/manifests/pipes.camel.apache.org.crd.yaml
operators/camel-k/2.8.0/metadata/annotations.yaml
operators/camel-k/2.8.0/tests/scorecard/config.yaml

operator camel-k (2.8.0)

---

operators/project-quay/3.14.5/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.14.5/manifests/quayregistries.crd.yaml
operators/project-quay/3.14.5/metadata/annotations.yaml

Add 3.14.5 to community operators

operator project-quay (3.14.5)

---

operators/project-quay/3.10.15/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.10.15/manifests/quayregistries.crd.yaml
operators/project-quay/3.10.15/metadata/annotations.yaml

Add 3.10.15 to community operators

operator project-quay (3.10.15)

---

operators/mongodb-atlas-kubernetes/2.11.0/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlascustomroles.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasnetworkcontainers.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasnetworkpeerings.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasorgsettings.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasthirdpartyintegrations.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.11.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.11.0/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.11.0/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.11.0)

---

operators/project-quay/3.9.16/manifests/quay-operator.clusterserviceversion.yaml
operators/project-quay/3.9.16/manifests/quayregistries.crd.yaml
operators/project-quay/3.9.16/metadata/annotations.yaml

Add 3.9.16 to community operators

operator project-quay (3.9.16)

---

operators/dynatrace-operator/1.7.1/Dockerfile
operators/dynatrace-operator/1.7.1/manifests/dynatrace-operator.clusterserviceversion.yaml
operators/dynatrace-operator/1.7.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
operators/dynatrace-operator/1.7.1/manifests/dynatrace-webhook_v1_service.yaml
operators/dynatrace-operator/1.7.1/manifests/dynatrace.com_dynakubes.yaml
operators/dynatrace-operator/1.7.1/manifests/dynatrace.com_edgeconnects.yaml
operators/dynatrace-operator/1.7.1/metadata/annotations.yaml

operator dynatrace-operator (1.7.1)

---

operators/mongodb-atlas-kubernetes/2.11.1/bundle.Dockerfile
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlascustomroles.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasnetworkcontainers.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasnetworkpeerings.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasorgsettings.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasprojects.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasteams.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/atlas.mongodb.com_atlasthirdpartyintegrations.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
operators/mongodb-atlas-kubernetes/2.11.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/mongodb-atlas-kubernetes/2.11.1/metadata/annotations.yaml
operators/mongodb-atlas-kubernetes/2.11.1/tests/scorecard/config.yaml

operator mongodb-atlas-kubernetes (2.11.1)
